pcieutil/main.py
scripts/db_migrator.py
scripts/natconfig
scripts/natshow
show/bgp_frr_v4.py
show/interfaces/portchannel.py
utilities_common/bgp_util.py

Clean up some alerts which were detected by LGTM tool

Clean up LGTM alerts

---

acl_loader/main.py
config/config_mgmt.py
config/main.py
config/nat.py
fdbutil/filter_fdb_entries.py
fwutil/lib.py
pfcwd/main.py
scripts/aclshow
scripts/configlet
scripts/db_migrator.py
scripts/fast-reboot-dump.py
scripts/intfutil
scripts/neighbor_advertiser
scripts/pcmping
scripts/sonic_sku_create.py
scripts/update_json.py
show/fgnhg.py
show/interfaces/__init__.py
show/main.py
show/vlan.py
tests/config_mgmt_test.py
tests/mock_tables/dbconnector.py
utilities_common/bgp_util.py
utilities_common/cli.py

After conversion to Python 3 using the 2to3 tool, all calls to `dict.keys()` and `dict.values()` were converted to lists. In the instances where the returned view objects from these calls are iterated over, there is no need to convert to a list, so I removed those.
Also, when iterating over the keys of a dictionary, one need not call `dict.keys()`, one can simply iterate over the dictionary as `for key in dict:`, so I cleaned those up as well.
Also remove some unnecessary parentheses.

Remove unnecessary conversions to list() and calls to dict.keys()

---

scripts/configlet
scripts/portconfig

Replace calls to `dict.has_key()` with `in`. It appears the `2to3` tool missed these.

[configlet][portconfig] Remove calls to dict.has_key() which is not available in Python 3

---

scripts/fast-reboot

Fixes https://github.com/Azure/sonic-buildimage/issues/5980
One of the logging statements during `warm-reboot` incorrectly prints `fast-reboot`.
Remove hard-coded `fast-reboot` with `REBOOT_TYPE` variable
Modified the script in device, and tested that logging is corrected:
```
admin@sonic-device:~$ sudo warm-reboot -vvv
Thu 19 Nov 2020 08:23:46 PM UTC Pausing orchagent ...
Thu 19 Nov 2020 08:23:47 PM UTC Collecting logs to check ssd health before fast-reboot...
...
...
Thu 19 Nov 2020 08:24:13 PM UTC Enabling Watchdog before warm-reboot
```
```
admin@sonic-device:~$ sudo …
```

Cosmetic fix - replace hard-coded fast-reboot with REBOOT_TYPE variable

---

acl_loader/main.py

In Python 3, `sort()` takes no positional arguments, only keyword arguments. Fix acl-loader to comply.
Fixes vsimage build failure in https://github.com/Azure/sonic-buildimage/pull/5926

[acl-loader] Make list sorting compliant with Python 3

---

scripts/natshow
scripts/route_check.py
scripts/sonic-kdump-config
show/main.py
utilities_common/cli.py

Now that the package is built as Python 3, all strings are unicode by default and `str.decode()` no longer exists.

Remove unnecessary calls to str.decode() now that the package is Python 3

---

scripts/fast-reboot

There is a issue for counters after warm-reboot:
If I clear counters by command "sonic-clear counters", then execute 'warm-reboot' and whenSONiC is restart, the counters showed with command "show interface counters" is still old counters before "sonic-clear". It is not the right counters because the counters file in '/tmp' is lost in warm-reboot process.
I fixed it by saving '/tmp/portstat-0' folders in '/host/' before executing 'warm-reboot', and restore the counters folders back to '/tmp/' after warm-reboot process is finished (in pull request Azure/sonic-buildimage#5346 ).
Clear counters by command 'sonic-clear'
sonic-clear counters
sonic-clear dropcounters
sonic-clear pfccounters
sonic-clear queuecounters
sonic-clear …

fix error: interface counters is mismatch after warm-reboot

---

utilities_common/netstat.py

Fixed "portstat" rate and utilization issue.
Changed size factor from 1024 to 1000 for rate throughput calculation.
Pls check the diff.
"portstat",  "portstat -a"
IFACE STATE RX_OK RX_BPS RX_UTIL RX_ERR RX_DRP RX_OVR TX_OK TX_BPS TX_UTIL TX_ERR TX_DRP TX_OVR
Ethernet41 U 353,628,250 98.67 MB/s 1.93% 0 0 0 353,660,334 98.67 MB/s 1.93% 0 0 0
FACE STATE RX_OK RX_BPS RX_UTIL RX_ERR RX_DRP RX_OVR TX_OK TX_BPS TX_UTIL TX_ERR TX_DRP TX_OVR
Ethernet2 U 5,065,263,485 124.98 MB/s 99.99% 0 0 0 113 7.63 B/s 0.00% 0 0 0

Fixed porstat rate and util issues

---

scripts/generate_dump

Signed-off-by: Sabareesh Kumar Anandan <sanandan@marvell.com>
generate_dump fails if some files/directories are not found.
Added checks to ignore files/directories that are not present while generating the dump.
Generated dump using the script and verified it.

[generate_dump] Ignoring file/directory not found Errors

---

acl_loader/main.py
fwutil/lib.py
scripts/decode-syseeprom

In Python 3, all strings are unicode by default. There is no need to encode strings to bytes.
Fixes vsimage check build failure in Azure/sonic-buildimage#5926, due to caclmgrd test failing because acl-loader was encoding the table names to bytes and comparing them against strings, thus failing to match table names and therefore failing to load ACL rules.
Also fix Python 3 deprecation warning in decode-syseeprom, as the `imp` module is deprecated in favor of `importlib`

Remove unnecessary calls to str.encode() now that the package is Python 3; Fix deprecation warning

---

config/config_mgmt.py

[config_mgmt.py]: Remove sort_data call, we do not need it now.
Backend handles unsorted Port creation.
Signed-off-by: Praveen Chaudhary<pchaudhary@linkedin.com>
[config_mgmt.py]: Remove sort_data call, we do not need it now.
[config_mgmt.py]: Remove sort_data call, we do not need it now.
Build the PKG.

[config_mgmt.py]: Remove sort_data call, we do not need it now.

---

tests/mock_tables/dbconnector.py

The original code only works on `str` value

Improve MockRedis _encode(): so it will work on all types of value

---

clear/main.py
connect/main.py
doc/Command-Reference.md

Align following commands' exit code with consutil commands since there are aliasing commands:
- `connect line`
- `sonic-clear line`
This is a fix for this issue: https://github.com/Azure/sonic-utilities/issues/1241 
The issue will also cause the reverse ssh script couldn't response as expect for console switch feature disabled user(https://github.com/Azure/sonic-buildimage/pull/5438)
Bump the inner command's exit code to user.
Installed the script on a Physical DUT and test it.
```
admin@sonic:~$ consutil connect 2
Cannot connect: line [2] has no baud rate
admin@sonic:~$ echo $?
0
```
**- New command output (if the output of a command-line utility …

[connect][sonic-clear] Align the exit code with consutil for line commands

---

config/main.py

Fix that it cannot add loopback interface by CLI, like the following:
```
root@as7816-64x:~# config loopback add Loopback1
Usage: config [OPTIONS] COMMAND [ARGS]...
Try "config --help" for help.
Error: No such command "L".
```
Remove `@config.group()` before the function `is_loopback_name_valid(loopback_name)`, which will be called by add/del command
Applied the fix, and the add command works as following.
```
root@as7816-64x:~# config loopback add Loopback1
root@as7816-64x:~# ip link show Loopback1
74: Loopback1: <BROADCAST,NOARP,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
link/ether 8e:59:1e:43:e8:73 brd ff:ff:ff:ff:ff:ff
root@as7816-64x:~#
```
**- Previous command output (if the …

[config][loopback] Fix Bug that cannot add loopback interface by CLI

---

show/fgnhg.py

Fix crashes like the following:
```
File "/usr/local/bin/show", line 10, in <module>
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
File …
```

[show/fgnhg] Fix crash bug

---

tests/console_test.py

Add unit tests for `consutil clear` command.
Write unit test cases.
Run unit tests locally and all pass.
```
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
consutil/lib.py                              218      8    96%
consutil/main.py                              67      4    94%
```
N/A
N/A

[consutil][test] Add unit tests for consutil clear command

---

scripts/fast-reboot

A new `teamd` service script has been added in `sonic-buildimage` as part of the PR - https://github.com/Azure/sonic-buildimage/pull/5163
With this change, fast-reboot script will now use the new `teamd` script to handle killing teamd docker in both fast-boot and warm-boot mode.
Replaced the existing teamd docker handling with the `systemctl stop teamd`.
Tested the locally modified script in a DUT for `warm-reboot` and `fast-reboot`:
`warm-reboot` teamd shutdown path:
```
Nov 19 23:15:01.073902 str-7260cx3-acs-7 NOTICE admin: Stopping teamd ...
Nov 19 23:15:01.080848 str-7260cx3-acs-7 INFO systemd[1]: Stopping TEAMD container...
Nov 19 23:15:01.086341 str-7260cx3-acs-7 NOTICE admin: Stopping teamd service...
Nov 19 23:15:01.278733 …
```

Modify fast-reboot script to use teamd service script

---

pfcwd/main.py

Fixes: #https://github.com/Azure/sonic-buildimage/issues/6075
Fix the float division due to recent transfer to Python3, use floor division instead to
generate integer result in the PFCWD detect/restore time calculation.
Use `//` instead of `/` in Python3 to enforce integer output.
```
```
```
$ pfcwd show config
Changed polling interval to 606.25ms
PORT    ACTION    DETECTION TIME    RESTORATION TIME
-----------  --------  ----------------  ------------------
Ethernet0      drop            606.25              606.25
Ethernet4      drop            606.25              606.25
Ethernet16      drop …
```

[pfcwd] Use floor division in Python3

---

scripts/fdbshow
scripts/natshow
scripts/nbrshow

I fixed python porting errors in fdbshow, natshow and nbrshow scripts.
I removed 'b' from strings of the form b"xxxxx"
Without the fix, executing show mac, show arp, show nat throws an error related to this python porting error. So, with this fix, the show mac, show arp and show nat scripts execute successfully.
None
None

Fixing python porting errors in fdbshow, natshow and nbrshow

---

scripts/nbrshow

Fix https://github.com/Azure/sonic-buildimage/issues/6085
The output of 'arp -n' is bytes in python3, as a result, the search of 'ether' or other str failed. This commit addresses the issue.
I guess there are similar issues when upgrading to python3. I think we need to come up with a universal method to address these issues.
Convert the output of 'arp -n' from bytes to str.
Verified on dx010-6, running master image.
```
admin@str2-dx010-acs-6:~$ show arp
Address       MacAddress         Iface            Vlan
------------  -----------------  ---------------  ------
10.0.0.1      52:54:00:b7:a8:31  PortChannel0002  -
10.0.0.5      52:54:00:b9:b9:23  PortChannel0005  -
...... …
```

[nbrshow] Convert the output of 'arp -n' from bytes to str.

---

config/vlan.py
doc/Command-Reference.md
tests/vlan_test.py

When adding or deleting an DHCP relay destination address to a VLAN, previously, the service was simply restarted. However, we have set a start limit on services in SONiC, such that if a service is restarted X times within Y time, the service will enter a failed state and cannot be started until the failed state is cleared (currently 3 times within 20 minutes). However, if someone attempts to perform more than 3 add or delete operations within 20 minutes, it would trigger this failure condition. This change prevents this form occurring.
Rather than simply calling `systemctl restart dhcp_relay` after adding or deleting a DHCP relay destination IP address, we now call
```
systemctl stop dhcp_relay
systemctl reset-failed dhcp_relay
systemctl start …
```

[config vlan] Stop, reset-failed, then start dhcp_relay service

---

show/main.py
utilities_common/cli.py

Signed-off-by: Sabareesh Kumar Anandan <sanandan@marvell.com>
Some py imports in show/main.py script are taking more time on arm cpu.
modules - pkg_resources, netaddr are taking around 500ms causing delay for all show cmds.
These modules are used by only specific cmds. So, I have included these imports only for the commands that are using them.
Test all show commands. Execution time of show commands is better than before.

[show] Moving some py imports inside specific cmds

---

scripts/centralize_database
scripts/fast-reboot
scripts/migrate_warmboot_database
setup.py

* lua script to backup all database into one database and create rdb file - following earlier multiDB warmboot design at https://github.com/Azure/SONiC/blob/master/doc/database/multi_database_instances.md
* copy this rdb file as before to WARM_DIR
* restoring database part is in another PR at sonic-buildimage  https://github.com/Azure/sonic-buildimage/pull/5773, they depend on each other

[MultiDB] add MultiDB warmboot support - backing up database

---

scripts/fast-reboot

This is to fix/enhance the issue https://github.com/Azure/sonic-buildimage/issues/5972
`warm-reboot` with force flag ignores ASIC config checksum mismatch along with orchagent RESTARTCHECK failure.
There can be a use case when checksum-verification should be ignored but orchagent pause check should not be ignored.
Added a new `option` in fast-reboot script to ignore ASIC checksum verification failures.
Reproduced the issue locally:
```
root@sonic:~# warm-reboot -vvv
Sat 05 Dec 2020 02:14:38 AM UTC Saving counters folder before warmboot...
ASIC config may have changed: errno=1
Sat 05 Dec 2020 02:14:40 AM UTC warm-reboot failure (1) cleanup ...
Sat 05 Dec 2020 02:14:41 AM UTC Cancel warm-reboot: code (1)
root@sonic:~# 
```
With the …

Fast-reboot: add a new flag to ignore ASIC checksum verification failure

---

fdbutil/filter_fdb_entries.py

Fast-reboot failed to execute when NDP entries are present in the DB.
The split() function used with a delimiter ':' is not limited.
IPv6 address contains ':' delimiter causing it to create an object unsuitable for a tuple.
This is causing an exception.
Limit the split() function to 2 splits, forcing the IPv6 address to stay the same and create a proper tuple.
Inject NDP entries on a L3 interface and try to run "fast-reboot -v" command.
**- Which release branch to backport (provide reason below if selected)**
root@r-qa-sw-eth-20162:/home/admin# fast-reboot -v
Mon Dec 7 15:37:02 UTC 2020 Prepare …

[fast-reboot] Fix fast-reboot when NDP entries are present

---

config/console.py
consutil/lib.py
consutil/main.py
tests/console_test.py

This is the implementation of HLD: https://github.com/Azure/SONiC/blob/master/doc/console/SONiC-Console-Switch-High-Level-Design.md#33136-enabledisable-console-switch-feature
* This PR use below "CONSOLE_SWITCH:console_mgmt" instead the HLD mentioned key "CONSOLE_SWITCH" for better future change. I will update the HLD later.
This PR will allow user to enable/disable console switch management functions on a SONiC device.
- Add `config console {enable/disable}` command
- Exit directly if console swtich mgmt function not enabled when call console command
- Add unit tests
1. Added unit test cases and all pass
1. Build py-wheel package and tested on a physical SONiC DUT
```
admin@sonic:~$ consutil show
Console switch feature is …
```

[config/console][consutil] Support enable/disable console switch

---

show/sflow.py
tests/mock_tables/appl_db.json
tests/sflow_test.py

* Fix traceback seen for 'show sflow interface' command
Signed-off-by: Garrick He <garrick_he@dell.com>
Fixed a traceback seen when `show sflow interface` is executed.
Updated the script to follow Python3 conventions.
Retested the command to ensure no traceback is seen.

[sflow] Fix traceback seen for show sflow interface

---

acl_loader/main.py

I updated the default DENY rule for V6 to use IP type rather than Ethertype. This is necessary because L3V6 tables do not support Ethertype as a qualifier.
Updated the deny_rule method to use the new field.
1. Run acl-loader on a table of type L3V6
2. Verify there are no errors in the logs
3. Verify that IPv6 traffic that does not hit any of the ALLOW rules is dropped.
4. Verify that `aclshow` shows these drops under the DEFAULT_RULE.

[acl_loader] Fix default DENY rule for V6 dataplane ACLs

---

pcieutil/main.py
show/platform.py

Remove redundant 'pcie-' prefix from subcommands
Note this will also require an update to files/image_config/pcie-check/pcie-check.sh in sonic-buildimage. Also, since these commands require sudo, they need to be added to the read-only commands in the sudoers file, which they have not yet been.
Ensure the following commands work:
```
pcieutil show
pcieutil check
pcieutil generate
show pcieinfo
show pcieinfo -c
```

[pcieutil] Remove 'pcie-' prefix from subcommands

---

scripts/reboot

The platform identifier string is used in the reboot script to identify and execute any custom platform specific reboot script. 
sonic_platform is used as the kernel parameter to pass the platform identifier string.
In the reboot script, under the case where it is executed by the crash kernel, parse /proc/cmdline and parse sonic_platform value.
Enable kdump and reboot to operationally enable it.
Using echo c /proc/sysrq-trigger, crash the kernel and observe that the crash kernel executes platform specific reboot script

Parse sonic_platform kernel command line parameter to read the platform identifier string

---

scripts/generate_dump

Mellanox SAI implementation of the sai dump is now extracting more information which previously provided by direct call to a Mellanox FW tool which is not longer required.
The new files created will be taken along with the new dump.
Remove MST dump as it is not required anymore.
Add commands to copy FW dump output into techsupport output file, inside "sai_sdk_dump" directory.
Remove commands for MST dump.
Run "show techsupport" with MLNX SAI 1.18.0
├── mstdump
│   ├── mstdump1.gz
│   ├── mstdump2.gz
│   └── mstdump3.gz …

[Mellanox] Add FW dump with new SAI implementation and remove mst dump

---

config/main.py
show/main.py

1. added ip address validation for add_snmp_agent_address in config/main.py
2. Added click choice for routes in show/main.py 
3. Default kernel route via eth0 interface is still being show in the output 'show ip route' even after creating 'mgmt' VRF
Added Fix for it .
-   Added different validation checks in add_snmp_agent_address for the following cases : -
a.  Invalid ip check for snmpagentaddress click cmd
b.  Error case when vrf is not provided for snmpagentaddress click cmd
c.  Error case when a different ip is used for snmpagentaddress click cmd.
d.  If ip and port exists throw a msg notifying the same
-   click choice for routes in show/main.py was added .
-   Default kernel route via eth0 interface is still being show in the output 'show ip …

Mgmt vrf validations and bug fixes

---

scripts/fast-reboot-dump.py

This commit fix the exception thrown by struct.pack when attempting to pack a unicode string.
The script ```fast-reboot-dump.py``` will throw an exception in python3 because ```struct.pack``` requires ```bytes``` for ```s```.
```
Traceback: Traceback (most recent call last):
#012  File "/usr/local/bin/fast-reboot-dump.py", line 299, in <module>
#012    res = main()
#012  File "/usr/local/bin/fast-reboot-dump.py", line 292, in main
#012    send_garp_nd(neighbor_entries, map_mac_ip_per_vlan)
#012  File "/usr/local/bin/fast-reboot-dump.py", line 221, in send_garp_nd
#012    src_ip_addrs = {vlan_name:get_iface_ip_addr(vlan_name) for vlan_name,_,_ in neighbor_entries}
#012  File "/usr/local/bin/fast-reboot-dump.py", line 221, in …
```

[fast-reboot-dump] Fix exception in struct.pack

---

config/vlan.py

Remove `-t` flag from the `docker exec` command used to restart SWSS after updating the proxy ARP config. Currently with the flag, this command cannot be executed as part of a script (e.g. during a unit test in sonic-mgmt) since Docker is expecting the input device to be a TTY. 

[config vlan]: Remove `-t` flag from docker exec command

---

scripts/dropstat
tests/drops_group_test.py

Fixes https://github.com/Azure/sonic-buildimage/issues/5602
I followed the same pattern from `portstat` and gave each user their own `dropstat` directory instead of indexing the files by uid.
Validated that non-root user can clear after a `sudo sonic-clear dropcounters`. Also verified that each uid has their own `/tmp` directory. Also updated the unit tests.

[dropcounters] Fix clear for non-root users

---

config/config_mgmt.py
config/main.py
tests/config_dpb_test.py

```
Test Plan:
Consideration for sonic utilities breakout config tests: 
-- create a breakout config file,  
-- mock load_configMgmt() to return specially constructed configMgmtDPB instance. 
-- Device info get_ path*__file function should return default file so it should be mocked. 
-- config db must have breakout config table. 
-- mock get child ports to return interfaces, if needed.
-- mock shut down interfaces, if needed.
*Test Plan:* 
*>>> Test _get_ breakout options()* 
-- create a file breakout config. This can be a PY test fixture. 
-- mock device information part to return breakout file. 
-- pass argument incomplete as below and observe the results: 
a.) 1x1 b.) 4x c.) 2x d.) Wrong interface. 
*>> Test Verbose Args:* 
Pass verbose as args, and observe that loadConfigMgmt is …
```

[config] Add unit tests for 'config interface breakout' command

---

scripts/aclshow
scripts/ecnconfig
scripts/fdbclear
scripts/fdbshow
scripts/lldpshow
scripts/mmuconfig
scripts/natclear
scripts/natconfig
scripts/natshow
scripts/nbrshow
scripts/portconfig
scripts/sonic_sku_create.py

In python3, message is not an attribute of Exception. As a result, another exception will be thrown in exception handling code. 
```
"Traceback (most recent call last):", 
"  File \"/usr/local/bin/fdbshow\", line 154, in <module>", 
"    main()", 
"  File \"/usr/local/bin/fdbshow\", line 150, in main", 
"    print(e.message)", 
"AttributeError: 'RuntimeError' object has no attribute 'message'"
```
This commit addressed the issue.
Relpace ```e.message``` with ```str(e)```.
Verified by a demo script.

Fix exception handling code in python3

---

scripts/fast-reboot

Add FG_ROUTE_TABLE to backup database for warm reboot support for fgnhg. 
Test on lab sonic device for the script and see the state db entry retained after warm reboot

retain fgnhg state db table entry during warm reboot

---

show/bgp_common.py
tests/conftest.py
tests/ip_show_routes_multi_asic_test.py
tests/mock_tables/asic0/ip_route_summary.txt
tests/mock_tables/asic1/ip_route_summary.txt
tests/mock_tables/asic2/ip_route_summary.txt
tests/show_ip_route_common.py

Added Multi-ASIC support of handling "show ip/v6 route summary"
This was not supported for multi-ASIC platform previously.
When running this cmd under multi-ASIC platform the following output are expected:
```
admin@SONiC:$ show ip route summary -d all
asic0:
Route Source         Routes               FIB  (vrf default)
kernel               1                    1
connected            6                    6
static               1                    0
ebgp                 6371                 6371
ibgp                 88                   88
------
Totals               6467                 6466
asic1:
Route Source         Routes               FIB  (vrf default)
kernel               1                    1
connected            6                    6
static               1 …
```

Added show ip/v6 route summary support for multi-asic platform

---

scripts/fast-reboot-dump.py

Fix fast reboot failure due to invalid parsing of genetlink type hostif object id attribute. Genetlink type hostif does NOT have object ID attribute.
SAI_HOSTIF_ATTR_OBJ_ID (SAI_HOSTIF_ATTR_TYPE == SAI_HOSTIF_TYPE_GENETLINK)

Update fast-reboot-dump.py to handle invalid parsing of genetlink type hostif object id attribute

---

scripts/route_check.py

orchagent ignore all routes pointing to Loopback interfaces.
add this skip logic in route check.
https://github.com/Azure/sonic-swss/pull/1570
use regex to match the interface name
tested on kvm switch

[route_check]: ignore routes pointing to Loopback interface

---

tests/pfcwd_test.py

The 'config' tests that require sudo access were failing. Fixed it by mocking os.geteuid.
Fixed it my mocking os.geteuid.
Unit tests and manual verification
```
before:
samaddik@856d790db1d1:/sonic/src/sonic-utilities/tests$ pytest-3 pfcwd_test.py  -k test_pfcwd_start_actions_masic
>       assert result.exit_code == 0                                                                                                                                                                                                         |
E       AssertionError: assert 1 == 0 …
```

[unit test][pfcwd] Fix tests that require sudo access

---

scripts/generate_dump

Mellanox SAI implementation of the sai dump is now extracting more information which previously provided by direct call to a Mellanox FW tool which is not longer required.
The new files created will be taken along with the new dump.
Remove MST dump as it is not required anymore.
Add commands to copy FW dump output into techsupport output file, inside "sai_sdk_dump" directory.
Remove commands for MST dump.
Run "show techsupport" with MLNX SAI 1.18.0
├── mstdump
│   ├── mstdump1.gz
│   ├── mstdump2.gz
│   └── mstdump3.gz …

Add FW dump with new SAI implementation

---

scripts/generate_dump
show/main.py

and some other enhancements to techsupport
Following is the brief description of the changes,
- Adding a ‘--silent’ option to ‘show techsupport’ command. Various  tar/untar, addition and removal logs appear on the console by default. This option would disable above logs.
- Adding global and per-command timeouts. This would provide more user control on ‘show techsupport’ CLI.
- Adding time profiling information for the commands in techsupport. Time profiling information would be part of the tarball and helps to analyse the time consumption per command.
- Sometimes ‘syncd’ docker is down and bcmshell is unavailable. In such cases all the bcmcmd commands would timeout and result in tremendous increase in the total techsupport collection time. We provided an option to skip …

Adding global-timeout, individual command timeout, log files collection

---

scripts/storyteller
setup.py

Introduce storyteller tool to grep syslog (or any other logs) for
a story line of a certain scenario.
Defined scenarios are:
- reboot  : device reboot related events.
- service : service start/stop events.
- link    : link up/down events.
- lag     : LAG up/down events.
- bgp     : BGP config change events.
- crash   : process/service crash events.
Unmatched cateory is used as grepping regex directly.
Used this tool in some recent investigations.

[storyteller] adding a grep wrapper with predefined scenarios

---

scripts/route_check.py
tests/route_check_test.py

The routes flow from APPL-DB to ASIC-DB, via orchagent.
This tool's job is to verify that all routes added to APPL-DB do
get into ASIC-DB and all routes removed from APPL-DB are deleted from ASIC-DB.
NOTE: The flow from APPL-DB to ASIC-DB takes non zero milliseconds.
1) Initiate subscribe for ASIC-DB updates.
2) Read APPL-DB & ASIC-DB 
3) Get the diff.
4) If any diff, 
4.1) Collect subscribe messages for a second
4.2) check diff against the subscribe messages 
5) Rule out local interfaces & default routes
6) If still outstanding diffs, report failure.
Run this tool in SONiC switch and watch the result. In case of failure
checkout the result to validate the failure.
To simulate failure:
Stop Orchagent.
Run this tool, and likely you …

[route_check.py] -  update includes checks on subscriptions

---

config/main.py
tests/mock_tables/config_db.json
tests/portchannel_test.py

Added below validation checks when user the configures a port as member a portchannel:
1. Check if the given portchannel name is valid or not
2. Check if the given portchannel name exists in CONFIG_DB
3. Check if the given port is configured with an IP address or not
4. Check if the given port is configured with with VLAN membership or not
5. Check if the given port is already member of a portchannel
6. Check if the given port speed matches the speed of existing members
7. Check if the given port MTU matches the speed of existing members
Added below validation checks when user the removes member port from a portchannel:
1. Check if the given portchannel name is valid or not
2. Check if the given portchannel name exists in exists in CONFIG_DB or not
3. Check if the given port is member of …

Validations checks while adding a member to PortChannel and removing a member from a Portchannel

---

show/chassis_modules.py
tests/chassis_modules_test.py
tests/mock_tables/state_db.json

sonic-utilities: Changes to show midplane status in modular chassis
HLD: Azure/SONiC#646
- What I did
Show command to verify status of midplane in modular chassis
$show chassis_modules midplane-status
- How I did it
Extended the show/chassis_modules.py with the midplane-status option
Verified via UT and vendor-platform implementation to show the midplane IP-address and rechability-status
- New command output (if the output of a command-line utility has changed)
An example vendor specific output below
**CLI Output - On Supervisor**
```
show chassis-modules midplane-status
Name    IP-Address    Reachability
----------  ------------  --------------
LINE-CARD0      10.0.0.1            True
LINE-CARD1      10.0.0.2           False
LINE-CARD2      10.0.0.3            True …
```

[show] Add subcommand to show midplane status for modular chassis

---

scripts/configlet

Drop explicitly introduced 3 seconds pause between object updates using configlet.
Remove the added time.sleep(3)
Add 10 objects using old code and see it takes 30+ seconds. Repeat the same with this updated code which would complete in small fraction of a second.
Verified ASIC-DB contents to the extent possible in both scenarios of applying objects using old code with 3 seconds pause and new code w/o any explicit pause, to be the same.

Drop explict 3 seconds pause between two object updates/deletes.

---

show/muxcable.py
tests/mock_tables/config_db.json

Summary:
This PR provides the support for fixing the show muxcable config. 
There was a change in the Config_DB schema where there was an addition of key-value pair
"peer_switch:tor_name" in DEVICE_METADATA|localhost  table which actually gives the other TOR's name (hostname).
This TOR name is then utilized in PEER_SWITCH|switchname table which has "address_ipv4: IPv4 address" key-value pair,
which correctly gives the ip address for displaying on the show mux config           
` show muxcable config <portname>`
`
added the changes in sonic-utilities/show muxcable.py
To add the fix the working for show muxcable config
Added the changes inside sonic-utilities and tested it on the testbed
Ran the cli commands on an Arista7050cx3 testbed with Gemini cable
Signed-off-by: vaibhav-dahiya …

[show]fix for show muxcable status by replacing "hostname" to "peer_switch" for deriving tor ipv4_address

---

config/main.py
pfcwd/main.py

The 'config' method is getting arguments from the user CLI and build a proper command for the pfcwd script in a wrong way, causing this issue.
Fix the command structure to align with pfcwd.main script.
Run "config pfcwd start --action drop ports all detection-time 400 --restoration-time 400"
config pfcwd start --action drop ports all detection-time 400 --restoration-time 400
Failed to run command, invalid options:
ports
detection-time
Command succeeded.

[PFCWD] Fix 'start' pfcwd command

---

scripts/nbrshow

* Adding condition to check result of getting of Vlan id, using bvid.
If the vlan id is None, then skip the record to avoid exception
raising on int(NoneType)
Resolves https://github.com/Azure/sonic-buildimage/issues/6367
Fix exception raising while executing "show arp" command in cases, when the system has an FDB entry, which is linked to default VLAN 1.
New condition has added to function "fetch_fdb_data" inside "nbrshow" script, which checks the result of getting "vlan_id" by using "bvid". If "vlan_id" is None, then just continue iterate "fdb_str", as a record inside "bridge_mac_list", which has not vlan_id, could not be using in any other places of "nbrshow" script.
1. …

[show] Fix show arp in case with FDB entries, linked to default VLAN

---

config/main.py

Made a robust check for below cases.
1. when the interface is wrong and the mode is correct.
2. BREAKOUT_CFG table is NOT present in CONFIG DB
Also, Fixed Breakout mode option when options are not available for easy readability.
Made changes in the `config/main.py` file for an extra check 
`sudo config interface breakout`

[config] Fix Breakout mode option and BREAKOUT_CFG table check method

---

config/main.py
tests/portchannel_test.py

Added below validation checks when a portchannel is created by the user:
1 if a given portchannel name is valid or not
2 if a given portchannel name is already created by user (exists in CONFIG_DB)
Added below validation checks when a portchannel is attempted for deletion by the user:
1 if a given portchannel name is valid or not
2 if a given portchannel name exists in exists in CONFIG_DB or not (throw an error if it does not exist)
More details : 
Issue 1 : Creating a invalid Portchannel name
If we create a portchannel with invalid name, it gets added to CONFIG_DB, like below
root@sonic:/home/admin# config portchannel add PortChan001
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChan001
Fix: Added a …

Validations checks while creating and deleting a Portchannel

---

show/muxcable.py

Unix domain sockets require privileged access while show command
could be run by ro user. Switch muxcable show command to use TCP
connection to work with ro user.
fixes Azure/sonic-buildimage#6456
resolves Azure/sonic-buildimage#6456
Fix show command for ro users
Change use_unix_socket attribute to False
run `show muxcable config` from ro user account
N/A
N/A (same)

[show]: Use TCP Connection For Muxcable Commands

---

scripts/ecnconfig

On Multi ASIC platforms ports names for backend ports have the following convention: 'Ethernet-BPxy'
Port ID extraction was failing for these backend port names.
Fix the port ID extraction for backend port names.
Manual:
```
before:
admin@str-sonic-acs-2:~$ sudo ip netns exec asic0 ecnconfig -q 3
Exception caught:  invalid literal for int() with base 10: '-BP48'
After:
admin@str-sonic-acs-2:~$ sudo ip netns exec asic0 ecnconfig -q 3
ECN status:
queue 3: on
```

[ecnconfig] Handle Multi ASIC backend port names when extracting port I/F

---

config/main.py
scripts/ecnconfig
setup.py
show/main.py
tests/ecn_input/ecn_test_vectors.py
tests/ecn_test.py
tests/mock_tables/config_db.json

Added unit tests for ecnconfig command
Updated 'show ecn' command to use run_command wrapper 
Updated 'config ecn' command to allow configuration of drop probabilities
Cleanup trailing spaces in ecnconfig script and add hooks to support unit tests
Ran the new ecn_test.py and it passed

[ecn] Add tests for ecnconfig command

---

scripts/neighbor_advertiser

Add vlan_interface_object based on the presence of ipv4 or ipv6 mappings
Introduce a check for the count of ipv4 and ipv6 before adding vlan_interface_object and add it only if either of the mappings are present
Look for the slice object and see that it contains no empty ipv4 and ipv6 mappings.

Add vlan_intf_object only if there are ipv4 or ipv6 mappings

---

config/config_mgmt.py
tests/config_mgmt_test.py

Changes:
-- Set leaf-list to empty list while port breakout, because deletions
are not done to fields once set.
Signed-off-by: Praveen Chaudhary<pchaudhary@linkedin.com>
Changes:
-- Set leaf-list to empty list while port breakout, because deletions
are not done to fields once set.
Set list to empty while DPB.
Build time tests are changes accordingly. PKGs build fine.

[config_mgmt.py]: Set leaf-list to empty list while port breakout.

---

config/main.py

Fixed bug https://github.com/Azure/sonic-buildimage/issues/6426
Added a validation in config/main.py to prevent configuring IP interface on a port which is a member of VLAN
Change config/main.py
Add interface as member in vlan
Try to configure IP address on same interface
Success in the above scenario. 
prevent configuration:
"Interface Ethernet0 is a member of vlan
Aborting!"

Prevent configuring IP interface on a port which is a member of VLAN

---

show/main.py

* Performing getting from APPL_DB of all the keys while checking readiness
status of the gearbox to prevent warnings sending to syslog if there no 
records of PHYs of a gearbox in APPL_DB.
* Moving of the gearbox readiness status checking procedure to separated
function.
1. Resolves https://github.com/Azure/sonic-buildimage/issues/6311.
Occurrence of the next warnings while performing show commands has fixed:
`Jan 29 15:05:50.705534 sonic WARNING python3: :- operator(): DB '{APPL_DB}' is empty with pattern '_GEARBOX_TABLE:phy:*'!`;
The issue has fixed by getting of all the keys from APPL_DB, before checking of presence of _GEARBOX_TABLE:phy:* records in the DB.
1. open two …

[show] Fix warnings, related to gearbox, while show commands execution

---

consutil/lib.py

The configuration file of consulit did not tolerate a trailing new line.
Enhance the plugin mechanism by allowing trailing chars.
Removed trailing chars on the 1st line read from `udevprefix.conf`
Run this fixed version with the following scenarios.
Backward compatibility: `echo -n ttyUSB > udevprefix.conf`
Support of trailing whitespaces `echo ttyUSB > udevprefix.conf`
Futureproof case where we might want to handle multiple prefixes `echo "ttyUSB \nttySMTH" > udevprefix.conf`

Improve robustness of consutil plugin loading

---

config/vlan.py
tests/vlan_test.py
utilities_common/cli.py

Fix for https://github.com/Azure/sonic-buildimage/issues/6421
User was able to add an interface to multiple VLANs as untagged. Added a validation to a single untagged member.
Added a validation when adding a port as untagged to check in DB if is already member as untagged in a different vlan.
Add vlan, add interface as untagged member in this vlan, add another vlan, try to add the same interface as untagged member in the new vlan.
Command was successful.
Fail in VLAN membership.
Error: Ethernet8 is already untagged member!

Prevent user from adding more then a single untagged VLAN to an interface

---

show/interfaces/__init__.py

Fixed `show interface breakout` command
From command line type `show interface breakout`
```
File "/usr/local/bin/show", line 10, in <module>
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
return …
```

[show] fix "show interfaces breakout" command

---

scripts/ecnconfig

Allow ecn unit tests to run without root privileges
Included the UTILITIES_UNIT_TESTING' env variable also as one of the conditions to determine if the command needs root privileges for execution
Ran utilities test using the command "python3 setup.py test" and ecn_test.py passed. Prior to the fix, most of the testcases were failing with the error 'Root privileged required for this operation'

[ecnconfig] Allow ecn unit test to run without sudo

---

show/platform.py

Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>
Added ability to run `show platform firmware` commands without `sudo`, as described in the [design document](https://github.com/Azure/sonic-utilities/blob/master/doc/Command-Reference.md#platform-component-firmware-show-commands):
Made `show platform firmware` implementation run `fwutil` with `sudo` 
Run `show platform firmware status` 
```
$ show platform firmware status 
Error: Root privileges are required. Aborting...
Aborted!
```
```
$ show platform firmware status 
Chassis    Module    Component    Version …
```

[show] Run fwutil with sudo

---

config/main.py

* Replacing using 'get_all' with 'exists' in port state checking
procedure inside bind function to avoid freezing in the while loop,
what caused by absence of related record in STATE_DB.
Resolves https://github.com/Azure/sonic-buildimage/issues/6209
Freezing of "sudo config interface vrf bind EthernetXX Vrf_XX" operation has resolved.
As currently the system completely deletes "INTERFACE_TABLE|EthernetXX" record in STATE_DB on unbinding or on preparing stage of bind, there is not need to check presence of any keys of the record.
Checking of keys of "INTERFACE_TABLE|EthernetXX" record in STATE_DB, what caused freezing due to absence of the record, has changed to checking for existence of entire record. …

[vrf]: Fix freezing during interface binding (#6209)

---

scripts/storyteller

- Add log path parameter to allow storyteller to work on  logs downloaded from sonic devices.
- Improve reboot regex to capture more warm reboot related logs.
Use storyteller against a sonic dump.

[storyteller] allow storyteller to work on downloaded logs

---

clear/main.py
show/main.py

ignore the message printed on stderr
sonic:$ show ip bgp sum
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
ignore stderr
tested on pilot devices manually

do not parse stderr to get correct routing stack

---

scripts/route_check.py

As part of dual-tor features, kernel tunnel interface (tun0) is being created. The routes over this is intended for kernel forwarding and not expected to be installed in ASIC. 
Ref PR - https://github.com/Azure/sonic-swss/pull/1615
Added to the list of 'skipped' interfaces

[route_check.py] Skip route check for tun0 interfaces

---

config/muxcable.py
doc/Command-Reference.md
setup.py
show/muxcable.py
tests/muxcable_test.py

Summary:
This PR provides the support for adding CLI commands for configuring prbs, loopback and showing the BER and Eye info of the muxcable.
In particular these Cli commands are supported:
` show muxcable eyeinfo <portnumber><target>`
` show muxcable berinfo <portnumber> <target>`
`config muxcable prbs <portnumber> <target> <mode> <lanemap>`
`config muxcable loopback <portnumber> <target> <lanemap>`
added the changes in sonic-utilities/show and sonic-utilities/config by changing the muxcable.py 
To add the support for Cli for muxcable to be utilized for configuring prbs, loopback modes and showing the ber, eye info of all the Port/Ports on a muxcable.
Added the changes inside sonic-utilities and tested it on the testbed
Ran the cli commands on an Arista7260cx3 testbed with Gemini cable …

[config][show] cli support for retrieving ber, eye-info and configuring prbs, loopback on Y-cable 

---

scripts/intfutil

Fixed crash of "show int status" command when there are portchannels in system.
```
File "/usr/local/bin/intfutil", line 521, in <module>
main()
File "/usr/local/bin/intfutil", line 513, in main
interface_stat.display_intf_status()
File "/usr/local/bin/intfutil", line 354, in display_intf_status
self.get_intf_status()
File "/usr/local/lib/python3.7/dist-packages/utilities_common/multi_asic.py", line 137, in wrapped_run_on_all_asics
func(self,  *args, **kwargs)
File "/usr/local/bin/intfutil", line 435, in get_intf_status
self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
File "/usr/local/bin/intfutil", line 249, in po_speed_dict
interface_speed = '{}G'.format(interface_speed[:-3])
TypeError: 'NoneType' object is not …
```

[show] Fix int status when portchannel is in the system

---

scripts/storyteller

- Sanitize user inputs with shlex
- Add support for specifying a time period
- Add basic ACL regex
I made a few changes to the storyteller:
- You can now specify a timeframe to check through, similar to `show tech`
- There is a regex for getting ACL information
- User inputs are sanitized using `shlex`
I followed the same general approach as `show tech` to add time filter support.
`sudo storyteller --since "last hour" -c acl -p "/var/log"`

[storyteller] Enhance the storyteller utility

---

scripts/neighbor_advertiser
tests/neighbor_advertiser_test.py

Modify the neighbor_advertiser script to advertise ipv6 link local address
This PR resolves https://github.com/Azure/sonic-buildimage/issues/6599
Add ipv6 link local address to the slice returned by the neighbor advertiser script
Added the verification logic to the neighbor_advertiser test

Advertise ipv6 link local address

---

scripts/natshow

* Substituting nat_entry variable, instead of s inside fetch_translations
function to avoid exception throwing inside the function due to undefined
variable.
Resolves https://github.com/Azure/sonic-buildimage/issues/6391
Fix exception throwing during fetching translations inside `natshow `scripts.
The issue has introduced in be63918d, while migrating to Python 3.
Variable `s` has replaced with `nat_entry`.
Execute:
`natshow -t`
or
`show nat translations`

[show] Use proper variable to avoid exception in natshow script

---

sonic_installer/bootloader/aboot.py
sonic_installer/bootloader/bootloader.py
sonic_installer/common.py
sonic_installer/main.py

Abstracted away the access to the path of the rootfs via a contextmanager.
In Arista secureboot, the rootfs is never extracted on the flash. Instead it's mounted directly from within the signed SWI.
The `update_sonic_environment` function however always assume that the rootfs to be at the same place. 
To alleviate this restriction, a new context manager to obtain the rootfs is introduced.
The choice of a context manager rather than a function is entirely based on error management and cleanup.
Mounting a squashfs from a swi file requires the use of `losetup` which makes the rootfs available under `/dev/loopX`
Once done or on error, we need to free this resource which becomes free when using a contextmanager.
Use `sonic-installer …

Fix sonic-installer install for Arista secureboot

---

scripts/generate_dump

This reverts commit 12f03b195609c07762d8c8efd80dc548ddd4fe78.
revert changes to call mstdump and replace with old call to sdkdump
reverting a previous commit [Mellanox] Add FW dump with new SAI implementation and remove mst dump Azure#1298
run techsupport
N/A
N/A

[Mellanox] Revert "Add FW dump with new SAI implementation (#1298)"

---

config/main.py

Fixes https://github.com/Azure/sonic-buildimage/issues/6708
This bug is exposed by https://github.com/Azure/sonic-utilities/pull/1392. Previously the `config` command will call `SonicDBConfig.load_sonic_global_db_config()` even on a single ASIC platform, and it will silently failed. After exposed, it will fail with error syslog message:
```
admin@sonic:~$ sudo config save
Existing files will be overwritten, continue? [y/N]: ^CAborted!
Feb  8 03:23:48.729434 sonic ERR sniffer: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
```
Tested on DUT
**- New command output (if the …

Fix: initialize SonicDBConfig differently for single or multi_asic

---

pcieutil/main.py

Fixes https://github.com/Azure/sonic-buildimage/issues/6437
Changed the configuration file path from plugin to platform directory 
Verify on the device

[pcieutil] Remove the warning message and change the config file location

---

config/main.py

Signed-off-by: Ze Gan <ganze718@gmail.com>
Add `macsec` service to list of services to clear fail count and restart after config reload
`config reload` on a device with the `macsec` service and container running. Verify `macsec` container comes back up after config reload is finished.
`config reload` on a device without the `macsec` service and container. Verify config reload proceeds normally.
```sh
admin@sonic:~$ sudo config reload -y
Executing stop of service telemetry...
Warning: Stopping telemetry.service, but it can still be activated by:
telemetry.timer
Executing stop of service swss...
Executing stop of service lldp...
Executing stop of …
```

[config reload]: Restart macsec container

---

scripts/generate_dump

This reverts commit b10622e08fd0a92dd22688b023f7dbbef498aceb.
revert changes to call sdkdump and replace with old call to mstdump
reverting a previous commit [Mellanox] Add FW dump with new SAI implementation and remove mst dump Azure#1338
run techsupport
N/A
N/A

[Mellanox] Revert "Add FW dump with new SAI implementation (#1338)"

---

tests/config_dpb_test.py
tests/config_mgmt_test.py
tests/reboot_cause_test.py

As of Python 3, `mock` is part of `unittest` in the Python standard library. Since sonic-utilities is now Python 3-only, we should import it this way everywhere.

Import 'mock' module from 'unittest' library

---

show/muxcable.py
tests/muxcable_test.py

Sort the output of `show mux status` and `show mux config` for easier comparison between devices

[show mux]: Sort output by intf name

---

acl_loader/main.py
crm/main.py
scripts/db_migrator.py
scripts/lldpshow
scripts/portconfig

This bug is exposed by https://github.com/Azure/sonic-utilities/pull/1392. Previously the `config` command will call `SonicDBConfig.load_sonic_global_db_config()` even on a single ASIC platform, and it will silently failed. After exposed, it will fail with error syslog message:
```
Feb  9 05:04:46.462361 vlab-01 ERR python3: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
```

Fix: initialize SonicDBConfig differently for single or multi_asic (continued)

---

config/config_mgmt.py
config/main.py
scripts/route_check.py
tests/sku_create_test.py

Fix Python deprecation warnings as reported by pytest
Convert strings which include escape sequences into raw strings

Fix deprecation warnings

---

scripts/storyteller

- sort output by time
- improve lag support according to event format changes
- add an option to sort the log files by a field of file name (after log files got moved or copied, sorting by timestamp is no longer reliable).
run 'sudo storyteller --since "2021-2-10" -c lag' on a dut

[storyteller] sort output by time and improve lag support

---

consutil/lib.py

Config files do not belong under `<platform>/plugins/` directory. That directory is intended for (now-deprecated) platform-related Python plugins. The directory will be removed in the near future.
Look for udevprefix.conf file directly under the respective platform directory instead.
Also clean up and reorganize imports
NOTE: When this submodule is updated in sonic-buildimage, related files will need to be updated. Currently only platform/broadcom/sonic-platform-modules-cel/haliburton/script/udev_prefix.sh

[consutil] Look for udevprefix.conf file under platform dir, not plugins

---

scripts/decode-syseeprom

Refactor decode-syseeprom utility to use sonic-platform package in lieu of old, deprecated platform plugins.
- Complete refactor to use sonic-platform package
Run all `decode-syseeprom` commands, ensure they work. Do the same on multiple platforms. Output should be the same as before.

[decode-syseeprom] Refactor to utilize sonic-platform package

---

psuutil/main.py
tests/psuutil_test.py

Refactor psuutil to use sonic-platform package in lieu of old, deprecated platform plugins.
The psuutil utility is still useful, as psushow only reads and displays PSU data from State DB. However, this utility provides us the ability to read directly from the PSUs which is helpful for debugging.
- Complete refactor to use sonic-platform package
- Refactor display functions to align with psushow utility (add more output columns)
- Bump version to 2.0
- Add basic unit tests
Run all `psuutil` commands, ensure they work. Do the same on multiple platforms. Output should be the same as before.
```
admin@sonic~: psuutil status
PSU    Status
-----  --------
PSU 1  OK
PSU 2  OK
```
```
admin@sonic~: psuutil status
PSU    Model    Serial                          Voltage (V)    Current (A)    Power …
```

[psuutil] Refactor to utilize sonic-platform package

---

utilities_common/cli.py

Fix #1397 
Added fix for Issue in CLI output alignment with shorter alias names in intf naming mode "alias"
Added code to remove last few extra characters from string (-------…) using Slicing & Positive Indexing in python, to match the width to alias's name(not interface)
Steps to reproduce:
1. Change the naming mode to alias instead of port names
admin@sonic-svk169-dut:~$ config interface_naming_mode alias
2. Update config_db.json for port section to change alias to shorter names like below
3. Reload and run following command
For shorter alias names like P0, P1, etc..
```
admin@sonic-svk169-dut:~$ show interfaces  counters
IFACE    STATE    RX_OK …
```

[show ] Issue in CLI output alignment with shorter alias names in intf naming mode "alias" #1397

---

config/vlan.py
tests/vlan_test.py

Prevent deleting VLAN if it has IP addresses.
fixes: https://github.com/Azure/sonic-buildimage/issues/6769
Currently, if an IP was added to the vlan, it creates entries in the VLAN_INTERFACE table and increments the reference counter for the vlan:
```
VLAN_INTERFACE|Vlan22|100.0.0.20/24
VLAN_INTERFACE|Vlan22
```
But after deleting the vlan, they get stuck in the table and throw an error:
```
sonic ERR swss#orchagent: :- removeVlan: Failed to remove ref count 1 VLAN Vlan22
```
Therefore, to prevent this error, make sure that the entries do not exist before deleting the VLAN.
Added check of the VLAN INTERFACE table and if there are records, the delete operation is not available and an error is displayed.
1. config vlan add 22
2. config int ip add Vlan22 10.0.0.51/24
3. config vlan del 22 …

[config] Prevent deleting VLAN with IP addresses.

---

counterpoll/main.py
tests/counterpoll_test.py
tests/mock_tables/config_db.json

Enhance counterpoll utility to support PG drop counters. 
Add new CLI to enable/disable it.
**depends on:**
https://github.com/Azure/sonic-buildimage/pull/6444
https://github.com/Azure/sonic-swss/pull/1600
**merge priority:**
https://github.com/Azure/sonic-swss/pull/1600
https://github.com/Azure/sonic-utilities/pull/1355
https://github.com/Azure/sonic-buildimage/pull/6444
Added new option for "counterpoll" utility
Enhance counterpoll utility for SAI_INGRESS_PRIORITY_GROUP_STAT_DROPPED_PACKETS 
Add new CLI command and extend the show command.
To test it use QoS test. run the pfcxontest and Pfcxofftest, drop can be triggered in either of the test.
It runs in ptf32 topo and requires …

Add new CLI for PG drop counters part of counterpoll utility

---

scripts/sfpshow

Clean up sfpshow utility
- Reword header docstring and comments
- Unify formatting
- Rename variables and constants
- Use `+=` for string concatenation to reduce line length
- Pass through `autopep8 --max-line-length 120`

[sfpshow] Cleanup

---

sfputil/main.py
tests/sfputil_test.py

Refactor sfputil to use sonic-platform package in lieu of old, deprecated platform plugins.
The sfputil utility is still useful, as sfpshow only reads and displays SFP data from State DB. However, we still need a utility to write to the transceivers (low power mode, reset, etc.), and the ability to read directly from the transceivers is helpful for debugging.
- Complete refactor to use sonic-platform package
- Refactor display functions to align with sfpshow utility
- Bump version to 3.0
- Add unit tests
Run all `sfputil` commands, ensure they work. Do the same on multiple platforms. Output should be the same as before.

[sfputil] Refactor to utilize sonic-platform package

---

scripts/vnet_route_check.py
setup.py

Added "vnet_route_check" tool for check VNET route consistency.
vnet_route_check.py: tool that verifies VNET routes consistancy between SONiC and vendor SDK DBs.
Logically VNET route verification logic consists of 3 parts:
1. Get VNET routes entries that are missed in ASIC_DB but present in APP_DB.
2. Get VNET routes entries that are missed in APP_DB but present in ASIC_DB.
3. Get VNET routes entries that are missed in SDK but present in ASIC_DB.
Returns 0 if there is no inconsistancy found and all VNET routes are aligned in all DBs.
Returns -1 if there is incosistancy found and prints differences between DBs to standart output and syslog.
Added "vnet_route_check" script with the relevant VNET …

[201911][vnet] Add "vnet_route_check" script

---

scripts/route_check.py
tests/route_check_test.py

Cherry-pick from master

---

scripts/neighbor_advertiser
tests/neighbor_advertiser_test.py

Refactored code in neighbor_advertiser script and used mock module to unittesting
The neighbor_advertiser test will verify it.

Refactor neighbor_advertiser script and use mock for testing

---

azure-pipelines.yml

Now that https://github.com/Azure/sonic-utilities/pull/1427 has merged, we should be able to successfully run all unit tests in a non-privileged slave container.
Remove `--privileged` option from sonic-slave-buster container
Ensure PR unit tests pass

[ci] No longer pass '--privileged' option to slave container

---

doc/Command-Reference.md

Fix #1424
Added CLI reference for buffer-pool watermark|persistent-watermark commands
Updated the Command-Reference.md file for following:
1. Added buffer_pool in "show" help
2. show description for buffer_pool watermark
3. show descritpion buffer_pool persistent-watermark
NA
NA
NA

Added CLI reference for buffer-pool watermark|persistent-watermark commands

---

scripts/centralize_database

Fixes: https://github.com/Azure/sonic-buildimage/issues/6811
The DB backup during warmboot has started failing recently after the changes made in commit (https://github.com/Azure/sonic-utilities/commit/2e1f354a2abb5d38eff4d418c89215c40f52e736#diff-5777288143b5a8ff1e97be074d748fd825f0ee1812f2d7c65d850c893bccefd6)
Above change was an attempt to deprecate the `SonicDBConfig` methods originally implemented by python in https://github.com/Azure/sonic-py-swsssdk/. The new implementation is based on hiredis C++ library.
The `centralize_database` script still uses the Python APIs instead of C++, update the method names which are now defined in `sonic-swss-common` https://github.com/Azure/sonic-swss-common/blob/master/common/dbconnector.h#L64
With the changes, the warmboot now works without an …

Update SonicDBConfig calls for centralize_database to use C++ APIs

---

doc/Command-Reference.md

Add documentation for console feature switch
Update `Command-Reference.md`
N/A
N/A
N/A

[doc] Add documentation for console feature switch

---

config/main.py
tests/config_dpb_test.py

Signed-off-by: Sangita Maity <samaity@linkedin.com>
As per latest update in DPB [DOC](https://github.com/Azure/SONiC/pull/749), fixed this [bug](https://github.com/Azure/sonic-buildimage/issues/6645)
previously we had string value in "breakout_modes" key so it was not matching the whole string, But after the update via, now "breakout_modes" contain a dictionary where `key` is the `breakout_mode` and value is the `alias`. So we can easily check whether the key is present or not.
> DEPENDENCY on [Update Dynamic Port Breakout Logic for flexible alias support](https://github.com/Azure/sonic-buildimage/pull/6831) which fixes the [issue](https://github.com/Azure/sonic-buildimage/issues/6024)
checked whether the user-specified breakout mode key is present under "breakout_modes" …

[dpb|config] Fix the validation logic of breakout mode

---

config/vlan.py
tests/vlan_test.py

Signed-off-by: allas <allas@nvidia.com>
In vlan.py , function del_vlan added validation if there is no members assigned to this VLAN. If there are members - the execution of this command is failed with error on the screen.
Added validation of the VLAN_MEMBER_CFG_TABLE with the key VLAN_ID. If there are entries with this VLAN_ID - print error:
VLAN ID {} can not be removed. First remove all members assigned to this VLAN.
User should remove all members assigned to this VLAN, and after that he can delete vlan.
sudo config vlan add 200
sudo config vlan member add 200 Ethernet0
sudo config vlan del 200
In this case - you will see error as there are members assigned to this VLAN
sudo config vlan member del 200 Ethernet0
sudo config vlan del 200
Will pass.

[VLAN] Do not allow to delete a VLAN with members

---

scripts/route_check.py

Removed code that had bug, because it is redundant
The key used is as read from APPL-DB, hence use it as such to get the value,
to help get the interface name, so it can be used for filtering out.

Dropped redundant code.

---

show/muxcable.py
tests/muxcable_test.py
utilities_common/platform_sfputil_helper.py

Summary:
This PR provides the support for adding CLI commands for retrieving cable vendor name and part number information of the muxcable.
In particular these Cli commands are supported:
` show muxcable cableinfo <port>`
added the changes in sonic-utilities/show and sonic-utilities/config by changing the muxcable.py 
To add the support for Cli for muxcable to be utilized for retrieving cable vendor name and part number information of the muxcable.
Added the changes inside sonic-utilities and tested it on the testbed
Ran the cli commands on an Arista7050cx3 testbed with Gemini cable

[show] cli support for show muxcable cableinfo

---

scripts/generate_dump

Add NOOP option for 'save_proc' and 'docker cp' commands. 
(this option can be used in pytest to check against all commands that will be executed for techsupport collection)
Added "NOOP" option to print the command without executing it.
```
admin@str-s6000-acs-8:~$ generate_dump -n
mkdir -p /var/dump/sonic_dump_str-s6000-acs-8_20210218_230943
ln -s /usr/local/bin/generate_dump /var/dump/sonic_dump_str-s6000-acs-8_20210218_230943
tar -chf /var/dump/sonic_dump_str-s6000-acs-8_20210218_230943.tar -C /var/dump sonic_dump_str-s6000-acs-8_20210218_230943
rm -f /var/dump/sonic_dump_str-s6000-acs-8_20210218_230943/sonic_dump
mkdir -p /var/dump/sonic_dump_str-s6000-acs-8_20210218_230943/proc
echo cp  -r /proc/buddyinfo /var/dump/sonic_dump_str-s6000-acs-8_20210218_230943/proc
echo cp  -r …
```

[CLI][techsupport] Add NOOP option for commands that did not have that option

---

scripts/ipintutil
setup.py
show/main.py
sonic-utilities-tests/mock_tables/asic0/config_db.json
sonic-utilities-tests/mock_tables/asic1/config_db.json
sonic-utilities-tests/mock_tables/config_db.json
sonic-utilities-tests/mock_tables/mock_multi_asic.py
sonic-utilities-tests/mock_tables/mock_single_asic.py
sonic-utilities-tests/show_ip_int_test.py
utilities_common/multi_asic.py

The PR has changes to support command `show ip interface` for multi asic platform.
Dependent on this PR: https://github.com/Azure/sonic-buildimage/pull/6792
The following changes  are done in this PR
- The code for `show ip interface` has been moved from `show/main.py` to `scripts\ipintutil`
-  Modify the code to support both single and multi asic platform
- To do this the library [pyroute2](https://pypi.org/project/pyroute2/) is used to get interface information in each namespace
- Add the following options for multi asic
-  [-n, --namespace] to allow user to display the information for given namespaces
If this option is not present the information from all the namespaces will …

[201911] show ip int changes

---

scripts/reboot

The S6000 devices, the cold reboot is abrupt and it is likely to cause issues which will cause the device to land into EFI shell. Hence the platform reboot will happen after graceful unmount of all the filesystems as in S6100.
In reboot script, if platform-specific reboot cause update script exists, run it
Issue "reboot" command to verify if the reboot is happening gracefully.
[UT_logs.txt](https://github.com/Azure/sonic-utilities/files/6017269/UT_logs.txt)
These changes are associated with https://github.com/Azure/sonic-buildimage/pull/6835.
Please cherry pick the changes to 201811, 201911 branches

[reboot] Add platform-specific reboot cause update hook

---

scripts/soft-reboot

Add a new reboot named as soft-reboot which can be performed by "kexec -e" 
Replace the platform reboot with "kexec -e" for the cold reboot case.
Verified the reboot on DUT and check the reboot-cause

Add soft-reboot reboot type

---

scripts/fast-reboot

Check if any warm restart flag is set when issuing a warm-reboot. This check avoids starting a warm reboot while another warm restart is in progress. In the scenario where a warm reboot is issued with another warm restart in progress, the warm restart flag may be reset and part of the components have a risk of doing cold reboot. 
Fix: https://github.com/Azure/sonic-buildimage/issues/6509
Check if any warm restart flag is set when issuing a warm-reboot.
Verified that warm-reboot exits when any warm restart flag is set true.

[warm-reboot] Check if warm restart flag is set when issuing a warm-reboot

---

acl_loader/main.py
tests/acl_input/acl1.json
tests/acl_input/illegal_icmp_code_300.json
tests/acl_input/illegal_icmp_code_nan.json
tests/acl_input/illegal_icmp_code_neg_1.json
tests/acl_input/illegal_icmp_type_300.json
tests/acl_input/illegal_icmp_type_nan.json
tests/acl_input/illegal_icmp_type_neg_1.json
tests/acl_input/illegal_vlan_0.json
tests/acl_input/illegal_vlan_9000.json
tests/acl_input/illegal_vlan_nan.json
tests/acl_loader_test.py
tests/aclshow_test.py
tests/mock_tables/config_db.json

- Add ICMP and VLAN fields
- Add new unit test cases
I added support for loading rules that match on VLAN ID and ICMP type/code in acl-loader.
These fields were added to the model in https://github.com/Azure/sonic-buildimage/pull/6896. This PR extracts those fields so that users can use them in their rules.
Updated unit tests. Can also verify locally that existing acl.json files can still be loaded, and those using the new fields add the correct output to config DB.

[acl-loader] Add support for matching on ICMP and VLAN info

---

config/main.py

On dual ToR systems, before performing `config reload` cache the ARP and FDB tables (similar to fast reboot) so that the standby ToR is able to resume normal operation afterwards.
Note: will require a separate change in sonic-buildimage for the `docker_image_ctl.j2` file for the SWSS container
Add an optional flag to disable caching behavior (enabled by default for dual ToR systems, disabled for all others).
Use the `fast-reboot-dump` and `filter_fdb_entries` scripts to cache the current ARP and FDB tables in `/host/config-reload`. Also create a file in the same directory to indicate to SWSS that it should restore from the cache.
* Run `config reload -d` on a dual ToR system. Confirm that no cache is created in `/host/config-reload`. 
* …

[config reload]: On dual ToR systems, cache ARP and FDB tables

---

acl_loader/main.py
sonic-utilities-tests/acl_input/acl1.json
sonic-utilities-tests/acl_input/illegal_icmp_code_300.json
sonic-utilities-tests/acl_input/illegal_icmp_code_nan.json
sonic-utilities-tests/acl_input/illegal_icmp_code_neg_1.json
sonic-utilities-tests/acl_input/illegal_icmp_type_300.json
sonic-utilities-tests/acl_input/illegal_icmp_type_nan.json
sonic-utilities-tests/acl_input/illegal_icmp_type_neg_1.json
sonic-utilities-tests/acl_input/illegal_vlan_0.json
sonic-utilities-tests/acl_input/illegal_vlan_9000.json
sonic-utilities-tests/acl_input/illegal_vlan_nan.json
sonic-utilities-tests/acl_loader_test.py
sonic-utilities-tests/aclshow_test.py
sonic-utilities-tests/mock_tables/config_db.json

- Add ICMP and VLAN fields
- Add new unit test cases
Ported https://github.com/Azure/sonic-utilities/pull/1469 to 201911.
Moved files from `tests` to `sonic-utilities-tests`.
Run unit tests + run ACL tests against 201911 image with this change and verify there is no regression.

[201911][acl-loader] Add support for matching on ICMP and VLAN info

---

scripts/fdbshow

* Skip records of FDB entries, which are linked to default Vlan 1,
to prevent exception throwing while performing
command 'show mac' or 'fdbshow'.
Resolves https://github.com/Azure/sonic-utilities/issues/894
Fixed "show mac" command execution failure in case, when the system has an FDB entry, which is linked to default Vlan 1.
The failure is caused by throwing exception, while trying to get int from None type object.
The condition has added to src/sonic-utilities/scripts/fdbshow script to handle and skip FDB entries, for which the system can not get Vlan ID.
Configure your system to receive both tagged and untagged traffic. For example, you could use the next steps:
1. Do …

[show] Fix 'show mac' output, when FDB entry with Vlan 1 is present

---

config/main.py
doc/Command-Reference.md
sonic-utilities-tests/acl_config_test.py
sonic-utilities-tests/mock_tables/config_db.json

Ported #1475 to 201911.
Moved files from tests to sonic-utilities-tests.
Run unit tests + run ACL tests against 201911 image with this change and verify there is no regression.

[201911][acl] Expand VLAN into VLAN members when creating an ACL table

---

acl_loader/main.py
tests/acl_input/acl1.json
tests/acl_input/icmp_bad_protocol_number.json
tests/acl_input/icmpv6_bad_protocol_number.json
tests/acl_input/tcp_bad_protocol_number.json
tests/acl_loader_test.py
tests/mock_tables/config_db.json

I fixed two issues:
1) The IPv6 block rule was only looking at the table name, not the table type, when determining what type of default deny rule to add. This isn't very robust.
2) Individual fields are validated, but there are some invalid combinations like mixing certain protocol numbers like TCP (6) with fields that don't make sense for TCP (like ICMP type/code fields).
1) Used the new `is_table_ipv6` method to verify that the table is a V6 dataacl table.
2) Added a post-check once all qualifiers are validated to ensure that they make sense when put together.
Added new test cases, verified that the existing ACL and CACL tests have no regression.

[acl-loader] Improve input validation for acl_loader

---

scripts/fast-reboot

Below changes are made to warmboot/fastboot script:
1. Disable swss auto-restart during warm reboot.
2. Add timeout to make sure syncd shutdown request will return in time. 5s
3. Disable trap handler after +e.
4. Make sure that syncd pre-shutdown wait won't take more than 60 seconds.
5. Make sure subsequent docker exec won't stuck for long time
6. Before shutdown, check docker exec on the relevant docker containers still works.
Testing on a physical tested - 6100 T0:
Ideal warmboot
```
$ sudo warm-reboot -vvv
Wed Mar 3 21:08:15 UTC 2021 Disabling swss auto restart ...
Wed Mar 3 21:08:16 UTC 2021 Pausing orchagent ...
Wed Mar 3 21:08:16 UTC 2021 Stopping radv ...
Wed Mar 3 21:08:17 UTC 2021 Stopping bgp ...
Wed Mar 3 21:08:17 UTC 2021 Stopped bgp ...
Wed Mar 3 21:08:20 UTC 2021 Initialize …
```

[201811] Warmboot script improvements - timeout in exec and disable swss autorestart

---

scripts/soft-reboot

Introduce a new reboot named as soft-reboot to perform a kernel reboot instead of platform reboot
Replace the platform reboot with kernel reboot from cold reboot.
Perform soft-reboot on DUT and verify all dockers and ports are up and running as expected as cold reboot
And verify the reboot-cause as soft-reboot

[201911] Add soft-reboot reboot type

---

pddf_fanutil/main.py
pddf_ledutil/main.py
pddf_psuutil/main.py
pddf_thermalutil/main.py
utilities_common/util_base.py

Fixes: #1459
- Removed the references of deprecated plugins from PDDF utils
- Removed the references of the deprecated plugins from helper utility util_base
- 
- Made PDDF debug utils python3
- Modified them to base only upon the 2.0 platform APIs classes
- Removed the helper utilities pertaining to old plugins init
Verified it locally on a AS9716 TH3 setup.
```
root@sonic:/home/admin# pddf_psuutil status
PSU    Status
-----  --------
PSU1   NOT OK
PSU2   OK
root@sonic:/home/admin# pddf_psuutil mfrinfo
PSU    Status    Manufacturer ID    Model       Serial               Fan Airflow Direction
-----  --------  -----------------  ----------  -------------------  -----------------------
PSU1   NOT OK    3Y POWER           YESM1300AM  S0A000X601825000091  exhaust
PSU2   OK        3Y POWER …
```

[PDDF] Remove references to deprecated platform plugins

---

scripts/fast-reboot

Modified pre-check for file `/host/warmboot/issu_bank.txt` in `warm-reboot` script.
Added automated recovery of  `/host/warmboot/issu_bank.txt`
Modified the `warm-reboot` script.
Need to somehow corrupt the `/host/warmboot/issu_bank.txt` (list below) and then run the `warm-reboot` command.
For testing I have modified the `warm-reboot` script - added corruption command before `check_issu_bank_file` function call.
1. Remove `issu_bank.txt`
2. Clear `issu_bank.txt`
3. Change characters count in `issu_bank.txt`
4. Write invalid content into `issu_bank.txt`
```
root@arc-switch1041:~# warm-reboot
(/host/warmboot/issu_bank.txt) does NOT exist or empty ...
To recover (/host/warmboot/issu_bank.txt) file, do the following:
$ docker exec -it syncd …
```

[warm-reboot]: added automated recover for ISSU file

---

config/muxcable.py
show/muxcable.py
tests/mock_tables/state_db.json
tests/muxcable_test.py
utilities_common/platform_sfputil_helper.py

This PR fixes the show mux status  "health" field. 
There is also support for new commands for muxcable
show muxcable hwmode muxdirection 
sudo config muxcable hwmode state active all
which can check the muxdirection and toggle the mux direction directly through eeprom
Fixed the show mux status health field
Also added these new commands
```
vdahiya@BN9-0101-0301-01UT0:~$ show muxcable hwmode muxdirection 
Port         Direction
-----------  -----------
Ethernet0    active
Ethernet4    active
Ethernet8    active
Ethernet12   active
Ethernet16   active
```
```
vdahiya@BN9-0101-0301-01UT0:~$ sudo config muxcable hwmode state active all
Muxcables at all ports will be changed to active state. Continue? [y/N]: y
Success in toggling port Ethernet0 to active
Success in toggling port Ethernet4 to …
```

[show][config] fix show mux status health field; add support for hwmode functionality to toggle mux, check mux direction for Y cable (#1467)

---

scripts/reboot

- Added platform pre check support in reboot script.
- Checking platform based changes before stopping dockers and sonic services.
On branch reboot_pre_check_201911
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   scripts/reboot
- Write a platform pre check script(platform_reboot_pre_check) and place it in /usr/share/sonic/device/\<HWSKU\>/ directory.
- If the script exit with status 0, reboot will be proceeded.
- If script exit with non-zero status, the reboot script gets stopped.
Usecase:
[Azure/sonic-buildimage#6934](https://github.com/Azure/sonic-buildimage/pull/6934)

[201911] platform pre-check for reboot

---

pytest.ini

Increase verbosity of pytest to allow for full, non-truncated error messages to appear in CI unit test results in order to help facilitate troubleshooting of unit test failures.
Replace `-v` with `-vv` in pytest options in pytest.ini
Ensure unit test failure messages are no longer truncated

[pytest] Increase verbosity

---

scripts/fast-reboot

Fix for: https://github.com/Azure/sonic-buildimage/issues/7015
Added a check for empty key before checking `WARM_RESTART_ENABLE_TABLE `
Without fix: 
```
admin@str-s6100-acs-2:~$ sudo warm-reboot -vvv
File "/usr/local/bin/sonic-db-cli", line 131, in <module>
main()
File "/usr/local/bin/sonic-db-cli", line 114, in main
execute_cmd(args.db_or_op, args.cmd, args.namespace, args.unixsocket)
File "/usr/local/bin/sonic-db-cli", line 73, in execute_cmd
resp = client.execute_command(*cmd)
File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 901, in execute_command
return self.parse_response(conn, command_name, **options)
File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 915, in parse_response
response = connection.read_response() …
```

[warm-reboot] Fix key error - check empty key before issuing redis hget

---

scripts/generate_dump

Cleanup review to remove Arista specific logic from `generate_dump`.
We now implement the vendor specific `hw-management-generate-dump.sh` hook which achieves the same purpose.
Our platform drivers install the hook under `/usr/bin/hw-management-generate-dump.sh`
Run `generate_dump` and validate that the `hw-mgmt-dump` file in the dump gets populated and has content.

[generate-dump] Remove Arista specific logic

---

scripts/decode-syseeprom
tests/decode_syseeprom_test.py

Changes when reading system EEPROM values from State DB (`decode-syseeprom -d`):
- Display CRC-32
- Display all present vendor extensions
- Display hex TLV code with lower-case `x` to match the output when reading directly from EEPROM
- If a TLV code is not available, omit it from the output rather than displaying 'N/A' for all fields
```
admin@sonic:~$ sudo decode-syseeprom -d
TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 170
TLV Name             Code      Len  Value
-------------------  ------  -----  --------------------------
Product Name         0X21        8  S6100-ON
Part Number          0X22        6  0F6N2R
Serial Number        0X23       20  TH0F6N2RCET0007600NG
Base MAC Address     0X24        6  0C:29:EF:CF:AC:A0
Manufacture Date     0X25       19 …
```

[decode-syseeprom] When reading from DB, display CRC-32 and all Vendor Extensions

---

scripts/reboot

If the script detects it is running on a dual ToR system, stop the mux container before shutting down syncd
This is necessary to prevent some links from flapping when the standby ToR is rebooted - when reboot stop syncd, the linkmgr will stop receiving heartbeats and will then tell the mux to switchover. However, since the device is rebooting, no heartbeats will be sent out. The peer ToR will see this absence of heartbeats and tell the mux to switch back to itself (the peer ToR), causing the flap.
By stopping the mux container before shutting down syncd, we prevent the rebooting ToR from switching the mux.
Read the `subtype` field from config DB. Run `systemctl stop mux` if it is `DualToR`.
* Reboot on a dual ToR device. Confirm that no …

[reboot]: Stop mux before reboot on dual ToR

---

scripts/route_check.py
tests/route_check_test.py

Log callstack on timeout.
Add self timeout and crash on timeout.
Before crash log the error and call stack.
Add a signal based alarm and the handler to print error & call stack.
Artificially introduce a sleep (> TIMEOUT, which is 2mins) in the script in any function that is in the call path.
Invoke the script. Watch it crash and note the error & stack logged in syslog.

Add self timeout and crash if exceeded.

---

config/main.py
tests/config_test.py

When we ran the commands `sudo config reload or sudo config load_minigraph`, the containers `swss, snmp, lldp, teamd, syncd, snmp, bgp, radv, pmon, dhcp_relay, telemetry, mgmt-framework` and `restapi` would be stopped and then restarted. The script `container_checker ` ran by Monit will generate false alerting messages into syslog to indicate some containers were not running during such stopping and restarting process. So this PR aims to prevent Monit from generating false alarm messages.
Before stopping services, we disable Monit to monitor the running status of containers. After restarting services, we enable Monit to monitor the running status of containers again.
I deliberately reduce the monitoring interval of Monit from 60 seconds to …

[config] Disable/enable container monitoring when stopping/starting services

---

show/vlan.py
tests/vlan_test.py

Signed-off-by: allas <allas@nvidia.com>
It fixes the community bug: 
https://github.com/Azure/sonic-buildimage/issues/6606
The problem was that there is VLAN without members `show vlan config` wasn't presented VLAN.
```
Name    VID    Member    Mode
------  -----  --------  ------
```
I modified existed code to fix this problem.
File show/vlan.py, function config(db) was modified to fill the table with VLAN even without members.
```
sudo config vlan add 10
sudo config vlan add 11
```
```
Name    VID    Member    Mode
------  -----  --------  ------
```
```
Name      VID  Member    Mode
------  -----  --------  ------
Vlan10     10
Vlan11     11
```

Fix bug: show vlan config for vlan with no members

---

config/vlan.py
tests/vlan_test.py

Handled error scenario when adding a port to Vlan which is already part of a LAG. Added unit test to cover the scenario. This is fix for the bug https://github.com/Azure/sonic-buildimage/issues/4456
Fixed the config vlan script to check if port is a port channel member before setting config_db
config vlan add 10
config portchannel add PortChannel0
config portchannel member add PortChannel0 Ethernet0
config vlan member add 10 Ethernet0
Usage: config vlan member add [OPTIONS] port
Try "config vlan member add -h" for help.
Error: Ethernet0 is part of portchannel!

Handling error scenario of adding port to Vlan which is part of LAG

---

config/muxcable.py
show/muxcable.py

There is also support for new commands for muxcable/Y cable
show muxcable hwmode switchmode
sudo config muxcable hwmode setswitchmode manual/auto all
which can basically set/display the switching modes on the cable to auto or manual 
using the cli
Also added these new commands
```
admin@STR43-0101-0101-01LT0:~$ show muxcable hwmode switchmode 
Port       Switching
---------  -----------
Ethernet0  manual
Ethernet4  manual
```
```
admin@STR43-0101-0101-01LT0:/usr$ sudo config muxcable hwmode setswitchmode manual all
Muxcable at port all will be changed to manual switching mode. Continue? [y/N]: y
Success in switching mode on port Ethernet0 to manual
Success in switching mode on port Ethernet4 to manual
admin@STR43-0101-0101-01LT0:/usr$ sudo config muxcable hwmode setswitchmode auto all …
```

[show][config] add support for setting and displaying switching modes on Y cable

---

scripts/route_check.py
tests/route_check_test.py

**Fix for hanging:**
Enforce max len on string to be printed to stdout.
With huge mismatch, the message to print can be too long to hang python print statement.
**Lower logging level:**
The log for "_details of route mismatch_" is lowered to WARNING. The caller of the route_check may log error, as it sees it fit. The failure of route_check is indicated to caller via exit code.
Simulate error (_route-mismatch_), and verify
a) message len does not exceed set MAX
b) log level is WARNING

route_check: Fix hanging & logging level

---

scripts/fast-reboot

Related PR for 201811 branch - https://github.com/Azure/sonic-utilities/pull/1474
Below changes are made to warmboot/fastboot script:
1. Disable swss auto-restart during warm reboot.
2. Add timeout to make sure syncd shutdown request will return in time. 5s
3. Disable trap handler after +e.
4. Make sure that syncd pre-shutdown wait won't take more than 60 seconds.
5. Make sure subsequent docker exec won't stuck for long time
6. Before shutdown, check docker exec on the relevant docker containers still works.
Tested warmreboot on a physical testbed.

Warmboot script improvements - timeout exec, disable swss autorestart, remove trap

---

pfcwd/main.py
tests/mock_tables/asic0/config_db.json
tests/mock_tables/asic1/config_db.json
tests/mock_tables/config_db.json
tests/pfcwd_input/pfcwd_test_vectors.py
tests/pfcwd_test.py

Prevent errors in the log when PFCWD starts on ports that PFC was not previously enabled. 
Example of such errors in the log:
```
Nov 13 17:27:22.878468 arc-switch1038 ERR swss#orchagent: :- createEntry: Failed to start PFC Watchdog on port Ethernet100
Nov 13 17:27:23.878620 arc-switch1038 NOTICE swss#orchagent: :- registerInWdDb: No lossless TC found on port Ethernet100
```
Add unit test to cover the new flow.
Before enabling PFCWD on a port, verify if PFC was previously enabled. If not, reply with an error to the user and as a warning in the log.
In the case where the command to enable PFCWD is done for all ports, the configuration will be applied for only those that has PCF enabled and for the rest the configuration will be skipped. In this case the output of the requested command will …

Enable PFCWD only on ports where PFC is enabled

---

tests/config_dpb_test.py

Signed-off-by: Sangita Maity <samaity@linkedin.com>
**What I did**
Modified the tests to use mock functionality of get_child_port function under portconfig utility.  This will remove the dependency of port config utility in the sonic-buildimage and make the test case more robust specific to the DPB cli utility.
**How I did it**
used MagicMock feature
All test cases are passed in config_dpb_test.py file
```
tests/config_dpb_test.py::TestConfigDPB::test_get_breakout_options PASSED [ 10%]
tests/config_dpb_test.py::TestConfigDPB::test_config_breakout_extra_table_warning PASSED [ 11%]
tests/config_dpb_test.py::TestConfigDPB::test_config_breakout_verbose PASSED [ 11%]
tests/config_dpb_test.py::TestConfigDPB::test_config_breakout_negative_cases PASSED [ 11%] …
```

Modified the tests to use mock functionality of get_child_port function under portconfig utility

---

scripts/fast-reboot

Path to `ssd-fw-upgrade` is not correct. Adding a path variable, that was missed in the PR https://github.com/Azure/sonic-utilities/pull/1487

[201811] Add missing variable DEVPATH to fast-reboot script

---

scripts/fast-reboot

Check if the below files exist and are executable, before executing them.
`/usr/bin/asic_config_check`
`/usr/bin/filter_fdb_entries`
Tested on a physical DUT, where the files are present/absent.

[201811] Fast reboot: check if the files are present before accessing

---

config/main.py
scripts/db_migrator.py
sonic-utilities-tests/db_migrator_test.py

Fixes: https://github.com/Azure/sonic-buildimage/issues/6659
This PR is to port a fix into 201911 branch that is already available in master branch. Original fix for master branch is here - https://github.com/Azure/sonic-utilities/pull/1209
FEATURE table is a part of 201911 image database, but absent in 201811 images. The warm upgrade from 201811 image to 201911 image fails as the feature table is missing in the DB and multiple errors are seen in syslog.
This PR fixes DB_MIGRATOR code to update missing init_cfg tables into config_db.
- How I did it
Iterate through the tables in /etc/sonic/init_cfg.json, if a table is found missing in configDB, update the configDB with the missing table. Otherwise, ignore it, so to avoid overriding configDB tables with init_cfg.
Verified …

Copy missing values from INIT_CFG to config_db during db_migration

---

scripts/reboot
show/reboot_cause.py
tests/reboot_cause_test.py

If the rebooting of SONiC device was caused by kernel panic, then the CLI command `show reboot-cause` should show `Kernel Panic`.
Currently if kernel was panicked, then the device would be rebooted. The `reboot` script wrote a message into `reboot-cause.txt`. I just updated the content of this message.
I verified this change on the virtual switch in the following steps:
1. Trigger kernel panic: `echo c > /proc/sysrq-trigger`
2. After device was rebooted, run the CLI `show reboot-cause`:
`admin@vlab-01:~$ show reboot-cause`
`Kernel Panic [Time: Tue 09 Mar 2021 03:03:56 AM UTC]`
`admin@vlab-01:~$ show reboot-cause`
`User issued 'kdump' command [User: kdump, Time: Mon 08 Mar 2021 01:47:43 AM UTC]`
`admin@vlab-01:~$ show reboot-cause`
`Kernel …

[reboot] User-friendly reboot cause message for kernel panic

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build_and_install_module.sh
.azure-pipelines/docker-sonic-vs/Dockerfile
.azure-pipelines/test-docker-sonic-vs-template.yml
azure-pipelines.yml

[ci]: add vstest

---

acl_loader/main.py
tests/acl_input/acl1.json
tests/acl_loader_test.py

dataplane acl has v4 and v6 type. in case the rule does not
specify the iptype, the acl_loader will automatically add
the match for the iptype based on the table type.
for l3 table, it will add ethertype = 0x800
for l3v6 table, it will add iptype = ipv4any
unit test

[acl_loader]: add iptype match to the rules for dataplane acl

---

scripts/reboot

As introduced by the [kernel doc](https://mjmwired.net/kernel/Documentation/sysrq.txt#37), we do not need the line 20 in reboot script since it only influenced the capability to reboot the Linux kernel by hitting the combo magic key of keyboard.
I removed this command.
I can reboot the Linux kernel by running command `echo b > /proc/sysrq-trigger` with root privilege. As such, there is no need to keep the line 20 in reboot script.

[reboot] No need enable the Linux magic system request key

---

config/main.py

Nightly test found a failure when we ran the command `sudo config reload/load_minigraph`, The error message is:
admin@str-a7050-acs-1:~$ sudo config reload -y
Disabling container monitoring ...
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/config_db.json --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate
Resetting failed status on bgp.service
Resetting failed status on caclmgrd.service
Resetting failed status on dhcp_relay.service
Resetting failed status on hostcfgd.service
Resetting failed status on hostname-config.service
Resetting failed status on interfaces-config.service
Resetting failed status on lldp.service
Resetting failed status on …

[config] Eliminate race condition between reloading Monit config and monitoring container_checker

---

fdbutil/filter_fdb_entries.py

Fix fast-reboot fdb-filtering issue for IPv6 addresses.
This change is already present in master branch. Original PR: https://github.com/Azure/sonic-utilities/pull/1295
Update 201811 branch with this fix.

[201811] Fix fast-reboot fdb filtering for IPv6 addresses

---

config/muxcable.py
show/muxcable.py
tests/muxcable_test.py

Summary:
This PR provides the support for adding CLI commands for activatie, download, upgrade firmware on the Y-cable
In particular these Cli commands are supported:
sudo config muxcable firmware download Ethernet0
sudo config muxcable firmware rollback Ethernet0
sudo config muxcable firmware download ~/AEC_WYOMING_B52Yb0_MS_0.6_20201218.bin Ethernet0
Added the support for firmware upgrade CLI on Y cable
added the changes in sonic-utilities/show and sonic-utilities/config by changing the muxcable.py
```
admin@STR43-0101-0101-01LT0:/usr$ sudo config muxcable firmware download ~/AEC_WYOMING_B52Yb0_MS_0.6_20201218.bin Ethernet0
firmware download successful Ethernet0
admin@STR43-0101-0101-01LT0:~/credo_script_01_21$ sudo config muxcable …
```

[show][config] cli support for firmware upgrade on Y-Cable

---

scripts/fast-reboot-dump.py

This PR https://github.com/Azure/sonic-utilities/pull/1393 merged after PR: https://github.com/Azure/sonic-utilities/pull/1392
This caused the first PR to be not aligned with SonicV2Connector change.
This PR motivation is to fix it.

[fast-reboot] Fix fast-reboot-dump.py SonicV2Connector after late merge

---

scripts/fast-reboot-dump.py
setup.py
tests/fast_reboot_dump_dbs/APPL_DB.json
tests/fast_reboot_dump_dbs/ASIC_DB.json
tests/fast_reboot_dump_test.py

Add PortChannels to the list of interfaces (port_id_2_iface) to support FDB dump for PortChannel in a VLAN group.
Fixes https://github.com/Azure/sonic-buildimage/issues/4793
This PR is the 201911 version of the original PR: https://github.com/Azure/sonic-utilities/pull/1393
* Get LAG ID from the DB.
* Find the LAG name from APP DB.
* Add it to the list of 'port_id_2_iface' to be used.
Reproduce the issue mentioned on this PR and try to run fast-reboot with this fix.
Traceback:
src_ifs = {map_mac_ip_per_vlan[vlan_name][dst_mac] for vlan_name, dst_mac, _ in arp_entries}
KeyError: 'b8:59:9f:a8:e2:00'
**- New command output (if the output of a …

[fast-reboot] Fix dump script to support PortChannels in a VLAN group [201911]

---

.azure-pipelines/test-docker-sonic-vs-template.yml

use the same snapshot of pytests as the docker-sonic-vs image
in case sonic-swss build failure, the docker-sonic-vs may not
match exactly the same pytest checkout from master

[ci]: use the same snapshot of pytests as the docker-sonic-vs image

---

fwutil/lib.py

* Fixed next image mount
* Removed `lstrip`
1. root@sonic:/home/admin# fwutil update chassis component <component_name> fw -i next
```bash
root@sonic:/home/admin# fwutil update chassis component SSD fw -i next
mount: /tmp/image-IC.202012.53-aee4892c_Internal-fs: special device /host/image-IC.202012.53-aee4892c_Internal/fs.squashfs does not exist.
Error: Command 'mount -t squashfs /host/image-IC.202012.53-aee4892c_Internal/fs.squashfs /tmp/image-IC.202012.53-aee4892c_Internal-fs' returned non-zero exit status 32.. Aborting...
Aborted!
root@sonic:/home/admin# fwutil update chassis component SSD fw -i next
mount: /tmp/image-SONIC.202012.55-0269fc1_Internal-overlay: special device overlay does not exist.
Error: Command 'mount -n -r -t …
```

[fwutil]: Fix next image mount

---

consutil/main.py
doc/Command-Reference.md
tests/console_test.py

Include flow control status in `show line` result.
1. Render the flow control option in `show line` table
2. Update unit test case
3. Update document
1. UT pass
2. Install and test the new package in a physical SONiC box
```
admin@sonic:~$ show line
Line    Baud    PID    Start Time    Device
------  ------  -----  ------------  --------
1    9600      -             -
2       -      -             -
3       -      -             -
4       -      -             -
5       -      -             -
```
```
admin@sonic:~$ show line
Line    Baud    Flow Control    PID    Start Time    Device
------  ------  --------------  -----  ------------  --------
1    9600         Enabled      -             -
2       -        Disabled      -             -
3       -        Disabled      -             -
4 …
```

[console] Include Flow Control status in show line result

---

scripts/route_check.py

Declared uninitialized variable, before its use.
No logical code change, other than avoiding crash in a print statement.
Little tough. We need a APP & ASIC DBs in sync state and run route_check.

Fixed the possibility of using uninitialized variable in route_check.py

---

config/config_mgmt.py
pfcwd/main.py
tests/aclshow_test.py
tests/buffer_test.py
tests/config_dpb_test.py
tests/config_mgmt_test.py
tests/config_test.py
tests/crm_test.py
tests/decode_syseeprom_test.py
tests/feature_test.py
tests/neighbor_advertiser_test.py
tests/pfcstat_test.py
tests/pfcwd_test.py
tests/port2alias_test.py
tests/psushow_test.py
tests/watermarkstat_test.py
utilities_common/general.py
utilities_common/util_base.py

Migrate from using the `imp` module to using the `importlib` module. As of Python 3, the `imp` module has been deprecated in favor of the `importlib` module.
Place logic in a new function, `load_module_from_source()` in a new file, `utilities_common/general.py`
Also fix some formatting
Eliminate all importing of the `imp` module, and replace all which were actually used with imports of the `importlib` module, and modify all affected code appropriately.
Test all affected utilities and unit tests.

Use 'importlib' module in lieu of deprecated 'imp' module

---

scripts/route_check.py
scripts/sfpshow
tests/mock_tables/appl_db.json
tests/mock_tables/asic0/appl_db.json
tests/mock_tables/asic1/appl_db.json
tests/mock_tables/asic2/appl_db.json
tests/route_check_test.py

Inband port can be made available in PORT table. But regular port handlngs are
not applicable for Inband port. This PR has change to avoid regular port handling for inband port
Ref: VOQ HLD https://github.com/Azure/SONiC/blob/master/doc/voq/voq_hld.md
The inband port is considered similar to back plane port. An inband_prefix = "Ethernet-IB" and this is checked in all places to avoid regular port handling.
- Expose a port with name prefixed with "Ethernet-IB" to SONiC via port_config.ini
- Have an entry in the PORT table for this port with name prefixed with "Ethernet-IB"
- When the system is booted, there should not be errors related to Inband interface
**- Previous command output (if the output of a command-line utility has …

[voq/inbandif] Voq inbandif port

---

sonic_installer/bootloader/aboot.py

These issues are only seen on secureboot enabled platform.

sonic-installer: fix py3 issues in bootloader.aboot

---

scripts/fdbshow

Add lookup table for bvid to vlan translations.
bvid_tlb will store previous successful translations from slow  get_vlan_id_from_bvid()
This patch does not change the output from the command, only speeds up it for case of 10k+ MAC tables.

cache the bvid to vlan translations

---

scripts/intfutil
sonic-utilities-tests/intfutil_test.py
sonic-utilities-tests/mock_tables/appl_db.json
sonic-utilities-tests/mock_tables/config_db.json
sonic-utilities-tests/multi_asic_intfutil_test.py

What/Why I did:
Fix in 201911 branch:
```
- show interface status Ethernet* 
- intfutil -c status -i <interface>
```
How I did:
- Pass the interface name 
- Skip Port channel Output when interface name is provided
How I verfied:
Added unit test case. Some of this test case are missing for master also and will be added as separate PR.

[201911] Fix show interface status command when interface is provided

---

scripts/fast-reboot-dump.py

It seems like this change is not backported to 202012: https://github.com/Azure/sonic-utilities/pull/1392
So this PR https://github.com/Azure/sonic-utilities/pull/1546 Is not required on 202012 branch.
It was cherry-picked to 202012 and now the fast-reboot-dump script is broken.
Revert the commit.
Run fast-reboot on 202012 branch.

[fast-reboot] Revert "Fix fast-reboot-dump.py SonicV2Connector after late merge (#1546)" [202012]

---

scripts/generate_dump

Update "show ip interface" command
After adding multi ASIC support to "show ip interface" CLI command, the existing command in tech support collection script will not work.
Updated the command
```
admin@svcstr-nmasic-acs-1:~$ show ip interface -d all
Interface        Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
---------------  --------  -------------------  ------------  --------------  -------------
Loopback0                  10.1.0.32/32         up/up         N/A             N/A
Loopback4096               8.0.0.0/32           up/up         N/A             N/A
8.0.0.1/32                         N/A             N/A
8.0.0.2/32                         N/A             N/A
8.0.0.3/32                         N/A             N/A
8.0.0.4/32 …
```

[techsupport] Update show ip interface command

---

config/muxcable.py
show/muxcable.py
tests/muxcable_test.py

Summary:
This PR provides the support for adding CLI commands for activate, download, upgrade firmware on the Y-cable
In particular these Cli commands are supported:
sudo config muxcable firmware download Ethernet0
sudo config muxcable firmware rollback Ethernet0
sudo config muxcable firmware download ~/AEC_WYOMING_B52Yb0_MS_0.6_20201218.bin Ethernet0
Added the support for firmware upgrade CLI on Y cable
added the changes in sonic-utilities/show and sonic-utilities/config by changing the muxcable.py
```
admin@STR43-0101-0101-01LT0:/usr$ sudo config muxcable firmware download ~/AEC_WYOMING_B52Yb0_MS_0.6_20201218.bin Ethernet0
firmware download successful Ethernet0
admin@STR43-0101-0101-01LT0:~/credo_script_01_21$ sudo config muxcable …
```

[show][config] cli support for firmware upgrade on Y-Cable (#1528)

---

config/kube.py
tests/kube_test.py

Dropped IP validation as server takes URL.
Provide a URL for IP in kube server config command.

No more IP validation as it is more likely a URL

---

config/main.py
tests/acl_config_test.py

Fixes https://github.com/Azure/sonic-buildimage/issues/4934
I discovered that using the @ syntax to insert the port list as a comma-separated list/array actually causes the port list to be deleted when the same table is `config add`-ed multiple times. Using a list works. (We still need to determine the root cause for why the @ syntax fails).
Updated the tests and ran the command locally to verify the fix. Still working on adding a new regression test case for this.

[acl] Use a list instead of a comma-separated string for ACL port list

---

scripts/reboot

- Added platform pre check support in reboot script.
- Checking platform based changes before stopping dockers and sonic services.
- Porting changes in master from 201911 branch Azure/sonic-utilities#1472
On branch reboot_pre_check_201811
Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git checkout -- ..." to discard changes in working directory)
modified:   scripts/reboot
- Write a platform pre check script(platform_reboot_pre_check) and place it in /usr/share/sonic/device/<HWSKU>/ directory.
- If the script exit with status 0, reboot will be proceeded.
- If script exit with non-zero status, the reboot script gets stopped.

[201811] platform pre-check for reboot

---

scripts/reboot

- Added platform pre check support in reboot script.
- Checking platform based changes before stopping dockers and sonic services.
- Porting changes in master from 201911 branch Azure/sonic-utilities#1472
On branch reboot_pre_check_master
Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git checkout -- ..." to discard changes in working directory)
modified:   scripts/reboot
- Write a platform pre check script(platform_reboot_pre_check) and place it in /usr/share/sonic/device/<HWSKU>/ directory.
- If the script exit with status 0, reboot will be proceeded.
- If script exit with non-zero status, the reboot script gets stopped.

platform pre-check for reboot in master branch

---

config/main.py
sonic-utilities-tests/acl_config_test.py

How I did it
I discovered that using the @ syntax to insert the port list as a comma-separated list/array actually causes the port list to be deleted when the same table is config add-ed multiple times. Using a list works. (We still need to determine the root cause for why the @ syntax fails).
Updated the tests and ran the command locally to verify the fix. Still working on adding a new regression test case for this.

[201911][acl] Use a list instead of a comma-separated string for ACL port list

---

config/aaa.py
config/main.py
show/main.py
tests/aaa_test.py
tests/radius_test.py

Radius Management User Authentication Feature
HLD: https://github.com/Azure/SONiC/blob/master/doc/aaa/radius_authentication.md
This is the CLI only. The changes are reflected in the Redis Config DB.
admin@sonic:~$ show radius
RADIUS global auth_type pap (default)
RADIUS global retransmit 3 (default)
RADIUS global timeout 5 (default)
RADIUS global passkey <EMPTY_STRING> (default)
admin@sonic:~$
admin@sonic:~$ sudo config radius
Usage: config radius [OPTIONS] COMMAND [ARGS]...
RADIUS server configuration
Options:
Commands:
add         Specify a RADIUS server
authtype    Specify RADIUS server global auth_type [chap | pap | mschapv2]
default     set its default configuration
delete      Delete a RADIUS server
nasip       Specify RADIUS server global …

RADIUS Management User Authentication Feature

---

consutil/main.py
tests/console_test.py

Display a success message after line been cleared
Simply echo a message after line cleared
Update unit test case
```
admin@sonic:~$ sudo sonic-clear line 1
admin@sonic:~$ 
```
```
admin@sonic:~$ sudo sonic-clear line 1
Cleared line
admin@sonic:~$ 
```

[console] Display success message after line cleared

---

config/main.py
tests/config_int_ip_common.py
tests/config_int_ip_test.py
tests/conftest.py
tests/crm_test.py
tests/int_ip_input/config_db.json
tests/vlan_test.py

Resolves https://github.com/Azure/sonic-buildimage/issues/7028
Added checking of static routes, related to the interface, before deleting of the last IP entry to prevent deleting the RIF if a static route is present in the system.
The related unit tests has added.
By checking IPv4 and IPv6 routes, received from Zebra.
1. `sudo config int ip add Ethernet2 10.0.0.18/31`
2. `sudo config route add prefix 20.0.0.1/32 nexthop Ethernet2`
3. `sudo config int ip rem Ethernet2 10.0.0.18/31`
If `10.0.0.18/31` is the last IP entry, you will receive the next error: `Error: Cannot remove the last IP entry of interface Ethernet2. A static ip route is still bound to the RIF.`
The similar situation is for IPv6: `Error: Cannot remove the last IP entry of interface Ethernet2. A static ipv6 route is still …

Fix remove ip rif

---

scripts/disk_check.py
setup.py
tests/disk_check_test.py

There is a bug that occasionally turn root-overlay as RO. This makes /etc & /home as RO. This blocks any new remote user login, as that needs to write into /etc & /home.
This tool scans /etc & /home (_or given dirs_) as in RW or RO state. If RO, it could create a writable overlay using tmpfs.
This is transient and stays until next reboot. Any write after the overlay will be lost upon reboot.
But this allows new remote users login.
Create upper & work dirs in /run/mount (tmpfs). Mount /etc & /home as lowerdirs and use the same name for final merge. This allows anyone opening a file in **/etc or /home to operate on the merged overlay, transparently.**
Mount any dir on tmpfs ( mount -t tmpfs tmpfs test_dir)
remount as RO (mount -o remount,ro test_dir)
Pass that dir to this script. …

disk_check: Check & mount RO as RW using tmpfs

---

show/muxcable.py

For 202012 branch ConfigDBConnector() is imported from swsssdk. 
So to use  ConfigDBConnector() we still have to import from swsssdk instead of swsscommon.
The [https://github.com/Azure/sonic-utilities/pull/1558](url) changed ConfigDBConnector() to be imported from swsscommon in show/muxcable.py
which causes unit test failure in sonic-utilities. 
This PR fixes that. 
changed the import
ran a local build to pass unit tests

[show] revert back to swsssdk from swsscommon for ConfigDBConnector() for muxcable

---

tests/db_migrator_test.py

Enhancement: handle the case that no buffer change in the latest database version
Current, the following two versions are the same:
- The latest version changed by mellanox_buffer_migrator
- The latest version in CONFIG_DB
That won't be true if another part in CONFIG_DB is updated. In that case, the latest version in CONFIG_DB will be greater than the latest version in mellanox_buffer_migrator.
However, this can break the buffer migrator unit test:
- The db_migrator will always migrate the database to the latest version
- The config database version check will fail in case the latest version in the config database doesn't match that defined in the buffer migrator.
This is to support this case.
Advance the database version in the expected …

[test][db migrator] Enhancement: handle the case that no buffer change in the latest database version

---

setup.py
show/bgp_frr_v4.py
show/bgp_frr_v6.py
sonic-utilities-tests/bgp_command_input/bgp_neighbor_test_vector.py
sonic-utilities-tests/bgp_command_input/bgp_network_test_vector.py
sonic-utilities-tests/bgp_commands_input/bgp_neighbor_test_vector.py
sonic-utilities-tests/bgp_commands_input/bgp_network_test_vector.py
sonic-utilities-tests/conftest.py
sonic-utilities-tests/show_bgp_neighbor_test.py
sonic-utilities-tests/show_bgp_network_test.py
utilities_common/bgp_util.py
utilities_common/multi_asic.py

This is port of the PR https://github.com/Azure/sonic-utilities/pull/1574 in 201911 branch
This PR is to add support for the commands show ip bgp neighbor and show ip bgp network
Add unit tests for these commands
How I did it
Add change to get the bgp neighbor and network information from each namespace
Check the command works on single and multi asic platforms
UT  results
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /sonic/src/sonic-utilities, inifile: pytest.ini
plugins: cov-2.4.0
collected 314 items
sonic-utilities-tests/acl_config_test.py ............ …

[201911]: add show bgp neigh/network support for multi asic

---

scripts/vnet_route_check.py
setup.py
tests/vnet_route_check_test.py

Added "vnet_route_check" tool for check VNET route consistency.
vnet_route_check.py: tool that verifies VNET routes consistancy between SONiC and vendor SDK DBs.
Logically VNET route verification logic consists of 3 parts:
1. Get VNET routes entries that are missed in ASIC_DB but present in APP_DB.
2. Get VNET routes entries that are missed in APP_DB but present in ASIC_DB.
3. Get VNET routes entries that are missed in SDK but present in ASIC_DB.
Returns 0 if there is no inconsistancy found and all VNET routes are aligned in all DBs.
Returns -1 if there is incosistancy found and prints differences between DBs in JSON format to standart output.
Added "vnet_route_check" script with the relevant VNET …

[vnet] Add "vnet_route_check" script

---

setup.py

added 'pg-drop' to the filesysytem of sonic
add 'scripts/pg-drop' to setup.py file
check that 'pg-drop' script exists in /usr/local/bin/pg-drop

[pg-drop counter] Add pg-drop script to sonic filesystem

---

scripts/route_check.py

Fixed errors related to VNET routes printed by ```route_check``` script.
Filtered out VNET routes for the list of routes that are taken into account by ```route_check``` script.
1. Configure VNET routes and run ```route_check``` script on the switch
2. Verify that no errors are onserved

[route_check] Filter out VNET routes

---

scripts/neighbor_advertiser
tests/neighbor_advertiser_test.py

Check for existing tunnels and use them if present while creating tunnel mappings
Modify the neighbor_advertiser script logic
Unittest has been updated

[neighbor_advertiser] Use existing tunnel if present for creating tunnel mappings

---

show/main.py

Modified show version command to pick serial number from STATE_DB if it was populated instead of getting it from EEPROM.
Check state_db to see if serial number EEPROM section is populated. If yes use the data from DB. If not, read it from the decode-syseeprom
Verify running 'show version' with and without pmon running to validate both scenarios, since eepromd in pmon populates the EEPROM table in state_db

Fixing serial number read to get from DB if it is populated

---

config/main.py
show/main.py
tests/config_snmp_test.py
tests/mock_tables/config_db.json
tests/show_snmp_test.py

I created these new show commands: 
show runningconfiguration snmp 
show runningconfiguration snmp contact
show runningconfiguration snmp location
show runningconfiguration snmp community
show runningconfiguration snmp user
show runningconfiguration snmp contact --json
show runningconfiguration snmp location --json
show runningconfiguration snmp community --json
show runningconfiguration snmp user --json 
These commands will check in the REDIS ConfigDB and get the information.
I created a standard snmp schema that was approved here: 
https://github.com/Azure/SONiC/pull/731
I also moved from using only the snmp.yml file to using the ConfigDB for the device. 
https://github.com/Azure/sonic-buildimage/pull/6205
Jinja template update: …

[show][config] Add new snmp commands

---

sonic_installer/common.py
sonic_installer/main.py

To not fail when user is doing downgrade
Fix https://github.com/Azure/sonic-buildimage/issues/7518
Do not fail when user is doing downgrade.
Ignoring failures.
On master image install 202012 image.

[sonic_installer] dont fail package migration

---

scripts/sfpshow

Gracefully handle improper 'specification_compliance' field
The 'specification_compliance' field of transceiver info is expected to be a string representation of a dictionary. However, there is a chance, upon some kind of platform issue that a vendor's platform API returns something like 'N/A'. In this case, sfpshow would crash. Rather than crash, sfpshow should handle this gracefully and output 'N/A' instead.
Run sfpshow on a device where the 'specification_compliance' field of transceiver info is not a string representation of a dictionary.
N/A -- sfpshow would crash
```
Ethernet0: SFP EEPROM detected
Application Advertisement: N/A
Connector: N/A
Encoding: N/A
Extended Identifier: N/A
Extended RateSelect Compliance: N/A
Identifier: N/A
N/A: N/A
Nominal Bit Rate(100Mbs): N/A …
```

[sfpshow] Gracefully handle improper 'specification_compliance' field

---

scripts/reboot

The S6000 devices, the cold reboot is abrupt and it is likely to cause issues which will cause the device to land into EFI shell. Hence the platform reboot will happen after graceful unmount of all the filesystems as in S6100.
This has been merged in master through #1454 and raising it separately since it can't be cherry picked cleanly.
It is related to sonic-buildimage PR Azure/sonic-buildimage#6923
In reboot script, if platform-specific reboot cause update script exists, run it
Issue "reboot" command to verify if the reboot is happening gracefully.
[UT_logs_201811.txt](https://github.com/Azure/sonic-utilities/files/6432233/UT_logs_201811.txt)

[201811] Add platform-specific reboot cause update hook

---

config/vxlan.py
tests/vxlan_test.py

Remove extra 'CONFIG_DB' argument from db.cfgdb.get_keys()
Signed-off-by: shikenghua <kh_shi@edge-core.com>
Fix `config vxlan evpn_nvo add` command error.
Remove extra argument `'CONFIG_DB'` from `db.cfgdb.get_keys()`.
Run `config vxlan evpn_nvo add` command and verify the output.
admin@as7816-64x-3:~$ sudo config vxlan evpn_nvo add nvo1 vtep1
File "/usr/local/bin/config", line 8, in <module>
return …

[config][vxlan] fix 'vxlan evpn_nvo add' command error

---

sonic_installer/main.py

Skip sonic package migration on aboot platform.
Added a warning and skip the migration.
I changed AbootBootloader to OnieInstallerBootloader to test on my Onie device. I don't have Aboot device.

[sonic_installer] temporary fix: don't migrate packages on aboot platforms

---

config/main.py
tests/sflow_test.py

Signed-off-by: Venkatesan Mahalingam <venkatesan_mahalinga@dell.com>
The changes are copied from https://github.com/Azure/sonic-utilities/pull/845 to resolve the conflict.
The dependent swss PR : https://github.com/Azure/sonic-swss/pull/1728
Adding the 'default' option to allow user to set an interface's
sFlow sampling-rate back to default.
- What I did
Add a 'default' option so users can revert to the default sFlow sampling-rate on an interface.
- How I did it
Updated the config script in config/main.py.
Unit-test:
```
root@sonic:~# show sflow interface | less
sFlow interface configurations
+-------------+---------------+-----------------+
| Interface   | Admin State   |   Sampling Rate |
+=============+===============+=================+
| Ethernet0   | up            | …
```

Add 'default' option for sFlow.

---

config/config_mgmt.py
config/main.py
tests/config_mgmt_test.py

Changes:
-- Shutdown the interfaces after config validation while Dy Port Breakout.
-- Validate del ports before calling breakOutPorts API.
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
Fixes https://github.com/Azure/sonic-buildimage/issues/6646, https://github.com/Azure/sonic-buildimage/issues/6631, 
Changes:
-- Shutdown the interfaces after config validation while Dy Port Breakout.
-- move shutdown part to config_mgmt.py, because we need to shutdown only when DPB is initiated.
```
svc-lnos-user@server10:/home/svc-lnos-user/praveen/sonic-buildimage/src/sonic-swss/tests$ cat test_port_dpb_system.py | grep -A 4 -B 4 Uncomment
self.dvs_acl.verify_acl_table_count(1)
#TBD: Uncomment this, or explain why Ethernet0 is being …
```

Shut down interface before dynamic port breakout

---

setup.py

The latest version of pyroute2 introduce breaking change:
```
______________________ ERROR collecting tests/aaa_test.py ______________________
ImportError while importing test module '/__w/1/s/tests/aaa_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/__w/1/s/.eggs/pyroute2-0.6.1-py3.7.egg/pyroute2/__init__.py:44: in <module>
from importlib import metadata
E   ImportError: cannot import name 'metadata' from 'importlib' (/usr/lib/python3.7/importlib/__init__.py)
During handling of the above exception, another exception occurred:
/usr/lib/python3/dist-packages/_pytest/python.py:450: in _importtestmodule
mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3/dist-packages/py/_path/local.py:668: in pyimport
__import__(modname) …
```

Limit pyroute2 version range due to upstream broken

---

show/muxcable.py
tests/mock_tables/state_db.json
tests/muxcable_test.py

Added support for show muxcable metrics. This essentially records what events came to different modules per se
for toggling the mux from one state to another.
for example 
`admin@sonic$ show muxcable metrics Ethernet0 --json`
`{`
`"linkmgrd_switch_active_start": "2021-May-13 10:00:21.420898",`
`"linkmgrd_switch_standby_end": "2021-May-13 10:01:15.696728",`
` "linkmgrd_switch_unknown_end": "2021-May-13 10:00:26.123319",`
` "xcvrd_switch_standby_end": "2021-May-13 10:01:15.696051",`
`"xcvrd_switch_standby_start": "2021-May-13 10:01:15.690835"`
`}`
or 
`admin@sonic:$ show muxcable metrics Ethernet0`
`PORT       EVENT                         TIME`
`---------  ----------------------------  ---------------------------`
`Ethernet0 …

[show] add support for muxcable metrics

---

tests/db_migrator_input/config_db/non-default-config-expected.json
tests/db_migrator_test.py

Originally, the method `advance_version_for_expected_database` was introduced (in Azure/sonic-utilities#1566) to handle the case the latest version in `CONFIG_DB` is greater than the latest version in `mellanox_buffer_migrator`.
Now there are other database migrators whose test cases can also encounter this situation, like port auto-negotiation (Azure/sonic-utilities#1568) and port-channel for LACP key (Azure/sonic-utilities#1473).
So I would like to make the method public, available for all database migrators.
Related database migrator test cases have been updated accordingly.
Run the unit test.

[test][db_migrator] Make advance_version_for_expected_database available for other db migrator test cases as well

---

scripts/fast-reboot-dump.py

This PR is to address the Unicode issue in ```fast-reboot-dump.py``` script in ```201911```. 
There is another PR that addresses same issue in master image #1164 
However, ```builtins``` package is not available in ```201911``` image.
```
Python 2.7.13 (default, Apr 16 2021, 14:02:03) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import builtins
File "<stdin>", line 1, in <module>
ImportError: No module named builtins
``` 
So, I create this PR for 201911 branch to fix the issue in another way.
Add a custom method to convert ```string``` to ```unicode```.
Verified on MSN2700, running ```SONiC.20191130.72```. 
First populate some FDB entry and ARP …

Fix Unicode issue in ipaddress for python2

---

scripts/fdbclear

Fdb entries can be deleted with user specifying vlan or port or vlan&&port.
fdborch is in charge of deleting fdb entries in another issues#1064,and it had pull request.
-->

[fdb]cli: fdb entries are cleared according to vlan or port or vlan&&port

---

show/muxcable.py
tests/muxcable_test.py

This PR adds support for an option to display firmware version of muxcable of only active banks. 
The new output would look like this in case an active flag is passed to the command line
`admin@STR43-0101-0101-01LT0:~$ show muxcable firmware version Ethernet0 --active`
`{`
`"version_self_active": "0.7MS",`
`"version_peer_active": "0.7MS",`
`"version_nic_active": "0.7MS", `
`}`
added an option to display active banks only for display muxcable firmware version
added the changes in show/muxcable.py and added testcases
ran the command on the testbed. 
N/A
N/A

[show] support for show muxcable firmware version of only active banks

---

consutil/lib.py
consutil/main.py
tests/console_test.py

Address issue https://github.com/Azure/sonic-utilities/issues/1639
Force refresh each lines status during show line
Add unit tests:
Cases:
```
tests/console_test.py::TestConfigConsoleCommands::test_enable_console_switch PASSED [ 19%]
tests/console_test.py::TestConfigConsoleCommands::test_disable_console_switch PASSED [ 19%]
tests/console_test.py::TestConfigConsoleCommands::test_console_add_exists PASSED [ 20%]
tests/console_test.py::TestConfigConsoleCommands::test_console_add_no_baud PASSED [ 20%]
tests/console_test.py::TestConfigConsoleCommands::test_console_add_name_conflict PASSED [ 20%]
tests/console_test.py::TestConfigConsoleCommands::test_console_add_success PASSED [ 20%]
tests/console_test.py::TestConfigConsoleCommands::test_console_del_non_exists PASSED [ 20%] …
```

[console][show] Force refresh all lines status during show line

---

sonic_installer/bootloader/aboot.py
sonic_installer/bootloader/bootloader.py
sonic_installer/main.py

Fixes https://github.com/Azure/sonic-buildimage/issues/7566
The `get_rootfs_path` contextmanager was recently repurposed to implement
`get_file_in_image` . It then got used as a function by leveraging some
python complexity to bypass the restrictions coming with the contextmanager construct.
This was a conscious decision to prevent exactly what happened.
The method was then called multiple times to compute relative paths to the image directory.
Simple path joins using `new_image_dir` could have been performed instead.
The `get_rootfs_path` implementation for Aboot bootloaders behaves differently
when a rootfs is extracted or kept within the SWI image. It also behaves differently on secureboot systems.
The updated method was used by providing parameters it was never meant to process.
Over …

Fix Aboot breakage sonic-installer due to package migration

---

sonic_package_manager/manager.py

…temporary file
Since installation happens inside context manager "with tempfile.NamedTemporaryFile()"
it may be that depending on file size/number of writes the docker image isn't fully written
to the disk. In practice a small test docker image was succesfully migrated but when trying with
larger onces it started to file. This change fixes the issue by adding a flush.
Fixed corrupted tarfile written.
Added flie.flush().
Perform S2S package migration with a big docker image.

[sonic_package_manager] flush file to ensure integrity

---

scripts/db_migrator.py
tests/db_migrator_input/config_db/feature-expected.json
tests/db_migrator_input/config_db/feature-input.json
tests/db_migrator_input/init_cfg.json
tests/db_migrator_test.py

This change is in addition to https://github.com/Azure/sonic-utilities/pull/1522.
The init_cfg.json may have important fields added to configuration, while in
previous fix these entries will not be added when table already exists.
This change fixes this behaviour. Also, in order to preserve users auto_restart
configuration a special logic for migrating CONTAINER_FEATURE table has been implemented.
A test to cover this scenario is added.
Implemented migration for old FEATURE table.
Added migrate_feature().
Old 201911 with CONTAINER_FEATURE and old FEATURE schema upgrade to new 202012.

[202012] [db_migrator] fix old 1911 feature config migration to a new one.

---

scripts/db_migrator.py
tests/db_migrator_input/config_db/feature-expected.json
tests/db_migrator_input/config_db/feature-input.json
tests/db_migrator_input/init_cfg.json
tests/db_migrator_test.py

This change is in addition to https://github.com/Azure/sonic-utilities/pull/1522.
The init_cfg.json may have important fields added to configuration, while in
previous fix these entries will not be added when table already exists.
This change fixes this behaviour. Also, in order to preserve users auto_restart
configuration a special logic for migrating CONTAINER_FEATURE table has been implemented.
A test to cover this scenario is added.
Implemented migration for old FEATURE table.
Added migrate_feature().
Old 201911 with CONTAINER_FEATURE and old FEATURE schema upgrade to new master.

[db_migrator] fix old 1911 feature config migration to a new one.

---

scripts/vnet_route_check.py

Fixed issue when VNET route check detects some routes as missed they are really configured.
Fixed logic for getting VNET routes from ASIC DB in order to correctly retrieve all the configured in ASIC DB VNET routes.
* Run VNET test from sonic-mgmt
* Run VNET route check script and verify that no missing routes are reported.

[vnet_route_check] [201911] Fix logic for getting VNET routes from ASIC DB

---

config/aaa.py

[config][tacacs+] Change tacacs+ minimum timeout value base on specification.
- What I did
Change the minimum timeout value of TACACS+ to follow the value in specification.
- Why I did it
The minimum timeout value of tacacs CLI is not the same as
specification, so modify the CLI to make it follow it.
- How I verified it
Verified the minimum value is 1 on switch.
Signed-off-by: Po-hong Guo <steven_guo@edge-core.com>

[config][tacacs+] Change tacacs+ minimum timeout value base on specification.

---

config/muxcable.py
tests/mock_tables/config_db.json
tests/muxcable_test.py

This PR adds support for an option to  configure muxcable mode to  a `manual` mode. The manual mode is in addition
to `auto\active` mode. 
The new output would look like this in case an active flag is passed to the command line
`admin@sonic:~$ sudo config muxcable mode manual Ethernet0`
`admin@sonic:~$ sudo config muxcable mode manual all`
added an option to set muxcable  mode to manual mode, in addition to existing auto/active modes. 
added the changes in config/muxcable.py and added testcases
Ran the unit tests

[config] support for configuring muxcable to manual mode of operation 

---

tests/conftest.py

The build is broken for module name error
```
request = <SubRequest 'setup_single_bgp_instance' for <Function 'test_show_ip_route[ip_route]'>>
@pytest.fixture
def setup_single_bgp_instance(request):
import utilities_common.bgp_util as bgp_util
if request.param == 'v4':
bgp_mocked_json = os.path.join(
test_path, 'mock_tables', 'ipv4_bgp_summary.json')
elif request.param == 'v6':
bgp_mocked_json = os.path.join(
test_path, 'mock_tables', 'ipv6_bgp_summary.json')
else:
bgp_mocked_json = os.path.join(
test_path, 'mock_tables', 'dummy.json')
>       def mock_run_bgp_command(vtysh_cmd, bgp_namespace, vtysh_shell_cmd=constants.RVTYSH_COMMAND):
E       NameError: name 'constants' is not defined
```

Fix build test failure caused by error module name

---

scripts/db_migrator.py
tests/db_migrator_input/config_db/feature-expected.json
tests/db_migrator_input/config_db/feature-input.json
tests/db_migrator_input/init_cfg.json

This is a cherrypick of https://github.com/Azure/sonic-utilities/pull/1674 for 202012 since the master checks are failing and we need to unblock the 202012 branch
Fixing db_migrator.py for FEATURE table. In case of version_unknown, all versions' migrator APIs would be invoked which will also invoke the feature_table migration. Without the field check for 'status' the current logic will set it 'disabled' and will set 'state' field too to be 'disabled' which will in turn disable all the features bringing down the system.
Added check to migrate only if 'status' field is present.
Install the image through onie and confirm if services are up

[202012]Fixing db_migrator for Feature table 

---

tests/config_dpb_test.py
tests/config_mgmt_test.py

re-enable after fix those tests

[tests]: skip some dynamic port breakout unit tests

---

scripts/db_migrator.py
tests/db_migrator_input/config_db/feature-expected.json
tests/db_migrator_input/config_db/feature-input.json
tests/db_migrator_input/init_cfg.json

Fixing db_migrator.py for FEATURE table. In case of version_unknown, all versions' migrator APIs would be invoked which will also invoke the feature_table migration. Without the field check for 'status' the current logic will set it 'disabled' and will set 'state' field too to be 'disabled' which will in turn disable all the features bringing down the system.
Added check to migrate only if 'status' field is present.
Install the image through onie and confirm if services are up

Fixing db_migrator for Feature table

---

config/main.py

I removed the following line from the `config reload` flow....
```
click.echo("Resetting failed status on {}".format(service))
```
This is called in the `_reset_failed_services()` function which is used to reset the systemd restart timers on services so that it doesn't prevent them from starting from the config reload. 
The above line results in the following lines being printed to the terminal when `config reload` is run
```
Resetting failed status on bgp.service
Resetting failed status on caclmgrd.service
Resetting failed status on dhcp_relay.service
Resetting failed status on hostcfgd.service
Resetting failed status on hostname-config.service
Resetting failed status on interfaces-config.service
Resetting failed status on lldp.service
Resetting failed status on mgmt-framework.timer …
```

[config] Remove "reset failed" print lines from config reload

---

scripts/generate_dump

This PR depends on https://github.com/Azure/sonic-buildimage/pull/7844
Enhance the way techsupport collects dumps provided by SAI and do not keep them in the filesystem once the techsupport is created.
- Create a temporary directory once techsupport script is executed, gather all files SAI dumps created, add them to the tech support and remove the temporary directory and files.
-  Remove direct call to FW trace collection as it is done now by SAI dump
Run techsupport, verify newly created files are part of it including mlxtrace which is no longer called directly by the techsupport script.

[Mellanox] Add different dumps files collected by SAI to techsupport

---

config/plugins/mlnx.py

following the change in PR https://github.com/Azure/sonic-buildimage/pull/7830, the folder needs to be created when the first time enables the sniffer function.
check whether the path to store the sniffer file is existing or not, if not, create it.
run command "config platform mlnx sniffer sdk enable", can see sniffer function can be enabled successfully.
N/A
N/A

[Mellanox] Create sniffer folder if it doesn't exist yet

---

config/main.py

Signed-off-by: Raphael Tryster <raphaelt@nvidia.com>
Restrict the min-links parameter in "config portchannel" to the range 0-1024.
Fixes Azure/sonic-buildimage#6781 in conjunction with https://github.com/Azure/sonic-buildimage/pull/7265/files.
Changed
@click.option('--min-links', default=0, type=int)
to
@click.option('--min-links', default=0, type=click.IntRange(0,1024))
Note that all these need to be aligned:
the default value
the range enforced here
the limits in libteam
the limits in the yang model
The first two of these are in this PR; the last two are in the other one referred to above. The alignment was performed as follows:
the default value - remained 0
the range enforced here - previously absent, now 0-1024
the limits in libteam - maximum was 255, now 1024
the limits in the yang …

Add range check on portchannel min-links

---

scripts/vnet_route_check.py

Fixed issue when VNET route check detects some routes as missed they are really configured.
Fixed logic for getting VNET routes from ASIC DB in order to correctly retrieve all the configured in ASIC DB VNET routes.
* Run VNET test from sonic-mgmt
* Run VNET route check script and verify that no missing routes are reported.

[vnet_route_check] Fix logic for getting VNET routes from ASIC DB

---

config/main.py
scripts/db_migrator.py
tests/db_migrator_input/config_db/portchannel-expected.json
tests/db_migrator_input/config_db/portchannel-input.json
tests/db_migrator_test.py

This PR depends on:
- https://github.com/Azure/sonic-utilities/pull/1566
- https://github.com/Azure/sonic-swss/pull/1660
Fix issue - https://github.com/Azure/sonic-buildimage/issues/4009
Change the LACP key to be generated from the Port Channel name instead of always being 0.
When upgrading without warm-reboot update old port channels to use the new default.
When adding a new port-channel add by default the key lacp_key with the value 'auto' to the port-channel table, this is done to change the port-channel LACP key to be generated from the Port Channel name instead of always being 0.
When upgrading without warm-reboot, also update old port channels to use the new default.
This is not done on warm-reboot to avoid the link from going down.
Create a new port-channel, add a port and run …

[config]: Create portchannel with LACP key

---

config/main.py

DO NOT MERGE UNTIL https://github.com/Azure/sonic-buildimage/pull/7846 is merged.
Fixed config reload to add some system sanity checks
1) To check if the system is in running state
2) Check if the services which are grouped under delayed target up
3) Check if swss is running for at least 120 seconds
To force config reload and to avoid these checks an extra option -f/--force is added
Added the above mentioned checks in config reload flow
Perform config reload after reboot, between system up and delayed services up, immediately after another config reload and running two config reload in parallel. In all the cases the config reload should not execute and throw appropriate error messages.
When system is not up
sonic:~#config reload
System is not up
When delayed services are not up …

[config] Adding sanity checks for config reload

---

show/platform.py

Fix `NameError` from `show version`.
```
admin@str2-7050cx3-acs-02:~$ show version
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File …
```

[show] fix `show version`

---

.azure-pipelines/build_and_install_module.sh

When run "make modules_prepare", it prompts an ask as below:
Microsoft Network Devices (NET_VENDOR_MICROSOFT) [Y/n/?] (NEW)
It should be caused by the new version of the kernel config mis-match with existing one.
To fix it, add the CONFIG_NET_VENDOR_MICROSOFT and CONFIG_MICROSOFT_MANA settings in the .config file.

[ci]: Fix config prompt question issue

---

pfcwd/main.py
tests/pfcwd_test.py

Fixes #1690 
Set the correct return code when pfcwd command is specified with invalid options
Modified the unit test to check for the correct return code and ran them and they passed

[pfcwd] Fix the return code in invalid case

---

doc/Command-Reference.md
sfputil/main.py
show/interfaces/__init__.py
tests/mock_tables/state_db.json
tests/sfputil_test.py

Expose error status fetched from STATE_DB or platform API to CLI.
The command is
- `sfputil show error-status [-hw|--fetch-from-hardware] [<interface_name>]`
- and `show interfaces transceiver error-status [-hw|--fetch-from-hardware] [<interface_name>]`
The error status will be fetched from
- `STATE_DB` by default
- hardware via platform API if the parameter `--fetch-from-hardware` is provided.
In this case, the CLI will call platform API in the pmon docker and format the output.
Manually test and unit test
```
admin@sonic:~$ show interfaces transceiver error-status 
Port         Error Status
-----------  ----------------------------------------------------
Ethernet0    OK
Ethernet4    OK
Ethernet8    Long range for non-Mellanox cable or …
```

[sfputil] Expose error status fetched from STATE_DB or platform API to CLI

---

scripts/generate_dump

This PR depend on https://github.com/Azure/sonic-buildimage/pull/7708
Add Mellanoxs SDK dump output into techsupport in the generate_dump script.
Add a step to copy SDK dump output into techsupport in the Mellanox step in generate_dump script.
Simulate SDK event on a Mellanox switch and check that dump has been added copied into the techsupport results.

[Mellanox] Update mellanoxs dump generation to include SDK dumps

---

pcieutil/main.py

Pcieutil to load the platform api first instead of using common api
Some platform device with different BIOS version needs more than one pcie configuration to check the pcie devices properly.
Please refer to the platform api support : https://github.com/Azure/sonic-platform-common/pull/195
Load the platform pcie api first prior to use the common api

Pcieutil to load the platform api first instead of using common api

---

sonic-utilities-tests/conftest.py

Fix the name 'mock_show_bgp_command' not defined issue, caused by code merge.

Fix the name 'mock_show_bgp_command' not defined issue

---

pfcwd/main.py
tests/pfcwd_test.py

Backport #1691
Set the correct return code when pfcwd command is specified with invalid options

[202012] [pfcwd] Fix the return code in invalid case

---

config/muxcable.py
show/muxcable.py
utilities_common/platform_sfputil_helper.py

this PR adds support for interface alias support for muxcable commands. Basically for other OS's there could be a different scheme of interface naming which will be now be supported by muxcable commands as well.
Added the changes in muxcable.py in show and config . 
add unit-tests as well as run on a Arista-7050cx3 switch.
```
admin@str2-7050cx3-acs-04:/usr$ show mux cableinfo Ethernet15/1
Vendor    Model
--------  ----------------
Credo     CACL2X321P2PA1MS
admin@str2-7050cx3-acs-04:/usr$ show mux hwmode muxdirection Ethernet13/1
Port        Direction
----------  -----------
Ethernet48  standby
```

[show][config] support for interface alias for muxcable commands

---

config/main.py
tests/pgdropstat_test.py

Explanation how show/clear counters works:
- Suppose we got from SDK some count of dropped packets for priority group (№3) per interface (Ehernet4). (for example Ethernet4 PG-3 123 packets)
- Stats can be shown via show priority-group drop counters
Then we run sonic-clear priority-group drop counters. This command will save data "Ethernet4 PG-3 123 packets" to backup. It saved in /tmp/dropstat-{user_id} folder
- When we run show priority-group drop counters again, script will take data from SDK and data saved from backup. In backup it will find 123. In SDK it may still be number 123 for Ethernet4 (like in backup) or bigger (for example 126.)
Our sonic-clear priority-group drop counters command does not change anything in SDK. It just show …

[show priority-group drop counters] Remove backup with cached PG drop counters after 'config reload'

---

scripts/generate_dump

Remove redundant mellanox dumps now that Mellanox SAI is taking care of that.
Deleted the part related to mstdumps from the generate_script
Run 'show techsupport' see we no have mstdump folder but the actual dump available under the saisdk dump

[Mellanox] Remove mstdump from  Mellanox's collect dump script

---

config/main.py
crm/main.py
doc/Command-Reference.md
show/interfaces/__init__.py
tests/crm_test.py
tests/mock_tables/asic0/config_db.json
tests/mock_tables/asic0/counters_db.json
tests/mock_tables/asic1/config_db.json
tests/mock_tables/asic1/counters_db.json
tests/mock_tables/config_db.json
tests/mock_tables/counters_db.json
tests/mpls_input/appl_db.json
tests/mpls_test.py

**What I did**
SONiC CLI support for MPLS:
1) "config interface mpls (add | remove) \<if-name\>"
2) "show interface mpls [\<if-name\>]"
3) CRM threshold configuration for mpls_inseg and mpls_nexthop
4) Updated SONiC CLI command reference manual.
SONiC CLI support for MPLS
**How I verified it**
Unit-tests in sonic-swss/tests/test_mpls.py and sonic-utilities/tests
**Details if related**
Refer to HLD:  https://github.com/Azure/SONiC/pull/706

sonic-utilities updates for MPLS

---

.coveragerc

Originally, the Azure pipeline "Code Coverage" page will render folder structure wrongly. The first level of folders disappear and all the files in the first level are combined and de-dup. So we lost many main.py, etc.
Fix the coveragerc file so that the rendering will make sense.

Coverage uses top level directory as source

---

config/main.py
tests/config_test.py

The port state will be reset to up if user use `config load_minigraph` to recover configurations.
This PR is for supporting consume `port_config.json` while loading minigraph. User can put the stateful `port_config.json` with minigraph file to keep the port state unchanged after reload minigraph.
The `port_config.json` includes a segment of `config_db` PORT table(we called that segment `configlet` as well) and it will be placed on `\etc\sonic\port_config.json`, below is a sample:
```json
[
{
"PORT": {
"Ethernet0": {
"admin_status": "down"
},
"Ethernet4": {
"admin_status": "up"
}
}
}
]
``` 
This feature will only consume the `port_config.json` when the file is existed in `\etc\sonic\port_config.json`.
Please notice that we do not leverage this feature …

[minigraph][port_config] Consume port_config.json while loading minigraph

---

config/main.py
tests/ip_config_test.py

Signed-off-by: Andriy Kokhan <andriyx.kokhan@intel.com>
After executing command that should delete ipv6 address from LAG, ipv6 address still remains.
This affects t0 VLAN TCs.
Reworked IP validation for "config interface ip remove" command added by https://github.com/Azure/sonic-utilities/pull/1414
Since the IP address is used as a part of a key in Redis DB, we should not modify IP address format provided by the user (e.g., convert "FC00::71/126" to "fc00::71/126" which causes VLAN TCs failure). At the same time we probably should not tolerate extra zeros in IPv4...
So, reworked IP validation in "config interface ip add/remove" command:
- Renamed validate_ip_mask() to is_valid_ip_interface() as per code style
- Updated is_valid_ip_interface() to do not modify the IP address
- Updated UTs …

Fixed IP validation in "config interface ip add/remove"

---

acl_loader/main.py
config/main.py
crm/main.py
scripts/ipintutil
scripts/lldpshow
scripts/portconfig
show/main.py
utilities_common/cli.py
utilities_common/general.py

Introduce a new function `load_db_config()`. This function will load the global database file or database config file based on the platform. 
This change depends on https://github.com/Azure/sonic-buildimage/pull/8173
UT results
```
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-utilities, inifile: pytest.ini
plugins: pyfakefs-4.5.0, cov-2.6.0
collecting ... collected 1052 items
tests/aaa_test.py::TestAaa::test_show_aaa_default PASSED                 [  0%]
tests/aaa_test.py::TestAaa::test_config_aaa_radius PASSED                [  0%]
tests/aaa_test.py::TestAaa::test_config_aaa_radius_local PASSED          [  0%] …
```

Load the  database global_db only once for show cli 

---

scripts/configlet

Syntax error seen while trying to apply a configlet
File "/usr/local/bin/configlet", line 212, in <module>
main()
File "/usr/local/bin/configlet", line 205, in main
process_entry (do_update, i)
File "/usr/local/bin/configlet", line 175, in process_entry
do_operate(op_upd, t, (), data[t])
File "/usr/local/bin/configlet", line 162, in do_operate
if type(lst[lst.keys()[0]]) == dict:
TypeError: 'dict_keys' object is not subscriptable
Use next(iter()) to derive a key from the dict. This is both python2 and python3 compatible
Tried applying the json file below using the command 'configlet -j test.json -d'. Configlet was applied successfully. No errors were seen
[
{
"ACL_TABLE": {
"EVERFLOW": {},
"EVERFLOWV6": {} …

[configlet] Python3 compatible syntax for extracting a key from the dict

---

tests/config_test.py

We found an issue where UT couldn't pass in old release branch with patch https://github.com/Azure/sonic-utilities/pull/1705 
To solve this issue, I applied two change in this PR:
- Use imported config.main module since we are not import config.main as config in old release branches
- Add conditional patch since some file were not mocked in old release branches

[minigraph][port_config] Use imported config.main and add conditional patch

---

config/main.py

Signed-off-by: Jing Kan jika@microsoft.com
Merge patch of https://github.com/Azure/sonic-utilities/pull/1705
Made additional changes for this branch.
Tested on vSONiC:
Prepare `port_config.json`
```json
[
{
"PORT": {
"Ethernet112": {
"admin_status": "down"
},
"Ethernet116": {
"admin_status": "up"
}
}
}
]
```
Before
```
admin@vlab-01:~$ show interface status
Interface            Lanes    Speed    MTU    FEC           Alias             Vlan    Oper    Admin    Type    Asym PFC
---------------  ---------------  -------  -----  -----  --------------  ---------------  ------  -------  ------  ----------
Ethernet112      93,94,95,96      40G   9100    N/A  fortyGigE0/112  PortChannel0001      up       up     N/A         off
Ethernet116      89,90,91,92      40G   9100    N/A  fortyGigE0/116 …
```

[minigraph][port_config] Consume port_config.json while reloading minigraph

---

show/muxcable.py
tests/muxcable_test.py

This PR fixes the display for show muxcable metrics by sorting the output based on the time of the event. 
This is required for better display.
For example
`admin@str2-7050cx3-acs-12:~$ show mux metrics Ethernet0`
`PORT       EVENT                        TIME`
`---------  ---------------------------  ---------------------------`
`Ethernet0  xcvrd_switch_standby_start   2021-Jul-21 02:03:28.784027`
`Ethernet0  orch_switch_standby_end      2021-Jul-21 02:03:28.788150`
`Ethernet0  linkmgrd_switch_standby_end  2021-Jul-21 02:03:28.790288`
changed the output for muxcable metrics command for sorted time order
made the changes inside the show/muxcable.py by sorting the output
unit-tests

[show] fix show muxcable metrics <port> for sorted output

---

sonic_installer/main.py

What I did
Updated docker container list to include "macsec" so that sonic_installer upgrade-docker can be used for macsec container.
Why I did it
MACsec support.
How I verified it
System tests on Juniper platform which supports MACsec.
Details if related
N/A

Allow upgrade-docker for macsec container

---

show/bgp_frr_v4.py
show/bgp_frr_v6.py

Fix the issue https://github.com/Azure/sonic-buildimage/issues/7935
Add the default namespace option to `DEFAULT_NAMESPACE` instead of `None`
Run the command on VS
`show ip bgp network` and `show ipv6 bgp network`
```
admin@vlab-01:~$ show ip bgp network  -h
Usage: show ip bgp network [OPTIONS] [<ipv4-address>|<ipv4-prefix>]
[bestpath|json|longer-prefixes|multipath]
Show IP (IPv4) BGP network
Options:
-n, --namespace TEXT  Namespace name or all  [default: ]
-h, -?, --help        Show this message and exit.
admin@vlab-01:~$ show ip bgp network | more
BGP table version is 6405, local router ID is 10.1.0.32, vrf id 0
Default local pref 100, local AS 65100
Status codes:  s suppressed, d damped, h history, * valid, > …
```

fix the show ip bgp network command

---

scripts/disk_check.py
tests/disk_check_test.py

1) Set default log level to SYSLOG-ERR
2) Make log level configurable via args
By default, the debug logs don't appear, unless the "-l 7" is passed in command line.

disk_check: Minor log related updates

---

scripts/null_route_helper
setup.py
tests/aclshow_test.py
tests/mock_tables/config_db.json
tests/null_route_helper_test.py

This PR introduced a new helper script ```null_route_helper```.
```null_route_helper``` is a utility for blocking and unblocking traffic from given source ip_prefix on ACL tables.
The block operation will insert a DENY rule at the top of the table. The unblock operation will remove an existing DENY rule that has been created by the block operation (i.e. it does NOT insert an ALLOW rule, only removes DENY rules).
Since SONiC supports multi ACL rules share the same priority, all ACL rules created by null_route_helper will use the highest priority(9999).
Example:
```
Block traffic from 10.2.3.4:
./null_route_helper block acl_table_name 10.2.3.4
Unblock all traffic from 10.2.3.4:
./null_route_helper unblock acl_table_name 10.2.3.4
List all acl …
```

[CLI] Add script null_route_helper

---

scripts/null_route_helper
setup.py
sonic-utilities-tests/aclshow_test.py
sonic-utilities-tests/mock_tables/config_db.json
sonic-utilities-tests/null_route_helper_test.py

Signed-off-by: bingwang <wang.bing@microsoft.com>
This PR is derived from PR #1737, and make minor change for ```201911``` branch. 
Changes including
1. Change shebang from python3 to python2
2. Use ```swsssdk``` instead of ```swsscommon```.
The feature is implemented with applying ACL rules.
Verified by unit test and traffic test
Unit test
```
/sonic/src/sonic-utilities$ python2 -m py.test sonic-utilities-tests/null_route_helper_test.py -v --pdb
========================================================================================= test session starts =========================================================================================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/bin/python2
cachedir: sonic-utilities-tests/.cache
rootdir: …
```

[CLI] Implement null_route_helper script

---

scripts/null_route_helper
setup.py
tests/aclshow_test.py
tests/mock_tables/config_db.json
tests/null_route_helper_test.py

This is a backport of https://github.com/Azure/sonic-utilities/pull/1737
This PR introduced a new helper script ```null_route_helper```.
```null_route_helper```  is a utility for blocking and unblocking traffic from given source ip_prefix on ACL tables.
The block operation will insert a DENY rule at the top of the table. The unblock operation will remove an existing DENY rule that has been created by the block operation (i.e. it does NOT insert an ALLOW rule, only removes DENY rules).
Since SONiC supports multi ACL rules share the same priority, all ACL rules created by null_route_helper will use the highest priority(9999).
Example:
```
Block traffic from 10.2.3.4/32:
./null_route_helper acl_table_name block 10.2.3.4/32
Unblock all traffic …
```

Add script null_route_helper

---

scripts/lldpshow
tests/lldp_test.py

Fix an issue when having the following scenario:
1- remote interface has 2 MACs on the same physical interface.
2- "show lldp table" command displays one entry for only one MAC address
Root cause:
"show lldp table" command uses lldpshow script to get, parse and display data from the lldp open source package (lldpctl script).
lldpctl script returns a proper info about the 2 MACs but the issue is with the lldpshow script parser where it built a dictionary which its key is the local physical interface.
Therefore when having 2 MACs, lldpctl will return 2 entries but the lldpshow parser will overwrite the first entry.
Fix:
Change the key to be a string of "interface#MAC".
This will enable having 2 entries for 2 different MAC addresses.
In addition:
- update display_sum()-->get_summary_output() …

[LLDP] Fix lldpshow script to display multiple MAC addresses on the same remote physical interface

---

scripts/fast-reboot

The change being removed was introduced with PR#1174 with the condition that flex counter polling will be enabled in the boot up path unconditionally. However, a change was made to enable_counters.py to only enable counters when the configuration is missing (sonic-buildimage PR#7735). After the later change, the disabled flex counters will not be enabled when fast-reboot into the same image.
run fast-reboot test and snmp test, without the fix, the snmp test would fail. With the fix, the snmp test passes.

[fast-reboot] revert the change of disabling counter polling before fast-reboot

---

config/main.py

Do not enable PFC watchdog for MgmtTsToR
The MgmtTsToR is a kind of enriched MgmtToRRouter, so the configuration should be align.
Add the MgmtTsToR to the condition to not enble pfcwd for it
No functional change here, the build is pass.

[minigraph] Do not enable PFC watchdog for MgmtTsToR

---

scripts/portconfig

Fix for issue https://github.com/Azure/sonic-buildimage/issues/8308
"front_asic_namespaces" is not defined. Changed  function Sonic2VConnector() call with the correct argument "namespace". 
- Execute the config command to set the interface speed:
**sudo config interface -n asic0 speed Ethernet0 400000**
- No error shown
- Previously the command showed the following error.
**name 'front_asic_namespaces' is not defined**
- New output does not show the error

[config][interface][speed] Fixed the config interface speed in multi-asic issue

---

scripts/pg-drop
tests/pgdrop_input/config_db.json
tests/pgdropstat_test.py

Added additional output info for user when trying to show priority group counters and pg drop counters are disabled
modify pg-drop script, add additional print during executing "show priority-group drop counters" if PG polling disabled
```
counterpoll pg-drop disable
show priority-group drop counters
```
Expect:
`Warning: PG counters are disabled. Current stats may be outdated. Use 'counterpoll pg-drop enable' to enable'`
```
admin@r-tigon-04:/usr/local/bin$ show priority-group drop counters
Ingress PG dropped packets:
Port    PG0    PG1    PG2    PG3    PG4    PG5    PG6    PG7
-----------  -----  -----  -----  -----  -----  -----  -----  -----
Ethernet0      0      0      0      0      0      0      0      0
Ethernet2      0      0 …
```

[show priority-group drop counters] Add user info output when user want to check PG counters and polling are disabled

---

scripts/vnet_route_check.py

Fix an issue when having /16 prefix on Vlan with vnet:
```
ERR vnet_route_check.py:  {'results': {'missed_in_app_db_routes': {'Vnet3': {'routes': ['172.3.255.254/32']}}}}
```
```
Interface     Master    IPv4 address/mask    Admin/Oper    BGP Neighbor     Neighbor IP
------------  --------  -------------------  ------------  ---------------  -------------
Loopback0               10.1.0.2/32          up/up         N/A              N/A
PortChannel1            10.100.0.16/31       up/up         TGS-SONIC-N2-S1  10.100.0.17
PortChannel2            10.100.0.18/31       up/up         TGS-SONIC-N2-S1  10.100.0.19
PortChannel3            10.100.0.20/31       up/up         TGS-SONIC-N2-S1  10.100.0.21
PortChannel4            10.100.0.22/31 …
```

[201911][vnet_route_check] don't hardcode prefix length of /24

---

scripts/vnet_route_check.py

Fix an issue when having /16 prefix on Vlan with vnet:
```
ERR vnet_route_check.py:  {'results': {'missed_in_app_db_routes': {'Vnet3': {'routes': ['172.3.255.254/32']}}}}
```
```
Interface     Master    IPv4 address/mask    Admin/Oper    BGP Neighbor     Neighbor IP
------------  --------  -------------------  ------------  ---------------  -------------
Loopback0               10.1.0.2/32          up/up         N/A              N/A
PortChannel1            10.100.0.16/31       up/up         TGS-SONIC-N2-S1  10.100.0.17
PortChannel2            10.100.0.18/31       up/up         TGS-SONIC-N2-S1  10.100.0.19
PortChannel3            10.100.0.20/31       up/up         TGS-SONIC-N2-S1  10.100.0.21
PortChannel4            10.100.0.22/31 …
```

[vnet_route_check] don't hardcode prefix length of /24

---

setup.py
sonic_package_manager/constraint.py
sonic_package_manager/manager.py
sonic_package_manager/manifest.py
sonic_package_manager/version.py
tests/sonic_package_manager/test_constraint.py
tests/sonic_package_manager/test_database.py
tests/sonic_package_manager/test_manager.py
tests/sonic_package_manager/test_manifest.py

I replaced underneeth a library which I used for semver functionality.
Tried to keep existing Version/VersionConstraint API but replaced library used underneeth.
I also added two UT that failed with poetry-semver and show the motivation for this change.
UT description:
- ```test_invalid_version```
This test is to verify that **invalid** semantic version strings are rejected with exception by ```Version.parse```.
E.g. "1.2.3-0123" is not a valid semantic version due to this (https://semver.org/#spec-item-9):
```
A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers …
```

[sonic-package-manager] switch from poetry-semver to semantic_version due to bugs found in poetry-semver

---

config/main.py

When systemd services finished, the systemd status could running
or degraded. Therefore, compare system status with starting directly.
When systemd services finished, the systemd status could running
or degraded. Therefore, compare system status with starting directly.
Here is what is happening on kvm switch. Some services cannot be started.
Then, the system state is in degraded state.
```
admin@ARISTA01T1:~$ systemctl is-system-running
starting
admin@ARISTA01T1:~$ systemctl is-system-running
degraded
```

[config reload]: fix the condition for checking if system is starting

---

utilities_common/multi_asic.py

Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
Recent change was done to remove call to load database global_db which expects the clients to load global_db.
[https://github.com/Azure/sonic-buildimage/pull/8173]
The load global_db was missing in multi_asic.py which was causing "show interfaces cli" to fail.
While testing on multi-asic VS image:
```
admin@vlab-08:~$ show interfaces status
File "/usr/local/bin/intfutil", line 701, in <module>
main()
File "/usr/local/bin/intfutil", line 687, in main
interface_stat.display_intf_status()
File "/usr/local/bin/intfutil", line 376, in display_intf_status
self.get_intf_status()
File "/usr/local/lib/python3.7/dist-packages/utilities_common/multi_asic.py", line 133, in wrapped_run_on_all_asics
ns_list = …
```

Load the database global_db

---

config/main.py

`get_sonic_version_info()` may return `None` if `/etc/sonic/sonic_version.yml` does not exist. Previously the `config` exit without any useful information.
Some `config` subcommands do not depend on sonic version info, we should allow them to run.

Improve `config` error handling on version_info

---

config/main.py
doc/Command-Reference.md
show/main.py
tests/ipv6_link_local_test.py
tests/mock_tables/config_db.json

As per the HLD - https://github.com/Azure/SONiC/pull/625 , added config and interface commands.
SONiC CLI per interface configuration command to enable and disable the IPv6 link-local address mode when addresses are not configured manually.
Example:
```
config interface ipv6 enable use-link-local-only Ethernet24
config interface ipv6 disable use-link-local-only Ethernet24
```
SONiC CLI global command to enable or disable the IPv6 auto link-local address mode on all eligible interfaces.
```
config ipv6 enable link-local
config ipv6 disable link-local
```
Show command to display the link local mode of all interfaces.
```
root@sonic:/home/admin# show ipv6 link-local-mode 
+------------------+----------+
| Interface Name   | Mode     |
+==================+==========+
| Ethernet16       | …
```

Global and Interface commands for IPv6 Link local address enhancements

---

show/platform.py

Changed the behavior of the `get_chassis_info()` function which is used by `show version` and `show platform summary` to report the serial / model / revision of the switch to only attempt to call the platform API if pmon completely failed to provision STATE_DB with CHASSIS_INFO
Altered `get_chassis_info()` according to the above behavior. See changelog for details. 
Verify `show platform summary` and `show version` correctly report chassis info.
Delete the `CHASSIS_INFO` table from `STATE_DB`
Verify `show platform summary` and `show version` still correctly report the info.

[show][platform] Revise chassis info fallback to only fall back on pmon crash

---

sfputil/main.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Gracefully handle improper 'specification_compliance' field
The 'specification_compliance' field of transceiver info is expected to be a string representation of a dictionary. However, there is a chance, upon some kind of platform issue that a vendor's platform API returns something like 'N/A'. In this case, sfpshow would crash. Rather than crash, sfpshow should handle this gracefully and output 'N/A' instead.
Run "sfputil show eeprom -d" on a device where the 'specification_compliance' field of transceiver info is not a string representation of a dictionary.
N/A -- sfputil would crash
Ethernet0: SFP EEPROM detected
Application Advertisement: N/A
Connector: N/A
Encoding: N/A
Extended Identifier: N/A
Extended RateSelect Compliance: N/A …

[sfputil] Gracefully handle improper 'specification_compliance' field

---

config/kdump.py
tests/kdump_test.py
tests/mock_tables/config_db.json

This PR aims to update the `config` command of Kdump (Linux kernel dump) mechanism.
Before updating the value of a field in the table of `KDUMP`, we need decide whether the `KDUMP` table and corresponding field does exist in the table.
I verifies this on device `str-msn2700-03` and unit test passed.
tests/kdump_test.py::TestKdump::test_config_kdump_disable PASSED                                                                                                 
tests/kdump_test.py::TestKdump::test_config_kdump_enable PASSED                                                                                                  
tests/kdump_test.py::TestKdump::test_config_kdump_memory PASSED …

[Config] Update config command of kdump

---

doc/Command-Reference.md
utilities_common/cli.py

Update CLI reference document following PR : https://github.com/Azure/sonic-buildimage/pull/8211
Add a new API on utilities_common to get IP type.
- Update doc/Command-Reference.md with new DHCP CLI.
- Add ipaddress_type API to utilities_common/cli.py
- Build an image with PR https://github.com/Azure/sonic-buildimage/pull/8211 and this PR.
- Run DHCP CLI commands

[dhcp_relay] Update CLI reference document and add a new API for ip address type

---

scripts/disk_check.py
tests/disk_check_test.py

Have independent subdirs for each mounted dir to avoid any collisions of files/dirs by same name.
Adopt for older version of python3
Changes:
1) Individual subdirs for each dir to be mounted
2) subprocess args made compatible with older version of python3 (tested in version 3.5.3)
1) Simulate read-only state
2) Run this script
3) Test ssh via new tacacs user (who had not logged in earlier)

disk_check: Script updated to run good in 201811 & 201911

---

tests/mock_tables/dbconnector.py

This is a partial backport of https://github.com/Azure/sonic-utilities/pull/1392
Only add new mock support in unit test.

Add mock support for swsscommon classes

---

config/muxcable.py
show/muxcable.py
tests/muxcable_test.py

this PR adds support for cli refactor which is done for abstract class implementation of muxcable which is provided by vendors.
detailed design doc can be found https://github.com/Azure/SONiC/pull/757
Added the changes in muxcable.py in show and config . 
add unit-tests as well as run on a Arista-7050cx3 switch, run unit tests. 
no change in outputs, just the functionality has changed.

[show][config] cli refactor for muxcable with abstract class implementation from vendors

---

utilities_common/cli.py

What I did
Allow system with no ports in config db run without errors.
This is needed for modular system which should boot properly without line cards.
How I did it
Do not raise warning if ports dictionary is empty.
Run show interfaces status
root@r-leopard-41:/home/admin# show interfaces status
Warning: failed to retrieve PORT table from ConfigDB!
Warning: failed to retrieve PORT table from ConfigDB!
Interface Lanes Speed MTU FEC Alias Vlan Oper Admin Type Asym PFC
*----------- ------- ------- ----- ----- ------- ------ ------ ------- ------ ----------
root@r-leopard-41:/home/admin#
root@r-leopard-41:/home/admin# show …

[show] Allow system with no ports in config db run without errors

---

counterpoll/main.py
scripts/fast-reboot
scripts/fast-reboot-dump.py

Set flex counters delay indicator to prevent flex counters enablement after fast-reboot.
Modify config DB json file with 'true' status for delay of flex counters indicator.
Run fast-reboot and observe counters are created only when enable_counters script is called, even if the tables are present in config DB.

[Fast-reboot] Set flex counters delay indicator to prevent flex counters enablement after fast-reboot

---

sonic_installer/main.py
tests/swap_allocator_test.py
utilities_common/cli.py

* Let's add swap memory setup support for `sonic_installer` command so it could run on devices with limited memory resources.
* Add the following new options to `sonic_installer`:
1. `--skip-setup-swap`: if present, will skip setup swap memory.
2.  `--swap-mem-size`: this will change the swap memory size(the default swap size is 1024 MiB)
3. `--total-mem-threshold`: if the system total memory is less than the value passed to `--total-mem-threshold`(default 2048 MiB), `sonic_installer` will setup swap memory.
4.  `--available-mem-threshold`: if the system available memory is less than the value passed to `--available-mem-threshold`(default 1200 MiB), `sonic_installer` will setup swap memory.
* Add class `MutuallyExclusiveOption` to check the mutually-exclusive relationship between options. …

[sonic_installer] Add swap setup support

---

scripts/reboot

- Added platform pre check support in reboot script.
- Checking platform based changes before stopping dockers and sonic services.
- Porting changes in 202012 branch.
On branch reboot_pre_check_202012
Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git checkout -- ..." to discard changes in working directory)
modified:   scripts/reboot
- Write a platform pre check script(platform_reboot_pre_check) and place it in /usr/share/sonic/device/<HWSKU>/ directory.
- If the script exit with status 0, reboot will be proceeded.
- If script exit with non-zero status, the reboot script gets stopped.

platform pre-check for reboot in 202012 branch

---

config/main.py
scripts/intfstat
scripts/portstat
tests/intfstat_test.py
tests/mock_tables/asic0/counters_db.json
tests/mock_tables/asic1/counters_db.json
tests/mock_tables/asic2/counters_db.json
tests/mock_tables/counters_db.json
tests/portstat_test.py
utilities_common/netstat.py

Depends on [sonic-swss-common/pull/330](https://github.com/Azure/sonic-swss-common/pull/330)
According to [HLD](https://github.com/Azure/SONiC/blob/master/doc/rates-and-utilization/Rates_and_utilization_HLD.md) added calculation of rates and utilization columns to the `portstat` and `intfstat` scripts output
Modified the `portstat` and `intfstat` scripts
Added UT
```
admin@sonic:~$ show int count
IFACE    STATE    RX_OK    RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK    TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
-----------  -------  -------  --------  ---------  --------  --------  --------  -------  --------  ---------  --------  --------  --------
Ethernet0        X        0       N/A        N/A         0         0       N/A        0       N/A        N/A         0 …
```

[portstat, intfstat] added rates and utilization

---

scripts/fast-reboot

This is porting changes from 202012 branch to 201911 branch.
Related PR: https://github.com/Azure/sonic-utilities/pull/1774

[fast-reboot] Remove FLEX_COUNTER_TABLE from config_db.json before reboot

---

sonic_installer/common.py
sonic_installer/main.py
tests/swap_allocator_test.py
utilities_common/cli.py

Port PR #1787 to 202012 branch

[202012][sonic installer] Add swap setup support

---

config/main.py

Fixes https://github.com/Azure/sonic-buildimage/issues/7508
With this change:
```
root@sonic:/home/admin# config reload -y -f
Running command: rm -rf /tmp/dropstat-*
Disabling container monitoring ...
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/config_db.json --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Restarting SONiC target ...
Enabling container monitoring ...
Reloading Monit configuration ...
Reinitializing monit daemon
In Paralell:
admin@sonic:~$ sudo systemctl start …
```

[config reload] Fix config reload failure due to sonic.target job cancellation

---

config/main.py
scripts/intfstat
scripts/portstat
tests/intfstat_test.py
tests/mock_tables/asic0/counters_db.json
tests/mock_tables/asic1/counters_db.json
tests/mock_tables/asic2/counters_db.json
tests/mock_tables/counters_db.json
tests/portstat_test.py
utilities_common/netstat.py

Backport the [pull/1750](https://github.com/Azure/sonic-utilities/pull/1750) to `202012` branch
Depends on [sonic-swss-common/pull/330](https://github.com/Azure/sonic-swss-common/pull/330)
According to [HLD](https://github.com/Azure/SONiC/blob/master/doc/rates-and-utilization/Rates_and_utilization_HLD.md) added calculation of rates and utilization columns to the `portstat` and `intfstat` scripts output
Modified the `portstat` and `intfstat` scripts
Added UT
```
admin@sonic:~$ show int count
IFACE    STATE    RX_OK    RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK    TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
-----------  -------  -------  --------  ---------  --------  --------  --------  -------  --------  ---------  --------  --------  --------
Ethernet0        X        0 …
```

[202012] [portstat, intfstat] added rates and utilization 

---

generic_config_updater/generic_updater.py

Otherwise PatchSorter will see both config_wrapper, patch_wrapper as None.

[config][generic-update] Fix PatchApplier init order

---

sonic_installer/bootloader/aboot.py
sonic_installer/bootloader/bootloader.py
sonic_installer/bootloader/grub.py
sonic_installer/bootloader/onie.py
sonic_installer/bootloader/uboot.py
sonic_installer/main.py

Add --skip-platform-check option for sonic_installer; tune up comment for secureboot
Add --skip-platform-check option for sonic_installer
Install a bin file which differs the running platform's ASIC. For example;
install sonic-broadcom.bin to mellanox ASIC platform
install sonic-vs.bin to broadcom ASIC platform
sudo sonic-installer install --help
Usage: sonic-installer install [OPTIONS] URL
Install image from local binary or URL
Options:
-y, --yes
-f, --force_install       Force installation of an image of a type which
differs from that of the current running image
--skip_migration          Do not migrate current configuration to the newly
installed image
--skip-package-migration  Do not migrate current packages to the newly
installed image
--help                    Show this message and …

Add --skip-platform-check option for sonic_installer when image mismatch

---

scripts/portconfig
tests/config_an_test.py

Validate input parameter for command `config interface advertised-speeds` and `config interface advertised-types`, make sure there is no duplicate speeds or types
Split input speeds/types with "," and check if there is a duplication, if yes, print an error.
1. new unit test case
2. manual test
```
admin@sonice:$ sudo config interface advertised-speeds Ethernet4 100000,25000,100000
Invalid speed specified: 100000,25000,100000
Please remove duplicate speed
```
```
admin@sonic:$ sudo config interface advertised-types Ethernet4 CR,CR4,CR4
Invalid interface type specified: CR,CR4,CR4
Please remove duplicate interface type
```

[portconfig] Validate duplicate speed value and interface type value

---

sfputil/main.py

Signed-off-by: Kebo Liu <kebol@nvidia.com>
Wrong code indent cause sfputil go to wrong code branch while handling CMIS cable, result in not able show CMIS cable EEPROM info correctly:
```
root@r-ocelot-07:/home/admin# sfputil show eeprom -p Ethernet8
File "/usr/local/bin/sfputil", line 8, in <module>
return …
```

[sfputil] fix wrong code indent in sfputil

---

azure-pipelines.yml

Support PR coverage, It will print PR coverage in the AZP.
The output log will be collected by subsequent pipelines to generate Pull Request coverage reports.
And if a branch wants to enforce the coverage rate, we can simply and "--fail-under SCORE" in the cover-diff command, see detail in https://diff-cover.readthedocs.io/en/latest/README.html

[ci]: Support PR coverage

---

config/main.py
doc/Command-Reference.md
scripts/db_migrator.py
scripts/intfutil
scripts/portconfig
show/interfaces/__init__.py
tests/config_an_test.py
tests/db_migrator_input/config_db/non-default-config-expected.json
tests/db_migrator_input/config_db/port-an-expected.json
tests/db_migrator_input/config_db/port-an-input.json
tests/db_migrator_test.py
tests/intfutil_test.py
tests/mock_tables/appl_db.json

1. Add CLI support for port auto negotiation feature.
2. Add db_migrator change for auto negotiation feature
2. Add unit test cases for all changes
1. Add new subcommands to "config interface" command group to allow user configuring port auto negotiation
2. Add new subcommands to "show interfaces" command group to allow user show auto negotiation status
3. In db_migrator.py, change auto negotiation related DB field to latest one
Adding this PR because the cherry-pick from original PR #1568 
has conflicts 
Ran the changes on Arista7050cx3 testbed 
```
admin@sonic:~$ sudo config interface autoneg Ethernet96 enabled
admin@sonic:~$ echo $?
0
```
```
Interface    Auto-Neg Mode    Speed    Oper    Admin
-----------  ---------------  -------  ------  -------
Ethernet0              N/A     100G …
```

[202012][sonic-utilities] CLI support for port auto negotiation

---

config/main.py

As discussed in this PR https://github.com/Azure/sonic-utilities/pull/1814#discussion_r708225104, only the stop.job should have job-mode set to replace irreversibly.
Otherwise,  simultaneous config reloads in the quick succession, can lead to the behavior.
Although ,when the restart job (and all the other dependent jobs) are finished and is taken out of systemd's job queue, the next stop job will not be cancelled. 
```
admin@sonic:~$ sudo systemctl restart sonic.target --job-mode replace-irreversibly
admin@sonic:~$ sudo systemctl stop sonic.target --job-mode replace-irreversibly (Ran Immediately)
Failed to stop sonic.target: Transaction for sonic.target/stop is destructive (ntp-config.service has 'start' job queued, but 'stop' is …
```

[config reload] Removed replace irreversibly job-mode for sonic.target restart

---

scripts/neighbor_advertiser

Modify the neighbor_advertiser script to advertise ipv6 link local address
This PR resolves Azure/sonic-buildimage#6599
Master PRs:
1. https://github.com/Azure/sonic-utilities/pull/1402
2. https://github.com/Azure/sonic-utilities/pull/1427
Add ipv6 link local address to the slice returned by the neighbor advertiser script

[202012] Advertise ipv6 link local address

---

scripts/generate_dump
show/main.py

PR https://github.com/Azure/sonic-utilities/pull/1723 cannot be cherry-picked directly to 202012. Thus raised a separate PR

[techsupport] [202012] Removed -i option for docker commands and Improved Error Reporting

---

config/muxcable.py
tests/mock_tables/config_db.json
tests/mock_tables/state_db.json
tests/muxcable_test.py

This PR adds support for an option to  configure muxcable mode to  a `standby` mode. The standby mode is in addition
to `auto\active\manual` mode. 
The new output would look like this in case an standby arg is passed to the command line
`admin@sonic:~$ sudo config muxcable mode standby Ethernet0`
`admin@sonic:~$ sudo config muxcable mode standby all`
added an option to set muxcable  mode to standby mode, in addition to existing auto/active/manual modes. 
added the changes in config/muxcable.py and added testcases
Ran the unit tests

[config] support for configuring muxcable to standby mode of operation

---

scripts/generate_dump

Fix: https://github.com/Azure/sonic-buildimage/issues/8850
Issue was introduced by #1723, #1833, and #1843 (pending merge)
The error_handler is a great idea but the bash script needs to be error free first.
Fix bash script errors.
run show techsupport test..

[show techsupport] fix bash errors in generate_dump script

---

scripts/generate_dump

These format are not wrong. But if error_handler for $? is installed, these places would cause fase positives.
Update more bash syntax to avoid false positives
Run show tech support test before merge.

[show tech] fix more bash script format

---

scripts/log_ssd_health

At early boot up time, smartctl is observed could stuck forever, which causes fstrim service to be stuck in pre-start state forever.
This is a transient issue. The periodic retry will go through when pmon docker is healthy.
This issue is not highly repeatable. Tested on the device hit the issue.

[fstrim] limit smartctl execution time to 30 seconds

---

pfcwd/main.py

1. Disable pfcwd forward action config for cisco-8000.
2. Do not configure pfcwd if pfc is not configured on a port
This PR is in association with: https://github.com/Azure/sonic-swss/pull/1748 where PFC-WD forward action is disabled for cisco-8000 platform. 
Signed-off-by: Alpesh S Patel <alpesh@cisco.com>
There are two changes of interest:
1. disables pfcwd forward action configuration from pfcwd command
2. in the pfcwd script, adds a check to enable pfcwd configuration on a port only if it has pfc enabled. If config_db.json has an empty entry like: "pfc_enable" : "",
and subsequently pfcwd is configured, swss/orchagent throws an error logs
1. can be verified on cisco-8000 platform. It is a no-op for other platforms
```
SKIPPED: PFC WD 'forward' action not supported on asic 'cisco-8000' …
```

Disable pfcwd forward action config for cisco-8000.

---

scripts/generate_dump

Some bash syntax is correct without error handler on $?. With the error handler, they need to use different syntax to avoid false positives.
Update bash syntax.
tested with show techsuppor test.

[202012][show techsupport] address show techsupport return none zero code issue

---

config/plugins/mlnx.py
show/plugins/mlnx.py

Signed-off-by: Dror Prital <drorp@nvidia.com>
Add NVIDIA Copyright header to "mellanox" files
Add NVIDIA Copyright header as a comment for Mellanox files
Basic checkers

[Mellanox] Add NVIDIA Copyright header to "Mellanox" files

---

generic_config_updater/patch_sorter.py

Fixing issue #1830
Problem we consume the function `loadData` from sonic-yang-mgmt pkg that always crops tables without YANG models from configdb json object. It does it as a side-effect and is not an expected outcome of the function.
The fix here is to crop the current/target tables before doing any sorting, this way gurantee we avoid this bug. I think the better soln is to fix sonic-yang-mgmt pkg. Will look into this more next week.
Run the command in the issue, it will result in the expected outcome
**TODO: add unit-tests**

[generic-config-updater] Cropping current/target config before sorting

---

utilities_common/db.py

Currently, for all the cli commands, we connect to all databases mentioned in the database_config.json. The database_config.json also includes the databases from chassis redis server from supervisor card. It is unneccessary to connect to databases from chassis redis server when cli commands are executed form linecard. But we need to allow connection to chassis databases when the cli commands are executed from supervisor card. This problem is fixed by this PR
The constructor of Db() class which is instantiated for every CLI command execution is changed to skip chassis databases from the list of collected databases if the card is not supervisor card. This PR is dependent on sonic-buildimage PR https://github.com/Azure/sonic-buildimage/pull/8065.
In voq chassis execute some CLI commands …

[multi-asic][cli][chassis-db] Avoid connecting to chassis db for cli commands executed from linecard

---

generic_config_updater/generic_updater.py
generic_config_updater/gu_common.py

Add some logs to generic_updater
Empty patch
```
admin@vlab-01:~$ sudo config apply-patch empty.json-patch 
Patch Applier: Patch: []
Patch Applier: Validating patch is not making changes to tables without YANG models.
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config according to YANG models.
... [logs from sonic-yang-mgmt framework]
Patch Applier: Sorting patch updates.
Patch Applier: The patch was sorted into 0 changes.
Patch Applier: Applying changes in order.
Patch Applier: Verifying patch updates are reflected on ConfigDB.
Patch Applier: Patch application completed.
Patch applied successfully.
admin@vlab-01:~$ 
```
Single change patch …

[generic_config_updater] Logging

---

scripts/route_check.py
utilities_common/chassis.py

Signed-off-by: mlok <marty.lok@nokia.com>
In the VOQ chassis, the internal interfaces for communication between linecard and supervisor card need to be filtered out for the route check.  Since different vendor may have different number of internal interfaces and names, this PR adds function get_chassis_local_interfaces() to use chassisdb.conf as data file to get a list of internal interfaces and provide them to the filter_out_local_interfaces(). 
1. Add a list of interfaces as a new data field to the /usr/chare/sonic/device/<platform>/chassisdb.conf file.  The keyword is "chassis_internal_intfs"  with comma (,) as a separator. 
```
chassis_internal_intfs=enp12s0f2,enp5s0f4,enp5s0f4.2
```
2. Define a new function get_chassis_local_interfaces() to check and open …

[chassis][route-check]filter out the chassis internal interfaces

---

config/kdump.py
scripts/sonic-kdump-config

Fix Azure/sonic-buildimage#8888
Warn user to save the config instead of saving the kdump config
in config_db.json under the covers. Having more than one actors
operate on config_db.json can result in an exception.
Remove automatic saving of kdump config in startup config. Warn user to save the config instead of saving the kdump config in config_db.json under the covers.
Remove automatic saving of kdump config in startup config. Warn user to save the config instead of saving the kdump config in config_db.json under the covers.
config kdump enable
config kdump disable
config kdump memory
root@sonic:/home/admin# config kdump disable
root@sonic:/home/admin# config kdump enable
root@sonic:/home/admin# config kdump memory 512M
root@sonic:/home/admin# config kdump disable
KDUMP configuration …

[kdump] Remove automatic saving of kdump config in startup config

---

scripts/disk_check.py
setup.py
tests/disk_check_test.py

Cherry pick PR #1569, #1736 & #1747

[201811] disk_check.py: Allow remote user access when disk is read-only

---

scripts/log_ssd_health

Fix https://github.com/Azure/sonic-buildimage/issues/9114
The log_ssd_health command hangs due to timeout being used with docker exec -i which also affect warmboot flow.
Added foreground option for timeout. This is recommended when not using the command on shell
https://man7.org/linux/man-pages/man1/timeout.1.html
Run log_ssd_health and verify it does not hang

[log_ssd_health]Fix log_ssd_health hang issue

---

config/main.py
tests/ip_config_test.py

Current code takes an input from the user, converts the IPv6 string to lower letters and removes lower case IPv6 string from CONFIG DB. This is a bug since, according to the schema CONFIG DB is case insensitive for IPv6 address.
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
Fixed CLI for removing IPv6 address.
Issue is that below command does not work if IP address is written in upper case in CONFIG DB, like this: FC00::1/64.
```
config interface ip remove Ethernet0 FC00::1/64
```
- Make it case insensitive
- Relaxed the validation of IP address, a built-in validation from ipaddress package in python is used.
- Refactored interface_ipaddr_dependent_on_interface -> get_interface_ipaddresses
- Separated some functions (has_static_routes_attached, flush_ip_neigh_in_kernel, …

[config] fix interface IPv6 address removal.

---

config/main.py
tests/ip_config_test.py

Current code takes an input from the user, converts the IPv6 string to lower letters and removes lower case IPv6 string from CONFIG DB. This is a bug since, according to the schema CONFIG DB is case insensitive for IPv6 address.
- What I did
Fixed CLI for removing IPv6 address.
Issue is that below command does not work if IP address is written in upper case in CONFIG DB, like this: FC00::1/64.
'config interface ip remove Ethernet0 FC00::1/64'
- How I did it
Make it case insensitive
Relaxed the validation of IP address, a built-in validation from ipaddress package in python is used.
Refactored interface_ipaddr_dependent_on_interface -> get_interface_ipaddresses
Separated some functions (has_static_routes_attached, flush_ip_neigh_in_kernel, can_remove_router_interface, …

[202106] [config] fix interface IPv6 address removal

---

crm/main.py
tests/crm_test.py
tests/mock_tables/asic0/config_db.json
tests/mock_tables/asic0/counters_db.json
tests/mock_tables/asic1/config_db.json
tests/mock_tables/asic1/counters_db.json
tests/mock_tables/config_db.json
tests/mock_tables/counters_db.json

CRM CLI changes to include SRV6 nexthop and SRV6 MY_SID
Update CRM scripts to include options for SRV6 nexthop and MY_SID resources and threshold.
crm show CLI

Add CRM CLIs for SRV6 nexthop and my_sid_entry

---

tests/interfaces_test.py
utilities_common/cli.py

Fixed https://github.com/Azure/sonic-buildimage/issues/8521
Before displaying the warning message, call device_info.is_supervisor() function to check if it is supervisor card, don't display the warning message.
1) Running the image on supervisor card
2) Execute the CLI "show interfaces status"
3) No warning should be seen.
```
admin@supervisor:~$ show interfaces status
Interface    Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -------  -------  -----  -----  -------  ------  ------  -------  ------  ---------
```

[supervisor][show][interfaces]Fixed show interfaces command shows warning on Supervisor card

---

scripts/portconfig
tests/config_an_test.py

Depends on https://github.com/Azure/sonic-buildimage/pull/9098 and https://github.com/Azure/sonic-swss/pull/1991
**What I did**
Allow user to set none value for interface type
Say user has speed=50G, interface_type=CR2, and user wants to change it to 10G and CR. Currently, there is no CLI can support it, because:
1. If you change the interface type to CR first, SAI will get 50G and CR, SAI will report error because not supported
2. If you change the speed to 10G first, SAI will get 10G and CR2, also not supported
The only way for now is to manually change the CONFIG_DB and do a config reload, this is not user friendly.
This PR allow user to set none value to interface type. So there is a way to achieve the goal via CLI:
1. config interface type XXX none
2. config …

[config] Allow user to set none value for interface type

---

scripts/fast-reboot-dump.py

During fast-reboot,  media settings will be dumped from appDB to media_config.json file so they can be loaded to redis after fast-reboot.  This is done as part of fix for https://github.com/Azure/sonic-buildimage/issues/9165.  
During fast-reboot, delayed serdes programming done after transceiver detection results in additional interface flap and traffic loss exceeding the required 30s. This is addressed by
1. making a backup of media settings from appdb during fast-reboot (This PR)
2. loading this to redis after the switch boots up (https://github.com/Azure/sonic-buildimage/pull/9166).
3. Configuration of serdes triggered by reading media_settings.json file is skipped (https://github.com/Azure/sonic-platform-daemons/pull/221)
The script will dump an additional json file …

Dump media_settings from appDB during fast-reboot

---

dump/main.py
tests/dump_tests/dump_state_test.py

Copp dump module is raising an exception because of a undefined variable. Recitifed the issue and added to a UT to cover the scenario
```
admin@sonic:~$ dump state copp bgp
File "/usr/local/bin/dump", line 8, in <module>
sys.exit(dump())
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
File …
```

[dump] [copp] Fixed the NameError Exception for copp dump module

---

config/aaa.py
show/main.py
tests/aaa_test.py
utilities_common/db.py

This pull request add config command for AAA authorization & accounting.
Support TACACS per-command authorization & accounting.
Change AAA config command to support authorization & accounting.
Change show AAA command to support authorization & accounting.
Add UT to cover changed code.
1. Build following project and pass all UTs:
make target/python-wheels/sonic_utilities-1.2-py3-none-any.whl
2. Test new command manually.
N/A
Add config command for AAA authorization & accounting.

[TACACS+] Add config command for AAA authorization and accounting.

---

generic_config_updater/generic_updater.py
generic_config_updater/gu_common.py

Adding more logging to other CLI commands `config replace`, `config rollback`, `config checkpoint`, `config list-checkpoints` and `config delete-checkpoint`
Example of `config replace` without and with `-v` option
```bash
admin@vlab-01:~$ sudo config replace target.json 
Config Replacer: Config replacement starting.
Config Replacer: Target config length: 56594.
Config Replacer: Validating target config according to YANG models.
... [logs from sonic-yang-mgmt]
Config Replacer: Getting current config db.
Config Replacer: Generating patch between target config and current config db.
Config Replacer: Applying patch using 'Patch Applier'.
Patch Applier: Patch: []
Patch Applier: Validating patch is not making changes to tables without YANG models. …
```

[generic-config-updater] Adding logging to config-{replace, rollback, checkpoint, list-checkpoints}

---

setup.py
sonic_package_manager/registry.py
tests/sonic_package_manager/test_registry.py

If Auth service did not reply with "service" field, don't fail and request the token without it.
Modified registry.py and added UT.
Tested on DUT.

[sonic-package-manager] fix registry requests failing when no "service" field in Authorization header

---

show/platform.py

Add chassis type in the platform summary on chassis platforms.
Get the switch type from platform_info() API.
```
admin@str2-chasssis-lc3-1:~$ show platform summary
Platform: chassis_lc
HwSKU: chassis
ASIC: broadcom
ASIC Count: 1
Serial Number: xyz
Model Number: chassis-LC
Hardware Revision: N/A
Switch Type: voq
```

[show][platform summary] Add chassis type in the platform summary

---

scripts/fdbshow

The race condition is caused by a blocking Redis call which gets the contents of the FDB entry from ASIC DB.
Since it has been implemented as a simple loop, there is no guarantee that entry will be present in DB when the contents are being read.
```bash
root@sonic:/home/admin# ./reproduce.sh
...
Tue Nov  9 15:58:49 UTC 2021: Query...
Tue Nov  9 15:58:52 UTC 2021: Query...
...
=> Read ASIC DB: start
=> Read ASIC DB: done
=> Read ASIC DB: start
Key 'ASIC_STATE:SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000009cc","mac":"02:11:22:33:20:00","switch_id":"oid:0x21000000000000"}' unavailable in database '1'
```
The `fdbshow` script:
```bash
root@sonic:/home/admin# vim /usr/bin/fdbshow
...
class FdbShow(object):
HEADER = ['No.', 'Vlan', …
```

[fdbshow]: Handle FDB cleanup gracefully

---

generic_config_updater/generic_updater.py
generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/generic_config_updater/files/config_db_with_interface.json
tests/generic_config_updater/generic_updater_test.py
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

Fixing issue #1908 
- When the given patch produces empty-table, reject it since ConfigDb cannot show empty tables. Achieved that by:
- Adding a validation step before patch-sorting
- The patch-sorter should not produce steps which result in empty-tables because it is not possible in ConfigDb, we should instead delete the whole table. Achieved that by:
- Adding a new validator to reject moves producing empty tables
- No need to add a generator for deleting the whole table, current generators take care of that. They do by the following:
- The move to empty a table is rejected by `NoEmptyTableMoveValidator`
- The previous rejected move is used to generate moves using `UpperLevelMoveExtender` which produces either
- Remove move for parent -- This is good, we are removing the table
- Replace …

[generic-config-updater] Handling empty tables while sorting a patch

---

generic_config_updater/generic_updater.py

Logging a json change just before applying it. This help knowing at which step we failed change application.
Added new log msg
```sh
admin@vlab-01:~$ sudo config apply-patch empty-a-table.json-patch 
Patch Applier: Patch: [{"op": "replace", "path": "/DEVICE_METADATA", "value": {}}]
Patch Applier: Validating patch is not making changes to tables without YANG models.
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config according to YANG models.
... [sonic-yang-mgmt logs]
Patch Applier: Sorting patch updates.
... [sonic-yang-mgmt logs]
Patch Applier: The patch was sorted into 11 changes:
Patch Applier:   * [{"op": "remove", "path": …
```

[generic-config-updater] Logging change just before applying it

---

scripts/fast-reboot-dump.py

Fixed bug introduced by cherry-picking of https://github.com/Azure/sonic-utilities/pull/1910 (slight difference in code between master and 202012)
Run fast-reboot command on 202012

[202012] Fix bug introduced by cherry-picking of fastboot changes

---

scripts/disk_check.py
setup.py
tests/disk_check_test.py

Cherry pick: PRs #1569, #1736 and  #1747

disk_Check: Scan & mount as RW when disk turns into Read-only

---

scripts/generate_dump

Backport [generate_dump] remove secrets from dump files #1886 to 202012
Add bash functions to remove secrets from dump files.
For tacacs key, radius key, snmp community srring, use sed command with regex to remove user secrets from dump files.
For certs, update tar command exclude list to remove those certs from dump file.
Run 'show techsupport' command and check secrets removed from dump files.

Backport [generate_dump] remove secrets from dump files #1886 to 202012

---

doc/Command-Reference.md

Updating command reference reflecting the latest config reload behavior
Update command reference for the config reload behavior. These changes were introduced by https://github.com/Azure/sonic-utilities/pull/1664

[config reload] Update command reference

---

config/main.py
tests/config_test.py

Fixes Azure/sonic-buildimage#9292
Pfcwd was not getting started after executing load_minigraph after the changes done in #1508. This was because the PORT_QOS_MAP table is not yet present in config db (this gets populated only after the buffer templates are rendered) at the time we try to start pfcwd and hence the 'pfc_enable' field will always be empty and we skip writing PFC_WD table entries to config db. 
Delay pfcwd start until the buffer templates are rendered
Issue "config load_minigraph" with the changes and ensure that pfcwd is started on all active ports

[load_minigraph] Delay pfcwd start until the buffer templates are rendered

---

scripts/port2alias

master branch PR: https://github.com/Azure/sonic-utilities/pull/1906
get_port_config was modified to return different set number of arguments in PR: Azure/sonic-buildimage#4222. Changes in this PR is:
To address the different set of return values
To get the ports from all namespaces
How I did it
Modify port2alias to read ports from all namespaces and also add unit-test
Tested on single and multi-asic platforms.

[201911][port2alias]: Fix to get right number of return values

---

clear/main.py
config/main.py
counterpoll/main.py
scripts/flow_counters_stat
setup.py
show/flow_counters.py
show/main.py
tests/counterpoll_input/config_db.json
tests/counterpoll_test.py
tests/flow_counter_stats_test.py
tests/mock_tables/asic0/counters_db.json
tests/mock_tables/asic1/counters_db.json
tests/mock_tables/config_db.json
tests/mock_tables/counters_db.json

Add trap flow counter CLI support. See HLD: https://github.com/Azure/SONiC/pull/858
Add new command:
- counterpoll flowcnt-trap enable/disable
- counterpoll flowcnt-trap interval
- show flowcnt-trap stats
- sonic-clear flowcnt-trap
- Extend command: counterpoll show
Unit test/Manual test

Add trap flow counter support

---

doc/Command-Reference.md
show/main.py
tests/show_bfd_test.py

Add show command for BFD sessions. 
Add show command for BFD session and unit tests.
Verify the show command locally and unit test passes.
Example output:
```
>> show bfd summary
Total number of BFD sessions: 3
Peer Addr    Interface    Vrf      State    Type          Local Addr      TX Interval    RX Interval    Multiplier  Multihop
-----------  -----------  -------  -------  ------------  ------------  -------------  -------------  ------------  ----------
10.0.1.1     default      default  DOWN     async_active  10.0.0.1                300            500             3  true
10.0.2.1     Ethernet12   default  UP       async_active  10.0.0.1                200            600             3  false
2000::10:1   default      default  UP       async_active  2000::1                 100 …
```

Add show command for BFD sessions

---

doc/Command-Reference.md

Depend on https://github.com/Azure/sonic-utilities/pull/1868
Add command reference for trap flow counters
Add command reference for trap flow counters to describe the show and clear command

[Command Reference] Add command reference for trap flow counters

---

dump/helper.py
dump/plugins/copp.py
dump/plugins/evpn.py
dump/plugins/executor.py
dump/plugins/port.py
dump/plugins/portchannel.py
dump/plugins/portchannel_member.py
dump/plugins/route.py
dump/plugins/vlan.py
dump/plugins/vlan_member.py
dump/plugins/vxlan_tunnel.py
dump/plugins/vxlan_tunnel_map.py
tests/dump_tests/module_tests/copp_test.py
tests/dump_tests/module_tests/evpn_test.py
tests/dump_tests/module_tests/port_test.py
tests/dump_tests/module_tests/portchannel_member_test.py
tests/dump_tests/module_tests/portchannel_test.py
tests/dump_tests/module_tests/route_test.py
tests/dump_tests/module_tests/vlan_test.py
tests/dump_tests/module_tests/vxlan_tunnel_map_test.py
tests/dump_tests/module_tests/vxlan_tunnel_test.py

1) Moved the "populate_mock" method to dump/helper.py i.e. common to all the tests
2) Moved the "add_to_ret_template" to Executor class i.e. common across all the modules.
```
Unit Tests's:
vkarri@96050efd4f16:/sonic/src/sonic-utilities$ pytest-3 tests/dump_tests/ 
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-utilities/tests, configfile: pytest.ini
plugins: pyfakefs-4.5.3, cov-2.10.1
collected 116 items …
```

[debug dump] Refactoring Modules and Unit Tests

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Increase vs test timeout to 240 seconds similar to https://github.com/Azure/sonic-utilities/pull/1924
Started observing the following error:
##[error]The job running on agent Azure Pipelines 5 ran longer than the maximum time of 180 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134

[VS test] [202106]Increase vs test timeout to 240 seconds

---

.azure-pipelines/test-docker-sonic-vs-template.yml
doc/Command-Reference.md

Manual cherry-pick of https://github.com/Azure/sonic-utilities/pull/1941
Updating command reference reflecting the latest config reload behavior
Update command reference for the config reload behavior. These changes were introduced by #1664

[config reload][202106] Update command reference

---

show/main.py

Modify the filter function of `show runningconfiguration syslog`
Filter by ending "]" rather than split by ":"
add a syslog v6 server `sudo config syslog add f587::1:1`
run command `show runningconfiguration syslog`
```
admin@vlab-01:~$ show runningconfiguration syslog
Syslog Servers
----------------
[10.0.0.5]
[10.0.0.6]
[f587
```
```
admin@vlab-01:~$ show runningconfiguration syslog
Syslog Servers
----------------
[10.0.0.5]
[10.0.0.6]
[f587::1:1]
```

Fix invalid output of syslog IPv6 servers

---

scripts/portconfig

Signed-off-by: Mykola Gerasymenko <mykolax.gerasymenko@intel.com>
Wrong port speed is set if included as a substring in a speed literal.
For example if we have a valid supported speeds for a port with 4 lanes: 40000 and 100000. Then if we try to set 4000.
`sudo config interface speed Ethernet0 4000`
As a result, we will get a wrong set speed 4G:
```
dut:~$ show interfaces status
Interface  Lanes  Speed  MTU  FEC   Alias     Vlan   Oper  Admin   Type      Asym PFC
--------- ------ ------ ----  ---- --------   -----  ----- ------ -----------   -----
Ethernet0  0,1,2,3  4G  9100  rs  Ethernet1/1 routed  up    up   QSFP28 or later     off
```
Fixed finding the target (set) speed in the supported speeds list.
Set the wrong speed, which included as a substring in a speed literal.
For example, …

[port] Fix port speed set

---

doc/Command-Reference.md

Add explicit sections for showing management/loopback interfaces

Refine doc on show loopback/mgmt interfaces

---

config/main.py
tests/static_routes_test.py

Added portchannels support for static routes.
fix https://github.com/Azure/sonic-buildimage/issues/8907
Added check if nexthop is a portchannel and added check if this portchannel exists in config db.
```
config portchannel add PortChannel0001
sudo config route add prefix 20.0.0.1/32 nexthop PortChannel0001
```
Also
```
sudo config route add prefix 20.0.0.1/32 nexthop PortChannel0003
Error: portchannel does not exist.
```

[config] Add portchannel support  for static route 

---

sfputil/main.py
tests/sfputil_test.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Added following sfputil CLIs to support firmware upgrade on QSFP-DD transceivers:-
1. sfputil show fwversion [OPTIONS] <port_name>
2. sfputil firmware [OPTIONS] COMMAND [ARGS] ...
a. commit - Commit the running firmware
b. download - Download firmware 
c. run - Run the firmware
d. unlock - Unlock firmware download feature
e. upgrade - Upgrade firmware (combines a,b,c and d as one CLI) 
Firmware upgrade done successfully on Inphi, Molex and Centera QSFP-DD modules

[sfputil] Firmware download/upgrade CLI support for QSFP-DD

---

config/main.py
generic_config_updater/generic_updater.py
generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/config_test.py
tests/generic_config_updater/generic_updater_test.py
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

Added non-strict mode to patch sorting which is useful while building the E2E tests for the framework. It helps developers avoid the incompleteness of YANG models.
Was implementing by adding 2 options:
* Ignore tables without yang: This flag will ignore from validation all tables that does not have YANG model defined yet 
* Ignore path: This flag can explicitly ignore a path from validation, which can ignore any config. It will be useful for ignoring configs with YANG but the YANG is not up-to-date.
> :warning: **The non-strict mode is only meant for helping with E2E testing and not meant for production**
Added flags `ignore-non-yang-tables` and `ignore-path` to the config commands:
```
config apply-patch
config replace
config rollback
```
Added NonStrictSorter, together with the older …

[generic-config-updater] Adding non-strict mode

---

scripts/generate_dump

Backport [generate_dump] remove secrets from dump files #1886 to 201911
Add bash functions to remove secrets from dump files.
For tacacs key, radius key, snmp community srring, use sed command with regex to remove user secrets from dump files.
For certs, update tar command exclude list to remove those certs from dump file.
Run 'show techsupport' command and check secrets removed from dump files.

[generate_dump][201911] Remove secrets from dump files

---

scripts/soft-reboot

The soft-reboot command currently expects a platform that uses GRUB.
Information about the current kernel boot arguments is extracted from the
GRUB config file. This commit adds support for platforms that do not use GRUB
but rather uses Device Tree to define the current kernel boot arguments.
Example platform architectures using Device Tree include armhf and arm64.
Add soft-reboot command support for the armhf and arm64 platforms
Add logic to retrieve kernel boot arguments from the Device Tree rather than from the GRUB config for these platforms
Execute the soft-reboot command on an armhf or arm64 platform
sudo soft-reboot
Error response from daemon: Container 68b38ffde1c8a95922eed7706a2f92c46e5b6582539cecc4aaa7263803db56e3 is not running
cat: /host/grub/grub.cfg: No such file or …

[soft-reboot] Add support for platforms based on Device Tree

---

show/vxlan.py
tests/vxlan_test.py

What I did
Remove the unnecessary trailing space for `Total count : ` in the vxlan show commands, some developers are
used to be enabled the trim space functionality in their editor. These trailing
space are easily to be overlook and cause the unit test fail
Signed-off-by: Gord Chen <gord_chen@edge-core.com>

[vxlan] remove unnecessary trailing space for show commands

---

scripts/generate_dump

Signed-off-by: Noa Or <noaor@nvidia.com>
Added support for tech support extension scripts,
by cherry-picking of https://github.com/Azure/sonic-utilities/pull/1335 to branch 202012
The purpose is to have dumps of extensions in SONiC techsupport, even without App Extension infrastructure.
The new application will write a file that contains the dump command into /usr/bin/debug-dump folder, and it will appear in the output of `show techsupport` command.
It looks at /usr/bin/debug-dump for scripts, if it finds one it will execute them and save the output to dump/ folder.
Write a simple scripts that outputs something and place it under /usr/bin/debug-dump/

[202012] [generate_dump] allow to extend dump with plugin scripts

---

config/main.py

Fixes https://github.com/Azure/sonic-buildimage/issues/9473
Preserve the old order of the config reload
Manual tests
- change `SFLOW` feature state
```
admin@vlab-01:~$ show feature status
Feature         State            AutoRestart     SetOwner
--------------  ---------------  --------------  ----------
bgp             enabled          enabled
database        always_enabled   always_enabled
dhcp_relay      enabled          enabled         local
gbsyncd         enabled          enabled
lldp            enabled          enabled
macsec          disabled         enabled
mgmt-framework  enabled          enabled
mux             always_disabled  enabled
nat             disabled         enabled
pmon            enabled …
```

preserve old order for config reload

---

generic_config_updater/patch_sorter.py
tests/generic_config_updater/files/config_db_with_loopback_interfaces.json
tests/generic_config_updater/patch_sorter_test.py

Fix #1962
Updated `create-only` flag meaning.
From, Field is not replaceable but can be added or deleted. In other words:
- Field can be added
- Field can be deleted
- Field cannot be replaced
To, Field is only created, but never modified/updated. In other words:
- Field cannot be added, only if the parent is added
- Field cannot be deleted, only if the parent is deleted
- Field cannot be replaced
Also marked `/LOOPBACK_INTERFACE/LOOPBACK#/vrf_name` as `create-only`
- Field was already not replaceable -- so no changes
- If field is added, but parent already exist -- fail create-only validation
- If field is deleted, but parent remain -- fail create-only validation
unit-test
Check issue to see how `apply-patch` behaved before this fix.
Each example below we show configdb, vrf_01, vrf_02, …

[generic-config-updater] Improving CreateOnly validator and marking /LOOPBACK_INTERFACE/LOOPBACK#/vrf_name as create-only

---

tests/mock_tables/counters_db.json
tests/portstat_test.py

Update test for checking TX/RX utilization
Add real values for TX/RX to mock table instead of zeroes 
run **portstat_test.py** via  `python3 setup.py test`  in  sonic-utilities tests

[portstat] check TX/RX utilization calculation correctness

---

config/main.py
generic_config_updater/change_applier.py
generic_config_updater/generic_updater.py
generic_config_updater/gu_common.py
tests/generic_config_updater/change_applier_test.py
tests/generic_config_updater/generic_updater_test.py
tests/generic_config_updater/gu_common_test.py

Implementing `dry-run` option flag.
- Supports only printing the steps generated from patch-sorting
- TODO in a future PR: Print the `SET` commands sent to `config_db`
- TODO in a future PR: Print the service validation commands
By implementing the DryRunConfigWrapper.
- Whenever a dry-run is issued, the CLI output will start with `** DRY RUN EXECUTION **`
- At each step we simulate `config_db`, we print a log msg starting with `** DryRun: Would `
**Apply patch**
```
admin@vlab-01:~$ sudo config apply-patch remove-acl-table.json-patch -d -i /BGP_NEIGHBOR -i /FEATURE -i /QUEUE -i /VLAN/Vlan1000/members -i /DEVICE_METADATA -i /FLEX_COUNTER_TABLE -i /SCHEDULER
** DRY RUN EXECUTION **
Patch Applier: Patch: [{"op": "remove", "path": …
```

[GCU] Implementing DryRun by printing patch-sorter steps/imitating config_db

---

config/muxcable.py
doc/Command-Reference.md
show/main.py
show/processes.py
show/system_health.py
utilities_common/cli.py

Changed the show command help text to be more consistent with eachother. In particular, I made them all have the same format.
Edited the relevant comments in the show command scripts and the Command-Reference.md documentation.
Run show -h.
For example, 
lldp                  LLDP (Link Layer Discovery Protocol) information.
For example, 
lldp                  Show LLDP information.

show command help text fix.

---

tests/generic_config_updater/files/patch_sorter_test_failure.json
tests/generic_config_updater/files/patch_sorter_test_success.json
tests/generic_config_updater/patch_sorter_test.py

Moved PatchSorter unit-test to json file to make it easier to read/maintain
In the future this test json file can be used for adding nightly tests.
While testing I had to set `skip_exact_change_list_match=True` because different runs of the same input produce correct but different changes. It is better to always generate the same steps for easier debugging. Created issue: #1976
Copied to Json file the following:
- current_config i.e. current running config
- patch 
- expected change list
unit-tests

[GCU] Moving PatchSorter unit-test to json file to make it easier to read/maintain

---

config/main.py

fixes https://github.com/Azure/sonic-buildimage/issues/9411
on multi-asic platform, config reload CLI was not working without -f option.
This was because swss_ready function was checking status of swss.service and multi-asic platform will not have swss.service, it will have per-namespace swss service.
Fix swss_ready function to check all swss services status running on the platform.
On multi-asic platform, before Fix:
admin@vlab-08:~$ sudo config reload -y
SwSS container is not ready. Retry later or use -f to avoid system checks
After fix, on multi-asic platform, execute config load_minigraph to reload all services, immediately after that execute config reload. This should print swss not ready message.
Once swss services are up, execute config reload again and this time it should run …

Update swss_ready check to check per namespace swss service

---

generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

Loading sonic-yang models only once, and re-using them. This makes the sorting a lot faster.
How to verify `loadYangModel` took a lot of time?
Add the following snippet to `TestPatchSorter`
```python
from pstats import Stats
import cProfile
class TestPatchSorter(...):
def setUp(self):
"""init each test"""
self.pr = cProfile.Profile()
self.pr.enable()
print("\n<<<---")
def tearDown(self):
"""finish any test"""
p = Stats (self.pr)
p.strip_dirs()
p.sort_stats ('cumtime')
p.print_stats ()
print("\n--->>>")
.
.
.
def verify(self, cc_ops=[], tc_ops=[]):
config_wrapper=ConfigWrapper()
target_config=jsonpatch.JsonPatch(tc_ops).apply(Files.CROPPED_CONFIG_DB_AS_JSON)
current_config=jsonpatch.JsonPatch(cc_ops).apply(Files.CROPPED_CONFIG_DB_AS_JSON)
patch=jsonpatch.make_patch(current_config, …
```

[GCU] Loading yang-models only once

---

doc/Command-Reference.md

Updated the  Command-Reference doc for the below changes.
1. Added few more info to `config interface breakout` command for user reference and the `CLI section of DPB HLD DOC` link has been added for more info.
2. Same goes for `show interface breakout`
3. updated `config interface speed` info as per version.
All the above-mentioned points have been added for SONiC version >=**202006**.
Signed-off-by: Sangita Maity <samaity@linkedin.com>

[doc|DPB] Update DPB related interface breakout command Info

---

show/interfaces/__init__.py
tests/show_breakout_test.py

Signed-off-by: Sangita Maity <samaity@linkedin.com>
This PR fixed issue for [show interface breakout](https://github.com/Azure/sonic-buildimage/issues/7957) issue
**Before this fix**
removed `Ethernet60` from breakout_cfg table for unit testing and got the issue
```
 
admin@lnos-x1-a-asw04:~$ sudo redis-cli -n 4 del "BREAKOUT_CFG|Ethernet60"
(integer) 1
admin@lnos-x1-a-asw04:~$ sudo redis-cli -n 4 hgetall "BREAKOUT_CFG|Ethernet60"
(empty array)
admin@lnos-x1-a-asw04:~$ show int breakout
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in …
```

[breakout] Fix the check  when port is not present in BREAKOUT_CFG table

---

generic_config_updater/gu_common.py
tests/generic_config_updater/files/patch_sorter_test_success.json
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

Fixes #1976
Different runs of `apply-patch` would produce different sorted steps. It is better to be consistent while producing the sorted steps to make it easier to debug issues in the future.
The issue is with using `set(list)` to remove duplicates from the list. Looping over the set elements does not guarantee same order every time we iterate. To reproduce this do the following:
1. Create a file named `test.py` with the content
```python
x = ["XYZ", "ABC", "DEF"]
y = set(x)
print(y)
```
2. Run `python3 test.py`
3. Again `python3 test.py`
4. Again `python3 test.py`
The output of these runs will be different each time.
Instead of returning a `set`, return a list of `ref_paths` which does not have duplicated elements inserted to begin with.
unit-tests

[GCU] Different apply-patch runs should produce same sorted steps

---

generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/generic_config_updater/files/patch_sorter_test_failure.json
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

Adding unit-test for cases where `PatchSorter.sort` is called to update config that has tables without YANG. This would sometimes throw the error
```
KeyError: 'NameOfTableWithoutYang'
```
This error happened because `find_ref_paths` would remove tables without yang as a side-effect.
Earlier this was fixed by cropping tables without yang models from current and target configs. That fix had 2 issues:
- It is not addressing the real problem which is cropping the config as a side effect to `find_ref_paths`
- If the move generated by the inner logic of `PatchSorter` was to replace whole config, it would result in replacing whole config with the config with cropped non-yang tables
- Fixing `find_ref_paths` to not crop the given config as a side-effect
- Added a unit-test for that
- Revert the …

[GCU] Copying config_db before calling sonic_yang.loadData

---

generic_config_updater/patch_sorter.py
tests/generic_config_updater/patch_sorter_test.py

Using `SimulatedConfig` instead of `TargetConfig` for validating a move using `NoDependencyMoveValidator`
SimulatedConfig: config after applying the given move
TargetConfig: the final config state that's required by the patch
The problem is if the moves is to update a list item, the list item location in the `TargetConfig` might have different location in the `CurrentConfig`.
The reason for that is the `TargetConfig` has the final outcome after applying the `patch`, but the move might be just making a small change towards this goal.
Example:
Assume current_config
```
{
"VLAN": {
"Vlan100": {
"vlanid": "100",
"dhcp_servers": [
"192.0.0.1",
"192.0.0.2"
]
}
}
}
```
TargetConfig:
```
{
"VLAN": {
"Vlan100": {
"vlanid": "100",
"dhcp_servers": [
"192.0.0.3"
]
}
}
}
```
Move:
```python …
```

[GCU] Using simulated config instead of target config when validating replace operation in NoDependencyMoveValidator

---

config/main.py

Replace the wrong help message of "Set lossless PGs for the interface" with the right one "Set interface cable length"
Update the help message to the relevant one on main.py 
Run the following command: "config interface cable-length Ethernet0 -h"
Set lossless PGs for the interface
Set interface cable length

Fix wrong help message for cable length setting

---

scripts/generate_dump

This reverts commit 44ec4c8b8c89d8a38d1451d40e44979252831304.
revert "[202012] [generate_dump] allow to extend dump with plugin scripts (#1945)" commit
N/A
N/A

[202012] Revert #1945 commit

---

config/main.py
doc/Command-Reference.md
pfcwd/main.py
tests/pfcwd_test.py

… it says invalid options. Update it with a correct command
Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>
The example of pfcwd start command in start function comments is a little confused, after execution, it says invalid options. 
Update it with a correct command.
The output of the current example is:
admin@vlab-01:~$ sudo pfcwd start --action drop ports all detection-time 400 --restoration-time 400
Failed to run command, invalid options:
ports
detection-time
Update the example with a correct one in pfcwd start function comments which is also usage info for pfcwd start command.
Enter SONiC DUT, input the following command:
sudo pfcwd start --help
sudo pfcwd start --action drop all 400 --restoration-time 400
admin@vlab-01:~$ sudo pfcwd start --help
Usage: pfcwd start [OPTIONS] …

Update the example for pfcwd start command

---

config/main.py

Show the default enum for the option `--format`
Added `show_default=True`
Checkout output below
```bash
admin@vlab-01:~$ sudo config apply-patch -h
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Apply given patch of updates to Config. A patch is a JsonPatch which
follows rfc6902. This command can be used do partial updates to the config
with minimum disruption to running processes. It allows addition as well
as deletion of configs. The patch file represents a diff of ConfigDb(ABNF)
format or SonicYang format.
<patch-file-path>: Path to the patch file on the file-system.
Options:
-f, --format [CONFIGDB|SONICYANG]
format of config of the patch is either
ConfigDb(ABNF) or SonicYang
-d, --dry-run                   test out the command without affecting
config state
-v, --verbose …
```

[GCU] Show default option for '--format'

---

config/plugins/barefoot.py
doc/Command-Reference.md
show/plugins/barefoot.py

Signed-off-by: Oleksandr Kolomeiets <oleksandrx.kolomeiets@intel.com>
* Added "show platform barefoot profile" command
* Added "config platform barefoot profile" command
* Updated Command Line Reference Guide
* Created plugins for Barefoot in show/plugins/barefoot.py and config/plugins/barefoot.py
* Updated doc/Command-Reference.md
```
admin@sonic:~$ show platform barefoot profile
Current profile: x1
Available profile(s):
x1
x2
```
```
admin@sonic:~$ sudo config platform barefoot profile x1
Swss service will be restarted, continue? [y/N]: y
```

[Barefoot] Added CLI to list/set P4 profile

---

generic_config_updater/gu_common.py
tests/generic_config_updater/gu_common_test.py

Make sure the same order is always returned while getting the referrer paths i.e. data dependencies.
Sort the returned list.
unit-tests

[build-failure-fix][GCU] Sort referrer paths alphabetically directly on 202111

---

show/bgp_frr_v4.py
show/bgp_frr_v6.py

Fix the ro command rw permission required issue
```
show ip bgp neighbors 
Make sure your account has RW permission to current device.
Otherwise sudo requests will be rejected.
```

[Bug]: Fix show ip bgp nei command rw required issue

---

config/plugins/barefoot.py
doc/Command-Reference.md
show/plugins/barefoot.py

Refer to #1951 for details
The PR #1951 was reverted in #2016 because it was thought to be causing the build failure in sonic-swss TestWarmReboot UTs. But it seems the failures in TestWarmReboot are still occurring e.g. #2017 [build](https://dev.azure.com/mssonic/build/_build/results?buildId=65653&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e)
I think we can reapply #1951 and need to investigate TestWarmReboot tests instability

Reapply "[Barefoot] Added CLI to list/set P4 profile (#1951)""

---

setup.py

to sonic-utilities-test.
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
Include mock port_config.ini files in sonic-utilities-test.
https://github.com/Azure/sonic-utilities/pull/1954 - added unit-test for port2alias which added mock port_config files.
But these new files were not included in the package.
Update setup.py file to include *.ini files in mock_tables.
Unit-test passes.

[201911][port2alias]: Include mock port_config.ini files

---

generic_config_updater/patch_sorter.py
tests/generic_config_updater/files/patch_sorter_test_success.json
tests/generic_config_updater/patch_sorter_test.py

Fixes #2007 
Most of the children of `/BGP_NEIGHBOR/*` except `admin_status` are create-only field i.e. they can only be created with the neighbor but cannot be modified later.
Validated each attribute is read-only by the following steps:
* Delete a neighbor
* Add the neighbor back without the attribute under test e.g. `holdtime`
* show running config for the neighbor
* show neighbor config using `show ip bgp neighbor <ip>`
* Add just the attribute under test e.g. `holdtime`
* show running config for the neighbor -- we can see the attribute is added
* show neighbor config using `show ip bgp neighbor <ip>` -- we can see the attribute change did not take effect
Example for `holdtime`:
```sh
admin@vlab-01:~$ sudo config apply-patch remove-bgp-neighbor.json -i '' 
.
.
.
Patch applied …
```

[GCU] Mark children of bgp_neighbor as create-only

---

doc/Command-Reference.md
show/main.py
tests/show_bfd_test.py

Cherry-pick changes in https://github.com/Azure/sonic-utilities/pull/1942 to 202012 branch
Add show command for BFD sessions. 
Add show command for BFD session and unit tests.
Verify the show command locally and unit test passes.
Example output:
```
>> show bfd summary
Total number of BFD sessions: 3
Peer Addr    Interface    Vrf      State    Type          Local Addr      TX Interval    RX Interval    Multiplier  Multihop
-----------  -----------  -------  -------  ------------  ------------  -------------  -------------  ------------  ----------
10.0.1.1     default      default  DOWN     async_active  10.0.0.1                300            500             3  true
10.0.2.1     Ethernet12   default  UP       async_active  10.0.0.1                200            600             3  false …
```

[202012] Add show command for BFD sessions

---

.azure-pipelines/build-docker-sonic-vs-template.yml

For downloading docker-sonic-vs artifact from Azure.sonic-swss pipeline, it will also try to download artifacts if the build is partially succeeded

[build] allowPartiallySucceededBuilds: true

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Currently the latest sonic-swss-pytests has warning in armhf stage. We should allow download artifact from partially succeeded builds.
ref: https://dev.azure.com/mssonic/build/_build?definitionId=15&_a=summary&view=branches

[ci] allow download partially succeeded builds for sonic-swss-pytests artifact

---

.azure-pipelines/test-docker-sonic-vs-template.yml

… pytests
Like https://github.com/Azure/sonic-utilities/pull/2043, while downloading sonic-swss-pytests artifact from Azure.sonic-swss pipeline, it will also try to download artifacts if the build is partially succeeded.

[build] allowPartiallySucceededBuilds: true in sonic swss pytests download 

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/test-docker-sonic-vs-template.yml

1. upstream [Azure.sonic-swss](https://dev.azure.com/mssonic/build/_build?definitionId=15&_a=summary) keep failing at vstest, however the build artifacts should be good to download
2. Fix path of build_and_install_module

[ci] Fix pipeline on build_and_install_module

---

config/vlan.py

fixing https://github.com/Azure/sonic-buildimage/issues/9946
`config vlan add 1`
CLI throws an error specifying the user that Vlan 1 is default VLAN. Orchagent doesn't crash.

Check for adding default VLAN attempt added

---

tests/generic_config_updater/gu_common_test.py

Did a debug session with Ping Mao and found this case is failing in her PR: https://github.com/Azure/sonic-buildimage/pull/9545 I think it is an interesting case and I added it explicitly to GCU.
Adding unit-test where path and ref paths are under the same YANG container
[sonic-loopback-interface.yang](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-loopback-interface.yang) has:
```yang
container sonic-loopback-interface {
container LOOPBACK_INTERFACE {
list LOOPBACK_INTERFACE_LIST {
...
leaf name{
type string;
}
...
list LOOPBACK_INTERFACE_IPPREFIX_LIST {
leaf name{
...
type leafref {
path "../../LOOPBACK_INTERFACE_LIST/name";
}
}
...
```
Unit-test added
unit-test

[GCU] Adding unit-test where path and ref paths are under the same YANG container

---

generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/generic_config_updater/files/config_db_with_port_critical.json
tests/generic_config_updater/files/patch_sorter_test_success.json
tests/generic_config_updater/patch_sorter_test.py

Fixes #1930 
Issue can be summarized into these 2 case:
* A patch can contain an operation to turn port `admin up` -- do at the end
* A patch that modifies config that needs the port to be down -- start by bringing the port down then do the update then bring it back up
The configs that need the port to be down, we will call them `critical-port` configs.
* Added a move validator to validate `critical-port` configs, which does the following
* If a port is up, make sure the move does not make changes to related `critical-port` configs
* If the move is turning a port up, make sure there is no `critical-port` config are still left in the patch
* Added a move extender to `critical-port` changes:
* If a port is up, bring down if there are critical-port changes
* If the move is turning a port up, …

[GCU] Turning port admin down before some critical port changes

---

azure-pipelines.yml

1. Use official build debian pkg.
2. parameterize download source branch for future release branch.

[ci] Use official build debian pkg instead and parameterize source branch.

---

generic_config_updater/gu_common.py
tests/generic_config_updater/files/config_db_with_bgp_neighbor.json
tests/generic_config_updater/files/config_db_with_lldp.json
tests/generic_config_updater/gu_common_test.py

Fixes #2041
Supporting groupings during `config-db path` <-> `config-yang xpath` translation
This mimics the `config-db` <-> `config-yang`  translation as added by https://github.com/Azure/sonic-buildimage/pull/8318
Handled groupings of leaf commands only as that's what is supported in sonic-yang-mgmt
unit-test

[GCU] Supporting Groupings during path-xpath translation

---

tests/interfaces_test.py
utilities_common/cli.py

Remove the warning of "Configuration database contains no ports" when ports table is empty.
Because when having a system with zero ports, this message appear per each access to ports tables on CONFIG DB
For example:
Run any cli command. For example  "show boot" or "show int st"
Observed behavior
root@r-sn4800-simx:/home/admin# show boot
Configuration database contains no ports
Configuration database contains no ports
Configuration database contains no ports
Remove the warning and remove the unit test verify this warning 
Remove all the ports and verify there is no such warning in case of running "show interface status" CLi command
Configuration database contains no ports
Interface    Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ------- …

Remove the warning message appear when there are no ports on CONFIG DB

---

counterpoll/main.py
tests/counterpoll_test.py
tests/mock_tables/config_db.json

Azure/sonic-swss#2031 updated the flex counter polling interval to 60s for watermark counters but the show command wasn't updated to reflect the correct default value
Display the correct poll interval for watermark related counters in the 'counterpoll show' command
Update the default interval to be the same as the one updated by the Orchs
Issue "counterpoll show", the queue, pg and buffer pool watermark should show default 60s
Updated the counterpoll unit tests to reflect the same

[counterpoll] Display the correct default poll interval for watermark counters

---

show/muxcable.py
tests/muxcable_test.py

Enhance ```show muxcable status``` to show last switchover time as well
sign-off: Jing Zhang zhangjing@microsoft.com
```
~$ show mux status 
PORT         STATUS    HEALTH
-----------  --------  ---------
Ethernet0    standby   unhealthy
Ethernet4    standby   unhealthy
Ethernet8    standby   unhealthy
Ethernet12   standby   unhealthy
Ethernet16   standby   unhealthy
Ethernet20   standby   unhealthy
Ethernet40   standby   unhealthy
Ethernet44   standby   unhealthy
Ethernet48   standby   unhealthy
Ethernet52   standby   unhealthy
Ethernet56   standby   unhealthy
Ethernet60   standby   unhealthy
Ethernet64   standby   unhealthy
Ethernet68   standby   unhealthy
Ethernet72   standby   unhealthy
Ethernet76   standby   unhealthy
Ethernet80   standby   unhealthy
Ethernet84   standby   unhealthy …
```

[muxcable][show] enhance show mux status to show last switchover time

---

show/muxcable.py

This change is required for such behavior with the command below, which works okay if you try with sudo
```
vdahiya@sonic:~$ show mux metrics Ethernet0 …
```

[show][muxcable] fix the sudo access error for show muxcable metrics

---

generic_config_updater/patch_sorter.py
tests/generic_config_updater/patch_sorter_test.py

Fixes #2029 #2062
Changes to fields under BGP_PEER_RANGE, BGP_MONITORS using GCU are not reflected unless each key is deleted and added back. This means the fields are create-only.
Marked the fields under BGP_PEER_RANGE, BGP_MONITORS as create-only
unit-test

[GCU] Marking fields under BGP_PEER_RANGE, BGP_MONITORS as create-only

---

sonic_installer/bootloader/uboot.py

Signed-off-by: Pavan Naregundi <pnaregundi@marvell.com>
Fixes #2089. 
Sonic-installer failure was seen due to missing import in uboot.py. 
Fix is just adding missing import.
Fix has been tested for successful sonic installation from sonic-installer

Fix sonic-installer failure due to missing import

---

scripts/intfutil
scripts/portstat
scripts/voqutil
tests/mock_tables/appl_db.json
tests/mock_tables/state_db.json

HLD change: https://github.com/Azure/SONiC/pull/932
Part of the fix for issue https://github.com/Azure/sonic-buildimage/issues/9595
For script intfutil, portstat, voqutil, try to get port operational speed from STATE_DB first. If speed value is not present or is "N/A" in STATE DB, try to get port operational speed from APPL_DB, this is for backward compatible
Extend existing unit test cases

Try get port operational speed from STATE DB

---

config/main.py
tests/portchannel_test.py

Corrected the validation check while adding a member to a PortChannel
This PR will fix the issue - https://github.com/Azure/sonic-buildimage/issues/9908
The CLI command should reject when trying to add member to a Portchannel when link-local is enabled in it.
```
root@sonic:/home/admin# config ipv6 enable link-local
root@sonic:/home/admin# config portchannel add PortChannel0001
root@sonic:/home/admin# config portchannel member add PortChannel0001 Ethernet64
Usage: config portchannel member add [OPTIONS] <portchannel_name> <port_name>
Try "config portchannel member add -h" for help.
Error:  Ethernet64 has ip address configured
```
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

Validation check correction while adding a member to PortChannel

---

scripts/generate_dump

exclude **mft** and **mlnx** folders from **/etc**  during execution **generate_dump**  
fix appropriate **--exclude** pattern in tar cmd execution (add * character )
py.test show_techsupport/test_techsupport_no_secret.py  --inventory="../ansible/inventory,../ansible/veos" --host-pattern (testbad) --module-path                ../ansible/library/ --testbed (testbad)-(topo) --testbed_file ../ansible/testbed.csv --allow_recover --assert plain --log-cli-level info --show-capture=no -ra --showlocals -v  --skip_sanity

[generate_dump] exclude mft and mlx folders from /etc

---

generic_config_updater/patch_sorter.py
tests/generic_config_updater/patch_sorter_test.py

Fix https://github.com/Azure/sonic-utilities/issues/2068
Changes to fields under MIRROR_SESSION using GCU are not reflected and removal will result in orchagent crash unless each key is deleted and added back. This means the fields are create-only.
Mark the fields under MIRROR_SESSION as create-only
unit-test

[GCU] Marking fields under MIRROR_SESSION as create-only

---

generic_config_updater/change_applier.py
generic_config_updater/generic_config_updater.conf.json
generic_config_updater/services_validator.py
tests/generic_config_updater/change_applier_test.py
tests/generic_config_updater/service_validator_test.py

After the json patch could be gathered in some way, it should fix nightly random failure issue.
When gcu make change to control plane ACL_RULE, the iptables doen't change immediately. There is a delay because caclmgr will update in 0.5 sec if no more update being made to config. So I add a caclrule validator to make sure the iptable is updated.
When caclrule is being changed, add a 1sec sleep to make sure caclmgr does update.
Run sonic-utilities unit test

[generic-config-updater] Add caclrule validator

---

config/muxcable.py
show/muxcable.py
tests/muxcable_test.py

Creating this PR because there was a conflict in #1961 and cherry-pick did not work
This PR supports for muxcable status command to support HWSTATUS as well.
the HWSTATUS could be either of these values
consistent/inconsistent/absent/Not-Y-Cable-Port/unknown
Made the changes in both sonic-platform-daemons as well as sonic-utilities. 
This PR is dependent on https://github.com/Azure/sonic-platform-daemons/pull/219
Ran the changes on Arista7260cx3 platform as well as unit-tests
```
admin@sonic:~$ show mux status
PORT         STATUS    HEALTH     HWSTATUS    LAST_SWITCHOVER_TIME
-----------  --------  ---------  ----------  ---------------------------
Ethernet0    active    unhealthy  consistent  2022-Mar-14 19:40:06.851394
Ethernet4 …
```

[show] add support for hwstatus in show muxcable status (#1961)

---

scripts/sfpshow

Command show interfaces transceiver presence/eeprom should not display recycle port.  
Script sfpshow needs to skip the recycle ports since recylce port is internal port without any SFP module.
This change is applicable to the 202111 branch
Modify the sfpshow script with using a function  recirc_prefix() to check if a port is a recycle port, skip it.
1. login to the linecard which contains recycle port
2. execute the CLI command:  show interface transceiver eeprom
```
admin@ixre-egl-board3:~$ show interfaces transceiver presence 
Port           Presence
-------------  -----------
Ethernet0      Not present
Ethernet1      Not present
Ethernet2      Not present
Ethernet3      Not present
...
Ethernet30     Not present
Ethernet31     Not present
Ethernet32     Not present
Ethernet33     Not …
```

[sfpshow][recycle_port]  Command show interfaces transceiver presence/eeprom should not display recycle port.

---

doc/Command-Reference.md
show/main.py

Add the current date attribute to the "show version" output that includes the current date and hour on the switch.
In sonic-utilities, in the "version" subcommand, print of the current date will be added using "datetime" from the "datetime" library.
Execute "show version" command and verify "Date" row under the "Uptime" row.
admin@sonic:~$ show version
SONiC Software Version: SONiC.HEAD.32-https://github.com/EdenGri/sonic-utilities/commit/21ea29a23f1f1b4a3ce294e6cbdaee4388047231
Distribution: Debian 9.8
Kernel: 4.9.0-8-amd64
Build commit: https://github.com/EdenGri/sonic-utilities/commit/21ea29a23f1f1b4a3ce294e6cbdaee4388047231
Build date: Fri Mar 22 01:55:48 UTC 2019
Built by: johnar@jenkins-worker-4
Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1 …

Add date to show version

---

scripts/fast-reboot

This is the PR for 202012 only as https://github.com/Azure/sonic-buildimage/pull/10046 cannot be cherry-picked to 202012.
Stopping swss and syncd causes some driver module unloading. Those driver modules are depended by PMON. This could trigger ERROR logs in syslog like:
```
Failed to run thermal policy all fan and psu presence
```
Adjust warmboot shutdown order in make file
Manual test

[202012] Stop PMON before stopping BGP while doing warmboot/fastboot

---

scripts/intfutil
scripts/portstat
scripts/voqutil
tests/dump_tests/dump_state_test.py
tests/mock_tables/state_db.json

Recently enhancements update port oper speed in state_db and query it do display in show commands. However the oper speed gets updated only when admin is up. When admin goes down and if the user configures new speed it doesn't get updated in state_db. So a query to show interface status displays the last set port speed and not newly updated speed.
To overcome the issue, the port speed is read from state_db only when oper status is up. Else it is obtained from config_db.
Added test configuration to verify the scenario.

Fixing get port speed when oper status is down

---

config/main.py

Fix issues in `clear_qos`
- Remove tables BUFFER_PORT_INGRESS_PROFILE_LIST and BUFFER_PORT_EGRESS_PROFILE_LIST
When `clear_qos` is executed, all QoS- and buffer-related tables should be removed. Currently, both tables are missed. This is to fix it.
- Adjust the order in which the buffer and QoS tables are removed
Remove the tables whose entries depend on other tables first and then the tables whose entries are referenced by other tables.
Any object can be removed from SAI only if there is no object referencing it. There are retrying and dependency-tracking mechanisms to guarantee it in `orchagent`.
If CLI operates the table in an order where the referencing tables removed first before referenced tables, it is possible to reduce the probability to retry theoretically.
The order does not …

[QoS] Fix issues in clear_qos

---

scripts/coredump_gen_handler.py
scripts/generate_dump
tests/coredump_gen_handler_test.py
utilities_common/auto_techsupport_helper.py

1) Print the last statement as the techsupport dump name, as some automation processes might depend of parsing the last line to infer the dump path.
```
Previously:
handle_exit
Removing lock. Exit: 0
removed '/tmp/techsupport-lock/PID'
removed directory '/tmp/techsupport-lock'
Updated:
handle_exit
Removing lock. Exit: 0
removed '/tmp/techsupport-lock/PID'
removed directory '/tmp/techsupport-lock'
/var/dump/sonic_dump_r-bulldog-03_20220324_195553.tar.gz
```
2) Don't acquire the lock when running in NOOP mode
3) Set the set -v option just before running main so that it won't print the generate_dump code to stdout
4) Update the auto-techsupport script to handle EXT_RETRY and EXT_LOCKFAIL exit codes returned by show techsupport command. 
5) …

[techsupport] Handle minor fixes of TS Lock and update auto-TS

---

scripts/fdbshow

• Fixes an issue where VLAN ID of None results in "int() argument must be a string, a bytes-like object or a number, not 'NoneType'" error.
Signed-off-by: James Denton <james.denton@outlook.com>
Fixed "show mac" command execution failure when the system has an FDB entry linked to default Vlan 1 that cannot be looked up (returns None).
If VLAN ID is None, assume it is 1 and allow the entry to be listed.
Pass traffic through an unconfigured interface and perform a 'show mac' or 'fdbshow'  command. 
admin@sonic:~$ show mac
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
admin@sonic:~$ show mac
No.    Vlan  MacAddress         Port          Type
-----  ------  -----------------  ------------  -------
1       1  98:03:9B:BE:E9:68  Ethernet60    Dynamic
2       1 …

Fix 'show mac' output when FDB entry for default vlan is None instead of 1

---

config/config_mgmt.py
tests/config_mgmt_test.py

libYang converts ietf yang types to lower case internally,which
creates false config diff for us while DPB.
This PR fixes the issue by not precessing false diff.
Related issue"
https://github.com/Azure/sonic-buildimage/issues/9478
Signed-off-by: Praveen Chaudhary <pchaudhary@linkedin.com>
fixes issue: https://github.com/Azure/sonic-buildimage/issues/9478
libYang converts ietf yang types to lower case internally,which
creates false config diff for us while DPB.
Example:
For DEVICE_METADATA['localhost']['mac'] type is yang:mac-address.
Libyang converts from 'XX:XX:XX:E4:B3:DD' -> 'xx:xx:xx:e4:b3:dd'
so args for function _recurCreateConfig in this case will be:
diff = DEVICE_METADATA['localhost']['mac']
where DEVICE_METADATA': {'localhost': {'mac': ['XX:XX:XX:E4:B3:DD', …

[config/config_mgmt.py]: Fix dpb issue with upper case mac in device_metadata.

---

scripts/fast-reboot

Remove obsolete code.
Removed obsolete code.
Run warm-reboot.
*Requested for*: 202111

[scripts/fast-reboot] cleanup

---

show/muxcable.py

Currently the response for hwmode muxdirection comes from ycabled. Since ycabled might not be running/exited state or
if the underlying hardware takes a long time to reciprocate the response for muxdirection, we decrease the timeout for the command, so atleast the user can see the output of CLI in 100ms. 
Added a constant timeout variable inside show/muxcable.py
Ran the change on Test DUT and unit-tests

[show][muxcable] Decrease the timeout for show mux status/hwmode muxdirection from 1 sec to 100ms

---

doc/Command-Reference.md

Signed-off-by: EdenGri <eden7045@gmail.com>
Fix command for portchannel creation
Change the command line guide:
Before:
config portchannel (add | del) [min-links ] [fallback (true | false)]
After:
config portchannel (add | del) [--min-links ] [--fallback (true | false)]

Fix incorrect command for portchannel creation

---

scripts/fast-reboot

Service timers may trigger service start in the middle of warm-reboot. Stopping them in advance prevents this issue.
Stopped all service timers that are part of sonic-delayed.target
Run warm-reboot.
*Requested for*: 202111, 202012

[scripts/fast-reboot] stop timers in advance

---

config/main.py

Now the `config load_minigraph` command will automate enable pfcwd for non-mgmt devices. However the `BmcMgmtToRRouter` not been count as a mgmt device.
Add check to avoid enable pfcwd for `BmcMgmtToRRouter`

[config] Do not enable pfcwd for BmcMgmtToRRouter

---

scripts/portconfig
tests/config_an_test.py

Block **"config interface type"** and **"config interface advertised type"** configuration on RJ45 ports
```
admin@sonic:~$ sudo config interface type Ethernet0 XGMII
Setting RJ45 ports' type is not supported
admin@sonic:~$ sudo config interface advertised-type Ethernet0 XGMII
Setting RJ45 ports' advertised types is not supported
```
Mock table depends on PR https://github.com/Azure/sonic-utilities/pull/2110
Check port type in the command, if RJ45 port then exit with not supported print out.
run above command on platforms with RJ45 ports

Enhance "config interface type/advertised-type" to be blocked on RJ45 ports 

---

show/main.py

Fixed error message: "Failed to get routing stack: a bytes-like object is required, not 'str'" introduced by https://github.com/Azure/sonic-utilities/pull/2117
Add missing 'text' paramter
Run on switch
Required for 202111

[show] fix get routing stack routine

---

scripts/intfutil
tests/mock_tables/state_db.json

Signed-off-by: Kebo Liu <kebol@nvidia.com>
In PR https://github.com/Azure/sonic-utilities/pull/2110 introduced an enhancement to support display port speed with different unit when it is RJ45 ports, however, it only covered the case that the speed was fetched from APPL_DB. 
Recently there is a change to fetch the speed from STATE_DB in some cases, the same logic also needs to be applied in this case.
1. rename `appl_db_port_speed_parse`  to a more generic name `port_speed_parse`.
2. call `port_speed_parse` when speed is fetched from STATE_DB.
3. In UT test, add port status entires to mocked STATE_DB to cover the logic that get port speed from STATE_DB.
UT and test it on platform support RJ45 ports

Fix speed parsing when speed is NOT fetched from APPL_DB

---

scripts/reboot

During a cold reboot on an image built with ENABLE_ASAN=y, swss and syncd (only on Mellanox platform) are explicitly stopped.
This will make the relevant processes receive SIGTERM and generate the ASAN reports.
The behavior for fast/warm reboots is not affected.
The behavior of regular (ENABLE_ASAN=n) images is not affected.
Modified the reboot script so the asan logs are generated on reboot.
Added stop_services_asan() to reboot script.
Added "asan: 'yes'" to the /etc/sonic/sonic_version.yml
Checked that relevant containers are stopped and logs are generated

[Mellanox] [reboot] [asan] stop asan-enabled containers on reboot

---

doc/Command-Reference.md

HLD: https://github.com/Azure/SONiC/pull/908
Add CLIs document for route flow counter feature, CLI PR: https://github.com/Azure/sonic-utilities/pull/2031
Add CLIs document for route flow counter feature
Run build
Enable/disable configuration:
```
counterpoll flowcnt-route  <enable | disable>
Example:
admin@sonic:~$ counterpoll flowcnt-route enable
```
Polling interval configuration:
```
counterpoll flowcnt-route interval <time_in_msec> // default - 1000ms
Example:
admin@sonic:~$ counterpoll flowcnt-route interval 2000
```
Show configuration:
```
counterpoll show
Example:
admin@sonic:~$ counterpoll show
Type                              Interval (in ms)          Status
--------------------------        ------------------        --------
FLOW_CNT_ROUTE_STAT               default(10000) …
```

[Command-Reference] Add CLI docs for route flow counter

---

tests/generic_config_updater/files/patch_sorter_test_success.json
tests/generic_config_updater/patch_sorter_test.py

Fixes #2051
RemoveRack/AddRack is confirmed to be working correctly by Renuka. Check https://github.com/Azure/sonic-mgmt/pull/5254
- Enabled ADD_RACK test
- Created REMOVE_RACK test using opposite data to ADD_RACK, verified the generated steps manually.
UnitTest and the KVM test by Renuka.

[GCU] Enabling AddRack and adding RemoveRack tests

---

generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

Fixes #2025
Stopping SonicYang from printing errors during config validation or moves generation.
If callers uses the `-v` option, they will see the SonicYang logs printed.
Also made sure that SonicYang returned error are properly propagated, so the user can see the exact errors.
Used the the option `print_log_enabled` while creating `SonicYang`
```python
sy = sonic_yang.SonicYang(self.yang_dir, print_log_enabled=sonic_yang_print_log_enabled)
```
Manually tested the change to the output, and added unit-tests to the gu_common functions that were modified.
Given an invalid patch will remove PORT table, while the PORT table is used.
```
admin@vlab-01:~$ sudo config apply-patch remove_port.json-patch -i /FEATURE
Patch Applier: Patch: [{"op": …
```

[GCU] Supressing YANG errors from libyang while sorting

---

config/main.py

Fix the path to `config_db.json` in config-reload for dual-tor device.
Related PR: https://github.com/Azure/sonic-utilities/pull/1465
Presently, there exists a typo in `config_db.json` filename that is sent as an argument to `filter_fdb_entries`. This causes failure during config reload:
```
Apr 27 01:35:26.990670 str2-7050cx3-acs-10 ERR filter_fdb_entries:
Got an exception file '/etc/sonic/configdb.json' does not exist:
Traceback: Traceback (most recent call last):
#012  File "/usr/local/lib/python3.7/dist-packages/fdbutil/filter_fdb_entries.py", line 146, in main
#012  file_exists_or_raise(config_db_filename)
#012  File "/usr/local/lib/python3.7/dist-packages/fdbutil/filter_fdb_entries.py", line 126, in file_exists_or_raise
#012  raise Exception("file '{0}' does not …
```

[202012][dualtor] Fix config_db.json path for config-reload

---

scripts/sfpshow

Due to `sfpshow eeprom` being a multi-ASIC function, ports on the same ASIC would be ordered and printed by each ASIC. I have fixed it so that the ports are printed in order, even if in multi-ASIC mode.
Previously we would keep appending to an output (string) class variable, and print that out after all of the information is gathered. Since this runs first on _asic0_, _asic1_, ... _asicN_, it would append each alphabetically organized list into one, which would then no longer be alphabetized.
Instead, I have the output saved into a dictionary of `EthernetN` -> `<output string>`. After the information is collected for each port, the `output string`s are pulled from the dictionary in the _natsorted_ order of the keys.
Run `sfpshow eeprom` and see all of the ports printing in order
``` …
```

Ordering fix for sfpshow eeprom

---

scripts/fast-reboot

Porting changes to 201911 branch from 201811: https://github.com/Azure/sonic-utilities/pull/1474
Below changes are made to warmboot/fastboot script:
Before shutdown, check docker exec on the relevant docker containers still works.
1. Disable trap handler after +e.
2. Disable services auto-restart during warm reboot. In 201811, only swss restart was needed to be extended. In 201911, most services can auto-restart, hence disabling them in the shutdown path.
3. Add timeout to make sure syncd shutdown request will return in time. 5s
4. Make sure that syncd pre-shutdown wait won't take more than 60 seconds.
5. Make sure subsequent docker exec won't stuck for long time
Mostly same changes as for 201811 branch, except that in 201911 all the services can auto-restart hence disable them all, …

[201911] Warmboot script improvements - timeout in exec and disable service-autorestart

---

config/main.py
tests/config_override_input/empty_input.json
tests/config_override_input/full_config_override.json
tests/config_override_input/new_feature_config.json
tests/config_override_input/partial_config_override.json
tests/config_override_test.py
tests/config_test.py

This PR is for supporting consume `golden_config_db.json` while loading minigraph. User can put the `golden_config_db.json` with minigraph file to override configDB after reload minigraph.
The `golden_config_db.json` looks just like a config_db.json and it will be placed on `/etc/sonic/golden_config_db.json`.
Add code `config override-config-table` command to let it consume `golden_config_db.json`
Add UT tests and run.
```
admin@vlab-01:~$ sudo config override-config-table -h
Usage: config override-config-table [OPTIONS] INPUT_CONFIG_DB
Override current configDB with input config.
Options:
--dry_run TEXT  Dry run, writes config to the given file
-h, -?, --help  Show this message and exit.
```

[minigraph]  Consume golden_config_db.json while loading minigraph

---

doc/Command-Reference.md
show/main.py
tests/show_vrf_test.py
tests/vrf_input/config_db.json

Fixed show vrf command to include vlan subinterfaces. Vlan subinterfaces are not displayed under show vrf.
Added VLAN_SUB_INTERFACE table to the list of tables to look in show vrf command.
Added UT to verify.

[show][vrf]Fixing show vrf to include vlan subinterface

---

scripts/intfutil
tests/dump_tests/dump_state_test.py
tests/intfutil_test.py
tests/mock_tables/state_db.json

Add support for remote speed advertisement, such that users could easily
identify the connection issues when autoneg is enabled.
HLD: Azure/SONiC#924
Signed-off-by: Dante Su <dante.su@broadcom.com>
Add support for remote speed advertisement
Implementation is done according to the AutoNeg HLD
1. Built-in unit tests
2. Manual tests
```
Interface    Auto-Neg Mode    Speed    Adv Speeds    Type    Adv Types    Oper    Admin
-----------  ---------------  -------  ------------  ------  -----------  ------  -------
Ethernet0          enabled      25G       10G,50G     CR4      CR4,CR2    down       up
Ethernet16              N/A     100M           N/A     N/A          N/A      up       up
Ethernet24              N/A       1G           N/A     N/A          N/A      up       up
Ethernet28 …
```

[autoneg] add support for remote speed advertisement

---

scripts/fast-reboot

This reverts commit 23e939846d4ea3507fba0fc51c0b3c4e34c6d6bd.
Revert "[scripts/fast-reboot] Shutdown remaining containers through systemd (#2133)"
This reverted PR is part of a story that refactors warm/fast shutdown sequence to gracefully stop services instead of killing them without any ordering and dependency requirements which creates several issues and is error prone for the future.
This PR must come together with https://github.com/Azure/sonic-buildimage/pull/10510.
However, #10510 is blocked due to an issue in swss-common https://github.com/Azure/sonic-swss-common/issues/603
And a fix by MSFT is in review https://github.com/Azure/sonic-swss-common/pull/606
I am reverting it because its dependency is still blocked and we cannot update submodule pointer. Once the dependency of the …

Revert "[scripts/fast-reboot] Shutdown remaining containers through systemd (#2133)"

---

scripts/fast-reboot

This reverts commit a5f55aa7060c2dff73627533ca489f7d29f51621.
Revert "[scripts/fast-reboot] Shutdown remaining containers through systemd (https://github.com/Azure/sonic-utilities/pull/2133)"
This reverted PR is part of a story that refactors warm/fast shutdown sequence to gracefully stop services instead of killing them without any ordering and dependency requirements which creates several issues and is error prone for the future.
This PR must come together with https://github.com/Azure/sonic-buildimage/pull/10510.
However, #10510 is blocked due to an issue in swss-common https://github.com/Azure/sonic-swss-common/issues/603
And a fix by MSFT is in review https://github.com/Azure/sonic-swss-common/pull/606
I am reverting it because its dependency is still blocked and we cannot update …

[202111] Revert "[scripts/fast-reboot] Shutdown remaining containers through systemd (#2133)"

---

config/main.py
tests/config_mirror_session_test.py

Signed-off-by: bingwang <wang.bing@microsoft.com>
FIX https://github.com/Azure/sonic-buildimage/issues/10795
`queue = 0` is not accepted by the validation of input because the follow check
https://github.com/Azure/sonic-utilities/blob/bce4694d3ad4454fc7181b99433457e76ab9e0a0/config/main.py#L2028-L2029
When addressing the issue, I saw similar issue in the logic of handling `gre_type`. The issue is also fixed.
Change `if queue` to `if queue is not None`
Verified by UT
```
python setup.py test --addopts "tests/config_mirror_session_test.py -v" 
========================================================================================= test session starts =========================================================================================
collected 3 items …
```

Fix validation of input of `config mirror_session add`

---

config/main.py
tests/config_test.py

Signed-off-by: Gang Lv ganglv@microsoft.com
'rstrip' behavior is wrong, if unit is 'gnmi.timer', the result is 'gn', and 'gnmi' is expected.
Use 're.sub' to replace 'rstrip'.
Run unit test for sonic-utilities.

[config reload] Fix invalid rstrip.

---

scripts/fast-reboot

Add new option "-u"  in ‘fast-reboot’ script, to add the “ssd-upgrader-part” boot option with SONiC partition and filesystem type.
Required by: https://github.com/Azure/sonic-buildimage/pull/10748
- Included a new option "-u" in fast-reboot script.
- If the option '-u' is specified, add "ssd-upgrader-part" with the SONiC partition and filesystem to the boot options to be used with kexec.
Execute fast-reboot with "-u" option and verify that the ssd-upgrader-part is specified in /proc/cmdline.
UT logs: [fast_reboot_new_option_logs.txt](https://github.com/Azure/sonic-utilities/files/8630286/fast_reboot_new_option_logs.txt)

[scripts/fast-reboot] Add option to include ssd-upgrader-part boot option with SONiC partition

---

scripts/portconfig

Signed-off-by: Kebo Liu <kebol@nvidia.com>
relevant SWSS and Yang PRs:
https://github.com/Azure/sonic-swss/pull/2268
https://github.com/Azure/sonic-buildimage/pull/10826
With SAI V.1.10.2, new interface types CR8/SR8/KR8/LR8 have been introduced, we should also support them from the CLI configuration.
Add new interface types to `VALID_INTERFACE_TYPE_SET`
Run CLI command "config interface types", new types can be accepted by the CLI.

[portconfig]Support new interface types CR8/SR8/KR8/LR8

---

generic_config_updater/gu_common.py
tests/generic_config_updater/gu_common_test.py

Fixes #2119
Sorting output:
```
Patch Applier: Applying 4 changes in order:
Patch Applier:   * [{"op": "remove", "path": "/BGP_PEER_RANGE/BGPSLBPassiveV6"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_PEER_RANGE/BGPVac", "value": {"ip_range": ["192.168.0.0/21"], "name": "BGPVac", "src_address": "10.1.0.32"}}]
Patch Applier:   * [{"op": "remove", "path": "/BGP_PEER_RANGE/BGPSLBPassive"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_PEER_RANGE/BGPSLBPassive", "value": {"ip_range": ["10.255.0.0/25"], "name": "BGPSLBPassive", "src_address": "10.1.0.32"}}]
```
Sorting output:
```
Patch Applier: Applying 4 changes in order:
Patch Applier:   * [{"op": "remove", "path": "/BGP_PEER_RANGE/BGPSLBPassiveV6"}]
Patch Applier:   * [{"op": "remove", "path": "/BGP_PEER_RANGE"}]
Patch Applier:   * …
```

[GCU] Validate peer_group_range ip_range are correct

---

tests/config_override_input/full_config_override.json
tests/config_override_input/port_config_override.json
tests/config_override_test.py

Modify the override-config-table testcase to cover PORT admin_status scenario.
Change the testcase to cover PORT admin_status change.
Run unit test.

Modify override testcase to cover PORT admin_status

---

config/main.py
scripts/intfutil
scripts/portconfig
show/interfaces/__init__.py
tests/config_lt_test.py
tests/dump_tests/dump_state_test.py
tests/intfutil_test.py
tests/mock_tables/appl_db.json
tests/mock_tables/state_db.json

HLD: Azure/SONiC#925
Add CLI support for link-trainig
1. portconfig: initial support for link-training config
2. config/main.py: initial support for link-training config
3. intfutil: initial support for link-training show command
4. show/interfaces/__init__.py: initial support for link-training show command
1. Manual test
2. Ran the Unit-tests to the corresponding changes
```
admin@sonic:~$ sudo config interface link-training Ethernet0 on
admin@sonic:~$ sudo config interface link-training Ethernet8 on
admin@sonic:~$ sudo config interface link-training Ethernet16 off
admin@sonic:~$ sudo config interface link-training Ethernet24 on
admin@sonic:~$ sudo config interface link-training Ethernet32 off
admin@sonic:~$ show interfaces link-training status
Interface      LT Oper    LT Admin    Oper …
```

sonic-utils: initial support for link-training

---

scripts/portconfig
tests/config_an_test.py

Allow config interface command to allow mtu only for physical ports. This has been the behavior until sometime back where a change made broke this and allowed the MTU to be passed to orchagent through port table which results in crash.
May 13 12:04:12.494964 r-tigon-20 INFO swss#buffermgrd: :- handlePortTable: Port PortChannel101: MTU updated from to 1514
May 13 12:04:12.495984 r-tigon-20 ERR swss#orchagent: :- set: switch id oid:0x0 doesn't exist
May 13 12:04:12.495984 r-tigon-20 ERR swss#orchagent: :- setPortMtu: Failed to set MTU 1536 to port pid:0, rv:-5
May 13 12:04:12.495984 r-tigon-20 ERR swss#orchagent: :- handleSaiSetStatus: Encountered failure in set operation, exiting orchagent, SAI API: SAI_API_PORT, status: SAI_STATUS
Blocked MTU setting if the port is not physical port. …

[portconfig] Allow to configure interface mtu for physical ports only

---

generic_config_updater/gu_common.py
tests/generic_config_updater/files/config_db_with_profile_list.json
tests/generic_config_updater/gu_common_test.py

Fixes #2170
Converting xpath to path:
- There is only 1 case where the path is referring to the list itself. Example:
```
path="/BUFFER_PORT_EGRESS_PROFILE_LIST/Ethernet9/profile_list",
xpath="/sonic-buffer-port-egress-profile-list:sonic-buffer-port-egress-profile-list/BUFFER_PORT_EGRESS_PROFILE_LIST/BUFFER_PORT_EGRESS_PROFILE_LIST_LIST[port='Ethernet9']/profile_list",
```
- There is no other case as we the list is just a single string, and we cannot refer to individual elements in string in ConfigDb.
Converting path to xpath, there are 2 cases:
- Xpath is pointing to leaf-list as a whole, return path of whole list
```
xpath="/sonic-buffer-port-egress-profile-list:sonic-buffer-port-egress-profile-list/BUFFER_PORT_EGRESS_PROFILE_LIST/BUFFER_PORT_EGRESS_PROFILE_LIST_LIST[port='Ethernet9']/pr …
```

[GCU] Handling non-compliant leaf-list with string values

---

scripts/sysreadyshow
setup.py
show/system_health.py
sonic_package_manager/manifest.py
sonic_package_manager/service_creator/feature.py
tests/mock_tables/state_db.json
tests/sonic_package_manager/test_service_creator.py
tests/system_health_test.py

show command support for System Ready Feature Implementation .
Also sonic-package-manager support for app readiness.
"show system-health sysready-status"
"show system-health sysready-status detail"
"show system-health sysready-status brief"
Introduce "show system-health sysready-status" click CLI with options.
Check the click CLIs introduced.
```
root@sonic:/home/admin# show system-health sysready-status
System is ready
Service-Name                      Service-Status    App-Ready-Status    Down-Reason
--------------------------------  ----------------  ------------------  -------------
as7326-56x-pddf-platform-monitor  OK                OK                  -
auditd                            OK                OK                  -
bgp                               OK                OK …
```

show commands for SYSTEM READY

---

config/config_mgmt.py
sonic_package_manager/manager.py

Should be merged after  https://github.com/Azure/sonic-buildimage/pull/10359 Used  **SonicYang** with extended list of params to init object.
Pass YANG attribute that allow do not automatically search for schemas in current working directory, which is by default searched automatically (despite not recursively).
extend ConfigMgmt constructor
1) Create some invalid link on switch :
**ln -s /usr/abc xxx**
2) run **spm list**
--> There should not be these messages:
```
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching …
```

[yang] extend ConfigMgmt constructor to pass YANG options

---

config/main.py
dump/match_helper.py
dump/match_infra.py
tests/mock_tables/config_db.json
tests/portchannel_test.py
utilities_common/db.py
utilities_common/helper.py

Backport https://github.com/Azure/sonic-utilities/pull/2151 to 202111
The change to handle it in oA is already added.
When this check is not performed when adding the config, the portchannel configuration will be inconsistent b/w Kernel and ASIC
Utilize the match infra to implement methods to check for ACL/PBH bindings to a port
Unit tests

[202111] [portchannel] Added ACL/PBH binding checks to the port before getting added to portchannel

---

config/main.py
doc/Command-Reference.md
tests/mock_tables/config_db.json
tests/static_routes_test.py

Fixed route add command to accept subinterface as dev option.
Previously VLAN_SUB_INTERFACE table was not checked when validating the dev. Added that table to the list of tables to look.
Added UT to verify the change

[subinterface] Fix route add command to accept subinterface as dev

---

sfputil/main.py
tests/sfputil_test.py

Tested on a QSFP-DD non-coherent Molex DR4 module. It won't crash. 
admin@sonic:~$ sudo sfputil show eeprom -d -p Ethernet16
Ethernet16: SFP EEPROM detected
Active App Selection Host Lane 1: 1
Active App Selection Host Lane 2: 1
Active App Selection Host Lane 3: 1
Active App Selection Host Lane 4: 1
Active App Selection Host Lane 5: 1
Active App Selection Host Lane 6: 1
Active App Selection Host Lane 7: 1
Active App Selection Host Lane 8: 1
Active Firmware Version: 3.1
CMIS Revision: 4.0
Connector: MPO 1x12
Encoding: N/A
Extended Identifier: Power Class 6 (12.0W Max)
Extended RateSelect Compliance: N/A
Hardware Revision: 1.1
Host Electrical Interface: 400GAUI-8 C2M (Annex 120E)
Host Lane Assignment Options: 1
Host Lane Count: 8
Identifier: QSFP-DD Double Density 8X Pluggable Transceiver …

fix for non-coherent cmis modules

---

scripts/db_migrator.py
tests/db_migrator_input/config_db/qos_map_table_expected.json
tests/db_migrator_input/config_db/qos_map_table_input.json
tests/db_migrator_test.py

Signed-off-by: bingwang <wang.bing@microsoft.com>
This PR is to cherry-pick changes in PR #2087 to `202012` branch after resolving conflicts.
This PR is to update `db_migrator` to support `pfcwd_sw_enable`.
Currently, table `pfc_enable` is to specify on which queue to enable PFC and pfc watchdog. As we are going to add two extra lossless queues on which on watchdog is enable(HLD https://github.com/Azure/SONiC/pull/950), a new table is required to specify on which queue to enable PFC watchdog. That is `pfcwd_sw_enable`.
| Table | Description |
| --- |----|
|pfc_enable|Specify on which queues to enable PFC| 
|pfcwd_sw_enable|Specify on which queues to enable software PFC watchdog|
HLD [DSCP remapping](https://github.com/Azure/SONiC/pull/950)
Change in orchagent [Update orchagent to support …

[cherry-pick][202012] Update db_migrator to support pfcwd_sw_enable

---

config/muxcable.py
show/muxcable.py
tests/mock_tables/config_db.json
tests/muxcable_test.py
utilities_common/general.py

this PR enhances the show mux status output to include the cable -type and soc_ipv4  and config mux mode is corrected to include soc_ipv4 an cable_type when the mux mode entry is overwritten. 
```
admin@sonic-1:~$ show mux config
SWITCH_NAME        PEER_TOR
-----------------  ----------
svcstr-7050-acs-2  10.1.0.33
port        state    ipv4             ipv6               cable_type      soc_ipv4
----------  -------  ---------------  -----------------  --------------  ---------------
Ethernet4   auto     192.168.0.2/32   fc02:1000::2/128   active-active   192.168.0.3/32
Ethernet8   auto     192.168.0.4/32   fc02:1000::4/128   active-active   192.168.0.5/32
Ethernet12  auto     192.168.0.6/32   fc02:1000::6/128   active-active …
```

[config][muxcable] Add support for displaying soc_ipv4 and cable_type in config/show muxcable commands

---

scripts/watermarkstat

Skip counters that are not enabled.
With change https://github.com/Azure/sonic-swss/pull/2143, following commands will cause exception:
admin@vlab-01:~$ show priority-group persistent-watermark headroom         
File "/usr/local/bin/watermarkstat", line 315, in <module>
main()
File "/usr/local/bin/watermarkstat", line 310, in main
watermarkstat.print_all_stat(table_prefix, args.type)
File "/usr/local/bin/watermarkstat", line 261, in print_all_stat
data = self.get_counters(table_prefix,
File "/usr/local/bin/watermarkstat", line 237, in get_counters
elif fields[pos] != STATUS_NA:
IndexError: list index out of range
With the change:
admin@vlab-01:~$ show priority-group persistent-watermark headroom         
Ingress headroom per PG:
Port
----------- …

[counters] skip showing counters that are not enabled

---

config/config_mgmt.py
tests/config_mgmt_test.py

Revert parameter from function that was mistakenly added in https://github.com/Azure/sonic-utilities/pull/2118
We don't need to pass 'sonic_yang_options' to static function get_module_name()
remove 'sonic_yang_options' from SonicYang object creation in get_module_name()

[yang] remove mistakenly added parameter for 'get_module_name'

---

scripts/port2alias
tests/port2alias_test.py

(cherry picked from commit 3714f63bfbaac377cb7638ddf73a3299d5d45a1f)
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
Cherry-pick of https://github.com/Azure/sonic-utilities/pull/1906 to 202012 branch
Fix conflict also few changes done to cherry-pick:
- get_port_config function takes asic id as argument in 2019/202012 branches
- Keep load_source of port2alias as module, as is used in unit-test in 202012 branch
get_port_config was modified to return different set number of arguments in PR: https://github.com/Azure/sonic-buildimage/pull/4222. Changes in this PR is:
1. To address the different set of return values
2.  To get the ports from all namespaces
3. To add unit-test
Additional change done over the cherry-pick:
added setup_class method in test case to load single asic mock …

[20212][port2alias]: Fix to get right number of return values

---

generic_config_updater/generic_config_updater.conf.json
generic_config_updater/services_validator.py

When GCU config NTP_SERVER table, its change is not actually taken info effect. Because NTP service is not restarted. So I add NTP service validator and restart service when NTP_SERVER is changed.
When NTP_SERVER table being configured through GCU, the ntp service will restart.
Run GCU E2E test for NTP_SERVER table.

[generic-config-updater] Add NTP validator 

---

config/muxcable.py

For active-standby type cable there will not be any soc_ipv4 entry in the "MUX_CABLE" table, hence when updating the config DB entry with update 
for 
```sudo config mux mode <state> <port>```
we should just check the cable_type and update the table entry
if no soc_ipv4 the value written in none in that case
Unit-tests cover the change

[config][muxcable] fix minor config DB logic issue

---

config/main.py
tests/config_test.py

Porting of https://github.com/Azure/sonic-utilities/pull/2200 into 202111
Fixed config reload when timer based delayed services are disabled. When they are disabled, the property property=LastTriggerUSecMonotonic returns "0". This will cause config reload to fail even though all enabled services are up.
Fixed the delayed services logic to check if the services are enabled before getting the property LastTriggerUSecMonotonic . Additionally fixed the return codes when config reload fails due to system checks
Added UT to verify it. Modified sonic-mgmt tests to verify it additionally.

[config reload][202111] Fixing config reload when timer based services are disabled

---

config/main.py
tests/config_test.py

DO NOT MERGE UNTIL https://github.com/Azure/sonic-mgmt/pull/5783 IS MERGED
Fixed config reload when timer based delayed services are disabled. When they are disabled, the property property=LastTriggerUSecMonotonic returns "0". This will cause config reload to fail even though all enabled services are up.
Fixed the delayed services logic to check if the services are enabled before getting the property LastTriggerUSecMonotonic . Additionally fixed the return codes when config reload fails due to system checks
Added UT to verify it. Modified sonic-mgmt tests to verify it additionally.

[config reload] Fixing config reload when timer based services are disabled

---

show/platform.py

> Equivalent PR for `master`: https://github.com/Azure/sonic-utilities/pull/2213
Gave cisco-8000 the ability to add sub-commands under `show platform <>` in our downstream repo. Currently every time we want to add/remove/update a cli, we must raise a PR upstream. 
I have the cisco-8000.py module import a list of `click` commands that are written in a module that is located in our platform code.
Run `show platform -h` to see all commands. We will be able to see `show platform inventory`. This is only available on cisco devices.

202012: Cisco-8000 show platform flexibility

---

show/plugins/cisco-8000.py

Gave cisco-8000 the ability to add sub-commands under `show platform <>` in our downstream repo. Currently every time we want to add/remove/update a cli, we must raise a PR upstream. 
I have the cisco-8000.py module import a list of `click` commands that are written in a module that is located in our platform code.
Run `show platform -h` to see all commands. We will be able to see `show platform inventory`. This is only available on cisco devices.

Cisco-8000 show platform flexibility

---

config/main.py
tests/config_test.py

Porting of changes https://github.com/Azure/sonic-utilities/pull/2200
- What I did
Fixed config reload when timer based delayed services are disabled. When they are disabled, the property property=LastTriggerUSecMonotonic returns "0". This will cause config reload to fail even though all enabled services are up.
- How I did it
Fixed the delayed services logic to check if the services are enabled before getting the property LastTriggerUSecMonotonic . Additionally fixed the return codes when config reload fails due to system checks
Added UT to verify it. Modified sonic-mgmt tests to verify it additionally.

[202205][config reload] Fixing config reload when timer based services are disabled

---

config/main.py
tests/config_override_input/empty_input.json
tests/config_override_input/full_config_override.json
tests/config_override_input/new_feature_config.json
tests/config_override_input/partial_config_override.json
tests/config_override_test.py
tests/config_test.py

This PR is to cherry-pick changes in PR https://github.com/Azure/sonic-utilities/pull/2140 to `202012` branch after resolving conflicts.
This PR is for supporting consume `golden_config_db.json` while loading minigraph. User can put the `golden_config_db.json` with minigraph file to override configDB after reload minigraph.
The `golden_config_db.json` looks just like a config_db.json and it will be placed on `/etc/sonic/golden_config_db.json`.
Step1: Load minigraph to configDB
Step2: If golden_config_db.json exists and contains some Table configuration, that Table in configDB will be overriden by the config in golden_config_db.json. Other config that not included in golden_config_db.json will keep the same as minigraph.
For example, assume below ACL_TABLE is loaded from minigraph:
_config …

[202012][minigraph] Consume golden_config_db.json while loading minigraph

---

scripts/coredump_gen_handler.py
scripts/generate_dump
show/main.py
tests/coredump_gen_handler_test.py
tests/techsupport_test.py
utilities_common/auto_techsupport_helper.py

Backport https://github.com/Azure/sonic-utilities/pull/2209 to 2111
Recently an issue is seen during the test_max_limit[core] sonic-mgmt test (Test for auto-techsupport).
This was a diff taken from two techsupport process runs and in the first case the core file to save was too large (almost 1G) and thus took upto 10 sec and all the commands that followed which append to the tar file have shown increased execution time. 
Finally, after 30 mins the execution timed out.
```
[ save_file:/var/core/bash.1653599272.10047.core.gz] : 10041  | [ save_file:/var/core/python3.1653598683.29.core.gz] : 42 mse
[ save_file:/var/core/bash.1653601099.288.core.gz] : 382 msec | [ save_file:/var/core/python3.1653598325.23.core.gz] : 43 mse
[ save_file:/var/crash/kdump_lock] : 473 msec                 | [ …
```

[202111] [generate dump] Move the Core/Log collection to the End of process Execution and removed default timeout 

---

sonic_installer/bootloader/aboot.py
sonic_installer/bootloader/bootloader.py
sonic_installer/bootloader/grub.py
sonic_installer/bootloader/onie.py
sonic_installer/bootloader/uboot.py
sonic_installer/main.py
tests/installer_bootloader_aboot_test.py
tests/installer_bootloader_bootloader_test.py
tests/installer_bootloader_grub_test.py
tests/installer_bootloader_onie_test.py
tests/installer_bootloader_uboot_test.py

* SONiC prefix shown twice when working branch
contains "image-" in its name.
Signed-off-by: Yevhen Fastiuk <yfastiuk@nvidia.com>
SONiC prefix is shown twice when the working branch contains "image-" in its name.
Fixed sonic-installer's one bootloader wrapper to show correct version.
Build image (the branch is important):
```
cd sonic-buildimage
git checkout -b dev-image-test
make configure PLATFORM=mellanox && make target/sonic-mellanox.bin
```
Run image on the switch and execute:
```
sudo sonic-installer list
```

Image-installer: Fix duplication of image prefix

---

scripts/coredump_gen_handler.py
scripts/generate_dump
show/main.py
tests/coredump_gen_handler_test.py
tests/techsupport_test.py
utilities_common/auto_techsupport_helper.py

Besides, it's better to collect the logs in the end, since we could collect more info and also core files are mostly static and it shouldn't matter much even if we collect them late. 
```
[ save_file:/var/core/bash.1653599272.10047.core.gz] : 10041  | [ save_file:/var/core/python3.1653598683.29.core.gz] : 42 mse
[ save_file:/var/core/bash.1653601099.288.core.gz] : 382 msec | [ save_file:/var/core/python3.1653598325.23.core.gz] : 43 mse
[ save_file:/var/crash/kdump_lock] : 473 msec                 | [ save_file:/var/crash/kdump_lock] : 29 msec
[ Warm-boot Files ] : 832 msec                                | [ Warm-boot Files ] : 39 msec
[ save_cmd:show services ] : 2191 msec                        | [ save_cmd:show services ] : 1738 msec
[ save_cmd:show reboot-cause ] : 817 msec …
```

[202205] [generate dump] Move the Core/Log collection to the End of process Execution and removed default timeout 

---

generic_config_updater/gu_common.py
generic_config_updater/patch_sorter.py
tests/generic_config_updater/gu_common_test.py
tests/generic_config_updater/patch_sorter_test.py

- Added a new supplemental YANG validator to validate UniqueLanes in `validate_config_db_config`
- Removed UniqueLanesMoveValidator as the lanes validation will be taken care of by FullConfigMoveValidator which uses `validate_config_db_config`
The benefit of this is at the beginning of `apply-patch` we make a call to `validate_config_db_config` to check if the given patch is valid or not ([code](https://github.com/Azure/sonic-utilities/blob/e6e4f8ceb9a59fb7b3767a65ffc4f017d0807832/generic_config_updater/patch_sorter.py#L1522)). Now we will fail early, instead of going for the move generation and not being able to generate a moves.
Check code.
Added unit-tests.

[GCU] Moving UniqueLanes from only validating moves, to be a supplemental YANG validator

---

utilities_common/auto_techsupport_helper.py

Signed-off-by: marvell <marvell@cpss-build3.marvell.com>
Added support for Sonic cross-compiling build. Specifically building Sonic armhf on amd64 host.
Removed addition of "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" to PATH variable when Sonic is built using cross-compilation (CROSS_BUILD_ENVIRON variable should be set to 'y' then).
Run Sonic armhf build using cross-compilation for marvell platform. Specifically run (when Sonic cross-compilation PR https://github.com/Azure/sonic-buildimage/pull/8035 is merged with the upstream):
NOJESSIE=1 NOSTRETCH=1 CROSS_BLDENV=1 make target/sonic-marvell-armhf.bin

Added support for Sonic cross-compilation build.

---

config/main.py
tests/portchannel_test.py

What I did
Added check to not allow deleting PortChannel if its member of vlan.
How I did it
Added a check in the command script.
Create a portchannel.
Add the portchannel to a vlan.
Try to delete the portchannel.
It should throw an error message.
Error: PortChannel1 has vlan Vlan100 configured, remove vlan membership to proceed

[202205] Add check to not allow deleting PO if its member of vlan

---

scripts/generate_dump

I add all bf_drivers*.log files into log folder of zipped filed created after perform the "show techsupport"
I gather all bf_drivers*.log files and make copy from syncd container into /var/log folder
I verified it on device with performing of "show techsupport"

Added bf_drivers.log to zipped dump after execution of "show techsupport"

---

config/main.py

Signed-off-by: Yucai Gu <yucgu@cisco.com>
Add cisco sub-command option under 'config platform' command
In config/main.py, check the platform type and import the cisco.py file under cisco platform code when it's cisco-8000.
Run config platform -h to see all commands. We will be able to see config platform cisco. This is only available on cisco devices.

Added cisco config platform commands

---

config/main.py
doc/Command-Reference.md
tests/config_test.py

Support load both IPv4 and IPv6 management address.
This PR requires https://github.com/Azure/sonic-buildimage/pull/11095
Iterate all mgmt intf config from device_desc.xml and apply them all.
Local UT run result (w/ sonic-buildimage change https://github.com/Azure/sonic-buildimage/pull/11095)
```
tests/config_test.py::TestConfigLoadMgmtConfig::test_config_load_mgmt_config_ipv4_only PASSED                                                                                                                  [ 15%]
tests/config_test.py::TestConfigLoadMgmtConfig::test_config_load_mgmt_config_ipv6_only PASSED                                                                                                                  [ 15%]
tests/config_test.py::TestConfigLoadMgmtConfig::test_config_load_mgmt_conf …
```

[config/load_mgmt_config] Support load IPv6 mgmt IP

---

config/main.py
doc/Command-Reference.md
tests/config_test.py

* [config/load_mgmt_config] Support load IPv6 mgmt IP
Signed-off-by: Jing Kan jika@microsoft.com
https://github.com/Azure/sonic-utilities/pull/2206

[cherry-pick][202012][config/load_mgmt_config] Support load IPv6 mgmt IP (#2206)

---

config/main.py
doc/Command-Reference.md

* [config/load_mgmt_config] Support load IPv6 mgmt IP
Signed-off-by: Jing Kan jika@microsoft.com
https://github.com/Azure/sonic-utilities/pull/2206

[cherry-pick][201911][config/load_mgmt_config] Support load IPv6 mgmt IP (#2206)

---

show/muxcable.py
tests/mock_tables/appl_db.json
tests/muxcable_test.py

Replace status in `show mux status` with APP DB `MUX_CABLE_TABLE:<port_name>`, which is written by linkmgrd and indicates linkmgrd's state transition. 
This change is required for active-active dualtor setup. In active-active setup, we care more about whether state transition happens **on ToR side**. In tests, we want to see if linkmgrd makes immediate reaction on link state changes. If we continue to use STATE DB entries, when gRPC is not available, we will get `unknow` in `show mux status`, which is not informatic and not the actual value we want to check. 
Use APP DB entries instead of STATE DB. 
Move STATE DB to column `SERVER_STATUS`. 
Unit tests with mock DB values. 
Tests on dual testbeds. 
```
PORT         STATUS    HEALTH     HWSTATUS …
```

show linkmgrd status in `show mux status`

---

config/main.py
tests/config_test.py

Load backend acl template as part of the load minigraph if the device type is a 'BackEndToRRouter' and the device is a storage device
Added unit tests to verify if the backend acl load commands are applied

Update load minigraph to load backend acl

---

config/main.py
doc/Command-Reference.md
show/main.py
tests/loopback_action_test.py
tests/mock_tables/config_db.json
utilities_common/cli.py

Add support for IP interface loopback action.
New CLI unittests were added.
```
root@sonic:~# config interface ip loopback-action Ethernet0 drop
```
```
root@sonic:~# show ip interfaces loopback-action
Interface     Action      
------------  ----------  
Ethernet232   drop
Vlan100       forward    
```

Add support for IP interface loopback action

---

show/muxcable.py
tests/mock_tables/appl_db.json
tests/mock_tables/asic_db.json
tests/muxcable_test.py

Add new CLI support to show tunnel route objects in ASIC DB.
sign-off: Jing Zhang zhangjing@microsoft.com
* Check if tunnel route object exists for **server_ipv4, server_ipv6, soc_ipv4**. If existing, print it out. 
* If not specifying port name, print all tunnel route objects. 
* Added unit tests. 
* Tested on dual testbeds: 
*  show mux tunnel-route Ethernet140
```
PORT         DEST_TYPE    DEST_ADDRESS    
-----------  -----------  ---------------  
Ethernet140  server_ipv4  192.168.0.29/32  
```
*  show mux tunnel-route --json Ethernet140
```
{
"TUNNEL_ROUTE": {
"Ethernet140": {
"server_ipv4": {
"DEST": "192.168.0.29/32"
}
}
}
}
```

[show] add new CLI to show tunnel route objects

---

config/main.py
tests/config_test.py

Backport #2236
Load backend acl template as part of the load minigraph if the device type is a 'BackEndToRRouter' and the device is a storage device
Added unit tests to verify if the backend acl load commands are applied

[202012] Update load minigraph to load backend acl

---

config/main.py
doc/Command-Reference.md
tests/config_test.py

Add a CLI option to 'config load_minigraph' to keep the device in maintenance
Added changes to execute TSA after minigraph is loaded to ensure the device is kept in maintenance. 
1. Execute 'sudo load_minigraph -t'
2.  After the new config is fully applied, execute 'TSC' to ensure the device mode is "Maintenance"
sudo config load_minigraph -h
Usage: config load_minigraph [OPTIONS]
Reconfigure based on minigraph.
Options:
-y, --yes
-n, --no_service_restart  Do not restart docker services
-?, -h, --help            Show this message and exit.
sudo config load_minigraph -h
Usage: config load_minigraph [OPTIONS]
Reconfigure based on minigraph.
Options:
-y, --yes
-n, --no_service_restart  Do not restart docker services
**-t, --traffic_shift_away  Keep device in maintenance with TSA**
-?, -h, …

Add 'traffic_shift_away' option to config load_minigraph

---

README.md

Update readme to reflect building the sonic-utilities Python wheel package inside the Bullseye slave container

Fix README to reflect sonic-utilities being built in Bullseye 

---

tests/coredump_gen_handler_test.py
utilities_common/auto_techsupport_helper.py

coredump_gen_handler script is throwing exception currently when the history table is empty.
```
root@r-lionfish-14:/home/admin# cat /tmp/coredump_gen_handler.log
File "/usr/local/bin/coredump_gen_handler.py", line 82, in <module>
main()
File "/usr/local/bin/coredump_gen_handler.py", line 77, in main
cls.handle_core_dump_creation_event()
File "/usr/local/bin/coredump_gen_handler.py", line 60, in handle_core_dump_creation_event
invoke_ts_command_rate_limited(self.db, EVENT_TYPE_CORE, {CORE_DUMP: self.core_name}, self.container)
File "/usr/local/lib/python3.9/dist-packages/utilities_common/auto_techsupport_helper.py", line 331, in invoke_ts_command_rate_limited
cooloff_passed = verify_rate_limit_intervals(db, global_cooloff, container_cooloff, container) …
```

[Auto-Techsupport] Fix the coredump_gen_handler Exception when the History table is empty

---

scripts/sysreadyshow
setup.py
show/system_health.py
sonic_package_manager/manifest.py
sonic_package_manager/service_creator/feature.py
tests/mock_tables/state_db.json
tests/sonic_package_manager/test_service_creator.py
tests/system_health_test.py

What I did
show command support for System Ready Feature Implementation .
Also sonic-package-manager support for app readiness.
"show system-health sysready-status"
"show system-health sysready-status detail"
"show system-health sysready-status brief"
How I did it
Introduce "show system-health sysready-status" click CLI with options.
Check the click CLIs introduced.

show commands for SYSTEM READY (#1851)

---

config/main.py
config/syslog.py
doc/Command-Reference.md
show/main.py
show/syslog.py
tests/syslog_input/assert_show_output.py
tests/syslog_input/config_mock.py
tests/syslog_input/syslog_cdb.json
tests/syslog_input/vrf_cdb.json
tests/syslog_test.py

**HLD:** https://github.com/sonic-net/SONiC/pull/1002
* Implemented CLI for Syslog Source IP
* N/A
* N/A
* N/A
```
root@sonic:/home/admin# show syslog
SERVER IP    SOURCE IP    PORT    VRF
-----------  -----------  ------  --------
2.2.2.2      1.1.1.1      514     default
3.3.3.3      1.1.1.1      514     mgmt
2222::2222   1111::1111   514     Vrf-Data
```

[ssip]: Add CLI

---

config/main.py
scripts/portconfig
tests/config_xcvr_test.py

Added new configuration CLI options to configure Tx power and laser frequency of ZR transceiver module
```
root@sonic:~# portconfig -p Ethernet0 -P -28.3
Setting target Tx output power to -28.3 dBm on port Ethernet0
root@sonic:~# redis-cli -n 4 hgetall "PORT|Ethernet0" 
1) "admin_status"
2) "up"
3) "alias"
4) "Ethernet1/1"
5) "index"
6) "1"
7) "lanes"
8) "1,2,3,4,5,6,7,8"
9) "laser_freq"
10) "1000"
11) "speed"
12) "400000"
13) "tx_power"
14) "-28.3"
root@sonic:~# 
```
```
root@sonic:~# portconfig -p Ethernet0 -F 191000
Setting laser frequency to 191000 GHz on port Ethernet0
root@sonic:~# redis-cli -n 4 hgetall "PORT|Ethernet0" 
1) "admin_status"
2) "up"
3) "alias"
4) "Ethernet1/1"
5) "index"
6) "1"
7) "lanes"
8) "1,2,3,4,5,6,7,8"
9) "laser_freq"
10) "191000"
11) "speed"
12) "400000"
13) …
```

portconfig option to configure Tx power and laser frequency of ZR transceiver module

---

scripts/reboot

Function stop_sonic_service() in /usr/local/bin/reboot script doesn't handle stopping the Asic syncd# on multiasic platform.  Instead, it only stops the syncd on  non-multiasic platform.  When issue command "sudo reboot",   the below message will be shown. 
```
admin@sonic:~$ sudo reboot
Error: No such container: syncd
```
Fixes https://github.com/Azure/sonic-buildimage/issues/11377
Add code the stop_sonic_services() to check and get NUM_ASIC. If it is multiasic, looping all asics  and call the syncd_request_shutdown for each asic. 
Issue the "sudo reboot" on the multiasic platform, the error message "Error: No such container: syncd"  should not be shown.

[MultiAsic] sudo reboot command doesn't gracefully stop Asic syncd# on multiasic platform

---

tests/db_migrator_input/config_db/qos_map_table_expected.json
tests/db_migrator_input/config_db/qos_map_table_input.json

This PR is to fix the input and output for testing the migration of `pfcwd_sw_enable`.
Before this change, 
```
resulting_table = dbmgtr.configDB.get_table('PORT_QOS_MAP')
expected_table = expected_db.cfgdb.get_table('PORT_QOS_MAP')
```
`resulting_table` and `expected_table` are always empty `{}`. So the test case can always pass.
Fix the input and output for testing the migration of `pfcwd_sw_enable`.
Run UT for `db_migrator` after update.
```
collected 75 items                                                                                                                                                                                    
tests/db_migrator_test.py ........................................................................... …
```

[202012] Fix test for `pfcwd_sw_enable` in `db_migrator_test`

---

tests/db_migrator_input/config_db/qos_map_table_expected.json
tests/db_migrator_input/config_db/qos_map_table_input.json

This PR is to fix the input and output for testing the migration of `pfcwd_sw_enable`.
Before this change, 
```
resulting_table = dbmgtr.configDB.get_table('PORT_QOS_MAP')
expected_table = expected_db.cfgdb.get_table('PORT_QOS_MAP')
```
`resulting_table` and `expected_table` are always empty `{}`. So the test case can always pass.
Fix the input and output for testing the migration of `pfcwd_sw_enable`.
Run UT for `db_migrator` after update.
```
collected 75 items                                                                                                                                                                                    
tests/db_migrator_test.py ........................................................................... …
```

Fix test for pfcwd_sw_enable in db_migrator_test

---

scripts/fast-reboot

Reverts Azure/sonic-utilities#2161
**What I did**
Revert a revert. This must be merged togather with https://github.com/Azure/sonic-buildimage/pull/10510
How I did it
Revert it
Run build

Revert "Revert "[scripts/fast-reboot] Shutdown remaining containers through systemd (#2133)""

---

scripts/watermarkstat

commit 409da5ff87cb8864cd41c7b23e62ad4849ff5037
Author: Shlomi Bitton <shlomibi@nvidia.com>
Date:   Tue Jun 14 16:17:20 2022 +0000
Fix watermarkstat CLI script.
Since PG/Queue counters are created only if they are configured in the switch, it is not enough to relay only on the first entry in the DB.
We need to go over all configured counters, check what is the max configured, and build the table accordingly.
Propagating https://github.com/Azure/sonic-utilities/pull/2220 with resolved review comments
Since PG counters are created only if they are configured in the switch, it is not enough to relay only on the first entry in the DB when building the output table of watermarkstat script.
We …

[watermarkstat] Fix CLI script for unconfigured PG counters

---

setup.py

The script was added in the PR https://github.com/sonic-net/sonic-utilities/pull/2277 which did not add this script to the setup.py script.
Added the new script to `setup.py`

[202012] Add db_migrator_constants.py script to setup.py

---

scripts/db_migrator.py
scripts/mellanox_buffer_migrator.py
tests/db_migrator_input/config_db/qos_map_table_expected.json
tests/db_migrator_input/config_db/qos_map_table_global_expected.json
tests/db_migrator_input/config_db/qos_map_table_global_input.json
tests/db_migrator_input/config_db/qos_map_table_input.json
tests/db_migrator_input/config_db/reclaiming-buffer-warmreboot-expected.json
tests/db_migrator_test.py

This PR is to fix the db_migrator version for table `PORT_QOS_MAP|global`.
Because the migrator version for table `PORT_QOS_MAP|global` is `version_2_0_0` in `202012` branch (PR #2215), we should use the same version in `master` and `202205` branch to be compatible.
Change the migrator version for table `PORT_QOS_MAP|global` from `version_3_0_5` to `version_2_0_0` .
Verified by UT.
```
collected 78 items                                                                                                                                                                                    
tests/db_migrator_test.py ..............................................................................                                                                                        [100%] …
```

Fix version in db_migrator  for `PORT_QOS_MAP|global`

---

tests/config_override_input/empty_table_removal.json
tests/config_override_test.py

Add one override-config-table testcase to verify empty table removal. 
Add the testcase to verify the removal.
Unit test.

Add override testcase to verify removal

---

tests/sfp_test.py
utilities_common/platform_sfputil_helper.py

Method is_rj45_port references sonic_platform which has not been implemented on vs platform
However, the method is referenced by `show interface status` which is widely used in kvm test in azure pipeline checkers
`True` is returned in `is_rj45_port` if `sonic_platform` can not be imported
Run vs tests

Fix the issue that sonic_platform is not installed on vs image

---

crm/main.py
tests/crm_test.py

add checking for range for CRM interval
add attribute **click.IntRange(1, 9999)** and UT to verify it (according to [CRM HLD](https://github.com/sonic-net/SONiC/blob/master/doc/crm/Critical-Resource-Monitoring-High-Level-Design.md#211-crm-table))
1) run UT
2) manual testing: `crm config polling interval 100000000` (receive error)
```
crm config polling interval 4566466
```
```
crm config polling interval --help
Usage: crm config polling interval [OPTIONS] INTERVAL
CRM polling interval configuration
Options:
--help  Show this message and exit.
```
```
crm config polling interval 4566466
Usage: crm config polling interval [OPTIONS] INTERVAL
Try "crm config polling interval --help" for help.
Error: Invalid value for "INTERVAL": 4566466 is not …
```

[crm] add CLI validation for CRM polling interval range

---

sonic_installer/common.py
sonic_installer/main.py
tests/installer_docker_test.py

Fix issues:
1. upgrade-docker shall not check STATE DB for those container which do not support warm mode
2. rollback-docker sometimes cannot really rollback the container because it cannot get the correct docker image tag
1. for containers do not support warm mode, ignore STATE_DB check
2. use another command to get docker image tag
Manual test.
UT is not created for this change because there are many docker command running for these two CLIs, thus:
1. Mock so many docker command causes the test case very tricky. The case would be even more complicated than the CLIs.
2. UT cannot really test the command in case of so many docker command
Instead, a new sonic-mgmt test case is on the way to cover these two CLI. Will create PR for the sonic-mgmt new test case later.

Fix issues for sonic_installer upgrade-docker and sonic_installer rollback-docker

---

generic_config_updater/change_applier.py
generic_config_updater/generic_updater.py
tests/generic_config_updater/generic_updater_test.py

Modifying PORT `admin_status` will result in backend service changing the running config. e.g. buffermgrd will modify `BUFFER_PG|EthernetXX|3-4` when one of the EthernetXX in `PORT` table admin down.
This PR is to skip comparison of config that is possiblly being modified by backend service
Fixes https://github.com/sonic-net/sonic-buildimage/issues/11576
Add a workaround to only compare config without backend service impact.
Manual test on specific platform and check operation success.

Fix GCU bug when backend service modifying config

---

config/muxcable.py
tests/muxcable_test.py

Signed-off-by: vaibhav-dahiya [vdahiya@microsoft.com](mailto:vdahiya@microsoft.com)
This PR provides a capability to sonic-utilities CLI to enable/disable telemetry for ycabled.
Basically there is a periodic loop for ycabled which posts telemetry data for that configured interval of time(currently 60 sec). This PR diables this data posting, and does not call platform API calls for ycable.
This PR is required for the initiative of getting some failover/switchover not get interfered because of sonic-telemetry API calls.
The CLI for enabling/disabling telemetry is
```config muxcable telemetry enable/disable```
Dependent on https://github.com/sonic-net/sonic-platform-daemons/pull/279 and submodule update

[config][muxcable] add support to enable/disable ycable telemetry

---

sonic_installer/bootloader/aboot.py
sonic_installer/bootloader/bootloader.py
sonic_installer/bootloader/grub.py
sonic_installer/bootloader/uboot.py
sonic_installer/main.py
tests/installer_bootloader_aboot_test.py
tests/installer_bootloader_grub_test.py
tests/installer_bootloader_input/host/grub/grub.cfg
tests/installer_bootloader_uboot_test.py
tests/test_sonic_installer.py

Cherry-pick https://github.com/sonic-net/sonic-utilities/pull/2154
Support to enable fips for the command sonic_installer
See https://github.com/sonic-net/SONiC/pull/997
sonic-installer set-fips <image> [--enable-fips|--disable-fips]
sonic-installer get-fips <image>

Support to enable fips for the command sonic_installer (#2154)

---

config/main.py
tests/config_test.py

To be able to configure the management interface and hostname standalone by changing database config at runtime.
From the CLI perspective fo view, the following behavior is the same. But now you have two ways of configuring it: CLI, directly through the database.
Moved configuration part of the interface and hostname to "hostcfgd".
* Built an image
* Flash it to the switch
* Run CLI commands
```
sudo config interface ip add eth0 10.210.25.127/22 10.210.24.1
ip address show eth0
sudo config interface ip remove eth0 10.210.25.127/22
ip address show eth0
ip address show mgmt
sudo config vrf add mgmt
ip address show mgmt
sudo config vrf del mgmt
ip address show mgmt
admin@r-anaconda-27:~$ sudo config hostname bla
admin@bla:~$
```
Description for the changelog
* Moved management interface …

[CLI] Move hostname, mgmt interface/vrf config to hostcfgd

---

config/main.py
tests/ip_config_input/patch_ipv6.test
tests/ip_config_test.py

Fixes https://github.com/sonic-net/sonic-buildimage/issues/11622
Convert IPv6 addresses to lowercase in apply-patch for remove op
python regex on 'remove' op in JSON patch input file
manual test of created bug

Convert IPv6 addresses to lowercase in apply-patch

---

tests/dump_tests/dump_state_test.py

[202205] Fix test failure in dump table test

---

tests/ip_config_test.py
tests/mock_tables/dbconnector.py

Fix VRF bind/unbind UT failed issue.
Mock DBInterface.close() method.
Add new UT.
Pass all UT.

Fix vrf UT failed issue

---

scripts/decode-syseeprom
tests/decode_syseeprom_test.py

Set use_db after support_eeprom_db is determined. The issue was affecting platform Arista platforms, where db is not used for syseeprom.
Verified on dut by running "show platform syseeprom" and "decode-syseeprom -d"

[decode-syseeprom] Fix setting use_db based on support_eeprom_db

---

scripts/route_check.py
tests/route_check_test.py

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
Add capability to check routes with VRF
All routes in VRF have a specific prefix in name.
**_Route table when we have VRF:_**
```
admin@igk-5-dut:~$ redis-cli -n 0 keys "ROUTE_TABLE*" 
1) "ROUTE_TABLE:Vrf2:20c0:cb50:0:80::/64"
2) "ROUTE_TABLE:Vrf2:192.211.48.0/25"
3) "ROUTE_TABLE:Vrf1:192.246.8.128/25"
4) "ROUTE_TABLE:Vrf1:192.222.8.0/25"
5) "ROUTE_TABLE:Vrf2:192.246.64.0/25"
.......
```
**_Route table without VRF:_**
```
admin@cab18-2-dut:~$ redis-cli -n 0 keys "ROUTE_TABLE*"
1) "ROUTE_TABLE:192.168.0.0/21"
2) "ROUTE_TABLE:10.1.0.32"
3) "ROUTE_TABLE:fc02:1000::/64"
4) "ROUTE_TABLE:fe80::/64"
5) "ROUTE_TABLE:fc00:1::32"
.......
```
Remove **_Vrf_** prefix from route. Without Vrf, we can compare routes from APP and ASIC DB.
Run next …

Fix bug with checking VRF's routes in route_check.py 

---

utilities_common/platform_sfputil_helper.py

Fix issue #2312. On some platforms, `logical_port_name_to_physical_port_list` doesn't return a valid port name list, which causes exception in `is_rj45_port`.
Fix it by catching the exception and treating it as a non-RJ45 port.

Fix issue: exception in is_rj45_port in multi ASIC env

---

utilities_common/platform_sfputil_helper.py

Followup fixes : https://github.com/sonic-net/sonic-utilities/issues/2312

Fix issue: port_type is referenced before initialized

---

doc/Command-Reference.md

Updated VRF unbind command to remove additional `<vrf_name>` argument.
- N/A
- The argument `<vrf_name>` is unrecognized for `unbind` command.
- `--help` for VRF unbind shows its `USAGE` without the `<vrf_name>` argument.
- N/A
- N/A

Update vrf unbind command in Command-References.md

---

sonic-utilities-data/templates/service_mgmt.sh.j2

Signed-off-by: Ze Gan <ganze718@gmail.com>
Fix an obvious script typo in service_mgmt.sh.j2 to fetch the MULTI_INST_DEPENDENT 
Fix typo
Check it manually.

[service_mgmt]: Fix fetch MULTI_INST_DEPENDENT bug in service_mgmt.sh.j2

---

tests/sfp_test.py
utilities_common/platform_sfputil_helper.py

Handle the cases that a port is not a front-panel port in is_rj45_port
Add mock test to cover the logic

Handle non-front-panel ports in is_rj45_port

---

config/main.py
tests/ip_config_test.py
tests/static_routes_test.py

Added CLI checks to verify if Vrf is created and valid when used in interface bind and static route commands
Check for presence of Vrf in VRF table or in case if it is mgmt vrf, verify if mgmt vrf is enabled/

[VRF]Adding CLI checks to ensure Vrf is valid in interface bind and static route commands

---

config/main.py
scripts/intfutil
tests/intfutil_test.py
tests/ip_config_test.py
tests/mock_tables/appl_db.json
tests/mock_tables/config_db.json
tests/show_vrf_test.py
tests/subintf_test.py
tests/vrf_input/config_db.json

This commit addresses below issues: 
1. Fixes #10802  : https://github.com/Azure/sonic-buildimage/issues/10802 
2. Fixes #10878 : https://github.com/Azure/sonic-buildimage/issues/10878

Subinterface vrf bind issue fix

---

acl_loader/main.py
tests/acl_input/incremental_1.json
tests/acl_input/incremental_2.json
tests/acl_loader_test.py

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>
When run try to add a new rule for existing rule table with this command `acl-loader update incremental`, it will throw a traceback like this:
```
admin@vlab-03:~$ sudo acl-loader update incremental /home/admin/external_acl.json 
File "/usr/local/bin/acl-loader", line 8, in <module>
File …
```

Replace cmp in acl_loader with operator.eq

---

scripts/route_check.py
scripts/route_check_test.sh
tests/config_test.py
tests/mock_tables/config_db.json
tests/route_check_test.py

When checking for route entry mismatches, ignore mismatched routes where an APPL_DB neighbor entry with a zero MAC is present. 
These routes are introduced by this change in SWSS and are expected: https://github.com/sonic-net/sonic-swss/pull/2137
Run the updated `route_check_test.sh` script

[route_check]: Ignore standalone tunnel routes

---

config/plugins/sonic-passwh_yang.py
show/plugins/sonic-passwh_yang.py
tests/passw_hardening_input/assert_show_output.py
tests/passw_hardening_input/default_config_db.json
tests/passw_hardening_test.py

Add Password Hardening CLI
created the CLI by using YANG model generator, the YANG model can be found in the password hardening HLD https://github.com/Azure/SONiC/blob/master/doc/passw_hardening/hld_password_hardening.md#TestPlan
and also in sonic-buildimage will be merged in the path: src/sonic-yang-models/yang-models/sonic-passwh.yang
Manually:
you can use configurations command like"config passw-hardening policies <policy> <value>"  or 
"show passw-hardening policies" (more examples in the HLD.)
Auto:
1.There are unitest of each policy including good & bad flow in this commit, that should pass.
2.There are tests in sonic-mgmt repo in the path: sonic-mgmt/tests/passw_hardening/
the test are end to end test and the are testing the config/show CLI commands as well.
(new feature)
``` …
```

Add Password hardening CLI support

---

config/main.py
tests/config_override_input/final_config_yang_failure.json
tests/config_override_input/golden_input_yang_failure.json
tests/config_override_input/running_config_yang_failure.json
tests/config_override_test.py

Add Yang verification for config override-config-table
Make 3 step verification: running config, golden input, final config
Run unit test.

Add verification for override

---

generic_config_updater/change_applier.py
tests/generic_config_updater/change_applier_test.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/11912
Add the missing 'remove_backend_tables_from_config' in dry run.
Run unit test and manual test locally.
Previous:
```
admin@vlab-01:~$ sudo config apply-patch t2.json -d
** DRY RUN EXECUTION **
Patch Applier: Patch: [{"op": "remove", "path": "/VLAN/Vlan250"}]
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config does not have empty tables, since they do not show up in ConfigDb.
Patch Applier: Sorting patch updates.
Patch Applier: The patch was sorted into 1 change:
Patch Applier:   * [{"op": "remove", "path": "/VLAN/Vlan250"}]
Patch Applier: Applying 1 change in order:
Patch Applier: …
```

[GCU] Fix missing backend in dry run

---

scripts/fast-reboot

During fast-reboot there were warnings for few services
sudo fast-reboot
Warning: The unit file, source configuration file or drop-ins of mux.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Dumping conntrack entries failed
Warning: The unit file, source configuration file or drop-ins of nat.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of sflow.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: Stopping docker.service, but it can still be activated by:
docker.socket
Watchdog armed for 180 seconds
This is due to the fact that the services are masked and trying to stop them will throw warning
systemctl is-enabled sflow.service
masked
systemctl stop …

[fast-reboot]Avoid stopping masked services during fast-reboot

---

doc/Command-Reference.md

Signed-off-by: kannankvs <kannan_kvs@dell.com>
This is in continuation to the PR2134 As the mentioned PR had incorrect commits, closed it and raised this PR. The comments given in previous PR is mentioned below.
**@wen587 Hi, need to mention that GCU is experimental in 202111 and may not function well.
GCU is fully supporte in 202205.
<KVSK> Addressed** 
**@wen587 Hi, it seems the total documentation was removed fully and then added back, which make reviewer cannot check the file diff from here https://github.com/sonic-net/sonic-utilities/pull/2314/files.
Can we keep the original format and just add what is missing? That should be easier to compare the diff from the website.
<KVSK> While updating the CLI file for 202111 branch, the file diff is seen for whole of the file. While the merge …

Added missing commands for release 202111 in the command reference

---

counterpoll/main.py
tests/counterpoll_test.py
tests/mock_tables/config_db.json

Fixing counterpoll show for tunnel and acl stats.
Corrected the copy paste errors.
Updated test config and UT to verify it.

[counterpoll]Fixing counterpoll show for tunnel and acl stats

---

scripts/generate_dump

Added error message when saisdkdump fails and cont to gather the rest. This is done to provide more readable information to the user when it cannot be avaialble (syncd for example is not running, during restart, etc).
Checked error code and print log
Simulate saisdkdump error and verify the console output.

[generate dump]Added error message when saisdkdump fails

---

scripts/disk_check.py

Added event_publish for read-only state
Added API
Run this script w/o sudo, which will publish error, as the script can't do write to /etc or /home.
Look for event published and corresponding syslog message.
You may use events_tool or gnmi_cli to capture the event.
The events tool can be obtained from eventd docker /usr/sbin/
Sample message:
"`Aug 18 18:16:02.451626 sonic-switch INFO disk_check.py: :- publish: EVENT_PUBLISHED: {"sonic-events-host:event-disk":{"fail_type":"read_only","timestamp":"2022-08-18T18:16:02.451089Z"}}`"

disk_check: Publish event  for RO state

---

clear/main.py
counterpoll/main.py
scripts/tunnelstat
setup.py
show/vxlan.py
tests/counterpoll_test.py
tests/mock_tables/config_db.json
tests/mock_tables/counters_db.json
tests/tunnelstat_test.py

Backport of https://github.com/sonic-net/sonic-utilities/pull/1748
Implemented Vxlan counters and rates. Defined show commands for counters and rates similar to port and tunnel rates.
Implemented tunnelstat utility and used it in show vxlan counters command.
Using unit tests in CLI
```
show vxlan counters
IFACE    RX_PKTS    RX_BYTES    RX_PPS    TX_PKTS    TX_BYTES    TX_PPS
---------  ---------  ----------  --------  ---------  ----------  --------
vtep_1336      2,359         N/A    0.99/s    205,972         N/A   86.93/s
show vxlan counters  vtep_1336
vtep_1336
---------
RX:
13 packets
N/A bytes
TX:
1,164 packets
N/A bytes
```

[202012][VxLAN]VxLAN Tunnel Counters and Rates implementation

---

config/main.py
tests/intfutil_test.py
tests/ip_config_test.py
tests/loopback_action_test.py
tests/mock_tables/appl_db.json
tests/mock_tables/config_db.json
tests/portchannel_test.py
tests/show_vrf_test.py
tests/static_routes_test.py
tests/subintf_test.py
tests/vrf_input/config_db.json

Added additional checks in subinterface and portchannel commands so they don't conflict. Without the checks, a subinterface could be created on a portchannel member and vice versa which will lead to SAI failure followed by orchagent crash.
Added checks in relevant config functions.

[subinterface]Added additional checks in portchannel and subinterface commands

---

scripts/fast-reboot

This PR is similar to https://github.com/sonic-net/sonic-utilities/pull/2286 - it is being raised as a different PR following discussion with Ying Xie.
This PR should be merged together with the sonic-sairedis PR (https://github.com/sonic-net/sonic-sairedis/pull/1121) and sonic-buildimage PR (https://github.com/sonic-net/sonic-buildimage/pull/12026).
Improve fast-reboot flow.
Using warm-reboot infrastructure.
Clear all routes except of default routes for faster reconciliation time.
Community fast-reboot test, manual testing.

[202205] Use warm-boot infrastructure for fast-boot

---

config/main.py
tests/intfutil_test.py
tests/ip_config_test.py
tests/loopback_action_test.py
tests/mock_tables/appl_db.json
tests/mock_tables/config_db.json
tests/portchannel_test.py
tests/show_vrf_test.py
tests/static_routes_test.py
tests/subintf_test.py
tests/vrf_input/config_db.json

Backport of https://github.com/sonic-net/sonic-utilities/pull/2345
*Added additional checks in subinterface and portchannel commands so they don't conflict. Without the checks, a subinterface could be created on a portchannel member and vice versa which will lead to SAI failure followed by orchagent crash.
Added additional checks in subinterface and portchannel commands so they don't conflict. Without the checks, a subinterface could be created on a portchannel member and vice versa which will lead to SAI failure followed by orchagent crash.
Added checks in relevant config functions.

[202205][subinterface]Added additional checks in portchannel and subinterface commands (#2345)

---

config/main.py
tests/static_routes_test.py

Fix for https://github.com/sonic-net/sonic-buildimage/issues/11803
While adding static routes, if VRF name is not present, use `default` VRF
In the `add` and `del` route implementations, I check if VRF name is present or not.
Unittests have been updated

Use 'default' VRF when VRF name is not provided

---

pfcwd/main.py

Fix pfcwd connect DB with exception issue: https://github.com/Azure/sonic-buildimage/issues/11269
pfcwd implicit depends on InterfaceAliasConverter() to initialize DB config, however following PR change InterfaceAliasConverter() behavior to lazy initialize, then pfcwd failed when try connect to DB without initialize DB config:
https://github.com/Azure/sonic-utilities/pull/2183
Load  DB config in pfcwd.
Pass all UT.

Fix DBConfig not initialize issue in pfcwd (#2238)

---

scripts/vnet_route_check.py
tests/vnet_route_check_test.py

Modified Vnet_route_check to ignore the Vxlan tunnel routes which uses default VRF.
Updated the vnet_route_check script to handle the vxlan tunnel routes.
By checking the scope of the tunnel route, if it is default then it is treated in a different way. Tunnel routes coming from App_db are compared with ASIC_db default_VRF routes and their presence is verified.
For routes coming from ASIC_db with default_VRF, the comparison is not done with the routes form App_db as ASIC_DB carries all other the routes.
For normal vnet routes, the functionality of the script is unaffected. 
run the script after adding a vxlan tunnel.

Vnet_route_check Vxlan tunnel route update.

---

utilities_common/platform_sfputil_helper.py

Fix typo in `platform_sfputil_helper.is_rj45_port`.

Fix typo in platform_sfputil_helper.is_rj45_port

---

scripts/fast-reboot

Fixed issue when cache wasn't generated and warm reboot command fails.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/11914
Added a check for cache existence
Run warm-reboot

[warm-reboot] fix warm-reboot when /tmp/cache is missing

---

utilities_common/platform_sfputil_helper.py

This is to backport https://github.com/sonic-net/sonic-utilities/pull/2374
Fix typo in `platform_sfputil_helper.is_rj45_port`.

[202205] Fix typo in platform_sfputil_helper.is_rj45_port (#2374)

---

scripts/fast-reboot

This PR should be merged together with the sonic-sairedis PR (https://github.com/sonic-net/sonic-sairedis/pull/1100) and sonic-buildimage PR (https://github.com/sonic-net/sonic-buildimage/pull/11594).
Improve fast-reboot flow.
Using warm-reboot infrastructure.
Clear all routes except of default routes for faster reconciliation time.
Community fast-reboot test, manual testing.

[fastboot] fastboot enhancement: Use warm-boot infrastructure for fast-boot

---

config/main.py
tests/config_test.py

Add an option for load_minigraph to specify golden path
Add an option for load_minigraph
Unit test
sudo config load_minigraph -h
Usage: config load_minigraph [OPTIONS]
Reconfigure based on minigraph.
Options:
-y, --yes
-n, --no_service_restart Do not restart docker services
-t, --traffic_shift_away Keep device in maintenance with TSA
-?, -h, --help Show this message and exit.
sudo config load_minigraph -h
Usage: config load_minigraph [OPTIONS]
Reconfigure based on minigraph.
Options:
-y, --yes
-n, --no_service_restart Do not restart docker services
-t, --traffic_shift_away Keep device in maintenance with TSA
**-p, --golden_config_path TEXT  specify Golden Config path**
-?, -h, --help Show this message and exit.

[minigraph] add option to specify golden path in load_minigraph

---

tests/ipv6_link_local_test.py
tests/mock_tables/config_db.json
utilities_common/cli.py

Modify RIF check to include interfaces with link-local mode. The existing RIF check will only work if the key is tuple which is applicable only when interface has IP address. However if the interface has IPv6 only enable the key is of type string.
So in common if the interface is either IPv6 enabled or ip configured it has both string and tuple keys as illustrated below. Hence modified the if check to check directly for interface name which will match the key of type string
127.0.0.1:6379[4]> keys INTERFACE|Ethernet48
"INTERFACE|Ethernet48"
"INTERFACE|Ethernet48|1.1.1.1/16"
127.0.0.1:6379[4]> keys INTERFACE|Ethernet0
"INTERFACE|Ethernet0"
Modified the logic to check if port has Router interface

[link-local]Modify RIF check to include link-local enabled interfaces

---

config/main.py
config/validated_config_db_connector.py
config/vlan.py
generic_config_updater/generic_updater.py
generic_config_updater/gu_common.py
tests/config_test.py
tests/portchannel_test.py
tests/validated_config_db_connector_test.py

Added YANG validation to add/remove portchannel using GCU apply patch

YANG validation for ConfigDB Updates: portchannel add/remove, loopback interface, VLAN YANG validation Using GCU

---

show/main.py
tests/show_vrf_test.py

Fix display disorder problem of show vrf 
The problem is as follows, the vlan interfaces are not sorted in the interface column：
```
root@sonic:/home/admin# show vrf
VRF             Interfaces
--------------  ------------
Vrf1            Vlan30
Vlan399
Vlan40
Vrf2            Vlan41
Vlan422
Vlan50
Vlan599
Vlan60
```
Sort the interface column with natsorted
use “show vrf”
```
root@sonic:/home/admin# show vrf
VRF             Interfaces
--------------  ------------
Vrf1            Vlan30
Vlan399
Vlan40
Vrf2            Vlan41
Vlan422
Vlan50
Vlan599
Vlan60
```
```
root@sonic:/home/admin# show vrf
VRF             Interfaces
--------------  ------------
Vrf1            Vlan30
Vlan40
Vlan399
Vrf2            Vlan41
Vlan50
Vlan60
Vlan422
Vlan599
```

Fix display disorder problem of show vrf 

---

doc/Command-Reference.md

Updated "config feature" section with "--block" option
Added missing documentation on "config feature" command
N/A

[doc] update "config feature" section with "--block" option

---

tests/installer_dependency_test.py

Add new test cases to test sonic-installer does not depends on database docker.
Add new test cases to test sonic-installer does not depends on database docker.
Add new test case to cover user scenarios.
Run new UT make sure they are all pass.
Make sure all current UT not break during merge validation.
N/A

Add UT to check sonic installer does not depend on database

---

config/vxlan.py
tests/vnet_input/config_db.json
tests/vxlan_test.py

Fix for https://github.com/sonic-net/sonic-buildimage/issues/12063
Check for VNET references for vxlan before deleting vxlan object
Check VNET table and throw error if vxlan is referenced

[VxLAN]Fix Vxlan delete command to throw error when there are references
