- sonic_installer/main.py
- tests/test_sonic_installer.py
Backport of https://github.com/sonic-net/sonic-utilities/pull/2179
I attempted to fix an issue that happens on multi-asic devices after new SONiC image installation. The issue is caused by overriding docker0 bridge configuration as well as installing iptables rules by dockerd started in chroot environment.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/10135
I start dockerd in chroot using same parameters the host dockerd is started with.
Run VS multi-asic device.
Install a new image on it.
Verify "show version", "show interface status"
> [202205][sonic-installer] use host docker startup arguments when running dockerd in chroot (#2179)

- config/main.py
- tests/config_test.py
Change the behavior that load_minigraph will consume golden config by default.
New behavior:
`config load_minigraph`: No longer consume golden config.
`config load_minigraph --golden_config`: Consume default golden config. /etc/sonic/golden_config_db.json
`config load_minigraph --golden_config FilePath`: Consume golden config with FilePath
Make golden_config click.Option() and add an argument for golden config path.
UT test.
sudo config load_minigraph -h
Usage: config load_minigraph [OPTIONS]
Reconfigure based on minigraph.
Options:
-y, --yes
-n, --no_service_restart Do not restart docker services
-t, --traffic_shift_away Keep device in maintenance with TSA
-p, --golden_config_path TEXT specify Golden Config path
-?, -h, --help Show this message and exit.
admin@vlab-01:~$ sudo config …
> [minigraph] new workflow for golden path

- doc/Command-Reference.md
- show/vnet.py
- tests/mock_tables/appl_db.json
- tests/mock_tables/state_db.json
- tests/show_bfd_test.py
- tests/show_vnet_vxlan_cli_test.py
Clone for 202012.
Orignal PR https://github.com/sonic-net/sonic-utilities/pull/2342
> [show] vnet endpoint [ip/ipv6] command [202012]

- config/main.py
Add YANG validation using GCU for writes to MGMT_INTERFACE, PORTCHANNEL_MEMBER in ConfigDB
Using same method as https://github.com/sonic-net/sonic-utilities/pull/2190/files, extend to MGMT_INTERFACE and PORTCHANNEL_MEMBER use cases
Verified testing CLI on virtual switch
> YANG validation for ConfigDB Updates: MGMT_INTERFACE, PORTCHANNEL_MEMBER use cases

- config/muxcable.py
Add support for `config mux mode detach`. Stemming from https://github.com/sonic-net/sonic-linkmgrd/pull/79
sign-off: Jing Zhang zhangjing@microsoft.com
Add `detach` to the choice list. 
* Existing unit test. 
* Tested on DUT
```
admin@svcstr-7050-acs-1:~$ sudo config mux mode detach Ethernet12
port        state
----------  -------
Ethernet12  OK
```
After config change, shutdown peer's link, self side got peer link prober unknown event but didn't toggle peer's mux state as it's in `Detached` mode. 
```
Oct  5 23:47:03.510501 svcstr-7050-acs-1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:524 handlePeerStateChange: Ethernet12: Received peer link prober event, new state: PeerUnknown
```
A `auto` mode interface would toggle: 
```
Oct  5 23:46:21.472932 …
```
> [muxcable][config] add CLI support for mux mode detach

- config/main.py
- tests/config_int_mtu_test.py
What I did
Filter port invalid MTU configuration
How I did it
Adjust the MTU value to the range of [68,9216]
Use "config interface mtu Ethernet1 40" command to configure the port MTU. The following error will occur in SWSS.
```
Sep 16 14:53:39.051202 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet1 MTU to 40
Sep 16 14:53:39.052217 sonic INFO swss#/supervisord: portmgrd Error: mtu less than device minimum.
Sep 16 14:53:39.052600 sonic ERR swss#portmgrd: :- main: Runtime error: /sbin/ip link set dev "Ethernet1" mtu "40" : 
Sep 16 14:53:39.325117 sonic INFO swss#supervisord 2022-09-16 06:53:39,324 INFO exited: portmgrd (exit status 255; not expected)
Sep 16 14:53:40.339256 sonic INFO swss#/supervisor-proc-exit-listener: Process 'portmgrd' exited unexpectedly. …
```
> Filter port invalid MTU configuration

- tests/coredump_gen_handler_test.py
- utilities_common/auto_techsupport_helper.py
BACKPORT OF: https://github.com/sonic-net/sonic-utilities/pull/2265
coredump_gen_handler script is throwing exception currently when the history table is empty.
```
root@r-lionfish-14:/home/admin# cat /tmp/coredump_gen_handler.log
File "/usr/local/bin/coredump_gen_handler.py", line 82, in <module>
main()
File "/usr/local/bin/coredump_gen_handler.py", line 77, in main
cls.handle_core_dump_creation_event()
File "/usr/local/bin/coredump_gen_handler.py", line 60, in handle_core_dump_creation_event
invoke_ts_command_rate_limited(self.db, EVENT_TYPE_CORE, {CORE_DUMP: self.core_name}, self.container)
File "/usr/local/lib/python3.9/dist-packages/utilities_common/auto_techsupport_helper.py", line 331, in invoke_ts_command_rate_limited
cooloff_passed = …
```
> [202205][Auto-Techsupport] Fix the coredump_gen_handler Exception when the History table is empty (#2265)

- sfputil/main.py
- tests/sfputil_test.py
**What I did**
Added a subcommand to display the hexdump of transceiver EEPROM page specified by the user.
"sfputil show eeprom-hexdump -p <port_name> -n <page_number>" has been added for this purpose. Specifying the port name is mandatory. If page number is not mentioned, page 0 content will be displayed by default.
For SFF-8472 based transceivers, following is the behavior
The entire 256 byte region of A0h will displayed. In addition to this, the lower 128 byte of A2h will be displayed.
The upper 128 bytes of A2h will be displayed based on the page number specified by the user. If no page number is specified, page 0 relevant data will be shown.
For non SFF-8472 based transceiver, following is the behavior
Lower page 0h is always displayed and the upper page is displayed based on the …
> Add a subcommand to display a hexdump of transceiver EEPROM page

- doc/Command-Reference.md
Update CLI examples to reflect recent changes of adding these two config CLIs.
config interface transceiver frequency
config interface transceiver tx-power
> Include configuring laser frequency and tx power

- scripts/generate_dump
Signed-off-by: Geert Vlaemynck <gvlaemyn@cisco.com>
Added cisco-8000 specific platform information to "show techsupport" tarfile
Added collect_cisco_8000 function to scripts/generate_dump which filters out the wanted files from /usr/share/sonic/device/${platform} and saves them in the techsupport tarfile under sai subdirectory
Run "show techsupport" and grep sai in the generated techsupport tarfile
> [generate_dump]: Enhance show techsupport for cisco-8000 platform

- config/vlan.py
- tests/vlan_test.py
Backporting https://github.com/sonic-net/sonic-utilities/pull/2388 to 202205
check for vxlan mapping before removing vlan
added a check similar to vlan member above
attempt to delete a vlan that has a vxlan mapping in place
> [202205] check for vxlan mapping before removing vlan 

- config/validated_config_db_connector.py
- tests/config_test.py
- tests/portchannel_test.py
- tests/validated_config_db_connector_test.py
In ValidatedConfigDBConnector decorator code, create a new instance of ConfigDBConnector so that original instance is not modified.
Tested locally - ensure that GCU is used when YANG Config Validation is enabled, and ADHOC_VALIDATION is False
> YANG Validation for ConfigDB Updates: Fix Decorator Bug

- sonic_package_manager/service_creator/feature.py
- tests/sonic_package_manager/test_service_creator.py
With this change, when a new app-extension is installed, available_mem_threshold config is added to `AUTO_TECHSUPPORT_FEATURE|<feature_name>` key 
```
vkarri@d7a060369aba:/sonic/src/sonic-utilities$ pytest-3 tests/sonic_package_manager/test_service_creator.py 
=============================================================== test session starts ===============================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-utilities/tests, configfile: pytest.ini
plugins: pyfakefs-4.7.0, cov-2.10.1
collected 13 items …
```
> [app_ext] [auto-ts] Add available_mem_threshold option

- show/muxcable.py
- tests/mock_tables/state_db.json
- tests/muxcable_test.py
This PR adds support for show mux firmware version all as well as adds a click confirmation to process event-log
This PR also fixes a permission issue for executing the show mux packetloss command.
$show mux firmware version all
```
{
"Ethernet116": {
"version_nic_active": "1.0MV",
"version_nic_inactive": "0.9MS",
"version_nic_next": "1.0MV",
"version_peer_active": "1.0MV",
"version_peer_inactive": "0.9MS",
"version_peer_next": "1.0MV",
"version_self_active": "1.0MV",
"version_self_inactive": "0.9MS",
"version_self_next": "1.0MV"
}
}
{
"Ethernet120": {
"version_nic_active": "1.0MV",
"version_nic_inactive": "0.9MS",
"version_nic_next": "1.0MV",
"version_peer_active": "1.0MV",
"version_peer_inactive": "0.9MS",
"version_peer_next": …
```
> [show][muxcable] add support for show mux firmware version all

- scripts/generate_dump
Adding FRR related evpn dumps to techsupport
Added vtysh commands in generate_dump to dump required EVPN related information
Run techsupport and check if the commands are dumped
> [techsupport]Adding FRR evpn dumps

- config/main.py
- tests/config_mirror_session_test.py
This PR is to fix the exception in adding mirror session when `gre_type` is absent.
```
~$ sudo config mirror_session add session_1 25.25.25.25 10.1.1.1 8 100
File "/usr/local/bin/config", line 8, in <module>
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1135, in invoke
sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
File …
```
> Fix exception in adding mirror_session when `gre_type` is absent

- scripts/generate_dump
I added/extended some commands of the generate_dump script to collect more information about the system and processes.
In addition, I removed some errors when trying to remove files that don't exist.
create new function and add new calls for commands to get more information.
Regarding the error messages - I checked before removing the files and remove with force parameter.
verified that the new files and information are part of the dump
> [scripts/generate_dump] add information to tech-support file

- config/main.py
- tests/show_vrf_test.py
- tests/subintf_test.py
Added IP address remove warnings when performing various VRF commands i.e.,
- `vrf bind`
- `vrf unbind`
- `del vrf`
* Modify `config/main.py` to include `click.echo` warnings.
* Add test cases for interface/subinterface vrf bind, unbind and del.
Tested the changes locally by building sonic-utilities Python wheel package inside Bullseye slave container
<pre>mdanish@3be53d98ab67:/sonic/src/sonic-utilities$ pytest-3 tests/show_vrf_test.py
<b>==================================================================== test session starts =====================================================================</b>
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-utilities/tests, configfile: pytest.ini
plugins: pyfakefs-5.0.0, cov-2.10.1
<b>collected 3 items …
> Add IP remove warnings for VRF commands

- sfputil/main.py
- tests/sfputil_test.py
Fixed  "sudo sfputil show error-status" on a multiasic platform issue.  Fixes https://github.com/sonic-net/sonic-buildimage/issues/8504
This change is also applicable to 202205 branch
The current implementation is only hard code to  connect STATE_DB on host database  with SonicV2Connector(127.,0.0.1).   To support the multiasic platform, we need to query the data entry from STATE_DB of namespace database.   Following the existing design to  use multi_asic.get_front_end_namespaces.  And looping the namespaces to get the output_table for each namespace.  
1) running the image on a multasic platform which front panel ports have  SFP inserted. 
2) execute "sudo sfptuil show error-status". The output should show all ports with status.
```
admin@sonic:~$ sudo sfputil show error-status
Port …
```
> Fix sudo sfputil show error-status on a multiasic platform issue

- show/interfaces/__init__.py
With the commit of https://github.com/sonic-net/sonic-buildimage/pull/11894.
device neighbor metadata in config_db.json changed a little bit when "lo_addr"/"mgmt_addr" are None.
CLI parse code for "show interface neighbor expected" is not strong enough to handle None case. 
It always assume 'lo_addr' and 'mgmt_addr' exists, and will finally cause KeyError, show command will not print the information. 
```
for port in natsorted(list(neighbor_dict.keys())):
try:
device = neighbor_dict[port]['name']
body.append([port,
device,
neighbor_dict[port]['port'],
neighbor_metadata_dict[device]['lo_addr'],
neighbor_metadata_dict[device]['mgmt_addr'],
neighbor_metadata_dict[device]['type']])
except KeyError:
pass
```
After discussion with team, we plan to keep current yang model change, but 
add fields …
> fix show interface neighbor expected empty issue

- config/main.py
- tests/config_mirror_session_test.py
This PR is a duplication  of https://github.com/sonic-net/sonic-utilities/pull/2458/files.
This PR is to fix the exception in adding mirror session when `gre_type` is absent.
```
~$ sudo config mirror_session add session_1 25.25.25.25 10.1.1.1 8 100
File "/usr/local/bin/config", line 8, in <module>
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1135, in invoke
sub_ctx …
```
> [202205] Fix exception in adding mirror_session when `gre_type` is absent

- config/aaa.py
- config/main.py
- config/validated_config_db_connector.py
- tests/aaa_test.py
- tests/validated_config_db_connector_test.py
-Add YANG validation using GCU for writes to TACPLUS, TACPLUS_SERVER, AAA, VLAN_SUB_INTERFACE  in ConfigDB
-decorate mod_entry with validated_mod_entry to include YANG validation 
-process all values in GCU JsonPatch, convert to string
Using same method as https://github.com/sonic-net/sonic-utilities/pull/2190/files, extend to TACPLUS, TACPLUS_SERVER, AAA, VLAN_SUB_INTERFACE use cases
Verified testing CLI on virtual switch
> YANG Validation for ConfigDB Updates: TACPLUS, TACPLUS_SERVER, AAA, VLAN_SUB_INTERFACE tables + decorated validated_mod_entry

- show/vnet.py
- tests/mock_tables/appl_db.json
- tests/mock_tables/state_db.json
- tests/show_vnet_test.py
Original PR
https://github.com/sonic-net/sonic-utilities/pull/2390
What I did
Added a new show command to see the VNET Tunnel routes being advertised by BGP. The output can be filtered based on IPv4/Ipv6 and community string.
How I did it
Iterate over the BGP_PROFILE_TABLE in Application DB and ADVERTISE_NETWORK_TABLE in state DB. Correlate the information and filter based on community string.
run **show vnet advertised-routes ** with optional community string.
$ show vnet advertised-route
Prefix                    Profile              Community Id
------------------------  -------------------  --------------
160.62.191.1/32           FROM_SDN_SLB_ROUTES  1234:1235
160.63.191.1/32           FROM_SDN_SLB_ROUTES  1234:1235
160.64.191.1/32           FROM_SDN_SLB_ROUTES …
> [show]show ip advertised route[202205]

- generic_config_updater/patch_sorter.py
- tests/generic_config_updater/patch_sorter_test.py
Refer to https://github.com/sonic-net/sonic-utilities/pull/2273
Before the fix, the prefix pattern `Ethernet12|*` would match `Ethernet124|0` and `Ethernet12|0`. 
The suffix pattern `*|10` would match `Ethernet1|10` and `Ethernet1|11110`.
Fix a bug of JsonPointerFilter in GCU that will make the wrong selection of candidates.
Add the patch addressing '|' in the prefix and suffix filter to avoid wrong selection.
Add UT.
> [GCU] Fix JsonPointerFilter bug

- scripts/db_migrator.py
Lock the major version on 202211 branch to version 3.
Start a new major version on master branch, with current version set to `version_4_0_0`.
> Change db_migrator major version on master branch from version 3 to 4

- scripts/portconfig
- tests/config_an_test.py
- tests/config_lt_test.py
- tests/config_xcvr_test.py
`portconfig` is a utility designed to configure various attributes on a physical port or a port channel.
It should reject the operation that a user wants to configure an attribute that will be inserted into `CONFIG_DB.PORT` table on a port channel. Otherwise, it will generate an entry for the port channel, which causes orchagent to be aborted.
Eg. the following commands
```
admin@sonic:~$ sudo config portchannel add PortChannel0001
admin@sonic:~$ sudo config interface speed PortChannel0001 100000
```
will cause the following error
```
Oct 26 04:50:27.055970 sonic ERR swss#orchagent: :- meta_sai_validate_oid: oid is set to null object id on SAI_OBJECT_TYPE_PORT
Oct 26 04:50:27.055970 sonic ERR swss#orchagent: :- getPortSupportedSpeeds: Failed to get a list of supported speeds for port …
```
> Do not configure physical attributes on port channels in portconfig

- scripts/fast-reboot-dump.py
`fast-reboot-dump.pty` script collects fdb entries, will send out arp request for these fdb entries to keep them active longer.
However, the script sends these requests with switch mac.
Which has negative impacts on dualtor devices where the arp requests should come from vlan_mac, instead of router_mac
Check the device subtype from metadata. If it is dualtor, use vlan_mac, otherwise use interface mac as the src address for ARP packets.
> [dualtor][202012] Send arp/ndp packets from vlan_mac if the device is dualtor

- sonic_installer/bootloader/uboot.py
- tests/installer_bootloader_uboot_test.py
sonic-installer list will throw a exception when install images as the following step
(onie-nos-install ) Install first image A
(sonic-installer) Install Image B and not reboot it
(sonic-installer) set default to back to Image A
sudo sonic-installer cleanup
At this time, executing sonic-installer list will throw exception
Modify the get_next_image() in uboot.py to check and return index 1 when the images list contains two elements.
This PR should work with https://github.com/sonic-net/sonic-buildimage/pull/12609
This PR is needed by branch 202012 and 2022o5
Using the following test case to verify it
Case 1:
1) (onie-nos-install ) Install first image A (SONiC-OS-202012.0-dirty-20221104.031351)
2) (sonic-installer) Install Image B (SONiC-OS-202205.0-dirty-20221104.050857) and not reboot it …
> [armhf][sonic-installer] Fix the issue of sonic-installer list after set-default and cleanup

- scripts/vnet_route_check.py
- tests/vnet_route_check_test.py
closes https://github.com/sonic-net/sonic-utilities/issues/2424
Fixed the return value for vnet route check if vxlan tunnel is present but no route mismatch is happening.
return 0 of there is no route diff
add a vxlan tunnel without routes and run the script. it should return 0.
> bugfix[2024] vnet route check exit code fix.

- tests/muxcable_test.py
- utilities_common/platform_sfputil_helper.py
Catch the exception if a user passes in an invalid port name.
Added a try/catch to catch the ValueError.
Run "show muxcable cableinfo [invalid port]".
```
crystalnet@ibr01:~$ show muxcable cableinfo all …
```
> [show][muxcable] Catch port Value error exception (#2076)

- config/main.py
- tests/config_mirror_session_test.py
This PR is to backport PR #2162 into `202205` branch.
`queue = 0` is not accepted by the validation of input because the follow check
https://github.com/Azure/sonic-utilities/blob/bce4694d3ad4454fc7181b99433457e76ab9e0a0/config/main.py#L2028-L2029
When addressing the issue, I saw similar issue in the logic of handling `gre_type`. The issue is also fixed.
Change `if queue` to `if queue is not None`
Verified by UT
```
python setup.py test --addopts "tests/config_mirror_session_test.py -v" 
========================================================================================= test session starts =========================================================================================
collected 3 items …
```
> [202205] Fix validation of input of `config mirror_session add`

- scripts/reboot
The vendor platform reboot, which is called from the reboot script, supports force mode, and for now there is no option to execute it via the reboot script, so this change will enable it.
**What I did**
Add an "f" option in reboot_script for executing reboot force mode.
Add this option to help command as well.
Execute the reboot script with "-f" and see that the vendor platform reboot executes the force mode indeed.
> Add "f" option for executing reboot force mode

- sonic_installer/bootloader/uboot.py
What I did
sonic-installer list will throw a exception when install images as the following step
(onie-nos-install ) Install first image A
(sonic-installer) Install Image B and not reboot it (sonic-installer) set default to back to Image A
sudo sonic-installer cleanup
At this time, executing sonic-installer list will throw exception
How I did it
Modify the get_next_image() in uboot.py to check and return index 1 when the images list contains two elements. This PR should work with sonic-net/sonic-buildimage#12609
This PR is needed by branch 202012 and 2022o5
Signed-off-by: mlok <marty.lok@nokia.com>
(cherry picked from commit d1ca2cdda0cdc1402b88d53816576486e2e8107f)
Cherry-pick PR https://github.com/sonic-net/sonic-utilities/pull/2479 from master branch to 202012 branch 
Cherry-pick …
> [armhf][sonic-installer] [cherry-pick to branch 202012] Fix the issue of sonic-installer list after set-default and cleanup (#2479)

- tests/bgp_commands_test.py
- tests/conftest.py
- utilities_common/bgp_util.py
Fixes #2492 
Use `click.echo` and `exit` instead of `ctx.fail` in cli handler when no neighbor information is returned from bgp container.
Test on target and add UT
new output when no neighbors are present
```
admin@sonic:~$ show ipv6 bgp summary
% No BGP neighbors found in VRF default
admin@sonic:~$
```
> avoid printing error if no neighbors are present

- show/bgp_common.py
- tests/conftest.py
- tests/ip_show_routes_multi_asic_test.py
- tests/ip_show_routes_test.py
- tests/mock_tables/asic0/config_db.json
- tests/show_ip_route_common.py
- utilities_common/bgp_util.py
- utilities_common/cli.py
There are many issues with the "SONIC_CLI_IFACE_MODE=aliasshow ip/ipv6 route [json]" commands on both single asic platform and multiasic platform
- Doesn't show the interface alias on single asic platform
- Display the route info twice either in Json format or default format on the single asic platform
- Doesn't show the interface alias on multiasic platform
- Display the route info in the Json format even if Json is not specified in the CLI command 
Resolves# https://github.com/sonic-net/sonic-buildimage/issues/8498
This PR is required by 202205 branch
- In the current show_routes() function, the internal command to get the route for single asic platform is formatted to "vtysh show ip/ipv6 route" while it is formatted to "vtysh  show ip/ipv6 route json".   This commit changes to use the …
> [show][multiasic]Fixed SONIC_CLI_IFACE_MODE=alias show ip|ipv6 route output in default mode issue

- scripts/generate_dump
While running showtech support in Cisco-8000 platform following errors are seen. This failure is happening
because non-file entries like current directory "." and subdirectory "./Cisco-8102-C64" are being
saved as a file.
mkdir: created directory '/var/dump/sonic_dump_mth64-m5-2_20221026_201933/sai'
cp: -r not specified; omitting directory '.'
handle_error $? $LINENO
ERR: RC:-1 observed on line 762
sonic_dump_mth64-m5-2_20221026_201933/sai/./
rm: cannot remove '/var/dump/sonic_dump_mth64-m5-2_20221026_201933/sai/.': Is a directory
handle_error $? $LINENO
ERR: RC:-1 observed on line 769
cp: -r not specified; omitting directory './Cisco-8102-C64'
handle_error $? $LINENO
ERR: RC:-1 observed on line 762
tar: sonic_dump_mth64-m5-2_20221026_201933/sai/Cisco-8102-C64: Cannot stat: No such file …
> Show tech save file to skip non-file entries in cisco-8000 platform

- config/main.py
- tests/config_snmp_test.py
- tests/config_test.py
- tests/synchronous_mode_test.py
- tests/tpid_test.py
- tests/yang_config_validation_test.py
-Add YANG validation using GCU for writes to DEVICE_METADATA, SNMP, SNMP_COMMUNITY  in ConfigDB
Using same method as https://github.com/sonic-net/sonic-utilities/pull/2190/files, extend to DEVICE_METADATA, SNMP, SNMP_COMMUNITY use cases
Verified testing CLI on virtual switch
> YANG Validation for ConfigDB Updates: DEVICE_METADATA, SNMP, SNMP_COMMUNITY tables

- doc/Command-Reference.md
- psuutil/main.py
- scripts/psushow
- tests/mock_tables/state_db.json
- tests/psushow_test.py
- tests/psuutil_test.py
Support PSU power threshold checking
1. Introduce a new state for the PSU, indicating whether a PSU power threshold is exceeded
2. For `psuutil`, expose the power thresholds
3. Add `HW Rev` to `psuutil`
Unit and manual test
show platform psustatus
```
admin@sonic:~$ show platform  psustatus
PSU    Model          Serial        HW Rev      Voltage (V)    Current (A)    Power (W)  Status  LED
-----  -------------  ------------  --------  -------------  -------------  -----------  ------- -----
PSU 1  MTEF-PSF-AC-A  MT1629X14911  A3                12.08           5.19        62.62  OK      green
PSU 2  MTEF-PSF-AC-A  MT1629X14913  A3                12.01           4.38        52.50  OK      green
```
psuutil
```
admin@sonic:~$ show platform …
```
> [psushow & psuutil] Support PSU power threshold checking

- show/vxlan.py
- tests/mock_tables/appl_db.json
- tests/vxlan_test.py
During the execution of show vxlan remotemac command, if a mac moves after the key is fetched but not the table fields, there will be the below traceback
```
show vxlan remotemac 2.2.2.2 
File …
```
> [VXLAN]Fixing traceback in show remotemac when mac moves during command execution

- scripts/pg-drop
Since PG counters are created only if they are configured in the switch, it is not enough to relay only on the first entry in the DB when building the output table of watermarkstat script.
We need to go over all configured counters, check what is the max configured and build the table accordingly.
Iterate all configured PG buffers for all ports and find the max index.
Build the output table according to the max index.
Run test "pgdropstat_test.py" including this PR and observe it passes.
- N/A
- N/A
> [drop counters] Fix CLI script for unconfigured PGs

- show/kube.py
- tests/kube_test.py
Signed-off-by: Yun Li <yunli1@microsoft.com>
Change show kube command default value of insecure key to "True"
Show kube command default value of insecure key should be "True"
Just execute "show kube server config" to see the output
> Change show kube command default value of insecure key to True

- config/main.py
- tests/config_reload_input/config_db_invalid.json
- tests/config_test.py
sonic-utilities: bugfix-9499
* Update config/main.py to verify if a config input file is properly formatted before writing it into confib_db
* Update tests/config_test.py to include test cases for invalid input file
* Add tests/config_reload_input/config_db_invalid.json as invalid input file used in tests/config_test.py
Signed-off-by: cchoate54@gmail.com
Include a check to validate if all input files are properly formatted before trying to write them to config_db to resolve bug [9499 in sonic-buildimage](https://github.com/sonic-net/sonic-buildimage/issues/9499).
Include a check to validate if all input files are properly formatted before trying to write them to config_db.
Run tests/config_test.py. 
With the change added in main.py, run 'config reload' with an inproperly formatted input …
> sonic-utilities: Update config reload() to verify formatting of an input file

- scripts/sfpshow
- tests/mock_tables/asic0/state_db.json
- tests/mock_tables/asic1/state_db.json
- tests/mock_tables/state_db.json
This PR is needed along with https://github.com/sonic-net/sonic-platform-daemons/pull/320 to continue supporting "show interface transceiver eeprom \<port\> -d" CLI since [PR#320](https://github.com/sonic-net/sonic-platform-daemons/pull/320) is separating DOM threshold related information in a separate table entry (TRANSCEIVER_DOM_THRESHOLD from TRANSCEIVER_DOM_SENSOR) in state DB.
The change with this PR will ensure that the CLI output remains unchanged until https://github.com/sonic-net/sonic-buildimage/issues/12911 is committed which will all together publish DOM threshold related information in a new CLI.
dom_info_dict is now populated using information from both TRANSCEIVER_DOM_SENSOR as well as TRANSCEIVER_DOM_THRESHOLD.
Please refer to the enclosure attached to …
> Transceiver eeprom dom CLI modification to show output from TRANSCEIVER_DOM_THRESHOLD table

- config/main.py
- tests/ip_config_test.py
Added a check in config interface ip command to block if the interface is portchannel member
Added check in config handling
Added UT to verify.
> [config]Block adding IP address on portchannel member 

- config/syslog.py
- setup.py
- show/syslog.py
- sonic_package_manager/manifest.py
- sonic_package_manager/service_creator/feature.py
- syslog_util/common.py
- tests/sonic_package_manager/test_service_creator.py
- tests/syslog_input/assert_show_output.py
- tests/syslog_input/syslog_rate_limit_db.json
- tests/syslog_test.py
HLD:
https://github.com/sonic-net/SONiC/pull/1049
Support CLIs for syslog rate limit feature
Support 4 new CLIs:
1. `config syslog rate-limit-host`
2. `show syslog rate-limit-host`
3. `config syslog rate-limit-container`
4. `show syslog rate-limit-container`
Unit test
N/A
```
Example:
show syslog rate-limit-host
INTERVAL     BURST
----------   --------
500          50000
show syslog rate-limit-container
SERVICE    INTERVAL     BURST
--------   ----------   --------
bgp        500          N/A
snmp       300          20000
swss       2000         12000
show syslog rate-limit-container bgp
SERVICE    INTERVAL     BURST
--------   ----------   --------
bgp        500          5000
```
> Support syslog rate limit configuration for containers and host

- scripts/db_migrator.py
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/12955
The cherrypick changes (from 202012 to master) made as part of https://github.com/sonic-net/sonic-utilities/pull/2515
broke the master branch `db_migrator`. The issue is due to an import of `swsssdk` which is no longer available in master image.
Removed the import statement that came due to cherrypick.
Checked on physical device running master image
Without fix:
```
root@str2-acs-12:~# db_migrator.py
File "/usr/local/bin/db_migrator.py", line 11, in <module>
from swsssdk import ConfigDBConnector, SonicDBConfig
ModuleNotFoundError: No module named 'swsssdk'
root@str2-acs-12:~# 
```
With fix:
```
root@str2-acs-12:~# db_migrator.py     
version_4_0_0
root@str2-acs-12:~# 
```
> [db_migrator] Remove import of swsssdk as it is not supported in master

- scripts/generate_dump
Signed-off-by: Geert Vlaemynck <gvlaemyn@cisco.com>
Added cisco-8000 specific platform information to "show techsupport" tarfile
Added collect_cisco_8000 function to scripts/generate_dump which filters out the wanted files from /usr/share/sonic/device/${platform} and saves them in the techsupport tarfile under sai subdirectory
Run "show techsupport" and grep sai in the generated techsupport tarfile
> [202205][generate_dump]: Enhance show techsupport for cisco-8000 platform

- show/muxcable.py
- tests/mock_tables/asic_db.json
- tests/muxcable_test.py
Stemming from https://github.com/sonic-net/sonic-swss/pull/2557. 
This PR is to update `show mux tunnel-route` command to show status of both ASIC and kernel tunnel routes.
Only check Kernel Route, if removing tunnel route for `server_ipv4` in kernel, it won't show in CMD output: 
```
zhangjing@********************:~$ show mux tunnel-route Ethernet4
PORT       DEST_TYPE    DEST_ADDRESS
---------  -----------  --------------------------------
Ethernet4  server_ipv6  2603:10b0:d11:8614::a32:9112/128
```
Check both ASIC and APP DB for tunnel route status
```
zhangjing@********************:~$ show mux tunnel-route Ethernet4
PORT       DEST_TYPE    DEST_ADDRESS                      kernel    asic
---------  ----------- …
```
> [muxcable][show] update `show mux tunnel-route` to separate ASIC and kernel into two columns

- scripts/generate_dump
Optimize the execution time of the 'show techsupport' script to 5-10%.
The `show techsupport` CLI command calls the `generate_dump` bash script. In the script, there are a many functions that do the next scenario:
```
1. Run some CLI command
2. Save output from step 1 to the temporary file
3. Append the temporary file from step 2 to the `/var/dump/sonic_dump_XXXX.tar` file
4. Delete the temporary file from step 2
```
This PR removes the `3 and 4 step` from those functions and creates a new function `save_to_tar()` which will add to `.tar` archive the whole directory with temporary files (which means it will not spawn a `tar -v -rhf ...` process for each temporary file)
Run the `time show techsupport` CLI command and compare the execution …
> [generate_dump] Optimize the execution time of the 'show techsupport' script to 5-10% by reducing calls to the 'tar append' operation

- scripts/db_migrator.py
- tests/db_migrator_input/appl_db/loopback_interface_migrate_from_1_0_1_expected.json
- tests/db_migrator_input/appl_db/loopback_interface_migrate_from_1_0_1_input.json
- tests/db_migrator_input/config_db/loopback_interface_migrate_from_1_0_1_expected.json
- tests/db_migrator_input/config_db/loopback_interface_migrate_from_1_0_1_input.json
- tests/db_migrator_test.py
Fix the issue where cross branch upgrades (base DB version 1_0_1) lead to a OA crash due to a duplicate IP2ME route being added when there are more than one Loopback interfaces.
The issue happens as in current implementation `lo` is hardcoded to be replaced as `Loopback0`.
When the base image's APP DB has more than one IP assigned to `lo` interface, upon migration, all the IPs are assinged to same loopback `Loopback0`. This is incorrect, as in newer images different IPs are assinged to distinct Loopback interfaces.
Eg. If the base image APP DB contains:
```
{
"INTF_TABLE:lo:10.1.0.32/32" : {
"scope": "global",
"family": "IPv4"
},
"INTF_TABLE:lo:10.20.8.199/32" : {
"scope": "global",
"family": "IPv4"
}
}
```
In current implementation, this will be INCORRECTLY migrated as:
```
{ …
```
> [db_migrator] Fix migration of Loopback data: handle all Loopback interfaces

- sonic-utilities-data/templates/timer.unit.j2
I fixed the timer unit template to account "wanted-by" option in the manifest. In case service is delayed, "wanted-by" is applied to the timer unit that delays it.
I updated timer.unit.j2 template
Make sure that "WantedBy" is rendered in the timer unit.
> [timer.unit.j2] use wanted-by in timer unit

- doc/Command-Reference.md
HLD: https://github.com/sonic-net/SONiC/pull/1049
Add command reference doc for syslog rate limit feature
Add command reference doc for syslog rate limit feature
Manual check
```
admin@sonic:~$ show syslog rate-limit-container
SERVICE         INTERVAL    BURST
--------------  ----------  -------
bgp             0           0
database        300         20000
lldp            300         20000
mgmt-framework  300         20000
pmon            300         20000
radv            300         20000
snmp            300         20000
swss            300         20000
syncd           300         20000
teamd           300         20000
telemetry       300         20000
admin@sonic:~$ show syslog rate-limit-container bgp
SERVICE         INTERVAL    BURST
--------------  ----------  -------
bgp …
```
> [Command Ref] Add doc for syslog rate limit

- scripts/generate_dump
Optimize the execution time of the 'show techsupport' script to 5-10%.
The `show techsupport` CLI command calls the `generate_dump` bash script. In the script, there are a many functions that do the next scenario:
```
1. Run some CLI command
2. Save output from step 1 to the temporary file
3. Append the temporary file from step 2 to the `/var/dump/sonic_dump_XXXX.tar` file
4. Delete the temporary file from step 2
```
This PR removes the `3 and 4 step` from those functions and creates a new function `save_to_tar()` which will add to `.tar` archive the whole directory with temporary files (which means it will not spawn a `tar -v -rhf ...` process for each temporary file)
Run the `time show techsupport` CLI command and compare the execution …
> [202205] [generate_dump] Optimize the execution time of the 'show techsupport' script to 5-10% by reducing calls to the 'tar append' operation

- scripts/generate_dump
**DEPENDS ON:** [sonic-utilities/pull/2562](https://github.com/sonic-net/sonic-utilities/pull/2562)
Optimize the execution time of the 'show techsupport' script.
The `show techsupport` CLI command calls the `generate_dump` bash script. In the script, there are a many functions that do the next scenario:
```
1. Run some CLI command
2. Save output from step 1 to the temporary file
3. Append the temporary file from step 2 to the `/var/dump/sonic_dump_XXXX.tar` file
4. Delete the temporary file from step 2
```
This PR will add the execution of these functions in parallel manner. Also, it will not spawn too many processes to not waste all CPU time.
First test scenario
```
Run the `time show techsupport` CLI command and compare the execution time …
```
> [202205] [generate_dump] Optimize the execution time of 'show techsupport' CLI by paraller function execution

- sonic-utilities-data/templates/timer.unit.j2
I fixed the timer unit template to account "wanted-by" option in the manifest. In case service is delayed, "wanted-by" is applied to the timer unit that delays it.
I updated timer.unit.j2 template
Make sure that "WantedBy" is rendered in the timer unit.
> [202205][timer.unit.j2] use wanted-by in timer unit

- scripts/pg-drop
- scripts/watermarkstat
Fix issue
All the PGs between minimal and maximal indexes are displayed regardless of whether they are configured.
Originally, watermark counters were enabled for all PGs, so there is no issue.
Now, watermark counters are enabled only for PGs with buffer configured, eg. if PG 0/2/3/4/6, is configured, PG 0-6 will be displayed, which is confusing by giving users a feeling that PG 7 is lost
Display valid PGs only
Manually test and unit test.
```
Port    PG0    PG1    PG2    PG3    PG4
-----------  -----  -----  -----  -----  -----
Ethernet0      0      0      0      0      0
Ethernet2      0      0      0      0      0
Ethernet8      0      0      0      0      0
Ethernet10      0      0      0      0      0
Ethernet16      0      0      0 …
```
> Fix issue: unconfigured PGs are displayed in watermarkstat

- scripts/pg-drop
- scripts/watermarkstat
This is to cherry-pick #2556 to 202205
Fix issue
All the PGs between minimal and maximal indexes are displayed regardless of whether they are configured.
Originally, watermark counters were enabled for all PGs, so there is no issue.
Now, watermark counters are enabled only for PGs with buffer configured, eg. if PG 0/2/3/4/6, is configured, PG 0-6 will be displayed, which is confusing by giving users a feeling that PG 7 is lost
Display valid PGs only
Manually test and unit test.
```
Port    PG0    PG1    PG2    PG3    PG4
-----------  -----  -----  -----  -----  -----
Ethernet0      0      0      0      0      0
Ethernet2      0      0      0      0      0
Ethernet8      0      0      0      0      0
Ethernet10      0      0      0      0 …
```
> [202205] Fix issue: unconfigured PGs are displayed in watermarkstat

- scripts/mellanox_buffer_migrator.py
It is expected that db_migrator is not able to fetch DEVICE_METADATA when it is invoked before the CONFIG_DB is initialized. In this case, we should not use ERROR to log the message since it's not an error.
Change the severity to NOTICE
Change the severity.
Manually test.
> [Mellanox] Change severity to NOTICE in Mellanox buffer migrator when unable to fetch DEVICE_METADATA due to empty CONFIG_DB during initialization

- scripts/generate_dump
Fixed a deletion flow for all secret files in the tech support dump.
Delete files by using the `find` and  `rm` Linux utilities.
Run the [show_techsupport/test_techsupport_no_secret.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/show_techsupport/test_techsupport_no_secret.py)
> [202205][generate_dump] Fix for a deletion flow for all secret files in the techsupport dump

- scripts/generate_dump
Fixed a deletion flow for all secret files in the tech support dump.
Delete files by using the `find` and  `rm` Linux utilities.
Run the [show_techsupport/test_techsupport_no_secret.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/show_techsupport/test_techsupport_no_secret.py)
> [generate_dump] Fix for a deletion flow for all secret files in the techsupport dump

- scripts/db_migrator.py
This PR implements [fastboot] Preserve CoPP table HLD to improve fastboot flow (https://github.com/sonic-net/SONiC/pull/1107).
It is PR against 202205 of the following PR: https://github.com/sonic-net/sonic-utilities/pull/2524
Preserve COPP table contents through DB migration. (Mellanox only)
Skipped deleting of COPP tables in DB migrator
Observe COPP table contents are preserved right after reboot
> [202205] Preserve copp tables through DB migration

- scripts/generate_dump
Reverted PRs because they caused the degradation that some files are missing in `show techsupport archive`.
Revert the:
`"[202205][generate_dump] Fix for a deletion flow for all secret files in the techsupport dump (#2572)"`
`"generate_dump] Optimize the execution time of 'show techsupport' CLI by paraller function execution (#2565)"`
`"[202205] [generate_dump] Optimize the execution time of the 'show techsupport' script to 5-10% by reducing calls to the 'tar append' operation (#2562)"`
This reverts commits
e1c82435b53fd699030d5c6d1ad64b16690dd9f6
f45dcfbdccca74e1579c76a3d88f4fb946c3c5a5
93172c4a0bf09421bff1b53e391b3f9d719da45f
> [202205] Revert the show-techsupport optimization PR's

- scripts/storyteller
Add `linkprober` category to story teller. It will reflect dualtor heartbeat events. 
Tested on dualtor device, was able to grep link prober state change events.
> [storyteller] add link prober state change to story teller

- scripts/db_migrator.py
This PR should be merged together with https://github.com/sonic-net/sonic-swss/pull/2548 and is required to 202205 and 202211.
This PR implements [fastboot] Preserve CoPP table HLD to improve fastboot flow (https://github.com/sonic-net/SONiC/pull/1107).
Preserve COPP table contents through DB migration. (Mellanox only)
Skipped deleting of COPP tables in DB migrator.
Observe COPP table contents are preserved right after reboot.
> Preserve copp tables through DB migration

- tests/bgp_commands_test.py
- tests/conftest.py
- utilities_common/bgp_util.py
Fix #2492. port #2502  in 202012 branch
Use `click.echo` and `exit` instead of `ctx.fail` in cli handler when no neighbor information is returned from bgp container.
Test on target and add UT
new output when no neighbors are present
```
admin@vlab-01:~$ show version
SONiC Software Version: SONiC.202012.202057-b111cecf0
Distribution: Debian 10.13
Kernel: 4.19.0-12-2-amd64
Build commit: b111cecf0
Build date: Thu Jan 12 12:18:18 UTC 2023
Built by: AzDevOps@vmss-soni000AO0
Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: 000000
Uptime: 00:04:12 up  2:26,  1 user,  load average: 0.30, 0.21, 0.19
Docker images:
REPOSITORY                    TAG                       IMAGE ID …
```
> [202012] avoid printing error if no neighbors are present

- scripts/fast-reboot
Due to an issue of fallback from to cold-boot when using upgrade with fast-reboot combined with FW upgrade a short term solution is to extend the timer.
An issue will be opened on this case with the full details, link will be added to the PR.
Long term solution of using fast-reboot finalizer replacing the timer is in work.
Extend the timer of STATE DB fast-reboot entry to 210 seconds.
Modify the TTL of the entry set in STATE DB.
Verify the entry was preserved for 210 seconds.
> Extend fast-reboot STATE_DB entry timer

- show/main.py
- tests/show_test.py
Add bgpraw output to `show runningconfiguration all`
```
Requirements:
1. current `show runningconfig` will print all the ConfigDB in a json format, we need to add a new key-value into the json output "bgpraw" with a long string value
2. The long string value should be the output of `vtysh -c "show run"`. It is normally multiline string, may include special characters like \". Need to make sure the escaping properly
3. We do not need to insert the key-value into ConfigDB is not existing there
4. If ConfigDB already has the key-value, we do not need to override it by vtysh command output
5. Not break multi-asic use
```
Generate bgpraw output then append it to `show runnningconfiguration all`'s output
Mannual test
```
admin@vlab-01:~$ show run all
{
"ACL_TABLE": {
......
"WRED_PROFILE": { …
```
> [show] Add bgpraw to show run all

- scripts/fast-reboot
This is a PR against 202205 based on the following PR: https://github.com/sonic-net/sonic-utilities/pull/2577
Due to an issue of fallback from to cold-boot when using upgrade with fast-reboot combined with FW upgrade a short term solution is to extend the timer.
An issue will be opened on this case with the full details, link will be added to the PR.
Long term solution of using fast-reboot finalizer replacing the timer is in work.
Extend the timer of STATE DB fast-reboot entry to 210 seconds.
Modify the TTL of the entry set in STATE DB.
Verify the entry was preserved for 210 seconds.
> [202205] Extend fast-reboot STATE_DB entry timer

- scripts/fast-reboot
I removed TODO comment which is no longer relevant.
TODO can be removed as there is no need to delete FDB table.
Recently, fast boot was changed to use this function and in fast boot we don’t want to clean FDB. 
In warmboot we do need to clean FDB, however, it is being performed in a later stage when FDB flush event occurs.
Remove comment.
Remove comment from python module, no functional effect.
> Remove TODO comment which is no longer relevant

- config/aaa.py
- tests/radius_test.py
Add YANG validation using GCU for writes to RADIUS_SERVER table in ConfigDB
Using same method as https://github.com/sonic-net/sonic-utilities/pull/2190/files, extend to RADIUS table
verified testing on virtual switch CLI, unit tests
> YANG Validation for ConfigDB Updates: RADIUS_SERVER

- scripts/generate_dump
I added APPL_STATE_DB to techsupport dump
Added a call to save APPL_STATE_DB
Run techsupport and verify dump/APPL_STATE_DB.json
> [techsupport] include APPL_STATE_DB dump

- generic_config_updater/generic_updater.py
- generic_config_updater/gu_common.py
- tests/generic_config_updater/gu_common_test.py
-Add new infrastructure to GCU for validation of moves that YANG models are unable to capture
-Prohibit deletion of PFC_WD POLL_INTERVAL field
- Ensure JSON Diff does not have POLL_INTERVAL deletion
- If diff reflects request for POLL_INTERVAL deletion, raise an Exception and do not allow patch application to go through
Attempt to delete POLL_INTERVAL field using GCU
Please note that this is different than the create-only extension, which is described here: https://github.com/sonic-net/SONiC/blob/master/doc/config-generic-update-rollback/Json_Patch_Ordering_using_YANG_Models_Design.md#313-using-yang-models-to-host-flags-for-move-validation
create-only is programmed as a MoveValidator in GCU, but that is different than the use case necessary for this PR. We don't want to validate each …
> [GCU] Prohibit removal of PFC_WD POLL_INTERVAL field

- show/main.py
- tests/techsupport_test.py
Modify the order of "--allow-process-stop" option, it belongs to 'generate_dump'.
Option "--allow-process-stop" does not belongs to 'timeout'. change to 'generate_dump'.
show techsupport can use option "--allow-process-stop" without error.
> fix show techsupport error

- scripts/fast-reboot
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
On some dev VMs, warm reboot on a VS image fails. Specifically, after kexec is called and the new kernel starts, the new kernel tries to load the initramfs, but fails to do so for whatever reason. There may be messages about gzip decompression failing and that it's corrupted.
```
[    2.053306] Initramfs unpacking failed: junk within compressed archive
[    2.372704] Failed to execute /init (error -2)
[    2.379385] Kernel panic - not syncing: No working init found.  Try passing init= option to kernel. See Linux Documentation/admin-guide/init.rst for guidance.
[    2.389714] CPU: 2 PID: 1 Comm: swapper/0 Not tainted 5.10.0-12-2-amd64 #1 Debian 5.10.103-1
[    2.396179] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS …
```
> [warm-reboot] Use kexec_file_load instead of kexec_load when available

- show/main.py
- tests/show_test.py
https://github.com/sonic-net/sonic-utilities/pull/2537
202205 branch doesn't have `from sonic_py_common import multi_asic`, which results in test failure and build error.
The only difference between this PR and original PR is just one line of import.
Tested locally on 202205 build and pass the build process.
> [202205][show] Add bgpraw to show run all

- scripts/generate_dump
Reverted PRs because they caused the degradation that some files are missing in `show techsupport archive`.
Revert
b34a540c [generate_dump] Fix for deletion flow for all secret files from show-techsupport dump (#2571)
258ffa09 [generate_dump] Optimize the execution time of 'show techsupport' CLI by parallel function execution (#2512) 
572c8cff Optimize the execution time of the 'show techsupport' script to 5-10%, (#2504)
This reverts commits
b34a540cca5555ab3aa74e19e81f24c2a20d311b
258ffa0928ce2c74ebdc180e13c6476dc2534983
572c8cffdddb7683e158d36067398600a71512ea
> Revert the show-techsupport optimization PR's

- scripts/fabricstat
- show/fabric.py
- tests/fabricstat_test.py
Added "show fabric reachability" command. 
The output of this command :
```# show fabric reachability
Local Link    Remote Module    Remote Link    Status
------------  ---------------  -------------  --------
0              304            171        up
1              304            156        up
2              304            147        up
```
Added test for the change at tests/fabricstat_test.py. The test is at https://github.com/sonic-net/sonic-mgmt/pull/6620/
> Add "show fabric reachability" command.

- config/muxcable.py
- tests/muxcable_test.py
This PR is to add CLI support to enable or disable the feature to send out a good-bye packet when `radv` service is stopped on `active-active` dualtor devices. 
UT added: 
```
tests/muxcable_test.py::TestMuxcable::test_config_muxcable_kill_radv_enable PASSED    [ 47%]
```
```
admin@svcstr-7050-acs-1:~$ sudo config mux kill-radv enable 
admin@svcstr-7050-acs-1:~$ redis-cli -n 4 hgetall "MUX_LINKMGR|SERVICE_MGMT"
1) "kill_radv"
2) "True"
admin@svcstr-7050-acs-1:~$ sudo config mux kill-radv disable 
admin@svcstr-7050-acs-1:~$ redis-cli -n 4 hgetall "MUX_LINKMGR|SERVICE_MGMT"
1) "kill_radv"
2) "False"
```
> [muxcable][config] Add support to enable/disable ceasing to be an advertisement interface when `radv` service is stopped

- generic_config_updater/change_applier.py
`show run all` output will include bgpraw for business needs. GCU ipv6 test will update BGP_NEIGHBOR table which caused `bgpraw` content change, which will make the `apply-patch` operation fail. The solution is to add `bgpraw` to ignored tables.
Add new added `bgpraw` table to ignored backend table.
Existing Unit test and local E2E GCU test.
> Ignore bgpraw in GCU applier

- doc/Command-Reference.md
- scripts/intfutil
- tests/intfutil_test.py
- What I did
Add interface link-training command into the CLI doc
- How I did it
Update Command-Reference.md
N/A
Signed-off-by: Dante Su <dante.su@broadcom.com>
> Add interface link-training command into the CLI doc

- show/main.py
- tests/show_bfd_test.py
the pull request https://github.com/sonic-net/sonic-swss/pull/2587 added local_discriminator to state_db
In this pull request, local discriminator is added in the output of the following show commands :
```
show bfd summary
show bfd peer
```
the upcoming BFD debug CLI needs the local discriminator to specify BFD session.
in show/main.py show bfd cli, read state db and show the value if there is local_discriminator field, and show "NA" if the field does not exist (backward compatible).
updated the test/show_bfd_test.py to test the local_discriminator field and show bfd cli output.
and also did manual test in a testbed (with modified bfdorch wich sonic-net/sonic-swss/pull/2587 diff ):
```
cisco@sonic:/var/tmp$ show bfd sum
Total number of BFD sessions: 1
Peer Addr    Interface    Vrf …
```
> [202012][show_bfd] add local discriminator in show bfd command

- generic_config_updater/change_applier.py
- generic_config_updater/gu_common.py
- tests/generic_config_updater/gu_common_test.py
After the previous fix https://github.com/sonic-net/sonic-utilities/pull/2623 , GCU still fails in the rollback operation. The `bgpraw` table should be discard in all GCU operation. 
Thus, I change `get_config_db_as_json` function to crop out "bgpraw" table.
Pop "bgpraw" table if exists.
Unittest
> [GCU] Ignore bgpraw table in GCU operation

- show/main.py
- tests/show_bfd_test.py
Double commit of PR https://github.com/sonic-net/sonic-utilities/pull/2616
> [show_bfd] add local discriminator in show bfd command

- show/system_health.py
Fix issue: show system-health CLI crashes
```
root@switch:/home/admin# show system-health summary 
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return …
```
> [system-health] Fix issue: show system-health CLI crashes

- scripts/generate_dump
What I did:
To address https://github.com/sonic-net/sonic-buildimage/issues/13561 skip saidump on T2 platforms for time-being.
How I did:
Check Device Type as SpineRouter and skip if true.
How I verify:
Manual Verification.
> Skip saidump for Spine Router as this can take more than 5 sec

- doc/Command-Reference.md
Updated docs about dhcp_relay config cli
Updated docs about dhcp_relay config cli
> [doc] Update docs for dhcp_relay config cli

- show/main.py
- tests/show_test.py
Signed-off-by: Mihir Patel <patelmi@microsoft.com>
Backport of #2641 
Enabling "show logging" CLI to show logs from tmpfs if it exists.
Added a check in the CLI handler to see if the path "/var/log.tmpfs" exists and display the logs from this directory if it exists. In case if the path doesn't exist, logs will be displayed from "/var/log"
Following tests were performed:
1.	"show logging" o/p when syslog resides in "/var/log"
2.	"show logging -f" o/p when syslog resides in "/var/log"
3.	"show logging" o/p when syslog resides in "/var/log.tmpfs"
4.	"show logging -f" o/p when syslog resides in "/var/log.tmpfs"
For detailed test results, please refer to [Unit-test_logging_cli.txt](https://github.com/sonic-net/sonic-utilities/files/10550147/Unit-test_logging_cli.txt)
> [202012][show] show logging CLI support for logs stored in tmpfs

- show/vnet.py
- tests/mock_tables/appl_db.json
- tests/mock_tables/state_db.json
- tests/show_vnet_test.py
- tests/show_vnet_vxlan_cli_test.py
Signed-off-by: siqbal1486 <shahzad.iqbal@microsoft.com>
fixed the output to wrap up the list of endpoints  after a certian number has bene printed.
added a function which limits the number of nexthops on each line to 2 for addresses longer than 16 characters and 3 for less than 16.
run show vnet routes all after adding a tunnel ecmp route with more than 3 endpoints.
```
vnet name    prefix    nexthop    interface
-----------  --------  ---------  -----------
vnet name        prefix                    endpoint                                     mac address    vni    status
---------------  ------------------------  -------------------------------------------  -------------  -----  --------
Vnet_v6_in_v6-0  fddd:a156:a251::a6:1/128 …
```
> [Bugfix] "show vnet routes all"

- show/vnet.py
- tests/mock_tables/appl_db.json
- tests/mock_tables/state_db.json
- tests/show_vnet_test.py
- tests/show_vnet_vxlan_cli_test.py
> [202012][Bugfix] "show vnet routes all"

- scripts/db_migrator.py
- tests/db_migrator_input/loglevel_db/logger_tables_input.json
It could be that LOG_LEVEL_DB includes some invalid data and/or a KEY_SET that is not cleaned up due to an issue, for example we observed _gearsyncd_KEY_SET set included in the LOG_LEVEL_DB and preserved in warm reboot. However, this key is not of type hash which leads to an exception and migration failure. The migration logic should be more robust allowing users to upgrade even though some daemon has left overs in the LOG_LEVEL_DB or invalid data is written.
To fix migration issue that leads to device configuration being lost.
Wrap the logic in try/except/finally.
202205 -> 202211/master upgrade.
> [db_migrator] make LOG_LEVEL_DB migration more robust

- scripts/generate_dump
HLD: https://github.com/sonic-net/SONiC/pull/1212
Added logic in techsupport script to collect SAI failure dump
Collected the SAI failure dumps if present.
Invoke techsupport and verify.
> [sai_failure_dump]Invoking dump during SAI failure

- generic_config_updater/gu_common.py
- tests/generic_config_updater/gu_common_test.py
Refer to https://github.com/sonic-net/sonic-buildimage/issues/11171, protect loopback0 from deletion
Add patch checker to fail the validation when remove loopback0
Unit test
> [GCU] protect loopback0 from deletion

- config/vlan.py
- tests/conftest.py
- tests/mclag_test.py
- tests/vlan_test.py
- utilities_common/cli.py
- utilities_common/dhcp_relay_util.py
Currently, add/del a vlan doesn't change related dhcpv6_relay config, which is incorrect.
1. Add dhcp_relay table init entry while adding vlan
2. Delete dhcp_relay related config while deleting vlan
3. Add unitest
1. By unitest
```
===================================================================================================================== test session starts ======================================================================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-utilities, configfile: pytest.ini
plugins: pyfakefs-5.0.0, cov-2.10.1
collected 2171 items  
tests/vlan_test.py::TestVlan::test_show_vlan PASSED …
```
> [vlan] Refresh dhcpv6_relay config while adding/deleting a vlan

- config/vlan.py
- tests/conftest.py
- tests/vlan_test.py
- utilities_common/cli.py
- utilities_common/dhcp_relay_util.py
Cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-utilities/pull/2660
Currently, add/del a vlan doesn't change related dhcpv6_relay config, which is incorrect.
1. Add dhcp_relay table init entry while adding vlan
2. Delete dhcp_relay related config while deleting vlan
3. Add unitest
1. By unitest
```
===================================================================================================================== test session starts ======================================================================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-utilities, configfile: pytest.ini
plugins: pyfakefs-5.0.0, …
```
> [202012][vlan] Refresh dhcpv6_relay config while adding/deleting a vlan (#2660)

- config/vlan.py
- tests/conftest.py
- tests/mclag_test.py
- tests/vlan_test.py
- utilities_common/cli.py
- utilities_common/dhcp_relay_util.py
Cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-utilities/pull/2660
Currently, add/del a vlan doesn't change related dhcpv6_relay config, which is incorrect.
1. Add dhcp_relay table init entry while adding vlan
2. Delete dhcp_relay related config while deleting vlan
3. Add unitest
1. By unitest
```
===================================================================================================================== test session starts ======================================================================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-utilities, configfile: pytest.ini
plugins: pyfakefs-5.0.0, …
```
> [202205][vlan] Refresh dhcpv6_relay config while adding/deleting a vlan (#2660)

- scripts/generate_dump
To address sonic-net/sonic-buildimage#13561 skip saidump on T2 platforms for time-being.
Cherry-pick https://github.com/sonic-net/sonic-utilities/pull/2637 to 202205
> Skip saidump for Spine Router as this can take more than 5 sec (#2637)

- scripts/generate_dump
1. [0ee19e5](https://github.com/sonic-net/sonic-utilities/commit/0ee19e55f946059a265551768a9b4b765c17f125) Revert [Revert the show-techsupport optimization PR's #2599](https://github.com/sonic-net/sonic-utilities/pull/2599)
2. [c8940ad](https://github.com/sonic-net/sonic-utilities/commit/c8940adec41c2c8432ae3eace5f06bfb881e4dd1) Add a fix for the empty `/dump` folder inside the final tar archive generated by the `show techsupport` CLI command.
3. [8a8668c](https://github.com/sonic-net/sonic-utilities/commit/8a8668c418868d2905afe99a9400a37a3a0a06be) Add a fix to not follow the symbolic links to avoid duplicate files inside the final tar archive generated by the `show techsupport` CLI command.
Modify the `scripts/generate_dump` script.
1. Manual verification
- do the `show techsupport` CLI …
> [generate_dump] Revert "Revert generate_dump optimization PR's #2599", add fixes for empty /dump forder and symbolic links

- scripts/portstat
For this change: https://github.com/sonic-net/sonic-utilities/pull/2466
1. do not emit `string` format Reminder if use json format is required
because the json output would be expecting only json format and might do some parsing for json only.
e.g.
test_drop_counters.py does a json.load on output of `portstats -j`
https://github.com/sonic-net/sonic-mgmt/blob/cbd1d60b43dd7b02e2f8a7b1755f60203a5a1fde/tests/common/helpers/drop_counters/drop_counters.py#L52
3. print for both multi_asic and chassis duts
even single_asic duts don't have internal links, single-asic linecards have inbnd&recycle ports connect to other linecards or SUP
Print the reminder only when no `-j` option is given -- json format not required
Move print of reminder to be only when not `use_json`
Before:
```
def …
```
> [portstat CLI] don't print reminder if use json format

- doc/Command-Reference.md
Add docs for dhcp_realy show/clear cli
Add docs for dhcp_realy show/clear cli
> [doc] Add docs for dhcp_relay show/clear cli

- config/dhcp_relay.py
- config/main.py
- config/vlan.py
- doc/Command-Reference.md
- tests/config_dhcp_relay_test.py
- utilities_common/dhcp_relay_util.py
Currently the config cli of dhcpv4 is may cause confusion and config of dhcpv6 is missing.
Add dhcp_relay config cli and test cases.
```
config dhcp_relay ipv4 helper (add | del) <vlan_id> <helper_ip_list>
config dhcp_relay ipv6 destination (add | del) <vlan_id> <destination_ip_list>
```
1. Verify by unitest, all passed
```
2023-01-31T17:13:39.5310534Z ----------- coverage: platform linux, python 3.7.3-final-0 -----------
2023-01-31T17:13:39.5311171Z Name                                          Stmts   Miss  Cover
2023-01-31T17:13:39.5311934Z -----------------------------------------------------------------
2023-01-31T17:13:39.5318510Z config/dhcp_relay.py                            101     11    89%
2023-01-31T17:13:39.5375220Z utilities_common/dhcp_relay_util.py               7      0 …
```
> [202012][dhcp-relay] Add support for dhcp_relay config cli

- scripts/fast-reboot
Add support of secure warm-boot to SONiC. 
Basically, warm-boot is supporting to load a new kernel without doing full/cold boot.
That is by loading a new kernel and exec with kexec Linux command. As a result of that, even when the Secure Boot feature is enabled, still a user or a malicious user can load an unsigned kernel, so to avoid that we added the support of the secure warm boot.
More Description about this feature can be found in the Secure Boot HLD: https://github.com/sonic-net/SONiC/pull/1028
In general, Linux support it, so I enabled this support by doing the follow steps:
1. I added some special flags in Linux Kernel when user build the sonic-buildimage with secure boot feature enabled.
2. I added a flag "-s" to the kexec command
Note: more details in the HLD above.
- Good flow …
> Add support of secure warm-boot

- config/vlan.py
- tests/vlan_test.py
Cherry-pick of this PR: https://github.com/sonic-net/sonic-utilities/pull/2678
> [202211][dhcp_relay] Remove add field of vlanid to DHCP_RELAY table while adding vlan

- config/vlan.py
- tests/vlan_test.py
Remove add field of vlanid to DHCP_RELAY table while add vlan which would cause conflict with yang model.
Remove add field of vlanid to DHCP_RELAY table while add vlan
```
2023-02-15T14:25:22.1711670Z ============================= test session starts ==============================
2023-02-15T14:25:22.1712734Z platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
2023-02-15T14:25:22.1713066Z cachedir: .pytest_cache
2023-02-15T14:25:22.1713331Z rootdir: /__w/1/s, configfile: pytest.ini
2023-02-15T14:25:22.1713766Z plugins: pyfakefs-5.1.0, cov-2.10.1
2023-02-15T14:25:32.4827379Z collecting ... collected 2183 items
2023-02-15T14:25:32.4827959Z 
2023-02-15T14:33:42.4732391Z tests/vlan_test.py::TestVlan::test_show_vlan PASSED                      [ 72%] …
```
> [dhcp_relay] Remove add field of vlanid to DHCP_RELAY table while add vlan

- config/dhcp_relay.py
- config/vlan.py
- tests/config_dhcp_relay_test.py
- tests/vlan_test.py
Remove add field of vlanid to DHCP_RELAY table while add vlan which would cause conflict with yang model.
Remove add field of vlanid to DHCP_RELAY table while add vlan
```
2023-02-16T02:09:35.8928219Z ============================= test session starts ==============================
2023-02-16T02:09:35.8933715Z platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
2023-02-16T02:09:35.8938378Z rootdir: /__w/1/s, inifile: pytest.ini
2023-02-16T02:09:35.8939079Z plugins: pyfakefs-5.1.0, cov-2.6.0
2023-02-16T02:09:40.5576217Z collected 961 items
2023-02-16T02:09:40.5615053Z 
2023-02-16T02:09:53.1351705Z tests/config_dhcp_relay_test.py ....................                     [ 10%]
2023-02-16T02:13:07.5436089Z tests/vlan_test.py ............................................ …
```
> [202012][vlan] Remove add field of vlanid to DHCP_RELAY table while adding vlan

- show/main.py
- sonic-utilities-tests/show_test.py
Backport https://github.com/sonic-net/sonic-utilities/pull/2537
Add bgpraw output to `show runningconfiguration all`
Generate bgpraw output then append it to `show runnningconfiguration all`'s output
Unittest and manual test on 201911 image.
> [201911][show] Add bgpraw to show run all

- show/main.py
Backport https://github.com/sonic-net/sonic-utilities/pull/2537
Add bgpraw output to `show runningconfiguration all`
Generate bgpraw output then append it to `show runnningconfiguration all`'s output
There is not unit test support on such old version.
Manually test on 201811 image.
> [201811][show] Add bgpraw to show run all

- config/vlan.py
- tests/vlan_test.py
Cherry-pick of this PR: https://github.com/sonic-net/sonic-utilities/pull/2678
> [202205][dhcp_relay] Remove add field of vlanid to DHCP_RELAY table while adding vlan

- doc/Command-Reference.md
- show/muxcable.py
- tests/muxcable_test.py
This PR adds the support for adding some utility commands for muxacble
This includes commands for health, operationtime, queueinfo, resetcause
```
vdahiya@sonic:~$ show mux health Ethernet4 
PORT          ATTR               HEALTH
---------     ---------------   --------
Ethernet4     health_check       Ok
vdahiya@sonic:~$ show mux health Ethernet4 --json
{
"health_check": "Ok"
}
vdahiya@sonic:~$ show mux operation Ethernet4 --json
{
"operation_time": "22:22"
}
vdahiya@sonic:~$ show mux operation Ethernet4
PORT       ATTR              OPERATION_TIME
---------  --------------  ----------------
Ethernet4  operation_time                 22:22
vdahiya@sonic:~$ 
vdahiya@sonic:~$ show mux resetcause Ethernet4
PORT       ATTR           RESETCAUSE
---------  -----------  ------------
Ethernet4 …
```
> [show][muxcable] add some new commands health, reset-cause, queue_info support for muxcable

- config/main.py
- scripts/fast-reboot
Add more logs for config reload/config minigraph/warm-reboot/fast/reboot to identify in the log (notice level) what was the command executed which could cause a service affect.
Add more logs for config reload/config minigraph/warm-reboot/fast/reboot. 
Manual test
> Add begin logs to config reload/config minigraph/warm-reboot/fast-reboot

- tests/generic_config_updater/files/feature_patch_application_test_failure.json
- tests/generic_config_updater/files/feature_patch_application_test_success.json
- tests/generic_config_updater/gcu_feature_patch_application_test.py
Add Sample Unit Test for RDMA Headroom Pool Size Tuning 
Set up template for future feature unit test development
Template includes:
- `feature_patch_application_test_failure.json` to define expected failure scenarios for patch application to feature under test
- `feature_patch_application_test_success.json` to define expected success scenarios for patch application to feature under test
- `gcu_feature_patch_application_test.py` test file to go through all test scenarios defined in the above two files
Run unit tests
> [GCU] Add Sample Unit Test for RDMA Headroom Pool Size Tuning

- config/vlan.py
- tests/conftest.py
- tests/vlan_test.py
In device that doesn't have dhcp_relay service, restart dhcp_relay after add/del vlan would encounter failed
Add support to check whether device is support dhcp_relay service.
1. Unit test
```
tests/vlan_test.py::TestVlan::test_show_vlan PASSED                      [ 71%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief PASSED                [ 71%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief_verbose PASSED        [ 71%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief_in_alias_mode PASSED  [ 71%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief_explicit_proxy_arp_disable PASSED [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_config PASSED               [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_config_in_alias_mode PASSED [ 72%] …
```
> [dhcp_relay] Fix dhcp_relay restart error while add/del vlan

- doc/Command-Reference.md
- show/muxcable.py
- tests/muxcable_test.py
raising this because cherry-pick failed for 202012
master branch PR https://github.com/sonic-net/sonic-utilities/pull/2414
This PR adds the support for adding some utility commands for muxacble This includes commands for health, operationtime, queueinfo, resetcause
```
vdahiya@sonic:~$ show mux health Ethernet4
PORT          ATTR               HEALTH
---------     ---------------   --------
Ethernet4     health_check       Ok
vdahiya@sonic:~$ show mux health Ethernet4 --json
{
"health_check": "Ok"
}
vdahiya@sonic:~$ show mux operation Ethernet4 --json {
"operation_time": "22:22"
}
vdahiya@sonic:~$ show mux operation Ethernet4
PORT       ATTR              OPERATION_TIME
---------  --------------  ----------------
Ethernet4  operation_time                 22:22
vdahiya@sonic:~$ …
```
> [show][muxcable] add some new commands health, reset-cause, queue_info support for muxcable 

- scripts/db_migrator.py
- tests/db_migrator_input/appl_db/routes_migrate_expected.json
- tests/db_migrator_input/appl_db/routes_migrate_input.json
- tests/db_migrator_input/config_db/routes_migrate_input.json
- tests/db_migrator_test.py
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/12625
Check for missing attribute `weight` in APPLDB route entries. If found missing this attribute is added with empty value.
Verified on physical device. 201911 to 202205 upgrade worked fine.
> [db_migrator] Add missing attribute 'weight' to route entries in APPL DB

- scripts/fast-reboot
Goal: Preserve logs during TOR upgrades and shutdown
Need:
Below PRs moved logs from disk to tmpfs for specific hwskus.
Due to these changes, shutdown path logs are now lost.
The logs in shutdown path are crucial for debug purposes.
https://github.com/sonic-net/sonic-buildimage/pull/13805
https://github.com/sonic-net/sonic-buildimage/pull/13587
https://github.com/sonic-net/sonic-buildimage/pull/13587
Check if logs are on tmpfs. If yes, backup logs from /var/log 
Verified on a physical device
> [warm/fast-reboot] Backup logs from tmpfs to disk during fast/warm shutdown

- scripts/fast-reboot
Warm-reboot fails on kvm due to non-zero exit upon command 
`bootctl status 2>/dev/null | grep -c "Secure Boot: enabled"` 
Added `|| true` to return 0 when previous command fails.
Added `CHECK_SECURE_UPGRADE_ENABLED` to check output of previous command
Added debug logs
Run warm-reboot on kvm and physical device when increased verbosity. Expects debug log to indicate secure/non secure boot. Successful warm reboot
> Fix non-zero status exit on non secure boot system

- show/muxcable.py
probe mux direction not always return success.
Sample output of: while [ 1 ]; do date; show mux hwmode muxdirection; show mux status; sleep 1; done
```
Mon 27 Feb 2023 03:12:25 PM UTC
Port         Direction    Presence
-----------  -----------  ----------
Ethernet16   unknown      True
PORT         STATUS    HEALTH    HWSTATUS      LAST_SWITCHOVER_TIME
-----------  --------  --------  ------------  ---------------------------
Ethernet16   standby   healthy   inconsistent  2023-Feb-25 07:55:18.269177
```
If we increase the timeout to 0.5 secs to get the values back from ycabled, this will remove the inconsistency issue, and display the consistent values, because while telemetry is going on, the time to get actual mux value takes significantly longer than 0.1 seconds. 
```
PORT …
```
> [show][muxcable] increase timeout for displaying HW_STATUS

- scripts/fast-reboot
Give platform chance to do proper cleanup before shutting down swss in warm/fast-reboot by calling a platform-provided script
update fast-reboot script.
execute fast-reboot/warm-reboot
> execute a platform-provided pre-reboot script before shutting down swss

- config/vlan.py
- tests/conftest.py
- tests/vlan_test.py
Cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-utilities/pull/2688
In device that doesn't have dhcp_relay service, restart dhcp_relay after add/del vlan would encounter failed
Add support to check whether device is support dhcp_relay service.
1. Unit test
2. Build and install in device
> [202012][dhcp_relay] Fix dhcp_relay restart error while add/del vlan (#2688)

- config/vlan.py
- tests/conftest.py
- tests/vlan_test.py
Cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-utilities/pull/2688
In device that doesn't have dhcp_relay service, restart dhcp_relay after add/del vlan would encounter failed
Add support to check whether device is support dhcp_relay service.
1. Unit test
2. Build and install in device
> [202205][dhcp_relay] Fix dhcp_relay restart error while add/del vlan (#2688)

- acl_loader/main.py
- tests/aclshow_test.py
- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/asic0/state_db.json
- tests/mock_tables/asic2/config_db.json
- tests/mock_tables/asic2/state_db.json
- tests/mock_tables/config_db.json
- tests/mock_tables/state_db.json
- tests/show_acl_test.py
HLD https://github.com/sonic-net/SONiC/pull/1261
This PR is to enhance `show acl table` and `show acl rule` commands.
Currently, `show acl table` and `show acl rule` commands read ACL table/rule configuration from `CONFIG_DB` directly. We don't know whether the ACL table or rule is created successfully.
We improved `swss` to write the status of ACL table/rule into a `STATE_DB` table. In this PR, the show command is enhanced to read the status from `STATE_DB` table.
1. Introduce two tables in `STATE_DB`
2. `orchgent` writes the status to `STATE_DB`
3. show commands read the status from `STATE_DB`.
Verified by copying the new script to a testbed, and check the output.
```
$ show acl table DATAACL
Name     Type    Binding      Description    Stage     
-------  ------  ----------- …
```
> Improve show acl commands

- setup.py
SONiC related packages shouldn't be intalled from Pypi.
It is security compliance requirement.
Check SONiC related packages when using setup.py.
> Check SONiC dependencies before installation.

- scripts/route_check.py
- tests/route_check_test_data.py
In case user has configured an IPv6 address on an interface in CONFIG DB in non simplified form like 2000:31:0:0::1/64 it is present in a simplified form in ASIC_DB. This leads to route_check failure since it just compares strings.
Convert prefix string using ip_network().
UT replicates the issue.
> [route_check] fix IPv6 address handling

- config/main.py
- tests/config_test.py
This is an enhancement of PR #2503
1. On top of waiting for `BUFFER_POOL_TABLE` to be cleared from `APPL_DB`, we need to wait for `KEY_SET` and `DEL_SET` as well.
`KEY_SET` and `DEL_SET` are designed to accommodate the `APPL_DB` entries that were updated by manager daemons but have not yet been handled by the orchagent.
In this case, even if the buffer tables are empty, entries in `KEY_SET` or `DEL_SET` will be in the buffer tables later on. So, we need to wait for key set tables as well.
2. Do not delay for traditional buffer manager because it does not remove any buffer table.
3. Provide a CLI option to print the detailed message if there is any table item which still exists
Manually test and unit test
```
Running command: …
```
> Enhance the logic to wait for all buffer tables to be removed in _clear_qos

- scripts/db_migrator.py
Fix DB migrator logic for migrating fast-reboot table, fixing https://github.com/sonic-net/sonic-utilities/pull/2724 db_migrator.
Checking if fast-reboot table exists in DB.
Verified manually, migrating after fast-reboot and after cold/warm reboot.
> [202205] Fix fast-reboot DB migration

- scripts/db_migrator.py
Fix DB migrator logic for migrating fast-reboot table, fixing https://github.com/sonic-net/sonic-utilities/pull/2621 db_migrator.
Checking if fast-reboot table exists in DB.
Verified manually, migrating after fast-reboot and after cold/warm reboot.
> Fix fast-reboot DB migration

- doc/Command-Reference.md
show vlan brief will only be showing dhcpv4 addresses and not dhcpv6 destination
> Update the ref guide to reflect the vlan brief output

- scripts/generate_dump
1. [34428157](https://github.com/sonic-net/sonic-utilities/commit/34428157116256c04cbd54d7ce0b1fd7c010f7ea) Revert "Optimize the execution time of the 'show techsupport' script to 5-10%"
2. [c3bd01f6](https://github.com/sonic-net/sonic-utilities/commit/c3bd01f680bb65668c96b9a17a7ce9645066102c) Revert "[generate_dump] Optimize the execution time of 'show techsupport' CLI by parallel function execution"
3. Add a fix for the empty `/dump` folder inside the final tar archive generated by the `show techsupport` CLI command.
4. Add a fix to not follow the symbolic links to avoid duplicate files inside the final tar archive generated by the `show techsupport` CLI command.
Modify the `scripts/generate_dump` script.
1. Manual verification
- do the `show techsupport` CLI command and save output …
> [202211][generate_dump] Revert "Revert generate_dump optimization PR's", add fixes for empty /dump forder and symbolic links

- scripts/generate_dump
1. Revert [[202205] Revert the show-techsupport optimization PR's #2581](https://github.com/sonic-net/sonic-utilities/pull/2581)
2. Add a fix for the empty `/dump` folder inside the final tar archive generated by the `show techsupport` CLI command.
3. Add a fix to not follow the symbolic links to avoid duplicate files inside the final tar archive generated by the `show techsupport` CLI command.
Modify the `scripts/generate_dump` script.
1. Manual verification
- do the `show techsupport` CLI command and save output `original.tar.gz` (with original `generate_dump` script)
- do the `show techsupport` CLI command and save output `fixes.tar.gz` (with the `generate_dump` script modified by this PR)
- unpack both archives `original.tar.gz` and `fixes.tar.gz`
- compare both directories with …
> [202205][generate_dump] Revert "Revert generate_dump optimization PR's #2581", add fixes for empty /dump forder and symbolic links

- config/main.py
- tests/config_test.py
Reverts sonic-net/sonic-utilities#2235
This change is no longer needed. Addressed by sonic-net/sonic-buildimage#14229
> Revert "[202012] Update load minigraph to load backend acl"

- config/main.py
- tests/config_test.py
Reverts sonic-net/sonic-utilities#2236
This change is no longer needed. Will be addressed by sonic-net/sonic-buildimage#14229
> Revert "Update load minigraph to load backend acl"

- scripts/portstat
What/Why I did:
Fix the `show interface counters` throwing exception
issue where device do not have any external ports and all are internal links (ethernet or fabric) which is possible in chassis
```
show interface counters
File "/usr/local/bin/portstat", line 643, in <module>
main()
File "/usr/local/bin/portstat", line 634, in main
portstat.cnstat_print(cnstat_dict, ratestat_dict, intf_list, use_json, print_all, errors_only, rates_only, detail)
File "/usr/local/bin/portstat", line 326, in cnstat_print
print(tabulate(table, header, tablefmt='simple', stralign='right'))
File "/usr/local/lib/python3.9/dist-packages/tabulate.py", line 1246, in tabulate
list_of_lists, headers = _normalize_tabular_data(
File …
```
> Fix the `show interface counters` throwing exception on device with no external interfaces

- scripts/dropstat
- scripts/flow_counters_stat
- scripts/intfstat
- scripts/pfcstat
- scripts/pg-drop
- scripts/portstat
- scripts/queuestat
- scripts/tunnelstat
This reverts commit 54e26359fccf45d2e40800cf5598a725798634cd.
Due to https://github.com/sonic-net/sonic-buildimage/issues/14089
> Revert "Replace pickle by json (#2636)"

- scripts/fast-reboot
- scripts/fast-reboot-filter-routes.py
- setup.py
Added a script to filter routes: preserve default routes (was already done as part of fast-reboot script) and connected routes.
Set teamd timer to minimal allowed value (1 second) for fast-reboot.
Both made in order to shorten dataplane downtime.
fast-reboot-filter-routes.py was added to preserve connected and default routes and is being called from fast-reboot script.
teamd-timer is set when setting fast-reboot.
Community fast-reboot test.
> [202205] Fast-reboot: preserve connected routes and set teamd timer to minimum.

- acl_loader/main.py
- tests/aclshow_test.py
- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/asic0/state_db.json
- tests/mock_tables/asic2/config_db.json
- tests/mock_tables/asic2/state_db.json
- tests/mock_tables/config_db.json
- tests/mock_tables/state_db.json
- tests/show_acl_test.py
This PR is to backport changes in PR #2667 into `202211` branch.
HLD https://github.com/sonic-net/SONiC/pull/1261
This PR is to enhance `show acl table` and `show acl rule` commands.
Currently, `show acl table` and `show acl rule` commands read ACL table/rule configuration from `CONFIG_DB` directly. We don't know whether the ACL table or rule is created successfully.
We improved `swss` to write the status of ACL table/rule into a `STATE_DB` table. In this PR, the show command is enhanced to read the status from `STATE_DB` table.
1. Introduce two tables in `STATE_DB`
2. `orchgent` writes the status to `STATE_DB`
3. show commands read the status from `STATE_DB`.
Verified by copying the new script to a testbed, and check the output.
```
$ show acl table DATAACL
Name     Type    Binding …
```
> [202211] [cherry-pick] Add status for ACL_TABLE and ACL_RULE in STATE_DB

- scripts/generate_dump
…ing to get only v4 peers in case of show ip bgp neighbors
Resolved Techsupport failure upon generate_dump (techsupport gives rc = 1) execution for 'show bgp ipv6 neighbors' and 'show ip bgp neighbors' cli.
fgrep returned non 0 RC in case bgp neighbors are not configured or link down/config abscent on peer etc. This results in script failure. So, I replaced fgrep with awk. This returns rc = 0 even when we dont have any results in filter.
In case of ipv4 (show ip bgp neighbors), it is observed that cli also gives v6 peers. Consequently neighbor_list_v4 has v4 and v6 peers. This generates 2 sets of files in techsupport (1 set for v4 and other for v6). however v6 neighbors do not have routes and are empty files. So I added extra filtering here using awk and neighbor_list_v4 will only have v4 …
> Fixed techsupport failure in generate_dump 'show bgp neighbors' 

- scripts/route_check.py
- tests/mock_tables/config_db.json
- tests/route_check_test.py
- tests/route_check_test_data.py
revert below PRs to unblock sonic-utilities submodule advance.
https://github.com/sonic-net/sonic-utilities/pull/2732
https://github.com/sonic-net/sonic-utilities/pull/2722
https://github.com/sonic-net/sonic-utilities/pull/2531
> Revert frr route check

- generic_config_updater/services_validator.py
Fix the bug in vlanintf_validator
ret will be 0 if success. Fix the statement.
E2E test
> [GCU]Fix bug in GCU vlanintf_validator

- config/validated_config_db_connector.py
- generic_config_updater/generic_updater.py
- tests/generic_config_updater/generic_updater_test.py
Make patch sorting optional. 
**Why:** In some cases, patch sorting is unnecessary, as the patch doesn't have dependencies on other tables, and the patch is already in an order that can directly be applied to ConfigDB. A specific example is when GCU is used for YANG validation of direct writes to ConfigDB via `set_entry` or `mod_entry`. In these scenarios, we can directly apply each element in the JsonPatch without need for additional sorting
This allows for a performance improvement of ~40%. 
Sample command to add portchannel including unnecessary patch sorting: 
```
admin@sonic:~$ sudo config portchannel add PortChannel09
Patch Applier: Patch: [{"op": "add", "path": "/PORTCHANNEL/PortChannel09", "value": {}}, {"op": "add", "path": …
```
> [GCU] Performance improvement by making patch sorting optional

- utilities_common/multi_asic.py
The get_ns_list_based_on_options function only gets front_ns and back_ns in current code. 
This change adds fabric_ns in the ns_list when display_option is DISPLAY_ALL. This enables the fabric related tests on voq chassis,  e.g  the change in https://github.com/sonic-net/sonic-mgmt/pull/6620/
> Add fabric_ns to the ns_list when display_option is DISPLAY_ALL.

- azure-pipelines.yml
Switch to using regular swss-common artifacts
The swss-common pipeline is now built for Bullseye.
> [ci] Switch to using regular swss-common artifacts

- sfputil/main.py
Pass UT
Manual test
```
admin@str-s6000-acs-12:~$ sudo sfputil show error-status -hw
Port         Error Status
-----------  --------------
Ethernet0
Ethernet4    OK
Ethernet8    OK
Ethernet12   OK
Ethernet16   OK
Ethernet20   OK
Ethernet24   OK
Ethernet28   OK
```
> [sfputil] replace shell=True

- azure-pipelines.yml
Make sure that the sonic-swss-common artifacts that get pulled are pulled from the matching branch (master branch artifacts for master branch, 202205 branch for 202205, etc.).
> Use sonic-swss-common artifacts from the matching source branch

- config/aaa.py
- tests/radius_test.py
fixes https://github.com/sonic-net/sonic-buildimage/issues/14356
fix radius command python config file for commands that fails with tracebacks due to NameError: name 'unicode' is not define
delete any unicode from python config file
run the two radius commands:
```
config radius nasip 1.1.1.1
config radius sourceip 2000::1
```
and check show radius output
```
show radius
```
```
root@qa-eth-vt03-1-4600ca1:/home/admin# config radius nasip 1.1.1.1
File "/usr/local/bin/config", line 8, in
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in call
File …
```
> fix radius error on unicode name error due to python3

- scripts/generate_dump
Signed-off-by: Sakthivadivu Saravanaraj <sakthivadivu.saravanaraj@nokia.com>
When we run generate_dump script in SFM cards in a Broadcom chassis, the errors were printed in syslog for all the Broadcom commands which are not supported in fabric/Ramon cards. Added a check to dump all l2, l3, fp and tm commands only if the switch_type is non fabric card since these commands are not valid for fabric cards.
Get the switch_type from DEVICE_METADATA and check the switch_type before dumping these BCM commands. 
Ran generate_dump script in both voq  and fabric cards,  (1)verified that the fabric cards don't log the errors for the BCM commands (2) verified that the commands are dumped correctly in non-fabric dnx cards.
> [generate_dump] [BCM] Dump only the relevant BCM commands for fabric cards

- show/main.py
- tests/show_test.py
Support to display the SONiC OS Version in the command show version.
It will be used to display the version info in the SONiC command "show version". The version is used to do the FIPS certification. We do not do the FIPS certification on a specific release, but on the SONiC OS Version.
```
SONiC Software Version: SONiC.master-13812.218661-7d94c0c28
SONiC OS Version: 11
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
```
The device info is in sonic-net/sonic-buildimage, see PR: https://github.com/sonic-net/sonic-buildimage/pull/14601
The submodule change can be merged to sonic-buildimage, after the PR 14601 merged.
> Support to display the SONiC OS Version in the command show version

- scripts/db_migrator.py
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-input.json
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-output.json
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-same-cable-input.json
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-same-cable-output.json
- tests/db_migrator_test.py
Updated dbmigrator to support warm upgrade to new buffer config for EdgeZoneAggregator neighbors.
Created a new version checkpoint for the change and made appropriate changes to the ConfigDB.
Unit tests pass and tested on lab device
> [202211][DBMigrator] Update db_migrator to support EdgeZoneAggregator Buffer Config for T0s

- show/main.py
Remove the additional new line in the command show version, the new line character is no use.
```
SONiC Software Version: SONiC.master-14619.252155-d7c9d3b7d
SONiC OS Version: 11
Distribution: Debian 11.6
```
Change to:
```
SONiC Software Version: SONiC.master-14619.252155-d7c9d3b7d
SONiC OS Version: 11
Distribution: Debian 11.6
```
> Remove the additional new line in the command show version

- config/aaa.py
- tests/radius_test.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/14356
This PR is based on https://github.com/sonic-net/sonic-utilities/pull/2751
fix radius command python config file for commands that fails with tracebacks due to NameError: name 'unicode' is not define
delete any unicode from python config file
run the two radius commands:
```
config radius nasip 1.1.1.1
config radius sourceip 2000::1
```
and check show radius output
`
show radius
`
```
root@qa-eth-vt03-1-4600ca1:/home/admin# config radius nasip 1.1.1.1
File "/usr/local/bin/config", line 8, in
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in call
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, …
```
> [202211] fix radius error on unicode name error due to python3

- scripts/fast-reboot
- scripts/fast-reboot-filter-routes.py
- setup.py
Part of https://github.com/sonic-net/sonic-buildimage/pull/14583
Similar to https://github.com/sonic-net/sonic-utilities/pull/2744
Added a script to filter routes: preserve default routes (was already done as part of fast-reboot script) and connected routes.
Set teamd timer to minimal allowed value (1 second) for fast-reboot.
Both made in order to shorten dataplane downtime.
fast-reboot-filter-routes.py was added to preserve connected and default routes and is being called from fast-reboot script.
teamd-timer is set when setting fast-reboot.
> Fast-reboot: set teamd timer to minimum, preserve connected routes

- scripts/route_check.py
- tests/route_check_test_data.py
BACKPORT of https://github.com/sonic-net/sonic-utilities/pull/2722
In case user has configured an IPv6 address on an interface in CONFIG DB in non simplified form like 2000:31:0:0::1/64 it is present in a simplified form in ASIC_DB. This leads to route_check failure since it just compares strings.
Convert prefix string using ip_network().
UT replicates the issue.
> [202205][route_check] fix IPv6 address handling

- fwutil/lib.py
- tests/fwutil_test.py
Signed-off-by: maipbui <maibui@microsoft.com>
Pass UT
Manual test
> [fwutil] replace shell=True

- acl_loader/main.py
- tests/acl_input/acl1.json
- tests/acl_loader_test.py
- tests/aclshow_test.py
- tests/mock_tables/config_db.json
1. Update `acl-loader` to only add default deny rule when table is L3 or L3V6.
2. Update unittest to cover it.
Update function `deny_rule` and return `{}` if table is not L3 or L3V6.
1. Update unittest and run all testcases to verify:
```
----------- coverage: platform linux, python 3.9.2-final-0 -----------
Name                                                   Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------------------------
acl_loader/__init__.py                                     0      0      0      0   100%
acl_loader/main.py                                       640    152    284     50    71%  ...
=================================================================== short test summary info …
```
> [acl-loader] Only add default deny rule when table is L3 or L3V6

- scripts/route_check.py
- tests/route_check_test_data.py
BACKPORT of https://github.com/sonic-net/sonic-utilities/pull/2722
In case user has configured an IPv6 address on an interface in CONFIG DB in non simplified form like 2000:31:0:0::1/64 it is present in a simplified form in ASIC_DB. This leads to route_check failure since it just compares strings.
Convert prefix string using ip_network().
UT replicates the issue.
> [202211][route_check] fix IPv6 address handling 

- sonic_package_manager/service_creator/creator.py
- tests/sonic_package_manager/test_service_creator.py
> [sonic_package_manager] replace shell=True

- show/plugins/barefoot.py
- tests/show_barefoot_test.py
Signed-off-by: maipbui <maibui@microsoft.com>
> [show][barefoot] replace shell=True

- config/main.py
- tests/config_dpb_test.py
Fixed typo in config breakout output. Fixed dependecies to dependencies
Fixed typo
Modified UT to align
> [DPB]Fixing typo in config breakout output

- scripts/db_migrator.py
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-input.json
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-output.json
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-same-cable-input.json
- tests/db_migrator_input/config_db/sample-t0-edgezoneagg-config-same-cable-output.json
- tests/db_migrator_test.py
Updated dbmigrator to support warm upgrade to new buffer config for EdgeZoneAggregator neighbors.
Created a new version checkpoint for the change and made appropriate changes to the ConfigDB.
Unit tests pass and tested on lab device
> [202205][DBMigrator] Update db_migrator to support EdgeZoneAggregator Buffer Config for T0s

- show/muxcable.py
`show mux hwmode muxdirection` always has `rc==1`. 
Fixed the issue below:
* `get_grpc_cached_version_mux_direction_per_port` has reverted `TRUE/FALSE` return value compared to `get_hwmode_mux_direction_port`. The former is used to get results for `active-active` ports, the latter is used to get results for `active-standby` ports.
* Use `sys.exit()` instead of `return rc`. CLI rc is different from function return value. 
* Fixed `show mux grpc muxdirection` as well. 
sign-off: Jing Zhang 
* Tested on DUTs to verify rc. Run commands for single port and all ports, with and without `--json`.
* Passed all UTs.
> [show][muxcable] fix `show mux hwmode muxdirection` RC

- sonic_package_manager/manager.py
- sonic_package_manager/manifest.py
- tests/sonic_package_manager/test_manager.py
Use case for some application extensions we develop is to have multiple features as part of a single container. Therefore we want to have ability to install multiple CLI plugins from a single extension.
Allowed to specify few CLI plugins in the manifest.
Build extension with multiple CLI plugins and install. Verified all plugins are installed.
> [sonic-package-manager] add support for multiple CLI plugin files

- config/main.py
- tests/config_test.py
Missing platform and mac in CONFIG_DB will result in container failure. We should make the `config reload` generate those info if missing.
Add missing sys info if config_db.json doesn't contain it.
Unit test
> [config]config reload should generate sysinfo if missing

- generic_config_updater/field_operation_validators.py
`if substring.isdigit() and re.match(r'^\d{8}$', substring):` In this version check, it only applies to this pattern: 20220531.XXX. It will fail the master and other build check. For example, `master.261851-010dc3957` is a master build_version string. It will fail version validation and return failure.
My thought to remove the check is that GCU is only supported in 202205 and later. Either `branch_version >= "20201200"` or `branch_version >= "20181100"` is already satisfied.
Remove redundant check in GCU RDMA validator
Unit test
> [GCU] fix rdma check failure

- acl_loader/main.py
- tests/acl_input/acl1.json
- tests/acl_loader_test.py
- tests/aclshow_test.py
- tests/mock_tables/config_db.json
Backport #2796 to 202205 branch.
**What I did**
1. Update acl-loader to only add default deny rule when table is L3 or L3V6.
2. Update unittest to cover it.
**How I did it**
Update function deny_rule and return {} if table is not L3 or L3V6.
1. Update unittest and run all testcases to verify.
2. Built the package and installed on DUT to verify.
Unittest results on 202205 branch:
```
tests/acl_loader_test.py::TestAclLoader::test_acl_empty PASSED                                                                [  0%]
tests/acl_loader_test.py::TestAclLoader::test_valid PASSED                                                                    [  0%]
tests/acl_loader_test.py::TestAclLoader::test_invalid PASSED …
```
> [Backport-202205][acl-loader] Only add default deny rule when table is L3 or L3V6 (#2796)

- config/vlan.py
- tests/vlan_test.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/14231
- When enabling proxy_arp for a VLAN, configure and start the ndppd service if it isn't already running
- When removing the last VLAN, stop the ndppd service
Check `supervisorctl status ndppd` to determine if ndppd needs to be started or stopped
- Load a config on a device that does not have any VLANs
- Create a vlan and enable proxy_arp:
```
sudo config vlan add 10
sudo config interface ip add Vlan10 4.0.0.2/24
sudo config vlan proxy_arp 10 enabled
```
- Verify that the commands succeed and ndppd is running:
```
admin@sonic:~$ docker exec -it swss supervisorctl status ndppd
ndppd                            RUNNING   pid 1744, uptime 0:00:03
```
- Remove the vlan:
```
sudo config interface ip remove Vlan10 4.0.0.2/24
sudo …
```
> [config]: Dynamically start and stop ndppd

- scripts/fast-reboot
- scripts/lag_keepalive.py
- setup.py
A new mechanism is added here to to reduce LAG flap issue during hitless upgrades.
During warm upgrades T0 goes down and with that wait time for LACP session starts.
If the waittime to refresh LACP session is > 90s then T1 initiates LAG teardown, and as a result dataplane impact is seen.
This script makes sure that LACPDUs are sent in the going down path continuously.
How time is saved w/ this mechanism:
The lacpsession wait period earlier used to start from when teamd container goes down.
New lacpsession wait period starts when kexec in current kernel is issued, and new kernel boots up.
When warm-reboot starts, capture LACPDUs sent from all LAG member ports.
For this allow 60s of prep + collection time.
Start sending LACPDUs w/ ~1s interval.
The last LACPDU is sent after all containers …
> LAG keepalive script to reduce lacp session wait during warm-reboot

- scripts/route_check.py
**Description:**
In our lab environment, 
cisco sonic router will hit below error message from route_check
Apr 27 10:51:07.253041 str3-8101-02 ERR monit[519]: 'routeCheck' status failed (255) – 
Failure results: #012    "Unaccounted_ROUTE_ENTRY_TABLE_entries": #012       &quot;fddd:a150:a0::a66:1/128&quot;,#012        &quot;fddd:a150:a0::a67:1/128&quot;,#012       &quot;fddd:a150:a0::a71:1/128&quot;,#012        &quot;fddd:a150:a0::a78:1/128&quot;,#012        &quot;fddd:a150:a0::a80:1/128&quot;#012    
#012#012Failed. Look at reported mismatches above#012add: []#012del: []
**Steps to reproduce the issue:**
run the testcase "vxlan/test_vxlan_ecmp.py" on T1 testbed.
issue is reported from 4202:C48-MSFT: vxlan/test_vxlan_ecmp.py
**Describe the results you expected:**
testcase should not dump …
> [route_check] incorrectly parsing complete ipv6 vnet info

- setup.py
Fix SONiC image compilation issue:
```
[2023-05-03T17:54:00.146Z] + sudo cp files/build_templates/docker_image_ctl.j2 ./fs********-mellanox/usr/share/sonic/templates/docker_image_ctl.j2
[2023-05-03T17:54:00.146Z] + sudo LANG=C DOCKER_HOST= ch******** ./fs********-mellanox /usr/local/bin/generate_shutdown_order.py
[2023-05-03T17:54:00.146Z] Traceback (most recent call last):
[2023-05-03T17:54:00.146Z]   File "/usr/local/lib/python3.9/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
[2023-05-03T17:54:00.146Z]     return self.version(api_version=False)["ApiVersion"]
[2023-05-03T17:54:00.147Z]   File "/usr/local/lib/python3.9/dist-packages/docker/api/daemon.py", line 181, in version
[2023-05-03T17:54:00.147Z]     return self._result(self._get(url), json=True) …
```
> [build] Fix base OS compilation issue caused by incompatibility of urllib with requests.

- config/main.py
- tests/config_test.py
- tests/load_minigraph_input/platform/plugins/platform_mg_post_check
- tests/load_minigraph_input/platform_false/plugins/platform_mg_post_check
Double commit (#2808 )
Signed-off-by: anamehra anamehra@cisco.com
Added platform plugin hook to execute platform script after minigraph config is loaded in config db and before starting the services.
For the phy-based platforms, changing the port speed via minigraoh, e.g. 400G to 100G, also requires gearbox/phy config files to be modified in hwsku directory. Current gearbox config change is not supported by config db or minigraph and that causes a mismatch in speed configuration between config db and gearbox config. To handle this scenario, a platform plugin is added which could do the gearbox config modifications as required based on the minigraph config.
Call platform plugin script, if present, before starting the services
Add a platform plugin script, platform_mg_post_check  in …
> Added platform plugin support in load_minigraph (#2808)

- scripts/fast-reboot
- scripts/lag_keepalive.py
- setup.py
Cherry pick of https://github.com/sonic-net/sonic-utilities/pull/2806 for 202012 branch
A new mechanism is added here to to reduce LAG flap issue during hitless upgrades.
During warm upgrades T0 goes down and with that wait time for LACP session starts.
If the waittime to refresh LACP session is > 90s then T1 initiates LAG teardown, and as a result dataplane impact is seen.
This script makes sure that LACPDUs are sent in the going down path continuously.
How time is saved w/ this mechanism:
The lacpsession wait period earlier used to start from when teamd container goes down.
New lacpsession wait period starts when kexec in current kernel is issued, and new kernel boots up.
When warm-reboot starts, capture LACPDUs sent from all LAG member ports.
For this allow 60s of prep + collection …
> [202012] LAG keepalive script to reduce lacp session wait during warm-reboot

- scripts/sonic_sku_create.py
- tests/sku_create_input/2700_files/config_db_incorrect_platform.json
- tests/sku_create_input/2700_files/config_db_invalid_portname.json
- tests/sku_create_test.py
`sys.exit` is better than `exit`, considered good to use in production code.
Ref:
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python
https://stackoverflow.com/questions/19747371/python-exit-commands-why-so-many-and-when-should-each-be-used
Replace `exit()` by `sys.exit()`
Add UT
> [sonic_sku_create] remove shell=True, replace exit() with sys.exit()

- show/plugins/mlnx.py
- tests/show_mlnx_test.py
Signed-off-by: maipbui <maibui@microsoft.com>
Add UT
Manual test
```
admin@***:~$ show platform mlnx issu
ISSU is enabled
admin@***:~$ show platform mlnx sniffer
sdk sniffer is disabled
```
> [show][mlnx] replace shell=True, replace xml

- scripts/fast-reboot
Backport of https://github.com/sonic-net/sonic-utilities/pull/2532 and https://github.com/sonic-net/sonic-utilities/pull/2715
Add support of secure warm-boot to SONiC.
Basically, warm-boot is supporting to load a new kernel without doing full/cold boot.
That is by loading a new kernel and exec with kexec Linux command. As a result of that, even when the Secure Boot feature is enabled, still a user or a malicious user can load an unsigned kernel, so to avoid that we added the support of the secure warm boot.
More Description about this feature can be found in the Secure Boot HLD: https://github.com/sonic-net/SONiC/pull/1028
In general, Linux support it, so I enabled this support by doing the follow steps:
I added some special flags in Linux Kernel when user build the sonic-buildimage with …
> [202211] Add support of secure warm-boot backport

- config/config_mgmt.py
- config/main.py
- tests/config_override_input/multi_asic_dm_rm.json
- tests/config_override_input/multi_asic_macsec_ov.json
- tests/config_override_test.py
ADO: 17746282
Support multi-asic Golden Config Override with fix based on https://github.com/sonic-net/sonic-utilities/pull/2738
Add ConfigMgmt support for ASIC validation. Modify override config cli to support multi-asic.
Unit test:
tests/config_override_test.py::TestConfigOverrideMultiasic::test_macsec_override PASSED [  8%]
tests/config_override_test.py::TestConfigOverrideMultiasic::test_device_metadata_table_rm PASSED [  8%]
> [config]Support multi-asic Golden Config override with fix

- sonic_installer/bootloader/uboot.py
Reproduce the issue:
```
/home/admin# sonic-installer set-fips
Command: /usr/bin/fw_setenv linuxargs net.ifnames=0 loopfstype=squashfs loop=image-20220531.27/fs.squashfs systemd.unified_cgroup_hierarchy=0 varlog_size=4096 loglevel=4 sonic_fips=1
Error: illegal character '=' in variable name "loopfstype=squashfs"
```
- Microsoft ADO **(number only)**: 22333116
Add the double quotation marks when calling the command.
It works fine when calling the following command:
/usr/bin/fw_setenv linuxargs "net.ifnames=0 loopfstype=squashfs loop=image-20220531.27/fs.squashfs systemd.unified_cgroup_hierarchy=0 varlog_size=4096 loglevel=4 sonic_fips=1"
> Fix the invalid variable issue when set-fips in uboot

- sfputil/main.py
- tests/sfputil_test.py
Currently, the TRANSCEIVER_INFO table is not updated periodically and is event driven through SFP insertion/removal events.
So after using sfputil to upgrade the FW ("sfputil firmware upgrade <port>" for example), if we use "show transceiver eeprom/info" CLI, we would still see the stale FW version. The only way to see new FW version is by using "sfputil show fwversion <port>" CLI.
We are now updating the TRANSCEIVER_INFO table after download, run and commit steps of FW update
Ensured that the TRANSCEIVER_INFO table gets updated after download, run and commit steps after triggering FW update.
> Update TRANSCEIVER_INFO table after CDB FW upgrade

- generic_config_updater/services_validator.py
- pcieutil/main.py
- tests/pcieutil_test.py
Currently, pcieutil will print the following message to console every time it is called if loading the common module:
root@sonic:/home/cisco# pcieutil show
Failed to load platform Pcie module. Error : No module named 'sonic_platform.pcie', fallback to load Pcie common utility.
==============================Display PCIe Device===============================
Update the error message to only be logged in syslog, rather than print to console.
Run any pcieutil command
```
root@sonic:/home/cisco# pcieutil show
Failed to load platform Pcie module. Error : No module named 'sonic_platform.pcie', fallback to load Pcie common utility.
==============================Display PCIe Device===============================
......
```
```
root@sonic:/home/cisco# pcieutil show …
```
> Update pcieutil error message on loading common pcie module

- scripts/route_check.py
- tests/mock_tables/config_db.json
- tests/route_check_test.py
- tests/route_check_test_data.py
This reverts commit 79a21ceff25cbe3fda8e09e4ad0db6f750b1be0d.
DEPENDS ON: https://github.com/sonic-net/sonic-buildimage/pull/12853
Reverted changes back
Reverted changes back
UT
> Revert "Revert frr route check (#2761)"

- config/main.py
- tests/config_override_input/multi_asic_dm_gen_sysinfo.json
- tests/config_override_test.py
ADO: 17921518
The generated Golden Config will not have knowledge of configs that are produced in run time, such as mac and platform.
Generate that info in Override Config if missing.
Reuse the mac and platform in existing device runnning config and generate that if missing.
Unit test
> [config] Generate sysinfo as needed when override config

- config/vlan.py
- tests/vlan_test.py
Fix this issue: https://github.com/sonic-net/sonic-buildimage/issues/15047
Show dhcp_relay ipv6 counter will display vlan which has been deleted.
Remove related info in state_db while deleting a vlan
1. Add unit test
```
tests/vlan_test.py::TestVlan::test_config_vlan_del_vlan PASSED           [ 74%]
```
2. Build utilities and run cmd to verify
```
admin@dut:~$ show dhcp_relay ipv6 counters
Message Type    Vlan1000
-------------------  ----------
Unknown           0
Solicit           0
Advertise           0
Request           0
Confirm           0
Renew           0
Rebind           0
Reply           0
Release           0
Decline           0
Reconfigure           0
Information-Request           0
Relay-Forward           0
Relay-Reply           0
Malformed           0
Message Type    Vlan1001 …
```
> [vlan][dhcp_relay] Clear dhcpv6 relay counter while deleting vlan

- sonic_package_manager/manager.py
- tests/sonic_package_manager/test_manager.py
Overcome a CLI plugin compatibility issue 
DHCP relay extension expects the spm to name its plugin "dhcp-relay". This change keeps that format if there is just one CLI plugin.
> [sonic-package-manager] fix CLI plugin compatibility issue

- scripts/db_migrator.py
MSFT ADO: 17972494
Fix errors in db migration when hwsku is not detected.
This PR is adds a better-error-handling fix for the issue that is fixed by: https://github.com/sonic-net/sonic-buildimage/pull/14933
```
May  2 20:35:04 sonic database.sh[649]: Creating new database container
May  2 20:35:04 sonic database.sh[663]: 99e8edba01ed0c7581f0d61dd2fa78374fa4f23e636a957004dd03a6f68eea86
May  2 20:35:04 sonic root: Starting database service...
May  2 20:35:06 sonic database.sh[690]: database
May  2 20:35:10 sonic database.sh[926]: True
May  2 20:35:10 sonic database.sh[928]:   File "/usr/local/bin/db_migrator.py", line 714, in common_migration_ops
May  2 20:35:10 sonic database.sh[928]:   File "/usr/local/bin/db_migrator.py", line 741, in migrate
May  2 20:35:10 sonic database.sh[928]: …
```
> [db-migrator] Fix hwsku match for 6100 and add errors when hwsku is None

- config/main.py
ADO: 17921518
It is a bug introduced from https://github.com/sonic-net/sonic-utilities/pull/2836. Need to generate sysinfo for single asic.
Reuse the mac and platform in existing device runnning config and generate that if missing.
Unit test
> [config]Generate sysinfo in single asic

- config/main.py
- doc/Command-Reference.md
- show/main.py
- tests/config_test.py
- tests/show_test.py
hld [#1219](https://github.com/sonic-net/SONiC/pull/1219)
closes [#1171](https://github.com/sonic-net/SONiC/issues/1171)
* Add command to configure date and time
* Add command to configure timezone
* Add command to show timezones
Show clock and timezones:
```
show clock
show clock timezones
```
Set date and time and verify:
```
sudo config clock date-time <date> <time>
show clock
```
Set timezone and verify:
```
sudo config clock timezone <timezone>
show clock
```
```
admin@sonic:~$ show clock
Sat 10 Oct 2020 01:02:20 AM HDT
```
```
admin@sonic:~$ show clock
Sat 10 Oct 2020 01:02:20 AM HDT
```
```
admin@sonic:~$ show clock timezones
Africa/Abidjan
Africa/Accra
Pacific/Wallis
UTC
Etc/UTC
```
```
admin@sonic:~$ sudo config clock timezone Europe/Ki # <TAB><TAB>
Europe/Kiev   Europe/Kirov …
```
> [Clock] Implement clock CLI

- config/main.py
- tests/sflow_test.py
Fixed issue: out of range sflow polling interval is accepted and stored in config_db.
Reproduce step:
```
1. Enable sflow feature:   config feature state sflow enabled
2. Enable sflow itself:   config sflow enable 
3. Configure out of range polling interval:  config sflow polling-interval 1. Error message is shown as expected
4. Save config:    config save -y
5. Check "SFLOW" section inside config_db
```
As the interval is invalid, the expected behavior is that the interval is not saved to redis. But we see the invalid value was written to redis.
Change `click.echo` to `ctx.fail`
1. Manual test
2. Add a check in existing unit test case to cover the change
> Fix issue: out of range sflow polling interval is accepted and stored in config_db

- config/main.py
- tests/config_test.py
This reverts commit 88ffb16721d6f867f71100bb14564120a456e07b.
It break config reload with stdin input.
> Revert "[config]config reload should generate sysinfo if missing (#2778)

- acl_loader/main.py
- doc/Command-Reference.md
- tests/acl_input/acl1.json
- tests/acl_input/illegal_v4v6_rule_no_ethertype.json
- tests/acl_loader_test.py
- tests/aclshow_test.py
- tests/mock_tables/config_db.json
Support a new ACL table type called L3V4V6.
This table supports both v4 and v6 Match types.
Added unit tests for this new ACL table type.
HLD: sonic-net/SONiC#1267
Signed-off-by: Ravi(Marvell) rck@innovium.com
Support a new ACL table type called L3V4V6.
- Added table L3V4V6. 
- Added checks that ethertype is provided for ACL rules in this table that have IP or ICMP or L4(TCP/UDP) match-fields.
- Enhanced convert_icmp() to decide ICMP_V6 vs ICMP by using the ether-type
- Added unit-tests to create both v4 and v6 rules in this new table.
- Verify that ICMP_CODE is translated to ICMPV6_CODE for rules with ether-type as IPv6.
- Extended the default_deny_rule testcase to have a drop rule with protocol as "IP". This will match both v4 and v6 packets.
- Added negative tests to skip rules that do …
> [acl-loader] Support for ACL table type L3V4V6

- config/config_mgmt.py
- config/main.py
- tests/config_override_input/multi_asic_dm_rm.json
- tests/config_override_input/multi_asic_macsec_ov.json
- tests/config_override_test.py
ADO: 17746282
Cherry-pick conflict.
Backport #2825 and fix conflict.
Tested device:
```
admin@str-msn2700-01:~$ show ver
SONiC Software Version: SONiC.20220531.24
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 262ec6a387
Build date: Tue Mar 28 19:56:42 UTC 2023
Built by: cloudtest@3d43ef1cc000000
Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2020T04272
Model Number: MSN2700-CS2FO
Hardware Revision: A2
Uptime: 07:40:46 up 36 min,  3 users,  load average: 1.32, 1.31, 1.48
Date: Tue 06 Jun 2023 07:40:46
```
> [202205][config]Support multi-asic Golden Config override with fix (#2825)

- show/chassis_modules.py
- tests/chassis_modules_test.py
- tests/mock_tables/state_db.json
Enhancement to the "show chassis modules status" CLI to add a new column added at the end to show each card's serial number
- Store another field - serial in chassis module table for each card, which is be fetched and displayed through show command
- Dependent PR in sonic-platform-daemons to accommodate the storage of serial field to the database, both PRs <363> and <2858> need to go together and submodule versions need to be updated 
(https://github.com/amulyan7/sonic-platform-daemons/pull/1)
Microsoft ADO: https://dev.azure.com/msazure/One/_workitems/edit/17320021
Through the CLI: show chassis modules status
RP
```
root@sonic:/home/cisco# show chassis modules status
Name                             Description    Physical-Slot    Oper-Status    Admin-Status       Serial
------------ …
```
> Add display support for serial field in show chassis modules status CLI

- generic_config_updater/field_operation_validators.py
- generic_config_updater/gcu_field_operation_validators.conf.json
- generic_config_updater/gu_common.py
- tests/generic_config_updater/field_operation_validator_test.py
- tests/generic_config_updater/gcu_feature_patch_application_test.py
- tests/generic_config_updater/gu_common_test.py
Original platform validator PR https://github.com/sonic-net/sonic-utilities/pull/2791/checks?check_run_id=12708751588 was merged and reverted due to unexpected test case behavior blocking submodule advance. The test case was fixed through https://github.com/sonic-net/sonic-mgmt/pull/8469. Now, this platform validator PR brings back the original changes
> Complete Platform Validator PR

- config/vlan.py
While deleting a Vlan, clear dhcpv6_relay counter info state_db before dhcp_relay container restart would cause that counter info still exist in state_db, which is incorrect.
Microsoft ADO number: 24211173
Clear counter info in state_db after container restart.
Previous ut and build image to verify.
```
admin:~$ show dhcp6relay_counters counts
Message Type    Vlan1000
-------------------  ----------
Unknown           0
Solicit           0
Advertise           0
Request           0
Confirm           0
Renew           0
Rebind           0
Reply           0
Release           0
Decline           0
Reconfigure           0
Information-Request           0
Relay-Forward           0
Relay-Reply           0
Malformed           0
Message Type    Vlan1001
-------------------  ----------
Unknown …
```
> [dhcp-relay] Fix dhcp6relay counter issue

- scripts/portstat
- tests/portstat_test.py
'and' logic has higher precedence than 'or' logic. we want to make sure it's either chassis or multi-asic, and in both case, if 'use_json' option is not provided.
fix https://github.com/sonic-net/sonic-buildimage/issues/15439
verified on a chassis linecard:
before:
Reminder: Please execute 'show interface counters -d all' to include internal links
is printed at end of 'portstat -j'
after: only json format is printed
```
...
"TX_OK": "3,014",
"TX_OVR": "0",
"TX_UTIL": "0.00%"
}
}
admin@str2-7804-lc5-1:~$ ```
> fix precedence in portstat CLI

- scripts/portstat
This is cherry pick of: https://github.com/sonic-net/sonic-utilities/pull/2874
ADO: https://msazure.visualstudio.com/One/_workitems/edit/24260584
fix issue: https://github.com/sonic-net/sonic-buildimage/issues/15439
> [202205] [chassis] fix incorrect output of 'portstat -j'

- scripts/db_migrator.py
- tests/db_migrator_input/appl_db/routes_migrate_expected.json
- tests/db_migrator_input/appl_db/routes_migrate_input.json
- tests/db_migrator_test.py
I added requires "protocol" field due to fpmsyncd reconcile logic (WarmRestartHelper class) requires old fvs keys to match new fvs.
Add "protocol" field in db migration.
Upgrade from older branch to new image with supported FIB pending.
The field was added by https://github.com/sonic-net/sonic-swss/pull/2551.
Now, after reboot:
```
127.0.0.1:6379> hgetall ROUTE_TABLE:0.0.0.0/0
1) "weight"
2) "1,1,1,1,1,1,1,1"
3) "protocol"
4) "bgp"
5) "ifname"
6) "PortChannel102,PortChannel105,PortChannel108,PortChannel1011,PortChannel1014,PortChannel1017,PortChannel1020,PortChannel1023"
7) "nexthop"
8) "10.0.0.1,10.0.0.5,10.0.0.9,10.0.0.13,10.0.0.17,10.0.0.21,10.0.0.25,10.0.0.29"
```
> [db_migrator] add required "protocol" field in ROUTE_TABLE

- show/main.py
- tests/show_test.py
- tests/syslog_input/rsyslog.conf
Adjust `show runningconfiguration syslog` command according to the new syslog configuration file
Fix regex to match the target syslog server
Run the next command in sonic shell:
```
show runningconfiguration syslog
```
N/A
N/A
> [syslog] Adjust runningconfiguration syslog command

- clear/main.py
- scripts/fabricstat
- tests/fabricstat_test.py
Added two clear commands for fabric counters queue and fabric counters port.
sonic-clear fabriccountersport
sonic-clear fabriccountersqueue
By issuing the command, the fabric counters are clear and saved.  An example is as follow.
```
ASIC    PORT    STATE    IN_CELL    IN_OCTET    OUT_CELL    OUT_OCTET    CRC    FEC_CORRECTABLE    FEC_UNCORRECTABLE    SYMBOL_ERR
------  ------  -------  ---------  ----------  ----------  -----------  -----  -----------------  -------------------  ----------
...
0      49       up          1         244           0            0       0                  2        2,372,752,496               0
0      50       up          2         315           1          135       0                  4        2,522,457,120               4
...
Clear and update saved counters …
```
> Clear fabric counters queue/port

- scripts/db_migrator.py
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_expected.json
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_input.json
- tests/db_migrator_input/state_db/fast_reboot_upgrade.json
- tests/db_migrator_test.py
Add migration of `FLEX_COUNTER_DELAY_STATUS` attribute of config_db `FLEX_COUNTER_TABLE` during the `SONiC to SONiC upgrade + fast-reboot` from older versions `201911 -> master`.
This change is required for the `fast-reboot` procedure because without it the counters will be created during the init flow which will waste a lot of resources and cause data plane degradation of more than 30 seconds.
Modify the `db_migrator.py`.
Add UT.
> [db_migrator] Add migration of FLEX_COUNTER_DELAY_STATUS during 1911->master upgrade + fast-reboot. Add UT.

- clear/main.py
- scripts/fabricstat
- tests/fabricstat_test.py
Reverts sonic-net/sonic-utilities#2789
The above PR was last run in pipelines on Apr 12 which succeeded all the test cases. After 2 months, it got merged yesterday but is failing the test cases introduced in it. It is causing build failures in master branch as well as several PRs due to the same test cases
Test Case Failure in master branch [https://dev.azure.com/mssonic/build/_build/results?buildId=295120&view=results](url)
@arlakshm @qiluo-msft Can you please help revert or resolve this issue so that PRs part of 202305 which includes our #2419  can be merged in the master branch which has cut off date for 16 June
> Revert "Clear fabric counters queue/port"

- scripts/db_migrator.py
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_3_0_7_expected.json
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_3_0_7_input.json
- tests/db_migrator_input/state_db/fast_reboot_upgrade.json
- tests/db_migrator_test.py
Add migration of `FLEX_COUNTER_DELAY_STATUS` attribute of config_db `FLEX_COUNTER_TABLE` during the `SONiC to SONiC upgrade + fast-reboot` from older versions `201911 -> 202205`.
This change is required for the `fast-reboot` procedure because without it the counters will be created during the init flow which will waste a lot of resources and cause data plane degradation of more than 30 seconds.
Modify the `db_migrator.py`.
Add UT.
> [202205][db_migrator] Add migration of FLEX_COUNTER_DELAY_STATUS during 1911->2205 upgrade + fast-reboot. Add UT.

- acl_loader/main.py
- tests/acl_loader_test.py
**Microsoft ADO  24363637**
Currently on multi asic platform the `acl-loader` script connects to all the db in the namespaces using `unix` sockets.
This cause permission errors when executing `show acl` commands for user with `RO` privileges.
To avoid this change the `acl-loader` to use tcp socket to connect to db in namespaces
update acl-loader
UT
> [chassis][multi asic] change acl_loader to use tcp socket for db communication

- generic_config_updater/field_operation_validators.py
- generic_config_updater/gcu_field_operation_validators.conf.json
- generic_config_updater/gu_common.py
- tests/generic_config_updater/field_operation_validator_test.py
- tests/generic_config_updater/files/feature_patch_application_test_failure.json
- tests/generic_config_updater/files/feature_patch_application_test_success.json
- tests/generic_config_updater/gcu_feature_patch_application_test.py
- tests/generic_config_updater/gu_common_test.py
ADO 17747379
This PR cherry-picks three PRs to 202205 in the following order: 
1. https://github.com/sonic-net/sonic-utilities/pull/2692
2. https://github.com/sonic-net/sonic-utilities/pull/2818
3. https://github.com/sonic-net/sonic-utilities/pull/2857.
Motivation of cherry-pick is to add PR #2857 platform validator functionality to 202205. Without this PR, GCU does not have the ability to restrict updates to certain tables based on platform. This function is necessary for RDMA related tables. This platform validator PR uses a test file created and updated in PR #2692 and PR #2818, so all three PRs are cherry-picked together.
After this PR is merged, the sonic-mgmt test cases need to be updated: https://github.com/sonic-net/sonic-mgmt/pull/8583
> [GCU Feature Update] Cherry-pick Platform Validator PR to 202205 

- config/dns.py
- config/main.py
- doc/Command-Reference.md
- show/dns.py
- show/main.py
- tests/dns_test.py
Implement config and show commands for static DNS feature. According to https://github.com/sonic-net/SONiC/pull/1262 HLD.
Static DNS config commands are implemented in the new config/dns.py file. DNS config commands are available under `config dns ...` sub-command.
Show commands are implemented in the new show/dns.py file. DNS show commands are available under `show dns ...` sub-command.
Compile sonic-utilities package. The unit tests will run automatically during the compilation.
Coverage for config/dns.py : 94%
Coverage for show/dns.py : 86%
```
Nameserver
------------
1.1.1.1
8.8.8.8
```
> [dns] Implement config and show commands for static DNS.

- scripts/generate_dump
Change-Id: Ibb5b5a860833e8d7834a1d72756d070c61f2ab37
Added support for marvell sdk commands in "show techsupport". 
Modified the generate_dump script, to add marvell sdk commands under a proper platform check.
Verified the change by running "show techsupport" command and check all the newly added marvel sdk commands are collecting the correct information.
> [generate_dump]: Enhance show techsupport for Marvell platform

- config/vlan.py
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-utilities/pull/2866.
While deleting a Vlan, clear dhcpv6_relay counter info state_db before dhcp_relay container restart would cause that counter info still exist in state_db, which is incorrect.
Microsoft ADO number: 24211173
Clear counter info in state_db after container restart.
Previous ut and build image to verify.
> [202012][dhcp-relay] Fix dhcp6relay counter issue (#2866)

- scripts/db_migrator.py
- tests/db_migrator_test.py
Set the correct value for the `db_migrator` class variable `CURRENT_VERSION`, because if the new DB version was introduced the `CURRENT_VERSION` variable should have the newest version value.
Edit the `db_migrator.py`.
Extend existing UT.
> [db_migrator] Set correct CURRENT_VERSION, extend UT

- scripts/db_migrator.py
- tests/db_migrator_test.py
Set the correct value for the `db_migrator` class variable `CURRENT_VERSION`, because if the new DB version was introduced the `CURRENT_VERSION` variable should have the newest version value.
Edit the `db_migrator.py`.
Extend existing UT.
> [202205][db_migrator] Set correct CURRENT_VERSION, extend UT

- scripts/route_check.py
- tests/route_check_test_data.py
Skip `soc_ipv6` when comparing appl_db and asic_db route entries on `active-active` dualtor. Because it's creating false alarms when tunnel route is added for soc ips. The route is meant to be programmed in asic only. 
Run the updated script on active-active dualtor devices.
> [dualtor][route_check] filter out `soc_ipv6` 

- scripts/fast-reboot
The PR is to flush `RESTAPI_DB` in the fast-reboot shutdown path.
After PR https://github.com/sonic-net/sonic-utilities/pull/2365, the table is not cleared because the `WARM_RESTART_ENABLE_TABLE|system` is set to `true`.
So below code in `swss.sh` doesn't do the db flush.
https://github.com/sonic-net/sonic-buildimage/blob/bdef73ea963064cdc9fbebb63ac381440c0fafd6/files/scripts/swss.sh#L168C1-L181C7
```
if [[ x"$WARM_BOOT" != x"true" ]]; then
debug "Flushing APP, ASIC, COUNTER, CONFIG, and partial STATE databases ..."
$SONIC_DB_CLI APPL_DB FLUSHDB
$SONIC_DB_CLI ASIC_DB FLUSHDB
$SONIC_DB_CLI COUNTERS_DB FLUSHDB
$SONIC_DB_CLI FLEX_COUNTER_DB FLUSHDB
$SONIC_DB_CLI GB_ASIC_DB FLUSHDB
$SONIC_DB_CLI GB_COUNTERS_DB FLUSHDB
$SONIC_DB_CLI RESTAPI_DB FLUSHDB
clean_up_tables STATE_DB "'PORT_TABLE*', …
```
> Flush RESTAPI db in fast-reboot shutdown path

- tests/db_migrator_input/config_db/cross_branch_upgrade_to_version_2_0_2_expected.json
- tests/db_migrator_test.py
MSFT ADO: 24598790
Why:
RESTAPI table has certs generated from minigraph parser.
The values in RESTAPI table (cert and key names) are dependent on how they are hardcoded in minigraph parser.
Current solution works on public repo, but breaks the internal build (different naming).
What:
Do not match values for RESTAPI attributes. The test still ensures that missing table and keys are migrated.
UT passes now even when cert names are changed in expected JSON.
> UT change: for db_migrator test do not check for RESTAPI cert values

- scripts/fast-reboot
**This PR is to backport change #2917 into `202205` branch.**
The PR is to flush `RESTAPI_DB` in the fast-reboot shutdown path.
After PR https://github.com/sonic-net/sonic-utilities/pull/2365, the table is not cleared because the `WARM_RESTART_ENABLE_TABLE|system` is set to `true`.
So below code in `swss.sh` doesn't do the db flush.
https://github.com/sonic-net/sonic-buildimage/blob/bdef73ea963064cdc9fbebb63ac381440c0fafd6/files/scripts/swss.sh#L168C1-L181C7
```
if [[ x"$WARM_BOOT" != x"true" ]]; then
debug "Flushing APP, ASIC, COUNTER, CONFIG, and partial STATE databases ..."
$SONIC_DB_CLI APPL_DB FLUSHDB
$SONIC_DB_CLI ASIC_DB FLUSHDB
$SONIC_DB_CLI COUNTERS_DB FLUSHDB
$SONIC_DB_CLI FLEX_COUNTER_DB FLUSHDB
$SONIC_DB_CLI GB_ASIC_DB FLUSHDB
$SONIC_DB_CLI GB_COUNTERS_DB FLUSHDB
$SONIC_DB_CLI …
```
> [202205] Flush RESTAPI db in fast-reboot shutdown path

- scripts/db_migrator.py
Cherry pick of https://github.com/sonic-net/sonic-utilities/pull/2821
> [202012][db-migrator] Fix hwsku match for 6100 and add error to logs

- setup.py
Update urllib3 to V2.
Some package depends on urllib3V2.
But urllib3 is pinned on V1 for docker 4.4.1 not support urllibV2.
Now docker is upgraded to V6. The issue didn't exist.
> [build] Fix dependency issue between responses and urllib3 package.

- tests/intfstat_test.py
Revert test case due to frequent failure in azp introduced in PR https://github.com/sonic-net/sonic-utilities/pull/2849
> revert unit test tests/test_clear_tag

- scripts/generate_dump
Added input check for argument "-t" in generate_dump script
Made sure only integer values can be received for this argument
Call generate_dump -t with non-integer values
> Input check for timeout in generate_dump

- rcli/linecard.py
- rcli/rexec.py
- rcli/rshell.py
- rcli/utils.py
- tests/remote_cli_test.py
**_Microsoft ADO 24703217_**
In this PR the following enhancements are done
- Add support for user to pass username
- Add support to login to all linecards before executing any commands 
- 
UT and chassis
> [chassis] rexec enhancements 

- show/main.py
- tests/show_test.py
- tests/syslog_input/rsyslog.conf
cherry-pick: #2843
Adjust `show runningconfiguration syslog` command according to the new syslog configuration file
Fix regex to match the target syslog server
Run the next command in sonic shell:
```
show runningconfiguration syslog
```
N/A
N/A
> [syslog] Add remote syslog configuration (cherry-pick to 202305)

- scripts/sonic-kdump-config
- tests/sonic_kdump_config_test.py
Simplify the API used to get the current active image name.
Instead of relying on the output of the "sonic-installer list" command, use the API  get_current_image() from the sonic_installer.bootloader py library.
config reload
config kdump disable
config kdump enable
config kdump memory 768M
> [kdump] Fix API to read the current running image

- acl_loader/main.py
- tests/mock_tables/asic2/config_db.json
- tests/show_acl_test.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/16012
The `show acl table` command currently get the ports from host config_db on multi asic platforms.
This  host config_db will not the phyiscal ports in the binding ports because the host doesnt have any front panel ports on the host.  This causes the `show acl table`  not to display the phyiscal ports in the output on multi asic devices/linecards.
The test `iface_namingmode/test_iface_namingmode.py::test_show_acl_table` fails because of this issue.
Details from the test failure
```
iface_namingmode/test_iface_namingmode.py::test_show_acl_table[alias-sonic-lc1-1] 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) …
```
> [chassis][multi-asic]Fix show acl table for masic

- config/main.py
- tests/config_override_input/multi_asic_missing_asic.json
- tests/config_override_test.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/16164
In the multi-asic devices for eg: supervisor card of a chassis, the asics are not of its own -- it is the asic present in the fabric cards in the chassis. On then -- all the fabric cards need not be present in the chassis everytime.
In that case golden_config_db.json file generated by NDM ( based on the Subdevices in the minigraph ) will not have all ASICs -- it will be for the fabric cards present in the chassis  
With the current logic, if there is an asic namespace missing -- config load_minigraph will exit with error as in the Issue #https://github.com/sonic-net/sonic-buildimage/issues/16164 and not restart dockers.
Add logic to check and continue if the "asic" namespace is not present in the golden_config_db.json for …
> Fix in config override when all asic namespaces not present in golden_config_db

- sfputil/main.py
- tests/sfputil_test.py
The mismatch in 0 based or 1 based port numbering between sfp.index and physical_port number is causing the below issues while executing the "sfputil show error-status -hw" command
1.	“sfputil show error-status -hw” command doesn’t show error-status for Ethernet0 or the last port for some platforms and the remaining ports show error-status of the next or previous port
2.	“sfputil show error-status -hw -p <port>” doesn’t display error-status
3. platform_tests/sfp/test_sfputil.py::test_check_sfputil_error_status sonic-mgmt testcase fails for some platforms
Issue details with an example of sfp.index being 1 based while physical_port being 0 based:
The sfp.index https://github.com/sonic-net/sonic-utilities/blob/7435b1ca539382e644f29d424c551f6258fd2920/sfputil/main.py#L904 is 1 based whereas …
> [sfputil] Retrieve error-status for transceiver using sfp API

- scripts/db_migrator.py
- tests/db_migrator_input/state_db/fast_reboot_upgrade_from_202205.json
- tests/db_migrator_test.py
Fix issue while upgrading from 202205 to 202211 via fast reboot. This issue is caused by a mismatch version handling for fast reboot in db_migrator. 
In 202205, the db migrator for fast reboot flag handling is 3_0_5:
https://github.com/sonic-net/sonic-utilities/blob/56a1ae24dc8f4e2dd2ad8929506ecdc836d3dd7c/scripts/db_migrator.py#L920
However, in master(202211), the db migrator for fast reboot flag handling is 4_0_0:
https://github.com/sonic-net/sonic-utilities/blob/7435b1ca539382e644f29d424c551f6258fd2920/scripts/db_migrator.py#L993
This mismatch causes an incorrect sequence like this:
```
1. User issue fast-reboot under 202205
2. fast-reboot script set fast reboot flag by command "sonic-db-cli STATE_DB HSET "FAST_RESTART_ENABLE_TABLE|system" "enable" "true" &>/dev/null"
3. system boot to …
```
> [db_migrator.py] Fix issue while upgrading from 202205 to 202211 via fast reboot

- sfputil/main.py
- tests/sfputil_test.py
Removed usage of sfp_index in generating the list of sfp hw errors list. The iteration of 1:1 mapping between logical port and sfp object  works because the chassis's _sfp_list [] is sorted in increasing order of physical port indices.
Works fine on Arista, Cisco, Dell, Mellanox
````
Verified the changes with different types of vendors
1. vendorA
Automated run
Passed
Manual run
show int status
sfputil show error-status -hw
sfputil show error-status -hw -p Ethernet0
sfputil show error-status -hw -p Ethernet
root@vendorA:/home/admin# show int status
til show error-status -hw -p Ethernet0     Interface            Lanes    Speed    MTU    FEC    Alias            Vlan    Oper    Admin                                      Type    Asym PFC
--------------  ---------------  -------  -----  ----- …
```
> Remove SFP index usage in generating list of SFP hw error

- scripts/db_migrator.py
db_migrator should not depend on CONFIG_DB_INITIALIZED flag. get_hwsku api call busy waits on that flag
Replace get_hwsku call with get_localhost_info call which takes in a custom config_db object
> Remove the CONFIG_DB_INIT flag dependency on db_migrator

- sonic_package_manager/manager.py
- tests/sonic_package_manager/test_manager.py
When we migrate package via sonic-package-manager in some low-performance device, getting docker image from old image via docker socket may timeout by default timeout setting (60s) [client.py](https://github.com/docker/docker-py/blob/main/docker/api/client.py#L106). This PR is to increase timeout to 120s.
Increase docker client timeout from 60s to 120s.
1. ut passed.
2. Build image with INCLUDE_MACSEC, and install it, macsec image was not include. And the build image with this PR, install it. Migrate package successfully.
> [sonic-package-manager] Increate timeout for sonic-package-manager migrate

- config/vlan.py
- tests/vlan_test.py
Resolves https://github.com/sonic-net/sonic-buildimage/issues/16542
Update str -> list[str] commands which were missed in https://github.com/sonic-net/sonic-utilities/pull/2718
Pass UT. Manual test, issue resolved, tested in internal.79435802-3bbd91c86e version
> Fix del vlan command

- config/vlan.py
- tests/mock_tables/config_db.json
- tests/vlan_test.py
- utilities_common/dhcp_relay_util.py
**MSFT work item: 25218077**
Use static str to run_command would encounter error because change in this PR: https://github.com/sonic-net/sonic-utilities/pull/2718.
Change command from static str to list.
1. UT passed
2. Build whl and install in testbed.
3. Init vlan config:
```
admin@hostname:~$ show vlan bri
+-----------+-----------------+------------+----------------+-------------+
|   VLAN ID | IP Address      | Ports      | Port Tagging   | Proxy ARP   |
+===========+=================+============+================+=============+
|      1000 | 192.168.0.1/24  | Ethernet0  | untagged       | disabled    |
|           | fc02:1000::1/64 | Ethernet1  | untagged       |             |
|           |                 | Ethernet2  | untagged       |             |
|           |                 | …
```
> [vlan][dhcp_relay] Fix error while delete vlan

- scripts/generate_dump
Cherry pick #2979 
ADO - 25129114
202012 specific change
- Added support to include "log.tmpfs" in the final tar file. On other branches, save_to_tar function addresses this.
It seems that "show techsupport" currently doesn't archive the log files under "/var/log.tmpfs" directory. Hence, this PR addresses this issue.
We are now checking if "/var/log.tmpfs" directory exists and include the corresponding log files.
1. "show techsupport" on a system with logging to "/var/log/"
2. "show techsupport" on a system with logging to "/var/log.tmpfs/"
```
**************************************************************
1. "show techsupport" on a system with logging to "/var/log/"
**************************************************************
root@sonic:/tmp/temp/sonic_dump_sonic_20230921_184002/log# …
```
> [202012][Techsupport] Techsupport tmpfs logging

- acl_loader/main.py
- tests/acl_input/acl1.json
- tests/acl_loader_test.py
When adding ICMPv6 ACL rules in custom ACL table type, current `acl-loader` will incorrectly treat the ACL table as IPv4. I open this PR to fix this bug and let `acl-loader` identify ICMP v4 or v6 based on IP_PROTOCOL.
_Also fixed some typo in UT of acl-loader to avoid confusion._
In function `convert_icmp`, add one step to identify the rule is v4 or v6 based on IP_PROTOCOL.
Verified by UT:
```
Name                                                   Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------------------------
acl_loader/__init__.py                                     0      0      0      0   100%
acl_loader/main.py                                       691    154    320     50    74%
... …
```
> [acl-loader] Identity ICMP v4/v6 based on IP_PROTOCOL for custom ACL table types

- sonic_installer/common.py
- sonic_installer/main.py
- tests/test_sonic_installer.py
Don't capture output from migrate command for better debugging.
Added ```nocapture``` flag to ```run_command_or_raise```. Pass ```nocapture``` when running ```spm migrate```.
Run sonic to sonic upgrade and observe the output of migrate command.
> [sonic-installer] print output from spm migrate

- generic_config_updater/gcu_services_validator.conf.json
- generic_config_updater/services_validator.py
- tests/generic_config_updater/service_validator_test.py
Remove rsyslog related service validator in GCU because it has been supported in latest image
Remove related code
Unit test
> Remove syslog service validator in GCU

- acl_loader/main.py
- tests/acl_input/acl1.json
- tests/acl_loader_test.py
**Backport #2994**
**What is the motivation for this PR?**
When adding ICMPv6 ACL rules in custom ACL table type, current acl-loader will incorrectly treat the ACL table as IPv4. I open this PR to fix this bug and let acl-loader identify ICMP v4 or v6 based on IP_PROTOCOL. Also fixed some typo in UT of acl-loader to avoid confusion.
**How did you do it?**
In function convert_icmp, add one step to identify the rule is v4 or v6 based on IP_PROTOCOL.
**How did you verify/test it?**
Verified by UT.
> [202205][acl-loader] Identity ICMP v4/v6 based on IP_PROTOCOL for custom ACL table types

- doc/Command-Reference.md
- sfputil/main.py
- tests/sfputil_test.py
Add 'target' option to sfputil CLI. This target mode will be set in the vendor custom registers in the module page 0h Byte 60, which will direct the right path to upgrade remote module
Add target option in the sfputil file and add related vendor specific apis in the CMIS code.
Use remote upgraded module and execute the sfputil firmware command.
```
root@sonic:/home/cisco# sfputil firmware ?
Usage: sfputil firmware [OPTIONS] COMMAND [ARGS]...
Download/Upgrade firmware on the transceiver
Options:
--help  Show this message and exit.
Commands:
commit    Commit the running firmware
download  Download firmware on the transceiver
run       Run the firmware with default mode=0
unlock    Unlock the firmware download feature via CDB host password
upgrade   Upgrade firmware on the transceiver
``` …
> Add target mode to sfputil firmware

- fwutil/lib.py
- tests/fwutil_test.py
Fix a Python syntax warning in the fwuti command output:
**/usr/local/lib/python3.9/dist-packages/fwutil/lib.py:902: SyntaxWarning: "is" with a literal. Did you mean "=="?
if boot is "none" or boot in data:**
```
admin@sonic:/home/admin# sudo fwutil show status
/usr/local/lib/python3.9/dist-packages/fwutil/lib.py:902: SyntaxWarning: "is" with a literal. Did you mean "=="?
if boot is "none" or boot in data:
Chassis    Module    Component    Version                          Description
---------  --------  -----------  -------------------------------  ----------------------------------------
SN5600     N/A       ONIE         2022.08-5.3.0010-dev-115200-dev  ONIE - Open Network Install Environment
SSD          0913-000                         SSD - Solid-State Drive
BIOS …
```
> [fwutil] Fix python SyntaxWarning for 'is' with literals

- scripts/db_migrator.py
Warm Reboot from 202205 -> latest labels is failing because of an extra version that was added to 202205 and that was missing in later branches.
Add a placeholder for version 3_0_7 in latest labels
WR from 202205 to 202305 and try running db_migrator
```
root@r-anaconda-simx-139:/home/admin# db_migrator.py -o migrate
File "/usr/local/bin/db_migrator.py", line 1133, in main
result = getattr(dbmgtr, operation)()
File "/usr/local/bin/db_migrator.py", line 1085, in migrate
next_version = getattr(self, version)()
AttributeError: 'DBMigrator' object has no attribute 'version_3_0_7'
'DBMigrator' object has no attribute 'version_3_0_7'
usage: db_migrator.py [-h] [-o operation migrate, set_version, get_version] [-s unix socket] [-n asic namespace]
optional …
```
> [db_migrator] Fix the broken version chain

- sfputil/main.py
- tests/sfputil_test.py
Use the block size advertised by the xSFP to download the image if it is less than the default block size
It took the block size advertised by the xSFP module only when EPL was used.
In fact, it should be taken in both EPL and LPL.
Unit test
> [CMIS] Use the block size advertised by the xSFP to download the image if it is less than the default block size

- config/main.py
- tests/buffer_test.py
- tests/mock_tables/config_db.json
Fix issue: non-default configurations in `PORT_QOS_MAP` table isn't removed after `config qos reload --ports`
Remove configurations in single-indexed tables before regenerating the default QoS configuration.
Manual test & unit test
> Fix issue: non-default configurations in PORT_QOS_MAP table isn't removed after config qos reload --ports

- scripts/db_migrator.py
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_expected.json
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_input.json
- tests/db_migrator_input/config_db/portchannel-expected.json
- tests/db_migrator_input/config_db/portchannel-input.json
- tests/db_migrator_input/config_db/qos_map_table_expected.json
- tests/db_migrator_input/config_db/qos_map_table_input.json
- tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-double-pools-expected.json
- tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-double-pools-input.json
- tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-single-pool-expected.json
- tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-single-pool-input.json
Add unit test for db_migrator.py: ConfigDB passing yang validation.
Microsoft ADO: 24657445
Pending on https://github.com/sonic-net/sonic-buildimage/pull/16974
Add yang validation for unit test, and fix test data to pass yang validation.
Run sonic-utilities end to end test.
> Run yang validation in unit test

- config/main.py
- tests/config_test.py
ADO:17746072
Missing platform and mac in CONFIG_DB will result in container failure. We should make the config reload generate those info if missing.
Add missing sys info if config_db.json doesn't contain it.
Unit test
> [config] config reload should generate sysinfo if missing 

- scripts/dualtor_neighbor_check.py
- tests/dualtor_neighbor_check_test.py
Work item tracking
* Microsoft ADO (number only): 25667174
Fix the `dualtor_neighbor_check` error log complaining about the zero-mac neighbor inconsistency due to no tunnel route present in the ASIC.
This is because, for zero-mac neighbors, two situations:
1. new neighbor just learnt, no neighbor entry in ASIC, tunnel route present in ASIC.
2. neighbor expired, neighbor entry still present in ASIC, no tunnel route in ASIC.
Adjust the check condition.
UT and verify on testbed with expired neighbors.
> [dualtor_neighbor_check] Adjust zero-mac check condition

- sonic_package_manager/service_creator/creator.py
- tests/sonic_package_manager/conftest.py
- tests/sonic_package_manager/test_service_creator.py
Fixed an issue that after install new image the extension service isn't started immidetally at boot but when hostcfgd starts it.
There is systemd-sonic-generator that enables services listed in /etc/sonic/generated_services.conf. Add extension service to the list as well.
Build image and run, verify extension starts at boot and not by hostcfgd.
> [sonic-package-manager] add generated service to /etc/sonic/generated_services.conf

- sonic_package_manager/service_creator/sonic_db.py
Installing an app.ext currently inserts app.ext specific init config into redis CONFIG_DB, /etc/sonic/config_db.json and /etc/sonic/init_cfg.json.
Since on configuration reload and boot the configuration file is merged with /etc/sonic/init_cfg.json there is no point in modifying config_db.json.
This can cause issues when config_db.json is not up-to-date. This is not a problem to configuration reload due to config migration, but it is not a valid JSON according to YANG model which does not validate old schema.
Removed the relevant part of the code.
Verified by ONIE installing SONiC and installing an extension. Previosuly it failed and complaining about config_db.json not being valid:
```
Leafref "../../LOOPBACK_INTERFACE_LIST/name" of value "Loopback0" points to a non-existing leaf.
``` …
> [sonic-package-manager] do not modify config_db.json

- generic_config_updater/gcu_services_validator.conf.json
- generic_config_updater/services_validator.py
- tests/generic_config_updater/service_validator_test.py
ADO: 25468726
In the privous PR https://github.com/sonic-net/sonic-utilities/pull/2991, we removed the rsyslog validator because the background daemon can now react(reset-failed & restart) the rsyslog service when the configuration changes. 
However, this change introduced an issue found in nightly tests. The problem is that there is a chance that the rsyslog service is not refreshed promptly after modification. 
We have two potential solutions: we can either modify the sonic-mgmt syslog test to wait more time for the completion of the rsyslog update or reintroduce the syslog validator with enhancements. As the update for rsyslog happens after the completion of the GCU apply-patch, I choose to modify in GCU to ensure that it accurately reflects the completion of the rsyslog change when …
> Update GCU rsyslog validator

- sonic_installer/common.py
- sonic_installer/exception.py
- tests/test_sonic_installer.py
* Extended exception class with user notes
* Implemented new API
* Run UTs
* Backport from `master`: https://github.com/sonic-net/sonic-utilities/pull/3029
```
File "/usr/local/bin/sonic_installer", line 8, in <module>
sys.exit(sonic_installer())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return …
```
> [202305][sonic_installer]: Improve exception handling: introduce notes

- sonic_package_manager/service_creator/creator.py
- tests/sonic_package_manager/test_service_creator.py
This issue is seen during upgrade from older branches to 202305 with PR https://github.com/sonic-net/sonic-utilities/pull/3037.
When sonic-package-manager installs an extension it re-generates /etc/sonic/generated_services.conf. The file does not contain newline at the end.
If packages are installed at runtime everything is ok, but when they are installed at build time, /etc/sonic/generated_services.conf gets later appended with new services:
```
echo "{{service}}" | sudo tee -a $GENERATED_SERVICE_FILE
```
It results in having this line in /etc/sonic/generated_services.conf:
```
interfaces-config.servicedatabase.service
```
This pattern is used multiple times in sonic_debian_extension.j2 script, thus fixing it in sonic-utilities.
Added \n at the end of generated_services.conf
Build with …
> [sonic-package-manager] insert newline in /etc/sonic/generated_services.conf

- scripts/fast-reboot-filter-routes.py
- tests/fast_reboot_filter_routes_test.py
1. Removed click usage from a script since there is no active click context therefore we saw these error messages:
```
ERR fast-reboot-filter-routes: Got an exception There is no active click context.: Traceback: Traceback (most recent call last):#012  File "/usr/local/bin/fast-reboot-filter-routes.py", line 18, in get_connected_routes#012    output, ret = clicommon.run_command(cmd, return_cmd=True)#012  File "/usr/local/lib/python3.9/dist-packages/utilities_common/cli.py", line 545, in run_command#012    proc = subprocess.Popen(command, shell=shell, text=True, stdout=subprocess.PIPE)#012  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__#012    self._execute_child(args, executable, preexec_fn, close_fds,#012  File "/usr/lib/python3.9/subprocess.py", line 1823, in …
```
> [fast-reboot-filter-routes.py] Remove click and improve error reporting

- generic_config_updater/gcu_field_operation_validators.conf.json
- tests/generic_config_updater/field_operation_validator_test.py
Support all SKUs of a new platform `x86_64-mlnx_msn2700a1-r0`
Manual and unit test
> Support new platform in generic configuration update

- pytest.ini
- tests/chassis_modules_test.py
- tests/conftest.py
- tests/decode_syseeprom_test.py
- tests/mclag_test.py
- tests/muxcable_test.py
Running tests with `python3 -m pytest` instead of `python setup.py test` causes some breakages on Bookworm. Some of this has to do with what module searc paths get added, while others appear to be related to changes in the `mock` module between Python 3.9 and Python 3.11.
Fix this and make sure it works on both Bullseye and Bookworm.
Fix mock.patch entries so that the correct object reference gets patched, and remove duplicate test functions in `TestMuxcable`.
> Fix test execution on Bookworm

- sonic_package_manager/manager.py
- tests/sonic_package_manager/test_manager.py
In case feature's YANG model has a constraint on FEATURE table:
```
must "current() = \"disabled\" or /feature:sonic-feature/feature:FEATURE/feature:FEATURE_LIST[feature:name=\"Y\"]/feature:state = \"enabled\"" {
error-message "X can only be set when is Y enabled";
}
```
it will fail to upgrade due to transient disablement of the feature by the upgrade process.
The upgrade process looks like this:
1. Disable feature via FEATURE table and wait for container to go down.
2. Remove all configuration files generated for this feature.
3. Create new configuration files for new docker image.
4. Merge new init_cfg from the new docker image and perform YANG validation.
5. Enable feature via FEATURE table.
6. Remove old docker image.
Since there is a transient enable/disable of the feature and YANG …
> [sonic-package-manager] Fix YANG validation failure on upgrade when feature has constraints in YANG model on FEATURE table

- sonic_installer/common.py
- sonic_installer/exception.py
- tests/test_sonic_installer.py
* Extended exception class with user notes
* Implemented new API
* Run UTs
```
File "/usr/local/bin/sonic_installer", line 8, in <module>
sys.exit(sonic_installer())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
File "/usr/local/lib/python3.9/dist-packages/click/core.py", …
```
> [sonic_installer]: Improve exception handling: introduce notes.

- doc/Command-Reference.md
- setup.py
- tests/wol_test.py
- wol/main.py
Implement `wol` command-line utility based on [Wake-on-LAN-HLD.md](https://github.com/sonic-net/SONiC/blob/master/doc/wol/Wake-on-LAN-HLD.md).
Add unittest to verify code.
> [wol] Implement wol command line utility

- config/vlan.py
- tests/vlan_test.py
Fix issue: https://github.com/sonic-net/sonic-buildimage/issues/15047 of after deleting vlan member and vlan, the counters for for vlan / vlan member are still seen.
Delete related counter entry in state_db when deleting vlan and vlan members.
1. All UTs passed
2. Manually test
```
admin@sonic:~$ show dhcp_relay ipv4 counter -i Vlan1001
Message Type    Vlan1001(RX)
--------------  --------------
Ack               0
Decline               0
Discover               2
Inform               0
Nak               0
Offer               0
Release               0
Request               0
Unknown               0
Message Type    Vlan1001(TX)
--------------  --------------
Unknown               0
Discover               0
Offer               0
Request               0
Decline               0
Ack …
```
> [dhcp_relay] Fix dhcp_relay counter display issue

- scripts/generate_dump
Add the core files to the tarball while they are been processed, this ensures that only one core file at a time will be consuming flash space inside the tarpath and the tarball.
> Reduce generate_dump mem usage for cores

- scripts/teamd_increase_retry_count.py
For each BGP status, if the `admin_status` field is not present, then whether the BGP session is admin up or admin down depends on the default BGP status (in the `default_bgp_status` field coming from `init_cfg.json`), which is specified during image build. If the default BGP status is up, then `admin_status` will be created only when the BGP session is brought down; similarly, if the default BGP status is down, then `admin_status` will be created when the BGP session is brought up.
Because of that, modify the script to use the default BGP status as the initial value.
Tested on KVM and verified that the list of port channels seen were correct in the following cases:
* `default_bgp_status: down`, `config load_minigraph`
* `default_bgp_status: down`, `config load_minigraph`, `config bgp …
> Modify teamd retry count script to base BGP status on default BGP status

- scripts/route_check.py
- tests/route_check_test.py
- tests/route_check_test_data.py
Otherwise it fills up the pipe and print() will block. When this happens, `route_check.py` will timeout and eventually killed by `monit` after several minutes.
Request to cast the change to `202305` branch.
Add an option in `print_message()` to skip printing.
Add an option `write_to_stdout=True`, in `mitigate_installed_not_offloaded_frr_routes()` call `print_message()` with `write_to_stdout=False`.
Manually run route_check.py, verify that the messages were shown in syslog but not in stdout.
> route_check.py should not print too many outputs to stdout

- scripts/db_migrator.py
- tests/db_migrator_test.py
Create version name space for 202311/202305 branch.
Add unit test for version compare function.
This change is non-functional. This PR test should be all the needed tests.
> [db_migrator] add db migrator version space for 202311 branch

- scripts/db_migrator.py
- tests/db_migrator_test.py
Create version name space for 202311/202305 branch.
Add unit test for version compare function.
This is a non-functional change. this PR test is sufficient.
> [202311][db_migrator] add db migrator version space for 202311 branch

- scripts/db_migrator.py
- tests/db_migrator_test.py
Create version name space for 202305 branch.
Add unit test for version compare function.
This is a non-functional change. this PR test is sufficient.
> [202305][db_migrator] add db migrator version space for 202305 branch

- config/syslog.py
- doc/Command-Reference.md
- tests/syslog_test.py
Depends on PR https://github.com/sonic-net/sonic-buildimage/pull/17458
Add CLIs to enable/disable containercfgd to optimize warm/fast boot path
Add CLIs to enable/disable containercfgd
unit test
manual test
> Support disable/enable syslog rate limit feature

- scripts/db_migrator.py
- tests/db_migrator_test.py
db_migrator failed to initialize SonicDBConfig, and I fix this issue.
If SonicDBConfig is already initialized, do not invoke initialize() again.
Run unit test, and verified on DUT.
> Fix database initialization for db_migrator

- sonic_installer/bootloader/grub.py
Disabling key validation feature in grub file as its not yet supported for Cisco platforms 
1. Check if the platform we are installing the image on is a Cisco platform
2. Return success if it is so we are on Cisco platform. This way, we do not perform signature verification as this feature is not yet supported on our platforms.
Modified sonic-installer grub.py code
Use sonic-installer command without this fix and try to downgrade from 202305 image to 202205 image, you will see the error. With this fix, the image will be installed
```
root@yy39-rp:/home/cisco# sonic-installer install sonic-cisco-8000.bin
New image will be installed, continue? [y/N]: y
Verifing image SONiC-OS-azure_cisco_202205.0-dirty-20231023.141040 signature...
Verifying image signature
Failure: CMS signature …
```
> Disable Key Validation feature on 202305 branch for Cisco Platforms

- scripts/route_check.py
- tests/route_check_test.py
- tests/route_check_test_data.py
Reverts sonic-net/sonic-utilities#3075
This change and #3077 has prevented sonic-utilities repo submodule head moving for a month.
> Revert "route_check: Skip route checks if bgp feature is not enabled"

- scripts/route_check.py
- scripts/route_check_test.sh
- tests/route_check_test.py
- tests/route_check_test_data.py
Reverts sonic-net/sonic-utilities#3077
This change caused sonic-buildimage submodule advance PRs failing and blocked the submodule advance.
> Revert "Enhanced route_check.py for multi_asic platforms"

- doc/Command-Reference.md
- scripts/generate_dump
- sfputil/main.py
- tests/sfputil_test.py
Backport pR: https://github.com/sonic-net/sonic-utilities/pull/3009
Add a new CLI sfputil eeprom-hexdump-all to dump all pages for module
Support collecting module EEPROM in show techsupport command
HLD: https://github.com/sonic-net/SONiC/pull/1476
Manual test
Unit test
Regression test
```
EEPROM hexdump for module 1
Lower page 0h
00000000 11 08 06 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000010 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000020 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000030 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000040 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000050 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................| …
```
> [202311] Collect module EEPROM data in dump (#3009)

- azure-pipelines.yml
The current 202205 branch build of sonic-swss-common has failing test cases. This is blocking sonic-utilities, since this is the only build available in that branch.
Allow using that build even though tests are failing, to unblock PRs in this repo.
> [202205] Allow using latest sonic-swss-common build even if tests failed

- doc/Command-Reference.md
- sfputil/main.py
- tests/sfputil_test.py
Backport PR to 202311: https://github.com/sonic-net/sonic-utilities/pull/3008
Add two CLIs:
- sfputil read-eeprom
- sfputil write-eeprom
Allow user to read/write EEPROM by page and offset
See design:
https://github.com/sonic-net/SONiC/pull/1475
Unit test
```
sfputil read-eeprom Ethernet0 0 100 2
00000064 4a 44                                            |..|
sfputil read-eeprom Ethernet0 0 0 32
00000000 11 08 06 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000010 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
sfputil read-eeprom Ethernet0 0 100 2 --no-format
4a44
```
> [202311] Support reading/writing module EEPROM data by page and offset (#3008)

- config/main.py
- tests/config_test.py
Resolve cherry-pick conflict for PR #3031 
tests/config_test.py::TestConfigReload::test_config_reload_stdin PASSED  [ 12%]
tests/config_test.py::TestReloadConfig::test_reload_config_invalid_input PASSED [ 12%]
tests/config_test.py::TestReloadConfig::test_reload_config_no_sysinfo PASSED [ 12%]
tests/config_test.py::TestReloadConfig::test_reload_config PASSED        [ 13%]
tests/config_test.py::TestReloadConfig::test_config_reload_disabled_service PASSED [ 13%]
tests/config_test.py::TestReloadConfig::test_reload_config_masic PASSED  [ 13%]
> [config] config reload should generate sysinfo if missing  (#3031)

- config/main.py
- tests/sflow_test.py
This is to backport #2847 to 202205
Fixed issue: out of range sflow polling interval is accepted and stored in config_db.
Reproduce step:
```
1. Enable sflow feature:   config feature state sflow enabled
2. Enable sflow itself:   config sflow enable
3. Configure out of range polling interval:  config sflow polling-interval 1. Error message is shown as expected
4. Save config:    config save -y
5. Check "SFLOW" section inside config_db
```
As the interval is invalid, the expected behavior is that the interval is not saved to redis. But we see the invalid value was written to redis.
Change `click.echo` to `ctx.fail`
1. Manual test
2. Add a check in existing unit test case to cover the change
> [202205] Fix issue: out of range sflow polling interval is accepted and stored in config_db (#2847)

- scripts/fast-reboot
- scripts/teamd_increase_retry_count.py
- setup.py
This backports a part of #3069 to allow upgrading from 202205 to 202305 with the teamd retry count feature.
Did a warm reboot on 202205 KVM image and verified that the teamd retry count script ran.
> [202205] Add teamd retry count script to 202205 image

- scripts/route_check.py
- tests/route_check_test_data.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/17877
Added additional check to skip FRR-Offloaded check if the routeSrc BGP was not selected as best.
Ran the script on multi-asic KVM device, and could confirm the route_check is passing.
> [Master]: Additional check to skip FRR-Offloaded check if the bgp route-src was not selected as best

- scripts/db_migrator.py
- tests/db_migrator_input/config_db/gnmi-configdb-expected.json
- tests/db_migrator_input/config_db/gnmi-input.json
- tests/db_migrator_input/config_db/gnmi-minigraph-expected.json
- tests/db_migrator_test.py
We will use GNMI container to replace TELEMETRY container in public repo.
GNMI is using GNMI table for configuration, so we need to migrate configuration in CONFIG_DB.
For L2 mode, there's no GNMI configuration in minigraph, and there's no TELEMETRY table in CONFIG_DB, so we will not generate GNMI table.
Backport https://github.com/sonic-net/sonic-utilities/pull/3053
If there's no minigraph and golden config, copy GNMI configuration from TELEMETRY table.
If there're minigraph and golden config, copy GNMI configuration from minigraph or golden config.
Run db migrator unit test, test with minigraph and test without minigraph.
> [202311] Migrate GNMI table

- scripts/mellanox_buffer_migrator.py
- tests/db_migrator_input/config_db/empty-config-with-device-info-generic-expected.json
- tests/db_migrator_input/config_db/empty-config-with-device-info-generic-input.json
- tests/db_migrator_input/config_db/empty-config-with-device-info-traditional-expected.json
- tests/db_migrator_input/config_db/empty-config-with-device-info-traditional-input.json
- tests/db_migrator_test.py
Do not touch the buffer model on generic SKUs if the buffer configuration is empty.
Set the buffer model to traditional on generic SKUs in Mellanox db migrator only if the buffer configuration is not default and not empty.
Manually and mock test.
Buffer configuration contains two parts:
1. the buffer model in `DEVICE_METADATA|localhost` which is from `init_cfg.json` and can be updated by Mellanox buffer migrator
2. the buffer pools, profiles, PGs, and queues which are renderred from the buffer templates in `config qos reload`
There was a logic to update the buffer model in Mellanox buffer migrator: if the buffer configuration is not default, the buffer model is set to traditional. However, if a device is installed from ONIE, the buffer configuration is also empty. As a result, the …
> [Mellanox buffer migrator] Do not touch the buffer model on generic SKUs if the buffer configuration is empty

- scripts/generate_dump
Add support of the nvidia-bluefield platform to generate-dump utility to collect platform-specific dumps on NVIDIA Bluefield DPU.
Extend platform-specific section of generate-dump utility
Run "show techsupport" command to generate dump file. Verify that `platform-dump` directory exists in the created dump file.
> Add support of the nvidia-bluefield platform to generate-dump utility.

- doc/Command-Reference.md
- sfputil/main.py
Fix the sfputil treats page number as decimal instead of hexadecimal
https://github.com/sonic-net/sonic-utilities/pull/3009 breaks the number base rule, treats the page number CLI input as decimal rather than hex, this is used to fix it.
it also containes a redundancy function definition, so remove it.
unit test and manually test
```
sudo sfputil show eeprom-hexdump -n 10 -p Ethernet32
EEPROM hexdump for port Ethernet32 page 10h
Lower page 0h
00000000 0d 06 06 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000010 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000020 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000030 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000040 00 00 00 00 00 00 00 00  00 00 00 …
```
> Fix the sfputil treats page number as decimal instead of hexadecimal

- doc/Command-Reference.md
- sfputil/main.py
Manual cherry-pick of (#3153)
Fix the sfputil treats page number as decimal instead of hexadecimal
---------
https://github.com/sonic-net/sonic-utilities/pull/3009 breaks the number base rule, treats the page number CLI input as decimal rather than hex, this is used to fix it.
it also containes a redundancy function definition, so remove it.
unit test and manually test
> [202311]Fix the sfputil treats page number as decimal instead of hexadecimal 

- show/main.py
- tests/show_test.py
ADO: 26574293
Update `show runningconfiguration all` to cover asics config
Loop host and each asic to get config, then combine into one.
Unit test
```
admin@str3-7800-lc3-1:~$ show runningconfiguration all
{
"ACL_TABLE": {
...
},
...
}
```
```
admin@str3-7800-lc3-1:~$ show runningconfiguration all
{
"localhost": {
"ACL_TABLE": {
...
},
...
},
"asic0": {
"ACL_TABLE": {
...
},
...
},
...
}
```
> [show] Update show run all to cover all asic config in multiasic

- config/main.py
Fix  https://github.com/sonic-net/sonic-utilities/issues/3164
Check Golden Config earlier before service is down.
Move the check at the begining
Unit test
> [config] Check golden config exist early if flag is set

- sfputil/main.py
- tests/sfputil_test.py
This PR is to fix issue https://github.com/sonic-net/sonic-utilities/issues/3167
Basically sfputil Cli became broken on multi-asic platforms after introduction of https://github.com/sonic-net/sonic-buildimage/pull/10960 which removed the initialization of global DB config from portconfig.py (library side) and expects application to do it, but here application side (sfputil) was not updated accordingly. 
Add load_db_config call to sfputil for initialization
Before fix:
```
root@sonic:/home# sfputil show presence                                                                                                                                                                                     
Error reading port info (:- validateNamespace: Initialize global DB config using API …
```
> Fix sfputil CLI failure for multi-asic platforms

- scripts/sfpshow
MSFT ADO - 26894627
As part of the code changes through https://github.com/sonic-net/sonic-platform-common/pull/442, for the VDM fields which are not implemented by a vendor, "N/A" will be set in redis-db for such fields.
This change is breaking the "show int transceiver pm <port_name>" CLI since it parses the TRASNCEIVER_DOM_THRESHOLD table and converts the values to float. However, the handler of the CLI needs to be modified to ensure that "N/A" value is not converted to float.
The function `convert_interface_sfp_pm_to_cli_output_string` now doesn't convert `sfp_threshold_dict[key]` to float if the value is `N/A`.
```
root@admin:/home/admin# show int transceiver pm -n asic0 Ethernet88
Ethernet88: 
Parameter        Unit    Min       Avg       Max       Threshold    Threshold    Threshold …
```
> Modify transceiver PM CLI to handle N/A value for DOM threshold

- scripts/sfpshow
- sfputil/main.py
- tests/mock_tables/asic1/state_db.json
- tests/mock_tables/state_db.json
- tests/sfputil_test.py
Since we are moving active_firmware and inactive_firmware fields from TRANSCEIVER_INFO to TRANSCEIVER_FIRMWARE_INFO table (https://github.com/sonic-net/sonic-platform-daemons/pull/435 and https://github.com/sonic-net/sonic-platform-common/pull/440), following changes are needed to support existing CLIs
1. Modify "show int transceiver eeprom" o/p to include firmware information from TRANSCEIVER_FIRMWARE_INFO table
2. Modify "sfputil show eeprom" o/p to remove `active_firmware` and `inactive_firmware` fields from the output.
Reasoning for removing the fields
For transceivers supporting firmware version read through CDB command, a CDB command will be sent to the module. Parallelly, the DomInfoUpdateTask thread from xcvrd performs periodic firmware version reads. Hence, this could cause …
> CLI enhancements to revtrieve data from TRANSCEIVER_FIRMWARE_INFO table

- config/main.py
- tests/ip_config_test.py
~
Fix for https://github.com/sonic-net/sonic-buildimage/issues/16975
Prevent configuration of illegal Vlan name in "config interface ip add" command
Added Vlan name validation
config interface ip add Vlan100 1.1.1.1/24
config interface ip add Vlan4093 1.1.1.1/24
config interface ip add Vlan000000000000003 1.1.1.1/24
config interface ip add Vlan01 1.1.1.1/24
config interface ip add Vlan1.2 1.1.1.1/24
On illegal Vlan name command succeeded with no error
config interface ip add Vlan030 1.1.1.1/24
Error: Vlan030 is not a valid Vlan name
> Add vlan validation in config interface ip add command

- scripts/fast-reboot
MSFT ADO: 26918588
This change is to add ERR logs generated during warm-reboot script to syslog.
Currently the ERR logs are sent in stdout and a corresponding entry is not added to syslog.
This makes it difficult to debug issues when stdout is not readily available.
Modified existing error function to add the log entry to syslog.
Verified manually on physical device
W/o this fix:
Simulated a failure and confirmed that error is not captured in syslog.
```
Mar  1 23:56:22.060584 str2-7060cx-32s-29 NOTICE admin: Starting warm-reboot
Mar  1 23:56:23.756585 str2-7060cx-32s-29 NOTICE admin: Saving counters folder before warmboot...
Mar  1 23:56:26.049133 str2-7060cx-32s-29 NOTICE admin: warm-reboot failure (1) cleanup ...
Mar  1 23:56:27.076923 str2-7060cx-32s-29 NOTICE admin: Cancel …
```
> [fast/warm-reboot] Put ERR message in syslog when a failure is seen

- config/main.py
- tests/config_override_input/aaa_yang_hard_check.json
- tests/config_override_test.py
ADO: 26732148 
Add YANG hard depdency check for AAA and TACPLUS table
Add a special check
Unit test
> [config] Add Table hard dependency check

- config/main.py
- doc/Command-Reference.md
- tests/config_xcvr_test.py
MSFT ADO - 26801913
Created a CLI to enable/disable periodic polling through DomInfoUpdateTask thread in XCVRD.
The CLI handler related code changes in xcvrd can be found at https://github.com/sonic-net/sonic-platform-daemons/pull/443
With https://github.com/sonic-net/sonic-platform-daemons/pull/443, the DomInfoUpdateTask thread in xcvrd now polls periodically for reading CDB firmware version of transceiver to update the TRANSCEIVER_FIRMWARE_INFO table.
However, transceivers cannot handle multiple CDB commands issued from different sources at the same time.
This scenario is likely to occur during CDB firmware upgrade (triggered through `sfputil firmware download/run/commit`) and while issuing `sfputil show fwversion PORT_NAME` CLI wherein 1 or more CDB commands are issued to the …
> CLI to skip polling for periodic information for a port in DomInfoUpdateTask thread

- tests/show_test.py
ADO: 27108147
Clean up TOPO residue left for multi-asic test
change topo to default
unit test in 202205-chassis
> [show] clean up residue of multi-asic show runningconfig test

- sonic_installer/bootloader/uboot.py
The bug can be reproduced by the following command:
```
root@bjw-can-7215-6:/home/admin# sonic-installer set-fips
Command: /usr/bin/fw_setenv linuxargs net.ifnames=0 loopfstype=squashfs loop=image-fips-armhf-202305.88981472-dde4d1d844/fs.squashfs systemd.unified_cgroup_hierarchy=0 varlog_size=4096 loglevel=4 logs_inram=on sonic_fips=1
Error: illegal character '=' in variable name "loopfstype=squashfs"
```
It is to set the variable linuxargs to the the environment value cmdline, as the part of the Linux Kernel Cmdline. The environment variable cannot be split.
> [Bug] Fix fw_setenv illegel character issue

- acl_loader/main.py
- config/main.py
- tests/acl_loader_test.py
This PR is to fix a racing condition in system bootup path.
In the system bootup path, `config-setup` service will call `config load_minigraph` if it's the first startup, and then `/etc/sonic/acl.json` is loaded by `config load_minigraph`.
If `orchagent` hasn't written `ACL_STAGE_CAPABILITY_TABLE` or `SWITCH_CAPABILITY_TABLE` into `STATE_DB` before being terminated, then the dataplane ACL rules defined in `/etc/sonic/acl.json` is skipped.
This PR is to fix the racing condition by adding an option `skip_action_validation` to `acl-loader`.  If the option `skip_action_validation` is true, and `ACL_STAGE_CAPABILITY_TABLE` or `SWITCH_CAPABILITY_TABLE` is empty, the action validation is skipped.
This PR added an option `skip_action_validation` to `acl-loader`.  If the option …
> Skip the validation of action in acl-loader if capability table in STATE_DB is empty

- scripts/generate_dump
Handle the SAI key value pair if it is present in sai common profile rather than specific profile for mellanox platforms. The concept of common sai profile is introduced in https://github.com/sonic-net/sonic-buildimage/pull/18074 . After this the techsupport started to fail because of the absence of SAI_DUMP_STORE_PATH
Check if the variable is not present in platform specific file and then read the common file. If the common file is not accessible due to syncd being down, fallback to default path which is hardcoded.
Running techsupport and ensuring it exits with code 0
> [Techsupport]Handle SAI kv pair if present in sai common profile

- show/main.py
- utilities_common/bgp_util.py
bgp is not supported on Supervisor card,  "show runningconfiguration all" fails on the Supervisor since the bgp services is disable. Add code to check if bgp state in the FEATURE table is able before it tries to get the BGP configuration to avoid the error. Fix issue https://github.com/sonic-net/sonic-buildimage/issues/18276
Since BGP feature state is disabled in the FEATURE table on Supervisor card, add method is_bgp_feature_state_enabled() to the bgp_util.py check the BGP feature state.  Modify the "show runningconfiguration all" to call the is_bgp_feature_state_enabled(), then call the run_ngp_show _command to get the bgp configuration.
1) Execute the "show runningconfiguration all" command on Supervisor. The following output should be shown without any error.
``` …
```
> [master][chassis][show-runningconfig] Fix the show runningconfiguration all issue on the Supervisor

- scripts/ipintutil
- tests/mock_tables/mock_single_asic.py
- tests/show_ip_int_test.py
Handle exception in show ip interfaces command when executed during config reload. Sometimes during config reload the interfaces are removed and if show ip interfaces was executed during this time we may get the below traceback. The interface would exist when the call multi_asic_get_ip_intf_from_ns was made but would have been removed in the subsequent for loop which tries to get ip interface data for each interface
```
File "/usr/local/bin/ipintutil", line 276, in
main()
File "/usr/local/bin/ipintutil", line 269, in main
ip_intfs = get_ip_intfs(af, namespace, display)
File "/usr/local/bin/ipintutil", line 232, in get_ip_intfs
ip_intfs_in_ns = get_ip_intfs_in_namespace(af, namespace, display)
File "/usr/local/bin/ipintutil", line 153, …
```
> [ipintutil]Handle exception in show ip interfaces command

- scripts/reboot
**DEPENDS ON: [[graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle #18324](https://github.com/sonic-net/sonic-buildimage/pull/18324)**
Add the `pre_reboot_hook` script execution, add the watchdog arm before the reboot, in order to support the `graceful reboot` instead of the sysfs power cycle, to avoid filesystem corruption.
Modify the `scripts/reboot`
1. Start watching logs by using `show log -f` and `journalctl -p debug -f`
2. Execute the `reboot` command from the switch CLI
3. Check in logs that all systemd services terminated correctly
> [graceful reboot] Add the pre_reboot_hook script execution, add the watchdog arm before the reboot 

- scripts/port2alias
What I did
Basically `port2alias` Cli became broken on multi-asic platforms after introduction of https://github.com/sonic-net/sonic-buildimage/pull/10960 which removed the initialization of global DB config from portconfig.py (library side) and expects application to do it, but here application side (`port2alias`) was not updated accordingly.
How I did it
Add load_db_config call to `port2alias` for initialization
How to verify it:
Before fix
```
admin@svcstr2-xxxx-lc3-1:/usr/local/bin$ show interface status | port2alias
File "/usr/local/bin/port2alias", line 60, in <module>
main()
File "/usr/local/bin/port2alias", line 54, in main
(ports_ns, _, _) = get_port_config(hwsku=hwsku, platform=platform, asic_name=ns)
File …
```
> Update port2alias to work for multi-asic systems.

- scripts/route_check.py
- scripts/route_check_test.sh
- tests/route_check_test.py
- tests/route_check_test_data.py
Enhanced route_check.py script to cover multi-asic platforms.
Accordingly enhanced the test files as well.
MSFT ADO: 25416673
Enhanced the route_check.py script to take additional optional parameter(--n/namespace). Without this parameter, the check will be run on all asics in multi-asic platforms.
Different connections to DBs are modified accordingly to connect to relevant ns dbs.
Result will be encapsulated under different namespace. For single asic, results will be displayed under Default-Namespace("").
testData and the testfiles are enhanced accordinly.
1. Verified that all pytest UT cases are passing.
2. Verified the route_check_test.sh script on single asic and multi-asic platforms.
3. Verified Monit routecheck outputs by simulating a failure scenario on both single asic and …
> Enhance route-check for multi-asic platforms

- tests/mock_tables/state_db.json
- tests/sfp_test.py
- utilities_common/sfp_helper.py
With the below PR, we are now storing `cmis_state` in `TRANSCEIVER_STATUS` table of `STATE_DB`. Hence, we need to modify the `show interface transceiver status` CLI to show the software `cmis_state` of a port
https://github.com/sonic-net/sonic-platform-daemons/pull/449
MSFT ADO - 27254777
Added `cmis_state` in `QSFP_STATUS_MAP` to display it for all types of transceivers which have this field populated.
1. Dumped o/p of `show int transceiver status` with the `cmis_state` field present in TRANSCEIVER_STATUS table
2. Dumped o/p of `show int transceiver status` with the `cmis_state` field absent in TRANSCEIVER_STATUS table
```
root@sonic:/home/admin# show int transceiver status Ethernet256
Ethernet256: 
CMIS State (SW): READY
Tx fault flag on media lane 1: False
Rx loss of signal flag on …
```
> Modify "show interface transceiver status" CLI to show SW cmis state

- utilities_common/platform_sfputil_helper.py
For T2-Chassis VS support, we are adding new sonic_platform package for vs platforms. Please refer https://github.com/sonic-net/sonic-buildimage/pull/18512 for more details.
Due to this new platform package, need to modify excpetion handling as now the Module would be found, but the metadata file will not be found for pizzabox vs platforms.
Modified the exception handling logic.
MSFT ADO: 27414904
Bring up vms-kvm-t0 topology. ran show interface status. The output is proper.
PS: the Main PR(https://github.com/sonic-net/sonic-buildimage/pull/18512) is dependent on this PR to be merged in first.
> T2-VOQ-VS: Modified exception handling due to new sonic_platform package support for VS

- .github/workflows/semgrep.yml
- generic_config_updater/change_applier.py
Semgrep's default ruleset (p/default) somehow lost some important rules
Keep use p/default and add another rule
Added test code to this PR and Semgrep CI failed
```
diff --git a/generic_config_updater/change_applier.py b/generic_config_updater/change_applier.py
index d0818172..6e1473a4 100644
--- a/generic_config_updater/change_applier.py
+++ b/generic_config_updater/change_applier.py
@@ -169,6 +169,7 @@ class ChangeApplier:
def _get_running_config(self):
(_, fname) = tempfile.mkstemp(suffix="_changeApplier")
os.system("sonic-cfggen -d --print-data > {}".format(fname))
+        os.system("sonic-cfggen -d --print-data > {}".format(fname))
run_data = {}
with open(fname, "r") as s:
run_data = json.load(s)
```
Failed result: https://github.com/sonic-net/sonic-utilities/actions/runs/8559846841/ …
> Improve Semgrep CI

- config/plugins/mlnx.py
- tests/config_mlnx_test.py
Fixing mellanox related warnings in https://github.com/sonic-net/sonic-buildimage/issues/18401
Fix syntax warnings when config platform mlnx command is executed
```
dmin@sonic:~$ sudo config /usr/local/lib/python3.11/dist-packages/config/aaa.py:120: SyntaxWarning: "is" with a literal. Did you mean "=="?
if len(auth_protocol) is 0:
/usr/local/lib/python3.11/dist-packages/config/plugins/mlnx.py:219: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if err is not 0:
/usr/local/lib/python3.11/dist-packages/config/plugins/mlnx.py:232: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if err is not 0:
/usr/local/lib/python3.11/dist-packages/config/aaa.py:120: SyntaxWarning: "is" with a literal. Did you mean "=="?
if len(auth_protocol) is 0: …
```
> [Mellanox]Fix Syntax Warning in config mlnx command

- scripts/intfutil
- scripts/sfpshow
- tests/intfutil_test.py
- tests/mock_tables/appl_db.json
- tests/mock_tables/config_db.json
- tests/mock_tables/state_db.json
- tests/sfp_test.py
Added support for new role type. New role is shown as "DPU-NPU Data Port" in the output of "show interface status"
output for sfpshow commands doesn't show an output for internal ports.
Requires: https://github.com/sonic-net/sonic-buildimage/pull/18465
Output with role set
```
root@mtvr-leopard-01:/home/admin# show interfaces status
Interface                            Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin                                             Type    Asym PFC
-----------  -------------------------------  -------  -----  -----  -------  ------  ------  -------  -----------------------------------------------  ----------
Ethernet0                  0,1,2,3,4,5,6,7     400G   9100    N/A     etp1  routed    down       up  QSFP-DD Double Density 8X Pluggable …
```
> Update intfutil and sfpshow to support DPC role

- scripts/reboot
**DEPENDS ON: [[202311][graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle #18325](https://github.com/sonic-net/sonic-buildimage/pull/18325)**
Add the `pre_reboot_hook` script execution, add the watchdog arm before the reboot, in order to support the `graceful reboot` instead of the sysfs power cycle, to avoid filesystem corruption.
Modify the `scripts/reboot`
1. Start watching logs by using `show log -f` and `journalctl -p debug -f`
2. Execute the `reboot` command from the switch CLI
3. Check in logs that all systemd services terminated correctly
> [202311][graceful reboot] Add the pre_reboot_hook script execution, add the watchdog arm before the reboot

- scripts/reboot
**DEPENDS ON: [[202305][graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle #18250](https://github.com/sonic-net/sonic-buildimage/pull/18250)**
Add the `pre_reboot_hook` script execution, add the watchdog arm before the reboot, in order to support the `graceful reboot` instead of the sysfs power cycle, to avoid filesystem corruption.
Modify the `scripts/reboot`
1. Start watching logs by using `show log -f` and `journalctl -p debug -f`
2. Execute the `reboot` command from the switch CLI
3. Check in logs that all systemd services terminated correctly
> [202305][graceful reboot] Add the pre_reboot_hook script execution, add the watchdog arm before the reboot

- scripts/generate_dump
Added get component versions to techsupport
get_component_versions.py is a script that output a table that gathers the versions of all the Nvidia-related components in SONiC.
This PR depends on https://github.com/sonic-net/sonic-buildimage/pull/18591 and should be merged second.
> [Mellanox] added component versions to techsupport

- config/syslog.py
- doc/Command-Reference.md
- show/syslog.py
- syslog_util/common.py
- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/asic1/config_db.json
- tests/mock_tables/config_db.json
- tests/syslog_multi_asic_test.py
- tests/syslog_test.py
Build dependency https://github.com/sonic-net/sonic-buildimage/pull/18459
Add multi ASIC support for syslog rate limit feature
1. `show syslog rate-limit-container` add a new option namespace
2. `config syslog rate-limit-container` add a new option namespace
3. `config syslog rate-limit-feature` enable add a new option namespace and a new argument service_name
4. `config syslog rate-limit-feature` disable add a new option namespace and a new argument service_name
Manual test
show syslog rate-limit-container help:
```
show syslog rate-limit-container --help
Usage: show syslog rate-limit-container [OPTIONS] <service_name>
Show syslog rate limit configuration for containers
Options:
-h, -?, --help  Show this message and exit.
```
config syslog rate-limit-container help
```
sudo config syslog …
```
> Add multi ASIC support for syslog rate limit feature

- generic_config_updater/gcu_field_operation_validators.conf.json
Add support for a new platform x86_64-nvidia_sn5400-r0
Manual and unit test
> Support new platform SN5400 in generic configuration update

- scripts/route_check.py
- tests/route_check_test.py
- tests/route_check_test_data.py
Reverts sonic-net/sonic-utilities#3121
If bgp is not enabled, get_frr_routes() gets empty list and route check fails and throws a traceback. Adding check to to skip route checks  bgp feature is disabled. On the Chassis supervisor, bgp may be disabled. 
Signed-off-by: Anand Mehra anamehra@cisco.com
> Revert "Revert "route_check: Skip route checks if bgp feature is not enabled""

- scripts/fast-reboot
Retain TRANSCEIVER_INFO tables on fast/warm reboot. The PHY isn't reset on fast/warm reboot. Knowing about plugged modules is required for orchagent to set SAI_PORT_ATTR_HOST_TX_SIGNAL_ENABLE=true on start.
Save TRANSCEIVER_INFO tables on warm/fast-reboot.
Run fast/warm-reboot.
> [fast/warm-reboot] Retain TRANSCEIVER_INFO tables on fast/warm-reboot

- config/fabric.py
- scripts/fabricstat
- show/fabric.py
- tests/config_fabric_test.py
- tests/fabricstat_test.py
- tests/mock_tables/config_db.json
Add a force option for config fabric port unisolate command. 
Add a show command to display if a up link is get isolated or not . Example output is :
```
asic0
Local Link    Auto Isolated    Manual Isolated    Isolated
------------  ---------------  -----------------  ----------
0                0                  0           0
1                0                  0           0
2                0                  0           0
....
```
Add test for the new commands. 
The test is failed now as it needs this https://github.com/sonic-net/sonic-swss/pull/3089 merged in first.
> Add fabric monitoring commands.

- config/main.py
- generic_config_updater/change_applier.py
- generic_config_updater/generic_updater.py
- generic_config_updater/gu_common.py
- tests/config_test.py
- tests/generic_config_updater/change_applier_test.py
- tests/generic_config_updater/multiasic_change_applier_test.py
- tests/generic_config_updater/multiasic_generic_updater_test.py
Add Multi-ASIC GCU support apply-patch.
1. Categorize configuration as JSON patch format per ASIC.
2. Apply patch per ASIC, including localhost.
**Happy case**
**Reverse case**
**Failed case**
**Empty case**
> Add Multi ASIC support for apply-patch

- scripts/sfpshow
- tests/mock_tables/asic1/state_db.json
- tests/mock_tables/state_db.json
- tests/sfp_test.py
- utilities_common/sfp_helper.py
XCVRD is now periodically storing target firmware versions in TRANSCEIVR_FIRMWARE_INFO table of STATE_DB (https://github.com/sonic-net/sonic-platform-common/pull/455).
This change is to display the target firmware versions using `show interfaces transceiver eeprom EthernetXX` and `show interfaces transceiver info EthernetXX` CLI.
MSFT ADO - 27706023
The transceiver EEPROM/INFO dump CLI now reads target firmware information from the TRANSCEIVR_FIRMWARE_INFO table of STATE_DB. This is done only for the transceivers which have their target firmware version information populated in the TRANSCEIVR_FIRMWARE_INFO table.
Please refer to the testcases described in https://github.com/sonic-net/sonic-platform-common/pull/455 for further details.
snippet of `show interfaces transceiver info …
> Display target firmware version through CLI

- config/main.py
- tests/ip_config_test.py
- tests/vlan_test.py
In the test_po_update test case, one of the things done there is to remove an IP address from a port channel interface. As part of that, the current handling for that issues a `ip neigh flush dev ...` command, added in sonic-net/sonic-utilities#606, presumably to remove old neighbor entries that would no longer be valid. I would think that the kernel would automatically do this, but maybe it didn't back then; I'm not sure if there's been a behavior change here since then.
In some cases, this command is returning an error, saying "Failed to send flush request: No such file or directory". I'm not sure why this is; maybe when iproute2 is going through the list of neighbors, some neighbor entry was there, but then by the time it issued the deletion request, that neighbor entry was removed by …
> Run `ip neigh flush` before removing the IP address from the interface

- config/plugins/mlnx.py
This PR should be merged before PR: https://github.com/sonic-net/sonic-buildimage/pull/18711
Change the target path for SDK Sniffer from "/var/log/mellanox/sniffer/" To: "/var/log/sdk_dbg"
Change the default for SDK_SNIFFER_TARGET_PATH
Run SDK sniffer and make sure the sniffer output file kept in the new location
> [Mellanox] Update SDK sniffer default target folder

- scripts/reboot
Modify the "sudo reboot" script to notify the Supervisor card by creating/inserting CHASSIS_MODULE_REBOOT_INFO_TABLE|LINE-CARD#" entry to CHASSIS_STATE_DB when reboot command is issued on the Linecard. This provides the sufficient information to allow Supervisor to log a proper message to address issue https://github.com/sonic-net/sonic-buildimage/issues/18540
Add a new function linecard_reboot_notity_supervisor() to the reboot script.  If this platform is a linecard in a chassis, call sonic-db-cli to add a "CHASSIS_MODULE_REBOOT_INFO_TABLE|LINE-CARD#" to the CHASSIS_STATE_DB.  This provides the information to chassisd on Supervisor card to log a proper message.
This PRs requires the following 2 PRs to address issue https://github.com/sonic-net/sonic-buildimage/issues/18540 : …
> [chassis][midplane] Add notification to Supervisor when LC is graceful reboot

- show/main.py
- tests/conftest.py
- utilities_common/bgp_util.py
Modify `show run all` to display rest config when bgp is down
Add param in bgp_util's run_bgp_show_command to not exit when bgp down
unit test
```
admin@bjw-can-7260-11:~$ show run all
Error response from daemon: Container be60f9fe81c04ece34e5dea6aaa259283dc6d2aacfab14c2c5c402e607e20db4 is not running
admin@bjw-can-7260-11:~$ 
```
```
admin@bjw-can-7260-11:~$ show run all | more
Error response from daemon: Container be60f9fe81c04ece34e5dea6aaa259283dc6d2aacfab14c2c5c402e607e20db4 is not running
{
"ACL_TABLE": {
"DATAACL": {
"policy_desc": "DATAACL",
"ports": [
"PortChannel104",
"PortChannel103",
"PortChannel101",
"PortChannel102"
],
"stage": "ingress",
"type": "L3"
},
```
> [show] Show running config when bgp is down

- show/main.py
- tests/conftest.py
- utilities_common/bgp_util.py
cherrypick conflict for https://github.com/sonic-net/sonic-utilities/pull/3313
- Before the PR fix, `show run all` will not show running config when bgp down
```
admin@bjw-can-7060-2:~$ show ver
SONiC Software Version: SONiC.20230531.27
admin@bjw-can-7060-2:~$ docker kill bgp
bgp
admin@bjw-can-7060-2:~$ show run all
Error response from daemon: Container dfa7901af190f05e34130241b6d853b44048468a345e2f30241b70609f110c5b is not running
admin@bjw-can-7060-2:~$ 
```
- After PR fix, `show run all` will show running config when bgp down.
```
admin@bjw-can-7060-2:~$ docker kill bgp
bgp
admin@bjw-can-7060-2:~$ show run all | more
Error response from daemon: Container dfa7901af190f05e34130241b6d853b44048468a345e2f30241b70609f110c5b is not running
{
"ACL_TABLE": {
"DATAACL": {
"policy_desc": …
```
> [cherry-pick][202305] Show running config when bgp is down

- config/main.py
- generic_config_updater/generic_updater.py
- generic_config_updater/gu_common.py
- tests/config_test.py
Before apply the json patch, we will precheck and simulate-patch the payload in entire box level.
1. Add Duplication check
2. JSON patch structure validating
3. Simulating patch to full configuration
4. Verifying simulating result match YANG validation.
1. Single ASIC
```
admin@str2-msn2700-spy-2:~/gcu$ cat empty.json 
[]
admin@str2-msn2700-spy-2:~/gcu$ sudo config apply-patch empty.json 
Patch Applier: localhost: Patch application starting.
Patch Applier: localhost: Patch: []
Patch Applier: localhost getting current config db.
Patch Applier: localhost: simulating the target full config after applying the patch.
Patch Applier: localhost: validating all JsonPatch operations are permitted on the specified fields
Patch Applier: localhost: validating target config does not have empty tables, …
```
> Add full configuration validation.

- scripts/fabricstat
- show/fabric.py
- tests/fabricstat_test.py
- tests/mock_tables/asic0/state_db.json
Added "show fabric counters rate mbps" command. 
The output of the command is 
```
ASIC    Link ID    Rx Data Mbps    Tx Data Mbps
------  ---------  --------------  --------------
asic0          0               0            19.8
asic0          1               0            19.8
asic0          2               0            39.8
asic0          3               0            39.8
...
ASIC    Link ID    Rx Data Mbps    Tx Data Mbps
------  ---------  --------------  --------------
asic1          0               0               0
asic1          1               0               0
asic1          2               0               0
asic1          3               0               0
...
```
The HLD is at here
https://github.com/sonic-net/SONiC/blob/master/doc/voq/fabric.md
Amendment is at …
> Add show fabric rate command

- show/main.py
- tests/conftest.py
- utilities_common/bgp_util.py
cherry pick conflict for https://github.com/sonic-net/sonic-utilities/pull/3313
- output of `show run all` before fix:
```
admin@bjw-can-7260-8:~$ show ver
SONiC Software Version: SONiC.20231110.10
...
admin@bjw-can-7260-8:~$ docker kill bgp
bgp
admin@bjw-can-7260-8:~$ show run all
Error response from daemon: Container 94f750dbed0fdd990bb34c302c52f0fe16ec34d2092d3ff754500fcc647744bf is not running
admin@bjw-can-7260-8:~$ 
```
- output of `show run all` after fix:
```
admin@bjw-can-7260-8:~$ docker kill bgp
bgp
admin@bjw-can-7260-8:~$ show run all | more
Error response from daemon: Container 94f750dbed0fdd990bb34c302c52f0fe16ec34d2092d3ff754500fcc647744bf is not running
{
"ACL_TABLE": {
"DATAACL": {
"policy_desc": "DATAACL",
"ports": [
"PortChannel101",
"PortChannel102",
"PortChannel103", …
```
> [cherry-pick][202311] Show running config when bgp is down

- generic_config_updater/gcu_field_operation_validators.conf.json
Update sonic-utilities to support new SKU Mellanox-SN5600-V256
Add the SKU to the generic configuration updater
Manual and unit tests
> Update sonic-utilities to support new SKU Mellanox-SN5600-V256

- sonic_package_manager/service_creator/creator.py
- tests/sonic_package_manager/conftest.py
- tests/sonic_package_manager/test_service_creator.py
Added code to remove leftover symlinks and directories created by featured. Featured creates a symlink to /dev/null when unit is masked and an auto restart configuration is left under corresponding ```service.d/``` directory.
Added necessary changes  and UT to cover it.
Uninstall an extension and verify no leftovers from featured.
> [sonic-package-manager] remove leftovers from featured on uninstall

- azure-pipelines.yml
- setup.py
Fix SONiC image compilation issue:
```
+ sudo LANG=C DOCKER_HOST= chroot ./fsroot-mellanox /usr/local/bin/generate_shutdown_order.py
File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 532, in send
conn = self._get_connection(request, verify, proxies=proxies, cert=cert)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 400, in _get_connection
conn = self.poolmanager.connection_from_host(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/urllib3/poolmanager.py", line 304, in connection_from_host
return self.connection_from_context(request_context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> [build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages

- scripts/fast-reboot
Currently, entire PORT_TABLE in STATE_DB is being deleted during warm-reboot. Due to this, `host_tx_ready` changes to false after warm-reboot which causes the link to remain down.
Backing up `host_tx_ready`, `NPU_SI_SETTINGS_SYNC_STATUS` and `CMIS_REINIT_REQUIRED` fields from `STATE_DB PORT_TABLE* during warm-reboot now.
Verified that host_tx_ready in STATE_DB PORT_TABLE is retained after warm-reboot and the link remains up. Also, ensured that the keys CMIS_REINIT_REQUIRED and NPU_SI_SETTINGS_SYNC_STATUS are retained after warm-reboot.
Before warm-reboot
```
root@sonic:/home/admin# redis-cli -n 6 hgetall "PORT_TABLE|Ethernet0"
1) "state"
2) "ok"
3) "netdev_oper_status"
4) "up"
5) "admin_status"
6) "up"
7) "mtu"
8) "9100"
9) "CMIS_REINIT_REQUIRED"
10) "false"
11) …
```
> Backup STATE_DB PORT_TABLE|Ethernet during warm-reboot

- pfc/main.py
- tests/pfc_input/assert_show_output.py
- tests/pfc_test.py
This change puts contents originally in pfc/main.py into a class, to support the usage of the multi-asic helper in a future change. This change is required, as multi-asic helper being used expects members `self.config_db` and `self.db` to exist when a function with the decorator `run_on_multi_asic` is called. The multi-asic class helper will be used to add multi-asic support to pfc commands in a following pull request.
This is a part of the set of changes being pushed for https://github.com/sonic-net/sonic-buildimage/issues/15148
Moved contents of PFC commands into a class. There are no functional changes.
> Make PFC commands use a class

- utilities_common/cli.py
There's a difference in behavior when an external command is run under the default mode vs when it is run under the alias mode. In the default mode, execution control returns to the caller unless the command had a non-zero exit code. In the alias mode, regardless of exit code, the Python script exits. This may result in some tasks not completing.
Fix this by not unconditionally exiting if running a command in the alias mode. Note that there are other differences still present, but this fixes at least this one.
> Don't exit immediately if running a command under alias mode

- azure-pipelines.yml
- setup.py
Cherry-pick PR https://github.com/sonic-net/sonic-utilities/pull/3328 [build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages
> [cherry-pick][202205][build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages (#3328)

- config/bgp_cli.py
- config/main.py
- doc/Command-Reference.md
- show/bgp_cli.py
- show/main.py
- tests/bgp_input/assert_show_output.py
- tests/bgp_input/mock_config/all_disabled.json
- tests/bgp_input/mock_config/all_enabled.json
- tests/bgp_input/mock_config/empty.json
- tests/bgp_input/mock_config/tsa_enabled.json
- tests/bgp_input/mock_config/wcmp_enabled.json
- tests/bgp_test.py
- utilities_common/bgp.py
**HLD:** https://github.com/sonic-net/SONiC/pull/1629
* Implemented CLI for Weighted-Cost Multi-Path feature
* Integrated Weighted-Cost Multi-Path interface into `config` and `show` CLI root
1. Run Weighted-Cost Multi-Path CLI UTs
* N/A
```
admin@sonic:/home/admin# show bgp device-global
TSA      WCMP
-------  -------
enabled  enabled
admin@sonic:/home/admin# show bgp device-global --json
{
"tsa": "enabled",
"wcmp": "enabled"
}
```
> Add W-ECMP CLI

- scripts/fabricstat
"show fabric monitor capacity" command has a index error if the feature is disabled. With this change, the command can still display information without errors. 
the issue is tracking at https://github.com/sonic-net/sonic-utilities/issues/3350
> Fix show fabric monitor capacity command when the feature is disabled.

- config/main.py
- tests/config_dpb_test.py
Changing the return code of DPB command to 1 on failure when dependencies exit.
Updating the exit code
Modified UT to verify
> [DPB]Fixing return code of breakout command on failure

- config/main.py
- tests/config_test.py
Improve load_mingraph to wait eth0 restart before exit
load_minigraph will restart eth0, which cause device randomly lost network for 10-20 seconds after load_minigraph
When enable TACACS, this will cause commands randomly failed after load_minigraph
Wait interfaces-config and networking service restart after restart all sonic.target services.
- Microsoft ADO: 28302676
Pass all test case.
Add new test case.
admin@TEST_DEVICE:~$ date && sudo config load_minigraph -y && date
Wed Jun 12 08:30:59 AM UTC 2024
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Running …
> Improve load_mingraph to wait eth0 restart before exit

- config/main.py
- tests/config_test.py
ADO: 27941719
Improve Golden Config workflow and make sure no op if invalid config detected
Add table dependency check right after Golden Config path is enabled
Unit test
> [config] no op if Golden Config is invalid

- sfputil/main.py
For transceivers which are CMIS target FW upgrade capable, sfputil needs to update FW version for all targets as part of firmware download, run and commit.
However, the current function update_firmware_info_to_state_db updates the firmware info to redis-db only for target 0.
MSFT ADO - 27920760
Updating the active, inactive firmware versions for all sides. Also, updating the server firmware version for E1 and E2.
Ran the below sequence and ensured that the firmware info is updated for all targets in redis-db.
1. sfputil firmware target PORT_NAME TARGET
2. sfputil firmware download PORT_NAME FILE_PATH
3. sfputil firmware target PORT_NAME TARGET
4. sfputil firmware run PORT_NAME
5. sfputil firmware target PORT_NAME TARGET
6. sfputil firmware commit PORT_NAME
Also, tested the changes on …
> Update TRANSCEIVER_FIRMWARE_INFO table for all targets in sfputil

- config/main.py
- tests/config_test.py
Improve load_mingraph to wait eth0 restart before exit
This is cherry-pick PR for https://github.com/sonic-net/sonic-utilities/pull/3365
load_minigraph will restart eth0, which cause device randomly lost network for 10-20 seconds after load_minigraph
When enable TACACS, this will cause commands randomly failed after load_minigraph
Wait interfaces-config and networking service restart after restart all sonic.target services.
- Microsoft ADO: 28302676
Pass all test case.
Add new test case.
Verified on SONiC.202305.562827-f73bc5bfb
admin@TEST_DEVICE:~$ date && sudo config load_minigraph -y && date
Wed Jun 12 08:30:59 AM UTC 2024
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Running command: /usr/local/bin/sonic-cfggen …
> [202305] [cherry-pick] Improve load_mingraph to wait eth0 restart before exit (#3365)

- scripts/decode-syseeprom
If there is something wrong getting eeprom while exectuing script `decode-syseeprom`, it will raise an exception and log the error. There was no definition of `log` in script `decode-syseeprom`, which will raise such error 
```
File "/usr/local/bin/decode-syseeprom", line 264, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/bin/decode-syseeprom", line 246, in main
print_serial(use_db)
File "/usr/local/bin/decode-syseeprom", line 171, in print_serial
eeprom = instantiate_eeprom_object()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/bin/decode-syseeprom", line 36, in instantiate_eeprom_object
log.log_error('Failed to obtain EEPROM object due to {}'.format(repr(e)))
^^^
NameError: name 'log' is not defined
```
In this PR, I add the definition of log to …
> Add the definition of `log` in script `decode-syseeprom`

- config/main.py
- tests/config_test.py
Improve load_mingraph to wait eth0 restart before exit
This is cherry-pick PR for https://github.com/sonic-net/sonic-utilities/pull/3365
load_minigraph will restart eth0, which cause device randomly lost network for 10-20 seconds after load_minigraph
When enable TACACS, this will cause commands randomly failed after load_minigraph
Wait interfaces-config and networking service restart after restart all sonic.target services.
- Microsoft ADO: 28302676
Pass all test case.
Add new test case.
Verified with SONiC.202311.562838-e1f4859bf
admin@TEST_DEVICE:~$ date && sudo config load_minigraph -y && date
Wed Jun 12 08:30:59 AM UTC 2024
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Running command: /usr/local/bin/sonic-cfggen …
> [202311]  [cherry-pick]  Improve load_mingraph to wait eth0 restart before exit (#3365)

- scripts/fast-reboot
Backup DB after syncd and swss are stopped. I observed an issue with fast-reboot that in a rare circumstances a queued FDB event might be written to ASIC_DB by a thread inside syncd after a call to FLUSHDB ASIC_DB was made.
That left ASIC_DB only with one record about that FDB entry and caused syncd to crash at start:
```
Mar 15 13:28:42.765108 sonic NOTICE syncd#SAI: :- Syncd: syncd started
Mar 15 13:28:42.765268 sonic NOTICE syncd#SAI: :- onSyncdStart: performing hard reinit since COLD start was performed
Mar 15 13:28:42.765451 sonic NOTICE syncd#SAI: :- readAsicState: loaded 1 switches
Mar 15 13:28:42.765465 sonic NOTICE syncd#SAI: :- readAsicState: switch VID: oid:0x21000000000000
Mar 15 13:28:42.765465 sonic NOTICE syncd#SAI: :- readAsicState: read asic state took 0.000205 sec
Mar 15 …
```
> [fast-reboot] Backup database after syncd/swss stopped

- show/plugins/pbh.py
- tests/pbh_input/assert_show_output.py
- tests/pbh_input/counters_db_partial.json
- tests/pbh_test.py
During system init the initial snapshot of PBH rule counters doesn't contain all the necessary information, which makes a dump invalid. Thus, it fails CLI to do a comparison logic which prints a traceback. After some time, when counters are getting updated in the DB, the snapshot can be taken correctly and the issue is gone.
* Fixed PBH CLI output when counter's cache is partial
* Added additional constraint
1. Reboot the switch
2. Run `sonic-clear pbh statistics`
3. Run `show pbh statistics`
```
root@sonic:/home/admin# show pbh statistics
return …
```
> [pbh]: Fix show PBH counters when cache is partial

- config/main.py
- tests/config_dpb_test.py
Fix return code when DPB command fails. Return of 0 indicates success which might be a problem to detect failures using automation
Updated return code to 1
Basic manual testing
> [DPB]Fix return code in case of failure

- scripts/generate_dump
Improve generate_dump script to remove secrets from golden_config_db.json and old_config files
Improve generate_dump script to remove secrets from golden_config_db.json and old_config files
Remove golden_config_db.json and old_config files.
Run 'show techsupport' command and check secrets removed from dump files.
- Microsoft ADO: 28582108
> [generate_dump] Improve generate_dump script to remove secrets from golden_config_db.json and old_config files

- tests/bgp_commands_test.py
- utilities_common/bgp_util.py
Reverts #3375
It will impact many automation scripts that the community users may have developped for years... So if we change it now, all those scripts will be impacted... not something we want to do just to correct a miss spelled word at this stage...  
Revert this change
1. Reverts #3375
2. Add comments in case someone else fix the typo without notification.
> Revert "fix: fix show bgp summary output typo"

- tests/disk_check_test.py
- tests/drops_group_test.py
I fixed a problem that would cause disk_check_test and drops_group_test to fail when running the tests twice.
tests/drop_groups_test.py: In the setup_class() of TestDropCounters class, I invoked a function to remove cache files.
tests/disk_check_test.py: In the teardown_class() of TestDiskCheck class, I run a command to remove /tmp/tmp* files.
Run the tests in the slave containers several times repeatedly and see if they passed. Before adding these fixes, the tests should fail starting from the second time.
> [Bug Fix] Fix disk check test and drops group test

- scripts/generate_dump
Cherry-pick #2925
ADO 28548370
Added input check for argument "-t" in generate_dump script
Made sure only integer values can be received for this argument
Call generate_dump -t with non-integer values
> [202305] Input check for timeout in generate_dump (#2925)

- README.md
- rcli/linecard.py
- rcli/rexec.py
- rcli/rshell.py
- rcli/utils.py
- show/bgp_frr_v4.py
- show/main.py
- tests/bgp_commands_input/bgp_network_test_vector.py
- tests/conftest.py
- tests/mock_tables/chassis_state_db.json
- tests/remote_cli_test.py
- tests/remote_show_test.py
- tests/show_bgp_network_test.py
1. Enable "show ip bgp" on sup and "-n all" for show ip bgp network.
2. Modify README.doc to make the instructions of building and installing the wheel package more clear.
3. Improve the output format of rexec command
Modify the code in show/main.py to enable "show ip bgp ..." on supervisors and modify show/bgp_frr_v4.py to add support for the new features.
Update README.md.
Modify the rexec implementation to improve the output format.
Add unit tests for the above change.
Run on a SONiC chassis
> Enable show ip bgp on sup and -n all for show ip bgp network

- sfputil/main.py
- tests/sfputil_test.py
fixes https://github.com/sonic-net/sonic-buildimage/issues/19032
`sfputil show eeprom -d -p Ethernet0` command is failing for CMIS flat memory modules with a traceback.
```
root@switch/home/admin# sfputil show eeprom -d -p Ethernet0
File "/usr/local/bin/sfputil", line 8, in <module>
^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> [SfpUtil] sfp eeprom with option dom is not working on Xcvrs with flat memory

- scripts/generate_dump
Show techsupport is designed to collect logs and core files since given date.
I find that some core files are missing when given date is relative, for example "5 minutes ago".
Microsoft ADO: 28737486
Create the reference file at the start of the script, and don't update it in find_files.
Run end to end test: show_techsupport/test_auto_techsupport.py
> Fix show techsupport date issue

- config/main.py
- tests/vlan_test.py
Added Check for IP Assignment on Port when a Vlan is configured.
This PR is created in response to [Issue](https://github.com/sonic-net/sonic-buildimage/issues/19505)
Modified config/main.py to add check for IP Assignment when Port has vlan membership 
After this, ip cannot be assigned on port which is configured to a VLAN.
> IP Assignment Issue

- show/bgp_frr_v4.py
- tests/bgp_commands_input/bgp_network_test_vector.py
- tests/remote_show_test.py
- tests/show_bgp_network_test.py
I changed the default behaviors of "show ip bgp network" command on multi-asic chassis.
I modified the implementation of "bgp" command group and "network" subcommand in show/bgp_frr_v4.py and updated the relevant unit tests. The changes are listed below.
1. Now, by default "show ip bgp network" will display results from all namespaces. Meanwhile, it will not forcefully require "-n" option any more.
2. "show ip bgp network" now will require ip-address/ip-prefix option to be executed on chassis supervisors. This is to avoid getting excessive routes from such command on the supervisors.
Install and run it on a SONiC T2 chassis.
Previously, if you run `show ip bgp network` on a chassis supervisor you will get something similar to below:
```
======== LINE-CARD0|lc1-hostname output: ======== …
```
> Change the default behavior of show ip bgp network

- generic_config_updater/gcu_field_operation_validators.conf.json
Add Mellanox-SN4700-O32 and Mellanox-SN4700-V64 for generic_config_updater file
Verified GCU tests in sonic-mgmt
> [202405][Mellanox] Add support for Mellanox-SN4700-O32 and Mellanox-SN4700-V64

- generic_config_updater/generic_updater.py
- tests/generic_config_updater/multiasic_change_applier_test.py
Add namespace check for multiasic
If device is multi asic, check whether namespace appear.
1. Multi ASIC
```
admin@str2-7250-lc1-2:~$ cat badpatch.json 
[
{
"op": "add",
"path": "/AAA",
"value": {
"accounting": {
"login": "tacacs+,local"
},
"authentication": {
"debug": "True",
"failthrough": "True",
"fallback": "True",
"login": "tacacs+",
"trace": "True"
},
"authorization": {
"login": "tacacs+,local"
}
}
}
]
admin@str2-7250-lc1-2:~$ sudo config apply-patch badpatch.json 
sonic_yang(6):Note: Below table(s) have no YANG models: DHCP_SERVER
Failed to apply patch due to: Multi ASIC must have namespace prefix in path: '/AAA'.
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.
Error: Multi ASIC must have namespace prefix in path: '/AAA'.
```
> Add namespace check for multiasic

- doc/Command-Reference.md
- sfputil/main.py
- tests/sfputil_test.py
Due to a conflict while cherry-picking of the [PR#3369](https://github.com/sonic-net/sonic-utilities/pull/3369) to branch 202311, re-create this pull request to merge it manually
Add a **debug** group and a sub-command **loopback** under the sfputil command for debugging and module diagnostic purposes.
Implement the loopback command by directly calling the **set_loopback_mode**() API.
Tested under Cisco8111 with Credo C1 cable.
- Turn off loopback mode
`sfputil debug loopback Ethernet88 none`
- Turn on host input loopback
`sfputil debug loopback Ethernet88 host-side-input`
The loopback command is not supported in previous version.
> [sfputil] Add loopback sub-command for debugging and module diagnostics for branch 202311

- config/main.py
- tests/config_snmp_test.py
If link local IPv6 address is added as SNMP agent address, it will fail.
This PR requires changes in snmpd.conf.j2 template here https://github.com/sonic-net/sonic-buildimage/pull/18350/
Append scope id to ipv6 link local IP address.
Able to configure link local ipv6 address as snmp agent address
```
sudo config snmpagentaddress add fe80::2a99:3aff:fe17:1c08%eth0
sonic-db-cli CONFIG_DB keys "*SNMP*AGENT*"
SNMP_AGENT_ADDRESS_CONFIG|FC00:1::32|161|
SNMP_AGENT_ADDRESS_CONFIG|2a01::ae|161|
SNMP_AGENT_ADDRESS_CONFIG|10.1.0.32|161|
SNMP_AGENT_ADDRESS_CONFIG|10..0.13|161|
SNMP_AGENT_ADDRESS_CONFIG|fe80::2a99:3aff:fe17:1c08%eth0||
..
SNMP_AGENT_ADDRESS_CONFIG|fe80::3a38:a6ff:fe98:e960%eth0||  ---- Newly added agent IP along with zone id
SNMP_AGENT_ADDRESS_CONFIG|FC00:1::32|161|
SNMP_COMMUNITY|<> …
```
> Fix to use IPv6 linklocal address as snmp agent address

- generic_config_updater/gcu_field_operation_validators.conf.json
Add Mellanox-SN4700-O32 and Mellanox-SN4700-V64 for generic_config_updater file
Verified GCU tests in sonic-mgmt
> [Mellanox] Update sonic-utilities to support SN4700-V64  and  SN4700-O32

- scripts/fast-reboot
kexec -u on systems with SB enabled is failing
Fixes https://github.com/sonic-net/sonic-buildimage/issues/18007
```
root@sn5600:/home/admin# mokutil --sb-state
SecureBoot enabled
root@sn5600:/home/admin# kexec -u
kexec unload failed: Permission denied
[ 3443.199576] ima: impossible to appraise a kernel image without a file descriptor; try using kexec_file_load syscall.
```
Use the -a argument with kexec 
```
-a, --kexec-syscall-auto  Use file based syscall for kexec and fall
back to the compatibility syscall when file based
syscall is not supported or the kernel did not
understand the image
```
> Fix kexec_unload failure on secure boot enabled platforms

- show/bgp_frr_v4.py
- tests/bgp_commands_input/bgp_network_test_vector.py
- tests/remote_show_test.py
- tests/show_bgp_network_test.py
I changed the default behaviors of "show ip bgp network" command on multi-asic chassis.
Microsoft ADO: 28897424
I modified the implementation of "bgp" command group and "network" subcommand in show/bgp_frr_v4.py and updated the relevant unit tests. The changes are listed below.
1. Now, by default "show ip bgp network" will display results from all namespaces. Meanwhile, it will not forcefully require "-n" option any more.
2. "show ip bgp network" now will require ip-address/ip-prefix option to be executed on chassis supervisors. This is to avoid getting excessive routes from such command on the supervisors.
Install and run it on a SONiC T2 chassis.
Previously, if you run `show ip bgp network` on a chassis supervisor you will get something similar to below:
```
======== …
```
> Merge changes introduced in PR#3447 into branch 202405

- config/main.py
- tests/config_test.py
ADO: 27595279
What I did
Extend config reload to support single file reloading for multi-asic
How I did it
Add the single file reload support for mutli-asic
Unit test and manual test on multi-asic DUT
> [conflict resolve][config]Support single file reload for multiasic (#3349)

- generic_config_updater/gcu_field_operation_validators.conf.json
Add  Mellanox-SN4700-O32 and Mellanox-SN4700-V64  for generic_config_updater file
> [202311][Mellanox] Update sonic-utilities to support SN4700-V64 and SN4700-O32

- config/main.py
- tests/config_test.py
- tests/flock_test.py
- utilities_common/flock.py
In some cases, if multiple config reload/load_minigraph are running in parallel, they might leave the system in an error state.
In this PR, a flock is added to config reload/load_minigraph so they will not run in parallel.
The file lock is binding to `/etc/sonic/reload.lock`.
This is to fix issue: [#19855](https://github.com/sonic-net/sonic-buildimage/issues/19855)
* Microsoft ADO (number only): 28877643
Add flock utility and decoate the `reload` and `load_minigraph` with the `try_lock` to ensure the lock is acquired before reload/load_minigraph.
UT and on testbed.
* reload with locking success
```
Acquired lock on /etc/sonic/reload.lock
Clear current config and reload config in config_db format from the default config file(s) ? [y/N]: y …
```
> Add lock to config reload/load_minigraph

- rcli/utils.py
- tests/remote_cli_test.py
I added a timeout setting for the get_password function in rexec module so that automatic pipelines that does not expect password input will not get blocked. The current timeout setting is 10 sec.
Add a SIGALRM signal before waiting for password input. 
Run a "show ip bgp summary" on SONiC Chassis Supversior and does not input password until it times out.
Before adding such a mechanism, if you do not input password when run "rexec -c <cmd>" you will be blocked at the following output:
```
Since the current device is a chassis supervisor, this command will be executed remotely on all linecards
Password for username 'XXX':
```
After adding such a mechanism, if you do not input password when run "rexec -c <cmd>" you will see a timeout message after 10 seconds.
```
Since the current device is …
```
> Add timeout for rexec's get_password

- config/main.py
- scripts/ecnconfig
- show/main.py
- tests/ecn_input/ecn_test_vectors.py
- tests/ecn_test.py
- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/asic1/config_db.json
- tests/multi_asic_ecnconfig_test.py
Previously, ecnconfig -l was not behaving correctly on multi-asic devices, as the '-n' namespace option was not available, and correct namespaces were not traversed on multi-asic devices to retrieve correct results for ecnconfig. This change fixes multi-asic behaviour of CLI commands that rely on ecnconfig.
This is a part of the set of changes being pushed for https://github.com/sonic-net/sonic-buildimage/issues/15148
This change relies on helpers added in https://github.com/sonic-net/sonic-buildimage/pull/17243
Added namespace option -n and used multi_asic library to implement multi_asic behaviour. Added relevant unit tests to ensure functionality.
Run unit tests, or ecnconfig commands with option `-n`.
> Fix multi-asic behaviour for ecnconfig

- config/main.py
- tests/config_test.py
- tests/flock_test.py
- utilities_common/flock.py
What I did
This is to cherry-pick https://github.com/sonic-net/sonic-utilities/pull/3475 into 202311
In some cases, if multiple config reload/load_minigraph are running in parallel, they might leave the system in an error state. In this PR, a flock is added to config reload/load_minigraph so they will not run in parallel. The file lock is binding to /etc/sonic/reload.lock.
This is to fix issue: #19855
Microsoft ADO (number only): 28877643
Signed-off-by: Longxiang Lyu lolv@microsoft.com
How I did it
Add flock utility and decoate the reload and load_minigraph with the try_lock to ensure the lock is acquired before reload/load_minigraph.
UT and on testbed.
* reload with locking success
```
Acquired lock …
```
> [202311] Add lock to config reload/load_minigraph (#3475)

- config/main.py
- doc/Command-Reference.md
- scripts/route_check.py
- show/main.py
- tests/route_check_test.py
- tests/suppress_pending_fib_test.py
Reverts sonic-net/sonic-utilities#3331
BGP zebra enhancements is merged to master branch https://github.com/sonic-net/sonic-buildimage/pull/19717
Reverting the revert of bgp suppress pending feature to enable it in master branch
> Revert "Remove suppress-fib-pending CLI and make route_check.py check suppress-fib in BGP configuration"

- scripts/reboot
The fix is aimed to resolve reboot issue when vendor reboot hook is executed during `syncd` service startup.
Relevant PRs:
1. https://github.com/sonic-net/sonic-utilities/pull/3203
2. https://github.com/sonic-net/sonic-utilities/pull/819
* Fixed reboot failure in case of vendor reboot hook error
* Removed error validation
1. Execute `reboot` when `syncd` is starting and ASIC reset is in progress
* N/A
* N/A
> [reboot]: Allow reboot to happen regardless vendor hook errors

- doc/Command-Reference.md
> Save doc for WoL CLI

- scripts/generate_dump
For Mellanox platforms, I added the following CMIS host management-related files to the 'show techsupport' dumps (if they exist): sai.profile, pmon_daemon_control.json, media_settings.json, optics_si_settings.json, and autoneg.status.
I copied the relevant files from the SKU/platform folder and ran the 'show interface autoneg status' command to store the auto-negotiation status for all ports.
Run 'show techsupport' and verify that autoneg.status is located in the 'dumps' directory and that the other files are present in the cmis-host-mgmt path within the generated dump.
> [Mellanox] Add CMIS Host Management Files to 'show techsupport' Dumps

- scripts/reboot
Add back the support to call reboot -f
The support for this option was accidentally removed as part of this PR https://github.com/sonic-net/sonic-utilities/pull/3203
The same PR for 202311 doesn't have this mistake - https://github.com/sonic-net/sonic-utilities/pull/3204
Call reboot -f
> Add back the option f to the reboot script

- config/main.py
- tests/qos_config_input/0/config_qos.json
- tests/qos_config_input/1/config_qos.json
- tests/qos_config_input/config_qos.json
Fixes https://github.com/sonic-net/sonic-buildimage/issues/15894
`config qos reload` command uses a combination of `sonic-cfggen`'s flags `-d` and `--write-to-db` that makes  it override entire CONFIG_DB, updating every key. This leads to issues with Orchs, daemons that do not support updating keys in CONFIG_DB. Best case, it causes errors in logs.
First, render templates to temporary files, then load those files into CONFIG_DB.
Also, fixed an issue where using `dry_run` option only produced QOS config but not the buffer configuration and updated test files accordingly.
Run on switch:
```
root@sonic/home/admin# config qos reload
Running command: /usr/local/bin/sonic-cfggen -d -t /usr/share/sonic/device/x86_64-mlnx_msn2100-r0/ACS-MSN2100/buffers_dynamic.json.j2,/tmp/cfg_buffer.json -t …
```
> [qos reload] Fix "config qos reload" overriding entire CONFIG_DB

- config/chassis_modules.py
- tests/chassis_modules_test.py
MSFT ADO: 29166401
Executing CLI command "sudo config module shutdown FABRIC-CARD6" fails on latest Master and 202405 branch.  It cause back trace as below.  The "subprocess() has been modified with "sholl=False".  run_command() takes commands as list of string instead of a single line.   
```
admin@ixre-cpm-chassis7:~$ sudo config chassis modules shutdown FABRIC-CARD6
Shutting down chassis module FABRIC-CARD6
Stop swss@12 and peer services
File "/usr/local/bin/config", line 8, in <module>
^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
rv = …
```
> [chassis][cli] Fix config chassis module startup/shutdown command for fabric module

- scripts/generate_dump
Resolving 202311 conflicts for  https://github.com/sonic-net/sonic-utilities/pull/3501
For Mellanox platforms, I added the following CMIS host management-related files to the 'show techsupport' dumps (if they exist): sai.profile, pmon_daemon_control.json, media_settings.json, optics_si_settings.json, and autoneg.status.
I copied the relevant files from the SKU/platform folder and ran the 'show interface autoneg status' command to store the auto-negotiation status for all ports.
Run 'show techsupport' and verify that autoneg.status is located in the 'dumps' directory and that the other files are present in the cmis-host-mgmt path within the generated dump.
> [202311] [Mellanox] Add CMIS Host Management Files to 'show techsupport' Dumps

- config/main.py
- scripts/mmuconfig
- show/main.py
- tests/mmuconfig_input/mmuconfig_test_vectors.py
- tests/mmuconfig_test.py
- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/asic1/config_db.json
- tests/multi_asic_mmuconfig_test.py
Previously, mmuconfig did not function correctly on multi-asic devices as it did not traverse through the correct namespaces, as required for multi-asic devices. This change adds multi-asic support to mmuconfig with the use of multi-asic helper libraries, ensuring that mmuconfig searches throuugh the correct namespaces when used on multi-asic devices, and adds the '-n' optional argument for users to specify namespaces on multi-asic devices.
This is a part of the set of changes being pushed for https://github.com/sonic-net/sonic-buildimage/issues/15148
Added namespace option -n and used multi_asic library to implement multi_asic behaviour. Added relevant unit tests to ensure functionality.
Run unit tests, or mmuconfig with `-n` option.
> Fix multi-asic behaviour for mmuconfig

- config/main.py
- pfc/main.py
- show/main.py
- tests/multi_asic_pfc_test.py
- tests/pfc_input/assert_show_output.py
- tests/pfc_input/pfc_test_vectors.py
- tests/pfc_test.py
Added multi-asic support to PFC show and config commands by:
This is a logical successor of #3057 and is a part of the larger efforts to add multi-asic functionality tracked in [#15148](https://github.com/sonic-net/sonic-buildimage/issues/15148)
I used the multi_asic helper functions from `sonic_py_common` and `utilities_common` to handle multiple namespaces
There were three stages of verification:
The namespace argument is the new addition to the pfc command.
Case 1: If namespace is specified in a multi-asic device
Behaviour: We will run the command only on the specified namespace
e.g: `pfc show asymmetric --namespace asic0`
Case 2: If no namespace is specified in a multi-asic device
Behaviour: We will run the command on all namespaces
e.g: `pfc show priority`
Case 3: If a namespace is …
> Fix multi-asic support to PFC config/show

- generic_config_updater/gcu_field_operation_validators.conf.json
Update sonic-utilities to support new SKU Mellanox-SN5600-C256
Add the SKU to the generic configuration updater
Simplify the logic of the buffer migrator to support the new SKU
Manual and unit tests
> [Mellanox] Add new SKU Mellanox-SN5600-C256

- sonic_installer/bootloader/aboot.py
- tests/installer_bootloader_aboot_test.py
Fix a crash of sonic-installer for Aboot bootloaders when the next image is not exactly an installed sonic image. 
The Aboot bootloader relies of the SWI= keyword argument in the boot-config file to know which image to boot.
This value is also used by sonic-installer to figure to extract the next image that will be executed.
The current code has an issue as it only expects the next image to match the installation path of a SONiC image but not anything else.
This means that `SWI=flash:sonic-aboot-broadcom.swi` is not valid and can therefore be a problem when trying to install a new image via cold reboot.
Try `sonic-installer list` with the following values in `boot-config`
```
SWI=flash:image-something-expected/.sonic-boot.swi
SWI=flash:sonic-aboot-broadcom.swi
SWI=
```
> Enhance next image detection for Aboot in sonic-installer

- doc/Command-Reference.md
- sfputil/main.py
- tests/sfputil_test.py
This update enhances the loopback command functionality to support configuring the loopback mode for specific logical ports, instead of applying the configuration to the entire physical port.
By calculating the lane mask according to the port's configuration and state data, the loopback mode can now be accurately set for the specified port, ensuring that other unrelated logical ports are not affected during diagnostic operations.
Tested under Cisco8111 with Credo C1 cable.
The sfputil debug loopback command will now only affect the relevant lanes of the logical port.
Set **host input** loopback mode on logical port **Ethernet80**, the expected value of **page 0x13, byte 0xB7= 0x0F**
Set **media input** loopback mode on logical port **Ethernet84**, the expected value of **page 0x13, byte …
> [sfputil] Configure the debug loopback mode only on the relevant lanes of the logical port

- generic_config_updater/gcu_field_operation_validators.conf.json
A cherry-pick of https://github.com/sonic-net/sonic-utilities/pull/3431
Update sonic-utilities to support new SKU Mellanox-SN5600-C256
Add the SKU to the generic configuration updater
Simplify the logic of the buffer migrator to support the new SKU
Manual and unit tests
> [202405][Mellanox] Add new SKU Mellanox-SN5600-C256

- scripts/fast-reboot
- scripts/soft-reboot
- sonic_installer/bootloader/grub.py
Moved to use mokutil instead of bootctl as bootctl is no longer available in Bookworm.
This affected reboot scripts, and upgrade scenario.
Change calls to _bootctl status_ with _mokutil --sb-state_
After fixing the scripts to check reboot:
root@sn5600:/home/admin# soft-reboot
SECURE_UPGRADE_ENABLED=1
[[ CHECK_SECURE_UPGRADE_ENABLED -ne 0 ]]
load_kernel_secure
invoke_kexec -s
packet_write_wait: port 22: Broken pipe
admin@sn5600:~$ show reboot-cause
User issued 'soft-reboot' command [User: admin, Time: Tue Jul 23 11:06:43 PM UTC 2024]
> Move from bootctl to mokutil when checking for Secure Boot status

- config/main.py
- show/main.py
- tests/cli_sessions_test.py
HLD: https://github.com/sonic-net/SONiC/pull/1367
| Module name  | PR  | state | context |
| ------------- | ------------- | ----|-----|
| [sonic-buildimage](https://github.com/sonic-net/sonic-buildimage) | [Dev cli sessions](https://github.com/sonic-net/sonic-buildimage/pull/17623) | ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/17623) | ![GitHub pull request check contexts](https://img.shields.io/github/status/contexts/pulls/sonic-net/sonic-buildimage/17623) |
| [sonic-host-services](https://github.com/sonic-net/sonic-host-services)  | [cli-sessions](https://github.com/sonic-net/sonic-host-services/pull/99) | ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-host-services/ …
> SONIC CLI for CLI-Sessions feature

- setup.py
- utilities_common/multi_asic.py
- Older pyroute2 depends on distutils. Thus upgrade the version to latest to improve import time. A similar issue for natsort is reported here https://github.com/sonic-net/sonic-buildimage/issues/17246. However pyroute2 import is still heavy in bookworm and thus every CLI command is slow compared to bullseye. 
```
<Bullseye>
root@msn2700:/home/admin# time python3 -c "import pyroute2"
real	0m0.378s
user	0m0.308s
sys	0m0.060s
<Before upgrade>
root@msn2700:/home/admin# time python3 -c "import pyroute2"
real        0m0.707s
user        0m0.425s
sys        0m0.097s
<After upgrade>
root@msn2700:/home/admin#  time python3 -c "import pyroute2"
real	0m0.511s
user	0m0.433s
sys	0m0.075s
```
- To fix this, i've delayed the pyroute2 import into the method where it is actually used, this has an …
> Upgrade pyroute2 and improve cli response time

- scripts/queuestat
- tests/multi_asic_queue_counter_test.py
- tests/queue_counter_test.py
- Added support for iterating over all namespaces (ns) when none specified
- Added a test case to verify all ns behaviour
- Introduced a wrapper class to handle the mutli-asic functionality
- Replaced argparse with click for better argument checks
This is in accordance to the issue https://github.com/sonic-net/sonic-buildimage/issues/15148 which tracks the multi-asic support for scripts in sonic-utilities.
Modified the queuestat script and associated test files.
The changes were verified by:
- Running all the unit tests in conic-utilities
- Verifying the changes manually on a T2 single-asic linecard
- Verifying the changes manually on a multi-asic linecard
Cmd: `queuestat`
Result: Empty
Reason: When the namespace (`-n`/`--namespace`) argument is not specified on a multi asic device the …
> Fix multi-asic behaviour for queuestat

- scripts/fast-reboot
Sometimes during `/usr/local/bin/neighbor_advertiser` script execution, ACL entries are added to redis database with delay.
So during execution of function `check_mirror_session_acls() ` script can't find ACL entries.
Retry mechanism was added for this check in https://github.com/sonic-net/sonic-utilities/pull/3333
But the script will return error and exit with failure after first try.
Need to improve this algorithm.
add sleep 0.1 and 'continue' instead of 'exit'
run wr_arp test
>  [fast/warm-reboot] Improve retry mechanism to check if SAI_OBJECT_TYPE_ACL_ENTRY entries are in redis

- tests/portstat_db/on_sup_na/chassis_state_db.json
- tests/portstat_test.py
I added a unit test for scenarios where a LC's counter DB is N/A.
Run the unit test suite.
> Add Unit Test for portstat

- pfc/main.py
Used `getenv` to return `None` if the env variable is missing instead of key error. Fixes https://github.com/sonic-net/sonic-buildimage/issues/20398
Same as above
Run the `pfc config asymmetric on EthernetX` command on a T2 topology linecard
`KeyError: 'UTILITIES_UNIT_TESTING'`
No output (as expected). Config commands change attributes as expected
> Fix KeyError in pfc config command

- generic_config_updater/gcu_field_operation_validators.conf.json
Fix the name of the C256 SKU to C256A1
> Rename SKU to Mellanox-SN5600-C256X1

- config/syslog.py
- doc/Command-Reference.md
- tests/syslog_multi_asic_test.py
- tests/syslog_test.py
Add a command "config syslog level" to set log level at runtime.
Add a command "config syslog level" to set log level at runtime. This command shall update log level in CONFIG DB and send SIGHUP to relevant daemon if it requires a manual refresh
manual test
new unit test case
N/A
```
root@sonic:/home/admin# config syslog level --help
Usage: config syslog level [OPTIONS]
Configure log level
Options:
-c, --component TEXT            Component name in DB for which loglevel is
applied (provided with -l)  [required]
-l, --level [DEBUG|INFO|NOTICE|WARN|ERROR]
Loglevel value  [required]
--service TEXT                  Container name to which the SIGHUP is sent
(provided with --pid or --program)
--program TEXT                  Program name to which the SIGHUP is sent
(provided with --service) …
```
> Add a command to update log level and refresh configuration

- scripts/fast-reboot
Set cpufreq.default_governor to *performance* for faster boot time. We observe consistent 1 sec improvement across several devices.
**NOTE**: This will apply to upgrades starting from 202405 since this is set in shutdown path to avoid any extra scripts running at boot time. Upgrade from older versions/branches will require a runtime patch to fast-reboot and warm-reboot script.
DEPENDS ON: https://github.com/sonic-net/sonic-buildimage/pull/19634
Append this option to BOOT_OPTIONS variable.
Run fast-reboot or warm-reboot. Check:
```
admin@sonic:~$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
performance
```
After boot is finalized check that it is reset back to default:
```
admin@sonic:~$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
schedutil
```
> [fast/warm-reboot] add cpufreq.default_governor=performance to BOOT_OPTIONS

- doc/Command-Reference.md
Corrects the rendered output of .md file to generate the correct output. 
Example:
```
admin@sonic:/usr/bin$ show interface counters fec-histogram -i <PORT>
Symbol Errors Per Codeword  Codewords
--------------------------  ---------
BIN0:                       1000000
BIN1:                       900000
BIN2:                       800000
BIN3:                       700000
BIN4:                       600000
BIN5:                       500000
BIN6:                       400000
BIN7:                       300000
BIN8:                       0
BIN9:                       0
BIN10:                      0
BIN11:                      0
BIN12:                      0
BIN13:                      0
BIN14:                      0
BIN15:                      0
```
> [doc] correct the fec histogram output for show int counters fec-histogram

- config/main.py
- scripts/fast-reboot
- tests/config_test.py
Add constraint for YANG when config reload, which is already enabled in load_minigraph
Check YANG vaidation for the config
Unit test
> Add YANG validation for config reload if file is given

- generic_config_updater/gu_common.py
- tests/generic_config_updater/gu_common_test.py
Reverts sonic-net/sonic-utilities#3489 since the PR: https://github.com/sonic-net/sonic-buildimage/pull/19968 has merged.
> Revert "Skip default lanes dup check"

- config/main.py
ADO: 29917681
Sent a warn syslog if there are tables not covered by yang.
Sent a warn syslog if there are tables not covered by yang.
Manual test
> Record and warn tables which not covered by YANG

- config/main.py
ADO: 29917681
Sent a warn syslog if there are tables not covered by yang. Only show the list of keys of table name
Sent a warn syslog if there are tables not covered by yang.
Manual test
Improve output from
```
2024 Oct 23 07:43:20.293672 bjw-can-7260-12 WARNING config: YANG failed to cover tables: {'TABLE_NOT_COVRED_BY_YANG': {'mux_tunnel_egress_acl': {'status': 'disabled'}, 'tunnel_qos_remap': {'status': 'enabled'}}, 'bgpraw': 'aa', 'bgpraw1': 'aa', 'bgpraw2': 'aa'}.
```
to 
```
2024 Oct 23 07:45:21.755952 bjw-can-7260-12 WARNING config: YANG failed to cover tables: ['TABLE_NOT_COVRED_BY_YANG', 'bgpraw', 'bgpraw1', 'bgpraw2']
```
> [202311] Set warn msg for list of tables which not covered by YANG

- scripts/vnet_route_check.py
- tests/vnet_route_check_test.py
Currently the Vnet_route_check fails if a user calls it witout sudo with the following error.
```
File "/usr/local/bin/vnet_route_check.py", line 401, in <module>
sys.exit(main())
File "/usr/local/bin/vnet_route_check.py", line 364, in main
if not check_vnet_cfg():
File "/usr/local/bin/vnet_route_check.py", line 77, in check_vnet_cfg
db = swsscommon.DBConnector('APPL_DB', 0)
File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1656, in __init__
_swsscommon.DBConnector_swiginit(self, _swsscommon.new_DBConnector(*args))
RuntimeError: Unable to connect to redis (unix-socket): Cannot assign requested address
```
The **route_check** script accesses the same DB tables but is able to run without the sudo rights.  To solve this problem I have …
> Vnet_route_check TCP socket for DB connection.

- scripts/generate_dump
Add support of the pensando-dpu platform to generate-dump utility to collect platform-specific dumps on Pensando DPU.
Extend platform-specific section of generate-dump utility
Run "show techsupport" command to generate dump file. Verify that `{dpu_container}_techsupport` directory exists in the created dump file.
```
{
cat
}; docker exec syncd saidump | dummy_cleanup_method &> '/var/dump/sonic_dump_sonic_20240910_045531/dump/saidump'"
mkdir: created directory '/root/dpu_dump'
timeout --foreground 5m sudo docker exec polaris touch /data/techsupport//DSC_TechSupport_b08d.57cd.360f_2024-09-10_04-57-04_1725944224.tar.gz
timeout --foreground 5m sudo docker cp polaris:/data/techsupport//DSC_TechSupport_b08d.57cd.360f_2024-09-10_04-57-04_1725944224.tar.gz /root/dpu_dump
mkdir: created directory …
```
> Add support of the pensando-dpu platform to generate-dump utility.

- scripts/route_check.py
This PR fixes https://github.com/sonic-net/sonic-buildimage/issues/18773
Parallely execute route_check on each Asic.
Parallelly fetch ipv4 routes and ipv6 routes.
execute "time route_check.py" on T2 chassis having 32k v4+32k v6 routes.
Results:
Before:
Checking routes for namespaces: ['asic0', 'asic1']
real 3m16.387s
user 1m26.084s
sys 0m7.275s
After:
time route_check.py
real 1m30.675s
user 1m33.777s
sys 0m8.209s
None
None
> Speed up route_check script

- config/main.py
Bypass stdin input for config reload to avoid double json read which will cause issue
Add a bypass check
UT and manual test
> [config] Bypass standard input for reload

- utilities_common/portstat.py
Changed the data type casting to float if count coming is too large or in scientific notation .
made it float then type cast to int for display purpose
Manually passed big value and see the count output if it breaks or works
>  Fix for integer overflow of counter value if its too large

- generic_config_updater/change_applier.py
- generic_config_updater/gu_common.py
- tests/generic_config_updater/change_applier_test.py
- tests/generic_config_updater/gcu_feature_patch_application_test.py
- tests/generic_config_updater/multiasic_change_applier_test.py
Addressing the [issue 20508](https://github.com/sonic-net/sonic-buildimage/issues/20508).
ADO: 29979987
Remove temp file as intermediate steps.
```
admin@str2-7250-lc1-2:~$ cat test.json 
[
{
"op": "add",
"path": "/asic0/BGP_DEVICE_GLOBAL/STATE/idf_isolation_state",
"value": "unisolated"
}
]
admin@str2-7250-lc1-2:~$ sudo config apply-patch test.json 
sonic_yang(6):Note: Below table(s) have no YANG models: DHCP_SERVER
sonic_yang(6):Note: Below table(s) have no YANG models: LOGGER
sonic_yang(6):Note: Below table(s) have no YANG models: LOGGER
Patch Applier: asic0: Patch application starting.
Patch Applier: asic0: Patch: [{"op": "add", "path": "/BGP_DEVICE_GLOBAL/STATE/idf_isolation_state", "value": "unisolated"}]
Patch Applier: asic0 getting current config db.
Patch Applier: asic0: …
```
> Consolidate the get running config way.

- generic_config_updater/generic_updater.py
- tests/generic_config_updater/multiasic_change_applier_test.py
Addressing issue [#20377](https://github.com/sonic-net/sonic-buildimage/issues/20377). The issue caused by unescape in JsonPointer implementation which followed [RFC 6901](https://www.rfc-editor.org/rfc/rfc6901)
```python
pointer = jsonpointer.JsonPointer(path)
...
class JsonPointer(object):
"""A JSON Pointer that can reference parts of a JSON document"""
_RE_ARRAY_INDEX = re.compile('0|[1-9][0-9]*$')
_RE_INVALID_ESCAPE = re.compile('(~[^01]|~$)')
def __init__(self, pointer):
invalid_escape = self._RE_INVALID_ESCAPE.search(pointer)
if invalid_escape:
raise JsonPointerException('Found invalid escape {}'.format(
invalid_escape.group()))
parts = pointer.split('/')
if parts.pop(0) != '':
raise JsonPointerException('Location must start with /')
parts = [unescape(part) for part in parts] …
```
> Fix  slash in path.

- sonic_package_manager/manager.py
- tests/sonic_package_manager/test_manager.py
Add logic to disable the feature before stopping and enabling it before starting in order to properly clean the `systemd` symlinks to avoid issues with `delayed` attribute explained in the `How to verify it` section.
Add the `systemctl disable ...` after the `systemctl stop...` and the `systemctl enable ...` before the `systemctl start ..` for some feature.
- Add repository for some `featureX`
- `sonic-package-manager repository <featureX> <URL>`
- Install `featureX` version 1.0.0 where the `delayed` flag is equal to `false` (`delayed` flag means - the feature will be started right after the system boots or after the `PortInitDone` event)
- `sonic-package-manager install featureX==1.0.0 -y`
- Enable the feature in SONiC
- `config feature state featureX enabled`
- Install `featureX` …
> [SPM] Add logic to disable the feature before stopping it and enabling it before starting

- generic_config_updater/gcu_field_operation_validators.conf.json
Update Mellanox-SN5600-C256X1 to be Mellanox-SN5600-C256S1 in gcu_field_operation_validators.conf.json
> [Mellanox] Update C256X1 SKU to be C256S1 in gcu_field.json

- scripts/fast-reboot
Add support to optionally pass extra kernel command line arguments during warm-reboot kexec load. 
Extra command line arguments can be supplied from variable 'KEXEC_LOAD_EXTRA_CMDLINE_LINUX' in "installer.conf" present in device hwsku folder.
```
KEXEC_LOAD_EXTRA_CMDLINE_LINUX="<extra command line arguments>"
```
Triggered warm-reboot on Marvell AC5XRD platform and checked for successful warmboot.
> [warm-reboot] Add support to pass extra kernel cmdline parameters

- scripts/generate_dump
Signed-off-by: Anand Mehra anamehra@cisco.com
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/20693
During the show techsupport, generate_dump calls techsupport_cleanup with current generated file. The techsupport_cleanup verifies the file path provided for file last modification timestamp and on success only proceeds to cleanup. It expects the file to be modified within last 20 secs. Sometimes when file is big, gzip takes more that 20 sec. Due to this, the last modify timestamp to current time stamp diff is greater than 20 and verify_recent_file_creation fails causing cleanup to fail.
touch the tarfile after finishing the gzip to refresh modify timestamp.
run show techsupport
> Refresh showtech dump file modify timestamp before cleanup call 

- scripts/route_check.py
This is a cherry pick PR for 202405. Master branch PR: https://github.com/sonic-net/sonic-utilities/pull/3544
PR fixes https://github.com/sonic-net/sonic-buildimage/issues/18773
Parallely execute route_check on each Asic.
Parallelly fetch ipv4 routes and ipv6 routes.
execute "time route_check.py" on T2 chassis having 32k v4+32k v6 routes.
Results:
Verified on DUT running 202405. 
Before:
Checking routes for namespaces: ['asic0', 'asic1']
real 3m16.387s
user 1m26.084s
sys 0m7.275s
After:
time route_check.py
real 1m30.675s
user 1m33.777s
sys 0m8.209s
None
None
> [202405]: Speed up route_check.py

- generic_config_updater/gcu_field_operation_validators.conf.json
Add Mellanox-SN5600-C224O8 SKU to SPC4 list in gcu_field_operation_validators.conf.json
> [Mellanox] Add Mellanox-SN5600-C224O8 to gcu_field.json

- generic_config_updater/gcu_field_operation_validators.conf.json
Add Mellanox-SN5600-C224O8 SKU to Spectrum-4 list in gcu_field_operation_validators.conf.json
cherry pick https://github.com/sonic-net/sonic-utilities/pull/3612
Add Mellanox-SN5600-C224O8 SKU to Spectrum-4 list in gcu_field_operation_validators.conf.json
>  [Mellanox] Add Mellanox-SN5600-C224O8 to gcu_field.json (#3612)

- scripts/fast-reboot
Fetch boot arguments from the next boot image by reading it from uboot environment variables.
In current scenario, during warm-reboot for arm64, boot arguments are fetched from device tree of the current image. This causes an issue during upgrade/downgrade with warm-reboot.
With the change, boot arguments for arm64 is fetched from uboot environment variables. The logic relies on creation of
"sonic_bootargs" environment variable to fetch the right boot argument.
Tested by sonic to sonic install followed by warm-reboot.
> [ARM64][Warm-Reboot]: Get boot arguments from uboot environment

- scripts/route_check.py
Fixed a typo in route_check script. If result is not empty, script might fail due to undefined variable.
Corrected the typo. 
NA
> Fix typo in route_check_script

- sfputil/main.py
Introduce a delay in "sfputil firmware run" between running firmware and updating the cable firmware version info.
The flow of "sfputil firmware run" is the following
1. Issue CMIS CDB command "run cable firmware" (0x109) to the cable to switch to the inactive firmware.
2. Fetch the version of the cable's running firmware
It takes time for the cable to get ready after switching firmware, which can cause an error message in step 2.
We introduce a CLI option to specify a delay between step 1 and 2 to avoid error message.
> Extra delay between running firmware and updating firmware version

- counterpoll/main.py
Fix the object name and because of which, counterpoll show for ENI is not working
> Fix counterpoll show for ENI Counters

- scripts/generate_dump
Support saving folders.
Add a check to the save_file command, if the path that was provided is to a folder, use an appropriate method. 
Previously when a folder was given to be saved using this function, an empty file with the folder name would be created.
> [Mellanox] Update the save_file command in generate_dump to handle folders

- config/main.py
- config/vxlan.py
- tests/config_test.py
- tests/portchannel_test.py
- tests/subintf_test.py
- tests/vlan_test.py
- tests/vrf_test.py
- tests/vxlan_test.py
This PR is accompanied by https://github.com/sonic-net/sonic-swss-common/pull/931 and https://github.com/sonic-net/sonic-buildimage/pull/20108
Validate interface name length does not exceed the limitation of IFNAMSIZ to align to kernel restrictions.
Add validation checks in the relevant config functions for the following interface types:
vxlan
vlan
vrf
loopback
subinterface
portchannel
UT tests added
> Validate interface name length in CLI

- generic_config_updater/generic_updater.py
- tests/generic_config_updater/multiasic_change_applier_test.py
Addressing issue [#20377](https://github.com/sonic-net/sonic-buildimage/issues/20377). The issue caused by unescape in JsonPointer implementation which followed [RFC 6901](https://www.rfc-editor.org/rfc/rfc6901)
```python
pointer = jsonpointer.JsonPointer(path)
...
class JsonPointer(object):
"""A JSON Pointer that can reference parts of a JSON document"""
_RE_ARRAY_INDEX = re.compile('0|[1-9][0-9]*$')
_RE_INVALID_ESCAPE = re.compile('(~[^01]|~$)')
def __init__(self, pointer):
invalid_escape = self._RE_INVALID_ESCAPE.search(pointer)
if invalid_escape:
raise JsonPointerException('Found invalid escape {}'.format(
invalid_escape.group()))
parts = pointer.split('/')
if parts.pop(0) != '':
raise JsonPointerException('Location must start with /')
parts = [unescape(part) for part in parts] …
```
> Fix  slash in path. (#3573)

- scripts/generate_dump
On 202205 branch,  execute "show  techsupport " on Supervisor. It hung in the scripts which call "show queue counters". This PR filters out a list of command which are not applicable to Supervisor. Fixes https://github.com/Nokia-ION/ndk/issues/60
1) Modify generate_dump script by adding code to check if IS_SUPERVISOR, not to executes the "show queue counters".  
2) And also return at the beginning of the following functions which are not applicable on Supervisor:
save_bfd_info()
save_bgp_info()
save_evpn_info()
save_frr_info()
3) Also fix some of the failure which are shown during the show techsupport.
a) check if file /etc//cron.d/logrote exists before access it in function disable_logrotate() and enable_logrotate()
b) check if directory /var/log/sai_failure_dump/ exists before using …
> [show_tech] Filter out a list of commands in generate_dump script which are not applicable to Supervisor

- azure-pipelines.yml
This PR is to fix the PR checker failure due to migration in dependency.
1. Change dependency from bullseye to bookworm
2. Change building command accordingly
The change is verified by running the PR checker pipeline.
N/A
N/A
> Update PR checker pipeline to point to bookworm

- config/main.py
- tests/config_test.py
The sonic vm image has yang validation issue with default config setup. Limit YANG check to golden config only before fix default factory config.
Restrict YANG validation to golden config only.
Unit test and integration test.
> [config] Restrict YANG validation to Golden Config

- scripts/route_check.py
Reverts https://github.com/sonic-net/sonic-utilities/pull/3544 since this change would cause PR test failure in T0 sanity check, error message is:
```
"Program 'routeCheck'",
"  status                       Status ok",
"  monitoring status            Monitored",
"  monitoring mode              active",
"  on reboot                    start",
"  last exit value              0",
"  last output                  Exiting: failed to connect to any daemons.",
"                               Exiting: failed to connect to any daemons.",
"                               Error processing namespace : Command '['show', 'ip', 'route', 'json']' returned non-zero exit status 1.",
"  data collected               Wed, 04 Dec 2024 11:03:05",
```
> Revert "Speed up route_check script"

- scripts/generate_dump
Fix broken save_file command after #3631
Reverted wrong changes
> Fix save_file command in generate_dump

- scripts/db_migrator.py
- tests/db_migrator_test.py
config_sonic_basedon_testbed.yml creates an empty golden_config_db.json file under /etc/sonic for non mx platforms.
When this empty file exist db_migration fails for all asics for non mx platforms.
Update db_migrator to support empty golden config file.
Run unit test and end to end test
> Support empty golden config file for multi-asic

- doc/Command-Reference.md
introduces the show interfaces mac-statistics command. This command provides detailed statistics and error counters related to MAC-level operations for network interfaces.
> [show][interfaces] Add proposal for show interface errors {port}

- scripts/queuestat
Fixed the sonic-clear queuecounter issues reported in https://github.com/sonic-net/sonic-buildimage/issues/20913
Fixed the following 2 issues
1) For the egress queue counters, after the queue counter is cleared and show is issued with --nonzero option, the code takes the elif path at line 323 (old code) even if the diff between cached counter and current counter is 0, prints the current counter values from counter_db . This issue was for both egress queue counter and voq counter. 
2)  When the sonic-clear queuecounter is issued , the queuestat is called first without --voq option and this gets the port names and queue ids for each port in each asic , reads the egress queue counters and cache the values in /tmp/cache/queuestat/.  Then queuestat is called with --voq option and this gets all …
> Fixed the issues with sonic-clear queuecounter for egress queue and voq

- scripts/route_check.py
What I did
This PR fixes https://github.com/sonic-net/sonic-buildimage/issues/18773 and https://github.com/sonic-net/sonic-buildimage/issues/20648
Note: resubmitting the PR. The original PR was reverted due to PR check failure. The failure has been root caused and fixed via https://github.com/sonic-net/sonic-mgmt/pull/16013
How I did it
Parallely execute route_check on each Asic.
Parallelly fetch ipv4 routes and ipv6 routes.
execute "time route_check.py" on T2 chassis having 32k v4+32k v6 routes.
Results:
Before:
Checking routes for namespaces: ['asic0', 'asic1']
real 3m16.387s
user 1m26.084s
sys 0m7.275s
After:
time route_check.py
real 1m30.675s
user 1m33.777s
sys 0m8.209s
None
New command …
> speed up route check 202405 v2

- generic_config_updater/field_operation_validators.py
- generic_config_updater/gu_common.py
- tests/generic_config_updater/field_operation_validator_test.py
This is for fix issue:https://github.com/sonic-net/sonic-buildimage/issues/20379
For field_operation_validators, add scope if need read state_db.
```shell
admin@str2-7250-lc1-2:~$ sonic-db-cli STATE_DB -n asic0 hget "PORT_TABLE|Ethernet0" supported_fecs
none,rs
admin@str2-7250-lc1-2:~$ cat fec.json 
[
{
"op": "add",
"path": "/asic0/PORT/Ethernet0/fec",
"value": "fc"
}
]
admin@str2-7250-lc1-2:~$ sudo config apply-patch fec.json 
Patch Applier: asic0: Patch application starting.
Patch Applier: asic0: Patch: [{"op": "add", "path": "/PORT/Ethernet0/fec", "value": "fc"}]
Patch Applier: asic0 getting current config db.
Patch Applier: asic0: simulating the target full config after applying the patch.
Patch Applier: asic0: validating all JsonPatch operations are permitted on the specified fields …
```
> Add scope to field validator.

- scripts/generate_dump
platform renaming for marvell to marvell-prestera platform.
marvell asictype checks are renamed to marvell-prestera
run generate_dump script with the changes in both platforms and verified the outputs remains the same
NA
NA
> platform/marvell renaming to platform/marvell-prestera

- sonic_package_manager/service_creator/creator.py
Now, when the service-creator in sonic-package-manager renders the docker_image_ctl.j2 template, it does not include the sonic_asic_platform info in the render context. The sonic_asic_platform variable is crucial for the manipulation of template rendering, so I added the code to supplement it in the render context.
I added code to acquire sonic_asic_platform info and added it in the render context of docker_image_ctl.j2.
Microsoft ADO: 30477799
Add additional code in the service creator of sonic package manager.
Use the updated sonic-utilities code to build a new VS image.
> add sonic_asic_platform in the render context when rendering docker_image_ctl.j2

- generic_config_updater/field_operation_validators.py
- generic_config_updater/gu_common.py
- tests/generic_config_updater/field_operation_validator_test.py
Reverts sonic-net/sonic-utilities#3675 since it would cause PR test failure:
```
"Traceback (most recent call last):",
"  File \"/usr/local/bin/sonic-cfggen\", line 508, in <module>",
"    main()",
"  File \"/usr/local/bin/sonic-cfggen\", line 346, in main",
"    asic_id = get_asic_id_from_name(asic_name)",
"              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
"  File \"/usr/local/lib/python3.11/dist-packages/sonic_py_common/multi_asic.py\", line 129, in get_asic_id_from_name",
"    raise ValueError('Unknown asic namespace name {}'.format(asic_name))",
"ValueError: Unknown asic namespace name ",
"Failed to apply patch due to: Failed to apply patch on the following scopes:",
"- localhost: Modification of BUFFER_PROFILE table is illegal- validating function …
```
> Revert PR: Add scope to field validator

- counterpoll/main.py
- tests/counterpoll_test.py
To make the 'eni' command only appear in the list of commands when the 'switch_type' is 'dpu'.
This way the "counterpoll --help" output shows only what is supported on the system.
Current output (contains "eni" while the switch_type is not "dpu"):
```
admin@sonic:~$ counterpoll
Usage: counterpoll [OPTIONS] COMMAND [ARGS]...
SONiC Static Counter Poll configurations
Options:
--help  Show this message and exit.
Commands:
acl               ACL counter commands
config-db         Config DB counter commands
eni               ENI counter commands
flowcnt-route     Route flow counter commands
flowcnt-trap      Trap flow counter commands
pg-drop           Ingress PG drop counter commands
port              Port counter commands
port-buffer-drop  Port buffer drop counter commands
queue …
```
> [counterpoll] make the 'eni' command functional only on the DPU

- config/main.py
ADO:[30529412]
Add constraint for YANG when config reload, which is already enabled in load_minigraph
Check YANG vaidation for the config
Unit test
> Enable multi asic golden config YANG validation.

- config/main.py
Removed TRANSCEIVER tables while config reload / load minigraph is executed.
This code adds the option to reserve TRANSCEIVER_INFO table if xcvrd is being restarted. - https://github.com/sonic-net/sonic-platform-daemons/blob/0cb36447ebfda390d999df6516beac4c17315a7b/sonic-xcvrd/xcvrd/xcvrd.py#L2199  
The fix introduced here comes to fix the issue that the table remains also after config reload / load minigraph, which may cause config DB and TRANSCEIVER_INFO table have different ports keys. 
Update config reload command to delete TRANSCEIVER tables: ["TRANSCEIVER_INFO", "TRANSCEIVER_STATUS", "TRANSCEIVER_PM", "TRANSCEIVER_FIRMWARE_INFO", "TRANSCEIVER_DOM_SENSOR", "TRANSCEIVER_DOM_THRESHOLD"]
Execute config reload and make sure TRANSCEIVER tables are deleted
> Delete TRSNCEIVER tables while config reload 

- scripts/generate_dump
Modify the generate_dump to include the BERT data and the platform specified hw-mgmt info
1) Introduced a new function save_sys() which save the /sys/firmware/acpi/tables folder which container the BERT info.  
2) Follow the consistency to modify the collect_broadcom to the platform specified script hw-management-generate_dump.sh if this script exists.   
3) Enhance generate_dump to create log/files.timestamp.info to gather modification timestamp of all log files in the /var/log directory.
1) Execute the "show techsupport" on both Supervisor and Linecard
2) Download and open the show_tech file to verify the following info
- folder hw-mgmt exists and contains the platform specified info
- folder sys/   exists and contains the BERT info
- file log/files.timestamp.info.gz should exist.
> [show_tech] modify generate_dump to includes BERT data and also the platform specified hw-mgmt info

- scripts/ipintutil
- tests/mock_tables/config_db.json
Without this patch an exception is thrown when running `show ip interfaces` when BGP Unnumbered is configured:
```
root@sw1:~# show ip interfaces
File "/usr/local/bin/ipintutil", line 280, in <module>
main()
File "/usr/local/bin/ipintutil", line 273, in main
ip_intfs = get_ip_intfs(af, namespace, display)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/bin/ipintutil", line 236, in get_ip_intfs
ip_intfs_in_ns = get_ip_intfs_in_namespace(af, namespace, display)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/bin/ipintutil", line 149, in get_ip_intfs_in_namespace
bgp_peer = get_bgp_peer()
^^^^^^^^^^^^^^
File "/usr/local/bin/ipintutil", line 51, in get_bgp_peer
local_addr = data[neighbor_ip]['local_addr'] …
```
> show ip interfaces: fix exception with BGP unnumbered

- generic_config_updater/gcu_field_operation_validators.conf.json
Add Mellanox-SN5610N-C256S2, Mellanox-SN5610N-C224O8 to GCU validators
Add Mellanox-SN5610N-C256S2 and Mellanox-SN5610N-C224O8 SKUs to generic_config_updater/gcu_field_operation_validators.conf.json
Deploy an image on SN5610N with one of the mentioned SKUs
N/A
N/A
> [Mellanox] Add Mellanox-SN5610N-C256S2, Mellanox-SN5610N-C224O8 to GCU validators

- generic_config_updater/gcu_field_operation_validators.conf.json
Add Arista 7060X6-64 to gcu validator file.
Added the Arista-7060X6-64DE and Arista-7060X6-64PE hwsku platforms to the th5 entry in the gcu_field_operation_validators.conf.json file.
Run the sonic-mgmt gcu tests and confirm that apply-patch now works for hwskus under these platforms.
202405
202411
> [Arista] Add 7060X6-64 to GCU Validator

- show/platform.py
- tests/show_platform_test.py
- tests/show_test.py
Some platforms may have multiple primary disks which makes it ambiguous to determine the device when there is no device specific in the ssdhealth command
Update the show platform command to check platform.json
1) UT's
```
vkarri@85964d14e169:/sonic/src/sonic-utilities$ pytest-3 tests/show_platform_test.py -k "ssdhealth" -v
collected 8 items / 6 deselected / 2 selected
tests/show_platform_test.py::TestShowPlatformSsdhealth::test_ssdhealth PASSED                                                                                                                                [ 50%]
tests/show_platform_test.py::TestShowPlatformSsdhealth::test_ssdhealth_default_device PASSED                                                                                                                 [100%]
``` …
> [ssdhealth] Check for default device before falling back to discovery

- utilities_common/helper.py
Remove debug dump import by default, Starting 202411, debug dump started to import libdashapi to parse DASH objects. 
Keeping this in default import path is causing CLI execution time to increase. 
Make the import on-demand
UT and verified on the image
> Remove debug dump import by default

- config/main.py
- doc/Command-Reference.md
- tests/config_test.py
Fix issue when 'config qos reload' operation unsuccessful, but returns exit code 0, when operation unsuccessful, now it will return code 1 after executing all the commands.
When config qos reload failed with error print "Operation not completed successfully", exit with code 1 finally, instead of exit with code 0.
Check return value in function _wait_until_clear(), and after config qos reload command finish, check this flag, if it is none zero, then exit 1.
Test with command "config qos reload", will exit 1. Note that "config load_minigraph" is also verified, not impacted.
```bash
Operation not completed successfully, please save and reload configuration.
Running command: /usr/local/bin/sonic-cfggen -d -t /usr/share/sonic/device/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/buffers_dynamic …
```
> [config] Exit with non-zero when qos reload fail

- show/interfaces/__init__.py
- tests/interfaces_test.py
- tests/mock_tables/state_db.json
This pull request introduces a new subcommand to the show interfaces command, allowing users to view error statistics for network interfaces. The new errors subcommand displays a table of potential interface errors, including error types, counts, and the last timestamp (in UTC) when the error occurred. If an error has not been encountered, the count defaults to 0, and the timestamp is displayed as Never. This change helps users easily identify any issues with their network interfaces and track error occurrences.
To implement the errors subcommand, added a new command handler to the show/interfaces/__init__.py file. The handler retrieves the error data for a specified interface from the PORT_OPERR_TABLE in the database. The error types are predefined in a list, and for each type, the count …
> [show][interface] Add changes for show interface errors command

- acl_loader/main.py
- dump/plugins/acl_rule.py
- dump/plugins/acl_table.py
- tests/dump_input/acl/appl_db.json
- tests/dump_input/acl/config_db.json
- tests/dump_tests/module_tests/acl_test.py
- tests/mock_tables/appl_db.json
- tests/mock_tables/state_db.json
- tests/show_acl_test.py
Currently, show and dump CLI only show entries from CONFIG_DB. A lot of new features write ACL Rules to APPL_DB. Thus it is imperative that the CLI's should be updated to display ACL tables and rules from APPL_DB
1) UT's
2) Manual Testing by writing ACL rules to APPL_DB
**ACl rules written to APPL_DB**
```
root@sonic:/home/admin# sonic-db-cli APPL_DB KEYS "*ENI*"
ACL_TABLE_TYPE_TABLE:ENI_REDIRECT
ACL_RULE_TABLE:ENI:Vnet100_F4939FEFC47E_OUT
ACL_TABLE_TABLE:ENI
ACL_RULE_TABLE:ENI:Vnet100_F4939FEFC47E_IN
```
**Show CLI**
```
root@sonic/home/admin# show acl table ENI
Name    Type          Binding      Description                                  Stage    Status
------  ------------  -----------  -------------------------------------------  -------  --------
ENI     ENI_REDIRECT  Ethernet64 …
```
> [ACL] Display rule and table info written to APP DB

- sonic_installer/main.py
- tests/test_sonic_installer.py
Remove partially installer image when image install failed.
When install image failed, partially installed image not removed, which may cause disk full issue on small disk device.
Handle install image SystemExit exception and uninstall image.
Manually verify.
Pass all test case
- Microsoft ADO: 30611724
> Remove partially installer image when image install failed.

- show/platform.py
show platform ssdhealth is failing on multi asic vs platform
```
E sys.exit(cli())
E ^^^^^
E File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in call
E return self.main(*args, **kwargs)
E ^^^^^^^^^^^^^^^^^^^^^^^^^^
E File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
E rv = self.invoke(ctx)
E ^^^^^^^^^^^^^^^^
E File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
E return _process_result(sub_ctx.command.invoke(sub_ctx))
E ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
E return _process_result(sub_ctx.command.invoke(sub_ctx))
E ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in …
```
> Fix ssdhealth failure on multi-asic VS platform

- tests/bgp_commands_test.py
- utilities_common/bgp_util.py
Fix `show ip bgp summary` output when no peer groups are configured
fixes #3737 
Currently when we don't have any peer groups configured, `show ip bgp summary` fails
```
sonic(bash)$ show ip bgp summary
Usage: show ip bgp summary [OPTIONS]
Try "show ip bgp summary -h" for help.
Error: peerGroupCount missing in the bgp_summary
```
vtysh gives more meaningful output in this case:
```
sonic(bash)$ vtysh
Hello, this is FRRouting (version 10.0.1).
Copyright 1996-2005 Kunihiro Ishiguro, et al.
2025/01/27 20:21:52 [YDG3W-JND95] FD Limit set: 1048576 is stupidly large.  Is this what you intended?  Consider using
--limit-fds also limiting size to 100000
sonic# show ip bgp summary
IPv4 Unicast Summary:
BGP router identifier 10.0.0.3, local AS number 65001 VRF default vrf-id 0
BGP table version 48 …
```
> Make 'show ip bgp summary' work even when we don't have any peer groups

- scripts/generate_dump
Fix the calls for spanning-tree commands in dump script.
During call to generate techsupport, we can see that the spanning tree commands fail:
```
.
Error: No such command "spanning_tree".
timeout --foreground 5m bash -c "dummy_cleanup_method ()
.
```
Change from show spanning_tree to the actual command show spanning-tree
Call show techsupport
> Fix call for spanning-tree commands in dump script

- scripts/generate_dump
Modify the generate_dump to archive the /var/lib/systemd/pstore info for the `show techsupport`.  Fixes https://github.com/sonic-net/sonic-buildimage/issues/21526
Add function save_pstore() to generrate_dump script to collect the /var/lib/systemd/pstore info for the `show techsupport`. Also call the save_sys() function to collect /sys/fs/pstore directory info.
1) executes "show techsupport"
2) download the techsupport tra file
3) extract the techSupport tar file. and verify the following 2 directories should exist under sonic-dump 
pstore/
sys/pstore
> [show_techsupport][pstore] Archive /var/lib/systemd/pstore info to show techsupport

- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/config_db.json
- utilities_common/bgp_util.py
Fixing `show ip bgp neighbor neighbor_ip` command in frr unified config mode.
fixes #3736 
Currently this Cli fails for a valid neighbor in frr unified config mode, even when `show ip bgp neighbors` shows this neighbor correctly.
```
rtr1(bash)$ show ip bgp neighbor 10.1.0.2
Usage: show ip bgp neighbor [OPTIONS] [IPADDRESS] [[routes|advertised-
routes|received-routes]]
Try "show ip bgp neighbor -h" for help.
Error:  Bgp neighbor 10.1.0.2 not configured
```
The reason for this is that while trying to make sure neighbor exists in config_db, the code looks at BGP_NEIGHBOR table with key as neighbor_ip, whereas in frr unified config mode, the key is `vrfname|neighbor_ip`. I'm fixing this behavior.
A nice side effect of this fix is that neighbor name now shows up in `show ip bgp summary` …
> Fixing 'show ip bgp neighbor <ip>' in frr unified config mode

- config/main.py
- tests/config_test.py
Don't show an unnecessary warning message (`Operation not completed successfully, please save and reload configuration.`) during config qos reload
**To repro:**
```
root@sonic:/home/admin# sonic-cfggen -H -k Mellanox-SN4700-O8V48 --preset t1 > /tmp/default_config.json
root@sonic:/home/admin# config qos reload
Operation not completed successfully, please save and reload configuration.
Running command: /usr/local/bin/sonic-cfggen -d -t /usr/share/sonic/device/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/buffers_dynamic.json.j2,/tmp/cfg_buffer.json -t /usr/share/sonic/device/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/qos.json.j2,/tmp/cfg_qos.json -y /etc/sonic/sonic_version.yml
Running command: /usr/local/bin/sonic-cfggen -j /tmp/cfg_buffer.json -j /tmp/cfg_qos.json --write-to-db
Buffer …
```
> [QOS] Skip showing unnecessary warning message

- scripts/disk_check.py
- tests/disk_check_test.py
Improve SONiC disk checker to handle disk full case and mount overlay fs to allow remote user login.
This PR depends on DB schema change: https://github.com/sonic-net/sonic-buildimage/pull/21351
Currently disk checker only handle RO disk case, but when disk no free space, remote user also can't login.
Check disk free space and mount overlay fs to allow TACACS login.
Create big file on device, make device no free space. then login with remote user should success.
- Microsoft ADO: 30608100
> Improve SONiC disk checker to handle disk full case and mount overlay fs to allow remote user login.

- counterpoll/main.py
- scripts/db_migrator.py
- scripts/fast-reboot
- tests/counterpoll_test.py
- tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_expected.json
Backport of https://github.com/sonic-net/sonic-utilities/pull/3577
Simplify approach to delaying counters on warm boot and fast boot. Removed FLEX_COUNTER_DELAY_STATUS_FIELD and instead postpone all FC processing to happen after apply view to not delay data plane configuration.
The CONFIG_DB should not be updated in runtime anymore for counters to be delayed.
Removed FLEX_COUNTER_DELAY_STATUS_FIELD and corresponding counterpoll commands (that weren't supposed to be used by user directly anyway). Updated db_migrator.py to remove that field.
Ran fast-reboot from 202405. Made sure no delay field present, counters are enabled and delayed.
> [202411][FC] remove FC delay field

- config/main.py
- tests/config_test.py
Added golden config file content check in config_file_yang_validation.
The function reads a JSON configuration file.
It checks if the configuration is empty or not a dictionary.
If the device is multi-ASIC, it verifies that all required namespaces exist in the configuration.
Patch change into testbed, given below cases to verify
1. Empty file
2. Not dictionary
3. Empty dictionary
4. Missing namespace if platform is multi asic.
5. Normal golden config.
> Add golden config check

- config/main.py
- scripts/dropconfig
- show/dropcounters.py
- tests/config_test.py
- tests/drops_group_test.py
- tests/mock_tables/asic0/config_db.json
- tests/multi_asic_dropstat_test.py
- Added support for iterating over all namespaces (ns) when none specified
- Added a test cases to verify multi-asic behaviour
- Introduced a wrapper class to handle the mutli-asic functionality
This script was missed during the initial efforts to add multi-asic support.
This is in accordance to the issue https://github.com/sonic-net/sonic-buildimage/issues/15148 which tracks the multi-asic support for scripts in sonic-utilities.
The changes were verified by:
Running all the unit tests in sonic-utilities
Verifying the changes manually on a single-asic linecards
Verifying the changes manually on a multi-asic linecards
Screenshots of the manual tests:
> Running on all namespaces when none specified
---
> Running commands on specific namespaces
---
> When an invalid namespace name is passed …
> Add multi-asic support for dropconfig

- config/main.py
- tests/config_test.py
The multiasic golden config is a empty dict, which does not have namespace: [generate](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/library/generate_golden_config_db.py#L399)
Remove multi asic namespace check.
Multi Asic KVM and Testbed
> Remove Multi ASIC namespace Check.

- config/main.py
- tests/subintf_test.py
Subinterface name length validation validates only the interface alias and not the entire subinterface name. This will result in wrong validation.
Fixed the validation to use subinterface name and not just interface alias.
Added test case to verify.
> [subintf]Fix the interface name length validation for subinterface

- doc/Command-Reference.md
- show/interfaces/__init__.py
Adding namespace support for `show interface neighbor expected`. So that we can use
```
show interface neighbor expected -n asic0
```
Verified on T2 testbed
```
admin@somehost:/var/log$ show interfaces neighbor expected -n asic1
Usage: show interfaces neighbor expected [OPTIONS] [INTERFACENAME]
Try "show interfaces neighbor expected -h" for help.
Error: no such option: -n
```
```
admin@somehost:/var/log$ show interfaces neighbor expected -n asic1
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet96   ARISTAXXTX  Ethernet1       None                XXX.XX.XXX.XX   someHub
Ethernet104  ARISTAXXTX Ethernet1       None                XXX.XX.XXX.XX …
```
> Add namespace support for show interface neighbor expected

- sonic_package_manager/service_creator/creator.py
Fix docker ps command showing image ID instead of name:tag issue.
It only impacts dhcp-relay, dhcp-server and macsec.
render_ctx will provide name:tag and j2 template will use it instead of ID.
> Fix command docker ps shows image ID instead of image name issue.

- pfcwd/main.py
Currently, in Cisco 8800 chassis, PFCWD is only enabled for front end ports, not on backplane. As we have PFC enabled for backplane ports, need to enable pfcwd there too.
What I did.
Enable PFCWD for backplane ports.
How I did it
Include backplane ports into the port list to be enabled for pfcwd
manually copied the file to device, and run pfcwd start_default.
(cherry picked from commit 2866ccd9c20231bca87369b93f41f198ce55852b)
> enable pfcwd for backplane ports

- scripts/sfpshow
- utilities_common/sfp_helper.py
`show interface transceiver info Ethernet0` command was failing for CMIS SFP after this change: https://github.com/sonic-net/sonic-platform-daemons/pull/590/files#diff-fc70c43977a1ce57f3a6e9d7d09cb7ea5204f52b3adf3162936205e5680efb2f . Fixed the failing command. 
Added a check for C-CMIS SFP to pick the right dict to generate data.
Run `show interface transceiver info Ethernet0` command on a CMIS SFP.
```bash
root@str4-sn5600-2:/home/admin# show int transceiver info Ethernet0
File "/usr/local/bin/sfpshow", line 733, in <module>
cli()
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main …
```
> Fixes `show interface transceiver info Ethernet0` command failure for CMIS SFP.

- scripts/generate_dump
Adding show route-map commamnd to frr dump in techsupport. This will provide detailed information about route-map across different daemons which is useful for debugging.
Example
```
ZEBRA:
route-map: TO_BGP_PEER_V4 Invoked: 0 Optimization: enabled Processed Change: false
permit, sequence 100 Invoked 0
Match clauses:
Set clauses:
Call clause:
Call CHECK_IDF_ISOLATION
Action:
Exit routemap
BGP:
route-map: TO_BGP_PEER_V4 Invoked: 0 Optimization: enabled Processed Change: false
permit, sequence 100 Invoked 0
Match clauses:
Set clauses:
Call clause:
Call CHECK_IDF_ISOLATION
Action:
Exit routemap
```
Adding the command to list of commands dumped from frr in techsupport.
Running techsupport and verifying
> [Techsupport]Add show route-map command to frr dumps in techsupport

- show/interfaces/__init__.py
- tests/interfaces_test.py
- tests/mock_tables/appl_db.json
cherry-pick #3724 
####
MSFT ADO 
30169187
This PR introduces a new CLI command, show interfaces flap, to display interface flap information. The command fetches details about flap counts, admin and operational status, and timestamps of link down/up events for specified or all interfaces.
- Fetches data from the PORT_TABLE in the APPL_DB.
- Ensures consistent display by sorting the output by interface names.
- Handles single and multiple interface scenarios gracefully, with validation for invalid interface names.
UT and deploy on testbed
> [show][interface] Add changes for show interface flap command (#3724)

- generic_config_updater/field_operation_validators.py
- generic_config_updater/gu_common.py
- tests/generic_config_updater/field_operation_validator_test.py
This is for fix issue:https://github.com/sonic-net/sonic-buildimage/issues/20379. It was done by [PR 3675](https://github.com/sonic-net/sonic-utilities/pull/3675). and it was reverted by https://github.com/sonic-net/sonic-utilities/pull/3689.
This is redo by removing unnecessary change that caused PR test failure.
For field_operation_validators, add scope if need read state_db.
```shell
admin@str2-7250-lc1-2:~$ sonic-db-cli STATE_DB -n asic0 hget "PORT_TABLE|Ethernet0" supported_fecs
none,rs
admin@str2-7250-lc1-2:~$ cat fec.json 
[
{
"op": "add",
"path": "/asic0/PORT/Ethernet0/fec",
"value": "fc"
}
]
admin@str2-7250-lc1-2:~$ sudo config apply-patch fec.json 
Patch Applier: asic0: Patch application starting.
Patch Applier: asic0: Patch: [{"op": "add", "path": "/PORT/Ethernet0/fec", …
```
> Add scope to field validator.[redo PR: 3675]

- config/main.py
- tests/config_test.py
This reverts commit 032a0e03ab0330053a42c899dc049baa337386b9.
Since issue has been resolved: https://github.com/sonic-net/sonic-buildimage/issues/20730?reload=1
> Revert "[config]Restrict YANG validation to Golden Config (#3656)"

- scripts/vnet_route_check.py
- tests/vnet_route_check_test.py
Note: This PR is created from PR #3763 for the master branch.
Added the options `-a` and `--all` to `scripts/vnet_route_check.py`. Both options are equivalent. If none of them is provided, then when finding the VNET routes that are in APP DB but not in ASIC DB, we will ignore routes in APP DB that are not active.
Mock tests in `tests/test_vnet_route_check.py` are added to test this behavior.
If `-a` and `--all` are not provided, we first filter routes in APP DB to find active routes and then check which active routes are not in ASIC DB. The status of each route is retrieved from STATE DB. If a route is not found in STATE DB, then it is considered to be active.
You can verify the behavior by running mock tests in `tests/test_vnet_route_check.py`, or by manually running the …
> [202405] Fix `vnet_route_check` for active and inactive routes, add `--all` option

- scripts/sfpshow
- tests/sfp_test.py
Signed-off-by: Anand Mehra anamehra@cisco.com
Fixed the "ERR python3: [ :- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig]"
error when running 'show interfaces transceiver <>' commands.
e.g. show interfaces transceiver info Ethernet0
The error is observed in syslogs but not on the command line.
This log was seen while running snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py::test_m2o_fluctuating_lossless[multidut_port_info1] ERROR [100%]
E               Match Messages:
E               2025 Jan  7 06:27:14.025905 svcstr2-8800-lc1-1 ERR python3: :- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig
E               
E               2025 Jan  7 06:27:19.861658 svcstr2-8800-lc1-1 ERR python3: …
> Fixed syslog error "ERR python3:- validateNamespace: Initialize global.." for sfpshow

- config/kdump.py
- scripts/sonic-kdump-config
- show/kdump.py
- tests/kdump_test.py
- tests/sonic_kdump_config_test.py
**What I did**
Added remote kdump functionality using SSH in SONiC. 
**How I did it**
I added two new commands and two options to configure the kdump remote ssh feature.
Upon kernel crash, kdump will transfer the crash report files to the ssh server.
> kdump-Remote-SSH-Configurations

- scripts/dpu-tty.py
- Updated dpu-tty.py to run fifo enable configuration commands after exiting from dpu console.
- Read the command lists from platform.json if present and execute it.
- Command to Write to fifos_enable in Sysfs path
- Added the steps in UT
- No change
Sample DPU content in Platform.json:
```
"DPUS": {
"dpu0": {
"bus_info": "[0000:]1A:00.0",
"midplane_interface":  "dpu0",
"serial-console": {
"device": "ttyS4",
"baud-rate": "115200"
},
"tty-post-cmds": ["stty -F /dev/ttyS4 115200 cs8 ignpar -cstopb -clocal",
"echo 1 > /sys/bus/platform/devices/uxbar/modem0/fifos_enable"]
},
"dpu1": {
"bus_info": "[0000:]16:00.0",
"midplane_interface":  "dpu1",
"serial-console": {
"device": "ttyS5",
"baud-rate": "115200"
},
"tty-post-cmds": ["stty -F /dev/ttyS5 115200 cs8 ignpar -cstopb -clocal",
"echo 1 > …
```
> Added post commands for enabling fifos

- config/muxcable.py
- tests/muxcable_test.py
Support reset heartbeat suspend timer on active-standby dualtor mux ports.
This depends on https://github.com/sonic-net/sonic-linkmgrd/pull/286.
* Microsoft ADO (number only): 31520887
Add sub CLI `config muxcable reset-heartbeat-suspend` to write the reset port list to `MUX_LINKMGR|LINK_PROBER`.
The DB operations of `config muxcable reset-heartbeat-suspend all`:
```
1740387788.261626 [4 unix:/var/run/redis/redis.sock] "HSET" "MUX_LINKMGR|LINK_PROBER" "reset_suspend_timer" "Ethernet12,Ethernet16,Ethernet20,Ethernet24,Ethernet28,Ethernet32,Ethernet36,Ethernet4,Ethernet40,Ethernet44,Ethernet48,Ethernet52,Ethernet56,Ethernet60,Ethernet64,Ethernet68,Ethernet72,Ethernet76,Ethernet8,Ethernet80,Ethernet84,Ethernet88,Ethernet92,Ethernet96" …
```
> [dualtor] Support reset heartbeat suspend timer on active-standby ports

- doc/Command-Reference.md
cherry-pick #3627 
The show interfaces flap command provides detailed insights into interface events, including the timestamp of the last link down event and the total flap count (number of times the link has gone up and down). This helps in diagnosing stability and connectivity issues.
added documentation for show interfaces flap with a detailed output
> [show][interfaces] Add proposal for show interfaces flap (#3627)

- generic_config_updater/gcu_field_operation_validators.conf.json
Set ASIC of Arista-7050CX3-32S-C28S4 to td3.
> [Arista] Add Arista-7050CX3-32S-C28S4 to generic_config_updater

- config/main.py
- tests/config_test.py
Remove multi asic check for reload operation since multi asis golden config has finished qualification.
> Enable config reload yang validation for multiasic

- show/platform.py
- tests/show_platform_test.py
- tests/show_test.py
Fix `show platform ssdhealth` not showing expected output when a usb flash drive is plugged in. 
When 'show platform ssdhealth' is not supplied with a device name and a usb flash drive is attached we show incorrect output as we deduce incorrect device name from 'lsblk' command and pass it to ssdutil. I removed this incorrect deduction of the device name.
Instead of incorrectly deducing the device using the lsblk command we can instead not pass any device name as argument to the ssdutil and it will automatically choose the device on which /host partition is mounted which is the primary storage device in our case as per the PR: https://github.com/sonic-net/sonic-utilities/pull/3399
Run `sudo show platform ssdhealth` without any arguments with a flash drive plugged into the sonic switch. …
> Fix show platform ssdhealth not showing expected output when a usb flash drive is plugged in

- config/main.py
- tests/config_test.py
Set admin_status to 'up' for loopback interfaces on interface startup.
Set admin_status to 'down' for loopback interfaces on interface shutdown.
Related PRs: [https://github.com/sonic-net/sonic-swss/pull/3565](https://github.com/sonic-net/sonic-swss/pull/3565)
Updated config/main.py
pytest config_test.py::TestConfigInterface::test_startup_shutdown_loopback tests loopback interface startup/shutdown modifies admin_status as expected.
n/a
n/a
> Update loopback interface admin status on config interface startup/shutdown

- scripts/fast-reboot
MSFT ADO: 32296065
Added an additional safety check before proceeding to warm-reboot.
Added a blocking check into the warm-reboot/fast-reboot script. If at the time of setting up the VXLAN tunnel, there is leftover/pre-existing VXLAN configuration, the script will exit with an error message.
Create leftover VXLAN config. This can be easily done by running the neighbor_advertiser setup script: `/usr/local/bin/neighbor_advertiser -s 10.64.247.9 -m set`
Then trigger a warm-reboot: `sudo warm-reboot -c 10.64.247.9 -v`
warm-reboot command output:
```
sudo warm-reboot -c 10.64.247.9 -v
...
2025 Apr 14 07:51:43.499136 str2-7260cx3-acs-9 NOTICE root: Found leftover SAI_OBJECT_TYPE_TUNNEL with SAI_TUNNEL_ATTR_TYPE: SAI_TUNNEL_TYPE_VXLAN. (key = …
```
> Added protection for warm-upgrade when leftover VXLAN config is present

- scripts/fast-reboot
- scripts/reboot
When rebooting or doing a warm/fast reboot, stop the hwclock service and timer files before running `hwclock -w`. This removes the chance of a race condition where both of them run at the same time, causing one of them to fail.
Fixes sonic-net/sonic-buildimage#22230
This is a race condition, and as such, may require a couple hundred reboot attempts to occur. With the fix, it's expected that this race condition will not occur at all.
> [202411] Stop the hwclock service and timer files before updating CMOS time

- scripts/route_check.py
The route_check.py on UpStream LC of virtual chassis takes a longer time to complete while the current timeout limit is 2 mins. Thus, I want to:
1. Set a larger timeout when the device is a virtual chassis.
2. Speedup the route_check process a bit by simplifying the string manipulation.
> Set the timeout to be larger on VS chassis and speedup a bit

- scripts/generate_dump
`show queue counters` is supported and runs on host instance, even for mult-asic platforms.
We don't have to run `show queue counters` for each asic namespace.
This fixes https://github.com/sonic-net/sonic-buildimage/issues/22394
Modifiy generate_dump to call `save_cmd` instead of `save_cmd_all_ns` for `show queue counters`
Run `show techsupport` on multi-asic platform.
Verfiy that  the `queue.counters` files show correct information.
> [chassis][show_tech]Fix show queue counters to only run on host

- generic_config_updater/patch_sorter.py
- tests/generic_config_updater/files/change_applier_test.data.json
- tests/generic_config_updater/files/patch_sorter_test_success.json
- tests/generic_config_updater/patch_sorter_test.py
Added support to mark the `vnet_name` field as a create-only field in `VLAN_INTERFACE`, `VLAN_SUB_INTERFACE`, and `INTERFACE` tables.
1. Updated `patch_sorter.py` to include the following patterns as create-only fields:
```python3
["VLAN_SUB_INTERFACE", "*", "vnet_name"],
["VLAN_INTERFACE", "*", "vnet_name"],
["INTERFACE", "*", "vnet_name"]
```
2. Added test data in `patch_sorter_test.py` to verify these fields are identified as `create-only`.
3. Updated `change_applier_test.data.json` with example entries containing `vnet_name` fields.
4. Added unit tests in `patch_sorter_test_success.json` for `test_patch_sorter_success` in `patch_sorter_test.py`
> Vnet_name added in create_only patterns

- scripts/fast-reboot
Issue introduced in https://github.com/sonic-net/sonic-utilities/pull/3170
lag_keepalive invokes teamdctl which is a wrapper around docker exec -i. This command is known to not work togather with timeout and similar issues have been fixed before - https://github.com/sonic-net/sonic-utilities/pull/1904
Add ```--foreground``` option for timeout to receive TTY signals.
Run warm or fast reboot.
> [warm/fast-reboot] fix lag_keepalive.py hang

- scripts/generate_dump
Include component-versions file for sonic nvidia bluefield dpu
I enabled the get_component_versions.py script for the bluefield dpu through the PR [here](https://github.com/sonic-net/sonic-buildimage/pull/22100)
Once that is merged this change helps enable component-versions file is included in the generated dump for the dpu
component-versions file included in the generated dump
**NOTE**: This PR must be merged only after [this PR](https://github.com/sonic-net/sonic-buildimage/pull/22100) is merged into the sonic-buildimage repository.
> [nvidia-bluefield] Generate component-versions file for the dpu in the generated dump

- config/main.py
In `sudo config load_minigraph --override_config -y`,  it will call `pfcwd start_default` by default.
```
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
......
Running command: pfcwd start_default
Running command: config override-config-table /etc/sonic/golden_config_db.json
```
When golden_config_db.json has `"default_pfcwd_status": disable`, pfcwd should not be generated in the config.
However, in current code, when `pfcwd start_default` is called, the `default_pfcwd_status` is still using the value in `init_cfg.json` which is `enable`.  So, pfcwd configuration is still generated even though it's not needed.
Disable default_pfcwd_status for all lossy platform.
Check `default_pfcwd_status` in `golden_config_db.json` and skip `pfcwd …
> skip pfcwd if disabled in golden_config

- .gitignore
- doc/Command-Reference.md
- show/main.py
- tests/bfd_input/bfd_masic_test_vectors.py
- tests/mock_tables/asic0/state_db.json
- tests/multi_asic_show_bfd_test.py
Added the namespace support for `show bfd summary` & `show bfd peer <peer_id>` command. For example, users can run `show bfd summary -n asic0`, `show bfd peer 10.0.1.1 -n asic0` and etc.
Run `show bfd summary -n <namespace>` and `show bfd peer <peer_id> -n <namespace>` and verify the output
Nothing has changed to the output of these 2 commands, we are only adding the namespace argument support in this PR. Users can still use the `sudo ip netns exec asicX  ...` way after this PR.
I confirmed the output of `sudo ip netns exec asicX show bfd summary` and `show bfd summary -n asicX` are the same, and `sudo ip netns exec asicX show bfd peer <peer_id>` and `show bfd peer <peer_id> -n asicX` are the same
Nothing has changed to the output of these 2 commands, we are only adding the namespace …
> feat: support namespace arg for show bfd commands

- config/aaa.py
- tests/aaa_test.py
- tests/radius_test.py
Currently all AAA config commands create a new `ConfigDBConnector` object for every operation. This doesn't interact well with the pytest mock infrastructure used in the unit tests. I changed the AAA config commands to accept a `ConfigDBConnector` from the top-level command, which follows the standard pattern used by other config commands (such as those in [sonic-utilities/config/main.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/main.py)).
I fixed up tests so that they actually test config functionality, instead of manually manipulating the mock DB to return valid show results.
Some expected output in tests was not in line with actual product output. I updated the expected output in these cases.
fixes #3754 
Convert AAA config commands to use the pass_db decorator …
> Issue #3754: Modify AAA config commands to use pass_db decorator

- config/aaa.py
- tests/radius_test.py
Enabling RADIUS `statistics` adds config entries which are not valid in YANG.  The option adds the True/False boolean values instead of the 'true'/'false' booleans that are defined in the YANG model, which causes failures when trying to reload/replace the config.
Fixes: [#22407](https://github.com/sonic-net/sonic-buildimage/issues/22407)
Modified relevant config command to use the correct values.
Manually verified.
I added a test case for `config radius statistics` command. Note that this test follows the pattern in this file, which is not actually exercising the correct codepath (see https://github.com/sonic-net/sonic-utilities/issues/3754 for details).
> Issue #22407: ConfigReload fails when RADIUS options are enabled

- scripts/db_migrator.py
- tests/db_migrator_test.py
Fixed migration error during upgrade from 202411_02.
- Added version_202411_02 function in db_migrator to support proper migration during upgrade
(called dynamically via getattr from the migrate function).
- Updated db_migrator_test accordingly.
Manual:
- Use canonical setup with 202411 image
- Verify the version in config_db and Redis is version_202411_02
hget VERSIONS|DATABASE VERSION
vim /etc/sonic/config_db.json
- Install master image and reboot
- Check syslog for db_migrator errors or run config reload
Automatic:
- Use canonical setup with 202411 image
- Verify the version in config_db and Redis is version_202411_02
- Run test_deploy-and-upgrade
Additional Option:
- Verify the version in config_db and Redis is version_202411_02
- Run the following command to migrate (to 202505_01): …
> [db_migrator] Add version_202411_02

- scripts/route_check.py
- tests/route_check_test_data.py
1. Skip checking offload flags for static routes and static SIDs in FRR in check_frr_pending_routes.
2. Add check_sids to check consistency between MY_SID tables of ASIC_DB and APPL_DB
Run on a device supporting SRv6
> Skip checking offload flags for static routes/sids in route check and add check_sids

- show/main.py
Add an additional check in the cmd of the get_routing_stack function to detect the "frr" or "quagga"
Modify the CMD, add "grep -E 'quagga|frr'" in CMD
quagga
```
admin@bjw-can-7050qx-1:~$ sudo docker ps | grep bgp | grep -E 'quagga|frr' | awk '{print$2}' | cut -d'-' -f3 | cut -d':' -f1 | head -n 1
quagga
admin@bjw-can-7050qx-1:~$ 
```
frr
```
admin@str3-7060-acs-2:/usr/local/lib/python3.11/dist-packages/show$ docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED             STATUS             PORTS     NAMES
8a9e151d08bb   docker-sonic-restapi              "/usr/local/bin/supe…"   About an hour ago   Up About an hour             docker-sonic-restapi_but_bgp
21b846f8d085   docker-fpm-frr:latest             "/usr/bin/docker_ini…"   6 hours ago …
```
> fix issue #22476 fix show cmd for bgp

- config/main.py
- tests/config_test.py
Fix the issue introduced by [Enable config reload yang validation for multiasic #3825](https://github.com/sonic-net/sonic-utilities/pull/3825).
Fix the `config reload` flow in case when multiple `golden_config.json` files provided.
Add check for multi-asic.
Manual verification by running the:
```
cisco@sonic-lc5:~$ sudo config reload -y -f -l /etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json
```
Run the whole sonic-utilities UT suite.
```
cisco@sonic-lc5:~$ sudo config reload -y -f -l /etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json
Acquired lock on /etc/sonic/reload.lock
Released …
```
> [multi-asic] Fix the 'config reload' flow in case when multiple golden_config.json files provided

- scripts/ecnconfig
- tests/ecn_input/ecn_test_vectors.py
- tests/multi_asic_ecnconfig_test.py
https://github.com/sonic-net/sonic-buildimage/issues/22856
Fixed the ECN cli command to use the system ports for ECN config for voq switch to address
https://github.com/sonic-net/sonic-buildimage/issues/22856
Changed the ecnconfig to use the system ports for ECN config for voq switch
Verified with configuring ECN for certain queues on voq switch
> Fixed cli command for ECN config on voq switch

- sonic_cli_gen/yang_parser.py
- tests/cli_autogen_input/yang_parser_test/assert_dictionaries.py
sonic-yang-mgmt now integrates uses clauses as if a uses clause didn't exist. No need to have this complex handling in sonic-utilities.
Depends on https://github.com/sonic-net/sonic-buildimage/pull/21907
Fixes https://github.com/sonic-net/sonic-buildimage/issues/22382
Besides removal of the code, the only test case changes are the removal of the 'grouping' clause as it is specific to 'uses' which is not relevant and some minor reordering of expected responses.
Run `tests/cli_autogen_yang_parser_test.py` after applying both this PR and https://github.com/sonic-net/sonic-buildimage/pull/21907
N/A
N/A
Signed-off-by: Brad House (@bradh352)
> YANG: remove uses clause handling, now part of sonic-yang-mgmt

- config/chassis_modules.py
- tests/chassis_modules_test.py
Fixed issue #22138
Replaces PR: #3845 which was closed accidentally
The corresponding sonic-platform-daemon PR is : https://github.com/sonic-net/sonic-platform-daemons/pull/607
What I did
Fixed issue #22138
Chassisd does not wait for the execution to complete for previous admin state change requests. Added support to solve this.
How I did it
Added a state to indicate the progress of an admin_state transition period (window) of every module in config_db.
When in progress do not allow another admin_state change for that module.
Mark the beginning of state transition in the CLI itself. Added a timeout also for error cases.
Mark the end of state transition in chassisd.
Issue "config chassis module startup DPU0". This takes around 3 mins. Check the config_db and verify the new …
> Fix for 22138: Chassisd does not wait for the execution to complete for previous admin state change requests - Replaces PR: #3845

- doc/Command-Reference.md
- dump/plugins/copp.py
- show/copp.py
- show/main.py
- tests/copp_input/mock_config/mock_copp_cfg.json
- tests/copp_test.py
- tests/mock_tables/config_db.json
- tests/mock_tables/state_db.json
Port from master branch PR #3863
CoPP show commands:
* show copp configuration
* show copp configuration detailed --trapid <trap_id>
* show copp configuration detailed --group <group>
Added UT for the CLI commands.
Details in HLD: [sonic-net/SONiC#1943](https://github.com/sonic-net/SONiC/pull/1943)
Verified with UT
```
admin@sonic:~$ show copp configuration
TrapId           Trap Group     Action      CBS    CIR  Meter Type    Mode    HW Status
---------------  -------------  --------  -----  -----  ------------  ------  -------------
arp_req          queue4_group2  copy        600    600  packets       sr_tcm  installed
arp_resp         queue4_group2  copy        600    600  packets       sr_tcm  installed
bgp              queue4_group1  trap       6000   6000  packets       sr_tcm …
```
> Added CoPP show configuration command

- generic_config_updater/gcu_field_operation_validators.conf.json
Add GCU support for Mellanox-SN4280-C48, Mellanox-SN4280-O8C40 and Mellanox-SN4280-O8V40 SKUs to spc3 platforms.
> Add GCU Support for SKU Mellanox-SN4280-C48/O8C40/O8V40

- sonic-utilities-data/templates/sonic.service.j2
- sonic_package_manager/manifest.py
This change allows package developers to specify the systemd service type in their package manifests, which will be reflected in the generated systemd service files.
- Add optional 'type' field to service section in manifest schema
- Update sonic.service.j2 template to conditionally include Type= directive
> [SPM] Add support for configuring systemd service Type in package manifests

- sonic_package_manager/database.py
- sonic_package_manager/package.py
- sonic_package_manager/service_creator/creator.py
- sonic_package_manager/source.py
- tests/sonic_package_manager/conftest.py
- tests/sonic_package_manager/test_database.py
- tests/sonic_package_manager/test_manager.py
- Added functionality to save and track the Docker image tag used during package installation
- Modified the service creator to include the tag information in container configuration
- This change will improve visibility in `docker ps` output by showing the actual tag used for each container
- Added a new `tag` field to the `Package` class to store the image tag
- Modified the `PackageSource` class to save the tag from the installed image
- Updated the `ServiceCreator` to include the tag information in the container configuration
- The tag is extracted from the first tag in the image's tags list during installation
1. Install a package using sonic-package-manager
2. Run `docker ps` to verify that the container is running with the correct tag
3. Check the container configuration to ensure …
> [sonic-package-manager] Save tag that was used to install the application

- clear/main.py
- show/main.py
The PR https://github.com/sonic-net/sonic-utilities/pull/3960 check the docker container's name.
Check the docker's name whether is exactly same with "bgp"
However, on multiple asic devices, there are several bgp containers, and named bgp0, bgp1 ....
Modified the cmd to handle the multiple asic with several bgp containers.
Verified on multiple devices:
```
admin@strtk5-8800-lc1-1:~$ docker ps -a | grep bgp
8ff934f85dfb   docker-fpm-frr:latest             "/usr/bin/docker_iniâ€¦"   40 hours ago   Up 19 hours             bgp1
5702ae6e60c2   docker-fpm-frr:latest             "/usr/bin/docker_iniâ€¦"   40 hours ago   Up 19 hours             bgp0
e059d9688b25   docker-fpm-frr:latest             "/usr/bin/docker_iniâ€¦"   40 hours ago   Up 19 hours             bgp2
admin@strtk5-8800-lc1-1:~$ …
```
> [202411] fix show bgp cli on multiple asic device

- clear/main.py
- show/main.py
The PR https://github.com/sonic-net/sonic-utilities/pull/3960 check the docker container's name.
Check the docker's name whether is exactly same with "bgp"
However, on multiple asic devices, there are several bgp containers, and named bgp0, bgp1 ....
Modified the cmd to handle the multiple asic with several bgp containers.
run the cmd manually on both multiple and single asic device
https://github.com/sonic-net/sonic-utilities/pull/3980
> fix show bgp cli on multiple asic device

- scripts/vnet_route_check.py
- tests/vnet_route_check_test.py
Changed `vnet_route_check.py` so that when a VNET route is missing in STATE DB, then it is treated as an inactive route. This means that when the script is called without `-a` and `--all` options, if a route in APP DB is missing in both STATE DB and ASIC DB, it will not be reported as a mismatch.
1. Changed the logic in `vnet_route_check.py`.
2. Added a new test and modified an existing test in `vnet_route_check_test.py` to verify the desired behavior.
Run the tests in `vnet_route_check_test.py`.
N/A
N/A
> `vnet_route_check.py` should not report VNET routes in APP DB but not in STATE DB and ASIC DB as mismatches

- scripts/intfutil
- tests/vlan_test.py
Fixed "show interfaces status" output for interfaces with switchport mode configuration.
Configured "switchport mode" is fetched from DB for all front panel ports and PortChannel interfaces.
"Vlan" column in "show interface status"  is displayed based on below considerations:
1. If interface is part of PortChannel - display PortChannel interface name [present behavior]
2. If "switchport mode" is configured on interface [Ethernet/PortChannel] - display configured mode [new behavior]
3. If "switchport mode" is NOT configured on interface but part of a VLAN [Ethernet/PortChannel] - display as "trunk" [present behavior]
4. If "switchport mode" is NOT configured on interface and NOT part of a VLAN [Ethernet/PortChannel] - display as "routed" [present behavior]
Configure "switchport mode" for …
> Switchport mode update for 'show interfaces status'

- fwutil/lib.py
- tests/fwutil_test.py
When running the `test_fwutil_update_current` test in  https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/fwutil/test_fwutil.py we encounter the following issue when we run the command
```
admin@sonic:$ sudo fwutil update chassis component ONIE fw -y
Error: Failed to parse "platform_components.json": invalid platform schema: "module" key hasn't been found. Aborting...
Aborted!
```
This is because platform_components.json for smartswitch doesn't have module key in it and this should be ignored for smartswitch.
Avoid any modular chassis operations on smart-switch.
Added a check to verify the device is not a smart switch before treating it as a modular chassis.
> Exclude Smart Switch from modular chassis operations/checks

- sonic_package_manager/database.py
- sonic_package_manager/service_creator/creator.py
- sonic_package_manager/source.py
- tests/sonic_package_manager/conftest.py
- tests/sonic_package_manager/test_database.py
- tests/sonic_package_manager/test_manager.py
Rename the variable tag to docker_image_reference since it can also hold image digest.
Change the variable name to match the name agreed on  https://github.com/sonic-net/sonic-buildimage/pull/22911
Install App Extension
> [SPM] Rename the variable tag to docker-image-reference

- sfputil/debug.py
- tests/sfputil_test.py
OutputStatusTx and OutputStatusRx are only supported since CMIS 5.0. `sfputil debug tx-output` and `sfputil debug rx-output` should check them only if CMIS rev is higher or equal to 5.0.
1. Use `get_tx_disable` and `get_rx_disable` to check if the corresponding bits have been set by `sfputil debug` command
2. Check the CMIS rev, ignore checking of OutputStatusTx and OutputStatusRx if CMIS rev is below 5.0.
1. Manual test
2. unit test
> [sfputil debug] Fix issue: do not check output status when CMIS version is lower than 5.0

- show/chassis_modules.py
Fix for #23205 [Smartswitch] Issues caused due to introduction of the chassisd/sonic-utiltiies changes for consecutive admin state changes
Description
Fixes #23205
The corresponding sonic-platform-daemon commit is: # https://github.com/sonic-net/sonic-platform-daemons/pull/645
Motivation and Context
Some recent design changes not initializing some fields in DPU_STATE and DPU_MODULE_INFO tables.
How Has This Been Tested?
initializing the fields in DPU_STATE and DPU_MODULE_INFO tables
> Fix for #23205 [Smartswitch] Issues caused due to introduction of the chassisd/sonic-utiltiies changes for consecutive admin state changes

- scripts/generate_dump
Add output for `dpuctl dpu-status` for mellanox specific smartswitch devices in the generate_dump command
Add `save_cmd` output for `dpuctl dpu-status` it will be written to `dpu_status` file as part of the dump
Generate dump using `show techsupport` command and checked the output to see if the `dpu_status` file is created
> [Mellanox][Smartswitch]Added dpu status output

- scripts/sfpshow
- sfputil/main.py
- tests/mock_tables/state_db.json
- tests/sfp_test.py
- tests/sfputil_test.py
- utilities_common/sfp_helper.py
This PR enhances the sfputil and sfpshow CLI tools to properly display EEPROM and DOM data for all CMIS-compliant transceivers, not just QSFP-DD and OSFP modules. The enhancement replaces hardcoded transceiver type checks with a more generic detection method based on the presence of the cmis_rev field in transceiver information.
https://github.com/sonic-net/sonic-utilities/blob/252a643567dda88ddf93a72508e0331cdd7cb677/sfputil/main.py#L340
https://github.com/sonic-net/sonic-utilities/blob/252a643567dda88ddf93a72508e0331cdd7cb677/sfputil/main.py#L396
https://github.com/sonic-net/sonic-utilities/blob/252a643567dda88ddf93a72508e0331cdd7cb677/sfputil/main.py#L414
Currently, the transceivers which have identifier register value as 0x1e (`QSFP+ or later with CMIS`) show EEPROM and DOM output for …
> sfputil and sfpshow eeprom and DOM CLI enhancement to display data for all CMIS transceivers

- config/plugins/nvidia_bluefield.py
- tests/config_nvidia_bluefield_test.py
Added a New Config plugin implementing CLI commands for nvidia-bluefield sdk
packet-drop: Captures packet drops in the NASA pipeline.
config-cli: Captures config applied in a format applied to NASA team
These debug 'bin' files are captured during techsupport
Also, this config is not persistent and will not survive config-reload/reboot and is disabled by default
```
config platform nvidia-bluefield sdk config-record enabled
config platform nvidia-bluefield sdk config-record disabled
config platform nvidia-bluefield sdk packet-drop enabled
config platform nvidia-bluefield sdk packet-drop disabled
```
UT:
verify on the device to make sure if the changes are applied
> [nvidia-bluefield] Add CLI for packet-drop and config-record

- config/main.py
- show/main.py
- tests/suppress_pending_fib_test.py
CLI commands part of the fix for issue (https://github.com/sonic-net/sonic-buildimage/issues/19022)
- To send the suppress-fib-pending configuration to all asics in multi-asic system
- Show command to diplay current suppress-fib-pending configuration for all available asics
- Unit tests to test the multi-asic support of suppress-fib-pending configuration
- In a multi-asic device configure suppress-fib-pending using command "sudo config suppress-fib-pending enabled"
- Check the config db of all asics to verify whether the "suppress-fib-pending": "enabled" fv pair is avialable in the config db DEVICE_METADATA
- Run the same test for "disabled" 
admin@sonic:~$ show suppress-fib-pending 
Enabled
admin@sonic:~$ show suppress-fib-pending 
asic0: Enabled
asic1: Enabled
admin@sonic:~$
> [config show]BGP Suppress fib pending config and display for multi-asic

- sonic_package_manager/database.py
- sonic_package_manager/service_creator/creator.py
- sonic_package_manager/source.py
- tests/sonic_package_manager/conftest.py
- tests/sonic_package_manager/test_database.py
- tests/sonic_package_manager/test_manager.py
Rename entry tag variable to docker_image_reference
- Run all package manager tests: pytest tests/sonic_package_manager
- Install App Extension
> [spm] Rename entry tag variable to docker_image_reference

- config/main.py
- scripts/dropconfig
- show/dropcounters.py
- tests/config_test.py
- tests/dropconfig_test.py
- tests/drops_group_test.py
- tests/mock_tables/asic0/config_db.json
- tests/mock_tables/asic0/state_db.json
- tests/mock_tables/config_db.json
- tests/mock_tables/counters_db.json
- tests/mock_tables/state_db.json
This PR enables users to proactively monitor and identify persistent packet drops in their SONiC environment, improving network stability and troubleshooting capabilities.
Fixes https://github.com/sonic-net/sonic-utilities/issues/3757
*   Implements commands to configure persistent drop monitor thresholds.
*   Adds support for setting monitoring window size, drop count threshold, and incident count threshold.
*   Includes `show dropcounters persistent-drops` command to display persistent drop alerts.
*   Provides `config dropcounters enable-monitor/disbale-monitor` command to enable/disable the feature.
*   Adds unit tests to cover the new CLI functionality.
*   Configurable monitoring window: Users can specify the time window (in seconds) for detecting persistent drops.
*   Adjustable …
> [show][config] Add CLI support for configurable drop monitor feature

- scripts/ecnconfig
Set ECN ON/OFF for all the Voq's in the asic in the Voq system to fix https://github.com/sonic-net/sonic-buildimage/issues/22856
The existing code was setting ECN ON/OFF for only local front panel ports Voq's. However in the Voq system, the ECN should be ON/OFF for all the Voqs in the namespace including the Voq's of the remote asics.
Verified the ECN functionality in the Voq chassis.
None
None
> Fixed cli command for ECN config on voq switch to set the WRED_PROFILE for all Voqs

- tests/remote_cli_test.py
Python 3.13 will raise a SIGTTOU signal when getpass.getpass is called in a background process, like when running under pytest. Add a signal handler to `tests/remote_cli_test.py` to handle SIGTTOU whenever `getpass.getpass()` is called, since this will raise SIGTTOU when running `trixie`.
This closes [#23798](https://github.com/sonic-net/sonic-buildimage/issues/23798)
Wrap the call in a signal handler to ignore the signal. This avoids a hang when running `trixie`.
> Issue 23798: (trixie) Wrap getpass.getpass in a signal handler to avoid SIGTTOU

- generic_config_updater/field_operation_validators.py
- tests/generic_config_updater/field_operation_validator_test.py
Skip port speed validation for chassis
MSFT ADO: 35177627
Issue: https://github.com/sonic-net/sonic-buildimage/issues/23945
If device is chassis, skip port speed validation when applied a jsonpatch contains port speed related change.
Tested in lab and stage device.
> Skip speed validation for chassis.
