scripts/fast-reboot, setup.py
Add fast-reboot utility to reboot SONiC box using kexec-tools.
Add fast-reboot to kernel parameters to indicate that kernel was loaded after fast reboot
=> Add fast-reboot

scripts/portstat
=> [Portstat]: return N/A if no counter info exists

show/main.py
- Now calling `decode-syseeprom`, `cat /var/log/syslog` and `tail -f /var/log/syslog` using sudo.
- Minor refactoring of `show logging`:
- Changed option from `--tail` to `--lines`
- Made `--follow` option into a boolean flag that takes no argument
- Added abbreviated `-l` and `-f` options
TODO: Add  `decode-syseeprom`, `cat /var/log/syslog` and `tail -f /var/log/syslog` to /etc/sudoers in sonic-buildimage repo when updating this submodule.
=> Add 'sudo' to required calls

show/main.py
Default commands in a group prevent the use of autocomplete, which can prevent a user from knowing all of the available commands within that group.
See issue https://github.com/Azure/sonic-utilities/issues/27
TODO: If we agree not to use "default groups" in the future (I vote "no") we can also remove the installation and importing of "click_default_group" altogether.
=> [show]: Remove default commands from groups as they are confusing to users

scripts/fast-reboot, scripts/fast-reboot-dump.py, setup.py
1. Save fdb and arp entries inside of json files to allow consume them by swssconfig later
2. Explicitly kill -9 bgpd process to start graceful restart BGP feature.
=> [Fast-reboot]: Keep fdb and arp tables state between fast reboots

scripts/aclshow
- The counter of the corresponding ACL cannot be queried until it is
successfully created. Display 'N/A' when the counter of an ACL rule
is not available.
=> [aclshow]: Display 'N/A' when an ACL is not yet successfully created

config/main.py, sonic_installer/main.py
BGP admin state will be recorded when calling `config bgp neighbor shutdown` and `config bgp neighbor startup`. Those states will be preserved upon bgp service restart and firmware version upgrade.
=> [config and sonic-installer] Support bgp admin state preserving

scripts/aclshow
- Without -d or --details option, simplify the output by skipping the rules
that doesn't match any packets till now.
- Sort the output by sorting using table name first and then descending priority.
=> [aclshow]: Skip rules with 0 count and sort the output

sonic_sfp/sfputilbase.py
allow flexible mapping between front panel port name and index
=> [sfputil]: Use front panel index in port_config.ini to locate the front panel port

show/main.py
- These temporary files are owned by the logged-in user. If the files share the same name for all users, in the case where these files don't get deleted as they should, the commands will fail for other users because they don't have permission to write to them. This fix appends the logged-in username to the temporary filename to ensure the files are only ever modified by the same user.
=> [show]: Append username to temporary template filenames to prevent inter-user issues

scripts/aclshow
The current behavior is to display all ACL counters with value greater than 0.
It is necessary to know the whole ACL table to track if certain rule is there or not.
=> [aclshow]: Add an option -a to display all ACL counters

config/main.py
For BGP admin status, CLI will now only write config into DB, and config daemon in bgp docker will do actual config job.
=> [config] Adapt to config DB

config/main.py
`config save` will export current config db content into a json file (default /etc/sonic/config_db.json).
`config load` will import data from a json file into DB.
=> Add support for config save and config load

config/main.py
`config load_mgmt_config [FILENAME]` to reconfigure mgmt interface based on device description file.
`config load_minigraph` to reload config from `/etc/sonic/minigraph.xml`
=> Add support to reload mgmt conf file and minigraph

scripts/coredump-compress
Remove the assumption to decouple this script from future core dump parameter changes.
The script as-is can also support 0 parameter.
=> [core dump] remove number of parameter assumption from script coredump-compress

config/main.py, scripts/teamshow, sfputil/main.py, show/main.py
Fix issues that `config load_minigraph`, `config load_mgmt_desc`, `teamshow`, `sfputil show`, and `show platform su` not working correctly after https://github.com/Azure/sonic-buildimage/pull/942
=> Adapt to new minigraph_parser schema

scripts/generate_dump
It should merged only after following request:
https://github.com/Azure/sonic-sairedis/pull/199
=> Added syncd SAI dump to sysdump script

scripts/generate_dump
This sparse file is HUGE and without ignoring this file, it will take
forever to gzip this file and ultimately causing the script to hang.
=> [generate_dump]: Skip the sparse file /var/log/lastlog

show/main.py
- Add 'ipv6' group along with 'bgp' and 'route' subcommands
- Remove duplicate commands:
- Remove 'arp' from under 'ip' group, now only under root group
- Remove 'bgp' and 'route' commands from under root group (now different commands reside under 'ip' & 'ipv6')
- Remove 'interfaces' from under 'ip' group, now only under root group
=> [show]: Add 'ipv6' group along with 'bgp' and 'route' subcommands; Remove duplicate commands

show/main.py
Sample output:
```
admin@sonic:~$ show interfaces alias
Name         Alias
-----------  --------------
Ethernet0    fortyGigE0/0
Ethernet4    fortyGigE0/4
Ethernet8    fortyGigE0/8
Ethernet12   fortyGigE0/12
Ethernet16   fortyGigE0/16
Ethernet20   fortyGigE0/20
Ethernet24   fortyGigE0/24
Ethernet28   fortyGigE0/28
Ethernet32   fortyGigE0/32
Ethernet36   fortyGigE0/36
Ethernet40   fortyGigE0/40
Ethernet44   fortyGigE0/44
Ethernet48   fortyGigE0/48
Ethernet52   fortyGigE0/52
Ethernet56   fortyGigE0/56
Ethernet60   fortyGigE0/60
Ethernet64   fortyGigE0/64
Ethernet68   fortyGigE0/68
Ethernet72   fortyGigE0/72
Ethernet76   fortyGigE0/76
Ethernet80   fortyGigE0/80
Ethernet84   fortyGigE0/84
Ethernet88   fortyGigE0/88
Ethernet92   fortyGigE0/92
Ethernet96   fortyGigE0/96
Ethernet100 …
```
=> [show]: Add 'show interfaces alias' command to display port name/alias mapping

scripts/fdbshow, setup.py, show/main.py
Support to show Layer 2 MAC entries learnt in Hardware.  The entries can also be shown per Port/Vlan 
usage: fdbshow [-p PORT] [-v VLAN]
-p,  --port              FDB learned on specific port: Ethernet0
-v,  --vlan              FDB learned on specific Vlan: 1000
Example of the output:
admin@str~$ fdbshow
No.    Vlan  MacAddress         Port
-----  ------  -----------------  ----------
1    1000  7C:FE:90:80:9F:05  Ethernet20
2    1000  7C:FE:90:80:9F:10  Ethernet40
3    1000  7C:FE:90:80:9F:01  Ethernet4
4    1000  7C:FE:90:80:9F:02  Ethernet8
Total number of entries 4
=> CLI support for Layer 2 MAC/FDB show 

config/main.py
and add a `config reload` command to flush db and reload from json.
=> Flush DB first when loading from minigraph

setup.py
- Dependencies listed in `install_requires` are installed in reverse order, so `click-default-group` must precede `click`
=> Reorder dependencies to fix wheel build

scripts/lldpshow
**Summary**:
Fixed parser logic to handle non mandatory TLV.
From WIKI:
Each LLDP frame starts with the following mandatory TLVs: Chassis ID, Port ID, and Time-to-Live.
The mandatory TLVs are followed by any number of optional TLVs. The frame ends with a special TLV,
named end of LLDPDU in which both the type and length fields are 0.
**Log**:
admin@sonic:~$ show lldp table
'NoneType' object has no attribute 'text'
=> Fixed parser logic to handle non mandatory TLV.

config/main.py
Add default route through mgmt when load device description files.
=> [config load_mgmt_config] add default route

setup.py
- The swsssdk package is installed as a wheel. If we compile sonic-utilities as a wheel, it will locate the swsssdk package dependency. However, if we compile sonic-utilities as a Debian package, it will look for a swsssdk Debian package, fail to find it, and the installation will fail.
- For now, we remove this explicit dependency in order to revert back to building sonic-utilities as a Debian package until we find a better solution, as we should specify all dependencies to ensure proper builds in case something goes wrong with the swsssdk installation.
=> Remove explicit dependency on swsssdk

show/main.py
This should not be necessary, because if port_config.ini does not contain aliases, sonic-cfggen should create the 'alias' element with a value of the port name, but it doesn't hurt to add this check in case there is an inconsistency between minigraph and port_config.ini.
=> [show]: If interface has no alias, 'show interfaces alias' outputs interface name as alias

scripts/fast-reboot
Updated fast-reboot script to boot image which would boot after regular reboot
When deciding which kernel to kexec script now checks what is actually scheduled to boot in GRUB
Install new image using SONiC-to-SONiC method (not from ONIE) and execute fast-reboot.
Make sure newly installed version booted
**- Description for the changelog**
=> Update fast-reboot script to boot next selected image

scripts/portstat
- Move back to one column of port state to be compatible with old parsers
- The current state field has four choices: UP, DOWN, DIS, and N/A.
The current state field has four choices: U, D, X, N/A
U means the port is admin + oper status UP
D means the port is admin UP but oper DOWN
X means the port is admin DOWN
N/A for the rest abnormal scenarios
- Refactor the code
=> [portstat]: Combine ADMIN and OPER fields

acl_loader/main.py, config/main.py, data/etc/bash_completion.d/acl-loader, setup.py, show/main.py
- Add acl-loader implementation based on translate-acl utility.
- Add shortcuts to show command.
- Add shortcuts to config command.
=> [acl-loader] Add acl-loader utility.

scripts/decode-syseeprom
- `opts.target` did not exist, so a cache file was never specified. Now specifying cache file name explicitly.
- Also changed cache file path from `/var/cache/ssw/` to `/var/cache/sonic/`
- Resolves https://github.com/Azure/sonic-utilities/issues/137
=> [decode-syseeprom]: Fix caching

sonic_installer/main.py
if /host/old_config exists, the copy command will copy sonic directory
into /host/old_config
=> [installer]: remove old_config before backup

pfcwd/main.py
Add 'start/stop' commands
Create 'show' group
Move 'stats' to 'show' and add 'show config'
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [pfcwd]: Configuration commands

acl_loader/main.py
This change is to use natural sort for ports of the ACL_TABLE.
=> Use natural sort for 'show acl table' ports

show/main.py
In the case /var/log/syslog was recently rotated, `show logging` could potentially display no or very few log messages. WIth this PR, if /var/log/syslog.1 exists, we will display the contents of /var/log/syslog.1 followed by the contents of /var/log/syslog, thus ensuring `show logging` always displays a reasonable amount of recent log messages.
=> [show]: If rotated syslog.1 file exists, concatenate output of syslog.1 and syslog

config/main.py, show/main.py
https://github.com/Azure/sonic-py-swsssdk/pull/22 and https://github.com/Azure/sonic-py-swsssdk/pull/23 need to be get merged before this PR.
```
$ config vlan add 1000
$ config vlan member add 1000 Ethernet1
$ config vlan member add 1000 Ethernet9_1 -u
$ config vlan add 2000
$ config vlan member add 2000 Ethernet1
$ config vlan member add 2000 Ethernet9_2 -u
$ show vlan config
Name        VID  Member       Mode
--------  -----  -----------  --------
Vlan1000   1000  Ethernet1    tagged
Ethernet9_1  untagged
Vlan2000   2000  Ethernet1    tagged
Ethernet9_2  untagged
$ config vlan member del 1000 Ethernet1
$ config vlan member del 2000 Ethernet1
$ show vlan config
Name        VID  Member       Mode
--------  -----  -----------  --------
Vlan1000   1000  Ethernet9_1  untagged
Vlan2000 …
```
=> [config/show] add support for vlan configuration

setup.py, sonic_psu/psu_base.py
So we can install the wheel in a python3 environment
```
root@8b17db2d733c:/# python3.6
Python 3.6.0 (default, Dec 29 2016, 04:29:02)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sonic_psu.psu_base import PsuBase
>>>
```
=> Build a python3 wheel with sonic_psu

psuutil/main.py
Fixed runtime issue with displaying PSU status
Removed unused argument which was missed for removing as part of PSU review fixes 
Just run PSU utility
-->
=> [PSU] Fixes runtime issue with status displaying

scripts/intfutil
=> [intfutil]: Fix python indentation

acl_loader/main.py, config/main.py, pfcwd/main.py
Adapt to API refactor in 
https://github.com/Azure/sonic-py-swsssdk/pull/23 and https://github.com/Azure/sonic-py-swsssdk/pull/25
=> Adapt to py-swsssdk refactor of mod_entry and mod_config

config/main.py, scripts/ecnconfig, setup.py, show/main.py
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Should be merged AFTER https://github.com/Azure/sonic-buildimage/pull/1178
=> Add utility to configure ECN WRED parameters

psuutil/main.py
it seems that the number of characters to be displayed is limited.
previous output:
```
Usage: psuutil [OPTIONS] COMMAND [ARGS]...                 
psuutil - Command line utility for providing PSU status  
Options:                                                   
--help  Show this message and exit.                      
Commands:                                                  
numpsus  Display the number of supported PSU in the...   
status   Display PSU status                              
version  Display version info                            
```
current output:
```
Usage: psuutil [OPTIONS] COMMAND [ARGS]...                
psuutil - Command line utility for providing PSU status 
Options: …
```
=> [psuutil]: Shorten the help message to display it fully

pfcwd/main.py
Group columns in OK/DROP pairs
Add option to show empty lines now hidden by default
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [pfcwd]: Refine 'show stats' output

acl_loader/main.py
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [acl_loader]: Add status column to session table

scripts/aclshow
Fix the "aclshow -d" not showing ACL table if no rules were added
Check corner cases.
Verify the scenario is fixed.
empty.
```
ACL Table: dataacl
==================
Property      Value
------------  ----------------------------------------------------
type........  L3
policy_desc.  dataacl
ports.......  Ethernet8,Ethernet9,Ethernet16,Ethernet17,Ethernet18 
-->
```
=> fix aclshow -d not showing ACL table issue

scripts/fast-reboot-dump.py
Added a new functionality into fast-reboot-dumper.py. This script is called right before fast-reboot procedure to save dumps of fdb and arp entries. I've added a new functionality - send directed GARP requests for every NEIGHBOR entry in SONiC. It allows SONiC to be sure that host machines on vlan interfaces will keep their arp entries to SONiC device as long as possible. Previously host machines could expire arp entries to SONiC device when SONiC device in Fast-Reboot procedure.
I extract all required information from arp and fdb entries and then generate ARP entries using Linux raw sockets
Use tcpdump `sudo tcpdump -iEthernet10 -nevv` for example …
=> [Fast-Reboot]: Add directed GARP

show/bgp_quagga_v4.py, show/bgp_quagga_v6.py
- Add support for 'routes', 'advertised-routes', 'received-routes' options in both `show ip bgp neighbors` and `show ipv6 bgp neighbors`. Require the options as well as the neighbor IP address in the latter (ipv6), as the corresponding quagga vtysh command also requires them.
=> [show] Enhance/fix 'show ip/ipv6 bgp neighbors ...' commands

show/main.py
- Remove `show interfaces transceiver basic` and `show interfaces transceiver details` and combine the functionality into `show interfaces transceiver eeprom [-d/--dom]`
- Add `show interfaces transceiver lpmode` and `show interfaces transceiver presence` commands to give `show` command access to new sfputil functionality
```
admin@sonic:~$ show interfaces transceiver basic Ethernet0
Command: sudo sfputil show eeprom -p Ethernet0
Ethernet0: SFP EEPROM detected
Connector: No separable connector
Encoding: Unspecified
Extended Identifier: Unknown
Extended RateSelect Compliance: QSFP+ Rate Select Version 1
Identifier: QSFP+
Length Cable Assembly(m): 1
Specification compliance:
10/40G Ethernet …
```
=> [show] Add and rename 'show interfaces transceiver' subcommands (eeprom, lpmode, presence)

pfcwd/main.py
Set correct value range for restoration/detection time parameters
Switch the value.
Tested on DUT
-->
=> [pfcwd]: Set correct value range for restoration/detection time parameters

sonic_installer/main.py
sync file system after all copies and installations are done.
With platform specific reboot tool power cycling devices, it is highly repeatable that some file would be missing after sonic_install.
The fix is verified under the same circumstances.
The issue turns out not related to this sync. But putting the sync at the end of the execution list by itself is a good practice anyways.
=> [sonic_install] sync filesystem after file copy is done

scripts/fast-reboot, scripts/reboot, setup.py
Reboot device with platform specific tool when available.
- Added a script under /usr/bin/reboot, this script will be executed when reboot is invoked without absolute path.
- The script checks if <device path>/platform_reboot tool is available and executable. If so, use this tool to reboot device.
- Update fast-reboot to call native Linux reboot with absolute path.
- Executed the script on device with platform_reboot available, and the tool was called.
- Executed the script on device without platform_reboot tool or not with execution permission, Linux native reboot was called.
=> [reboot] While rebooting device, execute platform specific reboot tool when available

clear/main.py, scripts/fdbclear, setup.py
add a clear fdb command under "sonic-clear" group,
it's looks like "sonic-clear fdb all"
add "sonic-clear fdb all" to "sonic-clear" froup;
add a new script 'fdbclear' to implement the function, in this script it will publish notification via some channel of ASIC_DB to syncd.
tested this command on MLNX platform
```
SONiC command line - 'Clear' command
Options:
Commands:
arp       Clear IP ARP table
counters  Clear counters
ip        Clear IP
ipv6      Clear IPv6 information
```
```
SONiC command line - 'Clear' command
Options: …
```
=> [sonic-clear] add a clear fdb command

config/main.py
- Previously, if multiple BGP sessions existed for a neighbor (e.g., an IPv4 session and an IPv6 session), calling `config bgp shutdown neighbor <hostname>` would only shut down the first session it located in ConfigDB. This PR will now cause the command to shut down all BGP sessions associated with that neighbor. (The same is true of `config bgp startup neighbor <hostname>`)
- Also fix a bug where passing `config bgp [shutdown|startup] neighbor <ip_address>` would fail to locate a neighbor with that IP address if the IP address passed was an IPv6 address containing lowercase alphabet characters. IPv6 addresses are stored in ConfigDB with all uppercase alphabet characters and the lookup is case-sensitive. Now converting all IP addresses to uppercase before performing …
=> 'config bgp [shutdown|startup] neighbor <hostname>' now affects all sessions for neighbor

scripts/fdbshow
Get Vlan Id from SAI_OBJECT_TYPE_VLAN if _bvid_ is present in fdb entry. 
Execute fdbshow and it must display the entires
**- Command output**
```
$ fdbshow 
No.    Vlan  MacAddress         Port
-----  ------  -----------------  ----------
1    1000  24:8A:07:4C:F5:03  Ethernet12
2    1000  24:8A:07:4C:F5:18  Ethernet96
3    1000  24:8A:07:4C:F5:16  Ethernet88
4    1000  24:8A:07:4C:F5:09  Ethernet36
5    1000  24:8A:07:4C:F5:15  Ethernet84
```
-->
=> Get Vlan Id from SAI Vlan Object if bvid present

acl_loader/main.py
- If `acl-loader` was run by a non-root user, it would just hang indefinitely in the call to `SonicV2Connector()`.
- NOTE: We may want to exit if run by a non-root user and add "acl-loader show *` to /etc/sudoers as we have done for other CLI utils which have both show and config functionality.
=> [acl-loader] Prevent from hanging if run by non-root user

pfcwd/main.py
Add command to set pfcwd polling interval
Add set poll interval command
Test on DUT
```
root@sonic:/home/admin# pfcwd show config                              
PORT    ACTION    DETECTION TIME    RESTORATION TIME
-----------  --------  ----------------  ------------------
Ethernet112      drop               300                3000
```
```
root@sonic:/home/admin# pfcwd show config        
Changed polling interval to 100ms                           
PORT    ACTION    DETECTION TIME    RESTORATION TIME 
-----------  -------- …
```
=> [pfcwd]: add command to set pfcwd polling interval

scripts/fast-reboot, scripts/fast-reboot-dump.py
Dump default routes (both IPv4 and IPv6) from APPL db right before fast reboot restart.
Change fast-reboot-dump.py script
Run sudo /usr/bin/fast-reboot-dump.py and you'll find /tmp/default-routes.json file with valid output.
-->
=> [fast-reboot]: Dump default routes from APPL_DB table before fast-reboot

config/main.py
`config qos clear` can now clear all buffer and qos setting.
`config qos reload` will clear those settings and reload platform default value.
`config load_minigraph` will now apply `config qos reload` after loading topology from minigraph
Needs https://github.com/Azure/sonic-py-swsssdk/commit/f0980a09fe77924946df0bde58bdaed4a472c386.
=> [config] Add qos clear and qos reload support

scripts/reboot
sonic-cfggen has changed its information format. Particularly, platform is no longer under hwsku, instead, it is under localhost now.
Tested reboot on dut. without the change, there is an error; with the change, there is no error.
=> [reboot] update reboot script to retrieve platform with new format

crm/main.py, data/etc/bash_completion.d/crm, setup.py
Initial CRM  UI utility implementation for review. Please do not merge yet.
=> [crm]: Add utility for CRM configuration

scripts/fast-reboot
Get correct name for the Broadcom opennsl service before stopping it
Check list of systemctl services
Check the console when you doing fast-reboot procedure for output from systemctl
-->
=> [Fast-reboot]: Find correct opennsl module name before stopping the module

scripts/fast-reboot, scripts/fast-reboot-dump.py
1. Refactor fast-reboot script
2. Store the dumps in /host directory to better work with NOS-SONiC updates
Modify fast-reboot and fast-reboot.py to better serve our needs
1. Run mkdir your_dir; sudo /usr/bin/fast-reboot-dump.py your_dir to find the dumps in your_dir
2. Run sudo fast-reboot to find the fast-reboot working
-->
=> [Fast-reboot]: Refactor fast-reboot script. Store the dumps in /host

sfputil/main.py
@fillmorechen0928 @philipwangCP @pollyhsu2git 
sfputil/main.py was missed in PR #205. This is causing https://github.com/Azure/sonic-utilities/issues/215
(https://github.com/Azure/sonic-buildimage/issues/1433). This PR fixes the issue.
=> [sfputil] Adapt new way of getting PLATFORM 

config/aaa.py
Add support to login=login (ascii) authentication type to tacacs+
=> [AAA] Support login(ascii) authentication type

show/main.py
* Format the output of show vlan config
Signed-off-by: chenhu <chenhu@didichuxing.com>
Format the output of show clan config when multiple interfaces in vlan
iterate the vlan config to generate the table  first, then print it
before the modification
```
show vlan config
Name       VID  Member                                                                                                                          Mode
-------  -----  ------------------------------------------------------------------------------------------------------------------------------  ------------------------------------------------------------------------------------
Vlan2        2  Ethernet4
Ethernet88
Ethernet92
Ethernet96
Ethernet100
Ethernet104
Ethernet108
Ethernet112
Ethernet116
Ethernet120
Ethernet124 …
```
=> sonic-utilities: Format show vlan config output

scripts/fast-reboot
Added support of fast-reboot for Arista platform by adding support of Aboot in fast-reboot.
Also changed sonic_installer to use `install=y` instead of `sonic_upgrade=1`.
The boot0 will stay backward compatible with previous `sonic_installer` versions.
Running `sonic_installer install` and then `fast-reboot` should show kexec working.
It is assumed that all ONIE based platform define onie_platform= in /host/machine.conf.
=> Add fast-reboot support for Aboot based images

config/main.py, pfcwd/main.py
Set default configuration when enabled by default
Implement the pfcwd start_default function to set default configuration.
Test on DUT
-->
=> [PFCWD]: set default configuration when enabled by default

config/main.py
1. Do case conversion only for user input but not for keys queried from configDB. 
1. Use lower case instead of upper case.
We will make a change in minigraph parser as well to make sure all bgp session ipv6 addresses are written into configDB in lower case.
=> [config bgp] Convert user input ipv6 addr to lower case before comparing

scripts/fast-reboot
add fast-reboot support for nephos platform 
Stop kernel modules for Nephos platform
Passed test.
-->
=> add fast-reboot support for nephos platform by stop kernel modules

scripts/fast-reboot
Add a feature to gracefully shutdown syncd
Using syncd_request_shutdown utility
Run fast-reboot test
-->
=> [Fast-reboot]: Gracefully shutdown syncd in fast-reboot

crm/main.py
Fixed issue "CRM module throws error" (https://github.com/Azure/SONiC/issues/159)
Changed output to empty line instead of throwing error when retrieved nothing from config DB
Execute CRM show commands and observe that error is not shown
=> [crm]: Fix failures in CLI show commands

scripts/reboot
When the service dockers are in some rare failure situations, stopping
service might get stuck. To make sure reboot always move ahead, we
could request syncd to stop, wait some time, then proceed with reboot.
I executed a few hundreds of reboots with the new script on my dut.
=> [reboot] reduce stop service to only stop syncd

scripts/fast-reboot, scripts/reboot
When the command is called by ssh execution, there is no shell. With
-t option these docker commands will fail.
ssh execution: e.g. ssh admin@dut "sudo /usr/bin/fast-reboot"
ssh admin@dut "sudo /usr/bin/fast-reboot"
ssh admin@dut "sudo /sur/bin/reboot"
=> [reboot scripts] remove -t option in docker exec commands

show/main.py
Display output of `sonic-cfggen -d --print-data`
=> [show] add 'show runningconfiguration all' subcommand

scripts/fdbshow
Display fdbtype (Static/Dynamic) in show command
Modified `fdbshow` script
Run `show mac` or `fdbshow `in the DUT
```
No.    Vlan  MacAddress         Port
-----  ------  -----------------  ----------
1    1000  24:8A:07:4C:F5:0D  Ethernet52
2    1000  24:8A:07:4C:F5:12  Ethernet72
3    1000  24:8A:07:4C:F5:16  Ethernet88
```
```
No.    Vlan  MacAddress         Port        Type
-----  ------  -----------------  ----------  -------
1    1000  24:8A:07:4C:F5:0D  Ethernet52  Dynamic
2    1000  24:8A:07:4C:F5:12  Ethernet72  Dynamic
3    1000  24:8A:07:4C:F5:16  Ethernet88 …
```
=> Show FDB type in fdbshow/show mac

scripts/queuestat
CLI to show queue counters from counter DB. The tool can show incremental change on top of the previous snapshot too.
huima@huima-vm2:/datadrive/sonic-utilities/scripts$ ./queuestat -h
usage: queuestat [-h] [-v] [-p PORT] [-c] [-d]
Display the queue state and counters
-h, --help            show this help message and exit
-v, --version         show program's version number and exit
-p PORT, --port PORT  Show the queue conters for just one port
-c, --clear           Clear previous stats and save new ones
-d, --delete          Delete saved stats
Examples:
queuestat
queuestat -p Ethernet0
queuestat -c
queuestat -d
=> [queuestat] add python CLI tool to show queue counters

scripts/pfcstat
This is t create new python tool to show pfc counters.
The following are usage page and sample output:
huima@huima-vm2:/datadrive/sonic-utilities/scripts$ ./pfcstat -h
usage: pfcstat [-h] [-v] [-c] [-d]
Display the pfc counters
-h, --help     show this help message and exit
-v, --version  show program's version number and exit
-c, --clear    Clear previous stats and save new ones
-d, --delete   Delete saved stats
Examples:
pfcstat
pfcstat -c
pfcstat -d
=> [pfcstat]: create python cli tool to show pfc counters

show/main.py
- Also correct and tweak a few comments
=> [show] Rename 'show session' command to 'show mirror session' for clarity

acl_loader/main.py
Sample new output of `acl-loader show table`
```
admin@sonic:~$ acl-loader show table
Name            Type       Binding      Description
--------------  ---------  -----------  --------------
EVERFLOW        MIRROR     Ethernet0    EVERFLOW
Ethernet4
Ethernet8
Ethernet12
Ethernet16
ROUTER_PROTECT  CTRLPLANE  SNMP         ROUTER_PROTECT
SSH
DATAACL         L3         Ethernet0    DATAACL
Ethernet4
Ethernet8
Ethernet12
Ethernet16
```
=> [acl_loader] Support Service ACL binding to multiple services

clear/main.py, setup.py, show/main.py
Add both pfcstat and queuestat to package build and show/clear command
=> [pfcstat] add the new tools to show and clear command

show/main.py
- Previously, command output wasn't being displayed until the command finished running. This would cause programs like 'tail' (e.g., `sudo tail -F /var/log/syslog`) to not display any output.
- For all `docker exec ...` calls, I removed the `i` and `t` flags, as the `t` flag would create an unnecessary terminal with a narrow width which would truncate log lines. The `i` flag is not necessary as we are simply running non-interactive commands.
- I also have an updated sudoers file which I will add in sonic-buildimage when updating this submodule.
=> [show] Now displaying output while command is running (e.g., 'tail'); Remove 'it' flags from 'docker exec' calls

config/main.py, config/mlnx.py
modified:   config/main.py
new file:   config/mlnx.py
Signed-off-by:  Kebo Liu kebol@mellanox.com
Add new command line for Mellanox SDK sniffers
Add new cli group "platform" under "config" command.
"mlnx" subgroup of "platform" group is for Mellanox platform specific CLI
Add command "config platform mlnx sniffer sdk enable" to enable sdk sniffer
Add command "config platform mlnx sniffer sdk disable" to disable sdk sniffer 
On Mellanox platform can issue these command to enable and disable sdk sniffer.
please refer to design doc [https://github.com/Azure/SONiC/wiki/Mellanox-SDK-and-PRM-Sniffer-Utility-CLI-Design-for-SONiC](url)
**- New command …
=> [config] Add new command line to support mellanox sniffer

acl_loader/main.py
- Incremental update was not working as intended. `cmp(self.rules_info[key], self.rules_db_info[key])` would consistently fail because some string elements in `rules_info` were encoded in Unicode when loading the ACLs from a file, whereas all elements in `rules_db_info`, pulled from ConfigDB, were encoded in ASCII.
- Now, string elements in `rules_db_info` are converted to ASCII, which causes the compare operation to work properly.
- Also modified incremental update to only perform an incremental update on control plane ACLs. A full update is still performed on dataplane ACLs temporarily, until we fully test that we can insert ACLs (and shift existing ACLs) in the ASICs.
=> [acl-loader] Fix and refactor incremental update

config/main.py
During `load_minigraph`, stop sonic services before pushing new config. Previously (without stopping services), _orchagent_ crash was consistently observed while loading minigraph resulting in generating false-alarms. By stopping the services, the crash was _not_ observed
`
Apr 25 18:23:08.736428 str-a7060cx-acs-10 INFO supervisord 2018-04-25 18:23:03,100 INFO exited: orchagent (terminated by SIGABRT (core dumped); not expected`
Modified config python script
Execute `sudo config load_minigraph -y` and check syslogs for `not expected` process exit
```
admin$ sudo config load_minigraph -y
Running command: sonic-cfggen -H -m -j …
```
=> Stop services before pushing new config during "load_minigraph"

scripts/generate_dump
fix a bug that not able to copy saidump file from the syncd container
the saidump file is generated to the /tmp folder of syncd container,
"docker cp" command is not applicable to tmpfs, need to use other
way to copy this file from the tmpfs of syncd to the host.
please refer to "docker cp" command description:
[https://docs.docker.com/engine/reference/commandline/cp/](url)
use "show techsupport" to check, the saidump file can be found under /tmp folder of the switch.
=>  [generate_dump]: fix a saidump file copy bug

counterpoll/main.py, data/etc/bash_completion.d/counterpoll, setup.py
Provides CLI command to change counter polling interval. In future, add command to enable/disable specific counter query
Add counterpoll queue interval <value> and counterpoll port interval <value> to make the change
Add counterpoll show to display current counterpoll configuration.
Tested on DUT
```
admin@SONiC# counterpoll show  
Type          Interval                               
----------  ----------                               
QUEUE_STAT       10000                               
PORT_STAT        10000 …
```
=> [counterpoll]: init cli support to change counter polling configuration

scripts/reboot
This commit fixes the Front Panel Ports not coming up during
cold reboot and traffic being sent at line rate. The root cause
was the PCIe bus error which was caused because of the host
side not doing a gracefull shutdown calling bcm_shutdown and
soc_shutdown. The fix will call the gracefull shutdown of syncd
during reboot which in turns calls the bcm_shutdown and soc_shutdown.
Additionally added the check to make sure the script will run only when
it has root privileges otherwise it will quit.
Verified the fix by running traffic at line rate 40G from Ixia and
rebooted using script multiple times and traffic was successfully
forwarded after every reboot.
Signed-off-by: Harish Venkatraman <Harish_Venkatraman@dell.com>
**- Previous …
=> [sonic-utilities/scripts] Fixing FP ports issue

config/main.py
I made qos configuration a jinja2 template.  It allows us to create flexible qos configurations using jinja2 templates.
Add code dealing with it
Build an image and test on DUT.
-->
=> Render qos.json.j2 from a template

scripts/reboot, show/main.py
Example output:
```
admin@sonic:~$ show reboot-cause 
User issued reboot command [User: admin, Time: Sat Jun 23 01:30:43 UTC 2018]
```
```
admin@sonic:~$ show reboot-cause 
Unexpected reboot
```
=>  Add support for reboot cause and 'show reboot-cause' command for display

scripts/decode-syseeprom
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Updated decode-syseeprom utility to directly use sonic_platform module for getting platform name instead of running sonic-cfggen
imported needed functions from sonic_platform 
run decode-syseeprom -m to see it still able to fetch MAC
It also works faster
0.1s versus 0.3s
=> [decode-syseeprom] Optimize platform info fetch

sonic_installer/main.py
sonic_installer list return wrong next image index, if no next_boot set and default entry is 1.
To make sure `sudo sonic_installer list` shows the right list.
Just correct the right re search text.
Check all three grubenv conditions.
* Default
```
a@sonic:~$  cat /host/grub/grubenv 
saved_entry=0
########################################################################################################################################################################################################################################################################################################################################################################################################################################################### …
```
=> sonic_installer onie get_next_image() may return wrong index due to wrong re search text

config/main.py
Fix/enhance the messages when user do
"config load a.json" or "config reload b.json"
Print the specific file to be loaded rather than "all config" of previous code.
See command below.
$ sudo config load vlan.json 
Reload all config? [y/N]:y
Running command: sonic-cfggen -j vlan.json --write-to-db
$ sudo config load vlan.json -y
Running command: sonic-cfggen -j vlan.json --write-to-db
$ sudo config reload 
Clear current and reload all config? [y/N]: y
Running command: sonic-cfggen -j /etc/sonic/config_db.json --write-to-db
Running command: service hostname-config restart
Running command: service interfaces-config restart
Running command: service …
=> Fix/enhance the messages when user do "config load" or "config reload" with file

scripts/aclshow
Add ACL table name associated with the rules and sort the output
Add ACL table name associated with the rules
Sort the output with table name and rule name.
Add the code for above
See test below.
```
aclshow -d
ACL Table: dataacl
Property          Value
type............  L3
policy_desc.....  dataacl
ports...........  ['Ethernet8', 'Ethernet9', 'Ethernet16', 'Ethernet17', 'Ethernet18'] 
ACL Table: data-aclv6
Property          Value
type............  L3V6
policy_desc.....  data-aclv6
ports...........  ['Ethernet8', 'Ethernet9', 'Ethernet16', 'Ethernet17', 'Ethernet18'] 
ACL Rule: Rule_2
Property          Value
PACKET_ACTION...  FORWARD …
```
=> Add ACL table name associated with the rules and sort the output

show/main.py
1.) Added "show ndp" to show ipv6 neighbours.
This calls "/bin/ip -6 neigh show"
Signed-off-by: pchaudhary@linkedin.com
With this commit, New Sonic CLI Command "show ndp" is added to show IPV6 Neighbours. These IPv6 neighbour are learned via Neighbour Discovery Protocol(NDP).
Since Sonic CLI does not have a strict command parser as of now, this command will dump first argument to kernel except:
a.) if help argument is used i.e. "-?, -h, --help"
b.) or if more than one args are used i.e show ndp fe80::2e0:ecff:fe3c:a0a fe80::1
Added new python cli.command which calls "/bin/ip -6 neigh show"
[Tests Done:]
admin@lnos-x1-a-csw05:~$ show ndp
Command: /bin/ip -6 neigh show
fe80::2e0:ecff:fe3c:a0a dev eth0 lladdr 00:e0:ec:3c:0a:0a STALE …
=> [show/main.py]: New Sonic CLI Command "show ndp" to show IPV6 Neighbours

scripts/generate_dump
Added additional debugging information to the generate_dump script including
- USB and PCI devices
- Transceiver status and eeprom data
- Interface status and counters
- ASIC specific data
- Arista specific info
Added additional commands to the generate_dump script. 
The ASIC version is determined using sonic_cfggen to parse the sonic_version YAML file. 
The Arista platform check is done by grepping /host/machine.conf as the Arista bootloader (Aboot) populates this file.
admin@gd381:~$ show techsupport
...
/var/dump/sonic_dump_gd381_20180625_174535.tar.gz
admin@gd381:~$ tar -xzf /var/dump/sonic_dump_gd381_20180625_174720.tar.gz -C ~/
admin@gd381:~$ ls -l ~/sonic_dump_gd381_20180625_174720/dump
total 2620
-rw-r--r-- 1 admin admin …
=> [generate_dump]: Enhance the generate_dump debugging script

scripts/teamshow
- Handle the case when there is no port channel in the device
**- How I did it** 
- Check when the team_keys == None, return the function instead of continue to assign a none object to the team
- Run teamshow when there is no port channel in the device
'NoneType' object is not iterable
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available, S - selected, D - deselected
No.    Team Dev    Protocol    Ports
-----  ----------  ----------  -------
=> Add empty case

counterpoll/main.py
Output default value when not configured
Tested on DUT
fail to show when not configured before.
admin@sonic:/home/admin# counterpoll show
Type        Interval (in ms)    Status
----------  ------------------  --------
QUEUE_STAT  default (10000)     enable
PORT_STAT   1000                enable
-->
=> [counterpoll]: output default value when not configured

config/main.py
Modified the confirmation prompt to be before stop services
Changed the order
Do `sudo config reload`
```
#sudo config reload 
Running command: service dhcp_relay stop
Running command: service swss stop
Running command: service snmp stop
Running command: service lldp stop
Running command: service pmon stop
Running command: service bgp stop
Running command: service teamd stop
Clear current config and reload config from the file /etc/sonic/config_db.json? [y/N]
```
```
#sudo config reload 
Clear current config and reload config from the file /etc/sonic/config_db.json? …
```
=> Fixed the confirm prompt to be before stop service

connect/main.py, show/main.py
Now that we have upgraded our version of Click to 6.7-4 in https://github.com/Azure/sonic-buildimage/commit/f04f0704f70fcd0f114563d3d567b9f2cc9b1ee5, we no longer need to work around the Click "broken pipe" issue, as it was fixed here: https://github.com/pallets/click/commit/e850c58571272e24d7169172c0f8086c2f88b5ef
=> Remove 'broken pipe' workaround for Click

scripts/nbrshow, setup.py, show/main.py
1. Enhanced the output of  `show arp/ndp` to have Vlan member info.
2. Added the option to fetch neighbor entries for a specified interface. 
Fetch `arp/ipv6` neigh info from kernel and `fdb` info from ASIC db. Compare the `Interface `and `Mac address` from the neighbor info and get the matching entry from FDB table to append the physical interface. 
Execute `show arp` and `show ndp` commands
```
show arp
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.0.2              ether   24:8a:07:4c:f5:0a   CM                    Vlan1000
10.64.247.30             ether   00:50:b6:20:e2:41   C                     eth0 …
```
=> Enhanced "show arp/ndp" output

scripts/ecnconfig
Tested on DUT with https://github.com/Azure/sonic-swss/pull/571
-->
=> Add drop probability configurability to ecnconfig

scripts/ecnconfig
=> ecnconfig: Add drop probability configurability & show and change ECN on/off status on queues

scripts/fast-reboot
Fast-booting to a new image with new SDK/FW may increase
control plane downtime by 1.5 min, because of new FW installation.
Upgrading FW before fast reboot does not increase downtime of
control/data plane traffic
NOTE: This PR depends on https://github.com/Azure/sonic-buildimage/pull/1994, please merge only after that PR is merged
-->
=> [mellanox] Upgrade FW if neccesary before fast reboot

scripts/pcmping, setup.py
Add pcmping tool to get portchannel member packet loss state
1. Vary decap packet src ip to make the packet traverse target link within portchannel
2. Send the packet to see packet loss
Tested on the DUT
```
root@sonic:/home/admin# pcmping -h                                                 
usage: pcmping [-h] [-v] -i INTERFACE -ip DECAPIP [-c COUNT] [-t TRIAL]                         
Check portchannel member link state                                                              …
```
=> [pcmping]: Add pcmping tool to get portchannel member packet loss state

config/main.py
GRE type and queue number are set internally and shall not be set by users.
=> [config]: Move setting GRE/queue for mirror session as optional

pfcwd/main.py
Backport to 201803
Enable PFC WD on all ports and all tiers.
-->
=> [pfcwd]: enable pfcwd on all port by default (#307)

config/main.py, show/main.py
warm_restart config and show commands
```
root@sonic:/# config warm_restart enable
root@sonic:/# config warm_restart disable swss
root@sonic:/# 
root@sonic:/# show warm_restart 
Usage: show warm_restart [OPTIONS] COMMAND [ARGS]...
Show warm restart configuration and state
Options:
Commands:
config  Show warm restart config
state   Show warm restart state
root@sonic:/# show warm_restart  config
name    enable    timer_name    timer_duration
------  --------  ------------ …
```
=> Warm reboot: warm_restart config and show commands

config/main.py
config interface <interface_name> add <ip_addr>
config interface <interface_name> remove <ip_addr>
These two commands are used to configure IP addresses
config interface <interface_name> startup
config interface <interface_name> shutdown
These two commands are moved under interface subgroup, and
the order of the arguments are swapped to match the rest of
the commands
=> [config]: Add IP subgroup commands

pfcwd/main.py
Fix the following error when running 'pfcwd start_default'
File "/usr/bin/pfcwd", line 9, in <module>
load_entry_point('sonic-utilities==1.2', 'console_scripts', 'pfcwd')()
File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
File …
=> Fix pfcwd start_default

acl_loader/main.py
pybindJSON.load() silently ignore invalid acl.json according to YANG model, and return an emtpy object. Detect this situation and report an error.
=> Validate acl.json after parsed

config/main.py
Export environment variable "SONIC_CLI_IFACE_MODE" in user bashrc to store the interface mode. 
Introduced variable in config/main.py script. set_interface_mode() function will set the interface mode preferred by user.
Execute "config interface_naming_mode alias/default" and check the changes in ~/.bashrc. 
Logout and log back in the shell to see changes are taken into effect.
~~~
admin@sonic:~$ sudo config interface_naming_mode alias
Please logout and log back in for changes take effect.
~~~
-->
=>  SONIC_CLI_IFACE_MODE variable in bashrc for portalias feature

sonic_installer/main.py
Add some helpers to edit the boot-config for Aboot based products.
Calling set_default_boot will now set SWI and SWI_DEFAULT to the next
image to boot. Upon boot the SWI value gets overriden by SWI_DEFAULT.
This mimics the behavior that grub has.
A change from sonic-buildimage in boot0 is required to properly test.
However the logic here can be tested by looking at the content of boot-config after running set_next_boot and set_default.
-->
=> [arista] add default boot option for SWI files.

show/main.py
Added portalias support for following commands.  To enable alias output in CLI execute "sudo config interface_naming_mode alias" command and use the below commands.
- show ip route
- show ipv6 route
- show interface transceiver eeprom
- show arp 
- show lldp neighbors
- show vlan brief
- show vlan config
Implemented a seperate run_command_in_alias_mode function  to change the results of linux commands from default interface name to vendor specific name. This function read each line of the output and replace the equivalent vendor names. To speed up the result for mutli-line output ( show ip route/ipv6 route/arp)  we cache the alias_names from port_config.ini at init. This results in quick substitution.
Execute the commands as …
=> Add 'alias mode' support for show commands

scripts/ecnconfig
On dut:
$ ecnconfig -p AZURE_LOSSLESS -rmin 10000    
Root privileges required for this operation
$ sudo ecnconfig -p AZURE_LOSSLESS -rmin 10000
$ ecnconfig -p AZURE_LOSSLESS -rdrop 30     
Root privileges required for this operation
$ sudo ecnconfig -p AZURE_LOSSLESS -rdrop 30
$ ecnconfig -q 3 on 
Root privileges required for this operation
$ sudo ecnconfig -q 3 on
-->
=> Root priviliege for ecn configuration set commands

sonic_installer/main.py
Add sonic_installer upgrade_docker command to support docker upgrade
***sonic_installer upgrade_docker*** 
```
root@sonic:~# sonic_installer  upgrade_docker  --help
Usage: sonic_installer upgrade_docker [OPTIONS] <container_name> URL
Upgrade docker image from local binary or URL
Options:
-y, --yes
--cleanup_image  Clean up old docker image
--enforce_check  Enforce pending task check for docker upgrade
--tag TEXT       Tag for the new docker image
--help           Show this message and exit.
root@sonic:~# 
```
***Before docker upgrade***
```
root@sonic:~# docker images
REPOSITORY                 TAG                                   IMAGE ID            CREATED             SIZE …
```
=> Warm reboot: Add support for docker upgrade

scripts/fast-reboot, scripts/reboot
1. Fixed Mellanox fast reboot script
2. Added argument forwarder for platform reboot
* N/A
To verify fast reboot:
1. Run fast reboot
To verify argument forwarding:
1. Pass custom arguments to platform reboot script
* N/A
* N/A
**- External dependencies**
1. https://github.com/Azure/sonic-buildimage/pull/2111
=> Added argument forwarder for platform reboot.

setup.py
The latest version of Python tabulate library available as a Debian package for Stretch is 0.7.7. However, the new "show vlan" command requires support for multi-line output in a cell, a feature that was added in tabulate v0.8.1.
Tabulate v0.8.2 is the latest version available via pip, so I am now installing this package in the base image here: https://github.com/Azure/sonic-buildimage/pull/2130
I have also added comments describing the change and listing the packages that we cannot currently specify as explicit dependencies because they cannot be installed as .deb packages.
=> Remove explicit dependency on tabulate; Add comments

scripts/ecnconfig
On dut:
$ sudo ecnconfig -p AZURE_LOSSLESS -ymin -1 
Exception caught:  Invalid ymin
$ sudo ecnconfig -p AZURE_LOSSLESS -gdrop 101    
Exception caught:  Invalid gdrop
$ sudo ecnconfig -p AZURE_LOSSLESS -gdrop -1 
Exception caught:  Invalid gdrop
$ sudo ecnconfig -p AZURE_LOSSLESS -gdrop o    
Exception caught:  invalid literal for int() with base 10: 'o'
-->
=> ecnconfig check against invalid argument value

config/main.py, setup.py
- Replace calls to 'click.Abort()' with the Click context method 'fail()' which takes an error message as a parameter in order to ensure descriptive messages are printed rather than simply the message, "Aborted"
- Change entrypoint name from 'cli' to 'config'
- Rename a couple helper functions for clarity
- Replace 'print' calls with 'click.echo()' for consistency
- Enhance comments
=> [config] Use 'click.fail()' in place of 'raise click.Abort' in order to print error messages to user; Other minor tweaks

config/main.py
Fix config CLI command according to latest changes
There was recent changes which changed syntax for ```interface`` config command (PR https://github.com/Azure/sonic-utilities/pull/308).
Asymmetric PFC config command wasn't aligned to the new syntax.
In order to fix the issue just changed the command in order to use new syntax.
Verify that below commands are working without any errors
```
config interface Ethernet0 pfc asymmetric on
config interface Ethernet0 pfc asymmetric off
```
N/A
N/A
=> [pfc_asym]: Fix config CLI command according to latest changes

config/main.py
IP config on Vlan interface.
```
root@sonic:/home/admin# config  interface Vlan10  ip add 20.20.20.20/24 
root@sonic:/home/admin# 
root@sonic:/home/admin# 
root@sonic:/home/admin# ip add show Vlan10
6: Vlan10@Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
link/ether 00:05:64:30:73:c0 brd ff:ff:ff:ff:ff:ff
inet 11.163.117.119/26 scope global Vlan10
valid_lft forever preferred_lft forever
inet 11.213.14.247/26 scope global Vlan10
valid_lft forever preferred_lft forever
inet 20.20.20.20/24 scope global Vlan10
valid_lft forever preferred_lft forever
inet6 fe80::205:64ff:fe30:73c0/64 scope link 
valid_lft forever preferred_lft …
```
=> Add ip config support for Vlan

config/main.py, config/mlnx.py, show/main.py, show/mlnx.py
* Hide Mellanox sniffer CLI on other platforms
* Set enable/disable to be the argument of sniffer command rather
than the sub-command
Signed-off-by: Kevin Wang <kevinw@mellanox.com>
Make the CLI "config/show platform mlnx" just appear on Mellanox platform.
Use sonic_platform.get_sonic_version_info()['asic_type'] to identify the running platform.
Should not see "config/show platform mlnx" CLI on the other platforms.
-->
=> Some improvement for Mellanox sniffer CLI

scripts/fast-reboot
Because echo doesn't support '\n'
=> Fix echo commands

sfputil/main.py
When access an SFP eeprom which not presente will cause error print from the kernel modules:
`ERR kernel: [41770.216758] mlxsw_minimal 2-0048: Eeprom query failed`
to avoid this need to prevent from accessing none presence SFP eeprom
before read the SFP eeprom, add logic to determine the presence of SFP with method get_presence() 
run "show interface transceiver eeprom EthernetX" command to verify
no change for command output
no change for command output
=> [sfputil] add logic to avoid access none present SFP eeprom

show/main.py
* Fixing `show vlan brief` traceback
Signed-off-by: Stegen Smith <stegen@owns.com>
This resolves #357 
Did some key checking to ensure the key exists in the dict, instead of assuming it does.
Run `show vlan brief` with the fix.
```
root@sonic:/home/user# show vlan brief
File "/usr/bin/show", line 9, in <module>
load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
File …
```
=> [show]: Fixing traceback for show vlan brief

show/main.py
Fix `show ntp` takes about 20 seconds.
add `-n` option to `ntpq`
```
axxx@xxx-yyy:~$ date; show ntp; date
Wed Oct 24 08:44:28 CST 2018
Command: ntpq -p
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
11.1.1.99       .INIT.          16 u    -   64    0    0.000    0.000   0.000
Wed Oct 24 08:44:48 CST 2018
axxx@xxx-yyy:~$ date; show ntp; date
Wed Oct 24 09:00:07 CST 2018
Command: ntpq -p -n
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
11.1.1.99       .XFAC.          16 u    -   64    0    0.000    0.000   0.000
Wed Oct 24 …
```
=> [ntp] show ntp may take 20 seconds due to DNS issue.

config/aaa.py
Changes for accepting "vrfname" as an optional parameter for the command "config tacacs -v [vrfname] server_ip" and pass it to TACPLUS_SERVER in the config DB.
Added checks for argument "vrf" and passed it to config DB. Diff is at https://github.com/kannankvs/sonic-utilities/commit/bf51bb12b5c820fc40eff7d9b6d02405af2e68be  
Tested it along with the command "config tacacs -v mgmt 10.11.55.40" and verified that the passed parameter "vrfname" is there in /etc/sonic/config_db.json file under TACPLUS_SERVER. Verified that "show tacacs" displays the newly configured vrfname for the server IP.
```
root@sonic:/etc/sonic# show tacacs
TACPLUS global …
```
=> tacacs management vrf changes

config/main.py
Shall use mod_entry instead of set_entry when updating partial
information in the configuration database. set_entry will delete
the rest of the data associated with this entry.
Test result:
```
admin@str-s6100-acs-2:~$ redis-dump -d 4 | python -mjson.tool | grep -A10 PORT\|Ethernet18
"PORT|Ethernet18": {
"type": "hash",
"value": {
"admin_status": "up",
"alias": "fortyGigE1/2/3",
"index": "18",
"lanes": "29,30",
"mtu": "9100",
"speed": "40000"
}
},
admin@str-s6100-acs-2:~$ sudo config interface Ethernet18 shutdown
admin@str-s6100-acs-2:~$ redis-dump -d 4 | python -mjson.tool | grep -A10 PORT\|Ethernet18
"PORT|Ethernet18": {
"type": "hash",
"value": {
"admin_status": "down",
"alias": "fortyGigE1/2/3",
"index": "18",
"lanes": "29,30", …
```
=> [config]: Fix bug of losing data when setting admin status

scripts/fast-reboot
Fix https://github.com/Azure/sonic-utilities/issues/364 Use pkill instead of killall as suggested.
sed s/killall/pkill/
When sonic is running, issue sudo fast-reboot command and check you don't see any error messages on the screen.
-->
=> [fast-reboot]: Use pkill instead of killall

acl_loader/main.py
This reverts commit 7a51a85615eccab3e4bed943e0e25deb39dec4c7.
@kevinwangsk reported regression:
> Recently we found CLI “acl-loader show table” crashed. The error is “ports = val["ports"].split(",")  AttributeError: 'list' object has no attribute 'split'”.
=> Revert "[acl_loader] fix show acl table  (#329)"

scripts/fast-reboot
Back up log level db contents during warm shutdown. And restore in warm boot up sequence. 
So that after warm reboot, the log level will remain the same as before
warm boot.
Use swssloglevel to set syncd log level to INFO, execute full system warm reboot, verify that after boot up, syncd log level is still at INFO level.
(Require build image PR 2233)
=> [warm boot] save log level DB contents

scripts/fast-reboot
Change how we stop teamd.
In fast-reboot mode the teamd stopping method are the same.
In warm-reboot mode the teamd stopping method uses USR1 signal.
1. Build an image with the changes and issue `sudo warm-reboot` command.
2. teamd must send lacp updates on all lagg member interfaces
3. After restart you should see lacp dump files in /host/warmboot/teamd/
-->
=> Stop teamd gracefully in both modes

scripts/reboot
Both warm/fast reboot are invoking /sbin/reboot directly.
If user invoked 'reboot', one scenario could be that user tried to issue
either fast or warm reboot and failed to complete. User then tries to
recover the system with a cold reboot.
In this scenario, particularly after warm-reboot request failed, we should
remove db backup files, so that the system will come up and perform a cold
recovery.
created a few .json files under /host/warmboot. issue reboot, and after device rebooted, these .json files are gone.
touch /host/warmboot/config_db.json
reboot
After device boot up, check /host/warmboot, config_db.json has been renamed to config_db-\<timestamp\>.json
=> [reboot] clear warm boot files when reboot is requested

acl_loader/main.py
import ipaddr package and check if the ip address is ipv4 or ipv6
and set the corresponding rule properties
=> [acl_loader]: Add support for IPv6 field match

config/main.py, show/main.py
- interface_naming_mode functions fetch the alias_interface_name via sonic-cfggen. But, with the recent change in config_db removes all port related entries when a sepecific interface is down. This affects the existing implementation of fetching port details to following fucntions [ interface_alias_to_name(), interface_name_to_allias(), InterfaceAliasConverter() ] and throws key error.
- To fix this, harnessed the existing port_config.ini file to fetch the interface details and populated a port_dict and this fetch the alias interface names quickly.
NOTE: config commands are entirely modified from linux commands to db format. This fix does not cover interface validation for those commands.
=> Fix to get all port related attributes from config_db

scripts/fast-reboot
This PR is enabled by sonic-buildimage PR 2238
In test, we found that when issue-ing "docker kill swss", it causes swss service to become FAILED. As result, systemctrl will execute swss stop script. Which will also stop syncd service if the warmboot flag is not set in warm boot case. Before sonic-buildimage PR 2238, this will cause syncd process being killed instead of shutting down properly in both warm/fast reboot cases. Most importantly switch_remove() is not called. For both warm boot and fast reboot, properly shutting down syncd process is very crucial to the operations.
- Setting warm boot flag before kill swss docker, so that it won't stop syncd at the same time. (syncd will be stopped explicitly later)
- In fast reboot case, syncd script has knowledge to stop …
=> [warm boot] move warm reboot/fast reboot knowledge to syncd service script

config/main.py, show/main.py
```
root@node1# config warm_restart bgp_timer 14
root@node1# show warm_restart config
name    enable    timer_name    timer_duration
------  --------  ------------  ----------------
bgp     false     bgp_timer     14
system  true      NULL          NULL
root@node1:/# config warm_restart enable bgp
root@node1:/# show warm_restart config
name    enable    timer_name    timer_duration
------  --------  ------------  ----------------
bgp     true      bgp_timer     14
system  false     NULL          NULL
```
Signed-off-by: Rodny Molina <rmolina@linkedin.com>
=> Adding bgp's warmrestart timer and on-off knob

scripts/fast-reboot, scripts/reboot
unload kexec config before rebooting and/or during warm reboot failure clean up.
=> [warm reboot] unload kexec before rebooting and when error exiting from warm boot

config/main.py
Log message during `config load_minigraph`, `config reload `
Catch exception during `stop/restart` service and log the error. Reference [PR](https://github.com/Azure/sonic-utilities/pull/259) for this changes. 
Verify the syslog
None
```
Nov  9 21:48:03.211117 sonic INFO config: 'load_minigraph' executing...
Nov  9 21:48:03.235307 sonic ERR config: Stopping swss failed with error 1
```
```
Nov  9 21:48:29.134913 sonic INFO config: 'reload' executing...
Nov  9 21:48:29.167651 sonic ERR config: Stopping swss failed with error 1
```
-->
=> Log message during config load_minigraph/reload

show/main.py
In practice, a software bug could cause not having restore_count, and
we could have use case (e.g. warm-shutdown) has state without
restore_count.
It would be nice that the command show all these rows without exception.
=> [show command] allow warm restart table contains empty restore_count

scripts/fast-reboot, scripts/reboot
**Don't merge this disruptive change!**
The 'redis-cli save' will save database content in a binary file, which is much fast than redis-dump.
=> [warmboot] Use 'redis-cli save' to dump database to file

acl_loader/main.py
If input_interface is set, it will be converted to IN_PORTS.
```
format:
"input-interface": {
"interface-ref": {
"config": {
"interface": <interface_list>
}
}
}
```
It will be parsed and converted to:
"IN_PORTS": <interface_list>
as an attribute to the current ACL rule.
=> [acl_loader]: Add support for parsing input interface

scripts/fast-reboot
When pausing orchagent fails, it could fail quickly in succession. That defeats the purpose of retrying 5 times. Add a sleep in between retries.
=> [warm reboot] wait 1 second before retrying pausing orchagent

scripts/fast-reboot
Do not explicitly remove opennsl module during warm reboot. Removing the module introduces a 30+ seconds delay when kernel removes the netdevs.
=> [warm reboot] don't remove opennsl module during warm reboot

scripts/ecnconfig
New syntax:
"Ethernet0|4": {
"wred_profile": "[WRED_PROFILE|AZURE_LOSSLESS]",
"scheduler": "[SCHEDULER|scheduler.0]"
},
On dut:
$ sudo ecnconfig -q 3 on -vv
Enable ECN on Ethernet0,Ethernet4,Ethernet8,Ethernet12,Ethernet16,Ethernet20,Ethernet24,Ethernet28,Ethernet32,Ethernet36,Ethernet40,Ethernet44,Ethernet48,Ethernet52,Ethernet56,Ethernet60,Ethernet64,Ethernet68,Ethernet72,Ethernet76,Ethernet80,Ethernet84,Ethernet88,Ethernet92,Ethernet96,Ethernet100,Ethernet104,Ethernet108,Ethernet112,Ethernet116,Ethernet120,Ethernet124 queue 3
$ sudo ecnconfig -q 4 off -vv 
Disable ECN on Ethernet0,Ethernet4,Ethernet8,Ethernet12,Ethernet16,Ethernet20,Ethernet24,Ethernet28,Ethernet32,Ethernet36,Ethernet40 …
=> Accommodate syntax change in ecn/wred profile apply

config/main.py
Signed-off-by: Guohan Lu <gulv@microsoft.com>
enable warm_restart for teamd and verify restarting teamd will have warm restart option.
```
admin@vlab-01:/usr/share$ sudo config warm_restart enable teamd
admin@vlab-01:/usr/share$ redis-cli -n 4
127.0.0.1:6379[4]> keys *WARM*
1) "WARM_RESTART|teamd"
127.0.0.1:6379[4]> hgetall "WARM_RESTART|teamd"
1) "enable"
2) "true"
127.0.0.1:6379[4]> exit
admin@vlab-01:/usr/share$ sudo systemctl restart teamd
admin@vlab-01:/usr/share$ ps aux | grep team
admin    29542  0.0  0.1  11820  2988 ?        Ss   09:36   0:00 /bin/bash /usr/bin/teamd.sh attach
admin    29546  0.6  1.2 162648 25668 ?        Sl   09:36   0:00 docker attach --no-stdin teamd
root     29622  7.0  0.7  49128 15272 pts/3    S …
```
=> enable/disable warm_restart for teamd docker

config/main.py
* Fix Unexpected keyword argument when changing port speed using config
command
Signed-off-by: gene_kuo@edge-core.com
Fixes #397 
Fix Unexpected keyword argument when changing port speed using config
command
Add argument "interface_speed" to function "speed" in config/main.py
Run ```config interface Ethernet0 speed 100```
```
admin@sonic:~$ sudo config interface Ethernet0 speed 100
File "/usr/bin/config", line 9, in <module>
load_entry_point('sonic-utilities==1.2', 'console_scripts', 'config')()
File …
```
=> [sonic-utilities/config]: Fix Config Command for Change Port Speed

config/main.py
Fix https://github.com/Azure/sonic-buildimage/issues/2046.
All `sonic-cfggen -m` in `config qos reload` should be reading from db using `sonic-cfggen -d` instead.
=> Use -d instead of -m in config qos

scripts/fast-reboot
- Add command line option parsing to warm/fast reboot script.
- Allow ignoring orchagent pausing failure with -f option.
- Add verbose output statements.
- Log progress to syslog
=> [warm boot] introduce command line options to warm/fast reboot scripts

config/main.py, show/main.py
- Relaxed the validation of alias 'key' attribute as optional one. Script won't crash in the absence of alias-names in config/show commands.
- In show/main.py we fetch the alias-interface-names at startup to calculate the maximum length. Fixed by raising exception for invalid KeyError and break the operation. So, other part of script-execution won't be affected by the absence.
- In config/main.py we need to force the user to avoid configuring the CLI ["sudo config interface_naming_mode alias" ] to alias_mode. Without any alias entries in config it is useless to proceed further. So, allow alias mode configuration only when all ports are configured with suitable alias entries.
- This fix address #403 
show interface status
show …
=> Fix to make alias 'key' as optional atrribute in config/show commands

acl_loader/main.py
The mirror session's state is now stored in the state database
instead of the application database.
=> [acl-loader]: Read state from state db instead of appl db

sonic_installer/main.py
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
preserve the file/directories structure, attributes etc during backup.
This is needed for example FRR configuration under /etc/sonic/frr might not be under root ownership. with the old backup method, the ownership etc will be lost.
use "cp -ar" instead of "cp -r"
/etc/sonic/frr is under admin:admin,  when it backed up, the structure and attributes were preserved.
-->
=> [sonic_installer] preserve the backup file/directories structure, attributes etc

show/main.py
1. Removed 'show interfaces alias' command, based on https://github.com/Azure/SONiC/issues/290
2. Removed 'show interfaces summary' command, based on https://github.com/Azure/SONiC/issues/293
Removed definition of 'show interfaces summary' and 'show interfaces alias' from ./show/main.py
1. Check if 'show interfaces summary' and 'show interfaces alias' are invalid commands in Sonic shell, and do not provide any output.
2. Check if 'alias' and 'summary' are not available from 'show interfaces --help'.
3. Check if other 8 interfaces subcommands are not affected.
```
show interfaces summary
Bridge: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500 …
```
=> Removed 'show interfaces alias / summary'.

scripts/fast-reboot
* when bgp is not configured, there is no bgpd process, we should ignore the err check.
* when bgpd does not exist, EXIT_CODE is 1, we allow it along with EXIT_CODE SUCCESS 0, for both, we make it pass the errexit check
=> [Warm-reboot] Don't allow warm-reboot script to err exit when bgpd process doesn't exist(EXIT_CODE 1)

scripts/intfutil
I've added the OpticsType onto the output at the end of the "show interface status" command
I did this by getting the optics info from the REDIS STATE DB
You will be able to verify it if the optics are removed or changed on an interface. 
```
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/show$ show int status
Interface            Lanes    Speed    MTU           Alias    Oper    Admin
-----------  ---------------  -------  -----  --------------  ------  -------
Ethernet0      29,30,31,32      40G   9100    fortyGigE0/0    down       up
Ethernet4      25,26,27,28      40G   9100    fortyGigE0/4    down       up
Ethernet8      37,38,39,40 …
```
=> [show] adding optics info to show int status command 

scripts/fast-reboot
- add -x option to enable script execute in -x mode for debugging purpose.
- timeout on database query so the script will fail after timeout instead of stuck.
=> [warm reboot] timeout waiting for database operation and add -x option

scripts/fast-reboot, show/mlnx.py
- use system warmboot for Mellanox fastfast boot flow.
- 'backup_datebase' -> 'backup_database'
- don't fail if 'pkill -USR1 teamd' failed because no teamd processes are running in teamd docker
-->
=> [mellanox|ffb] use system level warm reboot for Mellanox fastfast boot

scripts/reboot
After upgrading to docker-ce 18.09.0. Shutdown SONiC takes 5-10 minutes
waiting for all the running docker containers to quit. They all enventually
hit the timeout and caused the huge delay.
This is a work-around until proper solution is found.
with the change, reboot takes little time after upgrading to docker-ce 18.09.0. Otherwise the reboot takes about 5-10 minutes on shutdown path.
=> [reboot] stop docker service before rebooting

setup.py
speed up command execution by avoiding 'pkg_resources' import.
related issue : https://github.com/Azure/sonic-utilities/issues/408
Used https://github.com/ninjaaron/fast-entry_points
```bash
admin@sonic:~$ time show
Usage: show [OPTIONS] COMMAND [ARGS]...
SONiC command line - 'show' command
Options:
Commands:
aaa                   Show AAA configuration
acl                   Show ACL related information
arp                   Show IP ARP table
clock                 Show date and time
ecn                   Show ECN configuration
environment           Show environmentals (voltages, fans, temps) …
```
=> avoid using pkg_resources for faster command execution

show/main.py
I updated the /usr/lib/python2.7/dist-packages/show/main.py file to add new commands
show route-map 
show ip prefix-list 
I'm pulling the information from quagga (vtysh) into the main cli. 
run commands
"show route-map"
and 
"show ip prefix-list" 
There was no previous command for this unless you went into vtysh 
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/show$ show route-map
ZEBRA:
route-map RM_SET_SRC, permit, sequence 10
Match clauses:
Set clauses:
src 10.1.0.32
Call clause:
Action:
Exit routemap
ZEBRA:
route-map RM_SET_SRC6, permit, sequence 10
Match …
=> add show route-map and show ip prefix-list commands

acl_loader/main.py
Fix for crash while executing 'show acl rule' in case ACL entry doesn't
have 'MATCH' fields (e.g. default action).
How to reproduce:
* apply config having ACL rule like
"TESTACL|DEFAULT_RULE": {
"PRIORITY": "1",
"PACKET_ACTION": "DROP"
}
* execute in console
show acl rule
Fix details:
in case ACL entry doesn't have any MATCH field just emulate one by pushing
empty string into the array.
@lguohan @jipanyang @stcheng  Please review it
=> [acl_loader]: Prevent crash in the event ac ACL entry has no 'MATCH' fields

scripts/fast-reboot, scripts/reboot, show/main.py
Move reboot-cause files from /var/cache/ to /host in order for the files to persist across SONiC upgrades (i.e., so that upon upgrading SONiC, we can still access the previous reboot cause from within the old image.
Note that this also requires corresponding changes in sonic-buildimage repo. PR to be opened soon.
=> [reboot cause] Move reboot-cause files to /host directory so they persist across SONiC upgrades

config/main.py
Reverts Azure/sonic-utilities#445
Name mismatch in delete operation. Fix planned in separate PR.
=> Revert "[config/main.py]Fixed - added a validation such that delete portchann…"

scripts/intfutil, show/main.py
- remove 'show interfaces pfc status'
- add 'Asymmetric PFC' status to the output of 'show interfaces status' 
```
admin@sonic:~$ show interface pfc status
Interface    Asymmetric
-----------  ------------
Ethernet0    on
Ethernet4    N/A
Ethernet8    N/A
Ethernet12   N/A
```
```
admin@sonic:~$ show interface status
Interface            Lanes    Speed    MTU    Alias    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -------  ------  -------  ------  ----------
Ethernet0          0,1,2,3 …
```
=> [intfutil] add Asymmetric PFC status to 'show interface status'

scripts/aclshow
Modified _aclshow_ utility.
1. Removed three unneeded columns (Type / Priority / Action) from the output 
(as this information is duplicated by _acl-loader_ utility).
2. Removed unneeded arguments (_details_ and _ports_) passed to the utility.
3. Added handling of arguments (_rules_ and _tables_), which were accepted by the utility but not handled 
(now the output is filtered based on the passed arguments).
Modified _scripts/aclshow_
Run _aclshow_ utility with all possible options:
_aclshow_
_aclshow -h_
_aclshow -a -vv_
_aclshow -t <existing_table,unexisting_table> -a_
_aclshow -r <existing_rule,unexisting_rule> -a_
```
aclshow   -a -t DATAACL -r …
```
=> [aclshow] output only counters per table/rule

scripts/fast-reboot, scripts/reboot
Sync o.s. time to CMOS before rebooting, so if CMOS clock has drifted, we fix it at reboot time after syncing with NTP.
What we found is that every time the o.s. boots up, the Linux kernel will take CMOS time and then sync with NTP. NTP fixes the time difference overtime. The o.s. syncs the o.s. time to CMOS at certain frequency that is not very often.
In a test setup when I continuously run warm-reboot, the small sync with the correct time got lost after every reboot.
With this change, the small sync will be persisted to CMOS. With the change, over 24 hours period, I saw clock got fixed towards the right NTP time by 35-ish seconds. This is slow but better than no sync at all.
=> [clock] sync os time to CMOS before rebooting

sonic_installer/main.py
Improve error handling in sonic_installer. Output messages to console rather than crashing and displaying backtrace.
1. If attempting to install a local image, first check whether the specified image file exists and is a regular file. If not, output an error message to the console and abort the operation.
2. If provided a URL as an image location, check for an HTTP response from the remote machine, and verify that the response is not 4xx. If either of these conditions exist, output a message to the console  and abort the operation.
1. Pass sonic-installer the name of an image file which doesn't exist on the local machine. Instead of a backtrace, you should see the following message:
```
Image file does not exist or is not a …
```
=> [sonic_installer] Improve error handling

show/main.py
Handle exceptions (KeyError and ValueError), when user issued 'show interfaces neighbor expected' command and 
DEVICE_NEIGHBOR data is not present configuration file.
In the src/sonic-config-engine/sonic-cfggen file 'KeyError' exception handled, when DEVICE_NEIGHBOR or DEVICE_NEUGHBOR_METADATA information is not present.
In the sonic-utilities/show/main.py utility, 'ValueError' exception handled.
Issue 'show interfaces neighbor expected' command and observe no exceptions. 
If DEVICE_NEIGHBOR data present in configuration file, data will be displayed. 
root@sonic-testing:/home/admin# show interfaces neighbor expected 
Traceback (most recent call …
=> Fix for KeyError: 'DEVICE_NEIGHBOR' when executing 'show interfaces neighbor expected' command

scripts/fast-reboot
'/sbin/reboot' randomly trigger a delay in shutdown path on some
platforms, this delay caused the lags to timeout.
Tested 'kexec -e' 1500+ times and never triggered the shutdown delay.
=> [fast/warm reboot] set default reboot method to "kexec -e"

scripts/decode-syseeprom, show/main.py
* Option '-d' means read the EEPROM information from DB directly
* CLI "show platform syseeprom" will invoke decode-syseeprom with
'-d' option
Signed-off-by: Kevin Wang <kevinw@mellanox.com>
Add a new option '-d' for decode-syseeprom to read EEPROM data from DB directly rather than from cache file.
It will support on the platforms which are using the TLV format in EEPROM file. As Arista uses a different format, so doesn't support this function on Arista platform until the update_eeprom_db() and read_eeprom_db() are overridden on Arista platform.
This change depends on the parent PR https://github.com/Azure/sonic-platform-common/pull/21.
Should not be merged before the parent PR is merged.
At the init stage, need to invoke command"decode-syseeprom --init" to update the …
=> [decode-syseeprom] Add option '-d' for decode-syseeprom

scripts/psushow, setup.py, show/main.py, sonic-utilities-tests/mock_tables/dbconnector.py, sonic-utilities-tests/mock_tables/state_db.json, sonic-utilities-tests/psu_test.py
* Access DB directly to get the PSU status information
* Add test case for psu CLI
Signed-off-by: Kevin Wang <kevinw@mellanox.com>
Refactor the CLI "show platform psustatus". As we implement a daemon for PSU to collect the status/presence information and write to state db, the CLI could get that information from state DB directly. It could improve the performance a lot. From the test on Mellanox platform, the old CLI costs around 1.8s, the new CLI just costs 5ms. The performance is > 300 times improvement.
Implement a script "psushow" to read the information from state DB directly.
Run "show platform psustatus".
**- New command output (if the …
=> Get PSU status from DB directly

counterpoll/main.py
Signed-off-by: Wenda Ni <wenni@microsoft.com>
In accordance with change in https://github.com/Azure/sonic-swss/pull/777
$ counterpoll show
Type                  Interval (in ms)    Status
--------------------  ------------------  --------
QUEUE_STAT            default (10000)     enable
PORT_STAT             default (1000)      enable
QUEUE_WATERMARK_STAT  default (10000)     enable
PG_WATERMARK_STAT     default (10000)     enable
-->
=> Update watermark default polling interval to 10s

scripts/aclshow
Signed-off-by: Roman Kachur <romankac@mellanox.com>
I reverted PRIO column to aclshow output.
Set sorting of rules to 'first by Table then by Priority',
before it was 'first by Table then by Counter'.
Added PRIO column to aclshow, changes sorting.
Load acl rules and run _aclshow -a_
```
RULE NAME     TABLE NAME      PACKETS COUNT    BYTES COUNT
------------  ------------  ---------------  -------------
RULE_9        DATAACL                   901            900
RULE_7        DATAACL                   701            700
RULE_4        DATAACL                   401            400
RULE_3        DATAACL                   301            300
RULE_2 …
```
=> [aclshow] restore PRIO column and sort entries by priority

sonic-utilities-tests/aclshow_test.py, sonic-utilities-tests/mock_tables/config_db.json, sonic-utilities-tests/mock_tables/counters_db.json
Signed-off-by: Roman Kachur <romankac@mellanox.com>
I created a unittest for the aclshow utility
Exploiting mock_tables, I added mock Rules, Databases, and occasional Counters.
Unittest calls aclshow with different arguments, and compares its output with the predefined outputs.
In total 10 cases were covered:
- aclshow
- aclshow -a
- aclshow -r RULE_1 -t DATAACL
- aclshow -r RULE_0 -a
- aclshow -r RULE_0
- aclshow -r RULE_6,RULE_4 -vv
- aclshow -t EVERFLOW
- aclshow -t DATAACL
- aclshow -c
- aclshow -c ; aclshow -a
python2 -m py.test  aclshow_test.py -v
N/A
```
collected …
```
=> aclshow unittest

scripts/reboot
Improve reboot script. Fixing issue https://github.com/Azure/sonic-buildimage/issues/2264
Added -h/-?/-x options
Tested on DUT.
=> [reboot script] add -h, -? options

scripts/fast-reboot
Setup control plane assistant when available
Limited test: confirmed the control plane assistance script is invoked with right parameters. confirmed the tear down is invoked when warm-reboot failed.
=> [warm/fast reboot] setup control plane assistant when available

scripts/intfutil
Updated the file to add a "VLAN" column that reports "routed", ~~"VlanXXXX"~~ "trunk", or "PortChannelXXXX" depending on how that interface is configured.  This is how Arista/Cisco report on this command. 
Also added PortChannels to the bottom on the command like Cisco/Arista.
Updated the intfutil file to add additonal methods to support this.
run the "show int status" command on the sonic systems.
```
admin@str-s6000-acs-11:/usr/bin$ show int status
Interface            Lanes    Speed    MTU           Alias    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  --------------  ------  -------  ------  ---------- …
```
=> [show] show interface status added vlan and portchannels to command

pfcwd/main.py
In accordance with https://github.com/Azure/sonic-swss-common/pull/266
Signed-off-by: Wenda Ni <wenni@microsoft.com>
-->
=> Change PFC watchdog CONFIG_DB table name from PFC_WD_TABLE to PFC_WD

show/main.py
Added the output of "show platform summary", "uptime", and "sudo decode-syseeprom -s" to get the serial number of the device.   I did this to include information most network engineers expect when running show version.
I added a function (run_command_save) to save the output of an existing command and then used that output to add the additional info into "show version".
Just run "show version" on the CLI.
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/show$ show version 
SONiC Software Version: SONiC.HEAD.534-8af9b8c
Distribution: Debian 9.8
Kernel: 4.9.0-8-2-amd64
Build commit: 8af9b8c
Build date: Tue Mar 12 13:44:27 UTC 2019
Built by: …
=> [show] Add serial numbers/uptime/hwinfo to 'show version' output

show/main.py
- Add support for 'alias' interface naming mode to the `show ip interface` command.
- Also modify `InterfaceAliasConverter.name_to_alias()` and `InterfaceAliasConverteralias_to_name.()` so that they no longer raise click.Abort(). Instead, if the interface name or alias to translate is not found in the PORT table of ConfigDB, we simply and gracefully return the untranslated parameter that was passed. A command like `show ip interfaces` will present interfaces besides front-panel interfaces (eth0, docker0, lo, etc.), so this prevents the need to do yet another test of whether the port is a front-panel port or not.
```
sudo config interface_naming_mode alias
logout
<log back in to device>
<confirm output now contains interface …
```
=> [show ip interface] Add support for 'alias' interface naming mode

scripts/fast-reboot
Make sure that when the new image boots up, the component state won't
be 'reconciled'.
continuous warm reboot.
admin@str-7260cx3-acs-1:~$ show warm_restart state ; uptime
name             restore_count  state
-------------  ---------------  ----------------------
syncd                       83
vlanmgrd                    83
neighsyncd                  83  reconciled
portsyncd                   83
teammgrd                    83
bgp                         83  reconciled
warm-shutdown                0  pre-shutdown-succeeded
orchagent                   83  reconciled
teamsyncd                   83
16:13:00 up 6 min,  1 user,  load average: 2.81, 1.54, 0.76
admin@str-7260cx3-acs-1:~$ show warm_restart …
=> [warm-reboot] initialize warm reboot state table before warm rebooting

show/main.py
Add support for 'alias' interface naming mode to the show ipv6 interface command.
Added these two lines to the function for "show ipv6 interfaces"
if get_interface_mode() == "alias":
iface = iface_alias_converter.name_to_alias(iface)
This is the same as what Joe did for PR 486. 
https://github.com/Azure/sonic-utilities/pull/486
Only just updated for IPv6.
```
sudo config interface_naming_mode alias
logout
<log back in to device>
<confirm output now contains interface aliases>
```
```
sudo config interface_naming_mode default
logout
<log back in to device>
<confirm output now contains SONiC port names
```
**- …
=> updated show ipv6 interface for alias mode

show/main.py
I updated the "show interface neighbor expected" command to be able to work with Alias mode. 
Verify the interface naming mode and then switch between them to verify the command. 
```
sudo config interface_naming_mode alias
logout
<log back in to device>
<confirm output now contains interface aliases>
sudo config interface_naming_mode default
logout
<log back in to device>
<confirm output now contains SONiC port names>
```
```
admin@str-s6000-acs-11:~$ show int naming_mode 
default
admin@str-s6000-acs-11:~$ show int neigh exp
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt …
```
=> [show interface neighbor expected] Support 'alias' interface naming mode

clear/main.py
Changes done:
---------------------------------------------------------------------------------------
1.) Clear ARP command clears NDP entries too today, With this fix, it will not clear NDP entries.
2.) Clear ndp <ip>(optional parameter) command has been added to clear one or all ndp neighbors.
3.) run_command function in clear/main.py file provides option for caller to process output.
4.) use ip neigh for clear arp\ndp instead of /usr/sbin/arp.
Reason for Point 4 
As per arp (8) - Linux Man Pages:
/usr/sbin/arp program is obsolete. For replacement check ip neigh. 
---------------------------------------------------------------------------------------
Added clear ndp <ip> command with below changes:
------------------------------------------------------------------------- …
=> [clear/main.py]: clear ndp command.

show/main.py
I updated the "show vlan brief" command to be able to work with Alias mode.
Verify the interface naming mode and then switch between them to verify the command.
```
sudo config interface_naming_mode alias
logout
<log back in to device>
show vlan brief
<confirm output now contains interface aliases>
sudo config interface_naming_mode default
logout
<log back in to device>
show vlan brief
<confirm output now contains SONiC port names>
```
```
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/show$ show vlan brief
+-----------+--------------+------------+----------------+-----------------------+
|   VLAN ID | IP Address   | Ports      | Port …
```
=> [show vlan brief] Support 'alias' interface naming mode

config/main.py
before:
config interface <interface_name> COMMANDS ...
after:
config interface COMMANDS <interface_name> ...
To make backwards compatible with 201803 branch and older,
change the order of the command arguments.
=> [config]: Change the order of interface commands

scripts/generate_dump, show/main.py
I added new option to ```show techsupport``` to specify ```--since``` parameter, e.g:
```
show techsupport --since=yesterday
```
When specified, the command will generated dump and include only logs and core files created since given date.
Also I added mstdump for mellanox to the script
execute:
```
show techsupport --since=yesterday
```
```
admin@sonic:~$ show techsupport -h
Usage: show techsupport [OPTIONS]
Gather information for troubleshooting
Options:
--verbose       Enable verbose output
```
```
admin@sonic:~$ show …
```
=> [generate_dump] system dump improvements

scripts/fast-reboot
treat `warm-reboot` as a  `fastfast-reboot` for Barefoot based platforms
run `sudo warm-reboot` on the hardware box
**- Description for the changelog**
Add warm/fast-boot feature processing for wedge100bf_32x/65x platforms
**- Should be merged together with**
https://github.com/Azure/sonic-sairedis/pull/434
https://github.com/Azure/sonic-buildimage/pull/2687
@akokhan, @mkbalani FYI
=> Add warm/fast-boot feature processing for wedge100bf_32x/65x platforms

scripts/intfstat, scripts/portstat, utilities_common/__init__.py
Handled https://github.com/Azure/sonic-buildimage/issues/2738
Show the BPS, PPS rates even if the counters were not cleared yet. 
Both for *show interface counters* and  *show interface counters rif*
If no counters cache available, calculate the rates over the switch uptime.
```
admin@sonic:~$ show int counters
IFACE    STATE    RX_OK    RX_BPS    RX_PPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK    TX_BPS    Tx_PPS    TX_UTIL    TX_ERR
----------  -------  -------  --------  --------  ---------  --------  --------  --------  -------  --------  --------  ---------  --------
Ethernet0 …
```
=> [portstat] show BPS, PPS, UTIL rates w/o previous clear

scripts/fast-reboot
- Refactoring some code into functions, and making main start point more visible.
- Add sanity checks for warm reboot (some check might be useful for reboot script too. Will create another PR when this one is in).
- Make sure that the next boot image is available.
- Make sure that /host is write-able and has enough space.
- continuous warm reboot
- reduce /host space available to at 100M and passed.
- further reduce /host space available and warm-reboot will abort.
- file system read-only test: have to change script to test with path /host/test and mount /host/test as read-only:
host> mount -t tmpfs -r -o size=100M tmpfs /host/test/
host> warm-reboot -v
touch: cannot touch '/host/test/test-20190412-223147': Read-only file system
Fri Apr 12 22:31:47 …
=> [fast/warm reboot] add some sanity check before warm reboot

config/main.py, show/main.py
Add hostcfgd as one of the services to restart upon load_minigraph, as load_minigraph does flush_db and creates the DB from scratch.
Even if we may get into flush_db to ensure  proper DB updates on 'deletes' to subscribers, when starting config from scratch it is more clean with less loop-holes if we could restart the subscribers.
1) Setup TACACS auth and see it reflect in /etc/pam.d/common-auth-sonic
2) sudo config load_minigraph
3) View /etc/pam.d/common-auth-sonic to find those TACACS servers not there anymore, as load_minigraph should have removed them.
-->
=> load_minigraph: restart hostcfgd

scripts/psushow, sonic-utilities-tests/mock_tables/state_db.json
* Aligned PSU DB 'num_psus' with the schema Spec
* N/A
1. show platform psustatus
```
root@sonic:/home/admin# show platform psustatus
Error! Failed to get the number of PSUs!
Error: fail to get psu status from state DB
```
```
root@sonic:/home/admin# show platform psustatus
PSU    Status
-----  --------
PSU 1  OK
PSU 2  OK
```
=> Align PSU DB count field with the schema Spec

pfcwd/main.py
$ pfcwd show stats
QUEUE       STATUS    STORM DETECTED/RESTORED    TX OK/DROP    RX OK/DROP    TX LAST OK/DROP    RX LAST OK/DROP
------------  -----------  -------------------------  ------------  ------------  -----------------  -----------------
Ethernet36:3  operational                       18/9        0/1800        0/1800              0/100              0/100
Ethernet36:4  operational                       18/9        0/1800        0/1800              0/100              0/100
Ethernet96:3  operational                       18/9        0/1800        0/1800              0/100              0/100
Ethernet96:4  operational                       18/9        0/1700        0/1700              0/100              0/100
$ pfcwd show stats
QUEUE       STATUS    STORM DETECTED/RESTORED    TX …
=> Bring queue storm status to 'pfcwd show stats'

scripts/pcmping, show/main.py
The two possible key formats of INTERFACE table are:
INTERFACE|<NAME>|<PREFIX>
INTERFACE|<NAME>
The last one carries RIF information without the prefix so it has to be
omitted
Signed-off-by: Marian Pritsak <marianp@mellanox.com>
=> Skip INTERFACE entries w/o prefix

config/main.py, scripts/db_migrator.py, setup.py
- Add infrastructure to migrate DB contents from a lower version schema
to a higher version schema, eventually reach latest version.
- if config load_minigraph is executed, the db schema version is always
the latest.
Some manual tests.
=> [db migrator] Introduce the DB migration infrastructure

scripts/fast-reboot
This change aligns fast-reboot script with the master
at point 42582872ac0285fed53141d9e4b9a1a5652bb132
Unfortunatelly cannot be cherry-picked because original
commits also change other files
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Updated fast-reboot script to update firmware before reboot
Used version from 201811 (latest before warm-reboot)
Tested upgrade to 201811 with fast-reboot
See log below
```
root@mts-sonic-dut:/home/admin# mlxfwmanager
Querying Mellanox devices firmware ...
Device #1:
----------
Device Type:      Spectrum
Part Number: …
```
=> [Mellanox] Update FW if needed before fast-reboot

scripts/teamshow, show/main.py
- Also modify teamshow to print a message and exit if it is not run as root.
- NOTE: This change will also require a modification to the sudoers file in sonic-buildimage to be complete.
=> [show] Call teamshow using sudo in 'show interfaces portchannel'

scripts/teamshow
Although teamd would indicate a team member is selected or not, due to
teamsyncd issue, it is possible that the state is not correclty synchronized
into the application database.
Add this '*' to indicate if the member port's state is not written into the
database.
=> [teamshow]: Add * to indicate if the state has been synced into database

scripts/ecnconfig
BUG: on t0 topo, if Ethernet0 is disabled, ecnconfig -q 3 will return the ecn status to be off on active ports.
Signed-off-by: Wenda Ni <wenni@microsoft.com>
Operate (get & set) ecn on/off status on active ports only. 
on brcm dut
-->
=> Fix TODO to get/set ecn status on active ports only

scripts/reboot
- Do not reboot device if the next image is not there.
- Log if the filesystem is read-only or full
Verified that the reboot request is logged in syslog.
Verified that the read-only file system won't stop rebooting, but will leave a log.
Verified that reboot won't proceed if next image is missing.
=> [reboot] log reboot progress and add a sanity check before reboot

sonic_installer/main.py
- `sonic_installer install` command now retrieves the version of the binary it is told to install and checks to see if it is in the list of currently installed images. If it is, the command outputs a message stating so and simply attempts to set that image as the default image.
- Also added a check in `sonic_installer install` to compare the image type (ONIE, Aboot, etc.) of the binary image it is told to install against the type of the currently running image. If the types do not match, the command will output a message informing the user of the mismatch and exit in error. However, I also added a `-f|--force` option in order to allow the user to forcefully install an image of a different type, just in case the need were to ever arise.
Related enhancements and refactoring:
- Rename …
=> [sonic_installer] If asked to install an image which is already installed, simply set as default

acl_loader/main.py
Default deny rule shall not be applied for neither MIRROR nor MIRRORV6
=> [acl_loader]: Do not apply default DENY rule for MIRRORV6 table

show/main.py
To clear configuration and load default l2 configuration, execute below commands.
redis-cli -n 4 flushdb
redis-cli -n 4 SET CONFIG_DB_INITIALIZED true
sonic-cfggen --preset l2 -H -p -k Accton-AS5712-54X  >/etc/sonic/config_db.json
config reload -y
After the clear config with above commands, switch reloaded with l2 default configuration (config_samples.py).
The command 'show vlan brief' displaying the default VLAN (1000) and associated members. 
But 'show vlan config' command not displaying not the VLAN information.
To fix this issue,  to the default l2 configuration(config_samples.py), all ports are added as members of default VLAN. The VLAN dict is updated with members list. 
In config_samples.py file, members are added to default Vlan(1000). 
In …
=> 'show vlan config' is not displaying the VLAN members, after the clear config and reload with default l2 configuration.

show/main.py
- Remove ability to clear counters from the following `show` commands, because all of these counters can now be cleared using the `sonic-clear` command, which is the appropriate command to use
- `show interface counters`
- `show pfc counters`
- `show queue counters`
- Also fix some comments and help messages
=> [show] Remove ability to clear counters from 'show' commands

config/main.py
IP Add CLI do not do any IP Address validation check. It accepts and inserts any string as IP address.
Added IP Address validation check.
Checking for valid IP v4/v6 as part of CLI configuration. Throw error if IP is not valid.
Configure IP Add/Del with invalid IP address should throw error.
No change in CLI syntax.
Log before change :
admin@sonic:$ sudo config interface ip add Vlan100 ?
admin@sonic:$ sudo config interface ip add Vlan100 21.1.1.2/24
admin@sonic:$ show run all
{
"VLAN_INTERFACE": {
"Vlan100|21.1.1.2/24": {}, 
"Vlan100|?": {}
},
No change in CLI syntax. …
=> IP Address validation check

counterpoll/main.py, scripts/watermarkstat, show/main.py
$ watermarkstat -t buffer_pool -p
Shared pool maximum occupancy:
Pool    Bytes
---------------------  -------
egress_lossless_pool   570336
egress_lossy_pool  2054624
ingress_lossless_pool     1664
$ counterpoll watermark enable
$ counterpoll watermark interval 20000
Apr 23 17:49:44.686196 
Apr 23 17:50:04.686427 
Apr 23 17:50:24.686704 
$ counterpoll watermark disable
$ counterpoll show
Type                        Interval (in ms)    Status
--------------------------  ------------------  --------
QUEUE_STAT                  default (10000)     enable
PORT_STAT                   default (1000)      enable
QUEUE_WATERMARK_STAT        20000               disable
PG_WATERMARK_STAT           20000               disable
BUFFER_POOL_WATERMARK_STAT  20000               disable …
=> Add buffer pool watermark support in watermarkstat and counterpoll

scripts/intfutil
**What I did**
show interface status Ethernet0 and show interface description Ethernet0. And the error message is dump
Use an incorrect variable db to get APP_DB. The correct variable should be appl_db
**How I verified it**
After modifying correct variable, the show interface status <interface name> would show correct value
=> [intfutil] Fix error when <interface name> specified in show interface related commands

scripts/fast-reboot
This helps to reduce the possbility of reply message loss from orchagent within the whole checking period
Has dependency on https://github.com/Azure/sonic-swss/pull/833 Add retryCount option for orchagent_restart_check program.
To  address issue: #827
Issue orchagent_restart_check with -r option
-->
=> [warm-reboot] Use retryCount option of orchagent_restart_check program

doc/Command-Reference.md, show/main.py
Follow commands are added-
1) show runningconfiguration accesslist
2) show runningconfiguration interface
3) show runningconfiguration interface **interfacename**
Signed-off-by: Prem Prakash prprakash@linkedin.com
Added above show commands, sonic-config-engine changes are under https://github.com/Azure/sonic-buildimage/pull/3036 
Built the python-sonic-utilities deb package and installed it in the box and tested it.
admin@lnos-x1-a-csw02:~$ show runningconfiguration ?
Usage: show runningconfiguration [OPTIONS] COMMAND [ARGS]...
Show current running configuration information
Options:
Commands:
accesslist  Show acl running …
=> [Sonic-utilities]: Added commands to view acl and port running configs

.github/PULL_REQUEST_TEMPLATE.md
Add a reminder in the GitHub pull request template to update Command Line Reference Guide if modifying user-facing commands to ensure contributors keep the documentation up-to-date with new changes.
=> [PR template] Add reminder to update Command Line Reference Guide if modifying user-facing commands

doc/Command-Reference.md
Updated the CLI doc for the following.
1) Changes based on 201904 (build#19) release, 
2) Changes related to the order in which "interfacename" is given in "config interface" commands
3) Changes in show command between FRR & Quagga 
4) Few mellanox platform specific commands addition
5) show runningconfig acl, show runningconfig interface <interfacename> additions
6) Few format changes.
=> Modified CLI doc for 201904 release, changed the config interface command, etc.,

scripts/fast-reboot
We have been running warm reboot test without removing opennsl for
10k+ iterations and not having issue.
The kexec reboot part is the same for warm reboot and fast reboot. It
should be safe for us to skip this during fast reboot to save some
time too.
=> [fast reboot] stop removing opennsl module before reboot

show/main.py
When the show command is run, don't abort if InterfaceAliasConverter fails to create port_dict. Instead, print a warning message and continue execution.
Without this change, no show commands will work if there is no PORT table in ConfigDB (e.g., if the device is freshly imaged, but unconfigured. In this situation, one cannot get any system info, as all show commands abort (e.g., `show version`, `show platform summary`, etc.). These commands should work whether or not the device is configured.
=> [show] Don't abort in InterfaceAliasConverter ctor if PORT table doesn't exist

config/main.py, scripts/db_migrator.py, scripts/neighbor_advertiser, scripts/pcmping, show/main.py
Generate interface table to have an entry designated to default VRF during config reload. This is when the interface is not configured to be part of any VRFs.  This is a placeholder PR to be merged along with https://github.com/Azure/sonic-buildimage/pull/2848
Current:
```
"VLAN_INTERFACE": {
"Vlan1000|192.168.0.1/21": {}
},
```
Proposed:
```
"VLAN_INTERFACE": {
"Vlan1000": {},
"Vlan1000|192.168.0.1/21": {}
},
```
DB migrator modified to migrate interface table during config reload
Run config reload and verify for entries without prefix in config_db
```
2) "LOOPBACK_INTERFACE|Loopback0|FC00:1::32/128"
3) "MGMT_INTERFACE|eth0|FC00:2::32/64"
4) "PORTCHANNEL_INTERFACE|PortChannel0002|FC00::75/126"
5) …
```
=> Generate interface table to have an entry for default VRF

config/mlnx.py
Prompt the risk of excessive consumption of disk space when user intends to turn on the sdk sniffer.
The SDK sniffer is a diagnosis feature, introduced with a view to recording all the operations to SDK into the sniffer file which the low-level team can replay and investigate. Only the sniffer file contains all the operations from SWSS restart does it help. To handle it in a way like log-rotate to limit its size can hurt its integrity since the operating records can be lost during rotating and to address this requires a big effort.
So we just add a prompt of that risk for now.
admin@arc-mtbc-1001:~$ sudo config platform mlnx sniffer sdk enable
To change SDK sniffer status, swss service …
=> [Mellanox] Improve the prompt of the Mellanox sdk sniffer command.

acl_loader/main.py
Signed-off-by: Jared.Liu <Jared.Liu@nephosinc.com>
when execute command "show mirror_session", the status display error.
admin@sonic:~$ show mirror_session
Name       Status    SRC IP        DST IP       GRE       DSCP    TTL  Queue
---------  --------  ------------  -----------  ------  ------  -----  -------
everflow0  error     14.14.14.149  192.192.2.2  0x6558      50     64 
there is some code error in acl_loader/main.py.
when get mirror session information from state_db, use MIRROR_SESSION_TABLE instead of MIRROR_SESSION
After fix, the status display correct.
admin@sonic:~$ show mirror_session
Name       Status    SRC IP        DST IP       GRE       DSCP    TTL  Queue    Policer
---------  --------  ------------ …
=> [acl_loader]:Fix show mirror_session error

scripts/fast-reboot
Explicitly stop corresponding services after killing Docker containers to prevent the service from automatically restarting the container during fast-/warm-reboot.
We are beginning to configure the services which control Docker containers to automatically restart the service and all dependent services if the container should ever stop. In the case of fast-/warm-reboot, stopping the service could require up to 10 seconds to stop the container (due to the behavior of the underlying `docker stop` command). This could take too long, so in this script we call `docker kill`, which will work faster. However, after killing the container, the service which controls the container (once configured to restart) will restart the container after the specified interval, but we do not …
=> [fast-reboot] Stop services after killing containers to prevent automatic restart

show/main.py
Please provide the following information:
-->
Fixed show interface neigh expected which was broken because of https://github.com/Azure/sonic-buildimage/pull/3036
There was a change in the output format for --var-json option in sonic-config-engine,changes had to be done for show commands as well.
Build the sonic-utilities debian package after applying these changes or for quick test smash /usr/lib/python2.7/dist-packages/show/main.py with the file with these changes.
**Test Data**
admin@lnos-x1-a-csw02:~$ sonic-cfggen -d --var-json "DEVICE_NEIGHBOR"
{
"DEVICE_NEIGHBOR": {
"Ethernet112": {
"name": "lsg1-p27-csw01.nw",
"port": "Eth0"
},
"Ethernet114": {
"name": "lsg1-p27-csw02.nw",
"port": "Eth0"
}
}
}
admin@lnos-x1-a-csw02:~$ …
=> Fixing the expected neighbor command due to change in output format under sonic-buildimage/pull/3036

scripts/reboot
This commit added fstrim to reboot script between
sync and sleep 3.
MERGE this PR before MERGING the following PR
https://github.com/Azure/sonic-buildimage/pull/2912
Signed-off-by: Harish Venkatraman <harish_venkatraman@dell.com>
-->
=> [sonic-utilities] Add fstrim to reboot

scripts/ecnconfig
Validate input WRED parameters, including
1) if the threshold is a non-negative integer
2) if the probability is a non-negative integer between 0 and 100
3) if min threshold is no larger than max threshold
Before setting new parameters in config DB, I validate all configuration parameters (including the old ones) using function validate_profile_data
Platform: SONiC on MLNX SN-2700
Input command: "ecnconfig -p AZURE_LOSSLESS -gmax 122 -gmin 123"
No output. But orch agent will crash due to wrong WRED parameters (gmin > gmax). You can use "ps aux|grep orch" to check the state of orch agent.
**- New command output (if the output of a command-line …
=> [ecnconfig] Validate input WRED parameters

sonic_installer/main.py
Add --warm option for docker upgrade to automatically enable warm restart before image upgrade and disable it after upgrade is done.
Added docker image version rollback tool.
<1> upgrade bgp and teamd docker
```
admin@vlab-01:~$ show warm_restart config
name    enable    timer_name    timer_duration
------  --------  ------------  ----------------
admin@vlab-01:~$ show warm_restart state
name          restore_count  state
----------  ---------------  -------
neighsyncd                0
bgp                       0
vlanmgrd                  0
orchagent                 0
teammgrd                  0
syncd                     0
teamsyncd                 0
portsyncd                 0
admin@vlab-01:~$ sonic_installer …
```
=> [warm-reboot] add docker upgrade --warm option and roll back support

scripts/sfpshow
When some specific 25G DAC attached to the system, the 'dom_info_dict'
could be a None object, as a result, the 'show int transceiver eeprom --dom'
will crash.
And thus, in this commit, we'll add an additional checker for the None object.
Signed-off-by: Dante (Kuo-Jung) Su <dante.su@broadcom.com>
Change-Id: Ic2b5eb38ddf98b98cce7eddf161595013a19c720
Add a None object checker to prevent CLI from crashing
Add a None object checker
Attach a 25G DAC to the system
-->
=> sfpshow: prevent 'show int trans eeprom --dom' from crashing

config/main.py
Remove explicit calls to stop/restart services which are now dependent on SwSS.
As of https://github.com/Azure/sonic-buildimage/pull/2546, teamd, snmp and dhcp_relay services will be stopped/started/restarted along with swss when it is stopped/started/restarted, respectively.
This prevents issues due to double restarts (e.g., this script would call `systemctl restart swss`, which would now cause teamd to restart, then shortly thereafter it would call `systemctl restart teamd`, which could lead to instability).
Now, stopping/starting/restarting swss will also stop/start/restart teamd, snmp, dhcp_relay and radv services, so we should no longer be stopping/starting/restarting them along with swss.
=> [config] Do not stop or restart dependent services when reloading config

sonic_installer/main.py
It's possible that users will either store the SONIC image in a NTFS
formatted USB disk, or make it read-only by a USB lock.
Unfortunately the sonic_installer always tries to make the image executable
during the 'sonic_installer install' process, and then fail in these cases.
And thus, in this commit, we'll copy the image to /tmp upon chmod failure,
and then resume the following operations
Signed-off-by: Dante (Kuo-Jung) Su <dante.su@broadcom.com>
Enable 'sonic_installer install' to update the SONIC from an image stored in NTFS formatted USB disk or a read-only filesystem
Copy the image to /tmp upon chmod failure, and then resume the following operations
1. Copy the SONIC image to a NTFS formatted USB, or simply make it read-only …
=> sonic_installer: fix read-only filesystem support for firmware update

scripts/portstat, utilities_common/netstat.py
When calc the RX_UTIL, currently it use hardcode 40G,
now change to get the real port speed via APP DB
Signed-off-by: Richard Wu <wutong23@baidu.com>
When test the RX_UTIL when 100G port with line rate, the RX_UTIL shows over 100%. port stats use default 40G to calc the RX_UTIL, now change to get the real time speed via APP DB
=> [portstat] Fix portstat show RX_UTIL over 100% for 100G

scripts/sfpshow, sonic-utilities-tests/mock_tables/state_db.json, sonic-utilities-tests/sfp_test.py
Added support to dump Dom Threshold values along with other dom values as per EEPROM sff8436 standard.
Read the eeprom,  save the redis transceiver_dom table with threshold values.
sfpshow eeprom --dom
Ethernet124: SFP EEPROM detected
Connector: MPOx12
Encoding: 64B66B
Extended Identifier: Power Class 1(1.5W max)
Extended RateSelect Compliance: QSFP+ Rate Select Version 1
Identifier: QSFP+ or later
Length OM3(2m): 50
Nominal Bit Rate(100Mbs): 103
Specification compliance:
10/40G Ethernet Compliance Code: 40GBASE-SR4
Vendor Date Code(YYYY-MM-DD Lot): 2010-09-01
Vendor Name: AVAGO
Vendor OUI: 00-17-6a
Vendor PN: AFBR-79E4Z-D
Vendor Rev: 01
Vendor SN: …
=> sonic_utilities: Support for DOM Threshold values for EEPROM dump

doc/Command-Reference.md
=> [doc/command-reference.md] dos2unix & remove trailing spaces

doc/Command-Reference.md, show/main.py
Added BGP neighbor and BGP neighbor ip to 'show ip interfaces' and 'show ipv6 interfaces' command output
By getting the neighbor info from the CONFIG DB BGP_NEIGHBOR table
Run show ip interfaces or show ipv6 interfaces in the hardware box
**show ip interfaces**
```
Interface      IPv4 address/mask    Admin/Oper  
-------------  -------------------  ------------
PortChannel01  10.0.0.56/31         up/down     
PortChannel02  10.0.0.58/31         up/down     
PortChannel03  10.0.0.60/31         up/down     
PortChannel04  10.0.0.62/31         up/down     
Vlan100        10.168.0.1/27        up/up       
docker0        240.127.1.1/24       up/down …
```
=> [show] Add BGP neighbor info to 'show ip/ipv6 interfaces' command output

consutil/main.py
[config]: fix the runtime error of the 'show line' command  (#595)
Signed-off-by: wangshengjun <wangshengjun@asterfusion.com>
**What I did**
Fix the runtime error of the 'show line' command 
the command of 'show line' executes fail.
**How I verified it**
Recompile the debian package and execute the 'show line' command.
**Before the change**
admin@48S:~$ show line      
File "/usr/bin/consutil", line 8, in <module>
from consutil.main import consutil
ImportError: No module named consutil.main
admin@48S:~$ show line              // add the  '__init__.py ' file 
File "/usr/bin/consutil", line 12, in <module>
Root privileges are required for this operation
sys.exit(consutil())
File …
=> [config]: fix the runtime error of the 'show line' command  (#595)

show/main.py
This partially reverts commit 3d03c130023eb03901f078369f238bd0a559e29b.
```
admin@str-s6100-acs-2:~$ show interfaces alias
Name        Alias
----------  ---------------
Ethernet0   fortyGigE1/1/1
Ethernet1   fortyGigE1/1/2
Ethernet2   fortyGigE1/1/3
Ethernet3   fortyGigE1/1/4
Ethernet4   fortyGigE1/1/5
Ethernet5   fortyGigE1/1/6
Ethernet6   fortyGigE1/1/7
Ethernet7   fortyGigE1/1/8
Ethernet8   fortyGigE1/1/9
Ethernet9   fortyGigE1/1/10
Ethernet10  fortyGigE1/1/11
Ethernet11  fortyGigE1/1/12
Ethernet12  fortyGigE1/1/13
Ethernet13  fortyGigE1/1/14
Ethernet14  fortyGigE1/1/15
Ethernet15  fortyGigE1/1/16
Ethernet16  fortyGigE1/2/1
Ethernet17  fortyGigE1/2/2
Ethernet18  fortyGigE1/2/3
Ethernet19  fortyGigE1/2/4
Ethernet20 …
```
=> Revert "Removed 'show interfaces alias'. (#412)"

doc/Command-Reference.md, show/main.py
Signed-off-by: Vasant Patil <vapatil@linkedin.com>
Testing:
```
[
admin@lnos-x1-a-csw06:~$ show runningconfiguration ?
Usage: show runningconfiguration [OPTIONS] COMMAND [ARGS]...
Show current running configuration information
Options:
Commands:
acl         Show acl running configuration
all         Show full running configuration
bgp         Show BGP running configuration
interfaces  Show interfaces running configuration
ntp         Show NTP running configuration
ports       Show ports running configuration
snmp        Show SNMP information
admin@lnos-x1-a-csw06:~$ show runningconfiguration ports
{
"Ethernet0": {
"admin_status": "up", 
"alias": "Eth1", 
"index": "1", 
"lanes": "65,66,67,68", 
"mtu": "9100", 
"speed": "100000"
}, 
"Ethernet4": { …
```
=> Changinging "show runningconfiguration interface" to "show runningconfiguration ports"

scripts/neighbor_advertiser
Fixed a bug which caused incorrect programming of vxlan tunnel map.
Run the script and check that syslog doesn't have any errors.
-->
=> [neighbor_advertiser] Use full vlan name for vxlan tunnel map programming

scripts/neighbor_advertiser
Currently only one IPv4 mirror type ACL table is supported.
Thus, in order to insert an ACL rule, we use the existing table
in the configuration.
=> [neighbor_advertise]: Use the existing MIRROR ACL table

show/main.py
Signed-off-by: Vasant Patil <vapatil@linkedin.com>
show runningconfiguration interfaces should read configDB instead of /etc/network/interfaces.
Also use the --key option of sonic-cfggen for more granular display.
Testing done:
--------------
```
admin@lnos-x1-a-csw06:~$ show runningconfiguration ?
Usage: show runningconfiguration [OPTIONS] COMMAND [ARGS]...
Show current running configuration information
Options:
Commands:
acl         Show acl running configuration
all         Show full running configuration
bgp         Show BGP running configuration
interfaces  Show interfaces running configuration
ntp         Show NTP running configuration
ports       Show ports running configuration
snmp        Show SNMP information
admin@lnos-x1-a-csw06:~$ …
```
=> Read config DB for running interface(s) and display per port/interface

scripts/fast-reboot
Kill radv docker before stopping BGP. Otherwise it will announce our
departure and cause hosts to lose default gateway.
warm reboot with IPv6 IO going through.
=> [fast/warm reboot] kill radv docker before stopping BGP

config/main.py, doc/Command-Reference.md
I've added config commands to add/del syslog servers from the device.
```
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ redis-cli -n 4 keys "*" | grep syslog  -i
SYSLOG_SERVER|100.127.20.21
SYSLOG_SERVER|10.3.145.8
SYSLOG_SERVER|4.4.4.4
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ sudo config syslog add 5.5.5.5
Syslog server 5.5.5.5 added to configuration
Restarting rsyslog-config service...
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ redis-cli -n 4 keys "*" | grep syslog  -i
SYSLOG_SERVER|100.127.20.21
SYSLOG_SERVER|10.3.145.8
SYSLOG_SERVER|4.4.4.4
SYSLOG_SERVER|5.5.5.5
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ sudo config syslog del 5.5.5.5
Syslog server 5.5.5.5 removed …
```
=> [config] Add commands for adding/removing syslog servers

config/main.py
This ensures that the process will get restarted, even if systemd has previously placed the service in the "failed" state, as `systemctl reset-failed <service>` will take the service out of the "failed" state.
Also, no longer print the command names as they are run; instead print a message stating that we are restarting each service.
The commands which currently call this function are `config load_minigraph` and `config reload`
This should address https://github.com/Azure/sonic-buildimage/issues/3244
=> [config] Call 'systemctl reset-failed' before 'systemctl restart' when restarting services

doc/Command-Reference.md
I already committed the change for updating the DHCP Relay Destination IP address but I didn't update the Command-Reference.md
Since I wrote and merged this change:
https://github.com/Azure/sonic-utilities/pull/585
The PR is only to update the documentation.
Just look at the Command-Reference.md.
None
None
-->
=> [Command Reference] Add config commands for DHCP relay destination address

config/main.py, doc/Command-Reference.md
I've added config commands to add/del NTP servers from the device.
```
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ redis-cli -n 4 keys "*" | grep -i ntp 
NTP_SERVER|10.3.149.170
NTP_SERVER|6.6.6.6
NTP_SERVER|10.3.149.171
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ sudo config ntp add 8.8.8.8
NTP server 8.8.8.8 added to configuration
Restarting ntp-config service...
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ redis-cli -n 4 keys "*" | grep -i ntp 
NTP_SERVER|10.3.149.170
NTP_SERVER|8.8.8.8
NTP_SERVER|6.6.6.6
NTP_SERVER|10.3.149.171
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ sudo config ntp del 8.8.8.8
NTP server 8.8.8.8 removed from configuration
Restarting ntp-config …
```
=> [config] Add commands for adding/removing NTP servers

scripts/asic_config_check, scripts/fast-reboot, setup.py
I modified the fast-reboot script to check that certain ASIC configurations haven't changed between the source and destination SONiC image before performing the warm reboot.
Azure/sonic-buildimage#3384 adds the relevant checksums at build time. I wrote a script to fetch these checksums from the filesystem and check that they match. This script is called as a pre-check in the warm reboot script.
I built two SONiC images with the same checksum and verified that warm reboot proceeded normally. I also built a third image with a different checksum and verified that warm reboot was aborted when attempting to boot from one of the other two images.
N/A
**- …
=> [fast-reboot] Check if ASIC config has changed before warm reboot

scripts/neighbor_advertiser
Need to mirror the neighbor solicitation packets - type 135.
=> [neighbor_advertiser]: Change the ICMPv6 type to 135

doc/Command-Reference.md, show/main.py
I added the "show boot" command to the CLI.
I updated the show/main.py file to add the command. 
run "show boot"
None 
```
admin@str-s6000-acs-11:~$ show boot
Current: SONiC-OS-20181130.31
Next: SONiC-OS-20181130.31
Available: 
SONiC-OS-20181130.31
```
=> [show] Add 'show boot' command

scripts/fast-reboot
provide strict option to prevent warm reboot under  certain conditions
- the only condition now is lack of control plane assistant.
run warm reboot with -s but without -c option.
=> [warm/fast reboot] provide strict option to prevent warm reboot under  certain conditions

show/main.py
When management VRF is enabled, the linux command/exe "ntpq" should be called using "cgexec -g l3mdev:mgmt".
"show ntp" is updated for the same.
Result of "show ntp" after enabling management VRF using "config vrf add mgmt" is as follows.
root@sonic:~# show ntp
remote           refid      st t when poll reach   delay   offset  jitter
================================================================
23.92.29.245    .STEP.          16 u    -  256    0    0.000    0.000   0.000
*204.2.134.164   44.24.199.34     3 u   31   64  377  201.063    0.444   0.514
root@sonic:~#
=> updated "show ntp" to use cgexec when management vrf is enabled

scripts/fast-reboot
Added sending of SIGINT signal to all active teamd processes before Fast-Reboot
using pkill utility
Put the changes from this PR to your DUT.
Then use `fast-reboot` on your dut while capturing packets on one of the portchannel member interfaces of DUT
-->
=> [FastReboot]: Send SIGINT to all teamd before stop

config/main.py
Updated method name in the config/main.py file to remove the conflict between the "import syslog" command and the click "syslog" command. 
Changed the click "syslog" group to be "syslog_group" to remove the conflict
These commands will now work again without the conflict: 
config load_minigraph -y
config reload -y
N/A
N/A
This fixes #635 
-->
=> [config] Fix naming conflict between 'config syslog' function and 'syslog' module

scripts/asic_config_check
**What I did**
I edited the ASIC config check script to abort the check if the current image does not have a checksum.
1. Run warm-reboot with the updated check script on a SONiC device that does not contain an asic_config_checksum file.
2. Confirm that warm-reboot proceeds past the pre-check stage.
3. Confirm that the syslog contains messages indicating that there was no checksum found on the current image and that the pre-check is not supported.
=> [warm reboot] Skip ASIC config pre-check if current image does not support it

config/main.py, doc/Command-Reference.md
I have added commands to remove BGP neighbor configuration
Added some new methods to the config/main.py file to support removing BGP neighbor configuration.
```
admin@Test_Device1:~$ show ip bgp summary
BGP router identifier 10.10.1.1, local AS number 65534
RIB entries 1, using 112 bytes of memory
Peers 42, using 191 KiB of memory
Peer groups 1, using 56 bytes of memory
Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
... 
10.10.193.43    4 64521       0       0        0    0    0 never    Idle       
10.10.193.45    4 64522       0       0        0    0    0 never    Idle       
10.10.193.47    4 64523       0       0        0    0    0 never    Idle       
10.106.8.240    4 64524       0 …
```
=> [config] Add commands to remove BGP neighbor configuration

scripts/fast-reboot
In order to maintain the same monitor port across the warm reboot,
exclude the mirror session state database.
=> [warm-reboot]: Do not clean up mirror session state database

config/main.py
* Fixed Asym PFC configuration 
* Added missing argument
1. root@sonic:/home/admin# config interface pfc asymmetric Ethernet0 off
2. root@sonic:/home/admin# config interface pfc asymmetric Ethernet0 on
```bash
root@sonic:/home/admin# config interface Ethernet0 pfc asymmetric off
Usage: config interface [OPTIONS] COMMAND [ARGS]...
Error: No such command "Ethernet0".
root@sonic:/home/admin# config interface pfc asymmetric Ethernet0 off
Usage: config interface pfc asymmetric [OPTIONS] STATUS
Error: Invalid value for "status": invalid choice: Ethernet0. (choose from on, off) …
```
=> Asym PFC configuration fix

scripts/fast-reboot
Reverts Azure/sonic-utilities#633
This change has unexpected side effect causing fast-reboot to have longer data plane down time. Reverting it for now.
=> Revert "[FastReboot]: Send SIGINT to all teamd before stop"

config/main.py
This reverts commit ab153a0a777acf76ed23937735a384fa141b5895.
This change is flagged for 201811 branch by mistake.
=> Revert "Fixed config Asym PFC CLI. (#632)"

config/main.py
The `show` and `sonic-clear` commands accepted `--help` as well as `-h` and `-?` as options to display help, but config only supported `--help`. This standardizes the help options among all three commands.
Resolves #646
=> [config] Add '-h' and '-?' as help options to unify with show/sonic-clear cmds

config/main.py
Port of https://github.com/Azure/sonic-utilities/pull/647 to merge cleanly into 201811 branch
=> [201811][config] Add '-h' and '-?' as help options to unify with show/sonic-clear cmds

scripts/fast-reboot
1. Use SIGUSR2 signal to stop teamd
use pkill
use fast-reboot and check teamd.log output. You must see that USR2 is received.
-->
=> Use SIGUSR2 to stop teamd before fast-reboot

scripts/fast-reboot
Some services are depending on swss and might have been stopped at the
time the loop of docker killing was executed.
Without the change, continuous fast-reboot seems to hit the issue fairly frequently where snmp docker has been stopped when reaching the docker kill loop. And that would cause test to fail.
With the fix, the snmp docker could still be killed already, but test would continue.
=> [warm/fast reboot] some service docker might have been stopped already

config/main.py
Don't start/stop pmon during config reload since pmon is triggered by syncd.
This PR depends on [[Mellanox] Stop pmon ahead of syncd #3505](https://github.com/Azure/sonic-buildimage/pull/3505)
For Mellanox platform, remove pmon from the services_to_stop and service_to_start list.
execute "config reload" and "systemctl restart swss.service" and check whether all dockers start.
-->
=> [Mellanox] Don't start & stop pmon when config reload

acl_loader/main.py
This column helps checking the output monitor port for the mirror
session.
=> [acl_loader]: Add monitor port column in show mirror_session output

scripts/neighbor_advertiser
I added a check to neighbor_advertiser to make sure that the DIPs returned from ferret are not in any of the device's VLANs.
- I added a helper method to query CONFIG_DB for VLAN interfaces and check that a given IP does not fall in that range.
- I used the helper method to check that DIPs returned from ferret did not fall in any of the device's VLANs.
- I added a retry to attempt to get other DIPs from ferret before moving on to the next ferret VIP.
1. Run the script against a response object that contains an IPv4 address that falls inside one of the DUTs VLANs. The script should retry 3 times and then fail.
2. Run the script against a response object that contains an IPv4 address that does not fall inside of the DUTs VLANs. The …
=> [neighbor_advertiser] Verify that DIPs returned from ferret are not in device VLAN

scripts/fast-reboot
Letting teamd quit and send out last handshake cause some unexpected
interaction with orchagent. It appears that orchagent noticed these lag
were removed and start to tear down the LAG on the ASIC side as well.
This would cause the control plane to go down immediately.
Until we have a better solution, revert back to original behavior.
=> [fast reboot] kill teamd docker directly

show/main.py
Properly replace port name with alias in command output. If the device is configured such that any port names happen to be substrings of port aliases (e.g., name  = "Ethernet1", alias = "Ethernet1/1"), alias naming mode would output incorrect aliases (e.g., "Ethernet1/1/1") because it would consider the substring of the alias as a port name.
Previous solution checked for word boundaries (`\b`) on either side of the port name. This did not work properly if there existed a port alias which contained a port name followed by a forwardslash, as the regex considers the forwardslash as a word boundary. Thus, it would get detected as a port name when, in fact, it was actually just a part of an alias name.
This fix will only replace a port name if it is at the start of a line or …
=> [show] Properly replace port name with alias in command output

pfcwd/main.py
Restrict the pfcwd config only to physical ports.
Excluding non-physical in get_all_ports() by matching the port name with "Ethernet".
Create a Port Channel
Configure pfc and start pfcwd on a port (sudo pfcwd start --action drop ports all detection-time 200 --restoration-time 2000)
Stop the pfcwd using (sudo pfcwd stop) -> Leads to crash in syncd as it tries to remove non-existing UC/MC queues for the port channel.
With the fix, no crash was observed. 
NA
NA
-->
=> [pfcwd] Apply pfcwd config only on physical ports

pfcwd/main.py
```
$ sudo pfcwd start_default
$ pfcwd show stats        
QUEUE       STATUS    STORM DETECTED/RESTORED    TX OK/DROP    RX OK/DROP    TX LAST OK/DROP    RX LAST OK/DROP
------------  -----------  -------------------------  ------------  ------------  -----------------  -----------------
Ethernet36:4  operational                        1/1       100/100         0/100            100/100              0/100
Ethernet96:3  operational                        1/1           0/0           0/0                0/0                0/0
Ethernet96:4  operational                        5/5       200/400       100/300              100/0              100/0
```
```
$ sudo pfcwd stop     
$ pfcwd show stats
QUEUE    STATUS    STORM DETECTED/RESTORED    TX OK/DROP    RX OK/DROP    TX LAST OK/DROP    RX LAST …
```
=> pfcwd: show storm status to be 'N/A' when pfcwd is stopped

config/main.py
Implement HLD Azure/SONiC#420
On mlnx dut
```
"VLAN_SUB_INTERFACE": {
"Ethernet64.10": {
"admin_status": "up"
},
"Ethernet64.10|10.0.0.32/31": {},
"Ethernet64.10|FC00::41/126": {}
},
```
```
sudo config interface ip remove Ethernet64.10 10.0.0.32/31
```
```
"VLAN_SUB_INTERFACE": {
"Ethernet64.10": {
"admin_status": "up"
},
"Ethernet64.10|FC00::41/126": {}
},
```
```
sudo config interface ip remove Ethernet64.10 FC00::41/126
```
`VLAN_SUB_INTERFACE` table is removed from CONFIG_DB
```
sudo config interface ip add Ethernet64.10 10.0.0.32/31
```
```
"VLAN_SUB_INTERFACE": {
"Ethernet64.10": {
"admin_status": "up"
},
"Ethernet64.10|10.0.0.32/31": {}
},
```
```
sudo config interface ip add Ethernet64.10 FC00::41/126
```
``` …
```
=> Add sub port interface to `config interface ip add/del`

config/main.py
Implement HLD https://github.com/Azure/SONiC/pull/420
On mlnx dut
alias mode:
```
$ show  interfaces naming_mode
alias
```
```
$ sudo config interface shutdown etp17.10
$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) "admin_status"
2) "down"
$ redis-cli -n 0 hgetall "INTF_TABLE:Ethernet64.10"
1) "admin_status"
2) "down"
```
```
$ sudo config interface startup etp17.10
$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) "admin_status"
2) "up"
$ redis-cli -n 0 hgetall "INTF_TABLE:Ethernet64.10"        
1) "admin_status"
2) "up"
```
default mode:
```
$ show interfaces naming_mode 
default
```
```
$ sudo config interface shutdown Ethernet64.10
$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) …
```
=> Support sub port interface admin status change

scripts/fast-reboot
Reverts Azure/sonic-utilities#683
Issue has been addressed by https://github.com/Azure/sonic-buildimage/pull/3544
=> Revert "[fast reboot] kill teamd docker directly"

show/main.py
Fixes #685 
Also included the bgp columns that were missed in the output
Updated the /usr/lib/python2.7/dist-packages/show/main.py with the changes. 
After the fix,
root@sonic:~# show ipv6 interface
Interface        IPv6 address/mask                   Admin/Oper    BGP Neighbor    Neighbor IP
---------------  ----------------------------------  ------------  --------------  -------------
Bridge           fe80::c7d:22ff:fe77:4702%Bridge/64  up/down       N/A             N/A
PortChannel0001  fc00::71/126                        down/down     ARISTA01T1      fc00::72
PortChannel0002  fc00::75/126                        down/down     ARISTA02T1      fc00::76
PortChannel0003  fc00::79/126                        down/down     ARISTA03T1      fc00::7a
PortChannel0004 …
=> Address the 'show ipv6 interface' crash and include the missed bgp columns

config/main.py, doc/Command-Reference.md
added new command **change-hostname** to config CLI so that the user can change the hostname on a SONiC device without traffic being impacted.
update **"hostname"** key to the **"DEVICE_METADATA|localhost"** field in config DB using sonic-cfggen and restart the **hostname-config** service.
> 
changed the hostname from **csw06** to **csw06-sonic**
```
admin@csw06:~$ sudo config change-hostname csw06-sonic
Running command: service hostname-config restart
Please note loaded setting will be lost after system reboot. To preserve setting, run config save.
admin@csw06:~$ sudo config save -y
Running command: /usr/local/bin/sonic-cfggen -d --print-data > /etc/sonic/config_db.json …
```
=> [config]: Add hostname command to config CLI

scripts/intfstat, scripts/portstat
The json format may come in handy. Sadly found it's broken at the moment.
Fixed it.
```
$ portstat -j
$ intfstat -j
```
```
admin@dev-r-vrt-233-010:~$ portstat -j
File "/usr/bin/portstat", line 311, in <module>
main()
File "/usr/bin/portstat", line 302, in main
portstat.cnstat_diff_print(cnstat_dict, {}, use_json, print_all)
File "/usr/bin/portstat", line 187, in cnstat_diff_print
print self.table_as_json(table, print_all)
AttributeError: 'Portstat' object has no attribute 'table_as_json'
```
**- New command output (if the output of a command-line utility has …
=> [portstat,intfstat] fix table_as_json

scripts/neighbor_advertiser
ACL table names varies on different platforms.
The current assumption is that the name would contain either
EVERFLOW or EVERFLOWV6.
Thus a function find_mirror_table_name is added to find the exact
names for both the v4 and v6 mirror table names.
=> [neighbor_advertiser]: Adapt to different mirror ACL table names

scripts/generate_dump
Fixes the bad minute error while reading /etc/cron.d/logrotate:
The following are the two routines used in the scripts/generate_dump script. 
disable_logrotate() {
sed -i '/logrotate/s/^/#/g' /etc/cron.d/logrotate
}
enable_logrotate() {
sed -i '/logrotate/s/^#*//g' /etc/cron.d/logrotate
}
When we run 'show techsupport', it basically disables the log rotate and collect all the logs, and enable them back again.  
Content of cron.d/logrotate file before the 'show techsupport ' execution:
root@sonic:/home/admin# cat /etc/cron.d/logrotate
*/10 * * * * root /usr/bin/pkill -9 logrotate > /dev/null 2>&1; /usr/sbin/logrotate /etc/logrotate.conf > /dev/null 2>&1
Content of cron.d/logrotate file after the 'show techsupport ' execution:
root@sonic:/home/admin# cat …
=> [generate_dump] Make regex more specific for disabling/enabling logrotate

doc/Command-Reference.md
- Unify style and Markdown formatting
- Fix organization of recently-added commands
- Modify heading sizes
- Fix spelling, grammar and other errors
- Fix bad links
- Add 'sonic_installer cleanup' command
- Add 'sudo' to sonic_installer command examples
=> [Command Reference] Unify style and formatting; Fix organization; Other fixes

scripts/fast-reboot
After killing bgpd, the execution has passed point of safe return. We need to proceed and ignore any trivial failures.
=> [warm/fast reboot] continue executing when killing docker failed

scripts/neighbor_advertiser
The sleep(3) is to ensure that orchagent could execute tasks by the
correct sequence so that mirror session and ACL rules could be
successfully created/removed.
=> [neighbor_advertiser]: Add sleep in setting mirror session and ACL rules

config/main.py
Manually trigger the flush command to remove the deprecated
neighbors that are associated with the removed router interface.
=> [config]: Flush the neighbor table when removing the router interface

config/main.py, show/main.py
CLI commands for configuring few parameters that are required in snmpd.conf.
1) "snmpd" daemon (snmp agent) shall use this configured IP address and VRF to listen on the particular IP address on that particular VRF.
2) "snmpd" daemon shall use the configured TRAP IP address and VRF to send the TRAPs to those servers connected in that particular VRF.
Requried back end snmpd patches are already applied in sonic-buildimage to handle this additional "VRF" configuration.
**Configuration**  
root@sonic:# config vrf add mgmt
root@sonic:# config snmpagentaddress add 100.104.45.9 -v mgmt
root@sonic:# config snmptrap modify 3 100.94.212.7 -v mgmt
root@sonic:# cat /etc/sonic/snmp.yml
snmp_rocommunity: public
snmp_location: public
v1_trap_dest: NotConfigured
v2_trap_dest: NotConfigured
v3_trap_dest: …
=> Management vrf snmp cli support

config/main.py, show/main.py, sonic_installer/main.py
**What I did?**
* Adding CLI to configure sFlow globally or per interface
* Adding CLI to show sFlow settings globally or per interface
**How I did it?**
Added logic into config/main.py to add sFlow related information supplied by the user through a CLI. Also added logic into show/main.py to query configDB to show sFlow related information.
**How to verify it?**
Manually ran the new CLIs and verified it with the corresponding show command. Also use redis-cli command to verify entries inside the configDB.
**Additional Information**
Please **DO NOT MERGE** until these PRs are merged:
[https://github.com/Azure/sonic-swss-common/pull/299](https://github.com/Azure/sonic-swss-common/pull/299)
[https://github.com/Azure/sonic-swss/pull/1011](https://github.com/Azure/sonic-swss/pull/1011) …
=> sonic-utilities: Add support for sFlow

scripts/intfstat, scripts/portstat, utilities_common/__init__.py
Reverted #508 
Reason: Assumption that HW counters are cleared on reboot is wrong.
```
show interface counters 
show interface counters rif
portstat
portstat -c
intfstat
```
=> Revert "show BPS, PPS, UTIL rates w/o previous clear (#508)"

scripts/configlet
Delete of non-existing table/keys is a no-op, hence can be ignored.
=> Make configlet application script idempotent for updates.

config/main.py, show/main.py
Add a knob to turn on/off the BGP EOIU pulling when BGP warm restart.  By default, it's off. 
This is to address review comments for https://github.com/Azure/sonic-buildimage/pull/2823
Other related PR
https://github.com/Azure/sonic-buildimage/pull/3489
https://github.com/Azure/sonic-buildimage/pull/2823
https://github.com/Azure/sonic-swss-common/pull/273
https://github.com/Azure/sonic-swss/pull/856
<pre>
root@ASW-7001:~# config warm_restart bgp_eoiu true
root@ASW-7001:~# show warm_restart config 
name    enable    timer_name    timer_duration    eoiu_enable
------  --------  ------------  ----------------  -------------
bgp     false     NULL          NULL              true
root@ASW-7001:~# config warm_restart bgp_eoiu false
root@ASW-7001:~# show warm_restart config 
name    enable …
=> Add an on/off knob for BGP EOIU pulling on warm restart

config/main.py
Disable pfcwd for M0 devices
Get the device type from the minigraph and use that for comparison
- Modified device type in the minigraph to 'MgmtToRRouter' and verified that pfcwd is not started when load_minigraph is executed.
- For other types, pfcwd was started when load_minigraph was executed
=> Do not start pfcwd for M0 devices

config/main.py
Signed-off-by: wangshengjun <wangshengjun@asterfusion.com>
When adding vlan through the CLI,  the corresponding api 'add_vlan' doesn't check the range of vid which input by user. If we add a invalid vlan id (such as 0) and configure a ip address for the vlan interface, the 'vlanmgrd' will crash.The crash log as follows:
Sep  9 06:37:11.166624 sonic NOTICE swss#vlanmgrd: :- main: --- Starting vlanmgrd ---
Sep  9 06:37:11.258563 sonic NOTICE swss#vlanmgrd: :- main: starting main loop
Sep  9 06:37:11.289983 sonic ERR swss#vlanmgrd: :- exec: /bin/bash -c "/sbin/bridge vlan add vid 0 dev Bridge self && /sbin/ip link add link Bridge up name Vlan0 address 52:54:00:12:34:56 type vlan id 0": Success
Sep  9 06:37:11.289983 sonic ERR swss#vlanmgrd: :- main: Runtime error: /bin/bash …
=> [config]: add the vid range check for creating vlan.

scripts/db_migrator.py
commit fe4446a4808bc98ca2b24b0a9afe822aaa50a7ce fix loopback vrf migration.
but the commit does not enable db migration from version 1_0_1.
Now, bump version 1_0_2 and allow db fix from 1_0_1
=> [bugfix]: allow loopback vrf migration from version 1_0_1

scripts/neighbor_advertiser
Added a call to the HTTPS endpoint for Ferret instances.
Since some Ferret instances may still be using HTTP, I added a new function that attempts to call the new HTTPS endpoint before failing over to HTTP.
1. Attempt to run neighbor_advertiser against a ferret VIP that supports HTTPS. The script should run successfully.
2. Attempt to run neighbor_advertiser against a ferret VIP that does not currently support HTTP. The script should print info messages to the syslog indicating that the HTTPS endpoint was not found, and then succeed using HTTP.
=> [neighbor_advertiser] Adds initial support for HTTPS to neighbor advertiser

show/main.py
Added 'show features' command to show status of an optional feature
run 'show features'
```
Feature    Status
---------  --------
telemetry  enabled
```
-->
=> [show] Add 'features' subcommand to display status for optional features

config/main.py, show/main.py
Submit VRF CLI according to vrf HLD #392
Pass the test on nephos lab
```
Interface    IPv4 address/mask    Admin/Oper
-----------  -------------------  ------------
Ethernet0    1.1.1.1/24           up/up
show ipv6 interfaces
Interface    IPv6 address/mask                       Admin/Oper
-----------  --------------------------------------  ------------
Ethernet0    fe80::6eec:5aff:fe08:164b%Ethernet0/64  up/up
```
```
Interface    Master    IPv4 address/mask    Admin/Oper
-----------  --------  -------------------  ------------ …
```
=> [VRF]: submit vrf CLI #392 

config/main.py
* There is existing get_redis_client() API to obtain redis_client, all application should use it.
* multiDB changes redesign interface class get_redis_client() implementation, internal private data redis_clients[] indexed by db_id when updating sonic-py-swsssdk, hence all application should use API to obtain redis-client for safety. 
* did a global search on all codes , looks only this two are missing to use get API, all other places are already modified earlier.
* after this changes, we can move the head for sonic-py-swsssdk without error when reloading config (minigraph) 
=> [multiDB]: all application should use API to get redis_client

scripts/configlet
Currently it misses the case where data for a new key is empty.
=> Fix a bug in idempotent check.

config/main.py
added command to configure feature status 
By adding in main.py 
config feature_status name value
=> [config] Add 'feature' subcommand

scripts/neighbor_advertiser
When connecting https endpoint failed, we need to try http endpoint.
Therefore we need to catch all exceptions.
warm-reboot-control-plane-assistant test. Also tested with https endpoint success code and timeout.
=> [neighbor advertiser] catch all exceptions while trying https endpoint

sonic_installer/main.py
Used "config-setup backup" command to take a backup copy of current SONiC configuration.
Refer to Azure/SONiC#433  and Azure/sonic-buildimage#3227 for more information
Added skip_migration option to "sonic_installer install" command to allow user to install an image
with factory default configuration. 
Replaced cp commands with "config-setup backup" command which performs same cp commands and also executes and user defined migration hook scripts.
Added a new command line option for install command.
Use sonic_installer install command
=> Use config-setup infrastructure to take backup of SONiC configuration

scripts/neighbor_advertiser
raise exception when http endpoint return failure to match the HTTPS handling flow.
=> [neighbor advertiser] raise exception when http endpoint return failure

scripts/fast-reboot
Added support for calling a platform specific plugin in fastboot, warmboot
Changes applied to 'scripts/fast-reboot'
Write a platform plugin script and execute fast-reboot command
Plugin script will be executed and then reboot will be invoked
=> Platform plugin for Fast-reboot/warm-reboot 

scripts/fast-reboot
Once any critical service is shutdown (radv/swss/syncd), we have to
commit to the reboot. Failing in the middle will leave the system in
bad state.
=> [fast/warm reboot] ignore errors after shutting down critical service(s)

scripts/syseeprom-to-json, setup.py
Add utility to translate text output of syseeprom dump into JSON, for
consumption by new management (1.0) command.
Signed-off-by: Howard Persh <hpersh@yahoo.com>
=> [scripts] Adds support for management (1.0) commands

scripts/intfstat
Fixes #749 
Additional check for counter snapshot folder existance.
1. intfstat -D
2. intfstat -D
File "/usr/bin/intfstat", line 346, in <module>
main()
File "/usr/bin/intfstat", line 272, in main
for file in os.listdir(cnstat_dir):
OSError: [Errno 2] No such file or directory: '/tmp/intfstat-0'
=> [intfstat] fix --delete-all fail when counters dump does not exist

doc/Command-Reference.md
Added the following config and show commands in Command Reference Document.
show mgmt-vrf
show mgmt-vrf
show management_interface address
show snmpagentaddress
show snmptrap
config vrf add mgmt
config vrf del mgmt
config snmpagentaddress add
config snmpagentaddress del
config snmptrap modify
config snmptrap del
=> Add VRF-related commands to Command Reference Document

scripts/portstat
Fixes #742 
Looks like after the revert wrong header was used for the table.
=> [portstat] fix header used

config/main.py
When user enables sflow, (since it is disabled by default), start the sflow docker service.
Note that this is a workaround until the "features" infrastructure can be fully utilized.
Check if the sflow service is running and if not active, enable and restart the service.
Check that sflow is disabled by default (with https://github.com/Azure/sonic-buildimage/pull/3930).
Perform "config sflow enable" and check that the sflow docker comes up.
Check the logs and the "show sflow" outputs.
=> On sflow enable, start the docker since it is disabled by default

scripts/dropconfig
I fixed the if-check for devices that do not publish any drop counter capabilities to state DB.
I added a return inside the if-check so that the function will stop if no capabilities are found.
I ran the `show dropcounters capabilities` command immediately after boot to ensure that the CAPABILITIES table would be empty, triggering the if-check.
```
admin@sonic:~$ show dropcounters capabilities
File "/usr/bin/dropconfig", line 414, in <module>
main()
File "/usr/bin/dropconfig", line 409, in main
dconfig.print_device_capabilities()
File "/usr/bin/dropconfig", line 97, …
```
=> [dropconfig] Clean-up error output for devices that do not support drop counters

config/main.py, doc/Command-Reference.md, scripts/dropconfig, scripts/intfstat, scripts/portstat, scripts/syseeprom-to-json, scripts/update_json.py, setup.py, show/bgp_frr_v6.py, show/bgp_quagga_v4.py, show/bgp_quagga_v6.py, show/main.py, sonic_installer/main.py
[sonic_installer] Adding support for ARM by introducing bootloader type 
grub vs uboot
For uboot fw_setenv/fw_printenv commands are utilized here
fw_env.cfg config needs to be updated per platform
[portstat] division by zero error fix when speed is < 1000 (1G)
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [sonic_installer] Adding support for ARM Uboot firmware and portstat fix

show/main.py
This is a bug fix for PR: 
https://github.com/Azure/sonic-utilities/pull/754
changing ipaddr module to ipaddress
=> ipaddr module to ipaddress

scripts/fdbshow, scripts/nbrshow
In release branches prior to 201911, FDB or ARP learnt on VLAN interface LAG port will cause nothing to appear in the "show arp" or "show mac" output because there existed no OID->interface name never had the mappings for LAG interface.
This issue has since been fixed in master (and 201911). However, making this change in master is not harmful and will prevent a regression from causing no output to be displayed for the interface name in the future.
=> [fdbshow][nbrshow] Print interface OID in lieu of name if there is no OID->interface name mapping

config/main.py, scripts/generate_dump, scripts/reboot, scripts/sonic-kdump-config, setup.py, show/main.py
In the event of a kernel crash, we need to gather as much information as possible to understand and identify the root cause of the crash. Currently, the kernel does not provide much information, which make kernel crash investigation difficult and time consuming.
Fortunately, there is a way in the kernel to provide more information in the case of a kernel crash. kdump is a feature of the Linux kernel that creates crash dumps in the event of a kernel crash. This PR will add kernel kdump support. Please note that there is another PR in sonic-utilities which is also needed:
https://github.com/Azure/sonic-buildimage/pull/3722
An extension to the CLI utilities config and show is provided to configure and manage kdump:
- view kdump status (enabled/disabled, active, configuration, stored crash …
=> kdump support

acl_loader/main.py
If ACL table name contains the substring "v6", set the EtherType of the rule to V6, otherwise set to V4.
=> [acl-loader] Use V6 EtherType for IPv6 ACL rule

scripts/dropconfig, sonic-utilities-tests/mock_tables/state_db.json
- Remove prefix-trimming from drop reason capability query
- Remove prefix-trimming from create/add safety checks
I removed some conditions from the drop counter CLI that was handling the presence of "SAI_IN/OUT_DROP_REASON_" in State DB.
**- Why I did it**
A change was made in SWSS that removed the SAI prefixes from the database, making the prefix removal unnecessary in the CLI.
The CLI tests have been updated to reflect this change. Additionally, you can load the updated script onto a device running the SWSS changes and verify that the behavior is unchanged.
Depends on: Azure/sonic-swss#1173
=> [dropconfig] Move prefix-handling from CLI to orchagent

scripts/fast-reboot
watchdog log message mentions the right reboot type
=> [fast/warm reboot] watchdog log message mentions the right reboot type

scripts/generate_dump
dump a few more DB, config db, state db, flex counter db in generate dump.
also do not zip some bgp table since the whole tar file is gziped.
=> [showtech]: dump a few more DB in generate dump

scripts/decode-syseeprom
Fixed show platform syseeprom on vs platform
add kvm to platforms which do not support syseeprom db and check for the 'read_syseeprom_db' method availibilty to avoid same issue on other platforms
Verify output of show platform syseeprom shell command
root@vlab-01:/home/admin# show platform syseeprom 
File "/usr/bin/decode-syseeprom", line 172, in <module>
exit(main())
File "/usr/bin/decode-syseeprom", line 61, in main
run(t, opts, args, support_eeprom_db)
File "/usr/bin/decode-syseeprom", line 88, in run
err = target.read_eeprom_db()
AttributeError: board instance has no attribute 'read_eeprom_db'
**- New command …
=> Fix 'show platform eeprom' on virtual switch

show/main.py
Since we introduced the auto-restart feature for each container, we need add a show subcommand to display the current status of auto-restart feature for all containers or a specific container.
We define a function named autorestart to show the status of this features. This function will accept an option parameter which is the container name. If this parameter is not specified, this function will by default show the status of all containers. Otherwise it will show the status of specific container.
We can run the command **show container feature autorestart** or **show container feature autorestart container_name** to verify.
=> [show] Add subcommand to display the status of auto-restart feature for each container

config/main.py
- What I did
Since we introduced the auto-restart feature for each container, we need add a config subcommand to change the current status (enabled/disabled) of auto-restart feature for a specific container.
- How I did it
We define a function named autorestart to change the status of a container. This function will accept two parameters which are the container name and new status. If one of parameters is not specified, this function will show the information and then exit.
We can run the command **config container feature autorestart container_name autorestart_status**.
=> [config] Add subcommand to configure the status of auto-restart feature for each container

doc/Command-Reference.md
I added two sections in the Command-Reference.md to introduce how should we use the auto-restart
feature for all containers.
=> [Command Reference] Document CLI commands related to container auto-restart feature

config/main.py
I modified the function reload() such that it will load the configuration files config_db.json and init_cfg.json into Config_DB.
=> [config/main.py] Modify reload() function to load configuration from init_cfg.json implicitly

config/main.py, doc/Command-Reference.md, scripts/portconfig
Implemented config interface mtu subcommand.
1. Implemented mtu() method in config/main.py for parsing MTU parameter.
2. Updated scripts/portconfig to enable correct hadling of MTU value.
1. Use config interface mtu command to set MTU on any Ethernet interface.
2. Use show interfaces status to whether the MTU value of the port has changed in the database.
3. Use ifconfig to check if the MTU change has been correcly handled by a subscriber.
**- Usage example**
`admin@sonic:~$ sudo config interface mtu Ethernet64 1500`
=> [config] Add 'config interface mtu' command

config/main.py
Do below steps to recreate the issue:
1. config vlan add 700
2. config vlan member add 700 Ethernet56
3. config vlan dhcp_relay add 700 155.1.24.1
4. config vlan member del 700 Ethernet56
Error message seen while trying to remove the member from vlan:
root@sonic:/home/admin# config vlan member del 700 Ethernet56
Usage: config vlan member del [OPTIONS] <vid> <interface_name>
Error: Ethernet56 is not a member of Vlan700
Config_DB:
After configuring Vlan with members (Step 2):
"VLAN": {
"Vlan700": {
"members": [
"Ethernet56"
]}}
After configuring dhcp relay on Vlan (Step 3), the vlan members are missing.
"VLAN": {
"Vlan700": {
"dhcp_servers": [
"155.1.24.1"
]}}
Fix:
Get all the entries from the VLAN and delete only the dhcp_servers if all the servers are deleted. And …
=> Fix for dhcp_relay deletion on a VLAN

doc/Command-Reference.md
- Remove prompts and `sudo` from usage statements
- Ensure all examples have prompts
- Change all existing prompts to `admin@sonic:~$`
- Add `sudo` to all `config` commands
=> [Command-Reference.md] Unify Usage statments and Examples (including sample prompts)

config/nat.py, scripts/natclear, scripts/natshow
Added multi-db changes for NAT scripts.
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>
=> Multi-Db changes for NAT feature.

scripts/reboot
Platform reboot tool could fail if the platform driver didn't load properly. In this case, a reboot is required to recover the device. We need to make sure the reboot tool is robust.
=> [reboot] make sure the reboot happens even if platform reboot failed

config/main.py, scripts/fast-reboot
Signed-off-by: shine.chen <shine.chen@nephosinc.com>
add support for MCLAG
Add iccpd(mclag daemon) item on restart_service and stop service.
issue docker kill iccpd when fast-reboot
Tested on nephos lab
-->
=> add support for MCLAG

crm/main.py, scripts/aclshow, scripts/fast-reboot, scripts/generate_dump, scripts/route_check_test.sh
* replace redis-cli/redis-dump with sonic-db-cli/sonic-db-dump
* depends on https://github.com/Azure/sonic-py-swsssdk/pull/62, need sonic-db-dump command
=> [MultiDB] sonic-utilities - replace redis-cli/redis-dump with sonic-db-cli/sonic-db-dump

fwutil/lib.py
* Fixed CLI endless wait when installing FW from URL and network goes down
* Added default socket 30 sec timeout
1. Connect to switch via serial console
2. Start FW installation form URL
3. Shutdown management interface
```bash
root@sonic:/home/admin# fwutil install chassis component BIOS fw http://sonic-server/fwutil/bios/x86_64-mlnx_msn3800-r0_latest/0ACLH004.rom
New firmware will be installed, continue? [y/N]: y
Downloading firmware:
[#-------------------------------------------------------------------]    2%
Error: timed out. Aborting...
Aborted!
root@sonic:/home/admin# cat /var/log/syslog | grep fwutil
Feb 25 15:06:20.718495 sonic INFO fwutil: Firmware download started: …
```
=> [fwutil]: Set default socket timeout for FW download to 30 sec

scripts/reboot, scripts/sonic-kdump-config
This change add the kdump support for Aboot platform, where differently "/host/image-%s/kernel-cmdline" is used to store the kernel cmdline parameters for kdump.
=> [arista] Add kdump support for Aboot platforms

doc/Command-Reference.md
1. Add command description for show platform fan
2. Add command description for show platform temperature
Verify it by preview the markdown document.
=> [Mellanox] add document for thermal control related cli

scripts/intfutil
This is not an issue with normal and correct configuration. The
issue was exposed when there is an incorrect configuration, e.g.
contain wrong port names. These wrong port names will still get
populated to the app_db but will not have speed associated.
Lack of speed entry will cause "show interface status" to throw
exception.
Without change, when speed is not available:
admin@str-dcfx-t1-2-03:~$ show interfaces status
File "/usr/bin/intfutil", line 424, in <module>
main(sys.argv[1:])
File "/usr/bin/intfutil", line 417, in main
interface_stat = IntfStatus(intf_name)
File "/usr/bin/intfutil", line 345, in __init__
self.portchannel_speed_dict = …
=> [intfutil] set speed to 0 when interface speed is not available

scripts/intfutil
This is not an issue with normal and correct configuration. The
issue was exposed when there is an incorrect configuration, e.g.
contain wrong port names. These wrong port names will still get
populated to the app_db but will not have speed associated.
Lack of speed entry will cause "show interface status" to throw
exception.
Without change, when speed is not available:
admin@str-dcfx-t1-2-03:~$ show interfaces status
File "/usr/bin/intfutil", line 424, in
main(sys.argv[1:])
File "/usr/bin/intfutil", line 417, in main
interface_stat = IntfStatus(intf_name)
File "/usr/bin/intfutil", line 345, in init
self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, …
=> [201811][intfutil] set speed to 0 when interface speed is not available

sonic_installer/main.py
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [sonic_installer] Enable ARM64 arch

config/main.py, pfcwd/main.py
Starting click 7.0. The default behavior of a command with under
scores will be replace with dashes.
this is to address the above default behavior change, so that
the command remains the same.
more details can be found:
https://github.com/pallets/click/issues/1123
tested for under current click and click 7.0
under buster
```
admin@vlab-01:/$ sudo config load
load              load_mgmt_config  load_minigraph    
admin@vlab-01:/$ sudo config load
```
=> explicitly specify command with underscores

scripts/decode-syseeprom
Fixes: #828 
For some platforms which implement the eeprom plugin by inheriting from TlvInfoDecoder, the line
`t.getattr('read_eeprom_db', None) == None:`
results in an error:
`AttributeError: 'board' object has no attribute 'getattr'`
The cause for that is that TlvInfoDecoder inherits from `object`, and looks like for object and derived classes there is no `__getattr__`.
```
sudo decode-syseeprom
File "/usr/bin/decode-syseeprom", line 175, in <module>
exit(main())
File "/usr/bin/decode-syseeprom", line 58, in main
or t.getattr('read_eeprom_db', None) == None: …
```
=> [decode-syseeprom] fix getattribute check for some platforms

scripts/fast-reboot
After the change in master branch updating SAI from 3.5.3.1m-25 to 3.7.3.2, we always found kernel panic after running fast-reboot command in testing SONiC with traffic. In the up path of fast-reboot, we can find warning messages like "unhandled irq 16 error" before kernel panic, which implies that some components are not properly closed in the down path. 
This fix will unload certain kernel modules by stopping opennsl before fast-reboot, which is suggested by BRCM. 
Note that another part of the fix is to add 'ExecStop=-/etc/init.d/opennsl-modules stop' to sonic-buildimage:platform/broadcom/saibcm-modules/systemd/opennsl-modules.service, which will be included in another pull request.
**- Previous command output (if the output of …
=> [fast-reboot] Fix kernel panic related to irq after fast-reboot

config/main.py, scripts/fast-reboot
Reverts Azure/sonic-utilities#453
=> Revert "add support for MCLAG"

config/main.py
Add `sflow` to _reset_failed_services in order to avoid errors `Job for sflow.service failed` when executing `config reload` or `config load_minigraph`
=> [config]Add sflow to _reset_failed_services

doc/Command-Reference.md, fwutil/lib.py, fwutil/log.py, fwutil/main.py
This PR contains some improvements which are intended to fix a several corner cases when FW binaries and `platform_components.json` configuration file were not provided by user during SONiC image build.
In this case it is impossible to manually made any changes in configuration files or update binaries: `fwutil` will always use the original versions which exist in squashed filesystem.
* Updated the way `fwutil` mounts next image filesystem: squashfs -> overlay
* Updated command line reference: current/next image update notes
* N/A
1. Update FW binaries and `platform_components.json`
2. Update platform FW using next image:
```bash
fwutil update --image=next
```
**- Previous command output (if the output of a command-line utility …
=> [fwutil]: Use overlay driver when mounting next image filesystem

config/main.py
Add validity check for the interface.
If the interface is L3 (has an IP) than it is impossible to add it to a vlan group.
Check if the interface is L3, if yes, do not add it to the vlan group and print a proper msg.
Try to add a L3 interface to a vlan group.
No output.
Ethernet# is a L3 interface!
=> Fix for adding L3 interface to Vlan group

fwutil/lib.py
This PR contains a fix for component table layout
in case chassis/module has more than one component
* Fixed component table layout
* N/A
1. Show platform component status
```bash
show platform firmware
```
2. Run platform component automatic update
```bash
config platform firmware update
```
```bash
root@sonic:/home/admin# fwutil update
Error: ''. Aborting...
Aborted!
```
```bash
root@sonic:/home/admin# fwutil show status
Chassis                 Module    Component    Version                  Description …
```
=> [fwutil]: Fix component table layout

show/main.py
When mgmt vrf is configured,  "show ntp" checks Linux version to determine if to use
```
- cgexec -g l3mdev:mgmt ntpq -p -n --> for 4.9.0
- ip vrf exec mgmt ntpq -p -n  ---> for 4.9.0+
```
changes in show/main.py to get linux version from os.uname() and then compare with 4.9.0
```
on 4.19.0
//////////////////////
root@sonic:/usr/lib/python2.7/dist-packages/show# show ntp
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*10.11.0.1       10.14.2.1        3 u    -   64    1    0.220  484.401   0.074
10.11.0.2       10.14.2.1        3 u    1   64    1    0.258  481.733   0.206
root@sonic:/usr/lib/python2.7/dist-packages/show# uname …
```
=> support "show ntp" with mgmt vrf based on linux os version

scripts/fanshow, scripts/tempershow
1. Display command output "show platform fan" and "show platform temperature" in natural order
2. Simplify the header of "show platform temperature"
1. Use natsort.natsorted instead of python default sort
2. Change header if "show platform temperature"
Manually verified.
```
root@r-qa-sw-eth-2037:/home/admin# show platform temperature 
NAME    Temperature    High Threshold    Low Threshold    Critical High Threshold    Critical Low Threshold    Warning Status          Timestamp
----------------------  -------------  ----------------  ---------------  -------------------------  ------------------------  ----------------  -----------------
Ambient …
```
=> [Mellanox] Fix thermal control issue: use natural sort for fan status and thermal status

config/main.py
For multi-asic platform, there can be multiple instances of some systemd services. currently config reload CLI stops and restarts only single instance of systemd service. 
Modified stop/reset failed-status and restart system services function to perform action on multiple instances of systemd services.
1. Read plaform/asic.conf file to get the number of ASICs for a platform.
2. Get the services which are multiple instances from generated_services.conf
3. For single ASIC platform, continue to stop and restart services as it is done today.
4. For multiple ASIC platform, stop and restart each instance for multi-instance service. stop and restart of single instance will be done the same way for single and multi-asic platforms.
Bring …
=> [multi-asic]: Update reload of systemd services to support multi-asic platforms

scripts/watermarkstat
Fix the bug where the unicast/multicast queue watermark display was incorrect
Calculate the header list dynamically for PG and queue display
Display the correct queue numbers in the output instead of always starting the index from 0
Calculate the display position relative to the starting index
The watermarkstat will now display information for all the queues and header will contain the correct queue numbers
For a system with 10 unicast queues where the starting queue index is 0
```
Egress shared pool occupancy per unicast queue:
Port    UC0    UC1    UC2    UC3    UC4    UC5    UC6    UC7
----------- …
```
=> [watermarkstat] Fix issue of fields overwritten before display

config/main.py, debug/main.py, pddf_fanutil/main.py, pddf_psuutil/main.py, pddf_thermalutil/main.py, pfcwd/main.py, show/main.py, sonic_installer/main.py, undebug/main.py
Starting with Click 7.0, the default behavior of a command with underscores will be to replace with dashes.
This is to address the above default behavior change, so that the commands remain the same, extending the work done in https://github.com/Azure/sonic-utilities/pull/846 to all Click-based SONiC command line utilities.
Resolves https://github.com/Azure/sonic-utilities/issues/847
More details can be found here: https://github.com/pallets/click/issues/1123
For new subcommands which haven't been included in a release branch yet, use hyphens, as this will be the direction we move in the future. I have also opened an issue to track the eventual transition: https://github.com/Azure/sonic-utilities/issues/853
=> Explicitly specify command names with underscores (continued)

scripts/watermarkstat
This is for #862 which cannot be cleanly cherry-picked 
Fix the bug where the unicast/multicast queue watermark display was incorrect
Calculate the header list dynamically for PG and queue display
Display the correct queue numbers in the output instead of always starting the index from 0
Calculate the display position relative to the starting index
The watermarkstat will now display information for all the queues and header will contain the correct queue numbers
For a system with 10 unicast queues where the starting queue index is 0
```
Egress shared pool occupancy per unicast queue:
Port    UC0 …
```
=> [201811] [watermarkstat] Fix issue of fields overwritten before display

pfcwd/main.py
- What I did
The feature allows setting 'detection_time', 'restoration_time' and 'pollling_interval' PFCWD to an interface. The 'pollling_interval' must be lower than 'detection_time' and 'restoration_time'.
The fix is checking if there is a lower value of 'detection_time' or 'restoration_time' than the 'pollling_interval' value entered by the user in config DB, if yes exit with error code 1.
- How I did it
Checking the config DB for interfaces PFCWD values.
Try adding 'pollling_interval' greater than one of the values of PFCWD interfaces.
- Previous command output (if the output of a command-line utility has changed)
No Output.
- New command output (if the output of a command-line utility has changed)
unable to use polling_interval = #ms, value is bigger or equal to …
=> Fixes bug for PFCWD feature parameters

config/main.py, debug/main.py, pddf_fanutil/main.py, pddf_psuutil/main.py, pfcwd/main.py, show/main.py, sonic_installer/main.py, undebug/main.py
Backport of https://github.com/Azure/sonic-utilities/pull/852 to the 201911 branch
Starting with Click 7.0, the default behavior of a command with underscores will be to replace with dashes.
This is to address the above default behavior change, so that the commands remain the same, extending the work done in https://github.com/Azure/sonic-utilities/pull/846 to all Click-based SONiC command line utilities.
Resolves https://github.com/Azure/sonic-utilities/issues/847
More details can be found here: https://github.com/pallets/click/issues/1123
For new subcommands which haven't been included in a release branch yet, use hyphens, as this will be the direction we move in the future. I have also opened an issue to track the eventual transition: https://github.com/Azure/sonic-utilities/issues/853
=> [201911] Explicitly specify command names with underscores (continued)

scripts/generate_dump
- What I did
Add docker to 'show techsupport' command.
- How I did it
Created a new file with the docker information.
Run 'show techsupport' command and see the new file.
- Previous command output (if the output of a command-line utility has changed)
No Output
- New command output (if the output of a command-line utility has changed)
No Output
=> Add docker to 'show techsupport' command

scripts/generate_dump
**What I did**
Add platform options to 'show techsupport' command.
**How I did it**
Created a new file with the platform information.
each platform element information begins with the appropriate 'show platform #' command.
Run 'show techsupport' command and see the new file.
**Previous command output (if the output of a command-line utility has changed)**
No Output
**New command output (if the output of a command-line utility has changed)**
No Output
=> Add platform options to 'show techsupport' command

doc/Command-Reference.md
* Added documentation regarding CPLD update on Mellanox platforms
* N/A
* N/A
* N/A
* N/A
=> [fwutil]: Update documentation: CPLD update on Mellanox platforms

config/main.py
Implement a config process level lock.
Changes:
1.) Implement a class, which uses hsetnx for lock.
2.) lock is expired within timeout period or will be released by owner.
3.) After -y prompt, lock is reacquired, because timer could have expired,
before user enters yes.
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
command such as port breakout interect with DB 3 times:
1.) Read Config DB,
---Processing---
2.) Delete Ports
---Processing---
3.) Add Ports.
Here we need to take the lock before step one and then have to release the lock after step three. If we take the lock only while interacting with DB then we have to take lock three times in above situation and that also doesn't solve the problem, because some process can update the DB in …
=> [config] Implement a process level lock

show/bgp_frr_v4.py, show/main.py
… file for FRR routing stack.
I created new file bgp_frr_v4.py for the FRR routing-stack and changed the code to use this file instead of the pass through to vtysh for "show bgp".  This now requires the use of "show ip bgp" like the bgp_quagga_v4.py file and which is standardized on most networking vendors. 
I added the file bgp_frr_v4.py in the same directory as the bgp_quagga_v4.py file and updated the main.py for the show commands to use this file.  This is the same as how we do bgp_quagga_v4.py today. 
If you are on a platform running FRR and you issue the "show bgp ?" command then it would be piped through to the FRR vtysh shell and show the help output for that command like this: 
```
admin@str-s6000-acs-11:~$ show ver
SONiC …
```
=> [show][bgp] Use only 'show ip bgp' as the base and use bgp_frr_v4 file for FRR routing stack

scripts/fast-reboot
Fix the warm-reboot script to support FRR based warm-reboot
In case we use FRR stack with watchfrr, the watchfrr should be killed
during the warm-reboot shutdown process. This will make sure that watchfrr
won't restart the zebra/bgpd etc to screw up the warm-reboot process.
The code support the case where watchfrr is not used like quagga.
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
Fix the warm-reboot script to support FRR based warm-reboot
Kill watchfrr which was used on 201811 branch
Before the fix, syslog during shutdown:
```
Mar 11 04:54:29.996460 sonic NOTICE admin: Stopping bgp ...
Mar 11 04:54:30.211232 sonic ERR bgp#watchfrr[91]: zebra state -> down : read returned EOF
Mar 11 04:54:30.211232 sonic NOTICE …
```
=> [201811 warm-reboot] Fix the warm-reboot script to support FRR based warm-reboot

doc/Command-Reference.md, show/main.py
add some basic show cmds:
* show vnet brief
* show vnet name \<vnetname\>
* show vnet interfaces
* show vnet neighbors
* show vnet routes all
* show vnet routes tunnel
* show vxlan tunnel
* show vxlan name \<vxlanname\>
* some example as below:
```
admin@ASW-7005:~$ show vnet brief
vnet name    vxlan tunnel      vni  peer list
-----------  --------------  -----  ------------------
Vnet_2000    tunnel1          2000
Vnet_3000    tunnel1          3000  Vnet_2000,Vnet4000
```
```
admin@ASW-7005:~$ show vnet name Vnet_3000
vnet name    vxlan tunnel      vni  peer list
-----------  --------------  -----  ------------------
Vnet_3000    tunnel1          3000  Vnet_2000,Vnet4000
```
```
admin@ASW-7005:~$ show vnet interfaces
vnet name    interfaces
-----------  ------------
Vnet_2000 …
```
=> [Vxlan] : adding show vnet/vxlan cmds

doc/Command-Reference.md, show/bgp_frr_v4.py, show/bgp_frr_v6.py
… normal commands for 'show ip bgp'
I updated the bgp_frr_v4.py and bgp_frr_v6.py files to have a new function for "network" since the Click framework required this.  I was going to use "route" but this conflicted with "route-map" in the vtysh so I found "network" was not something that would conflict and used that as it made the most sense.  The will support the normal networking commands of "show ip bgp [ipaddress|prefix] [options]" and "show ipv6 bgp [ipaddress|prefix] [options]"
Add a new "network" function so the VTYSH commands can be referenced by the SONIC CLI.
The command didn't exist on the SONIC CLI.  I had to add it. 
For both IPv4 and …
=> [show] Add 'ip/ipv6 bgp network' commands

scripts/fast-reboot
- This flag is currently no functional impact with just this change.
- This flag is intended to coordinate fast-reboot shutdown path.
- This flag enables moving fast-reboot per service knowledge to service scripts.
which unblocks moving warm-reboot per service knowledge to service scripts.
- This flag is consistent with the boot up flag we setting on the boot up path.
Did a quick fast-reboot test with the change.
=> [fast reboot] set a fast-reboot DB flag

scripts/fast-reboot, scripts/filter_fdb_entries.py, setup.py, sonic-utilities-tests/filter_fdb_entries_test.py, sonic-utilities-tests/filter_fdb_input/arp.json, sonic-utilities-tests/filter_fdb_input/expected_fdb.json, sonic-utilities-tests/filter_fdb_input/fdb.json, sonic-utilities-tests/filter_fdb_input/test_vectors.py
FDB table can get large due to VM creation/deletion which cause
fast reboot to slow down. This utility fitlers FDB entries based on
current MAC entries in the ARP table.
code change
run unit test
sudo pytest sonic-utilities-tests/filter_fdb_entries_test.py
N/A
N/A
=> [utility] Filter FDB entries

show/main.py
Allow show ztp to display non-sensitive information visible to non-root user
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
Removed user privileges checks. These changes fix https://github.com/Azure/sonic-utilities/issues/800. The ZTP PR https://github.com/Azure/sonic-ztp/pull/13 is also required for these changes to work as expected.
Removed root user check.
show ztp status
admin@sonic:~$ show ztp status
Root privileges are required for this operation
admin@sonic:~$ show ztp status
ZTP Admin Mode : True
ZTP Service    : Processing
ZTP Status     : …
=> Allow show ztp to display non-sensitive information visible to non-root user

doc/Command-Reference.md
Added ZTP commands
Added an entry in table of contents and few descriptive sections explaining the available commands
to configure and view the ZTP service status and results.
View the doc file in a marked down editor
=> ZTP configuration and show commands

fwutil/main.py
This PR contains a fix for `fwutil update --image=next` command: do not fail when current image contains invalid `platform_component.json`
* Fixed firmware update command
* Changed `ComponentUpdateProvider` init order
1. fwutil update --image=current
2. fwutil update --image=next
```
root@sonic:/home/admin# fwutil update --image=next
Error: Chassis component names mismatch: keys=['CPLD1', 'CPLD2', 'CPLD', 'CPLD3']. Aborting...
Aborted!
```
```
root@sonic:/home/admin# fwutil update --image=next
Chassis …
```
=> [fwutil]: Fix firmware update command

config/main.py
=> Make `config` command support abbreviation

scripts/watchdog
On newer CPLDs this script will enabled hardware watchdog and set timeout
to 600 sec. On older CPLDs this script will fail saying it does not
support mellanox watchdog type 1, however fast-reboot won't fail as by
the time this script is called all services are down, so better to do
fast reboot any way as it was before rathen then failing the whole fast
reboot process and leaving system in failed state.
*DEPENDS* https://github.com/Azure/sonic-buildimage/pull/4274
=> [mellanox] enable watchdog before fast-reboot

scripts/psushow, sonic-utilities-tests/mock_tables/state_db.json, sonic-utilities-tests/psu_test.py
Add a column to display LED color to show platform psustatus output.
Add a column "LED", it will display PSU physical LED color in command line output.
1. Adjust existing unit test case
2. Add/adjust test cases to sonic-mgmt
3. Manual test
```
PSU    Status
-----  --------
PSU 1  OK
PSU 2  OK
```
```
PSU    Status    LED
-----  --------  -------
PSU 1  OK        green
PSU 2  OK        red
```
=> [psushow] Add a column to display LED color to show platform psustatus output

scripts/route_check.py
1) Add syslog support.
2) Enable forever periodic scan
3) Skip link local addresses
4) Skip eth0 routes
3) Adopt to 20191130 changes
3.1) APPl-DB INTF_TABLE may not have IP address
3.2) nexthop is never empty
=> Improved route_check tool and adopt to 20191130 image.

config/main.py, scripts/db_migrator.py
Changes to the following config commands and scripts for Multi-ASIC devices.
> **config load** : supports config load across all namespaces 
> **config save** : supports config save across all namespaces 
> **config reload** : supports reload of all services across namespaces.
The following are the changes introduced in this PR
**The changes done here are  based on the namespace support added in https://github.com/Azure/sonic-py-swsssdk/pull/63**
(a) Added API's to 
> is_multi_asic()
> get_all_namespaces()
> validate_namespace(namespace)
(b) config load/save/reload commands :  the action is taken on the linux host + if we are in multi-asic platform repeat the action in the namespaces. The filename argument is optional as before. If not given these are …
=> [config] Add support for multi-ASIC devices

show/bgp_frr_v4.py, show/bgp_frr_v6.py, show/bgp_quagga_v4.py, show/bgp_quagga_v6.py
Currently, the `AliasedGroup` class in show/main.py handles finding a subcommand to run based on an abbreviation. Thus, we need to import in the bgp files and use it as the base class for the 'bgp' groups in order to allow abbreviations to work for the subcommands in these groups.
=> [show] Fix abbreviations for 'show ip bgp ...' commands

show/main.py
1. Fix  NameError:
```
admin@str-sn-01:~$ show vnet routes tunnel
appl_db = swsssdk.SonicV2Connector()
NameError: global name 'swsssdk' is not defined
```
2. Fix empty output for neighbors 
```
admin@str-sn-01:~$ show vnet neighbors 
admin@str-sn-01:~$ 
```
Code Fix - `SonicV2Connector `is already imported from `swsssdk `in the file
Rerun commands
```
admin@str-sn-01:~$ show vnet neighbors 
admin@str-sn-01:~$ 
```
```
admin@str-sn-01:~$ show vnet neighbors 
<vnet_name>    neighbor    mac_address    interfaces
-------------  ----------  -------------  ------------ …
```
=> [Vnet] Fix NameError for 'swsssdk' and align output

config/main.py, scripts/generate_dump
Modify the load_minigraph command handler to support multi NPU platforms
This PR needs the changes from[#4222](https://github.com/Azure/sonic-buildimage/pull/4222) for the minigraph parsing changes
No command output is changed
No command output is changed
=> Support load_minigraph command for multi NPU platform

config/main.py, doc/Command-Reference.md
Add 'transceiver' subgroup with 'lpmode' and 'reset' subcommands to 'config interface' group, wrapping sfputil commands.
New command examples:
```
user@sonic~$ sudo config interface transceiver --help
Usage: config interface transceiver [OPTIONS] COMMAND [ARGS]...
SFP transceiver configuration
Options:
Commands:
lpmode  Enable/disable low-power mode for transceiver
reset   Reset transceiver
user@sonic~$ sudo config interface transceiver lpmode --help          
Usage: config interface transceiver lpmode [OPTIONS] <interface_name>
(enable|disable)
Enable/disable low-power mode for SFP transceiver module
Options:
user@sonic~$ sudo config interface transceiver lpmode Ethernet0 enable
Enabling low-power …
```
=> [config] Add 'interface transceiver' subgroup with 'lpmode' and 'reset' subcommands

clear/bgp_frr_v6.py, clear/bgp_quagga_v4.py, clear/bgp_quagga_v6.py, clear/main.py, config/main.py, connect/main.py, debug/main.py, setup.py, show/main.py, undebug/main.py
Inheriting `DefaultGroup` class from click-default-group package breaks autocomplete, so we remove dependence upon it.
Fixes https://github.com/Azure/sonic-utilities/issues/27
- In doing so, a couple commands changed:
- Previously, `sonic-clear ip bgp` would, by default, clear all bgp data for all neighbors. This functionality was already being duplicated if someone ran `sonic-clear ip bgp neighbor` without specifying a peer IP address. Thus, I instead added an 'all' subcommand to `sonic-clear ip bgp neighbor` (and also added a matching 'all' subcommand to the 'soft' group `sonic-clear ip bgp soft`), restructuring the `sonic-clear ip bgp` commands as follows:
- `sonic-clear ip bgp neighbor all [<ipaddress>]`
- `sonic-clear ip bgp neighbor in [<ipaddress>]`
- `sonic-clear ip bgp neighbor …
=> Remove dependency on click-default-group package

config/main.py
- Also add a few missing docstrings
These log message can be useful in debugging, to understand if issues may have been caused by a user modifying the device configuration.
=> [config] Log invocation of config commands to syslog

doc/Command-Reference.md, show/main.py
Signed-off-by: yangshiping <yangshiping@jd.com>
add show ntpstat command
excute ntpstat in shell.  
NULL
```
admin@sonic:~$ sudo show ntpstat
synchronised to NTP server (192.168.16.4) at stratum 7 
time correct to within 326797 ms
polling server every 64 s
```
=> [show] Add `ntpstat` output to `show ntp`

scripts/fast-reboot
* use sonic-db-cli instead of redis-cli in new added codes
* use sonic-db-cli SAVE
=> [MultiDB] use sonic-db-cli instead of redis-cli in new added codes

scripts/fanshow
1. Add a column to display fan drawer name
2. Add a column to display fan led status
Manual test
```
FAN     Speed    Direction     Presence    Status          Timestamp
-----------  --------  -----------  -----------  --------  -----------------
fan1       91%       intake      Present        OK  20200414 09:41:52
fan2       81%       intake      Present        OK  20200414 09:41:52
```
```
Drawer    LED          FAN     Speed    Direction     Presence    Status          Timestamp
--------  -----  -----------  --------  -----------  -----------  -------- …
```
=> [fanshow] Add column drawer name and led status to output of show platform fan

acl_loader/main.py, config/main.py
Changes to support acl-loader and mirror session config commands for multi-npu platforms.
Also moved some of utility functions form config/main.py to sonic_device_util.py.
This PR is needed with:
https://github.com/Azure/sonic-buildimage/pull/4559
updated the commands to check if multi-npu platform present then program per asic namespace also
Verified for multi-npu platform
=> Changes to support acl-loader and mirror-session config commands for multi-npu platforms.

config/main.py, doc/Command-Reference.md
Changes to make commands config reload/load-minigraph
to have option of not stop/start docker services. This is not needed
when this commands are called from config-setup shell script. PR: https://github.com/Azure/sonic-buildimage/pull/4609 used this change.
Added new option -n (--no-service-restart) with default as False
so that existing command behavior remains same.
Verified Manually and as well when invoke with config-setup
=> Changes to commands  config reload/load-minigraph

config/main.py
Changes to config bgp commands for Multi-ASIC devices.
The changes done here are based on the namespace support added in SonicDBConfig/ConfigDBConnector/SonicV2Connector classes in the PR  **Azure/sonic-py-swsssdk#63**
> To connect to DB in a particular namespace pass the parameter namespace=namespaceName
> To connect to the DB in the local context ( where ever we are ) don't pass any namespace input, it would be defaulted to '' (empty string ). This is the default option, so that the changes made here are backward compatible with single ASIC platforms.
**The following are the changes introduced in this PR**
(a) added a new parameter of **config_db** to the bgp neighbor helper API's. This approach is better, as now we have to do this once **config_db = …
=> Multi-asic changes for config bgp commands and utilities.

scripts/generate_dump
Added 'hw-management-generate-dump.sh' to 'generate_dump' script.
this addon will provide new information under the dump folder regarding hw-mgmt.
New information:
- SMBIOS info - version, system info, base board info
- FW info
- hw-management tree (the fs tree under /var/run/hw-management).
- system fs tree contains: block, bus, class, kernel, power etc..
- system interrupts.
- registers status.
- system sensors data.
- system log.
- Linux version and build.
- current processes,'top' output.
run 'show techsupport' command and see the result file under
/var/dump/sonic_dump_'hostname'_'time'/hw-mgmt
=> [Mellanox] Add 'hw-management-generate-dump.sh' to 'show techsupport' command

scripts/reboot
This is to revert the change to the reboot command in https://github.com/Azure/sonic-utilities/commit/710540047dea0bc54aaf3e8bdea0e5d041912abd. 
Platform reboot is not supported by the kdump kernel, as the platform drivers are not loaded. With the existing code, there are some error messages printed, but the device is still rebooted by CPU. The change here helps to avoid the error messages.
=> Revert the change to kdump reboot

show/main.py
Mapping for `alias `to vnet `name`
Run show command
```
admin@str-sn-01:~$ show vnet alias 
Alias        Name
-----------  ------
vnet-guid-1  Vnet1
vnet-guid-2  Vnet2
admin@str-sn-01:~$ show vnet alias vnet-guid-2
Alias        Name
-----------  ------
vnet-guid-2  Vnet2
```
=> Show Vnet alias to name mapping

config/main.py
Make sure db_migrator is run after all config are loaded during load_minigraph. The behaviour got changed as part of multi-npu change so make it correct again.
sudo config load_minigrah -y
=> Make sure db_migrator is run after all config are loaded during load_minigraph

config/main.py, scripts/intfutil, sonic-utilities-tests/intfutil_test.py, sonic-utilities-tests/mock_tables/appl_db.json
Signed-off-by:yangshiping@jd.com
add interface fec configuration for the command "config interface ……"
modify config/main.py
check the command whether can be configured in switch shell
```
root@sonic:/home/admin# config interface --help
Usage: config interface [OPTIONS] COMMAND [ARGS]...
Interface-related configuration tasks
Options:
Commands:
ip        Add or remove IP address
pfc       Set PFC configuration.
shutdown  Shut down interface
speed     Set interface speed
startup   Start up interface
vrf       Bind or unbind VRF
the configdb:
127.0.0.1:6379[4]> HGETALL "PORT|Ethernet0"
1) "alias"
2) …
```
=> add fec configuration 'config interface fec [OPTIONS] <interface_name> <interface_fec>'

scripts/fast-reboot
Signed-off-by: Vadym Hlushko <vadymh@mellanox.com>
Added pre-check for file /host/warmboot/issu_bank.txt in warm-reboot script.
Added instruction on how to recover issu_bank.txt.
Modify the 'fast-reboot' script
Need to somehow corrupt /host/warmboot/issu_bank.txt (list below) and then run the warm-reboot command.
1. Remove issu_bank.txt
2. Clear issu_bank.txt
3. Change characters count in issu_bank.txt
4. Write invalid content into issu_bank.txt
`root@arc-switch1041:~# warm-reboot`
`Warning: Stopping telemetry.service, but it can still be activated by:`
`  telemetry.timer`
**- New command output (if the output of a command-line utility has …
=> [warm-reboot]: added pre-check for ISSU file

sfputil/main.py
> This PR is dependent on [sonic-platform-common/pull/72](https://github.com/Azure/sonic-platform-common/pull/72)
All three PRs are necessary to run `show interfaces transceiver` command.
1. [Azure/sonic-buildimage#3912](https://github.com/Azure/sonic-buildimage/pull/3912)
2. [Azure/sonic-platform-common#72](https://github.com/Azure/sonic-platform-common/pull/72)
3. [Azure/sonic-utilities#767](https://github.com/Azure/sonic-utilities/pull/767)
Add support of platform.json in sfputil to get correct output of `show interfaces transceiver`
Check whether all the below-mentioned CLI's are working correctly.
```
Usage: show interfaces transceiver [OPTIONS] COMMAND [ARGS]...
Show SFP Transceiver …
```
=> [sfputil] Add support of platform.json

crm/main.py
…s DB
Refactored CRM code to access redis DB due to issue described below. 
Using ```keys``` operation via ```redis-cli``` or ```sonic-db-cli``` should be avoided, because there would be an issue when ```KEY``` in database contains space or '\n'. For loop on the non-tty 'keys' output will take the space or '\n' as seperator when parsing the element. 
Changed CRM code to use ```swsssdk``` API  instead of ```redis-cli``` for getting keys from redis DB. 
Run ```crm show resources all``` command and verify output is as expected. 
N/A
**- New command output (if the output of a command-line …
=> [crm] Use swsssdk API instead of redis-cli for getting keys from redis DB

config/main.py
When restarting services, don't attempt to restart a service if it is disabled/masked or the `systemctl restart` command will fail, causing the calling command (e.g., `config load`, `config reload`, `config load_minigraph`) to error out.
=> [config] Don't attempt to restart disabled services

acl_loader/main.py, scripts/aclshow, sonic-utilities-tests/aclshow_test.py, sonic-utilities-tests/mock_tables/config_db.json, sonic-utilities-tests/mock_tables/counters_db.json
- What I did
I made the priority of ACL rule props in the ACL commands to be case insensitive.
- How I did it
Instead of checking the ACL ruleprops dictionary for "PRIORITY" based key, I made it the actual key to be searched for.
I verified the fix by testing on my switch using different case sensitive options of keyword "Priority".
=> handled the priority of ACL rules to be case insensitive

data/etc/bash_completion.d/fwutil, fwutil/lib.py, fwutil/log.py, fwutil/main.py, show/main.py
This PR introduces fwutil v2.0.0.0 according to the design requirements:
https://github.com/Azure/SONiC/pull/612
Key features:
1. New CLI command to show available firmware updates
2. New CLI commands to do per component firmware update
3. Advanced user notifications in case system state change
* Updated fwutil to v.2.0.0.0 according to the design requirements
* N/A
1. fwutil show updates
2. fwutil update chassis component <component_name> fw
3. fwutil update module <module_name> component <component_name> fw
```
root@sonic:/home/admin# fwutil update --image=next
Chassis                  Module …
```
=> [fwutil]: Update fwutil to v2.0.0.0

scripts/sfpshow
Executing show interface transceiver eeprom command with -d (-d, --dom Also display Digital Optical Monitoring (DOM) data) result error of key not present in dom dictionary.
Error O/P:
show interface transceiver eeprom -d Ethernet124
File "/usr/bin/sfpshow", line 358, in <module>
cli()
File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke …
=> [show interface transceiver] Ensure key exists in dom_info_dict before accessing

show/main.py
- Why I did it
When exec 'show ipv6 interfaces', the neighbor_ip will always be 'N/A' which will confuse the consumers. After checking we found that this is a show issue. As we know, there will be one local linked IPV6 address for every valid interface. In show/main.py, the interface's ipv6 neighbor ip will always be written by this local linked IPV6's neighbor_ip address which is 'N/A'. And i think this part code of 'show ipv6 interface' was copied from 'show ip interface' before, right? Yea, some change is necessary!
-  What I did
This is bug fixing. Using a array to store neighbor info in case that the old one be written by the newer one.
- How I did it
Code change.
Upgrate config_db.config attached in https://github.com/Azure/sonic-buildimage/issues/4716 and show …
=> [master]fix #4716 show ipv6 interfaces neighbor_ip is N/A issue

scripts/fast-reboot, scripts/filter_fdb_entries.py, sonic-utilities-tests/filter_fdb_entries_test.py, sonic-utilities-tests/filter_fdb_input/config_db.json, sonic-utilities-tests/filter_fdb_input/test_vectors.py
FTOS fast conversion script generates bogus vlan that does not exist.
This PR uses config_db in order to verify that provided vlans exist
in the switch configuration.
Added new code to parse config_db.json and used this to filter out arp entries
```
sonic-utilities$ sudo pytest sonic-utilities-tests/filter_fdb_entries_test.py  -vvvv
=================================================================================================================================================== test session starts ===================================================================================================================================================
platform linux2 -- Python 2.7.13, …
```
=> [filter-fdb] Check VLAN Presence When Filter FDB

show/main.py
Fixing "show line" by adding the missing decorator that supports
"--verbose" option.
Signed-off-by: lolyu <lolv@microsoft.com>
```
```
```
$ sudo show line
File "/usr/bin/show", line 12, in <module>
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in …
```
=> [show] Add missing verbose option to "show line"

scripts/sfpshow, sonic-utilities-tests/mock_tables/state_db.json
Change the following key names:
- hardwarerev -> hardware_rev
- serialnum -> serial
- manufacturename -> manufacturer
- modelname -> model
- Connector -> connector
Depends on:
- https://github.com/Azure/sonic-platform-common/pull/97
- https://github.com/Azure/sonic-platform-daemons/pull/62
=> [sfpshow][mock_state_db] Tweak key names of some transceiver info fields

doc/Command-Reference.md, show/main.py, sonic-utilities-tests/mock_tables/config_db.json, sonic-utilities-tests/show_breakout_test.py
Implemented show interface breakout sub-command to show the port capability and the current breakout mode.
Available commands are mentioned below.
```
show interfaces breakout --help
show interfaces breakout current-mode
```
using platform.json, hwsku.json and config-db BREAKOUT_CFG table.
```
admin@lnos-x1-a-fab01:~$ show interfaces breakout --help
Usage: show interfaces breakout [OPTIONS] COMMAND [ARGS]...
Show interface breakout
Options:
Commands:
current-mode  Show interface breakout current-mode
```
```
admin@lnos-x1-a-fab01:~$ show interfaces breakout
{
"Ethernet0": {
"index": "1,1,1,1",
"default_brkout_mode": "1x100G[40G]", …
```
=> [Show | Command Reference] Add Port breakout Show Command

setup.py, sonic_installer/bootloader/__init__.py, sonic_installer/bootloader/aboot.py, sonic_installer/bootloader/bootloader.py, sonic_installer/bootloader/grub.py, sonic_installer/bootloader/onie.py, sonic_installer/bootloader/uboot.py, sonic_installer/common.py, sonic_installer/main.py
Add a new Bootloader abstraction.
This makes it easier to add bootloader specific behavior while keeping
the main logic identical.
It is also a step that will ease the introduction of secureboot which
relies on bootloader specific behaviors.
Shuffle code around to get rid of the hacky if/else all over the place.
There are now 3 bootloader classes
- AbootBootloader
- GrubBootloader
- UbootBootloader
There was almost no logic change in any of the implementations.
Only the AbootBootloader saw some small improvements.
More will follow in subsequent changes.
<!--
Please make sure you've read and understood our contributing guidelines:
https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md
** Make sure all your commits include a signature generated with `git commit -s` **
If this is a bug …
=> [sonic_installer] Refactor sonic_installer code

config/main.py
If FEATURE table did not exist,` config load/reload/reload_minigraph` commands would crash similar to the following:
```
Executing reset-failed of service nat...
Executing reset-failed of service sflow...
File "/usr/bin/config", line 12, in <module>
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
File …
```
=> [config] Fix indentation level in _get_disabled_services_list()

config/main.py
Parenthesize multiple exception types. Otherwise Python2 will incorrectly interpret the last exception type as the target.
=> [config] Fix 'except' syntax error

setup.py, sonic_installer/bootloader/aboot.py
The feature is to verify the aboot swi image, it makes sure the installing image should be signed when secure boot enabled.
=> Suppport to verify aboot swi image for secure boot

config/main.py
If user configures IP (v4 or v6) address without a mask, append the default `/32` or `/128` mask
Redis command
```
config interface ip add Vlan1000 2001::1
config interface ip add Vlan1000 1.1.1.3
127.0.0.1:6379[4]> KEYS *VLAN_INTERFACE*
1) "VLAN_INTERFACE|Vlan1000|2001::1/128"
2) "VLAN_INTERFACE|Vlan1000|1.1.1.3/32"
```
=> Append default mask field if user has not provided one

acl_loader/main.py, config/main.py, doc/Command-Reference.md
Signed-off-by: Rupesh Kumar <rupesh-k.kumar@broadcom.com>
Port mirroring CLI implementation 
HLD @ https://github.com/Azure/SONiC/pull/58
Enhance existing mirror_session command to support port mirroring.
Create ERSPAN/SPAN mirror session and verify show mirror_session.
config mirror_session add everflow0 10.1.1.1 12.1.1.1 10 10
root@sonic:/home/admin# show mirror_session
Name       Status    SRC IP    DST IP      GRE    DSCP    TTL  Queue    Policer    Monitor Port    SRC Port    Direction
---------  --------  --------  --------  -----  ------  -----  -------  ---------  --------------  ----------  -----------
everflow0  active  10.1.1.1  12.1.1.1 …
=> Add support for port mirroring CLIs

config/config_mgmt.py, setup.py, sonic-utilities-tests/config_mgmt_test.py, sonic-utilities-tests/mock_tables/counters_db.json
Provided a class in sonic_util config for 
-- Config Validation,
-- BreakOut Ports
--ConfigMgmt Class uploads config data from config_Db.json or from config db using SONiC-py-swsssdk APIs . 
--Port, vlan and acl related config is cropped out of entire config, this is because yang models are available only for Vlan, Acl and Port as of now. 
--Cropped portion of config DB will be given as input to Python Yang LIB while loading config data.
--ConfigMgmt Class provides APIs to breakout, delete and add Ports. 
--Using Python yang LIB APIs, this class finds dependencies for each of the port which must be deleted and will delete dependencies. 
-- At last after successful validation, new config is written in config DB.
-- While addition, relevant default config …
=> [config] Add ConfigMgmt class for config validation, delete ports, add ports

setup.py, watchdogutil/main.py
Add a command line utility to control the hw watchdog arm/disarm
Add watchdogutil
Check the syslog 
```
user@server:~$ sudo watchdogutil status
Status : Unarmed
user@server:~$ sudo watchdogutil arm
Watchdog armed for 180 seconds
user@server:~$ sudo watchdogutil disarm
Watchdog disarmed successfully
```
=> Add watchdogutil to control the hw watchdog

scripts/natclear, scripts/natshow
Separated the notifications for 2 clear commands, as "sonic-clear nat translations" notifications to be handled now at NatMgr and like earlier "sonic-clear nat statistics" notification to be handled at NatOrch.
Depends on:
https://github.com/Azure/sonic-swss/pull/1274
https://github.com/Azure/sonic-buildimage/pull/4596
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>
=> Separated the notifications for "sonic-clear nat translations" and "sonic-clear nat statistics" commands

config/main.py
config reload and config load_minigraph commands were taking ~ 5m in in the multi ASIC platforms.**Reduced the total time taken to ~ 1min by parallelizing with python threads.**
Started a python thread per NPU to stop/restart the services. 
Currently the threads are started at the same time for all the ASIC's irrespective of whether they are front-end OR back-end ASIC's. I found it ok as we finish the entire activity of config reload in 1 min and when we do config reload usually the device should not be in production and not carrying active traffic.
Verified on a Single ASIC and multi AISC devices. Attaching sample output.
**MULTI ASIC**
**~$ time sudo config reload  -y**
Executing stop of service swss@1...
Executing stop of …
=> [Multi NPU] Time Improvements to the config reload/load_minigraph commands 

scripts/fast-reboot
Add the HW watchdog enable flow during the fast-reboot ( and warm-reboot) to make sure that the device wouldn't be stuck during the following boot up.
=> Enable HW watchdog before fast-reboot

scripts/filter_fdb_entries.py, sonic-utilities-tests/filter_fdb_input/test_vectors.py
VLAN_INTERFACE section in Config_db may contain entries with now CIDR.
This fix skip those entries.
Fixes #4933
Fix for VLAN_INTERFACE with no CIDR
Skipped over entries in VLAN_INTERFACE section that do not have CIDR
***- Without This Fix***
```
taahme@024d65787c01:/sonic/sonic-utilities$ sudo pytest sonic-utilities-tests/filter_fdb_entries_test.py  -vvvv
=================================================================================================================================================== test session starts ===================================================================================================================================================
platform …
```
=> [filter-fdb] Fix For Vlan Defined With No CIDR

scripts/fast-reboot, scripts/reboot, sonic_installer/bootloader/aboot.py, sonic_installer/bootloader/bootloader.py, sonic_installer/main.py
Add a command "sonic_installer verify_reboot" to verify the image before reboot.
The command will be called when reboot/fast-reboot/warm-reboot.
=> Support to verify reboot for secure boot

scripts/db_migrator.py, scripts/sfpshow
Fix the None Type Exception when Interface Table does not exist (cold boot) as part of db migration
Because of this exception database service does not come up.
After fix all docker and services cam up fine.
=>  Fix the None Type Exception when Interface Table does not exist (cold boot) as part of db migration

data/etc/bash_completion.d/sonic-installer, doc/Command-Reference.md, fwutil/lib.py, scripts/asic_config_check, scripts/fast-reboot, scripts/reboot, scripts/sonic-kdump-config, setup.py, show/main.py, sonic_installer/aliases.ini, sonic_installer/common.py, sonic_installer/main.py
Replace underscores with hyphens in all sonic-installer subcommands as well as the root command itself.
- Install two entry points for sonic-installer: `sonic-installer` and `sonic_installer`. This allows for backward compatibility and time for users to transition from using the underscore versions to the hyphenated versions.
- Replace underscores with hyphens in the following subcommands:
```
set-default
set-next-boot
binary-version
upgrade-docker
rollback-docker
```
- Also add aliases from the underscore versions of these subcommnds to the new hyphenated subcommands to allow for backward compatibility and time for users to transition from using the underscore versions to the hyphenated versions.
- Print deprecation warnings to stderr if issued command line contains any deprecated …
=> [sonic-installer] Hyphens instead of underscores in command and subcommands

scripts/sfpshow, sonic-utilities-tests/mock_tables/state_db.json, sonic-utilities-tests/sfp_test.py
Add support for QSFP-DD cables on 'sfpshow' script
Adapt sfp_test to new eeprom output.
Added a new label "application_advertisement" to print from DB.
Exclude "specification compliance" print from QSFP-DD cables.
Check for Transceiver DB data with QSFP-DD cable.
Check 'show interfaces transceiver eeprom Ethernet#' output.
Run unit test sfp_test.
=> [show] Add support for QSFP-DD cables on 'show' command

acl_loader/main.py
- Fix issue where protocol == 0 would be ignored
- Emit warning if --table_name not found in Config DB
**- What I did/How I did it**
I fixed a bug in acl-loader where rules with protocol=0 would have the protocol field ignored due to python's implicit boolean conversion. I fixed this by explicitly adding the `== 0` check to the ip protocol field.
I also fixed/added a warning when the provided `--table_name` can't be found in Config DB. Previously this case would fail silently, now the user will receive a warning to point them in the right direction.
Run `acl-loader` with a non-existent `--table_name`:
```
admin@sonic:~$ sudo acl-loader update full test.json --table_name yeehaw
Warning: Table "yeehaw" not found
```
Run …
=> [acl-loader] Fix bugs in acl-loader

sonic_installer/main.py
Root group name was changed from `cli` to `sonic_installer` in https://github.com/Azure/sonic-utilities/pull/983. However, `verify-next-image` subcommand was being added in an already-open PR https://github.com/Azure/sonic-utilities/pull/979/ at the time. It did not get updated before merge. This aligns it with the new group name.
=> [sonic-installer] Update group name for 'verify-next-image' subcommand

config/main.py
Add telemetry service to the list of services to stop/reset-failed/restart during config load/reload operations.
=> [config] Restart telemetry service upon config (re)load

config/main.py
Importing **json** module needed for loading json file in DPB.
somehow, missed in #766 PR. [3910 PR](https://github.com/Azure/sonic-buildimage/pull/3910) in sonic-buildimage is failing for it.
Imported built-in module.
=> importing json needed for DPB CLI

scripts/intfutil
Signed-off-by: Shlomi Bitton <shlomibi@mellanox.com>
Changed the output of 'show interfaces status' field related to a PortChannel.
If the PortChannel is a member of a vlan group it will be printed as 'trunk' port instead of default 'routed'.
Check if the PortChannel is a member of a Vlan group and assign a proper tag for it.
1) Add a PortChannel to a Vlan group.
2) Run 'show interfaces status' command.
PortChannel0005   N/A     100G     9100     N/A   N/A      routed    down       up       N/A         N/A
PortChannel0005   N/A     100G     9100     N/A   N/A      trunk …
=> [show] Fix for 'trunk' PortChannel reported as 'routed' port

config/config_mgmt.py, sonic-utilities-tests/config_mgmt_test.py
…ng().
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
Fix typo and enable test for tablesWithOutYang()
Fix typo and enable test for tablesWithOutYang()
After enabling built time test. I Build the PKG.
=> [config/config_mgmt.py]: Fix typo and enable test for tablesWithOutYang()

scripts/lldpshow
Fix "the input device is not a TTY" error reported by 'show lldp' commands when executed via pytest scripts in sonic-mgmt.
resolves Azure/sonic-buildimage#5019
Removed the usage of '-t' docker exec option to not allocate a TTY, while invoking 'lldpctl'.
Execute 'TestShowLLDP' test cases in test_iface_namingmode.py script in sonic-mgmt.
=> [show lldp]: Fix 'input device is not a TTY' error

tests/drops_group_test.py
a few tests in drops_group_test fails on second run.
The reason is that /tmp/dropstat is not cleaned, the first
run leave some state in the folder which cause the subsequent
run to fail.
The fix is the always clean up the folder.
The fix is the always clean up the folder.
run python setup.py test multiple times.
=> [tests]: fix drops_group_test failure on second run

config/main.py, show/main.py, sonic-utilities-tests/feature_test.py, tests/mock_tables/config_db.json
merge container feature cli into feature cli
add unit tests
```
02:24:22  ============================= test session starts ==============================
02:24:22  platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
02:24:22  rootdir: /sonic/sonic-utilities, inifile: pytest.ini
02:24:22  plugins: cov-2.6.0
02:24:24  collected 75 items
02:24:24  
02:24:24  sonic-utilities-tests/acl_loader_test.py ....                            [  5%]
02:24:24  sonic-utilities-tests/aclshow_test.py ...........                        [ 20%]
02:24:25  sonic-utilities-tests/config_mgmt_test.py ....                           [ 25%]
02:24:26  sonic-utilities-tests/drops_group_test.py .......                        [ 34%]
02:24:26 …
```
=> [show/config]: combine feature and container feature cli

setup.py, sonic_installer/common.py, sonic_installer/exception.py, sonic_installer/main.py, sonic_installer/templates/sonic-environment.j2
Create environment files for SONiC immutable attribute. The file
will reside in the incoming image dir under sonic-config dir.
Incoming image will then move the file to /etc/sonic. The file
will be used to avoid calls into cfggen for those attributes.
Added support to generate envvar file
Extended sonic_installer with ability to generate envvar file
1. For existing image:
update main.py in /usr/lib/python2.7/dist-packages/sonic_installer/main.py with new code
run sonic_installer install -y <image>
2. SONiC Image (ongoing)
build sonic image with new change in order to verify packaging.
N/A
**- …
=> [sonic-installer] Create Envvars File for Incoming Image

scripts/fast-reboot
Instead of having multiple implementation of preparing a SWI image for
secureboot, fast-reboot now reuses boot0.
SWI images booting in regular mode will keep using the old behavior.
=> Add secure fast/warm-reboot support for Aboot

pddf_fanutil/main.py, pddf_ledutil/main.py, pddf_psuutil/main.py, pddf_thermalutil/main.py, utilities_common/util_base.py
Added PDDF utilities changes to make them compatible with 2.0 platform APIs. Since PDDF 2.0 is supporting platform 2.0 APIs, we needed to move the utilities to support the same. 
Adding wrapper functions for various hw info retrieval 
Run PDDF utilities commands
Command o/p remains almost same. Please refer to 
https://github.com/Azure/SONiC/pull/536
Command o/p remains almost same.
https://github.com/Azure/SONiC/pull/536
Depend on:
https://github.com/Azure/SONiC/pull/536
=> [PDDF] Make utilities compatible to platform API 2.0, in accordance with pddf_2.0

config/main.py, show/main.py, tests/config_test.py, tests/conftest.py, tests/feature_test.py, utilities_common/db.py
it is better not let every command to have its
own connector and connect to db.
it is also not good to have a global db variable.
Here, the idea is to have a single db connector
and pass the connector as a click context
it is better not let every command to have its
own connector and connect to db.
it is also not good to have a global db variable.
Here, the idea is to have a single db connector
and pass the connector as a click context.
This will allow us to easily split the big config file into multiple 
small files without maintaining a global db variable.
use make_pass_decorator to pass the db object.
unit test.
**- Previous command output (if the output of a command-line utility has …
=> pass db connector as click context

acl_loader/main.py, config/main.py, config/mlnx.py, fwutil/lib.py, fwutil/log.py, pcieutil/main.py, pddf_fanutil/main.py, pddf_ledutil/main.py, pddf_psuutil/main.py, pddf_thermalutil/main.py, psuutil/main.py, scripts/db_migrator.py, scripts/decode-syseeprom, scripts/lldpshow, scripts/neighbor_advertiser, scripts/port2alias, setup.py, sfputil/main.py, show/main.py, sonic_installer/main.py, ssdutil/main.py, tests/conftest.py, utilities_common/util_base.py, watchdogutil/main.py
As part of consolidating all common Python-based functionality into the new sonic-py-common package, this pull request redirects all Python applications/scripts in sonic-utilities repo to point to sonic-py-common and removes multiple duplicate definitions of common functions in the process. This is the next step toward resolving https://github.com/Azure/sonic-buildimage/issues/4999.
- Also reorganize imports for consistency
- Also align some style
=> [Python] Migrate applications/scripts to import sonic-py-common package

config/feature.py, config/main.py, show/feature.py, show/main.py, tests/feature_test.py, utilities_common/cli.py
split feature into a separate file
create new feature.py for both config and show, move the code into feature.py
move common code into sonic-utiltities.common.cli.py
unit test
also run it in vs switch
=> [cli/feature]: split feature into a separate file

pytest.ini
generate xml, html and term report
generate xml, html and term report
modify pytest.ini
check the report. below is the term report. xml/html has lots of more details.
```
---------- coverage: platform linux2, python 2.7.16-final-0 ----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
config/__init__.py                    0      0   100%
config/aaa.py                       132     82    38%
config/config_mgmt.py               345    116    66%
config/feature.py                    25      5    80%
config/main.py                     2280   1683    26%
config/mlnx.py                      134     93    31%
config/nat.py …
```
=> [tests]:add coverage for config/main/utilities_common module

scripts/fast-reboot, scripts/filter_fdb_entries.py, sonic-utilities-tests/filter_fdb_entries_test.py, sonic-utilities-tests/filter_fdb_input/config_db.json, sonic-utilities-tests/filter_fdb_input/test_vectors.py
* [filter-fdb] Check VLAN Presence When Filter FDB
FTOS fast conversion script generates bogus vlan that does not exist.
This PR uses config_db in order to verify that provided vlans exist
in the switch configuration.
* review comments
making lgtm happy
Added two more test cases
* Update existing test case and adding new one
* adding support for filter ou based on vlan ip network
=> [filter-fdb] Check VLAN Presence When Filter FDB (#957)

scripts/fast-reboot
Enable the watchdog before running platform specific reboot plugin
Move the WatchdogUtil call before calling platform specific reboot plugin
Warm reboot without error for hw watchdog support platforms.
N/A
N/A
Fixes https://github.com/Azure/sonic-buildimage/issues/5118
=> [fast-reboot/warm-reboot] Enable watchdog before running platform specific reboot plugin

pytest.ini
add coverage for all scripts
```
---------- coverage: platform linux2, python 2.7.16-final-0 ----------
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
acl_loader/__init__.py                         0      0   100%
acl_loader/main.py                           541    367    32%
clear/__init__.py                              0      0   100%
clear/bgp_frr_v6.py                           44     44     0%
clear/bgp_quagga_v4.py                        44     44     0%
clear/bgp_quagga_v6.py                        44     44     0%
clear/main.py                                179    106    41%
config/__init__.py …
```
=> [pytest/coverage]: add coverage for all scripts

config/aaa.py, config/main.py, config/mlnx.py, config/utils.py, config/vlan.py, show/bgp_frr_v4.py, show/bgp_frr_v6.py, show/main.py, show/vlan.py, tests/config_test.py, tests/conftest.py, tests/intfutil_test.py, tests/mock_tables/appl_db.json, tests/mock_tables/config_db.json, tests/vlan_test.py, utilities_common/cli.py
- add vlan.py in config and show
- add extensive unit tests for vlan
- add vlan.py in config and show
- add extensive unit tests for vlan
unit test
```
---------- coverage: platform linux2, python 2.7.16-final-0 ----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
config/__init__.py                    0      0   100%
config/aaa.py                       124     75    40%
config/config_mgmt.py               345    116    66%
config/feature.py                    25      5    80%
config/main.py                     2103   1540    27%
config/mlnx.py                      126     85    33%
config/nat.py                       680 …
```
=> [config/show]: split vlan into separate file

scripts/fast-reboot, scripts/reboot, sonic_installer/exception.py
**- Why I did it**
`sonic_installer` has been renamed `sonic-installer`
Update the file name everywhere it is used
Test the affected applications. They should work and no longer output the sonic_installer deprecation warning.
=> Update all references to new 'sonic-installer' file name

scripts/watermarkstat
To support the `file=` argument in `print()` function in Python 2.7.
=> [watermarkstat] Import print_function from __future__

config/main.py
Port breakout-related data should be gathered on-demand, not every time `config` is executed. If the ConfigDB is not ready, the call to get hwsku will hang indefinitely, which will occur when loading config for the first time. Also, if it fails to retrieve the port breakout globals, it will abort, even if the executed command was unrelated to port breakout. This is not desirable behavior.
This PR eliminates port breakout-related global variables, and encapsulates them in functions to be called on-demand, only when commands which require the data are executed. It is currently only accessed in two places. If we feel the need to cache it in the future for efficiency, we can look into adding it to the Click context.
Also rename `_get_option()` to `_get_breakout_cfg_file_name()` to add more …
=> [config] Eliminate port breakout-related globals

pfcwd/main.py
* Traceback was returned if DB is not yet initialized
Fixed issue with ```pfcwd show stats``` command during SONiC init.
Traceback was returned if DB was not yet initialized which is incorrect. Correct behavior would to rather return empty line if something is not yet ready to be pulled and displayed.
Returned empty dictionary instead of ```None``` if data are still not present in DB. It is because in source code data expected to be as dictionary type but if there is no expected attributes in DB ```None``` was returned. Wich is incorrect and caused following exception: ```'NoneType' object has no attribute 'keys'```
Perform any type of reboot or config reload and once …
=> [PFCWD] Fix issue with "pfcwd show stats" command during SONiC init

show/vlan.py, tests/vlan_test.py
use VLAN_MEMBER table to get vlan configuration
read VLAN_MEMBER table.
added unit to cover.
=> [show/vlan]: fix show vlan config

acl_loader/main.py, config/main.py, fwutil/lib.py, scripts/db_migrator.py, scripts/decode-syseeprom, scripts/lldpshow, scripts/neighbor_advertiser, scripts/teamshow, show/main.py, show/mlnx.py
As part of consolidating all common Python-based functionality into the new sonic-py-common package, this pull request redirects all Python applications/scripts in sonic-utilities repo to point to sonic-py-common and removes multiple duplicate definitions of common functions in the process. This is the next step toward resolving https://github.com/Azure/sonic-buildimage/issues/4999.
- Also reorganize imports for consistency
- Also align some style
This is a port of https://github.com/Azure/sonic-utilities/pull/1008 to the 201911 branch
Depends on https://github.com/Azure/sonic-buildimage/pull/5132
=> [201911][Python] Migrate applications/scripts to import sonic-py-common package

scripts/portstat, utilities_common/constants.py, utilities_common/multi_asic.py
Common functions for show CLI support on multi ASIC
Depends on this PR 
https://github.com/Azure/sonic-buildimage/pull/4973
Add a set of common function will be used to support SONiC CLIs for multi ASIC
NA
NA
=> Common functions for show CLI support on multi ASIC

scripts/fast-reboot
Special handling is needed for services during fast, warm and cold reboot paths. This procedural handling is better suited in the respective service scripts to:
1) keep fast-reboot script simpler    2) avoid code duplication.
Call swss and radv service scripts to do special handling of reboot process behavior.
**_This PR should be merged only after service scripts changes are merged in following PRs:_**
RADV - https://github.com/Azure/sonic-buildimage/pull/5108
SWSS - https://github.com/Azure/sonic-buildimage/pull/5070
Created and modified service scripts to handle reboot procedure depending on the type. Fast-reboot script now simply calls these service scripts.
Tested service scripts independently.
Tested Fast, warm and cold …
=> Change fast-reboot script to use swss and radv service script

scripts/decode-syseeprom
what I did:
Fix show version on 201911. When using new sonic_py-common package
we have to use get_platform() instead of get_platform_info()
How i Verified:
show version is fine after this change
=> [201911] fix show version 

show/main.py, tests/mock_tables/appl_db.json, tests/mock_tables/config_db.json, tests/sflow_test.py, tests/show_sflow_test.py
Changes:
-- Display ipv4 address with left adjust of 25 width and with space before UDP.
-- IPv6 address will be displayed as is.
-- Add test data to appl_db.json and config_db.json
-- add test file show_sflow_test.py
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
Changes:
-- Display ipv4 address with left adjust of 25 width and with space before UDP.
-- IPv6 address will be displayed as is.
-- Add test data to appl_db.json and config_db.json
-- add test file show_sflow_test.py
Display ipv4 address with left adjust of 25 width and with space before UDP.
-- Add test data to appl_db.json and config_db.json
-- add test file show_sflow_test.py
Built with above test:
``` …
```
=> [show_sflow_test.py]: Fix show sflow display.

config/main.py
Calls to sonic-cfggen is CPU expensive. This PR reduces calls to
sonic-cfggen during config-setup when configuring buffer/qos.
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
Reduce time required to start config-setup service
Used template batch mode to batch together 4 calls into one call to sonic-cfggen
flame graph showed gain of ~1.5% sonic-cfggen CPU util.
N/A
N/A
=> [config] Reduce Calls to SONiC Cfggen

scripts/fast-reboot-dump.py
Try to fix fast-reboot function from error
Separate IPv4 and IPv6 neighbor address when fast-reboot try to send ARP to them
Make it learn some IPv6 neighbor address and ask it to fast-reboot. It should not return error.
**- Error log during executing fast-reboot**
```
Jul 23 21:18:47.612045 as5835-54x ERR fast-reboot-dump: Got an exception illegal IP address string passed to inet_aton: Traceback: Traceback (most recent call last):#012  File "/usr/bin/fast-reboot-dump.py", line 283, in <module>#012    res = main()#012  File "/usr/bin/fast-reboot-dump.py", line 276, in …
```
=> [fast-reboot]: Fix fail to execute fast-reboot problem

sonic_installer/main.py
The `import re` line was removed from the file in https://github.com/Azure/sonic-utilities/pull/953. However, it is still referenced in the `update_sonic_environment()` function. Adding it back.
Was causing the following traceback during `sonic-installer install` command on certain platforms:
```
Installed SONiC base image SONiC-OS successfully
Command: grub-set-default --boot-directory=/host 0
Command: config-setup backup
Taking backup of curent configuration
File "/usr/bin/sonic-installer", line 12, in <module>
sys.exit(sonic_installer())
File …
```
=> [sonic-installer] Import 're' module

scripts/lldpshow
This PR is to fix https://github.com/Azure/sonic-buildimage/issues/5239
The command 'show lldp table/neighbor' always return error message 'the input device is not a TTY' when running in a SSH command or running with Ansible. This commit is to fix this issue.
This is a backport of https://github.com/Azure/sonic-utilities/pull/1016 to the 201911 branch.
```
ssh admin@10.64.247.224 "show lldp table"   
the input device is not a TTY
ssh admin@10.64.247.224 "show lldp neighbors" 
the input device is not a TTY
```
Update lldpshow. Replace the **-it** in **docker exec** with **-i**, because there is no need for a pseudo-TTY when running in command line.
Verify on Arista-7260.
Before update:
```
ssh admin@10.64.247.224 "show lldp table" …
```
=> [show] [lldp] Fix error 'the input device is not a TTY' when running 'show lldp table/neighbor'

config/main.py
this PR addresses replacing _get_breakout_cfg_file_name
function with device_info.get_path_to_port_config_file().
This is part of a larger clean up of functions which return
the port_config_file which reside outside of
sonic_py_common packages. This is motivated due to
redundancy of code as well as making it easier to change
the default behaviour of helper utility function
port_config_file unified and in one place.
=> [config] Remove _get_breakout_cfg_file_name helper function

config/main.py
Update SONiC envvars file when loading minigraph.
Update SONiC Environment Var when loading minigraph
Add code to update those variables
`sudo config load_minigraph -y`
```
Executing stop of service bgp...
Executing stop of service hostcfgd...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db
Running command: pfcwd start_default
Running command: config qos reload
Running command: /usr/local/bin/sonic-cfggen  -d -t /usr/share/sonic/device/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers.json.j2,config-db -t …
```
=> [config] Update SONiC Environment Vars When Loading Minigraph

tests/bgp_commands_test.py, tests/multi_asic_intfutil_test.py, utilities_common/bgp_util.py
Two minor Fixes to the done 
- reset the os environ UTILITIES_UNIT_TESTING_TOPOLOGY multi_asic_intfutil_test after the test is done
- add the line "Total number of neighbors" to the show ip(v6) bgp summary
Update the bgp display function to display the` Total number of neighbors`
**UT results**
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /sonic/src/sonic-utilities, inifile: pytest.ini
plugins: cov-2.6.0
collected 143 items
tests/acl_loader_test.py ....                                            [  2%]
tests/aclshow_test.py ........... …
```
=> [show][bgp] Display the Total number of neighbors in the  show ip bgp(v6) summary

pfcwd/main.py
Pfcwd show stats was crashing when an invalid queue name was specified as argument
fixes #1076 
Retreive stats only for valid queue names
With the fix,
```
admin@str-7260cx3-acs-7:~$ pfcwd show stats Ethernet0:30                         
QUEUE    STATUS    STORM DETECTED/RESTORED    TX OK/DROP    RX OK/DROP    TX LAST OK/DROP    RX LAST OK/DROP
-------  --------  -------------------------  ------------  ------------  -----------------  -----------------
```
=> [pfcwd] Fix stats crash with invalid queue name

setup.py
Ensure aliases.ini gets installed with the sonic_installer package to enable backward-compatibility with the versions of subcommands which contain underscores.
This was missed in https://github.com/Azure/sonic-utilities/pull/983
=> [setup.py] Add aliases.ini to sonic_installer package

scripts/coredump-compress
Look for namespace of this process in crashing process's environ file.If any, add it to core filename as
< binary name >.< timestamp >.< local pid inside container >.< ns > .core.gz.
e.g. orchagent.1599073263.45.5.core.gz  <-- 5 is the asic namespace.
For processes that don't have asic namespace, there is no change.
e.g. snmpd.1599073245.27.core.gz
The /etc/sysctl.conf kernel.core_pattern is set to pass `pid in host`
as last arg.
Crash a process running in a namespace and another process that is *not* running in a namepsace and  verify, the core filenames.
=> Add ASIC namespace ID to core filename, if any

scripts/mellanox_buffer_migrator.py
Fix a typo in mellanox_buffer_migrator
This typo causes the db_migrator to update the buffer profiles even if they don't match the default
=> [Mellanox] Fix a typo in mellanox_buffer_migrator

config/main.py, setup.py
[ merge from #978 ]
To support buffer and QoS config generation for multi ASIC platform. In case of multi ASIC platforms each ASIC has its own buffer and qos configuration template which is used to populate corresponding ASIC's config DB.
Following commands were modified for this purpose:
In multi ASIC platforms the command runs on all namespaces. In case of single ASIC platform the command runs in global namespace.
admin@str-nSonic-acs-2:~$ sudo config qos reload --help                                                                                                                                
Usage: config qos reload [OPTIONS] …
=> [sonic-cfggen][QoS][multi ASIC] Multi ASIC QoS and Buffer config generation support, merge from master

sonic-utilities-tests/multi_asic_intfutil_test.py
Fix a bug in Multi ASIC interface test.
'multi ASIC' env variable was causing a subsequent test to fail.
Updated the env variable in teardown function.
verified by running the pytest
```
running build_ext                                                        
================================================================================ test session starts =================================================================================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /sonic/src/sonic-utilities, inifile: pytest.ini                                                                                                                              
plugins: cov-2.4.0 …
```
=> [Pytest][Multi ASIC] Update the environment variable in the teardown

scripts/route_check.py
As this is not a bug to report.
=> Skip default route present in ASIC-DB but not in APP-DB.

setup.py
201811 branch build fails without taking explicit dependency on
ipaddress package.
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
Resolved 201811 build failure
Added `ipaddress` as a required package for installation
`target/debs/python-sonic-utilities_1.2-1_all.deb` builds OK on 201811 branch
N/A
N/A
=> [utilities] Define Explicit Dependency On Ipaddress Package

config/main.py, doc/Command-Reference.md
- What I did
Handled configuration code to block deletion of Port channel when user tries to delete a Port channel before deleting its members.
- How I did it
In the sonic-utilities/config/main.py, where the removal of Port channel configuration is handled, I added a check whether the Port channel to be deleted has any members. If members exist, I will block the configuration of deleting the port channel.
Create a Portchannel. Add 2 switch ports to it as members. Then try to delete the port channel. Now, the deletion of port channel should be blocked by the config since it has port channel members still existing.
- Previous command output (if the output of a command-line utility has changed)
```
admin@r-qa-sw-eth-53:/tmp$ sudo config portchannel add portchannel100 …
```
=> Handling deletion of Port Channel before deletion of its members

config/main.py
To take care of comment https://github.com/Azure/sonic-utilities/pull/877#discussion_r487324882.  To support the way the config reload command is used in https://github.com/Azure/SONiC/wiki/L2-Switch-mode
Changed os.path.isfile check to os.path.exists.
Verified the command give in https://github.com/Azure/SONiC/wiki/L2-Switch-mode works ok.
admin@str-s6000-acs-8:~$ sudo config reload /dev/stdin -y
Executing stop of service telemetry...
Warning: Stopping telemetry.service, but it can still be activated by:
telemetry.timer
Executing stop of service swss...
Executing stop of service lldp...
Executing stop of service pmon...
Executing stop of service …
=> Update to make config load/reload backward compatible.

consutil/lib.py
fixes #1116 
Add missing reference to the header
Install new debs to SONiC and check with commands `sudo consutil show` and `sudo consutil connect 1`
```
admin@sonic:~$ sudo consutil show
File "/usr/bin/consutil", line 12, in <module>
sys.exit(consutil())
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
File …
```
=> [consutil] Fix issue where the ConfigDBConnector's reference is missing

scripts/teamshow
teamshow reads teams raw data by running docker exec -it xxx. However, the 't' may lead to error when called without a tty. This commit fix the issue.
Remove 't' from argument when calling docker exec.
Verified on Arista 7260.
**before update:**
```
ssh admin@10.64.247.224 "SONIC_CLI_IFACE_MODE=alias sudo show interfaces portchannel" 
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
S - selected, D - deselected, * - not synced
No.  Team Dev         Protocol    Ports
-----  ---------------  ----------  -------
0001  PortChannel0001  N/A
0002  PortChannel0002  N/A
0003  PortChannel0003  N/A
0004  PortChannel0004  N/A
```
We can see that the Protocols and Ports are invalid.
**after update:**
```
ssh -t …
```
=> [teamshow] Remove 't' from argument when calling docker exec

config/main.py
Fix a bug that config an interface to a new vrf failed.
Check the interface KEY existence instead of KFV in state_db, because of there is no `state` field in new schema.
Bind an interface to a new vrf and check interface master right.
=> [vrf] fix check state_db error when vrf moving

show/main.py
Fix `show int neighbor expected`
```
$ show int neighbor expected
File "/usr/bin/show", line 12, in <module>
File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return …
```
=> [show] Fix 'show int neighbor expected'

consutil/lib.py, consutil/main.py
Display remote device name in `consutil show` result table
Read remote device name from CONFIG_DB and append it to `consutil show` result table.
`-` will be displayed if there are no configured remote device name.
Build a deb and test it on a physical DUT with following CONSOLE_PORT configuration:
```json
"CONSOLE_PORT": {
"1": {
"remote_device": "switch1",
"baud_rate": "9600",
"flow_control": "1"
}
}
```
```bash
admin@sonic:~$ sudo consutil show
Line    Actual/Configured Baud    PID    Start Time
------  ------------------------  -----  ------------
0      9600/-              
1      9600/9600           
2      9600/-              
3      9600/- …
```
=> [consutil] Display remote device name in show command

config/main.py
Why I did:
config load_minigraph not working on Multi-asic platforms. 
Command config pfcwd start default now runs on all asic so if we using
it with ip netns exec asic0 it creates loop where asic0 can not reach redis server of other asic.
How I did:
pfcwd start default should be called only once.
Verified:
Tested on single and multi-asic platforms.
=> Fixed config load_minigrpah not working for Multi-asic platfroms.

config/main.py
Why I did:
config load_minigraph not working on Multi-asic platforms.
Command config qos reload now runs on all asic so if we using
it with ip netns exec asic0 it creates loop where asic0 can not reach redis server of other asic.
We need this PR https://github.com/Azure/sonic-utilities/pull/1123 in 201911 for complete fix.
How I did:
config qos reload should be called only once.
Verified:
Tested on single and multi-asic platforms.
=> [201911] Fix load minigraph for multi-asic platforms

show/main.py
Add the missing import of `netaddr` for `show ip interfaces`.
```
$ show ip interfaces
File "/usr/bin/show", line 12, in <module>
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
return …
```
=> [show] Add missing import to fix `show ip interfaces`

consutil/lib.py, consutil/main.py
- [update] removed actual baud from `consutil show` result table
- [refine] ensure only 1 db querying per command
- [refine] refactor code for better reusing in future
- [new] add a new return value `ERR_CFG` for indicating configuration issue
1. Add new constant `ERR_CFG` as the bad/missing configuration caused return code
1. Refactor code structure, include standardize the method naming/remove unnecessary methods/extract methods for future reusing
Build a deb and test it on a physical DUT with following CONSOLE_PORT configuration:
```json
"CONSOLE_PORT": {
"1": {
"remote_device": "switch1",
"baud_rate": "9600",
"flow_control": "1"
}
}
```
```bash …
```
=> [consutil] Remove actual baud and refactor lib for future change

README.md
Update README.md to reflect new sonic-utilities/sonic-utilities-data package creation schema
=> [README.md] Describe new package creation schema

utilities_common/bgp_util.py
call the vtysh script to get the information from Bgp container, instead of directly executing the docker commands
Modify the `run_bgp_command` function to call vtysh with correct instance_id and vtysh cmd.
The vtysh script is modified to take the namespace id in this PR https://github.com/Azure/sonic-buildimage/pull/5479
- On Multi ASIC
`admin@str-acs-2:~$ show ip bgp summary
IPv4 Unicast Summary:
asic0: BGP router identifier 8.0.0.0, local AS number 65100 vrf-id 0
BGP table version 12826
asic1: BGP router identifier 8.0.0.1, local AS number 65100 vrf-id 0
BGP table version 8913
asic2: BGP router identifier 8.0.0.2, local AS number 65100 vrf-id 0
BGP …
=> use vtysh in the show ip bgp summary command

config/console.py, config/main.py, tests/console_test.py
Support `console add` and `console del` commands under config command group. (More detail in HLD: https://github.com/Azure/SONiC/blob/master/doc/console/SONiC-Console-Switch-High-Level-Design.md#33121-adddel-console-port)
Added UT for commands.
1. Add new `console.py` file to support `config console` commands
1. Add UTs for console.py
1. UTs are all passed
1. Tested on a physical SONiC DUT, detail output below:
Initial state
```bash
admin@sonic:~$ sudo show line
Line    Actual/Configured Baud    PID    Start Time    Device
------  ------------------------  -----  ------------  --------
0      9600/-                                            -
1      9600/9600                                   switch1
2      9600/- …
```
=> [config/console] Support add/del console port setting commands

show/main.py, tests/mock_tables/config_db.json, tests/sflow_test.py
Changes:
-- show sflow use ctx.obj['db'] instead of creating new instance,
this is must for test, else config change will not be reflected.
-- config SFLOW tests for
config sflow <enable|disable>
config sflow agent-id <add | del>
config sflow collector add|del
config sflow interface <enable|disable>
config sflow interface sample-rate
Signed-off-by: Praveen Chaudhary <pchaudhary@linkedin.com>
Changes:
-- show sflow use ctx.obj['db'] instead of creating new instance,
this is must for test, else config change will not be reflected.
-- config SFLOW tests for
config sflow <enable|disable>
config sflow agent-id <add | del>
config sflow collector add|del
config sflow interface <enable|disable>
config sflow interface sample-rate
-- show sflow use ctx.obj['db'] …
=> [sflow_test.py]: tests for config sflow commands.

show/main.py
"show sflow interface" is updated to show all interfaces enabled for sflow
Updated sflow show command
Run "show sflow interface" and confirm all interfaces are displayed
show sflow interface
sFlow interface configurations
+-------------+---------------+-----------------+
| Interface | Admin State | Sampling Rate |
+=============+===============+=================+
| Ethernet4 | up | 10000 |
+-------------+---------------+-----------------+
| Ethernet12 | up | 10000 |
+-------------+---------------+-----------------+
| Ethernet16 | up | 10000 |
+-------------+---------------+-----------------+
| Ethernet26 | up | 10000 | …
=> Show sflow interface to display all interfaces enabled for sflow

scripts/watermarkstat
Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
Fix **_show queue watermark_** command failure when the queue doesn`t exist.
Change    `min_idx = float("inf")`  --> `min_idx = sys.maxint  `, because  cannot convert float infinity to integer
Execute` show queue watermark multicast` or `show queue watermark unicast`  when a multicast/unicast queue doesn`t exist.
> $ show queue watermark multicast 
> Traceback (most recent call last):
>   File "/usr/bin/watermarkstat", line 281, in <module>
>     main()
>   File "/usr/bin/watermarkstat", line 276, in main
>     watermarkstat.print_all_stat(table_prefix, args.type)
>   File …
=> Fix `show queue watermark` command fail

setup.py, tests/bgp_commands_test.py, tests/console_test.py, tests/counterpoll_test.py
To ensure a smooth transition once we stop installing the dependencies explicitly in the SONiC image.
We can upgrade dependencies selectively in the future.
Also had to replace single-quotes with double-quotes in expected Click error messages, as it seems the Click package installed via pip uses double quotes, whereas the package installed via Debian used single-quotes.
=> [setup.py] Pin external runtime dependencies at known working versions

README.md
Add instructions for setting up an environment to build the sonic-utilities package and run unit tests
Resolves https://github.com/Azure/sonic-utilities/issues/1160
=> [README.md] Add instructions for setting up a build/test environment

scripts/fast-reboot-dump.py
The ```ipaddress.ip_interface``` accepts only unicode string as input. However, an exception will be raised on python 2.
```
Oct 12 03:32:41.758040 str-dx010-acs-4 ERR fast-reboot-dump: Got an exception '192.168.0.240' does not appear to be an IPv4 or IPv6 interface: 
Traceback: 
#012  File "/usr/local/bin/fast-reboot-dump.py", line 298, in <module>
#012    res = main()
#012  File "/usr/local/bin/fast-reboot-dump.py", line 289, in main
#012    neighbor_entries = generate_neighbor_entries(root_dir + '/arp.json', all_available_macs)
#012  File "/usr/local/bin/fast-reboot-dump.py", line 42, in generate_neighbor_entries
#012    if ipaddress.ip_interface(ip_addr).ip.version != 4:
#012  File …
```
=> [fast-reboot] Fix unicode issue in ipaddress for python2

config/console.py, tests/console_test.py
* Support `config console remote_device` command
* Support `config console baud` command
* Support `config console flow_control` command
For more detail regarding the design, please refer to HLD(section 3.3.1.2.2/3.3.1.2.3/3.3.1.2.4): https://github.com/Azure/SONiC/blob/master/doc/console/SONiC-Console-Switch-High-Level-Design.md#3312-config
* Add new commands in `console.py` file to support update related `config console` commands
* Add UTs for new added commands
1. UTs are all passed
```
---------- coverage: platform linux2, python 2.7.16-final-0 ----------
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
config/console.py                             94 …
```
=> [config/console] Support update console configuration related commands

scripts/fast-reboot
Call BGP service script to do special handling of reboot process behavior.
This is part of cleanup that is being done for `fast-reboot` script as part of which service shutdown is handled by respective service script instead of populating fast-reboot script.
Updated `fast-reboot` script to call `systemctl stop bgp` instead of handling this in the script itself.
The service script is already created in `sonic-buildimage` repo as part of https://github.com/Azure/sonic-buildimage/pull/3992
Tested `warm-reboot`:
```
Oct 15 06:24:12.620808 str2-7060cx-32s-29 NOTICE admin: Stopping bgp ...
Oct 15 06:24:12.631107 str2-7060cx-32s-29 INFO systemd[1]: Stopping BGP container...
Oct 15 06:24:12.638316 str2-7060cx-32s-29 NOTICE admin: Stopping …
```
=> Modify fast-reboot script to use BGP script to stop bgp service

consutil/lib.py, consutil/main.py, show/main.py
Add `--brief` and `-b` option to show line command.
By default, show line command will render a table which includes all console lines in `CONSOLE_PORT` table and all `ttyUSB*` devices under `\dev`. We display `ttyUSB*` because we want to provide convenience to user when adding console line settings from scratch.
We add this optional option is for reduce noise for some user because the user are not allowed to connect a console line which is not present in CONFIG_DB.
Stop merge console line result into the result table when user specified `--brief` or `-b` option.
Build python-wheel package and tested on physical DUT.
N/A
**- New command output (if …
=> [consutil] Add brief option to show line command

config/vlan.py, doc/Command-Reference.md, show/vlan.py, tests/vlan_test.py, utilities_common/cli.py
Enable CLI management for proxy ARP setting
* Add `config vlan proxy_arp <vid> <enable/disable>
* Edits VLAN_INTERFACE table to set the "proxy_arp" setting for an interface
* Restarts the `ndppd` daemon running inside the SWSS container to grab changes
* Add proxy ARP info to `show vlan brief`
* Run unit tests
```
> show vlan brief
+-----------+-----------------+------------+----------------+-----------------------+
|   VLAN ID | IP Address      | Ports      | Port Tagging   | DHCP Helper Address   |
+===========+=================+============+================+=======================+
|      1000 | …
```
=> [config/show] Add CLI support for proxy arp

counterpoll/main.py, scripts/fast-reboot, setup.py, tests/counterpoll_input/config_db.json, tests/counterpoll_test.py
Counter polling is enabled via enable_counters script when booting
into new image and these configuration is written to config_db.
However, subsequent fast-reboot into the same image will have counter
polling enabled by default. This affect fast-reboot time. As a workaround,
we will disable counter poll when entering fast-reboot.
Fixes: Azure/sonic-buildimage#5107
Closes: Azure/sonic-buildimage#5107
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
Disable counterpoll when fast rebooting
Added new command to the counter poll command suite and then invoked it from fast-reboot
Unit test added
Verified on DUT
N/A
**- New command output (if the …
=> [counterpoll] Disable Counter Poll When Entering Fast Reboot

stdeb.cfg
stdeb.cfg was needed for building Debian package. Now that we build a Python wheel, it is no longer used.
=> Remove stdeb.cfg; no longer used now that we build as wheel

scripts/fdbshow, scripts/nbrshow
Following the plan in https://github.com/Azure/sonic-py-swsssdk/pull/89
1. fdbshow and nbrshow use SonicV2Connector with `decode_responses=True`
2. remove all the `decode()`
=> fdbshow and nbrshow use SonicV2Connector with decode_responses=True, and remove all the decode()

show/main.py, utilities_common/cli.py
Added platform ASIC count output to platform summary. Also added option for JSON output.
Added ASIC count in hardware info.
Manual CLI verification.
```
admin@str-s6000-acs-9:~$ show platform summary 
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom
```
```
admin@str-s6000-acs-9:~$ show platform summary 
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom
ASIC Count: 1
admin@str-s6000-acs-9:~$ show platform summary --json
{
"asic_count": 1, 
"asic_type": "broadcom", 
"hwsku": "Force10-S6000", 
"platform": …
```
=> [CLI][show][platform] Added ASIC count in the output.

show/interfaces/__init__.py
Remove `device2interface_dict` as it is no longer needed.
=> [show] Remove 'device2interface_dict'

fwutil/log.py
Cherry-pick changes of `fwutil/log.py` from https://github.com/Azure/sonic-utilities/pull/1008
* Reduced code duplication: replaced logger with common implementation
* Used logger from `sonic-py-common`
1. `fwutil install chassis component <component_name> fw <fw_path> -y`
2. `fwutil update chassis component <component_name> fw -y`
* N/A
* N/A
=> [201911][fwutil]: Use logger from sonic-py-common

scripts/route_check.py
Fix https://github.com/Azure/sonic-buildimage/issues/5804
By default, route_check.py will report an ERROR in syslog if route mismatch is detected, which is out of the control of monit config file and cause LogAnalyzer to report test error. This commit add an option (-s) to control this behavior. And log is not writen to syslog in default.
Add an option (-s) for ```route_checker.py```.
The update is verified on Arista-7260.
1. Add a static route whose nexthop is not reachable.
```
ip route add 1.1.1.1 via 192.168.1.101
```
2. Run ```route_check.py```, and error msg is only printed on stdout. Nothing is writen to syslog
3. Run ```route_check.py -s```. and error msg is writen to both stdout and syslog
4. Wait for 15 minutes, and …
=> [route_check]Add an option for route_check to control whether log is writen to syslog

show/fgnhg.py
- Replace tabs with spaces
- Fix alignment
- Remove trailing whitespace
- Remove spaces where not necessary, add spaces where necessary
- Reorganize imports per PEP8 standards
=> [show/fgnhg.py] Fix whitespace issues

sonic_installer/main.py
`sonic_installer` error message misses the filename due to string formatting error.
This fixes the missing string substitution in the message:
**Before (note that {} is missing the variable name.):**
```
Downloading image...
Image file '{}' is of a different type than running image.
If you are sure you want to install this image, use -f|--force.
Aborting...
Aborted!
```
**Now:**
```
Downloading image...
...95%, 724 MB, 57044 KB/s, 0 seconds left...   Image file 'sonic-broadcom.bin' is of a different type than running image.
If you are sure you want to install this image, use -f|--force.
Aborting...
Aborted!
```
Verified in a DUT, the error message is now printed correctly.
**- Previous command output (if the output of a …
=> SONiC installer - fix string formatting during image type check

consutil/lib.py, consutil/main.py, tests/console_test.py
Remove root privilege need for `consutil show` and `show line` command.
As discuss in this thread (https://github.com/Azure/sonic-buildimage/pull/5438), I am going to remove unnecessary root privilege need from console commands.
* Simply remove the check
* Add unit test for `consutil show` command
* Fix a known typo (found by adding unittest)
Build py-wheel package and install+test on a physical SONiC DUT
```
admin@sonic:~$ show line
Root privileges are required for this operation
```
```
admin@sonic:~$ show line
Line    Baud    PID    Start Time    Device
------  ------ …
```
=> [consutil][show] Remove root need from show line command

clear/main.py, connect/main.py, consutil/main.py, doc/Command-Reference.md
Support `--devicename` and `-d` option for sonic-clear/connect line commands
Add missing options.
Tested on physical SONiC DUT with below initial configuration.
```
admin@sonic:~$ sudo show line -b
Line    Baud    PID    Start Time    Device
------  ------  -----  ------------  --------
1    9600      -             -   switch1
```
```
admin@sonic:~$ sudo connect line --devicename switch1
Usage: connect line [OPTIONS] LINENUM
Try "connect line -h" for help.
Error: no such option: --devicename
admin@sonic:~$ sonic-clear line --devicename switch1
Usage: sonic-clear line [OPTIONS] LINENUM
Try "sonic-clear line -h" for help.
Error: no such option: …
```
=> [connect][clear] Support --devicename option for connect/clear line commands

config/main.py, scripts/db_migrator.py
Proposed fix for missing `FEATURE` table during warm-upgrade from 201811to 201911.
Fixes: https://github.com/Azure/sonic-buildimage/issues/5738
FEATURE table is a part of 201911 image database, but absent in 201811 images. The warm upgrade from 201811 image to 201911 image fails as the feature table is missing in the DB and multiple errors are seen in syslog.
This PR fixes DB_MIGRATOR code to update missing init_cfg tables into config_db.
Iterate through the tables in `/etc/sonic/init_cfg.json`, if a table is found missing in `configDB`, update the `configDB` with the missing table. Otherwise, ignore it, so to avoid overriding `configDB` tables with `init_cfg`.
Error is easily reproducible. Manually tested the fix by modifying …
=> Fix db_migrator to copy missing values from INIT_CFG to config_db

acl_loader/main.py, config/config_mgmt.py, config/main.py, config/nat.py, scripts/db_migrator.py, scripts/fanshow, scripts/fdbclear, scripts/fdbshow, scripts/natclear, scripts/natshow, scripts/nbrshow, scripts/neighbor_advertiser, scripts/psushow, scripts/tempershow, show/fgnhg.py, show/main.py, sonic_installer/main.py, tests/mock_tables/dbconnector.py
This is the following step for merging sonic-py-swsssdk into sonic-swss-common https://github.com/Azure/sonic-swss-common/pull/387
Unit test and tested in DUT
=> Replace swsssdk.SonicV2Connector with swsscommon.SonicV2Connector (SWIG wrapper of C++ implementation) in production code

show/main.py
`show int neighbor expected` only show one member interface for
portchannel with multiple member interfaces. This is because
`device2interface_dict` only stores mapping from one device to one
port.
```
$ show int neighbor expected
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet64   ARISTA01T0  Ethernet1       None                10.64.247.144   ToRRouter
Ethernet4    ARISTA01T2  Ethernet2       None                10.64.247.136   SpineRouter
Ethernet68 …
```
=> [201911][show] Fix 'show int neigh expected'

utilities_common/bgp_util.py
Function `is_ipv6_address` and `is_ipv4_address` use `ipaddress` as
function argument, which override the module in global namespace.
Fix Azure/sonic-buildimage#5440
```
$ show ip bgp sum
File "/usr/bin/show", line 12, in <module>
File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return …
```
=> [show] Fix `show ip bgp sum`

scripts/generate_dump
Add support to collect tech support on multi ASIC platform
Refactored code to put together related commands in a function.
Modified generate_dump script to run relevant commands on all namespaces for multi ASIC platform. On single ASIC the commands are run in default (host) namesapce.
Manual verification, and pytest.
```
samaddik@str-serv-acs-14:/var/sonic-mgmt/tests$ pytest show_techsupport/test_techsupport.py --testbed=vms12-t1-lag-1 ....
========= 2 passed in 7049.32 seconds ======
For 2 ASIC output (ASIC hardcoded to 2):
admin@str2-nswitch-acs-4:/var/dump/sonic_dump_str2-nswitch-acs-4_20201105_015555/dump$ ls
APPL_DB.json                             ip.bgp.neighbor.fc00::2.rcv1
APPL_DB.json.1 …
```
=> [show][techsupport][multi-ASIC] Add support to collect tech support on multi ASIC platform

tests/sku_create_test.py
I removed the output directory of the SKU create pytest before execution of the script, otherwise the pytest execution will fail when run for the second time.
I checked for existence of the output directory and if it exists, I remove it.
Run SKU creator pytest for the second time and ensure it runs successfully.
None
None
=> Remove SKU create pytest output directory before execution of the script

consutil/lib.py, consutil/main.py, tests/console_test.py
Remove root privilege need for `consutil connect` and `show line` command.
As discuss in this thread (https://github.com/Azure/sonic-buildimage/pull/5438), I am going to remove unnecessary root privilege need from console commands.
* Base on this change (https://github.com/Azure/sonic-buildimage/pull/5840), we are safe to remove the root need from `consutil command`
* Add unit tests for `consutil connect` command
Build py-wheel package and install+test on a physical SONiC DUT
```
admin@sonic:~$ consutil connect 1
Root privileges are required for this operation
```
``` …
```
=> [consutil][connect] Remove root need from connect line command

config/main.py, show/main.py, tests/mock_tables/config_db.json, tests/sflow_test.py
* Add mVRF support and options to CLICK CLI
Signed-off-by: Garrick He <garrick_he@dell.com>
Add options to allow mVRF configuration for sFlow collectors
Update the show/main.py and confg/main.py scripts
Check output of CLICK CLI:
```
admin@sonic:~$ sudo config sflow collector add col1 1.1.1.1 --port 1111 --vrf mgmt
admin@sonic:~$ show sflow
sFlow Global Information:
sFlow Admin State:          down
sFlow Polling Interval:     default
sFlow AgentID:              default
1 Collectors configured:
Name: col1                IP addr: 1.1.1.1         UDP port: 1111   VRF: mgmt
admin@sonic:~$ sudo config sflow collector add col2 1.1.1.2
admin@sonic:~$ show sflow
sFlow Global Information:
sFlow Admin State:          down
sFlow Polling …
```
=> [sflow] Add mVRF support

config/feature.py
If FEATURE table is not present in CONFIG_DB.
When I issue - "config feature state nat enabled", seeing below errors
root@sonic:/home/admin# config feature state nat enabled                                                                                                                                     
Feature 'nat' doesn't exist                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                           
File "/usr/local/bin/config", line 10, in <module> …
=> Added 'import sys' in feature.py file

scripts/natconfig, scripts/natshow
After migrated to Python 3, seeing some issues in NAT show commands like shown an example below
root@sonic:/home/admin# show nat translations count
()
Static NAT Entries ..................... 2
Static NAPT Entries ..................... 0
Dynamic NAT Entries ..................... 0
Dynamic NAPT Entries ..................... 0
Static Twice NAT Entries ..................... 0
Static Twice NAPT Entries ..................... 0
Dynamic Twice NAT Entries ..................... 0
Dynamic Twice NAPT Entries ..................... 0
Total SNAT/SNAPT Entries ..................... 1
Total DNAT/DNAPT Entries ..................... 1
Total Entries ..................... 2
()
After fix:
root@sonic:/home/admin# show nat translations count
Static NAT Entries ..................... 2 …
=> NAT show commands newline issue after migrated to Python3

show/main.py, utilities_common/cli.py
Added platform ASIC count output to platform summary. Also added option for JSON output.
Note: This is a merge from "master".
Added ASIC count in hardware info.
Manual CLI verification.
```
admin@str-s6000-acs-9:~$ show platform summary 
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom
```
```
admin@str-s6000-acs-9:~$ show platform summary 
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom
ASIC Count: 1
admin@str-s6000-acs-9:~$ show platform summary --json
{
"asic_count": 1, 
"asic_type": "broadcom", 
"hwsku": …
```
=> [CLI][show][platform] Added ASIC count in the output. (#1185)

config/main.py, show/main.py, tests/bgp_commands_test.py, tests/mock_tables/config_db.json, utilities_common/bgp_util.py
Updates to bgp config and show commands with the movement of internal bgp sessions to a new table BGP_INTERNAL_NEIGHBOR table. 
With the introduction of BGP_INERNAL_NEIGHBOR table, the user cannot start/stop/remove internal neighbors which I feel is not needed as these internal bgp sessions which are supposed to be UP allways.
Updated the show/bgp util so that it gets the internal bgp sessions from BGP_INTERNAL_NEIGHBOR table.
Removed the API's to get the local_as in config/bgp which is not required now. 
Made sure that the output remain same with the new internal bgp neighbor table.
```
admin@:~$ show ip bgp summary  
IPv4 Unicast Summary:
asic0: BGP router identifier 10.0.107.16, local AS number 65100 vrf-id 0
BGP table version …
```
=> Updates to bgp config and show commands with BGP_INTERNAL_NEIGHBOR table

tests/mock_tables/dbconnector.py
The python2 behavior is not changed.
=> Fix mock SonicV2Connector in python3: use decode_responses mode so caller code will be the same as python2

config/main.py, show/main.py, sonic-utilities-tests/bgp_commands_test.py, sonic-utilities-tests/mock_tables/config_db.json, utilities_common/bgp_util.py
Including the BGP internal neighbor tables changes in 201911 , https://github.com/Azure/sonic-utilities/pull/1224
=> [201911] Updates to bgp config and show commands with BGP_INTERNAL_NEIGHBOR table (#1224)

setup.py
The `requests` package is used by a couple modules (config/kube.py and scripts/neighbor_advertiser), but it was not specified as an install-time dependency. Now that the package is built as Python 3, some commands are crashing with `ModuleNotFoundError: No module named 'requests'`.
=> Add 'requests' as install dependency in setup.py
