sonic-net/sonic-utilities

.gitignore
README.md
setup.py
stdeb.cfg

Dependency package builds have changed; Adjust accordingly

---

scripts/teamshow
setup.py

[teamshow]: Add teamshow script to display the LAG status

---

scripts/teamshow

Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

[teamshow]: Update teamshow according to the update of minigraph.py

---

.gitignore
scripts/decode-syseeprom
scripts/sfputil

- Also unrelated update of .gitignore

[scripts]: Update sonic-cfggen path to /usr/local/bin

---

scripts/fast-reboot

Otherwise the switch freezes sometimes.

Stop opennsel before fast-reboot.

---

scripts/generate_dump
scripts/lldpshow
setup.py
sonic_cli/main.py

Fixed the following commands which were broken:
- `show version`
- `show platform`
- `show lldp table`
- `show techsupport`
Also some other cleanup.

[CLI]: Fix broken commands

---

scripts/teamshow

[Teamshow]: Add port channel status to the teamshow result

---

sonic_cli/main.py

Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

[sonic_cli]: Add build commit ID to show version command

---

scripts/teamshow

[Teamshow]: return N/A if no memember exists in the team

---

scripts/generate_dump

improve app/sai/counter db dump performance
get bgp neighbor received routes

archive coredump files in the generate_dump

---

scripts/portstat
sonic_cli/main.py

[portstat]:add packet rate and port state in portstat

---

sonic_installer/main.py

1. support sonic_installer in aboot
2. add progress bar for download image
3. show current/next/available image in list command

support sonic_installer in aboot

---

scripts/generate_dump
show/main.py

- Now also dumping the following commands in "generate_dump":
- show version
- show platform summary
- show platform syseeprom
- sensors
- Run generate_dump using sudo in 'show techsupport'

[generate_dump]: 	Add commands to 'generate_dump'; run with sudo in 'show'

---

show/main.py

- Add 'show interfaces sfp' subcommand to wrap sfputil
- Remove 'sfp' arg from 'show interfaces' command
- Add '-p/--period' argument and '-c/--clear' flag to 'show interfaces
counters'
- Add missing docstrings for Click
- Add sudo to all 'vtysh', 'docker', 'lldpctl', 'lldpshow' and 'sensors' calls

Enhance 'show' command

---

scripts/dropcheck
setup.py

- This tool could be used in monit to check periodically and exit 1
when the drop exceeds certain threshold for monit to alert in syslog.

[dropcheck]: Add the dropcheck as a script to sum up drop counters in a duration

---

config/main.py

[config]: Add 'config bgp shutdown all' and 'config bgp startup all' commands

---

config/main.py

[config]: Add 'config interface shutdown/startup' commands

---

scripts/fast-reboot

Otherwise teamd gets all LAGs down and FR failed

[Fast-reboot]: Make FR working again for 0.9.4

---

sfputil/main.py

Resolves https://github.com/Azure/sonic-utilities/issues/99

[sfputil]: Catch NotImplementedError, print message and exit gracefully

---

scripts/fdbshow

Fix added to continue if br_port_id not in oid_map

Continue processing next fdb entry if bridge port index not in list

---

sonic_psu/psu_base.py

Small changes for correct import PSU plugin inside SNMP docker

[PSU] Small changes for correct PSU plugin import

---

psuutil/main.py

Change the format of PSU CLI to align it with SONiC CLI output template

Align PSU CLI output with SONiC CLI output template

---

scripts/ecnconfig

Updated db access API to use mod_entry instead of set_entry
Utility should not remove entries which were not set

[ecnconfig] Fix db access from set to mod

---

acl_loader/main.py

Signed-off-by: marian-pritsak <marianp@mellanox.com>

[acl-loader]: Add 'delete' command

---

config/main.py

[config] Update ACLs in load_minigraph if ACL config is present

---

show/main.py

Fix ‘show aaa/tacacs‘ return error without aaa/tacacs configuration
Check if aaa and tacacs configuration in config_db
show aaa without aaa configuration
```
AAA authentication login local (default)
AAA authentication failthrough True (default)
AAA authentication fallback True (default)
```
-->

[TACACS+]: Fix aaa show error without configuration

---

acl_loader/main.py

Which is the root cause for https://github.com/Azure/sonic-utilities/issues/201.
-->

Fix an acl_loader crash issue when appdb is not consistent with cfgdb

---

config/main.py
psuutil/main.py
scripts/decode-syseeprom
scripts/generate_dump
scripts/reboot
show/main.py

Read platform information from `DEVICE_METADATA` table. This is to adapt changes in https://github.com/Azure/sonic-buildimage/pull/1397.

Adapt to config engine change to load platform info properly

---

scripts/fast-reboot
scripts/fast-reboot-dump.py

I adapted the fast reboot-dump script to support updated SAI version
FDB entry depends on bvid. I get this IP from SAI vlan object.
sudo /usr/bin/fast-reboot-dump.py
-->

[Fast-Reboot]: Adapt fast-reboot-dump script for SAIv1.2 

---

acl_loader/main.py

When there were error parsing acl rules, print / syslog error and skip current rule instead of crash the process immediately

[acl-loader] Not to crash upon invalid rule

---

pfcwd/main.py

Add cli to enable/disable BIG_RED_SWITCH mode
Tested on DUT
-->

[pfcwd]: add cli to enable/disable BIG_RED_SWITCH mode

---

show/main.py

- Also some minor code cleanup/unification

[show] Commands now support 'verbose' flag; Only display underlying commands if flag is passed

---

scripts/portconfig

FEC mode configuration support
Python script `portconfig `modified
Using `portconfig `command and check port status
```
admin$ portconfig --help
usage: portconfig [-h] [-v] -p PORT [-l] [-s SPEED] [-vv]
Set SONiC port parameters
-h, --help            show this help message and exit
-v, --version         show program's version number and exit
-p PORT, --port PORT  port name (e.g. Ethernet0)
-l, --list            list port parametars
-s SPEED, --speed SPEED
port speed value in Mbit
-vv, --verbose        Verbose output
```
```
admin$ portconfig --help …
```

Added support to configure fec mode on interface

---

acl_loader/main.py

The title shall be : Table instead of Rule ID

[acl-loader]: Change the header from Rule ID to Table

---

acl_loader/main.py

This option enables the ability to only do the full update within
this table, which means that only this table will be cleared and
reinstalled with the new rules from the JSON file.

[acl-loader]: Add --table_name option to update full operation

---

acl_loader/main.py

[acl_loader]: Missing one colon

---

acl_loader/main.py
config/main.py
config/mlnx.py
counterpoll/main.py
data/etc/bash_completion.d/counterpoll
pfcwd/main.py
psuutil/main.py
scripts/generate_dump
scripts/portconfig
setup.py
sfputil/main.py
show/main.py
sonic_installer/main.py

Merged changes from master branch to 201803 branch
Created a PR
-->

Merge master changes to 201803

---

counterpoll/main.py

Add support to enable/disable counter query
User can use counterpoll queue/port enable/disable to control the counter query.
Tested on DUT
-->

[counterpoll]: add support to enable/disable counter query

---

pfcwd/main.py

[pfcwd]:enable/disable counter poll

---

pfcwd/main.py

Fix small issue in cli'

---

clear/main.py
connect/main.py
consutil/lib.py
consutil/main.py
data/etc/bash_completion.d/connect
data/etc/bash_completion.d/consutil
setup.py
show/main.py

Added skeleton code for CLI for connecting to switches via console device
Includes new consutil directory, new connect directory, and added functions to show and clear
Command format: show line, clear line <line number>, connect line <line number>

Console show/clear/connect skeleton

---

pfcwd/main.py

Add knob to start pfcwd for all ports
Test on DUT
-->

[pfcwd]: add knob to start pfcwd for all ports

---

consutil/main.py

":" was missing, also all other places are checking against 0 instead of ""

Fix the syntax eror with if statement

---

show/main.py

add a command to show interface neighbor metadata i.e. expected data
get 2 set of data from the database and output in table format
run "show interface neighbor expected"
None 
```
admin@sonic:~$ show interfaces neighbor expected            
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet112  ARISTA01T1  Ethernet1       None                172.16.140.124  LeafRouter
Ethernet116  ARISTA02T1  Ethernet1       None …
```

[show] Add 'show interface neighbor expected' command

---

config/main.py
config/mlnx.py

Improved `config load_minigraph` command.
1. I make a list of services instead of having list of commands to run
2. Use systemctl instead of service, which is a wrapper around systemctl
Copy the changes into `/usr/lib/python2.7/dist-packages/config` and issue
`sudo config load_minigraph`
-->

Use systemctl utility instead of service utility in config

---

scripts/ecnconfig

Signed-off-by: Wenda Ni <wenni@microsoft.com>
Tested on DUT with https://github.com/Azure/sonic-swss/pull/577
-->

ecnconfig: add show and change ECN on/off status on queues 

---

config/main.py

[config]: Change del to remove

---

pfcwd/main.py

When PFCWD starts by default, enable it on all ports.
-->

[pfcwd]: enable pfcwd on all port by default

---

scripts/fast-reboot

[mellanox] Fail if FW upgrade fails during fast-reboot

---

config/main.py

Include /etc/sonic/sonic_version.yml to obtain the asic_type info in genertating qos.json

---

config/main.py

config port_channel add <port_channel_name>
config port_channel del <port_channel_name>
config port_channel member add <port_channel_name> <port_name>
config port_channel member del <port_channel_name> <port_name>

[config]: Add port channel related commands

---

pfcwd/main.py

Signed-off-by: Guohan Lu <gulv@microsoft.com>
-->

require root privilege for all pfcwd configuration commands

---

show/main.py

- Eliminate the need to write template files to disk in both "show platform summary" and "show version"
- Now catching exception if we cannot retrieve HwSKU from ConfigDB and display "Unknown" as result

[show] Eliminate need for writing template files for 'show platform summary' and 'show version'

---

config/main.py

Add a "-l/--load-sysinfo" option for "config reload" to merge the system info on device
The information includes:
-- platform string
-- system mac
-- port configuration: alias, lanes, speed, index
This is useful when we first load the configuration from config_db.json generated
outside which does not have the information on the device.
The default behaviour is not changed, so it won't impact the system unless you use this option.
This can be used for ZTP to config the box the first time and avoid any addtional work
which could cause inconsistency.
Add option for "config reload" to merge system info.
Add option for "config reload" to merge system info.
Use config_db.json without the system info like mac, port lane info etc, then do …

Add option for "config reload" to remove the dependency of individual box information in config_db.json

---

show/main.py

Updated  the show vlan brief command to populate the correct output
I updated the show vlan brief function to connect to the configdb and fetch the output. I then parsed the output and presented it in a tabular format
Had a SONiC lab device that I used to verify the output of my change
```
bridge name     bridge id               STP enabled     interfaces
Bridge          8000.3417eb41ac00       no              Ethernet10
Ethernet11
Ethernet12
Ethernet13
Ethernet14
Ethernet15
Ethernet22
Ethernet23
Ethernet24
Ethernet25
Ethernet26
Ethernet27
Ethernet28
Ethernet29
Ethernet30
Ethernet31
Ethernet32
Ethernet33
Ethernet36
Ethernet37
Ethernet38
Ethernet39 …
```

[show] Refactor show vlan brief to use configdb and update the output

---

pfcwd/main.py

pfcwd cmd check

---

pfcwd/main.py

1) default restoration time to 2 times detection time if it is not defined;
2) check if options are prefixed with "--"; 
3) add example command.
$ sudo pfcwd start --action drop ports Ethernet4 detection-time 200
restoration time not defined; default to 2 times detection time: 400 ms
$ sudo pfcwd start --action drop ports Ethernet4 detection-time 200 restoration-time 999
Usage: pfcwd start [OPTIONS] [PORTS]... DETECTION_TIME
Error: Bad command line format. Try 'pfcwd start --help' for usage
-->

pfcwd start commd pre-check fix

---

scripts/mmuconfig
setup.py
show/main.py

1) list all buffer pools and profiles
2) Change alpha if the corresponding profile uses dynamic thresholding
On dut:
1) list 
$ sudo ./mmuconfig -l                                
Pool: ingress_lossless_pool
----  --------
xoff  3855488
type  ingress
mode  dynamic
size  11213696
----  --------
Pool: egress_lossless_pool
----  --------
type  egress
mode  static
size  15982720
----  --------
Pool: egress_lossy_pool
----  -------
type  egress
mode  dynamic
size  9532224
----  -------
Profile: pg_lossless_100000_5m_profile
----------  -----------------------------------
xon_offset  2288
dynamic_th  -4
xon         2288
xoff        165568
pool        [BUFFER_POOL|ingress_lossless_pool]
size        1248
----------  -----------------------------------
Profile: …

Add mmuconfig

---

scripts/fast-reboot
scripts/warm-reboot
setup.py

Design doc is at https://github.com/Azure/SONiC/blob/master/doc/warm-reboot/system-warmboot.md

Implement warm-reboot script

---

config/main.py
config/mlnx.py
show/main.py
show/mlnx.py

Reverted because of the issue https://github.com/Azure/sonic-utilities/pull/345#issuecomment-431185231

Revert "Some improvement for Mellanox sniffer CLI (#345)"

---

show/main.py

Updated ```show vlan brief``` to include tagging info for ports
I updated the existing ```show vlan brief``` function to show the tagging info as well
Verified using the lab test machine
```
+-----------+--------------------------+-------------+-----------------------+
|   VLAN ID | IP Address               | Ports       | DHCP Helper Address   |
+===========+==========================+=============+=======================+
|       101 | 10.86.96.1/29            | Ethernet0   |                       |
|           | 2603:10b0:50a:82d9::1/64 |             |                       |
+-----------+--------------------------+-------------+----------------- …
```

[show] Updating 'show vlan brief' to show tagging info

---

clear/main.py
config/main.py
counterpoll/main.py
scripts/watermarkcfg
scripts/watermarkstat
setup.py
show/main.py

Add Cli and scripts for Watermark feature
[High Level Design Document](https://github.com/Azure/SONiC/blob/694754ac31c77724f43458e2779b552223791974/doc/watermarks_HLD.md)
Added 2 scripts:
- watermarkstat
- watermarkcfg
Extended show, clear and config CLI groups.
```
~$ show priority-group watermark shared
Ingress shared pool occupancy per PG:
Port    PG0    PG1    PG2    PG3    PG4    PG5    PG6    PG7
-----------  -----  -----  -----  -----  -----  -----  -----  -----
Ethernet0     96      0      0      0      0      0      0      0
Ethernet4     96      0      0      0 …
```

[watermarks] add watermarkstat, watermarkcfg and aliases

---

config/main.py

[config]: Change from 'cli' to 'config' for watermark cmd

---

scripts/ecnconfig

ecnconfig check against invalid argument value (#343)

---

acl_loader/main.py

Add .version to get the version of the IP

[acl_loader]: Fix IP match bug for checking IP version

---

scripts/fast-reboot

Depends on https://github.com/Azure/sonic-sairedis/pull/391
While executing system level warm reboot. Invoke 2 stage SAI shutdown the minimize the control plane down time.

[warm reboot] add 2-stage SAI shutdown support for system level warm reboot

---

scripts/fast-reboot
show/mlnx.py

Added support for mellanox fast-fast boot
Added support for mellanox fast-fast boot
Run "warm-reboot" CLI command and verify that all is up after reboot
N/A
N/A

[mlnx|ffb]: Add fast-fast flow in fast(warm)-reboot script

---

scripts/fast-reboot

Provide option to reboot with "kexec -e".
There is a difference of 10-16 seconds between "kexec -e" and "reboot" methods. Adding the option to use either. So test would be easier.

[warm reboot] provide option to reboot with "kexec -e"

---

config/main.py
show/main.py

Added teamsyncd timer for WR mode
Added a command into config interface
`sudo config warm_restart teamsyncd_timer 60`
-->

Add support for teamsyncd_timer

---

show/main.py

Make it aligned with config mirror_session command

[show]: Change show mirror session to show mirror_session

---

scripts/intfstat
sonic-utilities-tests/intfstat_test.py

Fixed variable name. On some corner case got a variable referenced before assignment.
-->

[intfstat] fix variable name

---

scripts/neighbor_advertiser
setup.py

Neighbor Advertiser Script
Set:
- set address mapping <vlan_mac : vlan_ip> on Ferret server
- set mirror encap tunnel (arp)
- set vxlan decap tunnel
Reset:
- reset mirror encap tunnel (arp)
- reset vxlan decap tunnel

neighbor advertiser script

---

scripts/route_check.py
sonic-utilities-tests/route_check_test.sh

Created a tool to verify ASIC-DB Route entries against Routes & Interfaces from APPL_DB.
-->

Tool to verify ASIC route entries against APPL-DB ROUTE & INTF tables

---

setup.cfg
setup.py

Tests were written using pytest framework. Should not use unittest framework to run the test in the setup.py. 
run python setup.py --command-packages=stdeb.command bdist_deb
-->

use pytest in setuptools

---

scripts/neighbor_advertiser

Update neighbor advertiser script:
1.  add the support of vip list, and try to iterate until setup getting successful
2.  add return value, 0 if no error, -1 otherwise
3.  change -s (vips) parameter to optional, only required in 'set' mode

Update neighbor advertiser

---

scripts/neighbor_advertiser

Fix a run time string exception
Invoke the script to with set/reset operations.

[neighbor advertiser] convert int to string before concatenating

---

show/main.py

Reference: Pull request #2746
Run "show aaa" command and you would see default value for failthrough as false.
-->

In sync with our latest change, where we default failthrough to be False

---

scripts/fast-reboot
scripts/fast-reboot-dump.py

1. Add exception handling in fast-reboot-dump.py. 
2. If we catch any exception in fast-reboot-dump, stop fast-reboot procedure
Modification of the scripts
Copy changed files in your dut and run fast-reboot command
-->

If fast-reboot-dump gives an error, don't continue with fast-reboot

---

scripts/decode-syseeprom

Added a new option -p to display the Product Name.

decode-syseeprom : added new option to show the Product Name.

---

scripts/neighbor_advertiser

- update scheme variable name
- align with Ferret server update

Update scheme variable name in Neighbor Advertiser

---

scripts/db_migrator.py

Enable the existing DB migration code
warm boot from before PFC_WD table rename to after.

[201811] enable DB migrator code

---

acl_loader/main.py

[acl_loader]: Add policer attribute in show mirror_session command

---

config/main.py

[config]: Add --policer option for mirror session

---

scripts/neighbor_advertiser

- update neighbor_advertiser
- use vlan members to set up acl

neighbor_advertiser: use vlan members to set up acl

---

doc/Command-Reference.md

Command Line Interface manual is moved from Azure/SONiC repository to sonic-utilities repository so that all developers can update this manual whenever they do any changes in the code related to CLI.
-->

Add SONIC CLI Manual

---

acl_loader/main.py
show/main.py

```
root@sonic:# show policer
Name    Type     Mode      CIR    CBS
------  -------  ------  -----  -----
test    packets  sr_tcm    100    100
```

[show]: Add show policer command

---

config/main.py

Add below two commands:
config acl add table <table_name> <table_type>
config acl remove table <table_name>
note:
add table supports description and ports

[config]: Add config acl add/remove table command

---

show/main.py

Submitted by: vapatil@linkedin.com
Editeddescription of "show bgp" CLI command to be consistent with other commands
Changed the description test
Using the command. Show ?
"BGP information"
"Show BGP information"
-->

[main.py] Edit comment as test fix.

---

scripts/db_migrator.py

* add '-s' option to db_migrator
Signed-off-by: Lawrence Lee <t-lale@microsoft.com>
Add support to db_migrator to specify unix socket
Add new option to db_migrator.py and pass it to ConfigDBConnector
Start a redis instance listening on a non-default unix socket, then pass the socket with the '-s' option to db_migrator.py

[scripts]: add support to db_migrator for non-default unix socket

---

acl_loader/main.py

Reverts Azure/sonic-utilities#447

Revert "show acl table command output should show binding column correctly ev…"

---

debug/aliases.ini
debug/main.py
scripts/generate_dump
undebug/aliases.ini
undebug/main.py

**Please don't merge!!!**
Reworked "debug" commands for BGP and zebra. Currently FRR and quagga supported simultaneously. 
Used click library
Build it and install to your dut.
-->

[debug][undebug] Rework of CLI for BGP

---

config/main.py

I've added commands to add/del dhcp_helpers from a vlan. 
Added some new methods to the config/main.py file to support adding and removing IP's for dhcp_relay.
```
admin@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/config$ show vlan brief
+-----------+--------------+-----------------------------+----------------+-----------------------+
|   VLAN ID | IP Address   | Ports                       | Port Tagging   | DHCP Helper Address   |
+===========+==============+=============================+================+=======================+
|      1000 |              | fortyGigE0/24,fortyGigE0/28 | untagged       | 192.0.0.1             |
|           |              |                             |                | 192.0.0.2 …
```

[config] Add commands to add/remove DHCP server address from a VLAN

---

scripts/neighbor_advertiser

This part of the change is needed in 201811 branch.

[neighbor_advertiser] hand pick partial change from #525

---

clear/bgp_frr_v6.py
clear/main.py
show/bgp_frr_v6.py
show/main.py

1. Fixed internal sonic commands (show and clear) to support new FRR
2. Fixed some bugs ('show ipv6 interfaces' gave syntax error)
3. Introduces 'show ipv6 prefix-list' command
Checking commands in vtysh and fixing non-working variants.
Build a new image and run commands on the console
-->

Fix bgp 'show' and 'clear' commands

---

.github/PULL_REQUEST_TEMPLATE.md

Modify the PR template: add reminder to add/modify/remove unit tests as appropriate.

[PR template] Add reminder to add/modify/remove unit tests as appropriate

---

doc/Command-Reference.md

[command reference] add warm reboot command document

---

scripts/configlet
setup.py

Added a generic configlet application script.

---

scripts/db_migrator.py

Adding LOOPBACK interface to db migrate script for supporting https://github.com/Azure/sonic-swss/pull/943

Adding LOOPBACK interface to db migrate script

---

doc/Command-Reference.md

Updated command reference. Added info about show RIF counters commands.

[command reference] Update show int counters info with l3 RIF

---

scripts/fast-reboot
scripts/watchdog
setup.py

To prevent from device hanging during fast/warm reboot

Enable HW Watchdog for fast/warm reboot

---

scripts/update_json.py
setup.py

This tool would be used to update /etc/sonic/core_analyzer.rc.json file to add
credentials by HW proxy.

A generic JSON file updater, which can add/update-existing attributes.

---

config/main.py

- What I did
Merge two vrf configuration to avoid user can't add or delete management VRF through CLI.
config vrf add mgmt
show mgmt-vrf
config vrf del mgmt
show mgmt-vrf
config vrf add Vrf-blue
show vrf
config vrf del Vrf-blue
show vrf

[config] Merge duplicate vrf configuration

---

doc/Command-Reference.md

Add document for warm restart use case

---

sonic_installer/main.py

* use swsssdk lib API instead of redis-cli

[MultiDB] refactor docker warm reboot codes

---

config/main.py

Added check if service existis before start/stop/restart of service.
This is possible if some of docker are not built then corresponding
service file will not be present
Read the generated services from file and check against it for service existence. 
N/A
Disable NAT docker and run config reload and see no error comes w.r.t NAT service

[config] Check if service exists before start/stop/restart of service

---

config/main.py

add stop/restart services messages in syslog
add syslog messages to config load_minigraph/reload
help future debugging

[config]: add syslog messages to config load_minigraph/reload

---

doc/Command-Reference.md

Added sFlow feature command reference
sFlow show and config commands
NA
NA

Update Command Reference with sFlow section

---

config/main.py

Reverts Azure/sonic-utilities#822

Revert "FIX the issue "config load_minigraph -y" command fails"

---

clear/main.py
config/aaa.py
config/main.py
config/mlnx.py
psuutil/main.py
scripts/boot_part
scripts/decode-syseeprom
scripts/fdbshow
scripts/natconfig
scripts/nbrshow
scripts/neighbor_advertiser
scripts/pcmping
scripts/portstat
scripts/sonic-kdump-config
sfputil/main.py
show/bgp_frr_v6.py
show/bgp_quagga_v4.py
show/bgp_quagga_v6.py
show/main.py
sonic_installer/main.py
ssdutil/main.py
utilities_common/util_base.py

- Fix Python warnings flagged by "LGTM" plugin.
- Also make all 'except' statements Python3-compliant

Fix Python warnings

---

clear/bgp_frr_v6.py
clear/bgp_quagga_v4.py
clear/bgp_quagga_v6.py
config/main.py
config/nat.py
fwutil/lib.py
pddf_fanutil/main.py
pddf_psuutil/main.py
pddf_thermalutil/main.py
psuutil/main.py
scripts/aclshow
scripts/ecnconfig
scripts/intfstat
scripts/intfutil
scripts/natshow
scripts/nbrshow
scripts/neighbor_advertiser
scripts/pfcstat
scripts/queuestat
scripts/sonic-kdump-config
scripts/teamshow
sfputil/main.py
show/main.py
sonic_installer/main.py

- Fix more Python warnings flagged by "LGTM" plugin.

Fix even more Python warnings

---

README.md

add lgtm and jenkins build badge

[doc]: add ltgm and jenkins badge

---

config/main.py

Reverts Azure/sonic-utilities#857

Revert "[config] Implement a process level lock"

---

show/bgp_frr_v4.py
show/bgp_frr_v6.py
show/bgp_quagga_v4.py
show/bgp_quagga_v6.py

Port https://github.com/Azure/sonic-utilities/pull/901 to the 201911 branch.

[201911][show] Fix abbreviations for 'show ip bgp ...' commands

---

scripts/generate_dump

[showtech]: add knet dump information in show tech

---

scripts/fanshow
scripts/tempershow

* [thermal fix] use natural sort for fan status and thermal status
* [thermal fix] set fan status to N/A when fan is removed
* Adjust header name for show platform temperature output
Merge thermal control related PRs from master to 201911
Cherry-pick all PRs related to thermal control and resolve conflict manually
Manual test on SN4700, SN4600C and SN3420

[201911][thermal control] Backport changes from master branch

---

config/main.py

Backport https://github.com/Azure/sonic-utilities/pull/893 to the 201911 branch

[201911][config] Support abbreviation

---

scripts/fast-reboot

Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>
Run warm-reboot CTs

Fixed warm-reboot for BFN platform

---

scripts/natshow

Updated the natshow script to get the nat type from newly added attribute.  
Addressing the issue - https://github.com/Azure/sonic-swss/issues/1234
Depends on :
https://github.com/Azure/sonic-swss/pull/1297
https://github.com/Azure/sonic-sairedis/pull/616
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

Updated natshow script to support DNAT Pool changes

---

scripts/db_migrator.py

Fix issue during warmboot from 201811 to 201911. (Issue - https://github.com/Azure/sonic-buildimage/issues/4589)
1. Migrate INTF table to have a default non-prefix entry 
`"INTF_TABLE:Vlan1000:192.168.0.1/21"`
to
```
"INTF_TABLE:Vlan1000"
"INTF_TABLE:Vlan1000:192.168.0.1/21"
```
2. Migrate 'lo' intf to 'Loopback0' interface 
`"INTF_TABLE:lo:10.1.0.32/32"`
to
`"INTF_TABLE:Loopback0:10.1.0.32/32"`
```
Jul  7 03:31:29.383159 str-acs-1 INFO db_migrator: Migrating lo entry to INTF_TABLE:Loopback0:FC00:1::32/128
Jul  7 03:31:29.383693 str-acs-1 INFO db_migrator: Migrating lo entry to INTF_TABLE:Loopback0:10.1.0.32/32
Jul  7 03:31:29.385589 str-acs-1 INFO db_migrator: Migrating intf table for PortChannel0003
Jul  7 03:31:29.386098 …
```

Intf table migration for APP_DB entries during warmboot

---

scripts/neighbor_advertiser

master branch PR: https://github.com/Azure/sonic-utilities/pull/1046

Add ip_prefix len based on proxy_arp status

---

scripts/teamshow

Why I did:-
Fix for show interface portchannel not working for single Asic platforms.
How I verify:
After fix show interface portchannel and sudo team show is fine on Single Asic Port-Channel.

[201911] Fix for show interface portchannel not working

---

fwutil/log.py

* Set min log priority to `INFO`
* N/A
1. `fwutil install chassis component <component_name> fw <fw_path> -y`
2. `fwutil update chassis component <component_name> fw -y`
```
root@sonic:/home/admin# tail -F /var/log/syslog | grep fwutil
```
```
root@sonic:/home/admin# tail -F /var/log/syslog | grep fwutil
Oct 26 09:43:37.906895 sonic INFO fwutil: Firmware install started: component=MSN3700C/BIOS, firmware=/home/admin/bios.bin
Oct 26 09:43:37.907493 sonic INFO fwutil: Firmware install ended: component=MSN3700C/BIOS, …
```

[fwutil]: Set min log priority to INFO

---

pfcwd/main.py

When ports are specified as option to 'pfcwd start', port validation fails on multi ASIC platform as the validation logic is executed on each ASIC namespace. Validation for valid ports fails as the port exits in only one namespace and not in others.
Fixed port validation logic for multi ASIC platform.
Changed logic to perform port validation after collecting ports from all namespaces. If port validation fails there is no config change on other valid ports.
Manual verification. (pytest does not support config change tests yet). Verified pytests for regression.
```
Before on Multi-ASIC (Ethernet0 is a valid port on ASIC0):
admin@str-nswitch-acs-2:~$ sudo pfcwd start --action drop --restoration-time 200 Ethernet0 200
Usage: pfcwd …
```

[CLI][pfcwd][start] Fix port validation issue when specifying port options in Multi ASIC platform

---

scripts/ecnconfig

fixes #1285
Fix ecnconfig with python 3 
Fix for python 3
root@sonic-dut:# ecnconfig -q 3 on
root@sonic-dut:#

Fix python3 issue in ecnconfig

---

doc/Command-Reference.md

Added "rif" subcommand to CLI reference guide
Edited command_reference.md file
N/A
N/A
N/A

Add "rif" subcommand description to interfaces counters

---

scripts/mellanox_buffer_migrator.py

To merge following https://github.com/Azure/sonic-buildimage/pull/6879 
Support new Mellanox system SN4600
Add the system name to the buffer migration script even if the system is first added
**- Which release branch to backport**
202012

[Mellanox] Add support for SN4600 system

---

acl_loader/main.py
sonic-utilities-tests/acl_input/acl1.json
sonic-utilities-tests/acl_input/icmp_bad_protocol_number.json
sonic-utilities-tests/acl_input/icmpv6_bad_protocol_number.json
sonic-utilities-tests/acl_input/tcp_bad_protocol_number.json
sonic-utilities-tests/acl_loader_test.py
sonic-utilities-tests/mock_tables/config_db.json

Ported https://github.com/Azure/sonic-utilities/pull/1479 to 201911.
Moved files from tests to sonic-utilities-tests.
Run unit tests + run ACL tests against 201911 image with this change and verify there is no regression.

[201911][acl-loader] Improve input validation for acl_loader

---

scripts/generate_dump
show/main.py

Merge changes from master
Manual merge.
```
admin@svcstr-nmasic-acs-1:~$ sudo show techsupport --help
Usage: show techsupport [OPTIONS]
Gather information for troubleshooting
Options:
--since TEXT                  Collect logs and core files since given date
-g, --global-timeout INTEGER  Global timeout in minutes. Default 30 mins
-c, --cmd-timeout INTEGER     Individual command timeout in minutes. Default
5 mins
--verbose                     Enable verbose output
--allow-process-stop          Dump additional data which may require system
interruption
--silent                      Run techsupport in silent mode
-?, -h, --help                Show this message and exit.
admin@svcstr-nmasic-acs-1:/var/dump$ ls -l
total 88536
-rw-r--r-- 1 root root 90660060 Feb 26 23:17 …
```

[CLI][techsupport] Merge 'show techsupport' changes from master

---

.azure-pipelines/build-docker-sonic-vs-template.yml
azure-pipelines.yml

install latest master version for swss/sairedis/swss-common to make sure 
packages version are aligned.

[ci]: use docker-sonic-vs from sonic-swss repo

---

setup.py

move the module to test requirement
bug introduced in #1393

[setup.py]: move the module to test requirement

---

config/main.py

Include EPMS in the check before starting PFCWD

Prevent starting PFCWD for EPMS devicetype

---

scripts/route_check.py
tests/route_check_test.py

1) Route check skip routes that are loopback. But if those entries has valid nexthop, they are not ignored from check.
2) The vrf routes are *not* handled by route_check.

route_check: Updates

---

counterpoll/main.py

Changed code to use use swsscommon instead of swsssdk in counterpoll
Removed an explicit function call from sdsssdk module
run counterpoll tests

Use swsscommon module instead of swsssdk ( swsssdk is deprecated)

---

scripts/neighbor_advertiser

Check for existing tunnels and use them if present while creating tunnel mappings
Modify the neighbor_advertiser script logic

[neighbor_advertiser] Use existing tunnel if present for creating tunnel mappings 

---

setup.py

Add soft-reboot to /usr/bin
Add soft-reboot to the script list for sonic-utilities.
See if soft-reboot is available on buildimage.

[201811]Add soft-reboot to script list to copy to /usr/bin

---

setup.py

Add soft-reboot to /usr/bin
Add soft-reboot to the script list for sonic-utilities.
See if soft-reboot is available on buildimage.

[201911] Add soft-reboot to script list to copy to /usr/bin

---

config/main.py

Restored cfggen sort method of json data and used it to
sort config db before saving.
closes: https://github.com/Azure/sonic-buildimage/issues/6328 
Restored cfggen sorting method
Tested on target

[config] Sort Config Db When Saving

---

scripts/natshow

Fixed undefined variable error for fetch_translation method, closes #1616 
```
admin@dut:~$ show nat translation                                                                                           
name 's' is not defined 
```
```
admin@dut:~$ show nat translation                                                                                           
Static NAT Entries         ..................... 0                                                                                  
Static NAPT Entries        ..................... 0                                                                                  
Dynamic NAT Entries        ..................... 0                                                                                  
Dynamic NAPT Entries …
```

[202012][natshow] Fix undefined variable error for fetch_translations

---

scripts/route_check.py
tests/route_check_test.py

[cherry-pick #1565]
Route check skip routes that are loopback. But if those entries has valid nexthop, they are not ignored from check.
The vrf routes are not handled by route_check.

route_check: Updates 

---

scripts/ipintutil
show/interfaces/__init__.py

swsssdk will be deprecated. Use swsscommon instead.

Replace swsssdk.ConfigDBConnector and SonicDBConfig with swsscommon implementation

---

config/main.py

Restored cfggen sort method of json data and used it to
sort config db before saving.

[202012][config] Sort Config Db When Saving (#1623)

---

show/bgp_quagga_v4.py
show/bgp_quagga_v6.py
show/main.py

Change to use rvtysh when calling the show commands
Merge code from master and fix code conflict, see #1572

[201811] Change to use rvtysh when calling the show commands

---

config/main.py

Fixes #1671 
Update the SONiC environment file during `config reload` before service restart

[config]: Update environment file during config reload

---

setup.py

Make the soft-reboot available in the SONiC image on master
Add soft-reboot to build package
Add "soft-reboot" to the package list of sonic-utility/setup.py
Build a SONiC image, load the image to DUT and check if soft-reboot is available.

Make the soft-reboot available in the SONiC image on master

---

sonic-utilities-tests/conftest.py

Change the method name to align with master, reduce diverge issue

Change the test method name to align with master

---

azure-pipelines.yml

- What I did
fix python gcov warning "Please install dotnet core to enable automatic generation of Html report"
more info check: https://github.com/Azure/sonic-snmpagent/pull/215
- How I did it
install dotnet core

[python coverage]Fix python coverage color bar

---

doc/Command-Reference.md

* Updated command reference to match `fwutil` v.2.0.0.0
* Updated command reference
* N/A
* N/A
* N/A

[doc][fwutil]: Update command reference: per component FW update

---

scripts/fdbshow

Fix typo in comment
Fix typo in comment
Read it

Fix typo in comment

---

setup.py

The script was added in the PR https://github.com/Azure/sonic-utilities/pull/1785 which did not add this script to the setup.py script.
Added the script to setup.py.

Add check_db_integrity script to setup.py

---

sfputil/main.py

Add support for CMIS-compliant QSFP modules
sfputil show eeprom

Enhance sfputil for CMIS QSFP

---

azure-pipelines.yml

Adapt for upstream target path change

[build] adapt for upstream target path change

---

show/bgp_frr_v4.py
show/bgp_frr_v6.py
utilities_common/bgp_util.py

port PR https://github.com/Azure/sonic-utilities/pull/1733 to 201911
UT and manual tests
Test log attached here
[show_ip_bgp_nw.log](https://github.com/Azure/sonic-utilities/files/7792025/show_ip_bgp_nw.log)

[201911] Fix "show ip bgp network"

---

config/main.py
doc/Command-Reference.md
tests/buffer_input/buffer_test_vectors.py
tests/buffer_test.py
tests/mock_tables/config_db.json
tests/mock_tables/state_db.json

Add CLI for configuring buffer profiles for queues
Run unit test to verify the logic
config interface buffer queue add <port> <queue-map> <profile>
config interface buffer queue set <port> <queue-map> <profile>
config interface buffer queue remove <port> <queue-map> <profile>

Support CLI for buffer queue configuration

---

config/feature.py
show/feature.py
sonic_package_manager/manager.py
tests/feature_test.py

Motivation for this change is to handle the TODO:
```
```
Implement blocking feature state change for CLI command and sonic-package-manager.
Implemented a wait loop that blocks till feature reaches desired state.
Run UT, run on switch.

[sonic-package-manager] implement blocking feature state change

---

azure-pipelines.yml

[ci] Fix python dependencies reference path.

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Cherry pick PRs https://github.com/Azure/sonic-swss/pull/2142, https://github.com/Azure/sonic-swss/pull/2138

[ci] pipeline fixes for VS test

---

azure-pipelines.yml

Enable diff coverage with 50% threshold

Set diff coverage 50% threashold

---

sonic-utilities-data/templates/timer.unit.j2

Add sonic-delayed.target to sonic-application-extension .timer file generator
This change will complete https://github.com/Azure/sonic-buildimage/pull/7846 of sonic-delayed.target addition.
N/A
make sure your App Ext is part of "WantedBy" sonic-delayed.target
N/A
N/A

Add sonic-delayed.target to Application Extension .timer file generator

---

azure-pipelines.yml

Change diff coverage threshold to 80%

Change diff coverage threshold to 80%

---

tests/route_check_test.py

Backport https://github.com/Azure/sonic-utilities/pull/2085 to 202111
Fix UT failed cause by change sonic_py_common to use swss_common
Fix UT failed cause by change sonic_py_common to use swss_common, here is UT failed message:
2022-02-28T09:26:11.4706067Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-28T09:26:11.4706457Z scripts/route_check.py:556: in main
2022-02-28T09:26:11.4706805Z     ret, res= check_routes()
2022-02-28T09:26:11.4707152Z scripts/route_check.py:491: in check_routes
2022-02-28T09:26:11.4707567Z     rt_appl_miss = filter_out_local_interfaces(rt_appl_miss)
2022-02-28T09:26:11.4708035Z scripts/route_check.py:352: in filter_out_local_interfaces
2022-02-28T09:26:11.4708494Z     chassis_local_intfs = …

[202111] Fix UT failed cause by change pycommon to use swsscommon (#2085)

---

config/main.py

Signed-off-by: Jing Kan jika@microsoft.com
https://github.com/Azure/sonic-utilities/pull/2206

[cherry-pick][201811][config/load_mgmt_config] Support load IPv6 mgmt IP (#2206)

---

doc/Command-Reference.md

Signed-off-by: kannankvs <kannan_kvs@dell.com>

Updated the CLI file for Radius and Linux kernel commands

---

azure-pipelines.yml

Transfer organization from Azure to sonic-net

Transfer organization from Azure to sonic-net

---

doc/Command-Reference.md

In the show bfd summary section, "show bgp summary" command should be "show bfd summary"
Changed "show bgp summary" to "show bfd summary"
Check Command-Reference.md

correct an error by changing "show bgp summary" to "show bfd summary"

---

sonic_installer/main.py
tests/swap_allocator_test.py

Signed-off-by: Xichen Lin <lukelin0907@gmail.com>
Consider preexisting swap when trying to enable swap before installing new image
Run script

[sonic_installer] consider swap checking memory

---

.github/workflows/bandit.yml

Support the bandit check by GitHub Action to find out the potential security issues in the python code.
Add the bandit check action in GitHub workflow
See the bandit test result: https://github.com/xumia/sonic-utilities/runs/8239964014?check_suite_focus=true
in the test PR: https://github.com/xumia/sonic-utilities/pull/1

Support the bandit check by GitHub Action

---

sonic_installer/main.py
tests/swap_allocator_test.py

Consider preexisting swap when setting up swap mem. The commits are cherry-picked from master.
Run tests

[202012][sonic_installer] consider existing swap when setting up swap mem

---

README.md

- The URL returned HTTP Error Code 404 (Not Found).

Fix broken pipeline build URL

---

config/plugins/auto_techsupport.py
scripts/coredump_gen_handler.py
scripts/memory_threshold_check.py
scripts/memory_threshold_check_handler.py
setup.py
show/plugins/auto_techsupport.py
tests/coredump_gen_handler_test.py
tests/memory_check_handler_test.py
tests/memory_threshold_check/config_db.json
tests/memory_threshold_check/state_db.json
tests/memory_threshold_check/state_db_2.json
tests/memory_threshold_check/state_db_3.json
tests/memory_threshold_check_test.py
utilities_common/auto_techsupport_helper.py

Backport of https://github.com/sonic-net/sonic-utilities/pull/2116
Implemented memory threashold check in auto techsupport feature according to https://github.com/Azure/SONiC/pull/939.
Added two scripts. The check script and the handler script. Few modifications made in auto tech implementation. UT added.
Run the action script and the handler script on the switch. Run UT.

[202205][auto-ts] add memory check (#2116)

---

doc/Command-Reference.md

Update sonic command doc to add CLIs relative to SONiC fips.
See https://github.com/sonic-net/SONiC/blob/master/doc/fips/SONiC-OpenSSL-FIPS-140-3.md

Update sonic command doc to add CLIs relative to SONiC fips

---

doc/Command-Reference.md
show/vnet.py
tests/mock_tables/appl_db.json
tests/mock_tables/state_db.json
tests/show_vnet_test.py

Original PR
https://github.com/sonic-net/sonic-utilities/pull/2341

[CLI] show vnet routes all. [202205]

---

doc/Command-Reference.md
show/vnet.py
tests/mock_tables/appl_db.json
tests/mock_tables/state_db.json
tests/show_bfd_test.py
tests/show_vnet_vxlan_cli_test.py

Orignal PR
https://github.com/sonic-net/sonic-utilities/pull/2342

[show] vnet endpoint [ip/ipv6] command [202205]

---

show/vnet.py
tests/mock_tables/appl_db.json
tests/mock_tables/state_db.json
tests/show_vnet_test.py

Parent PR
https://github.com/sonic-net/sonic-utilities/pull/2390
cherry-pick for 202012

[show] vnet advertised-route command [202012]

---

doc/Command-Reference.md

Signed-off-by: kannankvs <kannan_kvs@dell.com>
This PR is with reference to [PR#2435](https://github.com/sonic-net/sonic-utilities/pull/2435). Since the [PR#2435](https://github.com/sonic-net/sonic-utilities/pull/2435) has branch conflict. Raising this new PR. Will close the  [PR#2435](https://github.com/sonic-net/sonic-utilities/pull/2435) once this PR is merged.

resolved conflicts

---

show/main.py
tests/show_test.py

Pick up change from  https://github.com/sonic-net/sonic-utilities/pull/2537 .
Backport to 202012

[202012][show] Add bgpraw to show run all

---

azure-pipelines.yml

1. These 3 packages maybe purged by default. Do not block pipeline.
2. Download deb/whl packages only to accelerate download process.

[ci] Fix pipeline issue caused by sonic-slave-* change.

---

tests/route_check_test.py

The test fails with python3.7 (works in 3.9) when stopping patch which hasn't been started. We can always mock check_output call and if FRR_ROUTES is not defined return empty dictionary by the mock.
Removed check_frr_patch mock to fix UT running on python3.7
Removed the mock
Run unit test in stretch env

[route_check] remove check-frr_patch mock

---

doc/Command-Reference.md

Add the `aclshow` utility description to the User Manual document

[aclshow][user-manual] Add the aclshow utility description to the User Manual document

---

show/vnet.py
tests/mock_tables/appl_db.json
tests/mock_tables/state_db.json
tests/show_vnet_test.py
tests/show_vnet_vxlan_cli_test.py

Cherry-Pick https://github.com/sonic-net/sonic-utilities/pull/2644

[202205] Cli show vnet routes all fix 

---

tests/generic_config_updater/gcu_feature_patch_application_test.py

Add GCU UT coverage to ensure each step of patch sorting is valid 
Run UT

Add GCU UT Coverage

---

scripts/portstat

What I did:
Cherry-pick of PR: https://github.com/sonic-net/sonic-utilities/pull/2703/
Microsoft ADO: https://msazure.visualstudio.com/One/_workitems/edit/15760684
How I verify :
Manual Verification

Fix the show interface counters throwing exception on device with no external interfaces

---

azure-pipelines.yml

sonic-slave-buster updates some packages' version.
Use correct sonic-slave image to fix dependency issue.

[ci] Fix pipeline issue about sonic-slave container

---

azure-pipelines.yml

These 3 packages maybe purged by default. Do not block pipeline.

[ci] Fix pipeline issue caused by sonic-slave-* change. (#2709)

---

setup.py

Cherry pick PR:
* [build] Fix dependency issue between responses and urllib3 package.

[build] Fix dependency issue between responses and urllib3 package. (#2928)

---

show/main.py
tests/show_test.py
tests/syslog_input/rsyslog.conf

Reverts sonic-net/sonic-utilities#2947

Revert "Revert "[syslog] Add remote syslog configuration (cherry-pick to 202305)""

---

sonic-utilities-tests/mock_tables/asic4/config_db.json

Fixed UT error seen while integrating https://github.com/sonic-net/sonic-utilities/pull/2976
Added back missing ports in asic4 config_db.json file 
Full sonic-utilities build with the changes

[201911] [multi-asic] Unit test fix for internal link monitoring

---

config/vlan.py
tests/vlan_test.py

cherry-pick https://github.com/sonic-net/sonic-utilities/pull/2982

[202305] fix del vlan command

---

config/main.py
scripts/fast-reboot-filter-routes.py
tests/config_test.py
tests/fast_reboot_filter_routes_test.py

Update str -> list[str] in config/main and fast-reboot-filter-routes script
Add UT

Update str -> list[str] in config/main and fast-reboot-filter-routes script

---

azure-pipelines.yml
setup.py
sonic_package_manager/constraint.py
tests/debug_test.py

Update package dependencies and update code for Python 3.11 (in Bookworm).

Prepare for Bookworm upgrade

---

generic_config_updater/gcu_services_validator.conf.json
generic_config_updater/services_validator.py
tests/generic_config_updater/service_validator_test.py

Reverts sonic-net/sonic-utilities#2991
Test regression.

Revert "Remove syslog service validator in GCU"

---

setup.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/16788

Add six package required for bookworm

---

azure-pipelines.yml

use correct sonic-slave docker image for PR checker.

[ci] Use 202211 bullseye docker image instead of master branch.

---

azure-pipelines.yml

Use master branch's sonic-slave docker image will lead to build issue on release branches.
Use correct docker image according to source branch.

[ci] Use correct bullseye docker image according to source branch.

---

pytest.ini
scripts/generate_dump
setup.py
sonic_package_manager/constraint.py
tests/chassis_modules_test.py
tests/conftest.py
tests/debug_test.py
tests/decode_syseeprom_test.py
tests/mclag_test.py
tests/muxcable_test.py

This fixes 5 issues:
* Update tabulate to 0.9.0 and deepdiff to 6.2.2
* Specify test dependencies under `extra_requires`
* Add `check_output` parameter to the setup function due to the patch
* Fix error about having a mutable default for field headers in dataclass
* Fix test executions under Python 3.11 (done in #3041).

Update sonic-utilities for Bookworm

---

scripts/db_migrator.py
tests/db_migrator_input/appl_db/sflow_table_expected.json
tests/db_migrator_input/appl_db/sflow_table_input.json
tests/db_migrator_input/config_db/sflow_table_expected.json
tests/db_migrator_input/config_db/sflow_table_input.json
tests/db_migrator_test.py

Based on review comments from PR https://github.com/sonic-net/sonic-utilities/pull/2790, raised a separate PR for db_migrator changes as part of egress sFlow feature.
Recompile sonic-utilities bdist_wheel and verify pytest

[sflow][db_migrator] Egress Sflow support

---

scripts/db_migrator.py
tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_expected.json
tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_input.json
tests/db_migrator_input/config_db/portchannel-expected.json
tests/db_migrator_input/config_db/portchannel-input.json
tests/db_migrator_input/config_db/qos_map_table_expected.json
tests/db_migrator_input/config_db/qos_map_table_input.json
tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-double-pools-expected.json
tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-double-pools-input.json
tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-single-pool-expected.json
tests/db_migrator_input/config_db/reclaiming-buffer-dynamic-single-pool-input.json

Reverts sonic-net/sonic-utilities#3025

Revert "Run yang validation in unit test"

---

scripts/db_migrator.py

Add unit test for db_migrator.py: ConfigDB passing yang validation. Microsoft ADO: 24657445
Add yang validation for unit test, and fix test data to pass yang validation.
Run sonic-utilities end to end test.

Run yang validation in unit test

---

generic_config_updater/gcu_field_operation_validators.conf.json

Add all SKUs to the generic config update SKU list

[Mellanox] Add all SKUs to the generic config update SKU list

---

sfputil/main.py
tests/sfputil_test.py

manual cherry pick to 202305 for https://github.com/sonic-net/sonic-utilities/pull/3168, resolved conflicts

Fix sfputil CLI failure for multi-asic platforms

---

scripts/dualtor_neighbor_check.py
tests/dualtor_neighbor_check_test.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/17200
* Microsoft ADO (number only): 27317600
Upon advanced-reboot, the Lua script is flushed, so the EVALSHA command
might suffer from the script not-existed issue. Let's check if the
script exists before calling EVALSHA.
As the above.
UT and verify on dualtor testbed.

[dualtor_neighbor_check] Fix the script not exists issue

---

.azure-pipelines/pre-commit-check.yml
.pre-commit-config.yaml
azure-pipelines.yml

add precommit and flake8 to prevent syntax warning in python, e.g. https://github.com/sonic-net/sonic-buildimage/issues/18401
- initially, this check will be optional to verify its functionality, allowing developers to proceed even if it fails.
- if it performs as expected, this check will become mandatory in the future.
- use flake8 v4.0.1 in order to use diff only for PRs (flake8 with diff only is deprecated in v6.0.0 https://github.com/PyCQA/flake8/issues/1749
https://dev.azure.com/mssonic/build/_build/results?buildId=530004&view=logs&jobId=0cb31af1-9c12-5e3c-148e-856fdcff3a02

Add Precommit and flake8

---

config/plugins/mlnx.py

Update NVIDIA header date 
Changed the comment

[Mellanox] Update NVIDIA header for "config/plugins/mlnx.py" file

---

azure-pipelines.yml
setup.py

* [build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages
* [pipeline] Pin request package to v2.31.0

[cherry-pick][202311][build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages (#3328)

---

azure-pipelines.yml

[ci] Migrate ubuntu-20.04 agent pool to sonic-ubuntu-1c to fix S360 alert.

---

scripts/lldpshow
setup.py
tests/lldp_test.py
tests/mock_tables/config_db.json
utilities_common/general.py

… on multi-asic linecard
Modify the lldpshow script to fix the output of the "show lldp table"  and "show lldp neighbors" on the multi-asic Linecard.  Fixes  https://github.com/sonic-net/sonic-buildimage/issues/19209
After PR https://github.com/sonic-net/sonic-host-services/pull/120, lldp service is no longer enabled in localhost on the multi-asic Linecard.  To avoid the "show lldp table" command to access the lldp container which doesn't exist in the multi-asic linecard, this commit adds a new function get_feature_state_data() in the general.py to query the feature table to derive the globa_scope  and per_asic_scope value and modifies the lldpshow script to check if the lldp feature is enabled in scope before it is added to instance list for the show command.  Also fix the lldp_args list …

[chassis][mutli-asic][lldp] "show lldp table/neighbors" displays error message in output on multi-asis linecard.

---

scripts/db_migrator.py
tests/db_migrator_test.py

Update DB version to 202411_01 on master branch.
Changed db version to 202411_01 and updated comparison list in db_migrator_test.

Update DB version to 202411 on master branch.

---

generic_config_updater/gcu_field_operation_validators.conf.json

Backport https://github.com/sonic-net/sonic-utilities/pull/3368

[202405] [Mellanox] Add support for SN4280 platform

---

show/main.py
tests/ntp.conf
tests/show_test.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/20054
Ran UT's verified the output

[show] Fix ntp conf file path

---

azure-pipelines.yml

For the HTML code coverage report, .NET 6 or newer is needed. Install .NET 8 as it is the latest version currently.
Code coverage in the PR checker should have a proper HTML report with CSS styling, and there shouldn't be a warning saying .NET SDK wasn't found.

Update the .NET core version to 8.0

---

config/main.py

Reverts sonic-net/sonic-utilities#3583

Revert "Record and warn tables which not covered by YANG"

---

scripts/generate_dump

platform renaming for marvell teralynx platform.
innovium asictype checks are renamed to marvell-teralynx
run generate_dump script with the changes in both platforms and verified the outputs remains the same
NA
NA

[Marvell] platform renaming for innovium

---

scripts/route_check.py

Reverts sonic-net/sonic-utilities#3626

Revert "Fix typo in route_check_script"

---

scripts/route_check.py

Reverts sonic-net/sonic-utilities#3604

Revert "[202405]: Speed up route_check.py"

---

scripts/db_migrator.py

Update DB version to 202505
Modified current_version to 202505_01 branch for the next branch.

Update DB migrator script to next branch 202505

---

generic_config_updater/gu_common.py
tests/generic_config_updater/field_operation_validator_test.py

ADO: 30051071
Add a json patch check to avoid race condition issue when sonic consume ACL_TABLE and ACL_RULE together
Add a special dataacl check for specific change where ACL_TABLE type change with ACL_RULE update
unit test

[GCU] Add data acl table and rule check

---

scripts/db_migrator.py
tests/db_migrator_input/appl_db/tunnel_table_expected.json
tests/db_migrator_input/appl_db/tunnel_table_input.json
tests/db_migrator_input/config_db/tunnel_table_input.json
tests/db_migrator_test.py

Cherry-pick https://github.com/sonic-net/sonic-utilities/pull/3704 into 202405

[202405][db_migrator] Migrate tunnel table

---

show/interfaces/__init__.py

Adding namespace support for `show interfaces counters fec-histogram`
The code already provide option for namespace but is not using it. This PR will add the functionality for that
Single and Multi linecards device 
```
show interfaces counters fec-histogram -n asic0 Ethernet0
Port Ethernet0 not found in COUNTERS_PORT_NAME_MAP
Aborted!
```
```
show interfaces counters fec-histogram -n asic0 Ethernet0
Symbol Errors Per Codeword       Codewords
----------------------------  ------------
BIN0                          XXXXXXX
BIN1                                     0
BIN2                                     0
BIN3                                     0
BIN4                                     0
BIN5                                     0
BIN6                                     0
BIN7 …
```

feat: add namespace support for show interfaces counters fec-histogram

---

config/main.py
tests/config_override_input/multi_asic_dm_gen_sysinfo.json
tests/config_override_test.py

Fix empty asic_id for arista

---

scripts/pg-drop
tests/multi_asic_pgdropstat_test.py

Fix issue: pg-drop displayed value in wrong interface. Port oid and pg oid are unique within single asic, but not multi asic.
Update pg-drop UT: The output of Ethernet-BP256 should keep the same, between "pg-drop -c show -n asic1" and "pg-drop -c show".
Support duplicate oids in multi-asic for pg-drop cmd.
Save namespace info in self.counter_port_name_map and self.port_name_map.
Add namespace as input parameter when getting data from counter db.
Verified in T2 testbed.
```
cisco@r2-lc2:~$ ./pg-drop -c show -n asic1
Ingress PG dropped packets:
Port    PG0    PG1    PG2       PG3    PG4    PG5    PG6    PG7
--------------  -----  -----  -----  --------  -----  -----  -----  -----
Ethernet96      0      0      0         0      0      0      0      0
Ethernet104      0      0      0         0 …
```

Fix pg-drop cmd issue on multi-asic

---

generic_config_updater/gcu_field_operation_validators.conf.json

Add support for SN4280-O8C80 SKU in GCU
Verified GCU tests in sonic-mgmt

[Mellanox] Add GCU Support for SKU Mellanox-SN4280-O8C80

---

scripts/reboot_smartswitch_helper
tests/test_module.py
utilities_common/module.py

Change the pci_detach() and pci_rescan() calls to module_preshutdown and post_startup based on the new functions being added to module_base implementation

[Smartswitch][reboot] Addition of pre shutdown and post startup function calls 

---

scripts/generate_dump

Added sai.xml file from switch to sysdump
Copied sai.xml file to sai_sdk_dump folder in generate_dump file.
Verify the sai.xml file in sai_sdk_dump folder after generating sysdump using "show techsupport" command

[Mellanox] Collect sai.xml to sysdump

---

clear/main.py
show/main.py

Backport PR https://github.com/sonic-net/sonic-utilities/pull/3947
Backport the PR https://github.com/sonic-net/sonic-utilities/pull/3947 and fix the conflict manually

[202411] backport PR 3947 

---

generic_config_updater/gcu_field_operation_validators.conf.json
generic_config_updater/gu_common.py

Add support for the LodogaPrime product
- Added Arista-7050CX3-32C-C32 to TD3 broadcom_acics
- Added products to dup_lanes_platform

[Arista] Add support for LodogaPrime platform

---

clear/main.py
show/main.py

pick the https://github.com/sonic-net/sonic-utilities/pull/3981 to 202505

[202505] fix show bgp cli on multiple asic device

---

sonic_package_manager/database.py
sonic_package_manager/service_creator/creator.py
sonic_package_manager/source.py
tests/sonic_package_manager/conftest.py
tests/sonic_package_manager/test_database.py
tests/sonic_package_manager/test_manager.py

Reverts sonic-net/sonic-utilities#3998 to fix build issue.
Details in https://github.com/sonic-net/sonic-utilities/pull/3998

Revert "[SPM] Rename the variable tag to docker-image-reference"

---

doc/Command-Reference.md

Update doc to including dhcp_server ipv4 counter related CLI
Update doc to including dhcp_server ipv4 counter related CLI

[doc][dhcp_relay] Update doc to including dhcp_server ipv4 counter related CLI

---

generic_config_updater/gcu_field_operation_validators.conf.json

Add Arista 7800 platforms to GCU validator
Verified GCU tests pass on platforms

Add Arista 7800 platforms to GCU validator

---

scripts/fast-reboot

Add support for platforms based on Clounix net device
Add support for platforms based on Clounix net device
Verified on physical DUT

Support for platforms based on Clounix net device
